import { CourseMeta } from "./types";

export const ALGORITHMS_COURSE: CourseMeta = {
  id: "algorithms",
  title: "Algorithms",
  slug: "algorithms",
  subjectSlug: "algorithms",
  shortTitle: "Algorithms",
  icon: "⚙️",
  color: "bg-teal-400",
  tagline:
    "Master asymptotic analysis, Master Theorem, divide-and-conquer recurrences, greedy matroid optimality, dynamic programming memoization, graph traversals, shortest paths, and NP-completeness reductions.",
  description:
    "A rigorous, mathematically formal study notebook covering asymptotic growth hierarchies, recurrence trees, comparison sorting lower bounds, linear-time selection, Huffman coding, minimum spanning trees, 0/1 Knapsack, matrix chain multiplication, graph traversals, Dijkstra, Bellman-Ford, Floyd-Warshall, and Cook-Levin reduction chains for semester examinations and top-percentile GATE CS/IT & DA performance.",
  level: "Undergraduate / GATE CS & DA",
  estimatedHours: 48,
  prerequisites: [
    "Discrete Mathematics (proof by induction, recurrence relations, graph theory)",
    "Data Structures (arrays, linked lists, stacks, queues, binary heaps, trees)",
    "Elementary Calculus and Logarithmic properties",
  ],
  learningOutcomes: [
    "Formulate and evaluate asymptotic bounds using rigorous mathematical limit definitions and dominance rankings",
    "Solve complex recurrences using standard and extended Master Theorems, recursion trees, and change-of-variable techniques",
    "Prove the Omega(n log n) comparison sorting lower bound and implement linear-time sorting and selection algorithms",
    "Design optimal greedy algorithms using exchange arguments, the cut property, and priority queue optimizations",
    "Construct dynamic programming memoization tables with verified space-time complexity analysis",
    "Execute and analyze single-source and all-pairs shortest path algorithms and classify graph edges via DFS timestamps",
    "Formulate polynomial-time reductions to prove NP-completeness and categorize computational decision problems",
  ],
  gateScope: "GATE 2027 CS/IT + DA scope",
  gateBranches: ["cs", "da"],
  gateSyllabusTopics: [
    "Asymptotic analysis: Big-O, Omega, Theta, Little-o, Little-omega notations, order of growth hierarchy",
    "Recurrence relations: Substitution method, recursion trees, Master Theorem (standard and extended cases)",
    "Divide-and-Conquer: Merge Sort, Quick Sort (partition schemes, randomized expected time), linear-time selection (QuickSelect, Median-of-Medians)",
    "Sorting bounds and priority queues: Comparison sorting lower bound Omega(n log n), Counting Sort, Radix Sort, Bucket Sort, binary heaps, linear-time Build-Heap, Heap Sort",
    "Greedy algorithms: Greedy choice property, optimal substructure, Fractional Knapsack, Activity/Interval Selection, Huffman prefix codes",
    "Minimum Spanning Trees: Cut Property, Cycle Property, Kruskal with Disjoint Set Union (DSU), Prim's algorithm, uniqueness conditions",
    "Dynamic programming: Overlapping subproblems, 0/1 Knapsack (pseudo-polynomial time), Longest Common Subsequence (LCS), Longest Increasing Subsequence (LIS)",
    "Advanced dynamic programming: Matrix Chain Multiplication (Catalan number bounds), DP on DAGs, Held-Karp TSP",
    "Graph traversals and connectivity: Adjacency representations, BFS, DFS edge classification (tree, back, forward, cross), Topological Sort (Kahn's and DFS), Strongly Connected Components (Kosaraju, Tarjan)",
    "Shortest paths: BFS for unweighted graphs, DAG topological relaxation, Dijkstra with heaps, Bellman-Ford negative cycle detection, Floyd-Warshall APSP, Johnson's algorithm",
    "Computational complexity: Classes P, NP, co-NP, NP-Hard, NP-Complete, polynomial-time reductions, Cook-Levin theorem, classic NP-complete reductions",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: ASYMPTOTIC ANALYSIS & RECURRENCES
    // =========================================================================
    {
      id: "algo-module-1-asymptotics",
      title: "Module 1: Asymptotic Notations & Recurrences",
      slug: "asymptotic-analysis",
      description:
        "Formal mathematical definitions of Big-O, Omega, Theta, Little-o, Little-omega, limit quotients, dominance hierarchies, recurrence trees, and standard/extended Master Theorem cases.",
      order: 1,
      lessons: [
        {
          id: "asymptotic-notations-and-complexity-bounds",
          title: "Asymptotic Bounds, Order of Growth & Growth Hierarchy",
          slug: "asymptotic-notations-and-complexity-bounds",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Formal definitions of O, Omega, Theta, o, omega, limit tests, Stirling's approximation, and dominance ranking.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "f(n) = Theta(g(n)) iff 0 < lim_{n -> inf} [f(n) / g(n)] < inf. If ratio is 0 => f(n) = o(g(n)). If ratio is inf => f(n) = omega(g(n)).",
            keyFormulasAndRules: [
              "Big-O (Upper Bound): 0 <= f(n) <= c * g(n) for all n >= n0.",
              "Big-Omega (Lower Bound): 0 <= c * g(n) <= f(n) for all n >= n0.",
              "Big-Theta (Tight Bound): 0 <= c1 * g(n) <= f(n) <= c2 * g(n) for all n >= n0.",
              "Little-o (Strict Upper Bound): lim_{n -> inf} [f(n) / g(n)] = 0.",
              "Little-omega (Strict Lower Bound): lim_{n -> inf} [f(n) / g(n)] = inf.",
              "Growth Hierarchy: 1 < log(log n) < log n < (log n)^k < n^epsilon < sqrt(n) < n < n log n < n^2 < n^k < 2^(sqrt(n)) < 2^n < 3^n < n! < n^n.",
              "Stirling's Formula: n! approx sqrt(2 * pi * n) * (n / e)^n => log(n!) = Theta(n log n).",
            ],
            examPitfalls: [
              "f(n) = O(g(n)) DOES NOT imply 2^{f(n)} = O(2^{g(n)}). Counterexample: f(n) = 2n, g(n) = n. 2^{2n} = 4^n != O(2^n).",
              "Little-o and Little-omega are NOT reflexive: f(n) != o(f(n)) and f(n) != omega(f(n)).",
              "log(n!) = Theta(n log n), but n! = o(n^n) because (n/e)^n grows strictly slower than n^n.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Formal Set-Theoretic Definitions of Asymptotic Notations",
              body: [
                "In algorithmic analysis, asymptotic notations quantify the limiting behavior of execution time or memory footprint as input size `n` tends to infinity, abstracting away hardware-specific machine constants.",
                "**1. Big-O Notation (Asymptotic Upper Bound):**",
                "`O(g(n)) = { f(n) : exists c > 0, n_0 > 0 text{ such that } 0 <= f(n) <= c * g(n), forall n >= n_0 }`",
                "**2. Big-Omega Notation (Asymptotic Lower Bound):**",
                "`Omega(g(n)) = { f(n) : exists c > 0, n_0 > 0 text{ such that } 0 <= c * g(n) <= f(n), forall n >= n_0 }`",
                "**3. Big-Theta Notation (Asymptotically Tight Bound):**",
                "`Theta(g(n)) = { f(n) : exists c_1 > 0, c_2 > 0, n_0 > 0 text{ such that } 0 <= c_1 * g(n) <= f(n) <= c_2 * g(n), forall n >= n_0 }`",
                "Theorem: `f(n) = Theta(g(n))` if and only if `f(n) = O(g(n))` and `f(n) = Omega(g(n))`.",
                "**4. Strict Bounds (Little-o and Little-omega):**",
                "`o(g(n)) = { f(n) : forall c > 0, exists n_0 > 0 text{ such that } 0 <= f(n) < c * g(n), forall n >= n_0 }`",
                "`omega(g(n)) = { f(n) : forall c > 0, exists n_0 > 0 text{ such that } 0 <= c * g(n) < f(n), forall n >= n_0 }`",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Limit Quotient Criterion & Growth Hierarchy",
              body: [
                "When comparing continuous differentiable functions, L'Hopital's rule on the limit ratio `L = lim_{n -> inf} [f(n) / g(n)]` resolves dominance instantly:",
                "- If `L = 0`, then `f(n) = o(g(n))` and `f(n) = O(g(n))`, but `f(n) != Theta(g(n))`.",
                "- If `0 < L < inf`, then `f(n) = Theta(g(n))`, `f(n) = O(g(n))`, and `f(n) = Omega(g(n))`.",
                "- If `L = inf`, then `f(n) = omega(g(n))` and `f(n) = Omega(g(n))`, but `f(n) != O(g(n))`.",
                "- If `L` oscillates and does not exist (e.g. `n^(1 + sin n)` vs `n`), limit test is inconclusive; one must resort to definitions.",
                "**The Canonical Growth Hierarchy:**",
                "`1 prec log(log n) prec log n prec sqrt(log n) prec (log n)^k prec n^epsilon prec sqrt(n) prec n prec n log n prec n^2 prec n^k prec 2^(sqrt(n)) prec 2^n prec 3^n prec n! prec n^n`",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Asymptotic Ranking of Non-Trivial Functions",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "When comparing exponential forms, take the base-2 logarithm of each function to compare exponents, but remember that f(n) < g(n) does not always mean log f(n) < log g(n) with the same asymptotic separation unless differences are polynomial.",
              solutionSteps: [
                "Problem: Arrange the following four functions in strictly increasing order of asymptotic growth rate:",
                "  f1(n) = 2^{2^{log_2(log_2 n)}}",
                "  f2(n) = n^{log_2 n}",
                "  f3(n) = (log_2 n)^n",
                "  f4(n) = 2^{sqrt{n}}",
                "Step 1: Simplify f1(n):",
                "  Recall 2^{log_2 x} = x. Thus 2^{log_2(log_2 n)} = log_2 n.",
                "  Therefore, f1(n) = 2^{log_2 n} = n. So f1(n) = Theta(n).",
                "Step 2: Express remaining functions in base-2 exponential form 2^{g(n)}:",
                "  f2(n) = n^{log_2 n} = (2^{log_2 n})^{log_2 n} = 2^{(log_2 n)^2}.",
                "  f3(n) = (log_2 n)^n = (2^{log_2(log_2 n)})^n = 2^{n log_2(log_2 n)}.",
                "  f4(n) = 2^{sqrt{n}} = 2^{n^{0.5}}.",
                "Step 3: Compare exponents of f2(n), f4(n), and f3(n):",
                "  Exponent of f2: e2(n) = (log_2 n)^2.",
                "  Exponent of f4: e4(n) = n^{0.5} = sqrt{n}.",
                "  Exponent of f3: e3(n) = n log_2(log_2 n).",
                "  Comparing e2(n) vs e4(n): Any positive polynomial n^epsilon dominates polylogarithmic powers (log n)^k.",
                "  Here n^{0.5} asymptotically dominates (log_2 n)^2. Thus e2(n) = o(e4(n)), meaning 2^{(log_2 n)^2} = o(2^{sqrt{n}}).",
                "  Comparing e4(n) vs e3(n): n^{0.5} is strictly smaller than n log_2(log_2 n). Thus e4(n) = o(e3(n)).",
                "Step 4: Establish complete order:",
                "  f1(n) = n = 2^{log_2 n}",
                "  Exponents in increasing order: log_2 n << (log_2 n)^2 << n^{0.5} << n log_2(log_2 n).",
                "  Final verified ranking: f1(n) < f2(n) < f4(n) < f3(n).",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 3: Growth of Functions, formal definitions and bounding properties.",
                },
              ],
            },
          ],
        },
        {
          id: "master-theorem-and-recurrences",
          title: "Master Theorem, Recurrences & Advanced Recurrence Solvers",
          slug: "master-theorem-and-recurrences",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Comparing f(n) with n^{log_b a}, extended Master cases, substitution proofs, and change of variables.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "For T(n) = a*T(n/b) + f(n), compare f(n) with the critical exponent n^{log_b a}.",
            keyFormulasAndRules: [
              "Case 1 (Leaves Dominate): If f(n) = O(n^{log_b a - epsilon}) for epsilon > 0 => T(n) = Theta(n^{log_b a}).",
              "Case 2 (Even Balance): If f(n) = Theta(n^{log_b a} * log^k n) for k >= 0 => T(n) = Theta(n^{log_b a} * log^{k+1} n).",
              "Case 2 Extended: If f(n) = Theta(n^{log_b a} / log n) (k = -1) => T(n) = Theta(n^{log_b a} * log(log n)).",
              "Case 3 (Root Dominates): If f(n) = Omega(n^{log_b a + epsilon}) AND regularity condition a*f(n/b) <= c*f(n) for c < 1 => T(n) = Theta(f(n)).",
              "Square Root Recurrences: T(n) = 2T(sqrt(n)) + 1 => let n = 2^m => S(m) = 2S(m/2) + 1 => Theta(log n).",
            ],
            examPitfalls: [
              "Master Theorem FAILS when: a is not constant, b <= 1, or difference between f(n) and n^{log_b a} is not polynomial (e.g., T(n) = 2T(n/2) + n/log n cannot use Case 1 or 3).",
              "In Case 3, regularity condition MUST be verified; without it, Master Theorem does not apply.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Divide-and-Conquer Recurrence Framework",
              body: [
                "The classic divide-and-conquer recurrence has the form: `T(n) = a * T(n/b) + f(n)`, where:",
                "- `a >= 1`: Number of recursive subproblems generated at each step.",
                "- `b > 1`: Subproblem size reduction factor (each subproblem has size `n/b`).",
                "- `f(n)`: Time required to divide the input and combine the subproblem outputs.",
                "**The Recursion Tree Model:**",
                "At depth `j` of the recursion tree, there are `a^j` subproblems, each of size `n / b^j`. The work at depth `j` is `a^j * f(n / b^j)`. The total tree depth is `log_b n`. The number of leaves at the bottom level is `a^{log_b n} = n^{log_b a}`.",
                "The overall solution is dictated by the race between leaf work (`n^{log_b a}`) and root work (`f(n)`).",
              ],
            },
            {
              type: "explanation",
              heading: "2. Extended Master Theorem & Non-Standard Transformations",
              body: [
                "Standard Master Theorem requires a polynomial gap `n^epsilon` between `f(n)` and `n^{log_b a}`. When `f(n)` differs only by logarithmic factors, the extended theorem applies:",
                "If `f(n) = Theta(n^{log_b a} * log^k n)`:",
                "1. If `k > -1`: `T(n) = Theta(n^{log_b a} * log^{k+1} n)`.",
                "2. If `k = -1`: `T(n) = Theta(n^{log_b a} * log(log n))`.",
                "3. If `k < -1`: `T(n) = Theta(n^{log_b a})`.",
                "**Change of Variables (Domain Transformation):**",
                "For recurrences involving fractional powers like `T(n) = 2T(sqrt(n)) + log n`:",
                "Substitute `n = 2^m` (so `m = log_2 n` and `sqrt(n) = 2^{m/2}`).",
                "Define `S(m) = T(2^m)`. Then `S(m) = 2S(m/2) + m`. Apply Master Theorem to `S(m)`: `a=2, b=2, m^{log_2 2} = m^1`. Case 2 applies: `S(m) = Theta(m log m)`. Substituting back `m = log_2 n`: `T(n) = Theta(log n * log(log n))`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Multi-Factor Extended Recurrence",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Do not confuse Case 1 with Case 2 when logarithmic terms multiply n^{log_b a}. Even if k > 0, if the base power is n^{log_b a}, it belongs strictly to Case 2.",
              solutionSteps: [
                "Problem: Find the asymptotically tight bound for T(n) = 4 * T(n/2) + n^2 * (log_2 n)^2, with T(1) = Theta(1).",
                "Step 1: Identify parameters: a = 4, b = 2, f(n) = n^2 * (log_2 n)^2.",
                "Step 2: Compute critical exponent: n^{log_b a} = n^{log_2 4} = n^2.",
                "Step 3: Compare f(n) with n^{log_b a}:",
                "  f(n) = n^2 * (log_2 n)^2 = Theta(n^2 * log^k n) where k = 2.",
                "Step 4: Check applicability:",
                "  Since f(n) is of the form Theta(n^{log_b a} * log^k n) with k = 2 >= 0, Extended Case 2 applies directly.",
                "Step 5: Apply formula:",
                "  T(n) = Theta(n^{log_b a} * log^{k+1} n)",
                "  T(n) = Theta(n^2 * log^{2+1} n) = Theta(n^2 * log^3 n).",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 4: Divide-and-Conquer and Master Theorem proofs.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: DIVIDE-AND-CONQUER, SORTING BOUNDS & HEAPS
    // =========================================================================
    {
      id: "algo-module-2-sorting-selection",
      title: "Module 2: Sorting, Selection & Priority Queues",
      slug: "sorting-and-selection",
      description:
        "Merge Sort inversion counting, Lomuto vs Hoare partitions, randomized quicksort expected bounds, deterministic median-of-medians linear selection, decision tree lower bounds, non-comparison sorting, and binary heap mathematics.",
      order: 2,
      lessons: [
        {
          id: "divide-and-conquer-and-sorting",
          title: "Merge Sort, Quick Sort & Linear-Time Selection",
          slug: "divide-and-conquer-and-sorting",
          order: 1,
          estimatedMinutes: 36,
          tagline: "Inversion counting, Hoare vs Lomuto partitions, randomized quicksort expected O(n log n), and BFPRT Median-of-Medians.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Merge Sort: Always Theta(n log n), stable, O(n) space. Quick Sort: O(n log n) expected, O(n^2) worst case, in-place, unstable.",
            keyFormulasAndRules: [
              "Merge Sort Inversion Counting: Number of pairs (i, j) with i < j and A[i] > A[j] computed in O(n log n) during merge step.",
              "Quick Sort Worst Case: Occurs when partition is maximally unbalanced (0 : n-1 split at every level), yielding T(n) = T(n-1) + Theta(n) = O(n^2).",
              "Randomized Quick Sort: Expected comparisons E[C] = 2n ln n + O(n) = Theta(n log n) for ANY input array.",
              "QuickSelect (Hoare): Average time O(n), worst case O(n^2).",
              "Median-of-Medians (BFPRT): Groups of 5 guarantee worst-case T(n) <= T(n/5) + T(7n/10) + O(n) = O(n). Groups of 3 fail (yield O(n log n)).",
            ],
            examPitfalls: [
              "Lomuto partition uses the last element as pivot and makes more swaps than Hoare partition; Hoare uses two converging pointers.",
              "Even an extreme 99:1 unbalanced split at every level still yields Theta(n log n) running time because recursion tree depth is log_{100/99} n = O(log n).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Merge Sort Mechanics & Inversion Counting",
              body: [
                "Merge Sort recursively divides the array into two halves, sorts each half, and merges the sorted sublists in linear time:",
                "`T(n) = 2T(n/2) + Theta(n) = Theta(n log n)` in Best, Average, and Worst cases.",
                "**Inversion Counting:**",
                "An inversion is a pair `(i, j)` such that `i < j` but `A[i] > A[j]`. A completely reverse-sorted array of size `n` has `n(n - 1) / 2` inversions.",
                "During the merge step of two sorted subarrays `Left[0..p]` and `Right[0..q]`, whenever an element `Right[j]` is smaller than `Left[i]`, it is smaller than all remaining elements in `Left` (`Left[i..p]`). Hence, exactly `(p - i + 1)` inversions are contributed. This counts all inversions in `O(n log n)` time.",
              ],
            },
            {
              type: "explanation",
              heading: "2. QuickSort Partition Analysis & Deterministic Linear Selection",
              body: [
                "QuickSort selects a pivot element and partitions array `A[p..r]` into two subarrays such that elements in `A[p..q-1] <= A[q]` and elements in `A[q+1..r] >= A[q]`.",
                "**Expected Analysis of Randomized QuickSort:**",
                "Let `z_1 < z_2 < ... < z_n` be sorted elements. Any two elements `z_i` and `z_j` are compared at most once, and are compared if and only if either `z_i` or `z_j` is chosen as pivot before any element in `{z_{i+1}, ..., z_{j-1}}`. The probability of this event is `2 / (j - i + 1)`. Total expected comparisons:",
                "`E[X] = sum_{i=1}^{n-1} sum_{j=i+1}^n frac{2}{j - i + 1} = sum_{i=1}^{n-1} sum_{k=2}^{n - i + 1} frac{2}{k} <= 2n sum_{k=1}^n frac{1}{k} = 2n ln n + O(n) = Theta(n log n)`.",
                "**Median-of-Medians (BFPRT Selection):**",
                "To guarantee `O(n)` worst-case selection of the `k`-th order statistic:",
                "1. Divide `n` elements into `lfloor n/5 rfloor` groups of 5.",
                "2. Find the median of each group (takes `O(1)` per group, total `O(n)`).",
                "3. Recursively find the median of the medians, `x` (takes `T(n/5)`).",
                "4. Partition array around `x`. At least `3 * (1/2 * n/5) = 3n/10` elements are `<= x`, and at least `3n/10` elements are `>= x`. Thus, the recursive subproblem on either side has size at most `7n/10`.",
                "5. Recurrence: `T(n) <= T(n/5) + T(7n/10) + c * n`. Since `1/5 + 7/10 = 9/10 < 1`, `T(n) = O(n)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Partition Comparisons & Worst-Case Depth",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Remember that in Hoare's partition, the pivot is not necessarily placed at its final sorted position after one partition call; it merely separates the array into <= pivot and >= pivot segments.",
              solutionSteps: [
                "Problem: An array A contains n distinct elements. QuickSort is executed using the deterministic median-of-medians algorithm to select the pivot at each step. Find the recurrence for the number of comparisons C(n) and prove that C(n) = O(n log n) or O(n).",
                "Step 1: Formulate the recurrence components:",
                "  - Finding medians of groups of 5: For each group of 5, finding median requires at most 7 comparisons. Total = 7 * (n/5) = 1.4 n comparisons.",
                "  - Recursive call to find median of medians x: C(n/5).",
                "  - Partitioning array around x: Exactly n - 1 comparisons.",
                "  - Selection recurses on at most 7n/10 elements: T(7n/10).",
                "Step 2: Combine terms for full QuickSort (sorting, not selection):",
                "  T(n) = T(k) + T(n - k) + C_partition(n) + T_pivot_selection(n).",
                "  With BFPRT pivot selection, 3n/10 <= k <= 7n/10.",
                "  The worst-case split is 3n/10 and 7n/10.",
                "  T(n) = T(3n/10) + T(7n/10) + O(n).",
                "Step 3: Solve via recursion tree:",
                "  At each depth, work is (3/10 + 7/10) n = n.",
                "  Maximum depth of tree: log_{10/7} n = O(log n).",
                "  Total time = Depth * Work per level = O(n log n) guaranteed worst case!",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 7: Quicksort, and Chapter 9: Medians and Order Statistics.",
                },
              ],
            },
          ],
        },
        {
          id: "sorting-lower-bounds-and-linear-sorting",
          title: "Sorting Bounds, Non-Comparison Sorting & Binary Heaps",
          slug: "sorting-lower-bounds-and-linear-sorting",
          order: 2,
          estimatedMinutes: 34,
          tagline: "Omega(n log n) decision tree bound, Counting/Radix/Bucket sort, linear-time Build-Heap, and Heap Sort.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Any comparison sort requires Omega(n log n) worst-case comparisons. Non-comparison sorts (Counting, Radix) achieve O(n) by using key values as indices.",
            keyFormulasAndRules: [
              "Decision Tree Lower Bound: Height h >= ceil(log2(n!)) = Omega(n log n).",
              "Counting Sort: Time Theta(n + k), space Theta(n + k). Stable when traversed right-to-left.",
              "Radix Sort: Time Theta(d * (n + b)) where d is number of digits in base b. Requires stable sub-sort.",
              "Bucket Sort: Expected time O(n) when input is uniformly distributed over [0, 1).",
              "Binary Max-Heap: Complete binary tree in array. Parent = floor(i/2), Left = 2i, Right = 2i+1.",
              "Build-Max-Heap: Runs in strictly O(n) linear time, NOT O(n log n), because sum_{h=0}^inf (h / 2^h) = 2.",
              "Heap Sort: In-place, O(n log n) best/average/worst, unstable.",
            ],
            examPitfalls: [
              "Build-Heap is O(n), but inserting n elements one-by-one into an initially empty heap takes O(n log n).",
              "Radix Sort is NOT comparison-based; it does not violate the Omega(n log n) lower bound.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Decision Tree Lower Bound for Comparison Sorting",
              body: [
                "In a comparison sort, we only gain information about the input sequence `(a_1, a_2, ..., a_n)` by pairwise comparisons `a_i <= a_j`.",
                "A decision tree models the execution of any comparison sort on `n` inputs:",
                "- Each internal node represents a comparison `a_i : a_j`.",
                "- Each leaf represents a unique permutation of the input elements.",
                "Since any of the `n!` permutations could be the correct sorted order, the tree must contain at least `n!` reachable leaves (`L >= n!`).",
                "A binary tree of height `h` has at most `2^h` leaves. Therefore:",
                "`2^h >= L >= n! implies h >= log_2(n!)`",
                "Using Stirling's approximation (`n! >= (n/e)^n`):",
                "`h >= log_2((n / e)^n) = n log_2 n - n log_2 e = Omega(n log n)`.",
                "Hence, any comparison sort requires at least `Omega(n log n)` comparisons in the worst case.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Mathematical Proof of Linear-Time Build-Heap",
              body: [
                "A common misconception is that building a heap of `n` elements takes `O(n log n)` because each `Max-Heapify` call takes `O(log n)` on `n/2` nodes.",
                "The key insight is that most nodes in a heap are close to the leaves and have very small heights `h`:",
                "- An `n`-element heap has height `lfloor log_2 n rfloor`.",
                "- At height `h`, there are at most `lceil n / 2^{h+1} rceil` nodes.",
                "- Calling `Max-Heapify` on a node of height `h` takes `O(h)` time.",
                "Total time to build the heap:",
                "`T(n) <= sum_{h=0}^{lfloor log_2 n rfloor} lceil frac{n}{2^{h+1}} rceil * O(h) <= c * n * sum_{h=0}^infty frac{h}{2^h}`",
                "Evaluating the infinite series `S = sum_{h=0}^infty frac{h}{2^h}`:",
                "`S = 1/2 + 2/4 + 3/8 + 4/16 + ...`",
                "`S/2 = 1/4 + 2/8 + 3/16 + ...`",
                "`S - S/2 = S/2 = 1/2 + 1/4 + 1/8 + ... = 1 implies S = 2`.",
                "Therefore: `T(n) <= c * n * (2) = O(n)`. Building a binary heap takes strictly linear time!",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Maximum Swaps in Build-Heap",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Heapify operates top-down from index floor(n/2) down to 1. Count height from leaves (leaves are height 0).",
              solutionSteps: [
                "Problem: For an array of size n = 15 arranged in strictly ascending order, calculate the maximum number of element swaps performed by Build-Max-Heap.",
                "Step 1: Characterize tree structure for n = 15:",
                "  Complete binary tree of 4 levels (perfect binary tree):",
                "  - Height 0 (leaves): 8 nodes (indices 8 to 15). Heapify does 0 swaps.",
                "  - Height 1: 4 nodes (indices 4, 5, 6, 7). Each can swap at most 1 time.",
                "  - Height 2: 2 nodes (indices 2, 3). Each can swap at most 2 times.",
                "  - Height 3 (root): 1 node (index 1). Can swap at most 3 times.",
                "Step 2: Ascending array worst-case scenario:",
                "  Because array is ascending, parent elements are smaller than all descendants.",
                "  Every non-leaf node will trickle down to the leaf level.",
                "Step 3: Calculate total swaps:",
                "  Total swaps = (4 * 1) + (2 * 2) + (1 * 3) = 4 + 4 + 3 = 11 swaps.",
                "Final Answer: Exactly 11 swaps are performed.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 6: Heapsort, and Chapter 8: Sorting in Linear Time.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: GREEDY STRATEGIES & DYNAMIC PROGRAMMING
    // =========================================================================
    {
      id: "algo-module-3-greedy-dp",
      title: "Module 3: Greedy Strategies & Dynamic Programming",
      slug: "greedy-and-dp",
      description:
        "Greedy choice property, exchange arguments, Huffman coding, minimum spanning trees (Kruskal with DSU, Prim), 0/1 Knapsack pseudo-polynomial bounds, LCS, LIS, and Matrix Chain Multiplication parenthesizations.",
      order: 3,
      lessons: [
        {
          id: "greedy-algorithms-and-matroids",
          title: "Greedy Choice, Huffman Coding & Interval Scheduling",
          slug: "greedy-algorithms-and-matroids",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Optimal substructure vs greedy-choice property, activity selection, and Huffman prefix codes.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Greedy algorithms make locally optimal choices. Correctness requires proving both the Greedy Choice Property (via exchange argument) and Optimal Substructure.",
            keyFormulasAndRules: [
              "Activity Selection: Sort by finish time f_i in ascending order. Pick next compatible activity. Time O(n log n).",
              "Fractional Knapsack: Sort items by value density (v_i / w_i) in descending order. Greedy achieves optimal in O(n log n).",
              "Huffman Tree Structure: For n alphabet symbols, Huffman generates a strictly full binary tree with n leaves and n - 1 internal nodes (total 2n - 1 nodes).",
              "Average Huffman Length: L = sum_{i=1}^n f_i * length(c_i).",
              "Optimality of Huffman: No prefix-free binary code can achieve smaller expected length than Huffman code.",
            ],
            examPitfalls: [
              "Greedy strategy FAILS for 0/1 Knapsack because items cannot be divided; taking the highest v_i / w_i item can preclude taking two items of greater combined value.",
              "Huffman tree is NOT unique (ties in frequency produce different tree shapes), but the optimal expected bit length is strictly invariant.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Greedy Framework & Exchange Arguments",
              body: [
                "A problem exhibits **Greedy-Choice Property** if a globally optimal solution can be arrived at by making a locally optimal (greedy) choice.",
                "**The Exchange Argument Proof Technique:**",
                "1. Let `G` be the greedy solution, and let `O` be an arbitrary optimal solution.",
                "2. If `G = O`, greedy is optimal.",
                "3. If `G != O`, consider the first point where `G` and `O` differ.",
                "4. Show that modifying `O` by exchanging its choice with the greedy choice produces another valid solution `O'` whose objective value is at least as good as `O` (`text{value}(O') >= text{value}(O)`).",
                "5. By induction, `O` can be transformed into `G` without reducing value. Hence `G` is optimal.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Huffman Coding: Prefix Codes & Tree Properties",
              body: [
                "A **prefix-free code** is a code in which no codeword is a prefix of any other codeword. Prefix codes are uniquely decodable without delimiters.",
                "Huffman's algorithm constructs an optimal prefix code using a min-priority queue:",
                "1. Initialize `n` single-node trees, each labeled with symbol frequency `f_i`.",
                "2. Extract the two minimum frequency trees `T_1` and `T_2`.",
                "3. Merge them into a parent node with frequency `f_1 + f_2`.",
                "4. Repeat until a single tree remains.",
                "Running time: `O(n log n)` with binary min-heap.",
                "**Properties of Huffman Trees:**",
                "- Every internal node has exactly 2 children (strictly full binary tree).",
                "- The two least frequent characters are siblings at the maximum depth of the tree.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Huffman Tree Construction & Compression Ratio",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Remember that the two lowest frequencies MUST be merged first. When merging two subtrees, their combined weight must be re-inserted into the candidate set.",
              solutionSteps: [
                "Problem: A file contains 5 characters with frequencies: A (0.40), B (0.25), C (0.15), D (0.10), E (0.10). Construct the optimal Huffman code and find the expected code length.",
                "Step 1: Priority Queue iterations:",
                "  Initial: {D: 0.10, E: 0.10, C: 0.15, B: 0.25, A: 0.40}",
                "  Iteration 1: Merge D(0.10) and E(0.10) => DE(0.20). Set: {C: 0.15, DE: 0.20, B: 0.25, A: 0.40}",
                "  Iteration 2: Merge C(0.15) and DE(0.20) => CDE(0.35). Set: {B: 0.25, CDE: 0.35, A: 0.40}",
                "  Iteration 3: Merge B(0.25) and CDE(0.35) => BCDE(0.60). Set: {A: 0.40, BCDE: 0.60}",
                "  Iteration 4: Merge A(0.40) and BCDE(0.60) => Root(1.00).",
                "Step 2: Assign bit lengths from tree depth:",
                "  A: depth 1 => length = 1 bit (code '0')",
                "  B: depth 2 => length = 2 bits (code '10')",
                "  C: depth 3 => length = 3 bits (code '110')",
                "  D: depth 4 => length = 4 bits (code '1110')",
                "  E: depth 4 => length = 4 bits (code '1111')",
                "Step 3: Compute expected bits per symbol L:",
                "  L = (0.40 * 1) + (0.25 * 2) + (0.15 * 3) + (0.10 * 4) + (0.10 * 4)",
                "  L = 0.40 + 0.50 + 0.45 + 0.40 + 0.40 = 2.15 bits/symbol.",
                "Step 4: Compare with fixed-length encoding:",
                "  5 symbols require ceil(log_2 5) = 3 bits/symbol.",
                "  Compression savings = (3 - 2.15) / 3 = 0.85 / 3 = 28.33%.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Algorithm Design",
                  authors: "Jon Kleinberg, Éva Tardos",
                  year: "2006",
                  publisher: "Pearson",
                  relevance: "Chapter 4: Greedy Algorithms, interval scheduling and Huffman codes.",
                },
              ],
            },
          ],
        },
        {
          id: "minimum-spanning-trees",
          title: "Minimum Spanning Trees: Kruskal, Prim & Cut Properties",
          slug: "minimum-spanning-trees",
          order: 2,
          estimatedMinutes: 34,
          tagline: "Cut Property, Cycle Property, Kruskal with DSU, Prim with priority queues, and uniqueness theorems.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Cut Property: The strictly light edge crossing any cut belongs to every MST. Cycle Property: The strictly heaviest edge in any cycle cannot belong to any MST.",
            keyFormulasAndRules: [
              "MST Weight Uniqueness: If all edge weights in G are distinct, G has a UNIQUE minimum spanning tree.",
              "Kruskal's Algorithm: Sort edges O(E log E) + Disjoint Set Union (union-by-rank, path compression) O(E * alpha(V)). Overall O(E log V).",
              "Prim's Algorithm: Grows a single tree. Time O(V^2) with matrix, O((V + E) log V) with binary heap, O(E + V log V) with Fibonacci heap.",
              "Inverse Ackermann Function: alpha(V) <= 4 for all practical universe sizes.",
            ],
            examPitfalls: [
              "Distinct edge weights guarantee a unique MST, but unique MST DOES NOT require distinct edge weights.",
              "Decreasing the weight of an edge ALREADY in the MST leaves the MST unchanged (weights decrease, but edges remain).",
              "Increasing the weight of an edge NOT in the MST leaves the MST unchanged.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Spanning Tree Axioms & Fundamental Cut/Cycle Theorems",
              body: [
                "For a connected, undirected weighted graph `G = (V, E, w)`:",
                "A **Spanning Tree** is an acyclic subgraph connecting all `|V|` vertices, having exactly `|V| - 1` edges. An MST minimizes `w(T) = sum_{e in T} w(e)`.",
                "**Theorem 1 (The Cut Property):**",
                "Let `(S, V setminus S)` be any cut of `G`. If edge `e = (u, v)` is the strictly minimum-weight edge crossing the cut (`u in S, v in V setminus S`), then `e` belongs to every MST of `G`.",
                "*Proof:* Suppose an MST `T` does not contain `e`. Adding `e` to `T` creates a cycle `C`. This cycle must cross the cut at least once more via another edge `e'`. Since `w(e) < w(e')`, replacing `e'` with `e` creates a new spanning tree `T' = T cup {e} setminus {e'}` with `w(T') < w(T)`, contradicting the optimality of `T`.",
                "**Theorem 2 (The Cycle Property):**",
                "Let `C` be any cycle in `G`. If edge `e` is the strictly heaviest edge on `C`, then `e` cannot belong to any MST of `G`.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Kruskal vs Prim: Algorithmic Mechanics & Complexities",
              body: [
                "**Kruskal's Algorithm (Edge-Centric):**",
                "1. Sort all edges in non-decreasing order of weight.",
                "2. Maintain a Disjoint Set Union (DSU) of vertices.",
                "3. For each edge `(u, v)`: if `Find(u) != Find(v)`, union the sets and add `(u, v)` to the MST.",
                "Union-by-rank with path compression achieves `O(alpha(V))` amortized time per operation. Total time: `O(E log E) = O(E log V)`.",
                "**Prim's Algorithm (Vertex-Centric):**",
                "1. Start with an arbitrary root vertex `s`. Set `key[s] = 0`, `key[v] = inf` for all `v != s`.",
                "2. Extract min vertex `u` from priority queue.",
                "3. For each adjacent edge `(u, v)`: if `v` is in the queue and `w(u, v) < key[v]`, update `key[v] = w(u, v)` and `parent[v] = u` (`Decrease-Key`).",
                "Complexity with Binary Min-Heap: `O(V log V + E log V) = O(E log V)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Minimum Weight Spanning Tree Edge Inclusion",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Always verify whether the cut property isolates a subset. If multiple edges share the minimum weight across a cut, any of them may appear in some MST, but not necessarily all.",
              solutionSteps: [
                "Problem: Graph G has 5 vertices {A, B, C, D, E} and edges with weights: (A, B)=1, (B, C)=2, (C, D)=3, (D, E)=4, (E, A)=5, (A, C)=2, (B, D)=3, (C, E)=4. Find the total weight of the MST and check whether it is unique.",
                "Step 1: Sort edges in non-decreasing order:",
                "  (A, B): 1",
                "  (A, C): 2, (B, C): 2",
                "  (C, D): 3, (B, D): 3",
                "  (D, E): 4, (C, E): 4",
                "  (E, A): 5",
                "Step 2: Execute Kruskal's algorithm:",
                "  - Add (A, B) wt 1. Components: {A, B}, {C}, {D}, {E}. MST wt = 1.",
                "  - Consider wt 2: (A, C) connects {A, B} and {C}. Add (A, C) wt 2. Components: {A, B, C}, {D}, {E}. MST wt = 3.",
                "  - Consider (B, C) wt 2: Both B and C are already in {A, B, C}. Forms cycle (A-B-C-A). Discard.",
                "  - Consider wt 3: (C, D) connects {A, B, C} and {D}. Add (C, D) wt 3. Components: {A, B, C, D}, {E}. MST wt = 6.",
                "  - Consider (B, D) wt 3: Both B and D are in {A, B, C, D}. Forms cycle. Discard.",
                "  - Consider wt 4: (D, E) connects {A, B, C, D} and {E}. Add (D, E) wt 4. Components: {A, B, C, D, E}. MST wt = 10.",
                "Step 3: Verification:",
                "  Edges selected: (A, B)=1, (A, C)=2, (C, D)=3, (D, E)=4.",
                "  Total MST weight = 1 + 2 + 3 + 4 = 10.",
                "  Alternative tie: if at wt 2 we picked (B, C)=2 instead of (A, C)=2, we get edges (A, B)=1, (B, C)=2, (C, D)=3, (D, E)=4 with total weight 10. Hence MST is NOT unique, but the minimum weight 10 is unique.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 23: Minimum Spanning Trees.",
                },
              ],
            },
          ],
        },
        {
          id: "greedy-vs-dynamic-programming",
          title: "Dynamic Programming: 0/1 Knapsack, LCS & LIS",
          slug: "greedy-vs-dynamic-programming",
          order: 3,
          estimatedMinutes: 34,
          tagline: "Overlapping subproblems, 0/1 Knapsack pseudo-polynomial complexity, LCS table reconstruction, and LIS in O(n log n).",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "0/1 Knapsack: DP[i][w] = max(DP[i-1][w], val[i] + DP[i-1][w - wt[i]]). Time O(n*W) is Pseudo-Polynomial.",
            keyFormulasAndRules: [
              "0/1 Knapsack Space Optimization: 1D array DP[w] filled right-to-left (from W down to wt[i]) achieves O(W) space.",
              "LCS Recurrence: If X[i] == Y[j] => 1 + LCS[i-1][j-1]; Else max(LCS[i-1][j], LCS[i][j-1]). Time O(m*n).",
              "Longest Increasing Subsequence (LIS): O(n^2) via standard DP; O(n log n) via Patience Sorting (tails array with binary search lower_bound).",
              "Pseudo-Polynomial Time: O(n*W) is polynomial in numerical value of W, but EXPONENTIAL in input length log(W) bits.",
            ],
            examPitfalls: [
              "In 1D space-optimized 0/1 Knapsack, you MUST traverse capacity from W down to wt[i]. Traversing left-to-right solves the Unbounded Knapsack problem instead!",
              "LCS table has size (m + 1) x (n + 1); base cases are row 0 and column 0 initialized to 0.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Dynamic Programming Paradigm & Memoization",
              body: [
                "Dynamic programming is applicable when a problem has two key ingredients:",
                "1. **Optimal Substructure:** An optimal solution to the problem contains within it optimal solutions to subproblems.",
                "2. **Overlapping Subproblems:** A recursive algorithm visits the same subproblems repeatedly rather than generating new subproblems.",
                "**Top-Down (Memoization) vs Bottom-Up (Tabulation):**",
                "- Top-Down: Write natural recursive formulation, store computed results in hash table or array.",
                "- Bottom-Up: Identify topological ordering of subproblem dependencies and fill an iterative DP table from base cases up.",
              ],
            },
            {
              type: "explanation",
              heading: "2. 0/1 Knapsack, LCS and Patience Sorting for LIS",
              body: [
                "**0/1 Knapsack Recurrence:**",
                "`DP[i][w] = DP[i-1][w]` (if `wt[i] > w`), and `max(DP[i-1][w], val[i] + DP[i-1][w - wt[i]])` (if `wt[i] <= w`).",
                "Time complexity is `O(n * W)`. This is **pseudo-polynomial** because the input length of capacity `W` is `k = lceil log_2 W rceil` bits. Thus `W = 2^k`, meaning the running time is exponential in the input representation size.",
                "**Longest Increasing Subsequence (LIS) in `O(n log n)`:**",
                "Maintain an array `tails` where `tails[len]` stores the smallest tail of all increasing subsequences of length `len + 1` found so far.",
                "For each element `x` in `A`:",
                "- Binary search for the first element in `tails >= x`.",
                "- If found, replace it with `x` (maintaining smaller tail for that length).",
                "- If `x` is larger than all elements in `tails`, append `x` to `tails`.",
                "The length of `tails` at the end is the length of the LIS.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: LCS Matrix Table & String Reconstruction",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "When backtracking in the LCS table, if c[i-1][j] == c[i][j-1], both directions lead to valid optimal LCS strings of equal length.",
              solutionSteps: [
                "Problem: Given strings X = 'BDCABA' (length 6) and Y = 'ABCBDAB' (length 7), compute the length of their Longest Common Subsequence and reconstruct one LCS string.",
                "Step 1: Construct (6+1) x (7+1) matrix DP[i][j]:",
                "  Rows: X = [-, B, D, C, A, B, A]",
                "  Cols: Y = [-, A, B, C, B, D, A, B]",
                "Step 2: Fill rows using recurrence:",
                "  Row 1 (B): [0, 0, 1, 1, 1, 1, 1, 1]",
                "  Row 2 (D): [0, 0, 1, 1, 1, 2, 2, 2]",
                "  Row 3 (C): [0, 0, 1, 2, 2, 2, 2, 2]",
                "  Row 4 (A): [0, 1, 1, 2, 2, 2, 3, 3]",
                "  Row 5 (B): [0, 1, 2, 2, 3, 3, 3, 4]",
                "  Row 6 (A): [0, 1, 2, 2, 3, 3, 4, 4]",
                "Step 3: LCS length:",
                "  DP[6][7] = 4.",
                "Step 4: Backtrack from (6, 7):",
                "  - At (6, 7), X[6]='A' != Y[7]='B'. DP[5][7]=4, DP[6][6]=4. Move up to (5, 7).",
                "  - At (5, 7), X[5]='B' == Y[7]='B'. Match! Pick 'B', move to (4, 6).",
                "  - At (4, 6), X[4]='A' == Y[6]='A'. Match! Pick 'A', move to (3, 5).",
                "  - At (3, 5), X[3]='C' != Y[5]='D'. DP[2][5]=2, DP[3][4]=2. Move to (3, 3) through (3, 4).",
                "  - At (3, 3), X[3]='C' == Y[3]='C'. Match! Pick 'C', move to (2, 2).",
                "  - At (2, 2), X[2]='D' != Y[2]='B'. Move up to (1, 2).",
                "  - At (1, 2), X[1]='B' == Y[2]='B'. Match! Pick 'B', move to (0, 1).",
                "Reconstructed string (reversed): 'BCAB' (length 4). Other valid LCS is 'BDAB'.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 15: Dynamic Programming, 0/1 Knapsack and Longest Common Subsequence.",
                },
              ],
            },
          ],
        },
        {
          id: "matrix-chain-and-advanced-dp",
          title: "Matrix Chain Multiplication & Optimization Problems",
          slug: "matrix-chain-and-advanced-dp",
          order: 4,
          estimatedMinutes: 34,
          tagline: "Optimal parenthesization, Catalan number state space, O(n^3) table formulation, and DP on DAGs.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Matrix Chain: M[i, j] = min_{i <= k < j} { M[i, k] + M[k+1, j] + p_{i-1}*p_k*p_j }. Time O(n^3), Space O(n^2).",
            keyFormulasAndRules: [
              "Scalar Multiplications for A(p x q) and B(q x r): Cost is p * q * r multiplications.",
              "Number of Parenthesizations: Catalan number C_{n-1} = (1 / n) * binom(2n - 2, n - 1) = Omega(4^n / n^{1.5}).",
              "DP on DAGs: Shortest / Longest paths in a DAG can be solved in linear time O(V + E) by evaluating vertices in Topological Order.",
              "Held-Karp Traveling Salesperson: Solved via DP with bitmask in O(n^2 * 2^n) time.",
            ],
            examPitfalls: [
              "In matrix chain dimension vector p = [p0, p1, ..., pn], matrix A_i has dimension p_{i-1} x p_i (1-indexed).",
              "The base case M[i, i] = 0 (a single matrix requires 0 multiplications).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Matrix Chain Parenthesization Problem",
              body: [
                "Matrix multiplication is associative: `(A_1 A_2) A_3 = A_1 (A_2 A_3)`. However, the order of parenthesization dramatically impacts the number of scalar multiplications.",
                "For a chain of `n` matrices `<A_1, A_2, ..., A_n>` where matrix `A_i` has dimension `p_{i-1} times p_i`:",
                "Let `m[i, j]` be the minimum number of scalar multiplications needed to compute the product `A_i .. A_j`.",
                "**The Recurrence:**",
                "`m[i, j] = 0` if `i = j`",
                "`m[i, j] = min_{i <= k < j} { m[i, k] + m[k+1, j] + p_{i-1} * p_k * p_j }` if `i < j`.",
                "Because computing `m[i, j]` requires values of smaller chain lengths, the table is filled diagonally by chain length `l = 2, 3, ..., n`.",
                "Complexity: `Theta(n^3)` time and `Theta(n^2)` space.",
              ],
            },
            {
              type: "explanation",
              heading: "2. DAG Shortest/Longest Paths & Held-Karp TSP",
              body: [
                "**Dynamic Programming on DAGs:**",
                "Because a Directed Acyclic Graph has no cycles, vertices can be linearized into a topological sort `v_1, v_2, ..., v_n`.",
                "For longest path in a DAG:",
                "`dist[v] = max_{(u, v) in E} { dist[u] + w(u, v) }`.",
                "Evaluating in topological order ensures every subproblem `dist[u]` is finalized before computing `dist[v]`. Running time: `O(V + E)`. Works with negative edge weights!",
                "**Held-Karp TSP Algorithm:**",
                "Brute force TSP checks `(n - 1)!` tours. Using DP:",
                "Let `C(S, j)` be the minimum cost of visiting every vertex in subset `S` exactly once, starting at vertex 1 and ending at vertex `j in S`.",
                "`C(S, j) = min_{i in S setminus {j}} { C(S setminus {j}, i) + dist(i, j) }`.",
                "Time complexity: `O(n^2 * 2^n)`, space `O(n * 2^n)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: 4-Matrix Optimal Parenthesization Table",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Ensure dimensions array p corresponds to matrix A_i having size p_{i-1} x p_i.",
              solutionSteps: [
                "Problem: Find minimum scalar multiplications to multiply 4 matrices with dimensions: A1 (10x20), A2 (20x30), A3 (30x40), A4 (40x30). Dimension vector p = [10, 20, 30, 40, 30].",
                "Step 1: Compute chain lengths of 2 (l = 2):",
                "  M[1, 2] = 10 * 20 * 30 = 6,000  (split k = 1)",
                "  M[2, 3] = 20 * 30 * 40 = 24,000 (split k = 2)",
                "  M[3, 4] = 30 * 40 * 30 = 36,000 (split k = 3)",
                "Step 2: Compute chain lengths of 3 (l = 3):",
                "  M[1, 3] = min(",
                "    k=1: M[1,1] + M[2,3] + 10*20*40 = 0 + 24000 + 8000 = 32000,",
                "    k=2: M[1,2] + M[3,3] + 10*30*40 = 6000 + 0 + 12000 = 18000",
                "  ) = 18,000 (split k = 2)",
                "  M[2, 4] = min(",
                "    k=2: M[2,2] + M[3,4] + 20*30*30 = 0 + 36000 + 18000 = 54000,",
                "    k=3: M[2,3] + M[4,4] + 20*40*30 = 24000 + 0 + 24000 = 48000",
                "  ) = 48,000 (split k = 3)",
                "Step 3: Compute chain length 4 (M[1, 4]):",
                "  k=1: M[1,1] + M[2,4] + 10*20*30 = 0 + 48000 + 6000 = 54,000",
                "  k=2: M[1,2] + M[3,4] + 10*30*30 = 6000 + 36000 + 9000 = 51,000",
                "  k=3: M[1,3] + M[4,4] + 10*40*30 = 18000 + 0 + 12000 = 30,000 (MINIMAL)",
                "Step 4: Final Answer & Optimal Parenthesization:",
                "  Minimum scalar multiplications = 30,000.",
                "  Optimal parenthesization: ((A1 * (A2 * A3)) * A4).",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 15: Dynamic Programming, Matrix-chain multiplication.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: GRAPH TRAVERSALS & SHORTEST PATHS
    // =========================================================================
    {
      id: "algo-module-4-graphs",
      title: "Module 4: Graph Traversals & Shortest Paths",
      slug: "graph-traversals-and-paths",
      description:
        "Adjacency representations, BFS level frontiers, DFS discovery/finish timestamps, edge classification (tree, back, forward, cross), Topological Sort, Kosaraju/Tarjan SCCs, Dijkstra with heaps, Bellman-Ford negative cycle detection, Floyd-Warshall, and Johnson's algorithm.",
      order: 4,
      lessons: [
        {
          id: "graph-traversals-and-connectivity",
          title: "Graph Traversals, Topological Sort & Strongly Connected Components",
          slug: "graph-traversals-and-connectivity",
          order: 1,
          estimatedMinutes: 34,
          tagline: "BFS/DFS edge classification, discovery/finish timestamps, Kahn's algorithm, and Kosaraju/Tarjan SCCs.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A directed graph has a cycle iff DFS discovers a BACK EDGE. A DAG can be topologically sorted in reverse order of DFS finish times.",
            keyFormulasAndRules: [
              "BFS Time Complexity: Theta(V + E) with adjacency list. Finds shortest paths in unweighted graphs.",
              "Parenthesis Theorem: For any u, v in DFS, intervals [d[u], f[u]] and [d[v], f[v]] are either completely disjoint or one contains the other.",
              "Edge Classification (Directed): Tree Edge (unvisited), Back Edge (ancestor on stack: d[v] < d[u] < f[u] < f[v]), Forward Edge (descendant: d[u] < d[v] < f[v] < f[u]), Cross Edge (d[v] < f[v] < d[u] < f[u]).",
              "Undirected DFS Edges: Only TREE and BACK edges exist (no forward or cross edges).",
              "Topological Sort: Valid ONLY on DAGs. Computed in O(V + E) via DFS finish times or Kahn's in-degree queue.",
              "Kosaraju SCC: 1. DFS on G (record finish times); 2. Transpose G to G^T; 3. DFS on G^T in decreasing finish time order. Time O(V + E).",
            ],
            examPitfalls: [
              "In undirected graphs, an edge leading directly to the immediate parent vertex on the recursion stack is NOT a back edge; it is the tree edge traversed in reverse.",
              "If Kahn's algorithm terminates with vertices still having in-degree > 0, the graph contains a cycle.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. DFS Timestamps & Edge Classification Theory",
              body: [
                "During Depth-First Search (DFS), each vertex `u` is assigned two timestamps:",
                "- `d[u]`: Discovery time (when vertex turns from WHITE to GRAY).",
                "- `f[u]`: Finish time (when all outgoing edges are explored and vertex turns BLACK).",
                "**The Parenthesis Structure:**",
                "For any pair `u, v`, exactly one holds:",
                "1. `[d[u], f[u]]` and `[d[v], f[v]]` are entirely disjoint: neither is an ancestor of the other.",
                "2. `[d[u], f[u]]` is completely contained within `[d[v], f[v]]`: `u` is a descendant of `v` in the DFS forest.",
                "**Edge Classification on Directed Graphs:**",
                "- **Tree Edge:** Leads to an unvisited (white) vertex.",
                "- **Back Edge:** Leads to an ancestor currently on the recursion stack (gray vertex: `d[v] < d[u] < f[u] < f[v]`). **A back edge proves existence of a directed cycle.**",
                "- **Forward Edge:** Leads to a descendant already explored (black vertex: `d[u] < d[v] < f[v] < f[u]`).",
                "- **Cross Edge:** Leads to a vertex in another branch/tree (black vertex: `d[v] < f[v] < d[u] < f[u]`).",
              ],
            },
            {
              type: "explanation",
              heading: "2. Topological Sorting & Strongly Connected Components",
              body: [
                "A **Topological Sort** of a directed acyclic graph (DAG) `G = (V, E)` is a linear ordering of all vertices such that for every directed edge `(u, v)`, vertex `u` comes before `v`.",
                "**Two Classic Algorithms:**",
                "1. **DFS Finish Time Ordering:** Run DFS on `G`. As each vertex finishes (`f[u]`), prepend it to a linked list. The resulting list is a valid topological sort. Time `O(V + E)`.",
                "2. **Kahn's In-Degree Algorithm:** Compute in-degrees of all vertices. Enqueue all vertices with in-degree 0. Repeatedly dequeue vertex `u`, add to sorted order, and decrement in-degrees of its neighbors. If a neighbor reaches in-degree 0, enqueue it. Time `O(V + E)`.",
                "**Strongly Connected Components (Kosaraju's Algorithm):**",
                "A directed graph is strongly connected if every vertex is reachable from every other vertex.",
                "Kosaraju's 2-pass algorithm:",
                "1. Run DFS on `G` and record vertices in a stack ordered by finish time.",
                "2. Construct the transpose graph `G^T` (reverse all edge directions).",
                "3. Pop vertices from stack and run DFS on `G^T`. Each DFS tree corresponds to an SCC.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: DFS Edge Classification & Timestamp Tracing",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Alphabetical neighbor tie-breaking affects discovery times, but the topological property and existence of back edges remains invariant.",
              solutionSteps: [
                "Problem: A directed graph G has vertices {1, 2, 3, 4} and edges (1, 2), (1, 3), (2, 4), (3, 2), (4, 3). Run DFS starting at vertex 1 (exploring lower numerical vertex first). Classify all edges and determine whether G contains a cycle.",
                "Step 1: Trace DFS execution with timestamp clock starting at t = 1:",
                "  - Visit 1: d[1] = 1.",
                "  - From 1, explore (1, 2): 2 is unvisited => (1, 2) is a TREE EDGE. d[2] = 2.",
                "  - From 2, explore (2, 4): 4 is unvisited => (2, 4) is a TREE EDGE. d[4] = 3.",
                "  - From 4, explore (4, 3): 3 is unvisited => (4, 3) is a TREE EDGE. d[3] = 4.",
                "  - From 3, explore (3, 2): vertex 2 is currently GRAY (on stack: d[2]=2, f[2] not set).",
                "    Since 2 is an ancestor on stack, (3, 2) is a BACK EDGE!",
                "  - No more edges from 3: f[3] = 5.",
                "  - Backtrack to 4: no more edges => f[4] = 6.",
                "  - Backtrack to 2: no more edges => f[2] = 7.",
                "  - Backtrack to 1, explore (1, 3): vertex 3 is BLACK (d[3]=4, f[3]=5 < d[1]=1... wait d[1]=1 < d[3]=4 < f[3]=5 < f[1]).",
                "    Since 3 is a descendant already explored, (1, 3) is a FORWARD EDGE.",
                "  - Finish 1: f[1] = 8.",
                "Step 2: Summary of edge classifications:",
                "  - Tree Edges: (1, 2), (2, 4), (4, 3)",
                "  - Back Edge: (3, 2)",
                "  - Forward Edge: (1, 3)",
                "  - Cross Edges: None",
                "Step 3: Cycle Conclusion:",
                "  Because a BACK EDGE (3, 2) was discovered, the graph contains a directed cycle: 2 -> 4 -> 3 -> 2.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 22: Elementary Graph Algorithms (BFS, DFS, Topological Sort, SCC).",
                },
              ],
            },
          ],
        },
        {
          id: "shortest-paths-and-np-completeness",
          title: "Shortest Paths: Dijkstra, Bellman-Ford, Floyd-Warshall & Johnson",
          slug: "shortest-paths-and-np-completeness",
          order: 2,
          estimatedMinutes: 34,
          tagline: "Non-negative edge Dijkstra, negative edge relaxation, negative cycle detection, and all-pairs dynamic programming.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Dijkstra: O((V+E) log V), non-negative weights only. Bellman-Ford: O(V*E), handles negative weights and detects negative cycles. Floyd-Warshall: O(V^3) APSP.",
            keyFormulasAndRules: [
              "Dijkstra Greedy Invariant: When vertex u is extracted from min-heap, dist[u] = delta(s, u) is permanently finalized.",
              "Why Dijkstra Fails on Negative Edges: Negative edges violate greedy choice; adding constant C to all edges fails because paths with more edges are penalized.",
              "Bellman-Ford Relaxation: Relaxes all E edges V - 1 times. A V-th iteration that strictly decreases any distance proves a negative cycle reachable from s.",
              "Floyd-Warshall DP: D^{(k)}[i, j] = min(D^{(k-1)}[i, j], D^{(k-1)}[i, k] + D^{(k-1)}[k, j]). Negative cycle iff D[i, i] < 0.",
              "Johnson's Algorithm: Reweights edges using Bellman-Ford potentials h(v) so all w'(u, v) >= 0. Runs Dijkstra V times. Time O(V^2 log V + V*E).",
            ],
            examPitfalls: [
              "Dijkstra DOES NOT work with negative weights even if there are no negative cycles.",
              "Bellman-Ford detects negative cycles ONLY if they are reachable from the chosen source vertex s.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Single-Source Shortest Paths: Dijkstra vs Bellman-Ford",
              body: [
                "For a weighted graph `G = (V, E, w)`, the shortest-path weight from `s` to `v` is `delta(s, v)`.",
                "**Edge Relaxation Invariant:**",
                "`Relax(u, v, w):` If `dist[v] > dist[u] + w(u, v)`, update `dist[v] = dist[u] + w(u, v)`.",
                "**Dijkstra's Algorithm (Non-Negative Weights Only):**",
                "Maintains a set of vertices whose final shortest-path weights have been determined. Greedily extracts min `dist[u]` vertex from priority queue.",
                "Complexity: `O((V + E) log V)` using binary min-heap.",
                "**Bellman-Ford Algorithm (General Weights):**",
                "Relaxes all `|E|` edges `|V| - 1` times. A shortest simple path contains at most `|V| - 1` edges. If a `|V|`-th pass further relaxes any edge, a negative-weight cycle exists.",
                "Complexity: `O(V * E)`.",
              ],
            },
            {
              type: "explanation",
              heading: "2. All-Pairs Shortest Paths: Floyd-Warshall & Johnson's Reweighting",
              body: [
                "**Floyd-Warshall (Dense Graphs, Dynamic Programming):**",
                "Considers intermediate vertices in `{1, 2, ..., k}`.",
                "`d_{ij}^{(k)} = min( d_{ij}^{(k-1)}, d_{ik}^{(k-1)} + d_{kj}^{(k-1)} )`.",
                "Time complexity: `Theta(V^3)`, space `Theta(V^2)`.",
                "**Johnson's Algorithm (Sparse Graphs with Negative Weights):**",
                "1. Add dummy vertex `s` with 0-weight edges to all `v in V`.",
                "2. Run Bellman-Ford from `s` to compute potential function `h(v) = delta(s, v)`.",
                "3. Reweight edges: `hat{w}(u, v) = w(u, v) + h(u) - h(v)`. By triangle inequality, `hat{w}(u, v) >= 0`.",
                "4. Run Dijkstra from every vertex `u` using non-negative weights `hat{w}`.",
                "5. Recover true distances: `delta(u, v) = hat{delta}(u, v) - h(u) + h(v)`.",
                "Complexity: `O(V^2 log V + V E)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Floyd-Warshall Matrix Update Iteration",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "At step k, the k-th row and k-th column of the distance matrix never change because d[k, k] = 0.",
              solutionSteps: [
                "Problem: A 3-vertex directed graph has adjacency weight matrix D^{(0)}:",
                "  [  0,   4,  inf ]",
                "  [ inf,  0,   1  ]",
                "  [  2,  inf,  0  ]",
                "Compute D^{(1)} (using vertex 1 as intermediate) and D^{(2)} (using vertex 2 as intermediate).",
                "Step 1: Compute D^{(1)} (intermediate vertex k = 1):",
                "  Formula: D^{(1)}[i, j] = min( D^{(0)}[i, j], D^{(0)}[i, 1] + D^{(0)}[1, j] )",
                "  Row 1 and Col 1 remain unchanged.",
                "  - D^{(1)}[2, 3] = min(1, D^{(0)}[2, 1] + D^{(0)}[1, 3]) = min(1, inf + inf) = 1.",
                "  - D^{(1)}[3, 2] = min(inf, D^{(0)}[3, 1] + D^{(0)}[1, 2]) = min(inf, 2 + 4) = 6.",
                "  D^{(1)} matrix:",
                "  [ 0, 4, inf ]",
                "  [ inf, 0, 1 ]",
                "  [ 2, 6, 0 ]",
                "Step 2: Compute D^{(2)} (intermediate vertex k = 2):",
                "  Formula: D^{(2)}[i, j] = min( D^{(1)}[i, j], D^{(1)}[i, 2] + D^{(1)}[2, j] )",
                "  Row 2 and Col 2 remain unchanged.",
                "  - D^{(2)}[1, 3] = min(inf, D^{(1)}[1, 2] + D^{(1)}[2, 3]) = min(inf, 4 + 1) = 5.",
                "  - D^{(2)}[3, 1] = min(2, D^{(1)}[3, 2] + D^{(1)}[2, 1]) = min(2, 6 + inf) = 2.",
                "  D^{(2)} matrix:",
                "  [ 0, 4, 5 ]",
                "  [ inf, 0, 1 ]",
                "  [ 2, 6, 0 ]",
                "Step 3: Verification:",
                "  Direct path 1 -> 2 -> 3 has cost 4 + 1 = 5, replacing previous distance of infinity. Fully verified.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapters 24 & 25: Single-Source Shortest Paths and All-Pairs Shortest Paths.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: COMPUTATIONAL COMPLEXITY & NP-COMPLETENESS
    // =========================================================================
    {
      id: "algo-module-5-complexity",
      title: "Module 5: Computational Complexity & NP-Completeness",
      slug: "complexity-and-reductions",
      description:
        "Decision problems, complexity classes P, NP, co-NP, NP-Hard, NP-Complete, polynomial certificates, Cook-Levin theorem, and classic polynomial-time reduction chains.",
      order: 5,
      lessons: [
        {
          id: "computational-complexity-and-np-completeness",
          title: "Complexity Classes P, NP, NP-Complete & Reductions",
          slug: "computational-complexity-and-np-completeness",
          order: 1,
          estimatedMinutes: 36,
          tagline: "Deterministic vs non-deterministic polynomial time, polynomial certificates, Cook-Levin theorem, and reduction chains.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Language L is NP-Complete iff: 1. L in NP, and 2. L is NP-Hard (every problem in NP reduces to L in polynomial time).",
            keyFormulasAndRules: [
              "Class P: Decision problems solvable by a Deterministic Turing Machine in polynomial time O(n^k).",
              "Class NP: Decision problems verifiable by a polynomial-time verifier with a polynomial certificate (or solvable by Non-Deterministic TM in poly time).",
              "Class co-NP: Decision problems whose complement is in NP.",
              "Polynomial Reduction A <=_p B: A reduces to B in polynomial time. If B in P => A in P. If A is NP-Hard => B is NP-Hard.",
              "DIRECTION OF REDUCTION: To prove problem X is NP-Hard, reduce FROM a KNOWN NP-Hard problem Y TO X (Y <=_p X).",
              "Cook-Levin Theorem: Circuit-SAT and 3-SAT are NP-Complete.",
              "Classic Reductions: 3-SAT <=_p Clique <=_p Vertex Cover <=_p Independent Set; 3-SAT <=_p Subset Sum <=_p Partition <=_p 0/1 Knapsack.",
            ],
            examPitfalls: [
              "REDUCTION DIRECTION ERROR: Proving X <=_p 3-SAT proves that X is in NP, NOT that X is NP-Hard! To prove X is NP-Hard, you must prove 3-SAT <=_p X.",
              "NP does NOT stand for 'Non-Polynomial'; it stands for 'Nondeterministic Polynomial'.",
              "P subseteq NP is known, but whether P = NP remains the greatest open problem in computer science.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Formal Anatomy of Complexity Classes",
              body: [
                "Computational complexity categorizes problems based on the inherent resource requirements (time and space) of their algorithms:",
                "**1. Class P (Polynomial Time):**",
                "The class of languages decidable by a Deterministic Turing Machine in time `O(n^k)` for some constant `k`. Examples: Shortest Paths, MST, Sorting, Linear Programming.",
                "**2. Class NP (Nondeterministic Polynomial Time):**",
                "The class of decision problems for which a 'YES' answer has a polynomial-length certificate that can be verified by a deterministic algorithm in polynomial time.",
                "Alternatively: Decidable by a Nondeterministic Turing Machine in polynomial time.",
                "**3. Class co-NP:**",
                "Languages whose complement is in `NP`. Example: TAUTOLOGY (verifying that a boolean formula is true for ALL truth assignments).",
                "**4. NP-Hard:**",
                "A problem `X` is NP-Hard if for every language `L in NP`, `L <=_p X`. NP-Hard problems need not be in NP (they can even be undecidable, like the Halting Problem).",
                "**5. NP-Complete:**",
                "A problem `X` is NP-Complete if: (1) `X in NP`, and (2) `X` is NP-Hard.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Polynomial-Time Reductions & Karp's 21 Reductions",
              body: [
                "A polynomial-time reduction from language `A` to language `B` (`A <=_p B`) is a polynomial-time computable function `f` such that for every input string `x`:",
                "`x in A iff f(x) in B`.",
                "**Fundamental Theorems of Reductions:**",
                "1. If `A <=_p B` and `B in P`, then `A in P`.",
                "2. If `A <=_p B` and `A notin P`, then `B notin P`.",
                "3. If `A <=_p B` and `B <=_p C`, then `A <=_p C` (Transitivity).",
                "4. If `A` is NP-Complete, and `A <=_p B` with `B in NP`, then `B` is NP-Complete.",
                "**The Canonical Reduction Chain:**",
                "- **Circuit-SAT** (Cook-Levin Theorem, base of hierarchy)",
                "- `Circuit-SAT <=_p 3-SAT`",
                "- `3-SAT <=_p Independent Set` (construct gadgets with 3 vertices per clause)",
                "- `Independent Set <=_p Vertex Cover` (in graph `G=(V, E)`, `S` is an independent set iff `V setminus S` is a vertex cover)",
                "- `Independent Set <=_p Clique` (`S` is an independent set in `G` iff `S` is a clique in complement graph `bar{G}`)",
                "- `3-SAT <=_p Subset Sum <=_p Partition <=_p 0/1 Knapsack`",
                "- `Hamiltonian Cycle <=_p Traveling Salesperson Problem (TSP)`",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Directionality & Consequences of Reductions",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Carefully read whether problem A reduces to problem B (A <=_p B) or vice versa. If an NP-complete problem reduces to X, X is at least as hard as NP.",
              solutionSteps: [
                "Problem: Let P1 and P2 be two decision problems. Suppose P1 is known to be NP-Complete. Consider the following statements:",
                "  S1: If P1 <=_p P2, then P2 is NP-Hard.",
                "  S2: If P2 <=_p P1, then P2 is NP-Complete.",
                "  S3: If P1 <=_p P2 and P2 in P, then P = NP.",
                "  S4: If P2 <=_p P1 and P2 in P, then P = NP.",
                "Determine the truth value of each statement.",
                "Step 1: Analyze S1:",
                "  By definition, if a known NP-Complete problem P1 reduces to P2 in poly-time (P1 <=_p P2), then every problem in NP reduces to P2 via P1. Therefore P2 is NP-Hard.",
                "  S1 is TRUE.",
                "Step 2: Analyze S2:",
                "  P2 <=_p P1 means P2 is at most as hard as P1. For example, the trivial problem 'Is 2 + 2 = 4?' reduces to 3-SAT, but it is in P, NOT NP-Complete.",
                "  S2 is FALSE.",
                "Step 3: Analyze S3:",
                "  If P1 <=_p P2 and P2 in P, then P1 in P. Since P1 is NP-Complete, this implies every problem in NP is solvable in polynomial time, proving P = NP.",
                "  S3 is TRUE.",
                "Step 4: Analyze S4:",
                "  P2 in P and P2 <=_p P1 is always true for any problem in P. It tells us nothing about whether P1 is in P.",
                "  S4 is FALSE.",
                "Final Conclusion: Statements S1 and S3 are TRUE; S2 and S4 are FALSE.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Computers and Intractability: A Guide to the Theory of NP-Completeness",
                  authors: "Michael R. Garey, David S. Johnson",
                  year: "1979",
                  publisher: "W. H. Freeman & Co",
                  relevance: "The definitive reference for polynomial reductions, NP-completeness definitions, and Karp's 21 problems.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
