import { CourseMeta } from "./types";

export const ARTIFICIAL_INTELLIGENCE_COURSE: CourseMeta = {
  id: "artificial-intelligence",
  title: "Artificial Intelligence",
  slug: "artificial-intelligence",
  subjectSlug: "artificial-intelligence",
  shortTitle: "AI",
  icon: "🧠",
  color: "bg-pink-500",
  tagline:
    "Master state space search, A* heuristic proofs, CSPs, Minimax alpha-beta pruning, first-order logic resolution, and Bayesian network d-separation for GATE DA.",
  description:
    "A comprehensive, mathematically rigorous study notebook covering classical artificial intelligence. Spans uninformed and informed search, A* admissibility and consistency proofs, local optimization, constraint satisfaction (AC-3), adversarial game theory (Minimax, Alpha-Beta), formal logic theorem proving (CNF, Skolemization, MGU Unification, Resolution Refutation), and probabilistic graphical models (Bayesian Networks, d-separation, Markov blankets, variable elimination). Engineered from first principles specifically for high-percentile GATE Data Science & AI (DA) preparation.",
  level: "Undergraduate / GATE DA",
  estimatedHours: 42,
  prerequisites: [
    "Discrete Mathematics (Predicate logic, sets, relations, graph theory, trees)",
    "Data Structures & Algorithms (Priority queues, graph traversals, recursion)",
    "Probability & Statistics (Conditional probability, Bayes' theorem, independence)",
  ],
  learningOutcomes: [
    "Analyze time and space complexities, completeness, and optimality across uninformed search algorithms (BFS, DFS, UCS, IDS)",
    "Prove the optimality of A* search under admissible tree heuristics and consistent graph heuristics, and evaluate heuristic dominance",
    "Formulate Constraint Satisfaction Problems (CSPs) and execute the AC-3 arc-consistency algorithm alongside MRV/LCV backtracking",
    "Trace Minimax game trees and execute precise Alpha-Beta pruning cutoffs to minimize evaluated leaf states",
    "Convert First-Order Logic knowledge bases into Conjunctive Normal Form (CNF) via Skolemization and prove theorem entailment via Resolution Refutation",
    "Evaluate conditional independence in Bayesian Networks using d-separation rules (chains, forks, colliders) and determine Markov blankets",
    "Execute exact probabilistic inference via Variable Elimination and factor marginalization in Bayesian networks",
  ],
  gateScope: "GATE 2027 DA scope",
  gateBranches: ["da"],
  gateSyllabusTopics: [
    "Uninformed search strategies: Breadth-first search, depth-first search, uniform cost search, depth-limited search, iterative deepening search",
    "Informed search algorithms: Greedy best-first search, A* search, heuristic evaluation functions, admissibility, consistency, heuristic dominance",
    "Local search and optimization: Hill climbing variations, simulated annealing, genetic algorithms",
    "Constraint satisfaction problems (CSP): Node consistency, arc consistency (AC-3 algorithm), backtracking with MRV, degree, and LCV heuristics",
    "Adversarial search: Two-player zero-sum games, minimax algorithm, alpha-beta pruning, evaluation functions, games with chance (expectiminimax)",
    "Propositional logic: Syntax, semantics, truth tables, validity, satisfiability, logical entailment, CNF conversion, Horn clauses, forward and backward chaining",
    "First-order logic: Quantifiers, models, interpretations, clausal form conversion, Skolemization, Most General Unifier (MGU), resolution refutation",
    "Reasoning under uncertainty: Conditional probability, Bayes' rule, Bayesian belief networks, conditional independence, d-separation, Markov blanket, variable elimination",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: UNINFORMED & INFORMED STATE SPACE SEARCH
    // =========================================================================
    {
      id: "da-ai-module-1-search",
      title: "Module 1: Uninformed & Informed State Space Search",
      slug: "search-algorithms",
      description:
        "State space search formulation, uninformed graph traversals (BFS, DFS, UCS, IDS), heuristic design, A* admissibility and consistency proofs, and heuristic dominance.",
      order: 1,
      lessons: [
        {
          id: "uninformed-search-strategies",
          title: "State Space Formalism & Uninformed Search Strategies",
          slug: "uninformed-search-strategies",
          order: 1,
          estimatedMinutes: 28,
          tagline: "Problem formulation, BFS, DFS, Uniform Cost Search (Dijkstra), and Iterative Deepening (IDS) performance bounds.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Uninformed search explores state spaces without domain-specific heuristics. Breadth-First Search (BFS) is complete and optimal for uniform step costs but consumes exponential memory O(b^d). Depth-First Search (DFS) uses minimal memory O(b*m) but is incomplete on infinite graphs. Uniform Cost Search (UCS) is optimal for general non-negative step costs. Iterative Deepening Search (IDS) combines BFS completeness and optimality with DFS linear memory efficiency.",
            keyFormulasAndRules: [
              "Search Problem Formulation: 5-tuple: Initial State s_0, Actions(s), Transition Model Result(s, a), Goal Test Goal(s), Path Cost c(s, a, s').",
              "Branching factor b = maximum number of successors of any node; d = depth of shallowest goal; m = maximum depth of state space.",
              "BFS Complexity: Time = O(b^d); Space = O(b^d) (stores entire frontier); Complete = Yes (if b is finite); Optimal = Yes (if step costs are equal).",
              "DFS Complexity: Time = O(b^m); Space = O(b*m) (linear space); Complete = No (can loop infinitely on cyclic/infinite paths); Optimal = No.",
              "Uniform Cost Search (UCS): Expands node with lowest path cost g(n); Time = O(b^(1 + floor(C* / epsilon))); Space = O(b^(1 + floor(C* / epsilon))); Optimal = Yes (for step costs >= epsilon > 0).",
              "Iterative Deepening Search (IDS): Successive depth-limited searches from depth 0, 1, 2, ... d. Time = O(b^d); Space = O(b*d); Complete = Yes; Optimal = Yes (for uniform step costs).",
            ],
            examPitfalls: [
              "In BFS, the Goal Test is applied when a node is GENERATED (placed on frontier), NOT when expanded. In UCS, the Goal Test MUST be applied when a node is EXPANDED (popped from frontier) to guarantee optimality!",
              "Do not assume IDS repeats too much work: the ratio of states generated in IDS compared to BFS is at most b / (b - 1). For b = 10, IDS has only ~11% overhead while saving gigabytes of RAM.",
              "If step costs are zero or negative, UCS can loop indefinitely or fail to find optimal paths.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. State Space Search Problem Formulation",
              body: [
                "In classical artificial intelligence, an agent achieves its objectives by finding a sequence of actions that transforms an initial state into a desired goal state within an abstract state space.",
                "A formal search problem consists of five formal components:",
                "1. Initial State: The starting state the agent occupies (e.g. `s_0 = In(Arad)`).",
                "2. Action Set `Actions(s)`: The set of legal moves available to the agent in state s.",
                "3. Transition Model `Result(s, a)`: The deterministic state resulting from executing action a in state s.",
                "4. Goal Test `IsGoal(s)`: A Boolean predicate determining whether state s satisfies the target condition.",
                "5. Path Cost `c(s, a, s')`: The non-negative numerical cost of executing action a to reach s' from s. The total path cost is the additive sum of individual step costs.",
              ],
            },
            {
              type: "comparison",
              heading: "2. Master Comparison of Uninformed Search Strategies",
              leadParagraph:
                "Comparative theoretical criteria for the five classical uninformed search algorithms across branching factor b, shallowest goal depth d, and maximum path depth m:",
              columns: ["Criterion", "Breadth-First (BFS)", "Depth-First (DFS)", "Uniform-Cost (UCS)", "Iterative Deepening (IDS)"],
              criteria: [
                {
                  criterion: "Frontier Data Structure",
                  values: ["FIFO Queue", "LIFO Stack", "Priority Queue (by g(n))", "Call Stack (Depth-Bounded)"],
                },
                {
                  criterion: "Time Complexity",
                  values: ["O(b^d)", "O(b^m)", "O(b^(1 + floor(C*/eps)))", "O(b^d)"],
                },
                {
                  criterion: "Space Complexity",
                  values: ["O(b^d) (Exponential)", "O(b * m) (Linear)", "O(b^(1 + floor(C*/eps)))", "O(b * d) (Linear)"],
                },
                {
                  criterion: "Completeness",
                  values: ["Yes (if b is finite)", "No (fails on infinite/loops)", "Yes (if step cost >= eps > 0)", "Yes (if b is finite)"],
                },
                {
                  criterion: "Optimality",
                  values: ["Yes (if step costs equal)", "No (finds leftmost path)", "Yes (general non-negative costs)", "Yes (if step costs equal)"],
                },
              ],
            },
            {
              type: "explanation",
              heading: "3. Uniform-Cost Search (UCS) & The Goal Test Timing Rule",
              body: [
                "Uniform-Cost Search (equivalent to Dijkstra's algorithm on directed graphs) expands nodes in increasing order of cumulative path cost `g(n)` from the start node.",
                "The Critical Timing Rule for Optimality:",
                "In BFS, an agent can terminate the search the moment a goal node is *generated* (inserted into the FIFO queue) because all nodes at depth d are generated before any node at depth d+1.",
                "However, in UCS, the agent **MUST NOT** terminate when a goal is merely generated. A goal node might be generated via a high-cost path first, while a cheaper path to the same goal (or another goal) is still pending expansion on the priority queue. Therefore, UCS must test for the goal condition **ONLY WHEN A NODE IS SELECTED FOR EXPANSION** (popped from the priority queue).",
              ],
              callout: {
                kind: "gate-tip",
                title: "Classic GATE DA Trap: Goal Test on Generation vs Expansion",
                message:
                  "• BFS applies Goal Test at GENERATION time (saves 1 layer of node expansions).\n• UCS and A* apply Goal Test at EXPANSION time (mandatory to guarantee optimal cost path).",
              },
            },
            {
              type: "explanation",
              heading: "4. Iterative Deepening Search (IDS): Combining Completeness with Linear Memory",
              body: [
                "Breadth-First Search is memory-constrained: for branching factor b = 10 and depth d = 6, BFS stores ~1,000,000 nodes in RAM. Depth-First Search is memory-efficient (stores only b * m nodes) but can plunge down an infinite path.",
                "Iterative Deepening Search (IDS) resolves this fundamental dilemma by running Depth-Limited Search (DLS) repeatedly with increasing depth limits L = 0, 1, 2, ... d:",
                "Number of Generated Nodes in IDS:",
                "$$N(\\text{IDS}) = (d + 1) b^0 + d b^1 + (d - 1) b^2 + \\dots + 1 b^d = O(b^d)$$",
                "The root node is generated d+1 times, while the deepest level nodes (which constitute the vast majority of the search space, $(b - 1)/b$ of all nodes) are generated only once! Thus, IDS achieves asymptotic time $O(b^d)$ with linear space $O(b \\cdot d)$.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "5. GATE Worked Numerical: Node Expansion Counts in IDS vs BFS",
              weightage: "2 Marks",
              trap: "Remember that the bottom level nodes in IDS are generated exactly ONCE, whereas the root is generated d + 1 times!",
              solutionSteps: [
                "Problem (Original Practice Problem · Modeled on GATE DA Pattern):",
                "A state space has a uniform branching factor b = 4. The shallowest goal state lies at depth d = 4.",
                "Calculate: (a) Total nodes generated by Breadth-First Search (BFS) assuming goal test at generation, and (b) Total nodes generated by Iterative Deepening Search (IDS) up to depth d = 4.",
                "Step 1: Compute BFS Node Generation Count:",
                "  BFS generates all nodes from level 0 up to level d:",
                "  Level 0: 4^0 = 1 node.",
                "  Level 1: 4^1 = 4 nodes.",
                "  Level 2: 4^2 = 16 nodes.",
                "  Level 3: 4^3 = 64 nodes.",
                "  Level 4: In the worst case (goal is the last node generated at depth 4), BFS generates all 4^4 = 256 nodes.",
                "  Total BFS Nodes = 1 + 4 + 16 + 64 + 256 = 341 nodes.",
                "Step 2: Compute IDS Node Generation Count:",
                "  Formula: N(IDS) = sum_{k=0}^{d} (d - k + 1) * b^k",
                "  Here d = 4, b = 4:",
                "  k = 0 (Depth 0): (4 - 0 + 1) * 4^0 = 5 * 1 = 5 nodes.",
                "  k = 1 (Depth 1): (4 - 1 + 1) * 4^1 = 4 * 4 = 16 nodes.",
                "  k = 2 (Depth 2): (4 - 2 + 1) * 4^2 = 3 * 16 = 48 nodes.",
                "  k = 3 (Depth 3): (4 - 3 + 1) * 4^3 = 2 * 64 = 128 nodes.",
                "  k = 4 (Depth 4): (4 - 4 + 1) * 4^4 = 1 * 256 = 256 nodes.",
                "  Total IDS Nodes = 5 + 16 + 48 + 128 + 256 = 453 nodes.",
                "Step 3: Analyze Overhead:",
                "  Ratio = 453 / 341 ≈ 1.328 (only ~33% extra node generations, but BFS requires storing 256 nodes simultaneously, whereas IDS stores at most b * d = 4 * 4 = 16 nodes in the call stack!).",
                "Conclusion: BFS generates 341 nodes; IDS generates 453 nodes with 94% memory reduction.",
              ],
            },
            {
              type: "resources",
              heading: "6. Primary References",
              sources: [
                {
                  title: "Artificial Intelligence: A Modern Approach (4th Edition)",
                  authors: "Stuart Russell, Peter Norvig",
                  year: "2020",
                  publisher: "Pearson",
                  link: "https://aima.cs.berkeley.edu",
                  relevance:
                    "Chapter 3: Solving Problems by Searching — definitive formal models of state space formulation, BFS, DFS, UCS, and iterative deepening proofs.",
                },
              ],
            },
          ],
        },
        {
          id: "uninformed-and-a-star-search",
          title: "State Space Search, UCS & A* Heuristic Admissibility",
          slug: "uninformed-and-a-star-search",
          order: 2,
          estimatedMinutes: 30,
          tagline: "f(n) = g(n) + h(n), proving A* optimality on trees vs graphs, and dominance of heuristics.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A* Tree Search is optimal if heuristic h(n) is ADMISSIBLE (0 <= h(n) <= h*(n)). A* Graph Search is optimal if h(n) is CONSISTENT / MONOTONIC (h(n) <= c(n, a, n') + h(n')). Consistency implies admissibility, but the converse is not generally true. If h2(n) >= h1(n) for all n and both are admissible, h2 dominates h1 and expands a subset of nodes.",
            keyFormulasAndRules: [
              "A* Evaluation Function: f(n) = g(n) + h(n), where g(n) is exact cost from start to n, and h(n) is estimated cost from n to goal.",
              "Admissibility Condition (Tree Search): 0 <= h(n) <= h*(n) for all n, where h*(n) is the true optimal cost from n to nearest goal.",
              "Consistency / Monotonicity Condition (Graph Search): h(n) <= c(n, a, n') + h(n') for every transition from n to n' with action a.",
              "Monotonicity of f-values: Consistency implies f(n') = g(n') + h(n') = g(n) + c(n, a, n') + h(n') >= g(n) + h(n) = f(n) (non-decreasing along any path).",
              "Heuristic Dominance: If h2(n) >= h1(n) for all states n, then A* using h2 never expands more nodes than A* using h1 (except possibly tie-breaking).",
              "Memory-Bounded Variants: IDA* (Iterative Deepening A*, uses f-cost contour cutoffs with O(b*d) space); RBFS (Recursive Best-First Search, tracks alternative backup f-values).",
            ],
            examPitfalls: [
              "A heuristic that overestimates even once (h(n) > h*(n) for a single node n) is NOT admissible and can cause A* to return a strictly sub-optimal path!",
              "Admissibility is SUFFICIENT for Tree Search optimality, but NOT for Graph Search! Graph Search requires Consistency to avoid sub-optimal re-expansion bugs.",
              "Straight-line Euclidean distance h_SLD is always consistent for physical road navigation because Euclidean metric satisfies the triangle inequality.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The A* Search Algorithm & The f(n) Evaluation Function",
              body: [
                "Uninformed search algorithms suffer from exponential state expansion because they blindly explore all directions. Informed (heuristic) search guides exploration using domain-specific knowledge.",
                "**The A* Algorithm:** A* selects for expansion the frontier node that minimizes the estimated total solution cost:",
                "$$f(n) = g(n) + h(n)$$",
                "Where:",
                "• `g(n)` is the exact path cost incurred from the start state $s_0$ to node $n$.",
                "• `h(n)` is the heuristic estimate of the remaining path cost from node $n$ to the nearest goal state.",
                "• `f(n)` represents the estimated total cost of the cheapest solution path passing through node $n$.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Mathematical Proof of A* Tree Search Optimality under Admissibility",
              body: [
                "Definition (Admissibility): A heuristic function $h(n)$ is admissible if it never overestimates the true cost to reach the goal: $0 \\le h(n) \\le h^*(n)$ for all nodes $n$, and $h(G) = 0$ for any goal state $G$.",
                "Theorem: A* Tree Search is guaranteed to return an optimal solution if $h(n)$ is admissible.",
                "Proof by Contradiction:",
                "1. Let $G_2$ be a sub-optimal goal state generated during search, with path cost $g(G_2) > C^*$, where $C^*$ is the optimal path cost.",
                "2. Since $G_2$ is a goal, $h(G_2) = 0$, so $f(G_2) = g(G_2) + h(G_2) = g(G_2) > C^*$.",
                "3. Now consider an optimal goal path. At any point before finding $G_2$, there must exist at least one unexpanded node $n$ on the frontier that lies on this optimal path.",
                "4. For this node $n$ on the optimal path:",
                "   $$f(n) = g(n) + h(n) \\le g(n) + h^*(n) = C^*$$",
                "   (Since $h(n) \\le h^*(n)$ by admissibility, and $g(n) + h^*(n) = C^*$ by definition of an optimal path).",
                "5. Therefore, $f(n) \\le C^* < f(G_2)$.",
                "6. Since A* always selects the node with the lowest $f$-value, node $n$ will always be selected for expansion before $G_2$ could ever be selected for expansion.",
                "7. This holds for every node along the optimal path, culminating in the optimal goal $G^*$ being selected before $G_2$. Contradiction! Hence, sub-optimal goal $G_2$ can never be selected.",
              ],
            },
            {
              type: "explanation",
              heading: "3. Consistency (Monotonicity) for A* Graph Search",
              body: [
                "In Graph Search, an explored set (closed list) prevents re-visiting already expanded states. If a heuristic is admissible but *inconsistent*, the first path found to a state $n$ might NOT be the cheapest. If $n$ is discarded on subsequent encounters, A* can return a sub-optimal solution.",
                "Definition (Consistency / Monotonicity):",
                "A heuristic $h(n)$ is consistent if, for every node $n$ and every successor $n'$ generated by action $a$:",
                "$$h(n) \\le c(n, a, n') + h(n')$$",
                "This is the form of the classical **Triangle Inequality**: the estimated cost from $n$ to goal cannot exceed the step cost to $n'$ plus the estimated cost from $n'$ to goal.",
                "Consequences of Consistency:",
                "1. Non-decreasing $f$-costs: $f(n') = g(n') + h(n') = g(n) + c(n, a, n') + h(n') \\ge g(n) + h(n) = f(n)$.",
                "2. First Expansion Optimality: Whenever A* selects a state for expansion in graph search, the path to that state is guaranteed to be optimal. No closed-list state ever needs to be re-opened!",
                "3. Consistency strictly implies Admissibility (by induction along the path to goal, where $h(G) = 0$).",
              ],
              callout: {
                kind: "gate-tip",
                title: "Admissible but Inconsistent Heuristic Example",
                message:
                  "Consider S -> A (cost 1), A -> G (cost 3), S -> G (cost 5). Let h(S) = 4, h(A) = 1, h(G) = 0.\n• Admissibility: h(S)=4 <= 4 (optimal is S->A->G cost 4); h(A)=1 <= 3. Admissible!\n• Consistency check on edge S->A: h(S) <= c(S, A) + h(A) => 4 <= 1 + 1 = 2 (FALSE!). Inconsistent! Triangle inequality is violated.",
              },
            },
            {
              type: "gate-analysis",
              heading: "4. GATE DA Worked Example: A* Node Expansion Trace",
              weightage: "2 Marks (High Frequency in GATE DA)",
              trap: "Nodes are selected for expansion strictly based on lowest f(n) = g(n) + h(n), not purely h(n) or g(n) alone!",
              solutionSteps: [
                "Problem: Trace A* Graph Search from Start S to Goal G. Given transitions with step costs and heuristics h:",
                "  Heuristic values: h(S) = 5, h(A) = 3, h(B) = 4, h(C) = 2, h(G) = 0.",
                "  Directed Edges with costs:",
                "  S -> A (cost 2), S -> B (cost 3)",
                "  A -> C (cost 2), B -> C (cost 1)",
                "  C -> G (cost 3).",
                "Step 1: Initialize at Start S:",
                "  g(S) = 0, h(S) = 5 => f(S) = 0 + 5 = 5.",
                "  Frontier: [ S(f=5, g=0) ]. Closed: { }.",
                "  Pop S for expansion.",
                "Step 2: Generate successors of S:",
                "  Node A: g(A) = 0 + 2 = 2; f(A) = 2 + h(A) = 2 + 3 = 5.",
                "  Node B: g(B) = 0 + 3 = 3; f(B) = 3 + h(B) = 3 + 4 = 7.",
                "  Frontier: [ A(f=5, g=2), B(f=7, g=3) ]. Closed: { S }.",
                "  Lowest f is A(f=5) => Pop A for expansion.",
                "Step 3: Generate successors of A:",
                "  Node C: g(C) = g(A) + 2 = 2 + 2 = 4; f(C) = 4 + h(C) = 4 + 2 = 6.",
                "  Frontier: [ C(f=6, g=4), B(f=7, g=3) ]. Closed: { S, A }.",
                "  Lowest f is C(f=6) => Pop C for expansion.",
                "Step 4: Generate successors of C:",
                "  Node G: g(G) = g(C) + 3 = 4 + 3 = 7; f(G) = 7 + h(G) = 7 + 0 = 7.",
                "  Frontier: [ G(f=7, g=7), B(f=7, g=3) ]. Closed: { S, A, C }.",
                "  Lowest f is tie between G(f=7) and B(f=7).",
                "  If tie broken in favor of goal G: Pop G. Goal test succeeds!",
                "  If tie broken in favor of B: Pop B. B generates C with g(C) = 3 + 1 = 4 (same cost, C already closed). Then pop G.",
                "Conclusion: Optimal Path is S -> A -> C -> G with total optimal cost C* = 7.",
              ],
            },
            {
              type: "resources",
              heading: "5. Primary References",
              sources: [
                {
                  title: "Artificial Intelligence: A Modern Approach (4th Edition)",
                  authors: "Stuart Russell, Peter Norvig",
                  year: "2020",
                  publisher: "Pearson",
                  link: "https://aima.cs.berkeley.edu",
                  relevance:
                    "Chapter 3: Solving Problems by Searching — mathematical proofs of heuristic admissibility, consistency, and heuristic dominance.",
                },
                {
                  title: "Principles of Artificial Intelligence",
                  authors: "Nils J. Nilsson",
                  year: "1980",
                  publisher: "Morgan Kaufmann",
                  link: "https://www.sciencedirect.com/book/9780934613101",
                  relevance:
                    "Original historical proofs of the admissibility of A* and graph search closure properties.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: LOCAL SEARCH & CONSTRAINT SATISFACTION (CSP)
    // =========================================================================
    {
      id: "da-ai-module-2-local-and-csp",
      title: "Module 2: Local Search & Constraint Satisfaction Problems (CSP)",
      slug: "local-search-and-csps",
      description:
        "Local search landscapes, Hill Climbing, Simulated Annealing temperature schedules, Genetic Algorithms, CSP formulation, Arc Consistency (AC-3), and Backtracking heuristics.",
      order: 2,
      lessons: [
        {
          id: "local-search-and-optimization",
          title: "Local Search Optimization: Hill Climbing & Simulated Annealing",
          slug: "local-search-and-optimization",
          order: 1,
          estimatedMinutes: 26,
          tagline: "State space landscapes, plateaus, ridges, Simulated Annealing Metropolis acceptance probability, and Genetic Algorithms.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Local search operates using a single current state rather than maintaining frontiers, using minimal O(1) memory. Hill Climbing greedily climbs uphill but gets trapped in local maxima, plateaus, and ridges. Simulated Annealing escapes local maxima by accepting downhill moves with Metropolis probability P = exp(Delta E / T), where temperature T decreases according to an annealing schedule. Genetic Algorithms combine sexual recombination (crossover) with random mutation.",
            keyFormulasAndRules: [
              "Hill Climbing (Greedy Local Search): s <- argmax_{s' in Neighbors(s)} f(s'). Halts when no neighbor has a higher objective value.",
              "Simulated Annealing Metropolis Acceptance Probability: If Delta E = f(s') - f(s) > 0 (improvement), move is accepted unconditionally. If Delta E <= 0 (downhill move), accepted with probability P = exp(Delta E / T).",
              "Temperature Schedule T: High T (early) -> P approx 1 (random walk, broad exploration); Low T (late) -> P approx 0 (pure greedy hill climbing, fine convergence).",
              "Annealing Convergence Theorem: If schedule lowers T slow enough (e.g. logarithmic cooling T(t) = c / log(1 + t)), Simulated Annealing is guaranteed to converge to the global optimum.",
              "Genetic Algorithm Pipeline: Population -> Fitness Function -> Selection (Roulette Wheel / Tournament) -> Crossover (Recombination) -> Mutation (Random bit flip).",
            ],
            examPitfalls: [
              "In Simulated Annealing, Delta E is negative for a bad/downhill move: Delta E = f(neighbor) - f(current) < 0. Thus exp(Delta E / T) is always a probability strictly between 0 and 1.",
              "A Plateau is a flat area where all neighbors have the identical value; a Ridge is an ascending sequence of local maxima where uphill steps require diagonal moves not permitted by single-variable steps.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. State Space Landscapes & The Hill Climbing Dilemma",
              body: [
                "When the path to the goal is irrelevant and only the final configuration matters (e.g., 8-Queens puzzle, VLSI circuit layout, traveling salesperson problem), ==purple:Local Search Algorithms== evaluate configurations without retaining search paths, operating in $O(1)$ constant memory.",
                "Landscape Topography & Failure Modes of Pure Hill Climbing:",
                "1. Local Maxima: A peak that is higher than all neighboring states but lower than the global maximum. Greedy hill climbing halts permanently.",
                "2. Plateaus: Flat regions where all neighboring states possess the identical objective value (flat local maxima or shoulders). Hill climbing wanders aimlessly in a random walk.",
                "3. Ridges: Sloped areas where navigation requires simultaneous changes in multiple variables. Single-variable steepest-ascent oscillates back and forth, making negligible progress.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Simulated Annealing & The Metropolis Criterion",
              body: [
                "Inspired by the physical annealing process in metallurgy (where liquid metal is cooled slowly to form a crystal with minimal defect energy), ==yellow:Simulated Annealing== escapes local optima by intentionally accepting worsening moves with a controlled probability.",
                "The Metropolis Algorithm:",
                "At each time step $t$, the algorithm selects a random neighbor $s'$ of current state $s$.",
                "Let $\\Delta E = f(s') - f(s)$ be the change in the objective function.",
                "• If $\\Delta E > 0$ (the neighbor is superior): The transition is accepted unconditionally ($s \\leftarrow s'$).",
                "• If $\\Delta E \\le 0$ (the neighbor is inferior): The transition is accepted with probability:",
                "$$P = e^{\\frac{\\Delta E}{T}}$$",
                "Where $T = T(t)$ is the temperature parameter dictated by an annealing cooling schedule.",
                "Behavioral Dynamics Across the Cooling Schedule:",
                "• When $T \\to \\infty$ (early iterations): $\\frac{\\Delta E}{T} \\to 0 \\implies e^0 = 1$. The algorithm accepts almost all downhill moves, freely exploring the entire state landscape like a random walk.",
                "• When $T \\to 0$ (late iterations): $\\frac{\\Delta E}{T} \\to -\\infty \\implies e^{-\\infty} = 0$. The probability of accepting downhill moves approaches zero, smoothly degenerating into pure greedy hill climbing to settle into the local basin.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. GATE Worked Numerical: Simulated Annealing Acceptance Probability",
              weightage: "2 Marks",
              trap: "Ensure Delta E is computed as (New Value - Current Value). For a worsening move, Delta E must be negative!",
              solutionSteps: [
                "Problem (Original Practice Problem · Modeled on GATE DA Pattern):",
                "A maximization problem is being solved using Simulated Annealing. Current state s has objective value f(s) = 85. A randomly generated neighbor s' has objective value f(s') = 75.",
                "Calculate the probability of accepting this move when:",
                "  (a) Temperature T = 20",
                "  (b) Temperature T = 5",
                "Step 1: Compute Delta E:",
                "  Delta E = f(s') - f(s) = 75 - 85 = -10.",
                "  Since Delta E < 0, the move is a worsening move, so it is accepted with probability P = exp(Delta E / T).",
                "Step 2: Calculate for T = 20:",
                "  P = exp(-10 / 20) = exp(-0.5) ≈ 0.6065 (60.65% chance of acceptance).",
                "Step 3: Calculate for T = 5:",
                "  P = exp(-10 / 5) = exp(-2.0) ≈ 0.1353 (13.53% chance of acceptance).",
                "Conclusion: As temperature cools from T = 20 to T = 5, the probability of accepting this 10-unit worsening move drops dramatically from 60.65% to 13.53%.",
              ],
            },
            {
              type: "resources",
              heading: "4. Primary References",
              sources: [
                {
                  title: "Artificial Intelligence: A Modern Approach (4th Edition)",
                  authors: "Stuart Russell, Peter Norvig",
                  year: "2020",
                  publisher: "Pearson",
                  link: "https://aima.cs.berkeley.edu",
                  relevance:
                    "Chapter 4: Search in Complex Environments — local search landscapes, Simulated Annealing proofs, and Genetic Algorithms.",
                },
              ],
            },
          ],
        },
        {
          id: "constraint-satisfaction-problems-ac3",
          title: "Constraint Satisfaction Problems & The AC-3 Arc Consistency Algorithm",
          slug: "constraint-satisfaction-problems-ac3",
          order: 2,
          estimatedMinutes: 30,
          tagline: "CSP formalization, Arc Consistency (AC-3), MRV, Degree heuristic, and Least Constraining Value.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A Constraint Satisfaction Problem (CSP) represents states as variable-value assignments subject to constraints. Arc Consistency (AC-3) prunes domain values that have no valid support, running in O(c * d^3) time for c binary constraints and maximum domain size d. Backtracking search integrates MRV (Minimum Remaining Values / Most Constrained Variable), Degree heuristic (tie-breaker), and LCV (Least Constraining Value) to solve CSPs efficiently.",
            keyFormulasAndRules: [
              "CSP Definition: Triplet (X, D, C) where X = {X1, ..., Xn} variables, D = {D1, ..., Dn} domains, C = {C1, ..., Cm} constraints.",
              "Arc Consistency Definition: Directed arc Xi -> Xj is consistent if for EVERY value x in Di, there exists at least one value y in Dj that satisfies the binary constraint between Xi and Xj.",
              "AC-3 Time Complexity: O(c * d^3), where c is number of binary constraints (edges in constraint graph) and d is maximum domain size.",
              "MRV Heuristic (Variable Selection): Choose the variable with the FEWEST remaining legal values in its domain ('fail-first' principle).",
              "Degree Heuristic (Tie-breaker): Choose the variable involved in the LARGEST number of constraints with other unassigned variables.",
              "LCV Heuristic (Value Selection): Choose the value that rules out the FEWEST choices for neighboring unassigned variables ('fail-last' principle).",
            ],
            examPitfalls: [
              "Arc Consistency is DIRECTIONAL! The arc Xi -> Xj is consistent if every value of Xi has a partner in Xj. This does NOT automatically mean Xj -> Xi is consistent!",
              "When a value is deleted from Di during AC-3, you MUST re-insert all incoming arcs Xk -> Xi (where Xk is a neighbor of Xi, k != j) back into the queue!",
              "AC-3 alone does NOT always find a complete solution: an arc-consistent CSP can still have NO valid solution (e.g. 3-coloring of K4 with 2 colors). Backtracking is still required.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Formal Definition of Constraint Satisfaction Problems (CSPs)",
              body: [
                "Standard search treats states as atomic black boxes. In contrast, ==purple:Constraint Satisfaction Problems (CSPs)== employ a factored representation consisting of three components:",
                "1. Variables $X = \\{X_1, X_2, \\dots, X_n\\}$.",
                "2. Domains $D = \\{D_1, D_2, \\dots, D_n\\}$, where each $D_i$ is a set of allowable values for $X_i$.",
                "3. Constraints $C = \\{C_1, C_2, \\dots, C_m\\}$, where each constraint specifies a subset of variables and allowable tuples of values (e.g., $X_1 \\neq X_2$).",
                "A state is an assignment of values to variables. An assignment is **consistent** if it violates no constraints, and **complete** if every variable is assigned. A solution is a complete, consistent assignment.",
              ],
            },
            {
              type: "explanation",
              heading: "2. The AC-3 Arc Consistency Algorithm",
              body: [
                "Constraint propagation prunes variable domains before and during search. The most influential propagation algorithm is ==yellow:AC-3 (Arc Consistency 3)==.",
                "Definition of Arc Consistency:",
                "A directed arc $X_i \\to X_j$ is arc-consistent if for every value $x \\in D_i$, there exists at least one value $y \\in D_j$ such that $(x, y)$ satisfies the binary constraint between $X_i$ and $X_j$.",
                "The AC-3 Algorithm Execution:",
                "1. Initialize a queue $Q$ containing all directed binary constraint arcs in the CSP: $Q = \\{(X_i, X_j), (X_j, X_i) \\mid \\text{for all constrained pairs } X_i, X_j\\}$.",
                "2. While $Q$ is not empty:",
                "   • Remove an arc $(X_i, X_j)$ from $Q$.",
                "   • Execute `Revise(Xi, Xj)`: For each $x \\in D_i$, if no value $y \\in D_j$ satisfies the constraint, remove $x$ from $D_i$.",
                "   • If `Revise` modified $D_i$:",
                "     - If $D_i$ becomes empty, return FAILURE (no solution exists).",
                "     - Otherwise, re-insert into $Q$ all arcs $(X_k, X_i)$ where $X_k$ is a neighbor of $X_i$ ($k \\neq j$).",
                "Time Complexity: An arc $(X_k, X_i)$ can be inserted into $Q$ at most $d$ times (since $D_i$ has at most $d$ values to delete). With $c$ binary constraints, total arc revisions is at most $2c \\cdot d$. Each revision inspects at most $d^2$ value pairs. Hence, total AC-3 time complexity is $O(c \\cdot d^3)$.",
              ],
            },
            {
              type: "explanation",
              heading: "3. Backtracking Search Heuristics: MRV, Degree & LCV",
              body: [
                "When constraint propagation leaves multiple values in domains, CSP search uses Depth-First Backtracking augmented with three classic heuristics:",
                "1. Minimum Remaining Values (MRV / Most Constrained Variable):",
                "   • Selects the unassigned variable with the fewest legal values left in its domain.",
                "   • Philosophy: 'Fail-first' — if a variable is going to fail, fail immediately to prune the search tree early.",
                "2. Degree Heuristic (Tie-Breaker for MRV):",
                "   • Selects the variable involved in the largest number of constraints with other *unassigned* variables.",
                "   • Philosophy: Reduces the branching factor of future variables by constraining them early.",
                "3. Least Constraining Value (LCV):",
                "   • Once a variable is chosen, selects the value that rules out the fewest choices for neighboring unassigned variables.",
                "   • Philosophy: 'Fail-last' — leaves maximum flexibility for remaining unassigned variables to find a solution.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "4. GATE DA Worked Numerical: AC-3 Domain Pruning Trace",
              weightage: "2 Marks",
              trap: "Notice that arc consistency is directional: testing Xi -> Xj removes values from Xi, NOT Xj!",
              solutionSteps: [
                "Problem (Original Practice Problem · Modeled on GATE DA Pattern):",
                "Consider two variables X and Y with domains D_X = {1, 2, 3, 4} and D_Y = {1, 2, 3, 4}.",
                "The binary constraint is: X < Y - 1 (or equivalently, Y >= X + 2).",
                "Trace AC-3 domain pruning on the directed arcs X -> Y and Y -> X.",
                "Step 1: Test Arc X -> Y (Prune values from D_X that have no valid partner in D_Y):",
                "  For x = 1: Is there y in D_Y such that 1 < y - 1 => y > 2? Yes (y = 3, 4). Keep x = 1.",
                "  For x = 2: Is there y in D_Y such that 2 < y - 1 => y > 3? Yes (y = 4). Keep x = 2.",
                "  For x = 3: Is there y in D_Y such that 3 < y - 1 => y > 4? Max y is 4, so no y > 4 exists! Prune x = 3 from D_X.",
                "  For x = 4: Requires y > 5. No such y exists! Prune x = 4 from D_X.",
                "  Updated Domain: D_X = {1, 2}.",
                "Step 2: Test Arc Y -> X (Prune values from D_Y that have no valid partner in D_X = {1, 2}):",
                "  Constraint: y >= x + 2.",
                "  For y = 1: Requires 1 >= x + 2 => x <= -1. D_X has {1, 2}. No partner! Prune y = 1.",
                "  For y = 2: Requires 2 >= x + 2 => x <= 0. No partner in D_X! Prune y = 2.",
                "  For y = 3: Requires 3 >= x + 2 => x <= 1. Partner x = 1 exists in D_X! Keep y = 3.",
                "  For y = 4: Requires 4 >= x + 2 => x <= 2. Partners x = 1, 2 exist! Keep y = 4.",
                "  Updated Domain: D_Y = {3, 4}.",
                "Step 3: Verify Consistency of Both Arcs:",
                "  Arc X -> Y: D_X = {1, 2}, D_Y = {3, 4}. Every x has a partner y. Consistent!",
                "  Arc Y -> X: Every y has a partner x. Consistent!",
                "Conclusion: Final pruned domains are D_X = {1, 2} and D_Y = {3, 4}.",
              ],
            },
            {
              type: "resources",
              heading: "5. Primary References",
              sources: [
                {
                  title: "Artificial Intelligence: A Modern Approach (4th Edition)",
                  authors: "Stuart Russell, Peter Norvig",
                  year: "2020",
                  publisher: "Pearson",
                  link: "https://aima.cs.berkeley.edu",
                  relevance:
                    "Chapter 6: Constraint Satisfaction Problems — formal algorithms for AC-3, Forward Checking, and backtracking heuristics.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: ADVERSARIAL SEARCH & GAME THEORY
    // =========================================================================
    {
      id: "da-ai-module-3-adversarial",
      title: "Module 3: Adversarial Search & Game Theory",
      slug: "adversarial-search",
      description:
        "Two-player zero-sum perfect information games, Minimax decision trees, Alpha-Beta pruning cutoffs, evaluation functions, and games with chance (Expectiminimax).",
      order: 3,
      lessons: [
        {
          id: "minimax-and-alpha-beta-pruning",
          title: "Minimax Decision Trees & Alpha-Beta Pruning",
          slug: "minimax-and-alpha-beta-pruning",
          order: 1,
          estimatedMinutes: 28,
          tagline: "Alpha (MAX lower bound) >= Beta (MIN upper bound) triggers immediate subtree cutoff.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Alpha-Beta Pruning returns the identical Minimax value while pruning branches that cannot influence the final decision. A cutoff occurs the moment alpha >= beta. In optimal move ordering, Alpha-Beta evaluates O(b^(d/2)) leaves instead of O(b^d), effectively doubling the reachable search depth.",
            keyFormulasAndRules: [
              "Minimax Value: V(s) = max_{a} V(Result(s, a)) for MAX node; min_{a} V(Result(s, a)) for MIN node; Utility(s) for terminal leaves.",
              "Alpha (alpha): The highest utility choice found so far along the path for MAX (initialized to -infinity).",
              "Beta (beta): The lowest utility choice found so far along the path for MIN (initialized to +infinity).",
              "Pruning Condition: Prune remaining child subtrees as soon as alpha >= beta.",
              "Node Complexity: Standard Minimax = O(b^d); Alpha-Beta with Best Ordering = O(b^(d/2)); Alpha-Beta with Worst Ordering = O(b^d).",
              "Heuristic Evaluation Functions: Linearly weighted feature sum: Eval(s) = w1*f1(s) + w2*f2(s) + ... + wn*fn(s).",
            ],
            examPitfalls: [
              "Alpha-Beta pruning changes WHICH nodes are evaluated, but NEVER alters the final Minimax value or root move choice!",
              "Remember that MAX updates alpha, and MIN updates beta. Alpha only increases; Beta only decreases.",
              "Pruned nodes are NEVER visited or evaluated. In numerical exam questions, count carefully which leaves were skipped.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Two-Player Zero-Sum Games & The Minimax Principle",
              body: [
                "In classical game playing (Chess, Checkers, Go), two adversarial players alternate turns in a zero-sum environment: any advantage gained by player MAX directly corresponds to an equivalent loss for player MIN ($U(\\text{MAX}) + U(\\text{MIN}) = 0$).",
                "The Minimax Equation:",
                "$$\\text{Minimax}(s) = \\begin{cases} \\text{Utility}(s) & \\text{if } s \\text{ is terminal} \\\\ \\max_{a \\in \\text{Actions}(s)} \\text{Minimax}(\\text{Result}(s, a)) & \\text{if Player}(s) = \\text{MAX} \\\\ \\min_{a \\in \\text{Actions}(s)} \\text{Minimax}(\\text{Result}(s, a)) & \\text{if Player}(s) = \\text{MIN} \\end{cases}$$",
                "Minimax performs a complete depth-first exploration of the game tree. On a game with branching factor $b$ and maximum depth $d$, standard Minimax evaluates $O(b^d)$ terminal states, which is computationally intractable for complex games (e.g., Chess has $b \\approx 35, d \\approx 80 \\implies 35^{80}$ states).",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Alpha-Beta Pruning Algorithm",
              body: [
                "==yellow:Alpha-Beta Pruning== computes the exact Minimax decision while pruning entire subtrees that cannot affect the root's decision.",
                "Parameters Maintained Along the Path:",
                "• $\\alpha$ (Alpha): The value of the best (highest-value) choice found so far for MAX along the path. Initialized to $-\\infty$.",
                "• $\\beta$ (Beta): The value of the best (lowest-value) choice found so far for MIN along the path. Initialized to $+\\infty$.",
                "Cutoff Rule:",
                "As soon as $\\alpha \\ge \\beta$ at any node, stop searching its remaining children and return immediately!",
                "Intuition: If MAX already has a guaranteed path yielding $\\alpha = 5$, and at a descendant MIN node, MIN has found a move yielding $\\beta = 3$, MAX will never allow play to reach this MIN node (MAX would pick the $\\alpha=5$ alternative earlier). Therefore, evaluating further moves for MIN is completely irrelevant.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. GATE DA Worked Example: Alpha-Beta Pruning Cutoff Count",
              weightage: "2 Marks (Compulsory in GATE DA)",
              trap: "Ensure that alpha is updated ONLY at MAX nodes, and beta is updated ONLY at MIN nodes!",
              solutionSteps: [
                "Problem (Original Practice Problem · Modeled on GATE DA Pattern):",
                "Consider a 2-ply game tree with root MAX node A having two MIN children B and C:",
                "  Node B has leaf children evaluated left-to-right: 3, 5.",
                "  Node C has leaf children evaluated left-to-right: 2, 8, 1.",
                "Step 1: At Root A (MAX):",
                "  Initializes alpha = -inf, beta = +inf.",
                "  Calls MIN child B with (alpha = -inf, beta = +inf).",
                "Step 2: At Left Child B (MIN):",
                "  - Evaluates leaf 3: beta = min(+inf, 3) = 3.",
                "  - Check cutoff: alpha (-inf) >= beta (3)? No.",
                "  - Evaluates leaf 5: beta = min(3, 5) = 3.",
                "  - Returns value 3 to Root A.",
                "Step 3: Back at Root A (MAX):",
                "  Updates alpha = max(-inf, 3) = 3.",
                "  Calls MIN child C with (alpha = 3, beta = +inf).",
                "Step 4: At Right Child C (MIN):",
                "  - Inherits alpha = 3, beta = +inf.",
                "  - Evaluates first leaf 2: beta = min(+inf, 2) = 2.",
                "  - Check Cutoff: alpha (3) >= beta (2) is TRUE! Cutoff occurs immediately!",
                "  - Leaves 8 and 1 are PRUNED without being evaluated.",
                "  - Node C returns value 2 to Root A.",
                "Step 5: At Root A (MAX):",
                "  Root value = max(3, 2) = 3. Best move is to node B.",
                "Conclusion: Root value is 3. Exactly 2 leaf nodes (8 and 1) are pruned.",
              ],
            },
            {
              type: "resources",
              heading: "4. Primary References",
              sources: [
                {
                  title: "Artificial Intelligence: A Modern Approach (4th Edition)",
                  authors: "Stuart Russell, Peter Norvig",
                  year: "2020",
                  publisher: "Pearson",
                  link: "https://aima.cs.berkeley.edu",
                  relevance:
                    "Chapter 5: Adversarial Search and Games — formal definitions of Minimax, Alpha-Beta pruning proofs, and move ordering theorems.",
                },
              ],
            },
          ],
        },
        {
          id: "games-with-chance-expectiminimax",
          title: "Stochastic Games & Expectiminimax Decision Trees",
          slug: "games-with-chance-expectiminimax",
          order: 2,
          estimatedMinutes: 24,
          tagline: "Chance nodes, expected value propagation, and evaluation function linearity constraints.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "In games with chance (Backgammon, Monopoly, Poker), game trees include Chance Nodes in addition to MAX and MIN nodes. Expectiminimax calculates the expected value sum_{s'} P(s') * V(s') at chance nodes. Because expected value is linear, heuristic evaluation functions MUST be positive linear transformations of true expected utility.",
            keyFormulasAndRules: [
              "Expectiminimax Value at Chance Node C: V(C) = sum_{s' in Outcomes(C)} P(s') * V(s').",
              "Tree Node Sequence: MAX -> Chance -> MIN -> Chance -> MAX ...",
              "Time Complexity of Expectiminimax: O(b^d * n^d), where b is branching factor, d is depth, and n is number of distinct chance outcomes.",
              "Linearity Invariance: If evaluation function h(s) is transformed by positive affine transformation h'(s) = a * h(s) + b (a > 0), the optimal move choice is PRESERVED. Non-linear monotonic transformations do NOT preserve choices in expectiminimax!",
            ],
            examPitfalls: [
              "In deterministic Minimax, any monotonic transformation preserves move choices. In Expectiminimax with chance nodes, ONLY positive linear (affine) transformations preserve move choices!",
              "Alpha-Beta pruning cannot prune chance nodes unless rigorous mathematical upper and lower bounds on leaf utilities are known.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Stochastic Games & Expectiminimax Trees",
              body: [
                "Real-world environments and games such as Backgammon include elements of chance (dice rolls, card shuffling). In stochastic game trees, we introduce a third type of node: the ==purple:Chance Node==.",
                "The Expectiminimax Formulation:",
                "$$\\text{Expectiminimax}(s) = \\begin{cases} \\text{Utility}(s) & \\text{if } s \\text{ is terminal} \\\\ \\max_{a} \\text{Expectiminimax}(\\text{Result}(s, a)) & \\text{if Player}(s) = \\text{MAX} \\\\ \\min_{a} \\text{Expectiminimax}(\\text{Result}(s, a)) & \\text{if Player}(s) = \\text{MIN} \\\\ \\sum_{s'} P(s') \\times \\text{Expectiminimax}(s') & \\text{if } s \\text{ is a Chance Node} \\end{cases}$$",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Linearity Requirement for Evaluation Functions",
              body: [
                "In standard deterministic Minimax, an evaluation function requires only an *order-preserving (monotonic)* scale: replacing evaluation $v$ with $v^3$ or $\\log(v)$ does not alter which move is maximum or minimum.",
                "However, in Expectiminimax, expected utility is a weighted linear sum: $\\sum P(i) v_i$.",
                "Applying a non-linear monotonic transformation alters the expectation! For example, expected value of outcomes $(1, 9)$ with $P = 0.5$ is $0.5(1) + 0.5(9) = 5$. If we apply non-linear transform $f(x) = x^2$, the expectation becomes $0.5(1) + 0.5(81) = 41$, which can invert the preferred decision compared to an alternative move.",
                "Theorem: An evaluation function in expectiminimax must be a **positive affine transformation** $f(x) = a x + b$ ($a > 0$) of the true probability of winning to preserve optimal move choices.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. GATE Worked Numerical: Expectiminimax Root Decision",
              weightage: "2 Marks",
              trap: "Weight each child of a chance node by its explicit probability before computing the expected value!",
              solutionSteps: [
                "Problem (Original Practice Problem · Modeled on GATE DA Pattern):",
                "A MAX node A has two possible moves leading to chance nodes C1 and C2.",
                "  Chance node C1 has outcomes: Left (prob 0.7, utility 10) and Right (prob 0.3, utility 20).",
                "  Chance node C2 has outcomes: Left (prob 0.5, utility 5) and Right (prob 0.5, utility 25).",
                "Calculate: (a) Expected value of C1, (b) Expected value of C2, and (c) The optimal decision at Root A.",
                "Step 1: Compute Expected Value of C1:",
                "  V(C1) = P(Left) * Utility(Left) + P(Right) * Utility(Right)",
                "  V(C1) = 0.7 * 10 + 0.3 * 20 = 7 + 6 = 13.",
                "Step 2: Compute Expected Value of C2:",
                "  V(C2) = P(Left) * Utility(Left) + P(Right) * Utility(Right)",
                "  V(C2) = 0.5 * 5 + 0.5 * 25 = 2.5 + 12.5 = 15.",
                "Step 3: Root Decision at MAX Node A:",
                "  V(A) = max(V(C1), V(C2)) = max(13, 15) = 15.",
                "  Optimal Action: Choose move to Chance Node C2.",
                "Conclusion: V(C1) = 13, V(C2) = 15; Root A selects C2.",
              ],
            },
            {
              type: "resources",
              heading: "4. Primary References",
              sources: [
                {
                  title: "Artificial Intelligence: A Modern Approach (4th Edition)",
                  authors: "Stuart Russell, Peter Norvig",
                  year: "2020",
                  publisher: "Pearson",
                  link: "https://aima.cs.berkeley.edu",
                  relevance:
                    "Chapter 5: Adversarial Search — Expectiminimax game trees and evaluation function transformations.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: PROPOSITIONAL & FIRST-ORDER LOGIC REASONING
    // =========================================================================
    {
      id: "da-ai-module-4-logic",
      title: "Module 4: Propositional & First-Order Logic Reasoning",
      slug: "logic-and-resolution",
      description:
        "Propositional logic, truth tables, satisfiability (SAT), Horn clauses, Forward/Backward Chaining, First-Order Logic, Skolemization, Most General Unifier (MGU), and Resolution Refutation.",
      order: 4,
      lessons: [
        {
          id: "propositional-logic-and-sat",
          title: "Propositional Logic: Entailment, CNF & Forward/Backward Chaining",
          slug: "propositional-logic-and-sat",
          order: 1,
          estimatedMinutes: 28,
          tagline: "Logical entailment KB |= alpha, CNF conversion, Horn clauses, and linear-time chaining algorithms.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Logical entailment KB |= alpha means that in every model where KB is true, alpha is also true (M(KB) subset of M(alpha)). CNF represents formulas as conjunctions of clauses (disjunctions of literals). A Definite clause has exactly one positive literal; a Horn clause has at most one positive literal. Forward and Backward Chaining determine entailment for Definite clauses in linear O(n) time.",
            keyFormulasAndRules: [
              "Entailment Definition: KB |= alpha <=> (KB and ~alpha) is unsatisfiable.",
              "Implication Equivalence: P -> Q <=> ~P or Q.",
              "De Morgan's Laws: ~(P and Q) <=> ~P or ~Q; ~(P or Q) <=> ~P and ~Q.",
              "Distributive Laws: P or (Q and R) <=> (P or Q) and (P or R).",
              "Definite Clause: A disjunction of literals containing EXACTLY ONE positive literal (e.g., ~A or ~B or C <=> (A and B) -> C).",
              "Horn Clause: A disjunction of literals with AT MOST ONE positive literal (includes Goal clauses with zero positive literals: ~A or ~B).",
              "Forward Chaining (Data-Driven): Fires rules whose premises are satisfied in KB, adding heads to known facts until query is proven.",
              "Backward Chaining (Goal-Driven): Works backwards from query, proving premises recursively; avoids inferring irrelevant facts.",
            ],
            examPitfalls: [
              "Do not confuse Validity and Satisfiability: A sentence is Valid (Tautology) if true in ALL models. A sentence is Satisfiable if true in AT LEAST ONE model.",
              "Forward Chaining and Backward Chaining are complete ONLY for Knowledge Bases consisting entirely of Definite / Horn clauses. For general clauses, Resolution Refutation is required.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Propositional Logic: Syntax, Models & Entailment",
              body: [
                "Propositional logic provides formal language for knowledge representation:",
                "• Syntax: Propositional symbols ($P, Q, R$) connected by Boolean connectives ($\\neg, \\land, \\lor, \\implies, \\iff$).",
                "• Models: A model $m$ is a complete assignment of truth values (True/False) to every propositional symbol. With $n$ symbols, there are exactly $2^n$ distinct models.",
                "• Entailment ($KB \\models \\alpha$): Knowledge Base $KB$ entails sentence $\\alpha$ if and only if $\\alpha$ is true in every model in which $KB$ is true ($M(KB) \\subseteq M(\\alpha)$).",
                "Theorem: $KB \\models \\alpha \\iff (KB \\land \\neg \\alpha) \\text{ is unsatisfiable}$. This fundamental equivalence forms the foundation of all resolution refutation automated theorem provers.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Horn Clauses & Linear-Time Chaining Algorithms",
              body: [
                "While general Boolean satisfiability (SAT) is NP-Complete, restricting knowledge bases to ==yellow:Definite Clauses== enables inference in linear $O(n)$ time.",
                "Definitions:",
                "• Definite Clause: A disjunction of literals with exactly one positive literal: $(\\neg P_1 \\lor \\neg P_2 \\lor \\dots \\lor \\neg P_k \\lor Q) \\equiv (P_1 \\land P_2 \\land \\dots \\land P_k) \\implies Q$.",
                "• Horn Clause: A disjunction of literals with at most one positive literal.",
                "Algorithms for Definite Clause Knowledge Bases:",
                "1. Forward Chaining (Data-Driven): Starts with known atomic facts. Whenever all premises of an implication $(P_1 \\land P_2) \\implies Q$ are satisfied, rule fires and adds $Q$ to the known database. Continues until query is generated or no new facts appear. Runs in linear $O(n)$ time with respect to the size of KB.",
                "2. Backward Chaining (Goal-Directed): Starts from the query goal $Q$. Searches for rules having $Q$ as conclusion, and recursively proves each of their premises. Ideal for interactive diagnostics.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. GATE Worked Numerical: CNF Conversion Pipeline",
              weightage: "2 Marks",
              trap: "Distribute OR over AND carefully: (A and B) or C becomes (A or C) and (B or C)!",
              solutionSteps: [
                "Problem (Original Practice Problem · Modeled on GATE DA Pattern):",
                "Convert the propositional sentence S = (P or Q) -> (R and S) into Conjunctive Normal Form (CNF).",
                "Step 1: Eliminate Implication (A -> B = ~A or B):",
                "  S = ~((P or Q)) or (R and S).",
                "Step 2: Apply De Morgan's Law to move negation inward:",
                "  ~((P or Q)) = (~P and ~Q).",
                "  Sentence becomes: (~P and ~Q) or (R and S).",
                "Step 3: Distribute OR over AND:",
                "  Let X = (~P and ~Q). We have X or (R and S) = (X or R) and (X or S).",
                "  Expand (X or R) = ((~P and ~Q) or R) = (~P or R) and (~Q or R).",
                "  Expand (X or S) = ((~P and ~Q) or S) = (~P or S) and (~Q or S).",
                "Step 4: Combine all resulting clauses:",
                "  CNF = (~P or R) and (~Q or R) and (~P or S) and (~Q or S).",
                "Conclusion: CNF consists of 4 binary clauses.",
              ],
            },
            {
              type: "resources",
              heading: "4. Primary References",
              sources: [
                {
                  title: "Artificial Intelligence: A Modern Approach (4th Edition)",
                  authors: "Stuart Russell, Peter Norvig",
                  year: "2020",
                  publisher: "Pearson",
                  link: "https://aima.cs.berkeley.edu",
                  relevance:
                    "Chapter 7: Logical Agents — Propositional logic, entailment proofs, and forward/backward chaining algorithms.",
                },
              ],
            },
          ],
        },
        {
          id: "fol-unification-and-resolution",
          title: "CNF Conversion, Skolemization, Unification & Resolution",
          slug: "fol-unification-and-resolution",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Converting to clausal form, Most General Unifier (MGU), and proving theorems via contradiction.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Resolution Refutation: To prove KB |= alpha, negate alpha (~alpha), add it to KB, convert all sentences to Clausal Normal Form (CNF), and apply the Resolution inference rule until the Empty Clause (box / contradiction) is derived. Unification finds the Most General Unifier (MGU) substitutions theta making two literals identical.",
            keyFormulasAndRules: [
              "Resolution Rule: From clauses (L1 or C1) and (~L2 or C2), where Subst(theta, L1) == Subst(theta, L2), derive Resolvent: Subst(theta, C1 or C2).",
              "CNF 6-Step Conversion: 1. Eliminate <-> and ->; 2. Move ~ inwards (De Morgan); 3. Standardize variables (rename apart); 4. Skolemize existential quantifiers; 5. Drop universal quantifiers; 6. Distribute OR over AND.",
              "Skolemization Rule: Replace exists y P(y) with P(C) (Skolem Constant). If exists y lies inside scope of forall x1, ..., xk, replace y with Skolem Function f(x1, ..., xk).",
              "Most General Unifier (MGU): The minimal substitution theta such that Subst(theta, p) == Subst(theta, q).",
              "Occurs-Check: Variable x CANNOT unify with a term containing x (e.g., cannot unify x with f(x)).",
            ],
            examPitfalls: [
              "Never use a Skolem constant when an existential quantifier is preceded by a universal quantifier! For example, forall x exists y Loves(x, y) becomes Loves(x, f(x)), NOT Loves(x, C).",
              "Resolution is Refutation-Complete (guaranteed to find a contradiction if one exists), but cannot be used to enumerate all valid theorems directly.",
              "Standardize variables apart before unifying clauses from different sentences so that identical variable names do not cause false conflicts.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. First-Order Logic (FOL) Formalism & Clausal Form Conversion",
              body: [
                "First-Order Logic extends propositional logic by introducing objects, relations (predicates), functions, and quantifiers ($\\forall$ universal, $\\exists$ existential).",
                "The 6-Step Clausal Form (CNF) Pipeline:",
                "1. Eliminate Implications: Replace $P \\implies Q$ with $\\neg P \\lor Q$, and $P \\iff Q$ with $(\\neg P \\lor Q) \\land (\\neg Q \\lor P)$.",
                "2. Move Negations Inward: $\\neg \\forall x P(x) \\equiv \\exists x \\neg P(x)$; $\\neg \\exists x P(x) \\equiv \\forall x \\neg P(x)$.",
                "3. Standardize Variables: Ensure each quantifier uses a distinct variable name: $(\\forall x P(x)) \\lor (\\forall x Q(x)) \\implies (\\forall x P(x)) \\lor (\\forall y Q(y))$.",
                "4. Skolemization (Eliminate $\\exists$):",
                "   • Outside scope of any $\\forall$: Replace $\\exists x P(x)$ with $P(A)$, where $A$ is a new **Skolem Constant**.",
                "   • Inside scope of $\\forall x_1, \\dots, x_k$: Replace $\\exists y P(y)$ with $P(f(x_1, \\dots, x_k))$, where $f$ is a new **Skolem Function**.",
                "5. Drop Universal Quantifiers: All remaining variables are implicitly universally quantified.",
                "6. Distribute $\\lor$ over $\\land$: Produce a conjunction of clauses (each clause is a disjunction of literals).",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Unification Algorithm & Most General Unifier (MGU)",
              body: [
                "To resolve two complementary literals with different variable names (e.g. $P(x)$ and $\\neg P(John)$), inference engines execute ==yellow:Unification==.",
                "Definition (MGU):",
                "A substitution $\\theta = \\{v_1 / t_1, v_2 / t_2, \\dots\\}$ is a unifier for literals $p$ and $q$ if $\\text{Subst}(\\theta, p) = \\text{Subst}(\\theta, q)$. An MGU is the unique (up to variable renaming) most general unifier that makes the least commitment to variable bindings.",
                "The Occurs-Check Rule:",
                "A variable $x$ cannot unify with a term $t$ if $x$ occurs inside $t$ (e.g. cannot unify $x$ with $f(x)$). Attempting to do so creates an infinite cyclic term $f(f(f(\\dots)))$.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. GATE DA Worked Example: Most General Unifier (MGU)",
              weightage: "2 Marks (Compulsory in GATE DA)",
              trap: "Apply substitutions from earlier arguments to subsequent arguments before matching them!",
              solutionSteps: [
                "Problem (Original Practice Problem · Modeled on GATE DA Pattern):",
                "Find the Most General Unifier (MGU) theta for literals:",
                "  Literal 1: P(x, f(y), z)",
                "  Literal 2: P(a, f(g(w)), g(x))",
                "  (where a is a constant, and x, y, z, w are variables).",
                "Step 1: Match 1st arguments: x and a.",
                "  Variable x unifies with constant a.",
                "  Substitution theta1 = { x / a }.",
                "Step 2: Apply theta1 to remaining arguments of both literals:",
                "  Literal 1 becomes: P(a, f(y), z)",
                "  Literal 2 becomes: P(a, f(g(w)), g(a))   (notice x replaced by a).",
                "Step 3: Match 2nd arguments: f(y) and f(g(w)):",
                "  Function symbols match (f == f).",
                "  Unify internal arguments: y and g(w).",
                "  Substitution theta2 = { y / g(w) }.",
                "Step 4: Match 3rd arguments: z and g(a):",
                "  Variable z unifies with compound term g(a).",
                "  Substitution theta3 = { z / g(a) }.",
                "Step 5: Compose all substitutions:",
                "  MGU theta = { x / a, y / g(w), z / g(a) }.",
                "Conclusion: MGU is { x / a, y / g(w), z / g(a) }.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "4. GATE DA Worked Example: Resolution Refutation Theorem Proof",
              weightage: "2 Marks",
              trap: "To prove theorem alpha, add NEGATION ~alpha to the Knowledge Base, NOT alpha itself!",
              solutionSteps: [
                "Problem (Original Practice Problem · Modeled on GATE DA Pattern):",
                "Given Knowledge Base KB in Clausal Form:",
                "  Clause 1: ~P(x) or Q(x)",
                "  Clause 2: P(A)",
                "  Clause 3: ~Q(y) or R(y)",
                "Prove by Resolution Refutation that KB entails R(A).",
                "Step 1: Negate the goal theorem:",
                "  Goal is R(A). Negated goal: ~R(A) (Clause 4).",
                "Step 2: Resolve Clause 1 with Clause 2:",
                "  C1: ~P(x) or Q(x)",
                "  C2: P(A)",
                "  Unify P(x) with P(A) => theta = { x / A }.",
                "  Resolvent C5: Q(A).",
                "Step 3: Resolve Clause 5 with Clause 3:",
                "  C5: Q(A)",
                "  C3: ~Q(y) or R(y)",
                "  Unify Q(y) with Q(A) => theta = { y / A }.",
                "  Resolvent C6: R(A).",
                "Step 4: Resolve Clause 6 with Clause 4 (Negated Goal):",
                "  C6: R(A)",
                "  C4: ~R(A)",
                "  Resolvent C7: [] (Empty Clause / Contradiction).",
                "Conclusion: Derivation of the Empty Clause proves that KB entails R(A) with mathematical certainty.",
              ],
            },
            {
              type: "resources",
              heading: "5. Primary References",
              sources: [
                {
                  title: "Artificial Intelligence: A Modern Approach (4th Edition)",
                  authors: "Stuart Russell, Peter Norvig",
                  year: "2020",
                  publisher: "Pearson",
                  link: "https://aima.cs.berkeley.edu",
                  relevance:
                    "Chapters 8 & 9: First-Order Logic and Inference in First-Order Logic — formal proofs of unification, Skolemization, and Robinson's Resolution Theorem.",
                },
                {
                  title: "A Machine-Oriented Logic Based on the Resolution Principle",
                  authors: "J. Alan Robinson (Journal of the ACM)",
                  year: "1965",
                  publisher: "ACM",
                  link: "https://dl.acm.org/doi/10.1145/321250.321253",
                  relevance:
                    "The landmark paper introducing the Resolution Principle and the first formal Unification algorithm.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: REASONING UNDER UNCERTAINTY & BAYESIAN NETWORKS
    // =========================================================================
    {
      id: "da-ai-module-5-uncertainty",
      title: "Module 5: Probabilistic Reasoning & Bayesian Networks",
      slug: "probabilistic-reasoning-bayes-nets",
      description:
        "Bayesian belief networks, conditional independence, d-separation rules (chains, forks, colliders), Markov blankets, and exact probabilistic inference via Variable Elimination.",
      order: 5,
      lessons: [
        {
          id: "bayesian-networks-and-d-separation",
          title: "Bayesian Networks, Conditional Independence & D-Separation",
          slug: "bayesian-networks-and-d-separation",
          order: 1,
          estimatedMinutes: 30,
          tagline: "DAG factorization, d-separation over chains/forks/colliders, and Markov blanket boundaries.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A Bayesian Network is a Directed Acyclic Graph (DAG) whose joint distribution factorizes as P(X1, ..., Xn) = prod_{i=1}^n P(Xi | Parents(Xi)). D-Separation determines conditional independence: A path is blocked if it contains an active non-collider that is conditioned on, OR a collider that is NOT conditioned on (and none of its descendants are conditioned on). A node is conditionally independent of all other nodes given its Markov Blanket (Parents + Children + Spouses).",
            keyFormulasAndRules: [
              "Joint Distribution Factorization: P(X1, ..., Xn) = prod_{i=1}^n P(Xi | Parents(Xi)).",
              "Chain Motif (X -> Y -> Z): X and Z are dependent marginally; INDEPENDENT given Y (P(Z | X, Y) = P(Z | Y)). Blocked when Y is observed.",
              "Fork / Common Cause (X <- Y -> Z): X and Z are dependent marginally; INDEPENDENT given Y. Blocked when Y is observed.",
              "Collider / V-Structure (X -> Y <- Z): X and Z are INDEPENDENT marginally; DEPENDENT given Y or any descendant of Y ('explaining away'). Blocked when Y and its descendants are NOT observed.",
              "Markov Blanket of Node X: MB(X) = Parents(X) union Children(X) union Spouses(X) (other parents of X's children).",
              "Parameter Counting: A Boolean node with k parents requires 2^k independent conditional probability parameters in its CPT.",
            ],
            examPitfalls: [
              "Remember the Collider Inversion Rule: Conditioning on a node BLOCKS chains and forks, but OPENS (activates) colliders!",
              "Do not forget Spouses when computing the Markov Blanket: Other parents of X's children MUST be included in MB(X)!",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Bayesian Networks & Joint Probability Factorization",
              body: [
                "A full joint probability distribution over $n$ Boolean variables requires $2^n - 1$ parameters, which is computationally intractable for large domains. ==purple:Bayesian Networks (Belief Networks)== exploit local conditional independence to represent distributions compactly.",
                "Structure of a Bayesian Network:",
                "1. A Directed Acyclic Graph (DAG) where nodes represent random variables $X_i$ and directed edges represent direct statistical dependencies.",
                "2. A Conditional Probability Table (CPT) for each node, specifying $P(X_i \\mid \\text{Parents}(X_i))$.",
                "The Chain Rule of Bayesian Networks:",
                "$$P(X_1, X_2, \\dots, X_n) = \\prod_{i=1}^n P(X_i \\mid \\text{Parents}(X_i))$$",
                "Parameter Efficiency: If a network has $n$ Boolean variables and each node has at most $k$ parents, the total number of parameters is at most $n \\cdot 2^k$, scaling linearly with $n$ instead of exponentially ($2^n$).",
              ],
            },
            {
              type: "comparison",
              heading: "2. The Three Canonical Motifs of D-Separation",
              leadParagraph:
                "Conditional independence behavior across the three fundamental 3-node connection topologies in a Bayesian Network:",
              columns: ["Connection Motif", "Topology", "Marginal Independence (Unconditioned)", "Conditional Independence Given Y"],
              criteria: [
                {
                  criterion: "Causal Chain (Serial)",
                  values: ["X -> Y -> Z", "Dependent: Information flows along the directed path", "INDEPENDENT: Observing Y blocks path (P(Z | X, Y) = P(Z | Y))"],
                },
                {
                  criterion: "Common Cause (Fork)",
                  values: ["X <- Y -> Z", "Dependent: Common parent creates statistical correlation", "INDEPENDENT: Observing Y blocks path (P(X, Z | Y) = P(X | Y) P(Z | Y))"],
                },
                {
                  criterion: "Common Effect (Collider / V-Structure)",
                  values: ["X -> Y <- Z", "INDEPENDENT: No information flows (P(X, Z) = P(X) P(Z))", "DEPENDENT: Observing Y (or Y's descendant) OPENS path ('explaining away')"],
                },
              ],
            },
            {
              type: "explanation",
              heading: "3. D-Separation (Directional Separation) Formal Algorithm",
              body: [
                "Two disjoint sets of nodes $A$ and $B$ are **d-separated** by conditioning set $E$ (denoted $A \\perp B \\mid E$) if every undirected path between any node in $A$ and any node in $B$ is **blocked**.",
                "A path is blocked by evidence set $E$ if it contains at least one node $V$ such that either:",
                "1. $V$ is a non-collider (chain $X \\to V \\to Z$ or fork $X \\leftarrow V \\to Z$) and $V \\in E$ (i.e. $V$ is observed), OR",
                "2. $V$ is a collider ($X \\to V \\leftarrow Z$) and neither $V$ nor any descendant of $V$ is in $E$ ($V \\notin E$ and $\\text{Descendants}(V) \\cap E = \\emptyset$).",
                "Theorem: If $A$ and $B$ are d-separated by $E$, then $A$ and $B$ are conditionally independent given $E$: $P(A, B \\mid E) = P(A \\mid E) P(B \\mid E)$.",
              ],
            },
            {
              type: "explanation",
              heading: "4. The Markov Blanket of a Node",
              body: [
                "In a Bayesian Network, a node $X$ is conditionally independent of all other nodes in the entire network given its ==yellow:Markov Blanket== $\\text{MB}(X)$.",
                "$$\\text{MB}(X) = \\text{Parents}(X) \\cup \\text{Children}(X) \\cup \\text{Spouses}(X)$$",
                "Where **Spouses** are the other parents of $X$'s children.",
                "Why Spouses are Mandatory:",
                "If child $Y$ is in the conditioning set, the collider $X \\to Y \\leftarrow Z$ is opened! Therefore, $X$ and $Z$ become dependent via 'explaining away'. To shield $X$ completely from $Z$, spouse $Z$ must also be conditioned on.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "5. GATE DA Worked Numerical: D-Separation & Independence Testing",
              weightage: "2 Marks (High Frequency in GATE DA)",
              trap: "Remember: conditioning on a collider OPENS the path, while conditioning on a non-collider BLOCKS the path!",
              solutionSteps: [
                "Problem (Original Practice Problem · Modeled on GATE DA Pattern):",
                "Consider a Bayesian Network with 5 nodes and directed edges:",
                "  A -> B",
                "  C -> B",
                "  B -> D",
                "  B -> E",
                "Determine whether the following conditional independence statements are True or False using d-separation:",
                "  (a) Is A independent of C given empty set {}?",
                "  (b) Is A independent of C given {B}?",
                "  (c) Is D independent of E given {B}?",
                "  (d) What is the Markov Blanket of node C?",
                "Step 1: Evaluate (a) A _|_ C | {}:",
                "  Path: A -> B <- C. Node B is a COLLIDER on this path.",
                "  Neither B nor its descendants (D, E) are observed (evidence set is empty).",
                "  Therefore, the collider B is BLOCKED.",
                "  The only path between A and C is blocked => A _|_ C | {} is TRUE!",
                "Step 2: Evaluate (b) A _|_ C | {B}:",
                "  Path: A -> B <- C. Node B is a COLLIDER.",
                "  Node B IS OBSERVED in conditioning set {B}.",
                "  Observing a collider OPENS the path!",
                "  The path is now active => A _|_ C | {B} is FALSE (A and C become dependent via explaining away).",
                "Step 3: Evaluate (c) D _|_ E | {B}:",
                "  Path: D <- B -> E. Node B is a FORK (common cause).",
                "  Node B IS OBSERVED in conditioning set {B}.",
                "  Observing a fork BLOCKS the path.",
                "  No other paths exist => D _|_ E | {B} is TRUE!",
                "Step 4: Find Markov Blanket of Node C: MB(C):",
                "  • Parents(C) = {}",
                "  • Children(C) = { B }",
                "  • Spouses(C) (other parents of C's children B) = { A }",
                "  MB(C) = { B, A }.",
                "Conclusion: (a) True, (b) False, (c) True, (d) MB(C) = {A, B}.",
              ],
            },
            {
              type: "resources",
              heading: "6. Primary References",
              sources: [
                {
                  title: "Probabilistic Reasoning in Intelligent Systems: Networks of Plausible Inference",
                  authors: "Judea Pearl",
                  year: "1988",
                  publisher: "Morgan Kaufmann",
                  link: "https://www.sciencedirect.com/book/9780080514895",
                  relevance:
                    "The seminal foundational textbook introducing Bayesian Networks, d-separation, and belief propagation by Turing Award winner Judea Pearl.",
                },
                {
                  title: "Artificial Intelligence: A Modern Approach (4th Edition)",
                  authors: "Stuart Russell, Peter Norvig",
                  year: "2020",
                  publisher: "Pearson",
                  link: "https://aima.cs.berkeley.edu",
                  relevance:
                    "Chapter 12: Probabilistic Reasoning — clear proofs and diagrams of d-separation and Markov blanket boundaries.",
                },
              ],
            },
          ],
        },
        {
          id: "probabilistic-inference-in-belief-networks",
          title: "Exact & Approximate Inference in Bayesian Networks",
          slug: "probabilistic-inference-in-belief-networks",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Inference by enumeration, Variable Elimination factor algebra, and Likelihood Weighting sampling.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Inference in Bayesian Networks computes posterior probability P(Query | Evidence). Exact inference by Enumeration sums out hidden variables from the joint distribution in O(d^n) exponential time. Variable Elimination speeds this up by dynamic programming, storing intermediate factor products phi(X) and summing out one variable at a time. Approximate inference uses stochastic simulation (Prior Sampling, Rejection Sampling, Likelihood Weighting).",
            keyFormulasAndRules: [
              "Query Formulation: P(X | E = e) = alpha * P(X, E = e) = alpha * sum_Y P(X, E = e, Y), where Y are hidden unobserved variables, and alpha is normalization constant 1 / P(E = e).",
              "Variable Elimination Operations: 1. Factor Product: phi3(X, Y, Z) = phi1(X, Y) * phi2(Y, Z); 2. Factor Marginalization (Summing Out): phi'(X) = sum_Y phi(X, Y).",
              "Computational Complexity: Exact inference in general Bayesian networks is NP-Hard (and #P-Hard). On polytrees (singly connected DAGs with no undirected loops), Variable Elimination runs in linear O(n) time.",
              "Likelihood Weighting: Fixes evidence variables to their observed values and weights each generated sample by the likelihood of observed evidence: w = prod_{E_i in Evidence} P(E_i = e_i | Parents(E_i)). Avoids discarding samples.",
            ],
            examPitfalls: [
              "Always remember to normalize by alpha = 1 / (P(X=true, e) + P(X=false, e)) at the final step when computing conditional probabilities!",
              "Variable Elimination complexity depends critically on the Elimination Ordering: a poor variable ordering creates giant intermediate factors with exponential state size.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Probabilistic Inference Task",
              body: [
                "The fundamental inference query in a Bayesian Network consists of:",
                "• Query Variable $X$: The target variable whose posterior distribution we wish to compute.",
                "• Evidence Variables $E = \\{E_1, \\dots, E_k\\}$: Variables observed to have specific instantiated values $e = \\{e_1, \\dots, e_k\\}$.",
                "• Hidden Variables $Y = \\{Y_1, \\dots, \\dots, Y_m\\}$: All remaining unobserved non-query variables in the network ($Y = \\text{Variables} \\setminus (\\{X\\} \\cup E)$).",
                "We compute $P(X \\mid E = e)$ by marginalizing out all hidden variables:",
                "$$P(X \\mid E = e) = \\alpha P(X, E = e) = \\alpha \\sum_{y_1} \\sum_{y_2} \\dots \\sum_{y_m} P(X, e, y_1, y_2, \\dots, y_m)$$",
                "Where $\\alpha = \\frac{1}{P(E = e)} = \\frac{1}{\\sum_x P(X = x, E = e)}$ is the normalization constant.",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Variable Elimination (VE) Algorithm",
              body: [
                "Enumeration repeats identical sub-calculations exponentially many times. ==yellow:Variable Elimination== computes the sum efficiently by moving summations inside products (algebraic distributive law $ab + ac = a(b + c)$).",
                "Core Operations on Factors:",
                "1. Pointwise Factor Product: Multiplying two factors $\\phi_1(A, B)$ and $\\phi_2(B, C)$ yields a new factor $\\phi_3(A, B, C) = \\phi_1(A, B) \\cdot \\phi_2(B, C)$.",
                "2. Summing Out (Marginalization): Summing out variable $B$ from factor $\\phi_3(A, B)$ yields a reduced factor $\\phi_4(A) = \\sum_b \\phi_3(A, B = b)$.",
                "Variable Elimination Protocol:",
                "1. Collect all initial CPTs as factors $\\Phi$.",
                "2. Set instantiated evidence values $E = e$ across all factors.",
                "3. Choose an elimination ordering for hidden variables $Y_1, Y_2, \\dots, Y_m$.",
                "4. For each hidden variable $Y_j$:",
                "   • Remove from $\\Phi$ all factors mentioning $Y_j$.",
                "   • Multiply these factors together into a single composite factor.",
                "   • Sum out $Y_j$ from this factor.",
                "   • Insert the resulting factor back into $\\Phi$.",
                "5. Multiply remaining factors containing query $X$ and normalize by $\\alpha$.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. GATE DA Worked Numerical: Exact Inference Calculation",
              weightage: "2 Marks (High Frequency in GATE DA)",
              trap: "Be sure to normalize at the end so probabilities P(X=true|e) + P(X=false|e) = 1!",
              solutionSteps: [
                "Problem (Original Practice Problem · Modeled on GATE DA Pattern):",
                "Consider a 3-node Bayesian Network: Cloud -> Rain -> Traffic (C -> R -> T).",
                "Given CPT probabilities:",
                "  P(C = true) = 0.5",
                "  P(R = true | C = true) = 0.8;   P(R = true | C = false) = 0.2",
                "  P(T = true | R = true) = 0.9;   P(T = true | R = false) = 0.1",
                "Calculate P(C = true | T = true).",
                "Step 1: Formulate the unnormalized joint query:",
                "  P(C, T = true) = sum_{r in {true, false}} P(C) * P(R = r | C) * P(T = true | R = r)",
                "Step 2: Compute for C = true:",
                "  P(C=t, T=t) = P(C=t) * [ P(R=t|C=t) * P(T=t|R=t) + P(R=f|C=t) * P(T=t|R=f) ]",
                "  P(C=t, T=t) = 0.5 * [ (0.8 * 0.9) + (0.2 * 0.1) ]",
                "  P(C=t, T=t) = 0.5 * [ 0.72 + 0.02 ] = 0.5 * 0.74 = 0.37.",
                "Step 3: Compute for C = false:",
                "  P(C=f, T=t) = P(C=f) * [ P(R=t|C=f) * P(T=t|R=t) + P(R=f|C=f) * P(T=t|R=f) ]",
                "  P(C=f, T=t) = 0.5 * [ (0.2 * 0.9) + (0.8 * 0.1) ]",
                "  P(C=f, T=t) = 0.5 * [ 0.18 + 0.08 ] = 0.5 * 0.26 = 0.13.",
                "Step 4: Normalize by total evidence probability P(T = true):",
                "  P(T = true) = 0.37 + 0.13 = 0.50.",
                "  P(C = true | T = true) = 0.37 / 0.50 = 0.74.",
                "  P(C = false | T = true) = 0.13 / 0.50 = 0.26.",
                "Conclusion: P(C = true | T = true) = 0.74 (74%).",
              ],
            },
            {
              type: "resources",
              heading: "4. Primary References",
              sources: [
                {
                  title: "Artificial Intelligence: A Modern Approach (4th Edition)",
                  authors: "Stuart Russell, Peter Norvig",
                  year: "2020",
                  publisher: "Pearson",
                  link: "https://aima.cs.berkeley.edu",
                  relevance:
                    "Chapter 12: Probabilistic Reasoning — formal algorithms for Variable Elimination, sampling techniques, and complexity proofs.",
                },
                {
                  title: "Probabilistic Graphical Models: Principles and Techniques",
                  authors: "Daphne Koller, Nir Friedman",
                  year: "2009",
                  publisher: "MIT Press",
                  link: "https://mitpress.mit.edu/9780262013192",
                  relevance:
                    "The comprehensive graduate-level reference on factor operations, elimination orderings, and clique trees.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
