import { CourseMeta } from "./types";

export const CALCULUS_OPTIMIZATION_COURSE: CourseMeta = {
  id: "calculus-and-optimization",
  title: "Calculus and Optimization",
  slug: "calculus-and-optimization",
  subjectSlug: "calculus-and-optimization",
  shortTitle: "Calculus & Opt",
  icon: "📈",
  color: "bg-fuchsia-400",
  tagline:
    "Master single/multivariable calculus, Taylor series, convexity, KKT conditions, duality, Gradient Descent, and Newton's method for GATE DA.",
  description:
    "A comprehensive academic study notebook covering single and multivariable limits, L'Hôpital's rule, Mean Value Theorems, Taylor and Maclaurin expansions, directional derivatives, gradient vectors, Hessian curvature matrices, critical point classification, convex sets and functions, Jensen's inequality, Lagrangian duality, Slater's condition, method of Lagrange multipliers, Karush-Kuhn-Tucker (KKT) conditions, Gradient Descent convergence dynamics, Lipschitz smoothness, and Newton-Raphson second-order optimization. Modeled on the reference Operating Systems benchmark for the official GATE Data Science & AI (DA) curriculum.",
  level: "Undergraduate / GATE DA",
  estimatedHours: 40,
  prerequisites: [
    "High school single-variable differentiation and definite integration",
    "Basic vector dot products and linear algebra matrix multiplication",
  ],
  learningOutcomes: [
    "Evaluate indeterminate limits using L'Hôpital's rule and apply Rolle's and Lagrange's Mean Value Theorems to interval root analysis",
    "Construct Taylor and Maclaurin polynomial series approximations and compute truncation error bounds",
    "Calculate gradient vectors, Jacobian matrices, and Hessian curvature matrices for multivariate functions",
    "Classify unconstrained multivariable critical points into local minima, local maxima, and saddle points via Hessian eigenvalues",
    "Prove function and set convexity using first-order and second-order conditions (Hessian positive semi-definiteness)",
    "Apply Jensen's inequality to derive information-theoretic bounds and optimization inequalities",
    "Formulate optimization problems using the Method of Lagrange Multipliers for equality constraints and interpret shadow prices",
    "Apply the Karush-Kuhn-Tucker (KKT) conditions (Stationarity, Primal Feasibility, Dual Feasibility, Complementary Slackness) to solve constrained nonlinear programs",
    "Derive Lagrange dual functions, verify weak duality, and evaluate strong duality via Slater's constraint qualification",
    "Analyze Gradient Descent learning rates, prove convergence under L-Lipschitz smoothness, and implement Newton's second-order optimization step",
  ],
  gateScope: "GATE 2027 DA scope",
  gateBranches: ["da"],
  gateSyllabusTopics: [
    "Functions of single variable, limit, continuity and differentiability, Taylor series, maxima and minima",
    "Mean value theorems (Rolle's, Lagrange's MVT, Cauchy's MVT)",
    "Functions of multiple variables, partial derivatives, gradient, directional derivatives, total differential, Jacobian, Hessian matrix",
    "Multivariate Taylor series, unconstrained multivariable optimization, saddle points",
    "Convex sets, convex functions, quasiconvexity, Jensen's inequality, first and second order convexity conditions",
    "Unconstrained optimization: Gradient Descent, learning rate, Lipschitz continuity, convergence analysis",
    "Second-order optimization: Newton's method, quadratic convergence, Hessian inversion",
    "Constrained optimization: Method of Lagrange multipliers, equality constraints",
    "Karush-Kuhn-Tucker (KKT) conditions, complementary slackness, active and inactive constraints",
    "Lagrangian duality, primal problem, dual problem, weak duality, strong duality, Slater's condition",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: SINGLE-VARIABLE CALCULUS, LIMITS & TAYLOR SERIES
    // =========================================================================
    {
      id: "da-opt-module-1-single-variable",
      title: "Module 1: Single-Variable Calculus, Limits & Taylor Series",
      slug: "single-variable-calculus-and-limits",
      description:
        "Limits, L'Hôpital's rule for indeterminate forms, Mean Value Theorems (Rolle's, Lagrange's MVT), Taylor/Maclaurin polynomial expansions, and single-variable extrema.",
      order: 1,
      lessons: [
        {
          id: "limits-continuity-and-mean-value-theorems",
          title: "Limits, L'Hôpital's Rule & Mean Value Theorems",
          slug: "limits-continuity-and-mean-value-theorems",
          order: 1,
          estimatedMinutes: 28,
          tagline: "Indeterminate forms 0/0, inf/inf, 1^inf, L'Hôpital's rule, Rolle's theorem, and Lagrange's MVT average slope formula.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Lagrange's Mean Value Theorem: If f is continuous on [a, b] and differentiable on (a, b), there exists at least one c in (a, b) such that f'(c) = (f(b) - f(a)) / (b - a).",
            keyFormulasAndRules: [
              "L'Hôpital's Rule: If lim f(x)/g(x) yields 0/0 or inf/inf, then lim f(x)/g(x) = lim f'(x)/g'(x).",
              "Exponential Indeterminate Forms (1^inf, 0^0, inf^0): Take natural log: y = f(x)^{g(x)} => ln(y) = g(x) * ln(f(x)), then evaluate limit and exponentiate.",
              "Rolle's Theorem: If f is continuous on [a, b], differentiable on (a, b), and f(a) = f(b), then there exists c in (a, b) where f'(c) = 0.",
              "Cauchy's MVT: [f(b) - f(a)] / [g(b) - g(a)] = f'(c) / g'(c) for some c in (a, b).",
            ],
            examPitfalls: [
              "Never apply L'Hôpital's rule unless the expression is confirmed to be an indeterminate form (0/0 or inf/inf). Differentiating when the denominator limit is non-zero yields incorrect results.",
              "For 1^inf limits, lim [1 + g(x)]^{1/g(x)} = e as g(x) -> 0. Specifically, lim_{x -> a} [f(x)]^{g(x)} = exp( lim_{x -> a} g(x) * [f(x) - 1] ).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Limits, Indeterminate Forms & Mean Value Theorems",
              body: [
                "Limits describe the behavior of functions near points where direct evaluation fails or yields singular divisions.",
                "**L'Hôpital's Rule:**",
                "Applies directly to indeterminate forms `0/0` and `infinity/infinity`:",
                "`lim_{x -> a} f(x) / g(x) = lim_{x -> a} f'(x) / g'(x)`.",
                "For exponential forms `1^infinity`, `0^0`, and `infinity^0`, we transform via logarithms: `ln y = g(x) ln f(x) = ln f(x) / (1 / g(x))` to reduce to `0/0`.",
                "**Mean Value Theorems:**",
                "- **Rolle's Theorem:** If `f(a) = f(b)` on a differentiable interval, the tangent must be horizontal (`f'(c) = 0`) at least once.",
                "- **Lagrange's MVT:** Connects secant line slope to instantaneous slope: `f'(c) = (f(b) - f(a)) / (b - a)`.",
                "In machine learning, MVT is the foundation for proving Lipschitz continuity and bounding gradient growth.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Exponential Limit & MVT Root Interval",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Use the logarithmic transformation ln(y) to resolve the 1^inf indeterminate form.",
              solutionSteps: [
                "Problem: (a) Evaluate L = lim_{x -> 0} (1 + sin x)^{1/x}. (b) For f(x) = x^3 - x on [0, 2], find the value of c in (0, 2) satisfying Lagrange's Mean Value Theorem.",
                "Part (a): Evaluate L = lim_{x -> 0} (1 + sin x)^{1/x}:",
                "Step 1: Check form at x = 0: (1 + 0)^{1/0} = 1^infinity (Indeterminate form).",
                "Step 2: Let y = (1 + sin x)^{1/x} => ln y = (1/x) * ln(1 + sin x) = ln(1 + sin x) / x.",
                "Step 3: As x -> 0, ln(1 + 0) / 0 = 0/0. Apply L'Hôpital's rule:",
                "  Numerator derivative: d/dx [ln(1 + sin x)] = cos x / (1 + sin x).",
                "  Denominator derivative: d/dx [x] = 1.",
                "  lim_{x -> 0} [ cos x / (1 + sin x) ] / 1 = cos(0) / (1 + sin 0) = 1 / 1 = 1.",
                "Step 4: Exponentiate to recover L: ln L = 1 => L = e^1 = e ≈ 2.71828.",
                "Part (b): Find c for f(x) = x^3 - x on [0, 2]:",
                "Step 1: Compute average slope: f(0) = 0; f(2) = 2^3 - 2 = 8 - 2 = 6.",
                "  Average slope = [ f(2) - f(0) ] / [ 2 - 0 ] = 6 / 2 = 3.",
                "Step 2: Set instantaneous derivative f'(c) equal to 3:",
                "  f'(x) = 3*x^2 - 1.",
                "  3*c^2 - 1 = 3  =>  3*c^2 = 4  =>  c^2 = 4 / 3.",
                "  c = 2 / sqrt(3) ≈ 1.1547 (since c must lie in the open interval (0, 2)).",
                "Conclusion: (a) L = e; (b) c = 2 / sqrt(3) ≈ 1.1547.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Calculus: Early Transcendentals (8th Edition)",
                  authors: "James Stewart",
                  year: "2015",
                  publisher: "Cengage Learning",
                  relevance: "Chapter 4: Applications of Differentiation and Mean Value Theorems.",
                },
              ],
            },
          ],
        },
        {
          id: "taylor-series-and-single-variable-extrema",
          title: "Taylor Series Expansions & Single-Variable Extrema",
          slug: "taylor-series-and-single-variable-extrema",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Taylor & Maclaurin expansions, truncation error, critical points, and first/second derivative classification tests.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Taylor Series at x = a: f(x) = Sum_{k=0}^infinity [ f^{(k)}(a) / k! ] * (x - a)^k. Second-order approximation: f(x) ≈ f(a) + f'(a)(x - a) + (1/2) f''(a)(x - a)^2.",
            keyFormulasAndRules: [
              "Standard Maclaurin Expansions (a = 0):",
              "  e^x = 1 + x + x^2 / 2! + x^3 / 3! + ...",
              "  ln(1 + x) = x - x^2 / 2 + x^3 / 3 - x^4 / 4 + ... (for -1 < x <= 1).",
              "  sin x = x - x^3 / 3! + x^5 / 5! - ...",
              "  cos x = 1 - x^2 / 2! + x^4 / 4! - ...",
              "  1 / (1 - x) = 1 + x + x^2 + x^3 + ... (for |x| < 1).",
              "First Derivative Test: f'(c) = 0. If f' changes + to -, local max; if - to +, local min.",
              "Second Derivative Test: f'(c) = 0. If f''(c) > 0, local min; if f''(c) < 0, local max; if f''(c) = 0, test is inconclusive.",
            ],
            examPitfalls: [
              "f''(c) = 0 does NOT automatically imply an inflection point. For f(x) = x^4 at x = 0, f''(0) = 0, but x = 0 is a strict local minimum (not an inflection point).",
              "On closed intervals [a, b], ALWAYS check the boundary endpoints f(a) and f(b) alongside internal critical points when finding global extrema.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Polynomial Approximations & Local Landscape Curvature",
              body: [
                "**Taylor's Theorem:** Expresses any infinitely differentiable function as a polynomial series around expansion center a.",
                "**Truncation Error (Lagrange Remainder):**",
                "`R_n(x) = [ f^{(n+1)}(xi) / (n + 1)! ] * (x - a)^{n+1}` for some `xi in (a, x)`.",
                "In numerical optimization, the second-order Taylor polynomial `f(x) ≈ f(x_k) + f'(x_k) Delta x + (1/2) f''(x_k) (Delta x)^2` forms the exact quadratic surrogate minimized by Newton's method.",
                "**Single-Variable Extrema:**",
                "A point `c` is a **critical point** if `f'(c) = 0` or `f'(c)` does not exist.",
                "By Fermat's Theorem, interior local extrema can occur ONLY at critical points.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: 3rd-Order Taylor Approximation & Error",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Remember the alternating signs in ln(1 + u) = u - u^2/2 + u^3/3 - ... and apply the chain rule.",
              solutionSteps: [
                "Problem: Find the 3rd-degree Taylor polynomial P_3(x) for f(x) = ln(1 + 2x) centered at a = 0. Use P_3(x) to approximate ln(1.2), and find the absolute error compared to the exact value.",
                "Step 1: Compute derivatives of f(x) at a = 0:",
                "  f(x) = ln(1 + 2x)       => f(0) = ln(1) = 0.",
                "  f'(x) = 2 / (1 + 2x)     => f'(0) = 2.",
                "  f''(x) = -4 / (1 + 2x)^2 => f''(0) = -4.",
                "  f'''(x) = 16 / (1 + 2x)^3=> f'''(0) = 16.",
                "Step 2: Construct Taylor polynomial P_3(x):",
                "  P_3(x) = f(0) + f'(0)*x + [ f''(0) / 2! ]*x^2 + [ f'''(0) / 3! ]*x^3",
                "  P_3(x) = 0 + 2*x + (-4 / 2)*x^2 + (16 / 6)*x^3",
                "  P_3(x) = 2*x - 2*x^2 + (8 / 3)*x^3.",
                "Step 3: Approximate ln(1.2) by setting 1 + 2x = 1.2 => 2x = 0.2 => x = 0.1:",
                "  P_3(0.1) = 2(0.1) - 2(0.1)^2 + (8 / 3)(0.1)^3",
                "  P_3(0.1) = 0.2 - 2(0.01) + (8 / 3)(0.001) = 0.2 - 0.02 + 0.002667 = 0.182667.",
                "Step 4: Compare with exact value:",
                "  Exact ln(1.2) ≈ 0.182322.",
                "  Absolute Error = |0.182667 - 0.182322| ≈ 0.000345 (3.45 x 10^-4).",
                "Conclusion: P_3(x) = 2x - 2x^2 + (8/3)x^3; Approximation = 0.18267 with error < 0.00035.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Calculus (10th Edition)",
                  authors: "George B. Thomas, Maurice D. Weir, Joel Hass",
                  year: "2009",
                  publisher: "Pearson",
                  relevance: "Chapter 10: Infinite Sequences and Taylor Series.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: MULTIVARIABLE CALCULUS, GRADIENTS & HESSIANS
    // =========================================================================
    {
      id: "da-opt-module-2-multivariable",
      title: "Module 2: Multivariable Calculus, Gradients & Hessians",
      slug: "multivariable-calculus-and-hessians",
      description:
        "Partial derivatives, gradient vectors, directional derivatives, total differential, Jacobian matrices, Hessian curvature, and unconstrained critical point classification.",
      order: 2,
      lessons: [
        {
          id: "partial-derivatives-gradient-and-directional-derivatives",
          title: "Partial Derivatives, Gradients & Directional Derivatives",
          slug: "partial-derivatives-gradient-and-directional-derivatives",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Gradient vector grad(f), directional derivative D_u f = grad(f) . u, tangent hyperplanes, and Jacobian matrices.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Directional Derivative: D_u f(x) = grad(f(x)) . u for ANY unit vector ||u|| = 1. Maximum rate of increase is ||grad(f(x))|| in direction u = grad(f) / ||grad(f)||.",
            keyFormulasAndRules: [
              "Gradient Vector: grad(f) = [ df/dx1, df/dx2, ..., df/dxn ]^T.",
              "Steepest Descent Direction: -grad(f) points in the direction of maximum instantaneous decrease.",
              "Tangent Plane Equation at (x0, y0): z - z0 = (df/dx)(x - x0) + (df/dy)(y - y0).",
              "Jacobian Matrix J for F: R^n -> R^m: J_{ij} = dF_i / dx_j (size m x n).",
              "Chain Rule: d/dt f(x(t), y(t)) = (df/dx)*(dx/dt) + (df/dy)*(dy/dt) = grad(f) . [dx/dt, dy/dt]^T.",
            ],
            examPitfalls: [
              "Always check that direction vector v is normalized: u = v / ||v||. Using a non-unit vector scales the derivative incorrectly by ||v||.",
              "Directional derivative is ZERO in directions orthogonal to the gradient (tangent to level curves).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Multivariable Geometry, Gradients & Directional Derivatives",
              body: [
                "For a scalar field `f: R^n -> R`, the **Gradient Vector** `grad(f)` packages all first-order partial derivatives:",
                "`grad(f) = [ df/dx_1, df/dx_2, ..., df/dx_n ]^T`.",
                "**Geometric Meaning of the Gradient:**",
                "1. `grad(f)` is strictly orthogonal to the level curve (or level surface) `f(x) = c` at every point.",
                "2. `grad(f)` points in the direction of fastest increase.",
                "3. Its magnitude `||grad(f)||` is the maximum possible directional derivative.",
                "**The Directional Derivative:**",
                "For unit direction `u` (`||u|| = 1`), `D_u f(x) = lim_{h -> 0} [ f(x + h u) - f(x) ] / h = grad(f(x)) . u`.",
                "By Cauchy-Schwarz: `|D_u f| <= ||grad(f)|| * ||u|| = ||grad(f)||`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: 3D Directional Derivative & Normal Vector",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Normalize the given 3D direction vector before computing the inner product.",
              solutionSteps: [
                "Problem: Find the directional derivative of f(x, y, z) = x^2 * y * z + 2 * y^2 * z at point P(1, 1, 2) in the direction of vector v = [ 1, 2, 2 ]^T.",
                "Step 1: Compute partial derivatives of f:",
                "  df/dx = 2*x*y*z",
                "  df/dy = x^2 * z + 4*y*z",
                "  df/dz = x^2 * y + 2*y^2",
                "Step 2: Evaluate gradient vector at P(1, 1, 2):",
                "  df/dx = 2(1)(1)(2) = 4.",
                "  df/dy = (1)^2(2) + 4(1)(2) = 2 + 8 = 10.",
                "  df/dz = (1)^2(1) + 2(1)^2 = 1 + 2 = 3.",
                "  grad(f)(P) = [ 4, 10, 3 ]^T.",
                "Step 3: Normalize direction vector v:",
                "  ||v|| = sqrt( 1^2 + 2^2 + 2^2 ) = sqrt( 1 + 4 + 4 ) = sqrt(9) = 3.",
                "  Unit vector u = [ 1/3, 2/3, 2/3 ]^T.",
                "Step 4: Compute dot product D_u f = grad(f) . u:",
                "  D_u f = (4)(1/3) + (10)(2/3) + (3)(2/3)",
                "  D_u f = (4 / 3) + (20 / 3) + (6 / 3) = 30 / 3 = 10.",
                "Conclusion: The directional derivative at P in the direction of v is D_u f = 10.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Vector Calculus (6th Edition)",
                  authors: "Jerrold E. Marsden, Anthony Tromba",
                  year: "2011",
                  publisher: "W. H. Freeman",
                  relevance: "Chapter 2: Differentiation, gradients, and directional derivatives.",
                },
              ],
            },
          ],
        },
        {
          id: "multivariate-taylor-series-and-unconstrained-extrema",
          title: "Multivariate Taylor Approximations & Hessian Classification",
          slug: "multivariate-taylor-series-and-unconstrained-extrema",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Multivariate Taylor series, Hessian matrix H, critical points, eigenvalues, and the discriminant D = f_xx f_yy - (f_xy)^2.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Critical Point Classification: At critical point grad(f) = 0, Hessian H Positive Definite (all lambda_i > 0) => Local Min; H Negative Definite (all lambda_i < 0) => Local Max; H Indefinite => Saddle Point.",
            keyFormulasAndRules: [
              "Hessian Matrix H: H_{ij} = d^2 f / (dx_i dx_j). Symmetric for C^2 continuous functions.",
              "Second-Order Multivariate Taylor: f(x + Delta x) ≈ f(x) + grad(f)^T Delta x + (1/2) Delta x^T H Delta x.",
              "2D Discriminant Test: D = f_{xx} f_{yy} - (f_{xy})^2 = det(H).",
              "  If D > 0 and f_{xx} > 0: Local Minimum.",
              "  If D > 0 and f_{xx} < 0: Local Maximum.",
              "  If D < 0: Saddle Point (indefinite Hessian).",
              "  If D = 0: Test is Inconclusive (higher-order terms decide).",
            ],
            examPitfalls: [
              "A saddle point is NOT a local extremum. Optimization algorithms can get stuck at saddle points if gradients vanish.",
              "If det(H) > 0, the eigenvalues share the same sign, which matches the sign of f_{xx}. If det(H) < 0, eigenvalues have opposite signs (saddle point).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Hessian Curvature & Classification of Multivariable Critical Points",
              body: [
                "To optimize multivariable loss functions `L(w_1, ..., w_d)`, we locate **critical points** where `grad(f) = 0`.",
                "**The Hessian Matrix H:**",
                "Captures all second partial derivatives:",
                "`H = [ [d^2 f/dx_1^2, d^2 f/dx_1 dx_2], [d^2 f/dx_2 dx_1, d^2 f/dx_2^2] ]`.",
                "By Clairaut's theorem, `d^2 f / dx_i dx_j = d^2 f / dx_j dx_i`, so H is always **symmetric**.",
                "**Local Curvature Classification:**",
                "Near critical point `x*`, `f(x* + Delta x) - f(x*) ≈ (1/2) Delta x^T H(x*) Delta x`.",
                "- If `H > 0` (Positive Definite), quadratic form is strictly positive in all directions => **Local Minimum**.",
                "- If `H < 0` (Negative Definite), quadratic form is strictly negative => **Local Maximum**.",
                "- If `H` has both positive and negative eigenvalues => **Saddle Point**.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Complete Critical Point Classification",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Evaluate both critical points separately; check discriminant D and f_xx at each point.",
              solutionSteps: [
                "Problem: Find and classify all critical points of f(x, y) = x^3 + y^3 - 3*x*y.",
                "Step 1: Compute first partial derivatives and set to zero:",
                "  df/dx = 3*x^2 - 3*y = 0  =>  y = x^2",
                "  df/dy = 3*y^2 - 3*x = 0  =>  x = y^2",
                "Step 2: Solve the simultaneous system:",
                "  Substitute y = x^2 into x = y^2:",
                "  x = (x^2)^2 = x^4  =>  x^4 - x = 0  =>  x * (x^3 - 1) = 0.",
                "  Real solutions: x = 0 or x = 1.",
                "  If x = 0 => y = 0^2 = 0. Point 1: (0, 0).",
                "  If x = 1 => y = 1^2 = 1. Point 2: (1, 1).",
                "Step 3: Compute second partial derivatives (Hessian entries):",
                "  f_xx = 6*x",
                "  f_yy = 6*y",
                "  f_xy = -3",
                "  Discriminant D(x, y) = f_xx * f_yy - (f_xy)^2 = (6*x)*(6*y) - (-3)^2 = 36*x*y - 9.",
                "Step 4: Classify Point 1 at (0, 0):",
                "  D(0, 0) = 36(0)(0) - 9 = -9 < 0.",
                "  Since D < 0, Hessian is indefinite.",
                "  Conclusion for (0, 0): SADDLE POINT with value f(0, 0) = 0.",
                "Step 5: Classify Point 2 at (1, 1):",
                "  D(1, 1) = 36(1)(1) - 9 = 27 > 0.",
                "  f_xx(1, 1) = 6(1) = 6 > 0.",
                "  Since D > 0 and f_xx > 0, Hessian is Positive Definite.",
                "  Conclusion for (1, 1): LOCAL MINIMUM with value f(1, 1) = 1^3 + 1^3 - 3(1)(1) = -1.",
                "Summary: (0, 0) is a saddle point; (1, 1) is a strict local minimum.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Mathematics for Machine Learning",
                  authors: "Marc Peter Deisenroth, A. Aldo Faisal, Cheng Soon Ong",
                  year: "2020",
                  publisher: "Cambridge University Press",
                  relevance: "Chapter 5: Vector Calculus and Gradients of Matrices.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: CONVEXITY, JENSEN'S INEQUALITY & DUALITY
    // =========================================================================
    {
      id: "da-opt-module-3-convexity-duality",
      title: "Module 3: Convex Sets, Functions & Lagrangian Duality",
      slug: "convexity-and-lagrangian-duality",
      description:
        "Convex sets, convex functions, first/second-order convexity criteria, Jensen's inequality, global optimality, Lagrange dual functions, weak and strong duality, and Slater's condition.",
      order: 3,
      lessons: [
        {
          id: "convex-sets-convex-functions-and-jensens-inequality",
          title: "Convex Sets, Convex Functions & Jensen's Inequality",
          slug: "convex-sets-convex-functions-and-jensens-inequality",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Epigraphs, first/second-order convexity conditions, Hessian PSD H >= 0, and Jensen's inequality f(E[X]) <= E[f(X)].",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Global Optimality: For a convex function f defined on a convex set C, EVERY local minimum is guaranteed to be a GLOBAL minimum.",
            keyFormulasAndRules: [
              "Convex Set: For all x, y in C and theta in [0, 1], theta * x + (1 - theta) * y in C.",
              "Convex Function Definition: f(theta * x + (1 - theta) * y) <= theta * f(x) + (1 - theta) * f(y).",
              "First-Order Convexity Condition: f(y) >= f(x) + grad(f(x))^T (y - x) for all x, y in dom(f).",
              "Second-Order Convexity Condition: Hessian H(x) is Positive Semi-Definite (H(x) >= 0, all eigenvalues >= 0) for all x in dom(f).",
              "Jensen's Inequality: For any convex function f and random variable X, f(E[X]) <= E[f(X)].",
              "Strict Convexity: If H(x) is Positive Definite (all eigenvalues > 0), the global minimum is UNIQUE.",
            ],
            examPitfalls: [
              "The intersection of any arbitrary family of convex sets is ALWAYS convex; the union of convex sets is generally NOT convex.",
              "A linear function f(x) = c^T x is both convex AND concave (Hessian is zero matrix).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Foundations of Convex Analysis in Machine Learning",
              body: [
                "Convex optimization represents the fundamental boundary between computationally tractable and intractable problems.",
                "**Convex Sets:**",
                "A set C is convex if the line segment connecting any two points in C lies entirely within C.",
                "**Convex Functions:**",
                "A function `f` is convex if its **Epigraph** `epi(f) = { (x, t) : t >= f(x) }` is a convex set.",
                "**The Three Equivalent Characterizations of Convexity:**",
                "1. **Zeroth-Order:** `f(theta x + (1 - theta) y) <= theta f(x) + (1 - theta) f(y)` for all `theta in [0, 1]`.",
                "2. **First-Order:** The tangent hyperplane at any point lies entirely below the function graph: `f(y) >= f(x) + grad(f(x))^T (y - x)`.",
                "3. **Second-Order:** The Hessian matrix is Positive Semi-Definite (`H(x) >= 0`) everywhere on its convex domain.",
                "**Jensen's Inequality:**",
                "For convex `f`, `f(E[X]) <= E[f(X)]`. In statistics, this establishes that the arithmetic mean exceeds the geometric mean (`AM >= GM`), and forms the core of the EM algorithm and Variational Inference.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Proving Convexity via Hessian Matrix",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "To prove convexity everywhere, verify that all leading principal minors are non-negative for ALL values of (x, y).",
              solutionSteps: [
                "Problem: Prove that the function f(x, y) = exp(x - y) + x^2 + 2*y^2 is strictly convex everywhere on R^2.",
                "Step 1: Compute first partial derivatives:",
                "  df/dx = exp(x - y) + 2*x",
                "  df/dy = -exp(x - y) + 4*y",
                "Step 2: Compute second partial derivatives (Hessian entries):",
                "  f_xx = d/dx [exp(x - y) + 2*x] = exp(x - y) + 2.",
                "  f_yy = d/dy [-exp(x - y) + 4*y] = exp(x - y) + 4.",
                "  f_xy = d/dy [exp(x - y) + 2*x] = -exp(x - y).",
                "  Let a = exp(x - y) > 0 for all (x, y) in R^2.",
                "  Hessian H = [ [a + 2, -a], [-a, a + 4] ].",
                "Step 3: Test Positive Definiteness via Sylvester's Criterion:",
                "  Leading principal minor 1: D1 = f_xx = a + 2.",
                "    Since a = exp(x - y) > 0, D1 > 2 > 0 for all (x, y).",
                "  Leading principal minor 2: D2 = det(H) = (a + 2)*(a + 4) - (-a)^2.",
                "    D2 = (a^2 + 6*a + 8) - a^2 = 6*a + 8.",
                "    Since a > 0, D2 > 8 > 0 for all (x, y).",
                "Step 4: Conclusion on Definiteness:",
                "  Both leading principal minors (D1 > 0, D2 > 0) are strictly positive everywhere on R^2.",
                "  Thus, the Hessian matrix H is strictly Positive Definite everywhere on R^2.",
                "Conclusion: f(x, y) is strictly convex everywhere on R^2, guaranteeing a unique global minimum.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Convex Optimization",
                  authors: "Stephen Boyd, Lieven Vandenberghe",
                  year: "2004",
                  publisher: "Cambridge University Press",
                  relevance: "Chapter 2 & 3: Convex Sets and Convex Functions.",
                },
              ],
            },
          ],
        },
        {
          id: "lagrangian-duality-and-slaters-condition",
          title: "Lagrangian Duality, Dual Problem & Slater's Condition",
          slug: "lagrangian-duality-and-slaters-condition",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Lagrange dual function g(lambda, nu), concavity of dual, weak duality, strong duality, and Slater's condition.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Weak Duality: Dual optimal value d* <= Primal optimal value p* ALWAYS holds (duality gap p* - d* >= 0). Strong duality (d* = p*) holds for convex problems under Slater's condition.",
            keyFormulasAndRules: [
              "Primal Problem: min f0(x) s.t. f_i(x) <= 0 (i=1..m), h_j(x) = 0 (j=1..p).",
              "Lagrangian: L(x, lambda, nu) = f0(x) + Sum_{i=1}^m lambda_i f_i(x) + Sum_{j=1}^p nu_j h_j(x).",
              "Lagrange Dual Function: g(lambda, nu) = inf_x L(x, lambda, nu).",
              "Concavity Theorem: g(lambda, nu) is ALWAYS concave, even if the primal problem f0 is non-convex.",
              "Dual Problem: max g(lambda, nu) s.t. lambda >= 0.",
              "Slater's Constraint Qualification: If primal problem is convex and there exists a strictly feasible point x_tilde (f_i(x_tilde) < 0 for all non-affine inequalities), then Strong Duality holds (d* = p*).",
            ],
            examPitfalls: [
              "The dual function g(lambda, nu) provides a LOWER BOUND on the primal optimal value p* for ANY feasible lambda >= 0.",
              "Do not forget the non-negativity constraint on inequality dual multipliers: lambda >= 0.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Philosophy & Mechanics of Lagrangian Duality",
              body: [
                "Duality transforms a difficult constrained optimization problem in primal space into an alternative optimization problem in dual multiplier space.",
                "**The Lagrange Dual Function:**",
                "`g(lambda, nu) = inf_{x in D} L(x, lambda, nu) = inf_{x in D} [ f_0(x) + Sum lambda_i f_i(x) + Sum nu_j h_j(x) ]`.",
                "Because `g(lambda, nu)` is the pointwise infimum of affine functions in `(lambda, nu)`, **the dual function is always concave**, regardless of whether the primal problem is convex.",
                "**Weak vs Strong Duality:**",
                "- **Weak Duality:** `d* <= p*` (always true for any optimization problem).",
                "- **Strong Duality:** `d* = p*` (zero duality gap).",
                "**Slater's Condition:**",
                "Guarantees strong duality for convex optimization problems if there exists at least one interior strictly feasible point: `f_i(x) < 0` for all inequality constraints.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Deriving Dual Function & Verifying Duality",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Minimize the Lagrangian over x analytically before setting up the dual maximization.",
              solutionSteps: [
                "Problem: Consider the primal problem: minimize f(x) = (1/2) * x^2 subject to x >= 2 (rewritten as 2 - x <= 0). (a) Derive the Lagrange dual function g(lambda). (b) Solve the dual problem and verify strong duality.",
                "Step 1: Formulate Lagrangian with multiplier lambda >= 0:",
                "  L(x, lambda) = (1/2) * x^2 + lambda * (2 - x).",
                "Step 2: Find dual function g(lambda) = inf_x L(x, lambda):",
                "  dL/dx = x - lambda = 0  =>  x*(lambda) = lambda.",
                "  Substitute x* = lambda into L:",
                "  g(lambda) = (1/2) * lambda^2 + lambda * (2 - lambda)",
                "  g(lambda) = (1/2) * lambda^2 + 2*lambda - lambda^2 = 2*lambda - (1/2) * lambda^2.",
                "  Notice: g(lambda) is strictly concave (d^2 g / dlambda^2 = -1 < 0).",
                "Step 3: Solve the dual problem: maximize g(lambda) subject to lambda >= 0:",
                "  dg/dlambda = 2 - lambda = 0  =>  lambda* = 2.",
                "  Check feasibility: lambda* = 2 >= 0 (Feasible!).",
                "  Dual optimal value: d* = g(2) = 2(2) - (1/2)*(2^2) = 4 - 2 = 2.",
                "Step 4: Solve the primal problem directly:",
                "  f(x) = (1/2) * x^2 increases for x >= 0.",
                "  Subject to x >= 2, the minimum occurs at boundary x* = 2.",
                "  Primal optimal value: p* = f(2) = (1/2) * (2^2) = 2.",
                "Step 5: Compare primal and dual values:",
                "  p* = 2,  d* = 2  =>  p* - d* = 0 (Zero Duality Gap).",
                "Conclusion: Strong duality holds with optimal primal value p* = 2 and dual multiplier lambda* = 2.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Convex Optimization",
                  authors: "Stephen Boyd, Lieven Vandenberghe",
                  year: "2004",
                  publisher: "Cambridge University Press",
                  relevance: "Chapter 5: Duality and Slater's condition.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: CONSTRAINED OPTIMIZATION & KKT CONDITIONS
    // =========================================================================
    {
      id: "da-opt-module-4-constrained-kkt",
      title: "Module 4: Constrained Optimization & KKT Conditions",
      slug: "constrained-optimization-and-kkt",
      description:
        "Equality constraints via Lagrange multipliers, geometric gradient orthogonality, Karush-Kuhn-Tucker (KKT) conditions, and complementary slackness in SVMs.",
      order: 4,
      lessons: [
        {
          id: "method-of-lagrange-multipliers-for-equality-constraints",
          title: "The Method of Lagrange Multipliers",
          slug: "method-of-lagrange-multipliers-for-equality-constraints",
          order: 1,
          estimatedMinutes: 30,
          tagline: "grad(f) = lambda grad(g), collinear constraint normals, shadow prices, and constrained critical points.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Lagrange Multiplier Condition: At an equality constrained extremum of f(x) s.t. g(x) = 0, the gradient of the objective is parallel to the gradient of the constraint: grad(f) = lambda * grad(g).",
            keyFormulasAndRules: [
              "Lagrangian Function: L(x, lambda) = f(x) - lambda * g(x).",
              "Stationary System: grad_x L = 0 and grad_lambda L = 0 (recovering g(x) = 0).",
              "Multiple Constraints: grad(f) = Sum_{j=1}^k lambda_j * grad(g_j).",
              "Shadow Price Interpretation: df* / dc = lambda, where c is the perturbation in constraint g(x) = c.",
            ],
            examPitfalls: [
              "The constraint gradient grad(g) must be non-zero at the candidate point (Regularity condition / Constraint qualification).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Geometry of Equality Constrained Extrema",
              body: [
                "Consider minimizing `f(x)` constrained to surface `g(x) = 0`.",
                "**Geometric Principle:**",
                "At the optimum, the contour curve of `f` must be tangent to the constraint curve `g(x) = 0`. If they crossed transversely, moving along the constraint curve would continue to increase or decrease `f`.",
                "Since both curves share a tangent hyperplane at the contact point, their normal vectors (gradients) must be collinear:",
                "`grad(f(x*)) = lambda * grad(g(x*))`.",
                "**The Lagrangian Formulation:**",
                "`L(x, lambda) = f(x) - lambda * g(x)`.",
                "Setting `grad L = 0` converts the constrained problem into an unconstrained root-finding problem in `n + 1` variables.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Multi-Constraint Lagrange Optimization",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Set up the gradient proportionality system alongside both equality constraint equations.",
              solutionSteps: [
                "Problem: Find the minimum value of f(x, y, z) = x^2 + 2*y^2 + z^2 subject to two simultaneous equality constraints: g1(x, y, z) = x + y + z - 1 = 0 and g2(x, y, z) = x - y = 0.",
                "Step 1: Formulate Lagrangian with two multipliers lambda1 and lambda2:",
                "  L(x, y, z, lambda1, lambda2) = x^2 + 2*y^2 + z^2 - lambda1*(x + y + z - 1) - lambda2*(x - y).",
                "Step 2: Compute partial derivatives:",
                "  dL/dx = 2*x - lambda1 - lambda2 = 0  =>  2*x = lambda1 + lambda2",
                "  dL/dy = 4*y - lambda1 + lambda2 = 0  =>  4*y = lambda1 - lambda2",
                "  dL/dz = 2*z - lambda1 = 0            =>  2*z = lambda1  =>  z = lambda1 / 2.",
                "Step 3: Use constraint g2: x - y = 0 => y = x:",
                "  Substitute y = x into gradient equations:",
                "  2*x = lambda1 + lambda2",
                "  4*x = lambda1 - lambda2",
                "  Add equations: 6*x = 2*lambda1  =>  x = lambda1 / 3.",
                "  Then y = x = lambda1 / 3.",
                "Step 4: Substitute x, y, z in terms of lambda1 into constraint g1: x + y + z = 1:",
                "  (lambda1 / 3) + (lambda1 / 3) + (lambda1 / 2) = 1",
                "  (2*lambda1 + 2*lambda1 + 3*lambda1) / 6 = 1  =>  7*lambda1 / 6 = 1  =>  lambda1 = 6 / 7.",
                "Step 5: Find optimal coordinates (x*, y*, z*):",
                "  x* = (6/7) / 3 = 2 / 7.",
                "  y* = 2 / 7.",
                "  z* = (6/7) / 2 = 3 / 7.",
                "Step 6: Compute minimum value f(x*, y*, z*):",
                "  f(2/7, 2/7, 3/7) = (2/7)^2 + 2*(2/7)^2 + (3/7)^2",
                "  f = (4 / 49) + 2*(4 / 49) + (9 / 49) = (4 + 8 + 9) / 49 = 21 / 49 = 3 / 7 ≈ 0.4286.",
                "Conclusion: The constrained minimum occurs at (2/7, 2/7, 3/7) with minimum value 3/7.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Numerical Optimization (2nd Edition)",
                  authors: "Jorge Nocedal, Stephen J. Wright",
                  year: "2006",
                  publisher: "Springer",
                  relevance: "Chapter 12: Theory of Constrained Optimization.",
                },
              ],
            },
          ],
        },
        {
          id: "karush-kuhn-tucker-kkt-conditions-and-complementary-slackness",
          title: "Karush-Kuhn-Tucker (KKT) Conditions & Complementary Slackness",
          slug: "karush-kuhn-tucker-kkt-conditions-and-complementary-slackness",
          order: 2,
          estimatedMinutes: 34,
          tagline: "The Four KKT conditions: Stationarity, Primal feasibility, Dual feasibility, and Complementary slackness in Support Vector Machines.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "KKT Conditions: For min f0(x) s.t. f_i(x) <= 0: 1. Stationarity: grad(f0) + Sum lambda_i grad(f_i) = 0; 2. Primal: f_i(x) <= 0; 3. Dual: lambda_i >= 0; 4. Complementary Slackness: lambda_i * f_i(x) = 0.",
            keyFormulasAndRules: [
              "Complementary Slackness: lambda_i * f_i(x*) = 0 for all i.",
              "  Active Constraint: f_i(x*) = 0 => lambda_i >= 0 (constraint acts as an equality boundary).",
              "  Inactive Constraint: f_i(x*) < 0 => lambda_i = 0 (constraint has no effect on optimal location).",
              "Convexity & Sufficiency: If f0 and all f_i are convex, KKT conditions are BOTH necessary and sufficient for global optimality.",
              "SVM Connection: In Support Vector Machines, data points with lambda_i > 0 are precisely the SUPPORT VECTORS lying on the margin boundaries.",
            ],
            examPitfalls: [
              "Never set lambda_i < 0 for minimization problems with f_i(x) <= 0 constraints (violates Dual Feasibility).",
              "When solving KKT systems, split into cases based on which inequality constraints are active (lambda_i > 0, f_i = 0) versus inactive (lambda_i = 0, f_i < 0).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Karush-Kuhn-Tucker (KKT) Theorem",
              body: [
                "The **Karush-Kuhn-Tucker (KKT) conditions** extend the method of Lagrange multipliers to problems with inequality constraints: `min f_0(x)` s.t. `f_i(x) <= 0` and `h_j(x) = 0`.",
                "**The Four KKT Conditions:**",
                "1. **Stationarity:** `grad f_0(x*) + Sum_{i=1}^m lambda_i* grad f_i(x*) + Sum_{j=1}^p nu_j* grad h_j(x*) = 0`.",
                "2. **Primal Feasibility:** `f_i(x*) <= 0` for all i, and `h_j(x*) = 0` for all j.",
                "3. **Dual Feasibility:** `lambda_i* >= 0` for all inequality multipliers.",
                "4. **Complementary Slackness:** `lambda_i* * f_i(x*) = 0` for all i.",
                "**Geometric Meaning of Complementary Slackness:**",
                "Either the constraint boundary is reached (`f_i(x*) = 0`), meaning the constraint actively holds back the objective, OR the constraint is loose (`f_i(x*) < 0`), in which case its multiplier vanishes (`lambda_i* = 0`).",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Constrained Quadratic Program via KKT Case Analysis",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Test both active (lambda > 0) and inactive (lambda = 0) constraint cases systematically.",
              solutionSteps: [
                "Problem: Minimize f(x, y) = (x - 3)^2 + (y - 3)^2 subject to the inequality constraint x + y <= 4, with x >= 0, y >= 0.",
                "Step 1: Rewrite constraint in standard form f1(x, y) <= 0:",
                "  f1(x, y) = x + y - 4 <= 0.",
                "Step 2: Set up Lagrangian with multiplier lambda >= 0:",
                "  L(x, y, lambda) = (x - 3)^2 + (y - 3)^2 + lambda * (x + y - 4).",
                "Step 3: Write KKT conditions:",
                "  1. Stationarity: dL/dx = 2*(x - 3) + lambda = 0  =>  x = 3 - lambda / 2.",
                "                   dL/dy = 2*(y - 3) + lambda = 0  =>  y = 3 - lambda / 2.",
                "  2. Primal Feasibility: x + y - 4 <= 0.",
                "  3. Dual Feasibility: lambda >= 0.",
                "  4. Complementary Slackness: lambda * (x + y - 4) = 0.",
                "Step 4: Case 1 - Inactive Constraint (lambda = 0):",
                "  If lambda = 0, then x = 3, y = 3.",
                "  Check Primal Feasibility: x + y = 3 + 3 = 6 > 4 (Violated!).",
                "  Case 1 is infeasible.",
                "Step 5: Case 2 - Active Constraint (lambda > 0 => x + y - 4 = 0):",
                "  Substitute x = 3 - lambda / 2 and y = 3 - lambda / 2 into x + y = 4:",
                "  (3 - lambda / 2) + (3 - lambda / 2) = 4",
                "  6 - lambda = 4  =>  lambda = 2.",
                "  Check Dual Feasibility: lambda = 2 >= 0 (Satisfied!).",
                "  Optimal point: x* = 3 - 2/2 = 2;  y* = 3 - 2/2 = 2.",
                "  Check Primal Feasibility: 2 + 2 = 4 <= 4 (Satisfied!).",
                "  Check Complementary Slackness: 2 * (2 + 2 - 4) = 2 * 0 = 0 (Satisfied!).",
                "Step 6: Compute optimal objective value:",
                "  f(2, 2) = (2 - 3)^2 + (2 - 3)^2 = (-1)^2 + (-1)^2 = 1 + 1 = 2.",
                "Conclusion: The optimal constrained point is (2, 2) with multiplier lambda* = 2 and minimum value f* = 2.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Convex Optimization",
                  authors: "Stephen Boyd, Lieven Vandenberghe",
                  year: "2004",
                  publisher: "Cambridge University Press",
                  relevance: "Chapter 5.5: Karush-Kuhn-Tucker (KKT) conditions.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: NUMERICAL OPTIMIZATION & GRADIENT DYNAMICS
    // =========================================================================
    {
      id: "da-opt-module-5-algorithms",
      title: "Module 5: Numerical Optimization & Gradient Dynamics",
      slug: "numerical-optimization-and-gradient-dynamics",
      description:
        "Gradient Descent updates, Lipschitz smoothness, learning rate bounds, convergence rates, condition numbers, and Newton-Raphson second-order optimization.",
      order: 5,
      lessons: [
        {
          id: "gradient-descent-learning-rates-and-convergence-analysis",
          title: "Gradient Descent, Learning Rates & Convergence",
          slug: "gradient-descent-learning-rates-and-convergence-analysis",
          order: 1,
          estimatedMinutes: 32,
          tagline: "x_{k+1} = x_k - alpha grad(f), Lipschitz smoothness L, optimal step size alpha < 2/L, condition number kappa, and oscillations.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Gradient Descent Step Size Bound: For an L-smooth convex function (||grad(f(x)) - grad(f(y))|| <= L ||x - y||), Gradient Descent converges iff step size alpha < 2 / L, with optimal convergence rate at alpha = 1 / L.",
            keyFormulasAndRules: [
              "Gradient Descent Update: x_{k+1} = x_k - alpha * grad(f(x_k)).",
              "Lipschitz Smoothness L: Equivalent to ||H(x)||_2 <= L (maximum eigenvalue lambda_max(H) <= L).",
              "Descent Lemma: f(x_{k+1}) <= f(x_k) - alpha * (1 - L*alpha / 2) * ||grad(f(x_k))||^2.",
              "Convergence Rates: O(1/k) for general convex functions; Linear convergence O(c^k) for strongly convex functions.",
              "Condition Number kappa: kappa = lambda_max(H) / lambda_min(H). If kappa >> 1, gradient descent oscillates across ravines.",
            ],
            examPitfalls: [
              "If learning rate alpha >= 2 / L, gradient descent will OSCILLATE AND DIVERGE along the axis of maximum curvature.",
              "Linear convergence in optimization literature means the error satisfies ||x_{k+1} - x*|| <= c ||x_k - x*|| with c < 1 (which corresponds to exponential decay in engineering terms).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Gradient Descent Dynamics & The Lipschitz Bound",
              body: [
                "**Gradient Descent** is the workhorse algorithm of machine learning, iteratively stepping in the negative gradient direction:",
                "`x_{k+1} = x_k - alpha grad(f(x_k))`.",
                "**The Lipschitz Smoothness Constant L:**",
                "A continuously differentiable function `f` is **L-smooth** if its gradient does not change arbitrarily fast:",
                "`||grad(f(x)) - grad(f(y))|| <= L ||x - y||`.",
                "For twice-differentiable functions, `L = sup_x ||H(x)||_2 = lambda_{max}(H)`.",
                "**The Stability Threshold:**",
                "Using the Descent Lemma, setting `alpha < 2 / L` guarantees that the objective decreases at every iteration (`f(x_{k+1}) < f(x_k)`).",
                "**The Ravine Problem (Conditioning):**",
                "When `kappa = lambda_{max} / lambda_{min}` is large, contours are highly elongated ellipses. The gradient vector points almost perpendicular to the direction toward the true minimum, causing zig-zag oscillations.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Maximum Stable Learning Rate on Quadratic Loss",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "The maximum stable learning rate is alpha_max = 2 / lambda_max, NOT 1 / lambda_max.",
              solutionSteps: [
                "Problem: Consider the quadratic loss function f(x, y) = 4*x^2 + y^2. (a) Find the Lipschitz constant L and the maximum stable learning rate alpha_max. (b) Trace the first Gradient Descent update starting from (x0, y0) = (1, 1) with learning rate alpha = 0.1.",
                "Step 1: Compute Hessian matrix H:",
                "  df/dx = 8*x  =>  d^2 f / dx^2 = 8.",
                "  df/dy = 2*y  =>  d^2 f / dy^2 = 2.",
                "  d^2 f / dxdy = 0.",
                "  Hessian H = [ [8, 0], [0, 2] ].",
                "Step 2: Find eigenvalues and Lipschitz constant L:",
                "  Eigenvalues are the diagonal entries: lambda1 = 8, lambda2 = 2.",
                "  Lipschitz constant L = lambda_max(H) = 8.",
                "  Condition number kappa = lambda_max / lambda_min = 8 / 2 = 4.",
                "Step 3: Determine maximum stable learning rate alpha_max:",
                "  alpha_max = 2 / L = 2 / 8 = 0.25.",
                "  (For alpha >= 0.25, the algorithm diverges along the x-axis).",
                "Step 4: Trace step 1 with alpha = 0.1 from (x0, y0) = (1, 1):",
                "  grad(f)(1, 1) = [ 8(1), 2(1) ]^T = [ 8, 2 ]^T.",
                "  x_1 = x_0 - alpha * grad(f)_x = 1 - 0.1 * 8 = 1 - 0.8 = 0.2.",
                "  y_1 = y_0 - alpha * grad(f)_y = 1 - 0.1 * 2 = 1 - 0.2 = 0.8.",
                "  Updated point: (x1, y1) = (0.2, 0.8).",
                "Step 5: Verify descent in objective function:",
                "  Initial loss: f(1, 1) = 4(1)^2 + 1^2 = 5.0.",
                "  Updated loss: f(0.2, 0.8) = 4(0.2)^2 + (0.8)^2 = 4(0.04) + 0.64 = 0.16 + 0.64 = 0.80.",
                "  Loss decreased from 5.00 to 0.80.",
                "Conclusion: L = 8, alpha_max = 0.25; after 1 step with alpha = 0.1, (x1, y1) = (0.2, 0.8) with loss reduced to 0.80.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Introductory Lectures on Convex Optimization",
                  authors: "Yurii Nesterov",
                  year: "2004",
                  publisher: "Springer",
                  relevance: "Chapter 1: Smooth Convex Optimization and Gradient Method.",
                },
              ],
            },
          ],
        },
        {
          id: "second-order-optimization-newtons-method",
          title: "Second-Order Optimization & Newton's Method",
          slug: "second-order-optimization-newtons-method",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Newton step Delta x = - H^{-1} grad(f), quadratic convergence, scale invariance, and Hessian inversion cost.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Newton's Method: x_{k+1} = x_k - [H(x_k)]^{-1} * grad(f(x_k)). Exactly reaches the minimum of ANY positive definite quadratic function in PRECISELY ONE STEP.",
            keyFormulasAndRules: [
              "Newton Step: Delta x_nt = - [H(x)]^{-1} * grad(f(x)).",
              "Quadratic Convergence: Once near the minimum, error satisfies ||x_{k+1} - x*|| <= M ||x_k - x*||^2 (number of accurate digits doubles every step).",
              "Affine Invariance: Newton's step is completely invariant to linear coordinate transformations (unlike gradient descent).",
              "Computational Cost: Inverting Hessian H (d x d) costs O(d^3) per iteration, limiting pure Newton's method in deep learning.",
              "Non-Convex Failure: If Hessian H is not positive definite, Newton's step can jump toward local maxima or saddle points.",
            ],
            examPitfalls: [
              "Newton's method finds roots of grad(f) = 0. If H has negative eigenvalues, Newton's method will happily step TOWARD A LOCAL MAXIMUM.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Second-Order Optimization & The Quadratic Model",
              body: [
                "While Gradient Descent approximates the loss surface with a flat tangent plane, **Newton's Method** fits a quadratic paraboloid using the Hessian matrix:",
                "`f(x + Delta x) ≈ f(x) + grad(f(x))^T Delta x + (1/2) Delta x^T H(x) Delta x`.",
                "**Derivation of the Newton Step:**",
                "Differentiating the quadratic surrogate with respect to `Delta x` and setting to zero:",
                "`grad(f(x)) + H(x) Delta x = 0  =>  Delta x = - [H(x)]^{-1} grad(f(x))`.",
                "`x_{k+1} = x_k - [H(x_k)]^{-1} grad(f(x_k))`.",
                "**Comparison: First-Order vs Second-Order Optimization:**",
                "- **Gradient Descent:** Per-step cost `O(d)`, linear convergence `O(c^k)`, highly sensitive to feature scaling and conditioning.",
                "- **Newton's Method:** Per-step cost `O(d^3)`, quadratic convergence `O(e_k^2)`, completely affine-invariant, but fails if Hessian is singular or indefinite.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Exact Single-Step Newton Convergence",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Invert the 2x2 Hessian matrix accurately using the adjugate formula H^{-1} = (1 / det(H)) * adj(H).",
              solutionSteps: [
                "Problem: Apply one iteration of Newton's method to minimize f(x, y) = 2*x^2 + y^2 - 2*x*y - 4*x starting from initial guess (x0, y0) = (0, 0). Show that the step jumps directly to the exact global minimum.",
                "Step 1: Compute gradient vector grad(f):",
                "  df/dx = 4*x - 2*y - 4",
                "  df/dy = 2*y - 2*x",
                "  At (x0, y0) = (0, 0): grad(f)(0, 0) = [ -4, 0 ]^T.",
                "Step 2: Compute Hessian matrix H:",
                "  d^2 f / dx^2 = 4",
                "  d^2 f / dy^2 = 2",
                "  d^2 f / dxdy = -2",
                "  H = [ [ 4, -2], [-2,  2] ].",
                "Step 3: Compute Hessian inverse H^{-1}:",
                "  det(H) = (4)(2) - (-2)(-2) = 8 - 4 = 4 > 0 (Positive Definite).",
                "  H^{-1} = (1 / 4) * [ [2, 2], [2, 4] ] = [ [1/2, 1/2], [1/2, 1] ].",
                "Step 4: Compute Newton step Delta x = - H^{-1} * grad(f):",
                "  Delta x = - [ [1/2, 1/2], [1/2, 1] ] * [ -4, 0 ]^T",
                "  Delta x = - [ (1/2)*(-4) + 0, (1/2)*(-4) + 0 ]^T = - [ -2, -2 ]^T = [ 2, 2 ]^T.",
                "Step 5: Compute updated point x1 = x0 + Delta x:",
                "  [ x1, y1 ]^T = [ 0, 0 ]^T + [ 2, 2 ]^T = [ 2, 2 ]^T.",
                "Step 6: Verify that (2, 2) is the exact critical point:",
                "  df/dx(2, 2) = 4(2) - 2(2) - 4 = 8 - 4 - 4 = 0.",
                "  df/dy(2, 2) = 2(2) - 2(2) = 4 - 4 = 0.",
                "  grad(f)(2, 2) = [ 0, 0 ]^T.",
                "Conclusion: In exactly ONE iteration, Newton's method jumps from (0, 0) directly to the exact global minimum (2, 2).",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Numerical Optimization (2nd Edition)",
                  authors: "Jorge Nocedal, Stephen J. Wright",
                  year: "2006",
                  publisher: "Springer",
                  relevance: "Chapter 3: Line Search Methods and Newton-Raphson Optimization.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
