import type { LessonMeta } from "./types";

export const CN_SOCKET_API_LESSON: LessonMeta = {
  id: "tcp-socket-api-client-server-lifecycle",
  title: "TCP Socket API: From socket() to accept()",
  slug: "tcp-socket-api-client-server-lifecycle",
  order: 2,
  estimatedMinutes: 25,
  tagline: "Connect the transport service to the programming interface named in the GATE 2027 CS/IT syllabus.",
  hasInteractive: false,
  hasGATE: true,
  hasPractice: true,
  syllabusScope: "GATE 2027 CS/IT core: TCP socket API; UDP appears only as a contrast",
  cheatsheet: { summaryRule: "A TCP server creates, binds, listens, then accepts a connection; a client creates a socket and connects to the server endpoint.", keyFormulasAndRules: ["`socket()` creates an endpoint descriptor.", "`bind()` associates a local address and port; `listen()` makes a stream socket passive.", "`accept()` returns a new connected socket; the listening socket remains available for more clients.", "A TCP byte stream preserves byte order, not application message boundaries."], examPitfalls: ["`accept()` blocks until a connection is pending unless configured otherwise.", "The connected socket returned by `accept()` is distinct from the listening socket.", "TCP does not preserve the size of each individual `send()` call as a message boundary."], },
  sections: [
    { type: "explanation", heading: "Prerequisites and endpoint model", body: ["**Prerequisites:** know that TCP provides a reliable ordered byte stream between endpoints and that a port identifies an application endpoint at a host. Review [TCP flow and congestion control](/notes/computer-networks/tcp-connection-and-congestion-control) if needed.", "The socket API is the programming interface used by an application to ask the operating system for network communication. A server's usual passive-open sequence is `socket → bind → listen → accept`; a client's active-open sequence is `socket → connect`. After connection setup, both sides use `send`/`recv` (or equivalent operations) and close their endpoint when finished.", "Each TCP connection is identified by its local and remote IP addresses and port numbers. `accept()` returns a new connected socket for one client; the original listening socket can continue accepting additional connections. A successful `send` may transmit fewer bytes than requested, and `recv` may return a partial application record, so application protocols need framing (for example, a fixed length or explicit length prefix).", "UDP is a datagram service and can be contrasted with TCP, but it is not a named transport requirement in the current GATE 2027 CS/IT list. This note introduces only enough UDP semantics to distinguish socket types; it does not present UDP as GATE-core coverage."] },
    { type: "code", heading: "Socket call order (pseudocode) and descriptor roles", language: "text", filename: "socket-lifecycle.txt", code: "server_fd = socket(AF_INET, SOCK_STREAM)\nbind(server_fd, local_address, port)\nlisten(server_fd, backlog)\nconnection_fd, peer = accept(server_fd)\nrecv(connection_fd, buffer)\nsend(connection_fd, reply)\nclose(connection_fd)\n\nclient_fd = socket(AF_INET, SOCK_STREAM)\nconnect(client_fd, server_address, port)\nsend(client_fd, request)\nrecv(client_fd, buffer)\nclose(client_fd)", explanations: [{ lines: "1-4", note: "The server creates a stream endpoint, claims a local port, enters passive/listening state, and accepts one peer." }, { lines: "5-7", note: "The accepted descriptor carries that client's connected byte stream; closing it does not close the listening endpoint." }, { lines: "9-11", note: "The client creates a stream endpoint and actively requests the server's address and port." }] },
    { type: "worked-example", heading: "Worked trace: two clients", problemStatement: "A server calls `listen(server_fd, ...)`, then accepts client A and client B. How many listening descriptors and connected descriptors exist after both accepts?", steps: [{ stepNumber: 1, title: "Create the listener", description: "`server_fd` remains the single listening descriptor." }, { stepNumber: 2, title: "Accept client A", description: "The first `accept` returns `conn_A`; server_fd remains open." }, { stepNumber: 3, title: "Accept client B", description: "The next `accept` returns `conn_B`; both connections coexist with server_fd." }], finalAnswer: "One listening descriptor and two connected descriptors.", examTakeaway: "Do not treat accept as converting the listening descriptor into the client connection." },
    { type: "practice", heading: "Socket API checks", questions: [{ id: "cn-socket-1", prompt: "Which call makes a TCP server socket passive and ready to queue incoming connection requests?", type: "single-choice", options: [{ id: "a", text: "listen()", isCorrect: true, explanation: "listen marks a stream socket as passive and supplies a pending-connection backlog." }, { id: "b", text: "connect()", isCorrect: false, explanation: "connect is normally used by the active client." }, { id: "c", text: "accept()", isCorrect: false, explanation: "accept retrieves a pending connection and returns a connected descriptor." }], explanation: "Remember the server sequence: socket, bind, listen, accept.", difficulty: "foundation" }, { id: "cn-socket-2", prompt: "After a successful accept(), which descriptor usually remains available for later clients?", type: "single-choice", options: [{ id: "a", text: "The listening descriptor", isCorrect: true, explanation: "accept returns a separate connected descriptor." }, { id: "b", text: "Only the connected descriptor", isCorrect: false, explanation: "The listening descriptor is not consumed by accepting one client." }], explanation: "The server listener and each connection have distinct roles.", difficulty: "gate-level" }] },
    { type: "quick-revision", heading: "One-minute revision", oneMinutePanicCard: { coreRule: "Server: socket → bind → listen → accept. Client: socket → connect.", mustRememberFormulas: ["TCP connection endpoint pair = local (IP, port) + remote (IP, port)", "Listening socket ≠ accepted connected socket"], criticalPitfalls: ["accept returns a new descriptor", "TCP is a byte stream, not a message protocol", "send/recv may be partial", "UDP is comparative enrichment here"] } },
    { type: "resources", heading: "References", sources: [{ title: "GATE 2027 CS/IT syllabus", authorOrInstitution: "IIT Madras", url: "https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/CS_GATE2027_Syllabus.pdf", type: "gate-official", topic: "Computer Networks: TCP flow/congestion control and socket API." }, { title: "The Linux Programming Interface", authors: "Michael Kerrisk", year: "2010", publisher: "No Starch Press", url: "https://man7.org/tlpi/", type: "primary-standard", topic: "Socket API system calls, client/server sequence, and stream semantics." }] },
  ],
};