import { CourseMeta } from "./types";

export const COA_COURSE: CourseMeta = {
  id: "computer-organization",
  title: "Computer Organization & Architecture",
  slug: "computer-organization",
  subjectSlug: "computer-organization",
  shortTitle: "COA",
  icon: "🖥️",
  color: "bg-cyan-400",
  tagline:
    "Master instruction formats, addressing modes, IEEE 754 floats, Booth's multiplication, cache mapping, AMAT, 5-stage pipelining hazards, microprogramming, and DMA.",
  description:
    "A rigorous, mathematically precise study notebook covering the internal architecture and operational hardware of modern computing systems: machine instructions, addressing modes, expanding opcodes, datapath timing, IEEE 754 floating-point standard, Booth's multiplication, restoring/non-restoring division, cache bit-splitting, multi-level AMAT, 5-stage RISC instruction pipelining, RAW hazard forwarding, branch penalties, hardwired and microprogrammed control units, and interrupt/DMA I/O transfer for undergraduate excellence and top-rank GATE CS/IT performance.",
  level: "Undergraduate / GATE CS",
  estimatedHours: 48,
  prerequisites: [
    "Digital Logic (Boolean algebra, flip-flops, multiplexers, decoders, adders)",
    "Elementary C Programming (Pointers, memory addresses, binary representations)",
  ],
  learningOutcomes: [
    "Calculate exact effective addresses, instruction field bit lengths, and formulate expanding opcode allocations",
    "Analyze single-cycle and multi-cycle datapath propagation delays and register transfer semantics",
    "Encode and decode IEEE 754 single and double precision floating-point numbers including subnormal values and special conditions",
    "Trace Booth's signed 2's complement multiplication and analyze restoring/non-restoring division hardware steps",
    "Compute tag, set/line index, and block offset bits for direct, associative, and k-way set-associative cache architectures",
    "Derive Average Memory Access Time (AMAT) for multi-level hierarchical cache systems with local vs global miss rates",
    "Solve 5-stage instruction pipeline clock periods, speedup, CPI, RAW data hazard bubbles, and operand forwarding paths",
    "Evaluate structural hazards, branch penalty cycles, and 2-bit saturating dynamic branch predictor state machines",
    "Design horizontal and vertical microinstruction control words and calculate control store memory capacities",
    "Calculate CPU utilization and bus bandwidth slowdown during DMA cycle-stealing and burst mode data transfers",
  ],
  gateScope: "GATE 2027 CS/IT scope",
  gateBranches: ["cs"],
  gateSyllabusTopics: [
    "Machine instructions and addressing modes: Instruction formats (0, 1, 2, 3 address), instruction cycle, addressing modes, expanding opcodes, RISC vs CISC",
    "ALU, data-path and control unit: Single-cycle and multi-cycle datapaths, fixed and floating point arithmetic, Booth's algorithm, division, hardwired and microprogrammed control",
    "Instruction pipelining: Pipeline hazards (structural, data, control), operand forwarding, branch prediction, pipeline performance, speedup and CPI",
    "Memory hierarchy: Cache memory mapping (direct, associative, set-associative), cache lines, replacement policies, write policies, AMAT, memory interleaving",
    "I/O interface: Interrupts (vectored, priority, daisy chaining), DMA (cycle stealing, burst transfer, transparent)",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: INSTRUCTION FORMATS, ADDRESSING MODES & DATAPATH
    // =========================================================================
    {
      id: "coa-module-1-instructions-and-addressing",
      title: "Module 1: Machine Instructions, Addressing Modes & Datapath",
      slug: "instructions-and-addressing",
      description:
        "Instruction cycle state transitions, 0/1/2/3-address instruction formats, expanding opcode formulations, effective address computation across all classical addressing modes, and single/multi-cycle datapath execution delays.",
      order: 1,
      lessons: [
        {
          id: "addressing-modes-and-instruction-formats",
          title: "Addressing Modes, Effective Address & Expanding Opcodes",
          slug: "addressing-modes-and-instruction-formats",
          order: 1,
          estimatedMinutes: 30,
          tagline: "EA calculations, memory reference counting, opcode expansion, and addressing modes.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          sections: [
            {
              type: "explanation",
              heading: "1. The Classical Addressing Modes & Effective Address (EA)",
              body: [
                "An addressing mode specifies how the processor's execution unit interprets or modifies an instruction's address field to locate the actual target operand in memory or registers. The computed memory location of the operand is called the ==purple:Effective Address (EA)==.",
                "**Complete Classification of Addressing Modes & Memory Reference Costs:**",
                "1. **Immediate Mode:** The operand is embedded directly inside the instruction word (e.g., `ADD R1, #42`). ==yellow:EA = None. 0 memory references to fetch operand==.",
                "2. **Register Mode:** The operand resides in a named CPU register (e.g., `ADD R1, R2`). ==yellow:EA = Register address. 0 memory references==.",
                "3. **Direct (Absolute) Mode:** The instruction address field contains the actual main memory address of the operand (e.g., `LOAD R1, [1000]`). ==purple:EA = Address field (A). 1 memory reference to read operand==.",
                "4. **Indirect Mode:** The address field points to a memory word that holds the effective address of the operand (e.g., `LOAD R1, @[1000]`). ==pink:EA = Memory[A]. Requires 2 memory references (1 for pointer address + 1 for operand)==.",
                "5. **Register Indirect Mode:** A CPU register holds the effective memory address (e.g., `LOAD R1, (R2)`). ==purple:EA = [R2]. Requires 1 memory reference==.",
                "6. **Indexed Mode:** ==green:EA = Base Address (in instruction) + Index Register (IR)==. Used for sequential array element traversal (`A[i]`), where the index register holds the array subscript.",
                "7. **Base Register Mode:** ==green:EA = Base Register (BR) + Displacement/Offset==. Used for operating system program relocation; the base register points to the program segment origin in RAM.",
                "8. **Relative Mode (PC-Relative):** ==purple:EA = Program Counter (PC) + Offset==. Crucial for position-independent conditional branches (`BEQ target`). If the branch is taken, the signed offset is added to the PC.",
                "9. **Auto-Increment / Auto-Decrement:** ==pink:EA = [R]; then R ← R + d (or R ← R - d; then EA = [R])==. Essential for efficient hardware stack implementations and memory copy loops.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Memory Access Accounting in GATE Questions",
                message:
                  "Always count the ==pink:instruction fetch memory access== in addition to operand accesses! For instance, an instruction `ADD (R1)` requires: ==yellow:1 memory cycle to fetch instruction== + ==yellow:1 memory cycle to read operand at Memory[R1]== = ==purple:Total 2 memory access cycles==. If the instruction word is 32 bits on a 16-bit memory bus, the instruction fetch alone requires 2 memory accesses!",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. GATE Worked Numerical: Expanding Opcode Formulation",
              weightage: "2 Marks (Core Recurring Numerical)",
              trap: "Every unallocated pattern at an n-address level is multiplied by 2^k when expanded to the (n-1)-address level, where k is the bit-width of the freed register address field!",
              solutionSteps: [
                "Problem: A processor has a 16-bit instruction word and 16 general-purpose CPU registers (requiring 4 bits each for register addressing). The processor supports 3-address, 2-address, and 1-address instructions.",
                "If the instruction set architecture defines 14 three-address instructions and 30 two-address instructions, calculate the maximum number of 1-address instructions that can be supported.",
                "Step 1: Bit allocation for 3-address format:",
                "  Instruction layout: [Opcode (4 bits)] [Reg1 (4 bits)] [Reg2 (4 bits)] [Reg3 (4 bits)].",
                "  Total possible opcode bit patterns with 4 bits = 2^4 = 16.",
                "Step 2: Determine available patterns for 2-address expansion:",
                "  Used 3-address opcodes = 14.",
                "  Unassigned opcode prefixes = 16 - 14 = 2 prefixes.",
                "Step 3: Bit allocation for 2-address format:",
                "  Instruction layout: [Prefix (4 bits)] [Expanded Opcode (4 bits)] [Reg1 (4 bits)] [Reg2 (4 bits)].",
                "  Each free prefix expands into 2^4 = 16 distinct 2-address instructions.",
                "  Total possible 2-address instructions = 2 * 16 = 32 instructions.",
                "  Used 2-address instructions = 30.",
                "  Remaining free prefixes for 1-address expansion = 32 - 30 = 2 prefixes.",
                "Step 4: Bit allocation for 1-address format:",
                "  The next 4-bit register field is freed to expand the opcode.",
                "  Instruction layout: [2-address Prefix (8 bits)] [Expanded Opcode (4 bits)] [Reg1 (4 bits)].",
                "  Each of the 2 remaining free prefixes yields 2^4 = 16 distinct 1-address instructions.",
                "  Maximum 1-address instructions = 2 * 16 = 32 instructions.",
              ],
            },
            {
              type: "resources",
              heading: "3. References & Authoritative Sources",
              sources: [
                {
                  title: "Computer Organization and Embedded Systems (6th Edition)",
                  authors: "Carl Hamacher, Zvonko Vranesic, Safwat Zaky, Naraig Manjikian",
                  year: "2011",
                  publisher: "McGraw-Hill",
                  relevance:
                    "Chapter 2: Machine Instructions and Programs — authoritative treatment of instruction formats, memory operand access cycles, and assembly semantics.",
                },
                {
                  title: "Computer System Architecture (3rd Edition)",
                  authors: "M. Morris Mano",
                  year: "1993",
                  publisher: "Pearson",
                  relevance:
                    "Chapter 8: Central Processing Unit — classical textbook diagrams of addressing modes, expanding opcodes, and stack organizations.",
                },
              ],
            },
          ],
          cheatsheet: {
            title: "Addressing Modes & Instruction Formats Quick Revision",
            summaryRule: "Effective Address (EA) is the actual memory location accessed; always include instruction fetch memory cycle in total access count.",
            keyFormulasAndRules: [
              "Immediate: EA = None; 0 operand memory references.",
              "Direct: EA = Address field; 1 memory reference.",
              "Indirect: EA = Memory[Address field]; 2 memory references.",
              "Register Indirect: EA = [Register]; 1 memory reference.",
              "Relative: EA = PC + Offset; position-independent conditional branches.",
              "Indexed: EA = Base Address + Index Register; array traversal A[i].",
              "Expanding Opcode: Unused prefixes at level k expand by 2^(freed_field_bits) at level k-1.",
            ],
            examPitfalls: [
              "Never forget the memory access required to fetch the instruction code itself.",
              "PC-relative branch offsets are signed 2's complement numbers relative to the updated PC (pointing to the next instruction).",
            ],
          },
        },
        {
          id: "datapath-and-instruction-cycle",
          title: "Instruction Cycle State Machine & Datapath Timing Analysis",
          slug: "datapath-and-instruction-cycle",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Single-cycle vs multi-cycle datapath delays, RTL register transfers, and ALU flags.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          sections: [
            {
              type: "explanation",
              heading: "1. The Classical Instruction Cycle & RTL Semantics",
              body: [
                "Every machine instruction executes through a sequence of micro-operations coordinated by the central processor clock:",
                "1. **Fetch Cycle (IF):**",
                "   - $MAR \\leftarrow PC$",
                "   - $MDR \\leftarrow \\text{Memory}[MAR], \\quad PC \\leftarrow PC + 4$",
                "   - $IR \\leftarrow MDR$",
                "2. **Decode Cycle (ID / RF):**",
                "   - Decode opcode in $IR$, extract register specifiers, read source registers $A \\leftarrow R[rs], B \\leftarrow R[rt]$, and sign-extend immediate constants.",
                "3. **Execute Cycle (EX):**",
                "   - $ALUOut \\leftarrow A \\text{ op } B$ (arithmetic/logical instruction) or compute branch target address $PC \\leftarrow PC + \\text{offset}$.",
                "4. **Memory Access Cycle (MEM):**",
                "   - For LOAD: $MDR \\leftarrow \\text{Memory}[ALUOut]$.",
                "   - For STORE: $\\text{Memory}[ALUOut] \\leftarrow B$.",
                "5. **Write-Back Cycle (WB):**",
                "   - $R[rd] \\leftarrow ALUOut$ (ALU operation) or $R[rt] \\leftarrow MDR$ (LOAD operation).",
                "**ALU Status Flags (Condition Codes):**",
                "- **Zero Flag (Z):** Set to 1 if the result is all zeros.",
                "- **Sign Flag (S / N):** Equals the MSB of the result (1 for negative in 2's complement).",
                "- **Carry Flag (C):** Set if an unsigned addition generates a carry out of the MSB, or an unsigned subtraction requires a borrow.",
                "- **Overflow Flag (V):** Set if signed 2's complement addition/subtraction produces a result outside the representable range $[-2^{n-1}, 2^{n-1}-1]$. Formally: $V = C_{in} \\oplus C_{out}$ at the MSB position.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. GATE Worked Numerical: Single-Cycle vs Multi-Cycle Datapath Delay",
              weightage: "2 Marks",
              trap: "In a single-cycle datapath, the clock period MUST accommodate the SLOWEST instruction in the instruction set architecture (typically LOAD). In a multi-cycle datapath, the clock period equals the SLOWEST functional unit plus register setup time!",
              solutionSteps: [
                "Problem: A processor has functional unit latencies: Instruction Memory = 250 ps, Register File Read = 150 ps, ALU = 200 ps, Data Memory = 300 ps, and Register File Write = 100 ps. Multiplexers and wiring introduce zero delay.",
                "Compare the clock cycle time of:",
                "1. A single-cycle datapath.",
                "2. A multi-cycle datapath.",
                "3. Calculate the execution time ratio for a program where 25% of instructions are LOAD (5 cycles), 10% are STORE (4 cycles), 50% are R-type (4 cycles), and 15% are BRANCH (3 cycles).",
                "Step 1: Single-cycle clock period:",
                "  The longest instruction path is LOAD: Instruction Memory + Register Read + ALU + Data Memory + Register Write.",
                "  $T_{single} = 250 + 150 + 200 + 300 + 100 = 1000 \\text{ ps} = 1.0 \\text{ ns}$.",
                "  Every instruction must take exactly 1000 ps regardless of its type.",
                "Step 2: Multi-cycle clock period:",
                "  $T_{multi} = \\max(250, 150, 200, 300, 100) = 300 \\text{ ps}$ (dictated by Data Memory).",
                "Step 3: Average CPI for multi-cycle execution:",
                "  $\\text{CPI}_{multi} = (0.25 \\times 5) + (0.10 \\times 4) + (0.50 \\times 4) + (0.15 \\times 3)$",
                "  $\\text{CPI}_{multi} = 1.25 + 0.40 + 2.00 + 0.45 = 4.10 \\text{ cycles/instruction}$.",
                "Step 4: Average time per instruction:",
                "  Single-cycle: $1 \\times 1000 \\text{ ps} = 1000 \\text{ ps}$.",
                "  Multi-cycle: $4.10 \\times 300 \\text{ ps} = 1230 \\text{ ps}$.",
                "  Single-cycle is $1230 / 1000 = 1.23\\times$ faster for this specific instruction mix, but multi-cycle allows hardware sharing (single memory and single ALU).",
              ],
            },
            {
              type: "resources",
              heading: "3. References & Authoritative Sources",
              sources: [
                {
                  title: "Computer Organization and Design RISC-V Edition",
                  authors: "David A. Patterson, John L. Hennessy",
                  year: "2017",
                  publisher: "Morgan Kaufmann",
                  relevance:
                    "Chapter 4: The Processor — detailed schematics of single-cycle and multi-cycle datapaths with control signal generation.",
                },
              ],
            },
          ],
          cheatsheet: {
            title: "Datapath & ALU Flags Quick Revision",
            summaryRule: "Single-cycle clock period equals the sum of delays along the longest instruction path (LOAD); multi-cycle clock equals max stage delay.",
            keyFormulasAndRules: [
              "Single-cycle clock = Sum of delays along the longest instruction path (LOAD).",
              "Multi-cycle clock = Delay of the slowest individual functional stage.",
              "Overflow Flag V: $V = C_{in} \\oplus C_{out}$ at the most significant bit (MSB).",
              "Carry Flag C: Unsigned arithmetic out-of-range indicator.",
              "Sign Flag S: MSB of the result; indicates negative value in 2's complement.",
            ],
            examPitfalls: [
              "Do not confuse Carry (unsigned overflow) with Overflow V (signed 2's complement overflow). An operation can produce Carry=1 with Overflow=0 (e.g., adding two large unsigned numbers that do not violate signed bounds).",
            ],
          },
        },
      ],
    },

    // =========================================================================
    // MODULE 2: COMPUTER ARITHMETIC & FLOATING-POINT REPRESENTATION
    // =========================================================================
    {
      id: "coa-module-2-alu-and-arithmetic",
      title: "Module 2: Computer Arithmetic, IEEE 754 & Booth's Algorithm",
      slug: "alu-and-arithmetic",
      description:
        "Signed 2's complement arithmetic, ALU overflow flags, Booth's multiplication recoding, restoring and non-restoring division, and IEEE 754 single/double precision floating-point standard.",
      order: 2,
      lessons: [
        {
          id: "ieee-754-and-booth-multiplication",
          title: "IEEE 754 Floating Point & Booth's Algorithm",
          slug: "ieee-754-and-booth-multiplication",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Single/Double precision layouts, subnormal values, and Booth bit-pair recoding.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          sections: [
            {
              type: "explanation",
              heading: "1. The IEEE 754 Floating-Point Standard (32-Bit & 64-Bit)",
              body: [
                "The IEEE 754 standard encodes real numbers in normalized scientific notation: $(-1)^S \\times (1.M) \\times 2^{E - \\text{Bias}}$.",
                "**1. Single Precision (32 bits):**",
                "- **Sign bit (S):** 1 bit (0 for positive, 1 for negative).",
                "- **Biased Exponent (E):** 8 bits. Excess-127 bias ($\\text{Bias} = 127$). Normal range: $1 \\le E \\le 254$. True exponent $e = E - 127$.",
                "- **Mantissa / Significand (M):** 23 bits. Represents the fractional part with an implicit leading 1 ($1.M$).",
                "**2. Double Precision (64 bits):**",
                "- **Sign bit (S):** 1 bit.",
                "- **Biased Exponent (E):** 11 bits. Excess-1023 bias ($\\text{Bias} = 1023$). Normal range: $1 \\le E \\le 2046$. True exponent $e = E - 1023$.",
                "- **Mantissa (M):** 52 bits with an implicit leading 1 ($1.M$).",
                "**Special IEEE 754 Encodings & Boundary Cases:**",
                "- **Zero (+0.0 and -0.0):** $E = 0$, $M = 0$. Sign bit determines sign.",
                "- **Denormalized (Subnormal) Numbers:** $E = 0$, $M \\ne 0$. Value $= (-1)^S \\times (0.M) \\times 2^{-126}$ (Single) or $2^{-1022}$ (Double). Eliminates abrupt underflow!",
                "- **Infinity (+∞ and -∞):** $E = 255$ (all 1s), $M = 0$. Produced on overflow or non-zero division by zero ($1.0 / 0.0$).",
                "- **Not-a-Number (NaN):** $E = 255$ (all 1s), $M \\ne 0$. Represents invalid operations like $0.0 / 0.0$ or $\\sqrt{-1}$.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. GATE Worked Numerical: Encoding Real Decimal to IEEE 754 Hex",
              weightage: "2 Marks",
              trap: "Remember that the biased exponent E = e + 127. When normalizing, the radix point moves past the first non-zero bit, leaving an implicit leading 1 that is NOT stored in the mantissa!",
              solutionSteps: [
                "Problem: Convert the decimal number -13.625 into IEEE 754 single-precision format and write the 32-bit result in hexadecimal.",
                "Step 1: Sign bit:",
                "  Number is negative $\\implies S = 1$.",
                "Step 2: Binary conversion of magnitude 13.625:",
                "  Integer part $13 = 1101_2$.",
                "  Fractional part $0.625 = 0.5 + 0.125 = 2^{-1} + 2^{-3} = 0.101_2$.",
                "  Combined binary $= 1101.101_2$.",
                "Step 3: Normalize to $1.M \\times 2^e$:",
                "  $1101.101_2 = 1.101101_2 \\times 2^3$.",
                "  True exponent $e = 3$.",
                "  Mantissa $M = 10110100000000000000000$ (padded with trailing zeros to 23 bits).",
                "Step 4: Compute biased exponent E:",
                "  $E = e + \\text{Bias} = 3 + 127 = 130 = 10000010_2$.",
                "Step 5: Assemble the 32-bit field:",
                "  [S (1)] [E (8)] [M (23)]",
                "  1 10000010 10110100000000000000000",
                "Step 6: Group into 4-bit nibbles for hexadecimal:",
                "  1100 0001 0101 1010 0000 0000 0000 0000",
                "  Hexadecimal representation = 0xC15A0000.",
              ],
            },
            {
              type: "explanation",
              heading: "3. Booth's Multiplication Algorithm for Signed 2's Complement",
              body: [
                "Booth's multiplication algorithm multiplies two signed 2's complement integers by exploiting strings of consecutive 1s to reduce additions and subtractions.",
                "**Hardware Registers:**",
                "- $A$ (Accumulator): Initialized to 0 ($n$ bits).",
                "- $Q$ (Multiplier): Stores the multiplier ($n$ bits).",
                "- $Q_{-1}$ (Extra bit): Initialized to 0 (1 bit).",
                "- $M$ (Multiplicand): Stores the multiplicand ($n$ bits).",
                "**Algorithm Execution Cycle (Repeated $n$ times):**",
                "At each step, inspect the two least significant bits $(Q_0, Q_{-1})$:",
                "1. **$10$:** Subtract Multiplicand from Accumulator: $A \\leftarrow A - M$. Then perform Arithmetic Right Shift (ARS) on $[A, Q, Q_{-1}]$.",
                "2. **$01$:** Add Multiplicand to Accumulator: $A \\leftarrow A + M$. Then perform Arithmetic Right Shift (ARS) on $[A, Q, Q_{-1}]$.",
                "3. **$00$ or $11$:** No arithmetic operation; simply perform Arithmetic Right Shift (ARS) on $[A, Q, Q_{-1}]$.",
                "**Arithmetic Right Shift (ARS) Invariant:**",
                "In ARS, the sign bit ($A_{n-1}$) is duplicated into itself during the shift: $A_{n-1} \\leftarrow A_{n-1}$, preserving the negative sign.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Booth's Worst vs Best Case Performance",
                message:
                  "Worst case for Booth's algorithm occurs when bits alternate: `01010101...` (requires an addition/subtraction in EVERY step). Best case occurs when the multiplier contains long contiguous runs of 1s or 0s: e.g., `00001111` requires only ONE subtraction at the start and ONE addition at the end!",
              },
            },
            {
              type: "resources",
              heading: "4. References & Authoritative Sources",
              sources: [
                {
                  title: "Computer Architecture: A Quantitative Approach (6th Edition)",
                  authors: "John L. Hennessy, David A. Patterson",
                  year: "2017",
                  publisher: "Morgan Kaufmann",
                  relevance:
                    "Appendix J: Computer Arithmetic — rigorous analysis of IEEE 754 precision, rounding modes, and Booth recoding.",
                },
              ],
            },
          ],
          cheatsheet: {
            title: "IEEE 754 & Booth's Algorithm Quick Revision",
            summaryRule: "IEEE 754 encodes (-1)^S * (1.M) * 2^(E-Bias) with Bias 127 (Single) and 1023 (Double); Booth shifts arithmetic right preserving MSB.",
            keyFormulasAndRules: [
              "Single Precision: Bias = 127; E has 8 bits, M has 23 bits.",
              "Double Precision: Bias = 1023; E has 11 bits, M has 52 bits.",
              "Subnormal numbers: E = 0, M != 0; value = (-1)^S * (0.M) * 2^(-126).",
              "Booth (Q_0, Q_-1): 10 -> Subtract & Shift; 01 -> Add & Shift; 00/11 -> Shift only.",
              "ARS preserves MSB sign bit.",
            ],
            examPitfalls: [
              "Never include the hidden 1 when writing the stored mantissa bits.",
              "For negative numbers in Booth's algorithm, always compute -M in two's complement before starting.",
            ],
          },
        },
        {
          id: "division-algorithms-and-alu-overflow",
          title: "Restoring & Non-Restoring Division and Carry Lookahead Adders",
          slug: "division-algorithms-and-alu-overflow",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Binary restoring/non-restoring division cycles and CLA propagation-generation gate delays.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          sections: [
            {
              type: "explanation",
              heading: "1. Binary Division: Restoring vs Non-Restoring Algorithms",
              body: [
                "Hardware division computes Quotient ($Q$) and Remainder ($A$) such that $\\text{Dividend} = \\text{Divisor} \\times Q + A$ with $0 \\le A < \\text{Divisor}$.",
                "**1. Restoring Division Algorithm:**",
                "Registers: $A = 0$, $Q = \\text{Dividend}$, $M = \\text{Divisor}$. Repeat for $n$ bits:",
                "- Shift left $[A, Q]$ by 1 bit.",
                "- Subtract divisor: $A \\leftarrow A - M$.",
                "- If $A < 0$ (sign bit $A_{n} = 1$): Restore original $A$ by $A \\leftarrow A + M$, and set quotient bit $Q_0 = 0$.",
                "- If $A \\ge 0$ (sign bit $A_{n} = 0$): No restore needed, and set quotient bit $Q_0 = 1$.",
                "**2. Non-Restoring Division Algorithm:**",
                "Eliminates the extra addition cycle needed for restoring:",
                "- If $A \\ge 0$: Shift left $[A, Q]$, then subtract divisor $A \\leftarrow A - M$.",
                "- If $A < 0$: Shift left $[A, Q]$, then ADD divisor $A \\leftarrow A + M$.",
                "- After addition/subtraction: If $A \\ge 0$, set $Q_0 = 1$; if $A < 0$, set $Q_0 = 0$.",
                "- Final correction: If $A < 0$ after $n$ cycles, perform one final addition: $A \\leftarrow A + M$.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. GATE Worked Numerical: Carry Lookahead Adder (CLA) Gate Latency",
              weightage: "2 Marks (High Frequency)",
              trap: "Ripple carry adders have delay O(n) proportional to the number of bits. Carry Lookahead Adders (CLA) compute all carries in parallel in O(1) gate delays using Carry Generate (G_i) and Carry Propagate (P_i) terms!",
              solutionSteps: [
                "Problem: In a 4-bit Carry Lookahead Adder, each 2-input AND, OR, and XOR gate has a propagation delay of 10 ns, 10 ns, and 15 ns respectively. Assume gates have unlimited fan-in.",
                "Calculate:",
                "1. Time to generate all P_i and G_i signals.",
                "2. Time to compute the final carry C_4.",
                "3. Time to generate all sum bits S_i.",
                "Step 1: Generate and Propagate terms:",
                "  $G_i = A_i \\cdot B_i$ (computed via 2-input AND gate $\\implies 10 \\text{ ns}$).",
                "  $P_i = A_i \\oplus B_i$ (computed via 2-input XOR gate $\\implies 15 \\text{ ns}$).",
                "  Both are computed in parallel: $T_{PG} = \\max(10, 15) = 15 \\text{ ns}$.",
                "Step 2: Carry equation expansions:",
                "  $C_1 = G_0 + P_0 C_0$",
                "  $C_2 = G_1 + P_1 G_0 + P_1 P_0 C_0$",
                "  $C_3 = G_2 + P_2 G_1 + P_2 P_1 G_0 + P_2 P_1 P_0 C_0$",
                "  $C_4 = G_3 + P_3 G_2 + P_3 P_2 G_1 + P_3 P_2 P_1 G_0 + P_3 P_2 P_1 P_0 C_0$",
                "  Each carry is a two-level AND-OR circuit: 1 AND gate delay + 1 OR gate delay.",
                "  $T_{carry} = T_{PG} + T_{AND} + T_{OR} = 15 \\text{ ns} + 10 \\text{ ns} + 10 \\text{ ns} = 35 \\text{ ns}$.",
                "Step 3: Sum bit generation:",
                "  $S_i = P_i \\oplus C_i$.",
                "  Since $C_i$ is available at 35 ns, the final sum is computed by passing through one XOR gate:",
                "  $T_{sum} = T_{carry} + T_{XOR} = 35 \\text{ ns} + 15 \\text{ ns} = 50 \\text{ ns}$.",
              ],
            },
            {
              type: "resources",
              heading: "3. References & Authoritative Sources",
              sources: [
                {
                  title: "Digital Design (5th Edition)",
                  authors: "M. Morris Mano, Michael D. Ciletti",
                  year: "2012",
                  publisher: "Pearson",
                  relevance:
                    "Chapter 4: Combinational Logic — detailed Boolean algebra derivations of Carry Lookahead Adders and ALU logic units.",
                },
              ],
            },
          ],
          cheatsheet: {
            title: "Division & CLA Adders Quick Revision",
            summaryRule: "Non-restoring division eliminates the restore addition cycle by adding divisor when remainder is negative; CLA generates carries in 2 gate levels.",
            keyFormulasAndRules: [
              "Restoring division: Subtract; if negative, restore by adding back and set Q_0 = 0.",
              "Non-restoring division: If A >= 0, shift & subtract; if A < 0, shift & add.",
              "CLA: $G_i = A_i B_i$ (generate), $P_i = A_i \\oplus B_i$ (propagate).",
              "CLA Carry latency is constant 2 gate levels (AND-OR) after P and G are available.",
            ],
            examPitfalls: [
              "In non-restoring division, remember the final sign check on remainder A: if A is negative at the end of all steps, a final restore addition A = A + M is strictly required.",
            ],
          },
        },
      ],
    },

    // =========================================================================
    // MODULE 3: MEMORY HIERARCHY, CACHE ARCHITECTURE & AMAT
    // =========================================================================
    {
      id: "coa-module-3-memory-hierarchy-and-cache",
      title: "Module 3: Memory Hierarchy, Cache Mapping & AMAT",
      slug: "memory-hierarchy-and-cache",
      description:
        "Direct-mapped, fully associative, and k-way set-associative cache bit splitting, tag directory sizing, Average Memory Access Time (AMAT), write-through/write-back policies, and memory interleaving.",
      order: 3,
      lessons: [
        {
          id: "cache-mapping-and-amat-calculations",
          title: "Cache Memory: Direct, Associative, Set-Associative & AMAT",
          slug: "cache-mapping-and-amat-calculations",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Tag/Index/Offset bit splitting, multi-level cache AMAT, and tag directory overhead.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          sections: [
            {
              type: "explanation",
              heading: "1. The Principle of Locality & The Three Cache Mapping Techniques",
              body: [
                "Caches exploit ==purple:Temporal Locality== (recently referenced memory locations are likely to be accessed again soon) and ==green:Spatial Locality== (memory locations contiguous to recently accessed items are likely to be accessed soon).",
                "**Physical Address Partitioning Formulations:**",
                "1. **Block (Byte) Offset bits ($w$):**",
                "   $w = \\log_2(\\text{Block Size in bytes})$. Identifies the specific byte within a cache line.",
                "2. **Direct-Mapped Cache:**",
                "   Each main memory block maps to exactly ONE cache line index: $\\text{Line} = (\\text{Block Address}) \\bmod (\\text{Total Cache Lines})$.",
                "   Address Split: $[ \\text{Tag Bits} \\mid \\text{Line Index Bits } (\\log_2 N_{lines}) \\mid \\text{Block Offset Bits } (w) ]$.",
                "3. **Fully Associative Cache:**",
                "   A memory block can be placed in ANY cache line. No index bits required. Requires parallel comparator hardware for all lines.",
                "   Address Split: $[ \\text{Tag Bits} \\mid \\text{Block Offset Bits } (w) ]$.",
                "4. **k-way Set-Associative Cache:**",
                "   Cache lines are grouped into sets of $k$ lines each. Block maps to: $\\text{Set} = (\\text{Block Address}) \\bmod (\\text{Total Sets})$.",
                "   Address Split: $[ \\text{Tag Bits} \\mid \\text{Set Index Bits } (\\log_2 N_{sets}) \\mid \\text{Block Offset Bits } (w) ]$.",
                "   $\\text{Total Sets} = \\frac{\\text{Total Cache Capacity}}{\\text{Block Size} \\times k} = \\frac{N_{lines}}{k}$.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Tag Directory Overhead Formulation",
                message:
                  "Tag Directory Size = $\\text{Total Lines} \\times [\\text{Tag Bits} + \\text{Valid Bit} + \\text{Dirty Bit} + \\text{Replacement Bits}]$. In a $k$-way set-associative cache with LRU, each set requires $\\lceil \\log_2(k!) \\rceil$ or an approximation $\\lceil \\log_2 k \\rceil$ bits per line for LRU tracking.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. GATE Worked Numerical: Cache Bit Splitting & Tag Directory Size",
              weightage: "2 Marks",
              trap: "Always divide cache capacity by (Block Size * k) to get the number of sets in a set-associative cache. Do not use the line count directly for the index field!",
              solutionSteps: [
                "Problem: A 32-bit byte-addressable system contains a 64 KB 4-way set-associative cache with 64-byte block size. Find:",
                "1. Number of Tag, Set Index, and Block Offset bits.",
                "2. Total cache memory overhead (tag directory capacity) assuming 1 valid bit and 1 dirty bit per line.",
                "Step 1: Compute Block Offset bits:",
                "  $w = \\log_2(64 \\text{ bytes}) = 6 \\text{ bits}$.",
                "Step 2: Compute Total Lines:",
                "  $N_{lines} = \\frac{\\text{Cache Size}}{\\text{Block Size}} = \\frac{64 \\text{ KB}}{64 \\text{ B}} = 1024 \\text{ lines}$.",
                "Step 3: Compute Total Sets for 4-way set-associative (k = 4):",
                "  $N_{sets} = \\frac{1024}{4} = 256 \\text{ sets}$.",
                "Step 4: Compute Set Index bits:",
                "  $s = \\log_2(256) = 8 \\text{ bits}$.",
                "Step 5: Compute Tag bits:",
                "  $\\text{Tag} = 32 - s - w = 32 - 8 - 6 = 18 \\text{ bits}$.",
                "Step 6: Compute Tag Directory Overhead:",
                "  Bits per line $= \\text{Tag} (18) + \\text{Valid} (1) + \\text{Dirty} (1) = 20 \\text{ bits/line}$.",
                "  Total Tag Directory $= 1024 \\text{ lines} \\times 20 \\text{ bits} = 20,480 \\text{ bits} = 2560 \\text{ bytes} = 2.5 \\text{ KB}$.",
              ],
            },
            {
              type: "explanation",
              heading: "3. Multi-Level Average Memory Access Time (AMAT)",
              body: [
                "AMAT models the effective latency seen by the CPU across the memory hierarchy:",
                "**1. Single-Level Cache:**",
                "$\\text{AMAT} = T_{hit} + (M_{rate} \\times T_{penalty})$.",
                "**2. Two-Level Cache Hierarchy (L1 and L2):**",
                "$\\text{AMAT} = T_{L1} + M_{L1} \\times (T_{L2} + M_{L2,local} \\times T_{MM})$.",
                "**Local vs Global Miss Rate Distinction:**",
                "- **Local Miss Rate of L2 ($M_{L2,local}$):** $\\frac{\\text{Misses in L2}}{\\text{Accesses to L2 (Misses from L1)}}$.",
                "- **Global Miss Rate of L2 ($M_{L2,global}$):** $\\frac{\\text{Misses in L2}}{\\text{Total CPU References}} = M_{L1} \\times M_{L2,local}$.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "4. GATE Worked Numerical: Multi-Level Cache AMAT",
              weightage: "2 Marks",
              trap: "Ensure you check whether L2 miss rate is specified as LOCAL or GLOBAL! If GLOBAL miss rate is given, the formula simplifies to: AMAT = T_L1 + M_L1 * T_L2 + M_L2,global * T_MM.",
              solutionSteps: [
                "Problem: An L1 cache has hit time = 1 ns and miss rate = 8%. An L2 cache has hit time = 6 ns and local miss rate = 12%. Main memory access latency is 100 ns. Calculate overall AMAT.",
                "Step 1: Multi-level AMAT formula:",
                "  $\\text{AMAT} = T_{L1} + M_{L1} \\times (T_{L2} + M_{L2,local} \\times T_{MM})$.",
                "Step 2: Evaluate L1 miss penalty:",
                "  $\\text{Penalty}_{L1} = 6 \\text{ ns} + (0.12 \\times 100 \\text{ ns}) = 6 + 12 = 18 \\text{ ns}$.",
                "Step 3: Compute final AMAT:",
                "  $\\text{AMAT} = 1 \\text{ ns} + (0.08 \\times 18 \\text{ ns}) = 1 + 1.44 = 2.44 \\text{ ns}$.",
              ],
            },
            {
              type: "resources",
              heading: "5. References & Authoritative Sources",
              sources: [
                {
                  title: "Computer Organization and Design: The Hardware/Software Interface (5th Edition)",
                  authors: "David A. Patterson, John L. Hennessy",
                  year: "2013",
                  publisher: "Morgan Kaufmann",
                  relevance:
                    "Chapter 5: Large and Fast: Exploiting Memory Hierarchy — the gold-standard reference for cache architectures, AMAT derivations, and multi-level memory benchmarking.",
                },
              ],
            },
          ],
          cheatsheet: {
            title: "Cache Mapping & AMAT Quick Revision",
            summaryRule: "In set-associative caches, Set Index = log2(Capacity / (Block Size * k)); AMAT = T_L1 + M_L1 * (T_L2 + M_L2_local * T_MM).",
            keyFormulasAndRules: [
              "Direct: Line Index = log2(Lines); Tag = Address - Index - Offset.",
              "Fully Associative: Zero index bits; Tag = Address - Offset.",
              "k-way Set-Associative: Sets = Capacity / (Block Size * k); Set Index = log2(Sets).",
              "AMAT = T_L1 + M_L1 * (T_L2 + M_L2_local * T_MM).",
              "Global Miss Rate L2 = M_L1 * M_L2_local.",
            ],
            examPitfalls: [
              "Do not forget to count the Dirty bit in write-back cache tag directory size calculations.",
              "Cache capacity refers to DATA capacity; tag bits, valid bits, and dirty bits are additional hardware overhead.",
            ],
          },
        },
        {
          id: "cache-replacement-write-policies-and-interleaving",
          title: "Cache Replacement, Write Policies & Memory Interleaving",
          slug: "cache-replacement-write-policies-and-interleaving",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Write-through vs write-back, write allocate, LRU stacks, and memory interleaving math.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          sections: [
            {
              type: "explanation",
              heading: "1. Cache Write Policies: Write-Through vs Write-Back",
              body: [
                "When the CPU writes data to memory, cache and main memory must maintain consistency:",
                "**1. Write-Hit Policies:**",
                "- **Write-Through:** Every write to the cache is simultaneously propagated to main memory. Main memory is always up to date. Requires a Write Buffer to avoid CPU stalling during slow RAM writes.",
                "- **Write-Back (Copy-Back):** Data is written only to the cache line. The block is written back to main memory ONLY when it is evicted. Requires a ==pink:Dirty Bit (Modified Bit)== per cache line to track if the line was modified.",
                "**2. Write-Miss Policies:**",
                "- **Write-Allocate (Fetch on Write):** The block is loaded into the cache from main memory on a write miss, followed by the write hit operation. Usually paired with Write-Back.",
                "- **No-Write-Allocate (Write Around):** The block is modified directly in main memory without loading it into the cache. Usually paired with Write-Through.",
                "**3. Main Memory Interleaving:**",
                "Divides physical memory into $m$ independent banks to achieve concurrent memory accesses:",
                "- **High-Order Interleaving:** Most significant bits select the memory bank; lower bits select the word within the bank. Does NOT provide parallelism for sequential array accesses.",
                "- **Low-Order Interleaving:** Least significant bits select the memory bank ($\\text{Bank} = \\text{Address} \\bmod m$). Consecutive addresses fall into consecutive memory banks! Allows pipelined access of $m$ consecutive words in time $T + (m - 1) \\times t_{bus}$.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. GATE Worked Numerical: Low-Order Memory Interleaving Latency",
              weightage: "2 Marks",
              trap: "Consecutive memory requests to low-order interleaved banks overlap in parallel. The time to read m consecutive words is NOT m * T_cycle, but T_access + (m - 1) * T_bus!",
              solutionSteps: [
                "Problem: A main memory system has 8 memory banks organized with low-order interleaving. Each bank has a memory cycle time of 80 ns. The bus transfer time per word is 10 ns. Find:",
                "1. Time to read 8 consecutive words without interleaving (single bank).",
                "2. Time to read 8 consecutive words with 8-way low-order interleaving.",
                "3. Speedup achieved by interleaving.",
                "Step 1: Without interleaving:",
                "  Each word requires a full memory cycle of 80 ns.",
                "  $T_{non-interleaved} = 8 \\times 80 \\text{ ns} = 640 \\text{ ns}$.",
                "Step 2: With 8-way low-order interleaving:",
                "  All 8 banks initiate their reads simultaneously at cycle 0.",
                "  The first word is ready at $T = 80 \\text{ ns}$ and transferred on the bus (takes 10 ns).",
                "  Subsequent words are transferred over the bus every 10 ns because their memory accesses already completed in parallel.",
                "  $T_{interleaved} = 80 \\text{ ns} + (8 - 1) \\times 10 \\text{ ns} = 80 + 70 = 150 \\text{ ns}$.",
                "Step 3: Speedup:",
                "  $S = \\frac{640 \\text{ ns}}{150 \\text{ ns}} \\approx 4.27\\times$.",
              ],
            },
            {
              type: "resources",
              heading: "3. References & Authoritative Sources",
              sources: [
                {
                  title: "Computer System Architecture (3rd Edition)",
                  authors: "M. Morris Mano",
                  year: "1993",
                  publisher: "Pearson",
                  relevance:
                    "Chapter 12: Memory Organization — memory hierarchy, auxiliary memory, associative memory, and cache write policies.",
                },
              ],
            },
          ],
          cheatsheet: {
            title: "Write Policies & Memory Interleaving Quick Revision",
            summaryRule: "Low-order memory interleaving maps consecutive memory addresses to parallel banks, reducing streaming latency to T_bank + (words - 1) * T_bus.",
            keyFormulasAndRules: [
              "Write-Through: Main memory always consistent; write buffer avoids CPU stalls.",
              "Write-Back: Writes to cache only; dirty bit tracks eviction flush to RAM.",
              "Low-Order Interleaving: Bank = Address mod m; sequential words map to parallel banks.",
              "Interleaved Latency: T_total = T_bank + (words - 1) * T_bus.",
            ],
            examPitfalls: [
              "High-order interleaving places consecutive words in the SAME bank, so it provides zero speedup for sequential array streaming.",
            ],
          },
        },
      ],
    },

    // =========================================================================
    // MODULE 4: INSTRUCTION PIPELINING & HAZARD MITIGATION
    // =========================================================================
    {
      id: "coa-module-4-instruction-pipelining",
      title: "Module 4: Instruction Pipelining, Hazards & Performance",
      slug: "instruction-pipelining",
      description:
        "5-stage RISC pipeline, clock cycle time = max(stage) + latch, speedup formulas, RAW/WAR/WAW data hazards, operand forwarding bypassing paths, and branch penalties.",
      order: 4,
      lessons: [
        {
          id: "pipeline-hazards-and-speedup-calculations",
          title: "Instruction Pipelining: Stages, Speedup & Hazards",
          slug: "pipeline-hazards-and-speedup-calculations",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Clock period = max(stage) + latch, RAW data stalls, forwarding, and speedup.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          sections: [
            {
              type: "explanation",
              heading: "1. The 5-Stage RISC Pipelined Execution Principle",
              body: [
                "Pipelining overlaps the execution of multiple instructions across independent hardware execution stages:",
                "1. **IF (Instruction Fetch):** Fetch instruction from cache using PC; increment $PC \\leftarrow PC + 4$.",
                "2. **ID / RF (Instruction Decode / Register Fetch):** Decode opcode and read operand registers from the register file.",
                "3. **EX (Execute / ALU):** Perform arithmetic/logical operation or compute effective memory address.",
                "4. **MEM (Memory Access):** Read or write data cache (LOAD/STORE instructions only).",
                "5. **WB (Write Back):** Write the result back into destination register.",
                "**Clock Cycle Time ($T_{clock}$):**",
                "The pipeline clock period is determined by the slowest stage plus the pipeline register latch overhead:",
                "$T_{clock} = \\max(\\text{Stage Delay}_i) + \\text{Latch Delay}$.",
                "**Pipeline Performance Metrics:**",
                "- Ideal CPI of an in-order pipeline = 1.",
                "- Speedup ($S$) for $n$ instructions on a $k$-stage pipeline:",
                "  $T_{nonpipe} = n \\times k \\times T_{clock}$",
                "  $T_{pipe} = [k + (n - 1)] \\times T_{clock}$",
                "  $S = \\frac{n \\times k}{k + n - 1}$. As $n \\to \\infty$, $S \\to k$.",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Three Pipeline Hazards & RAW Forwarding",
              body: [
                "A hazard is any condition that prevents the next instruction from executing in its designated clock cycle:",
                "1. **Structural Hazard:** Two instructions compete for the same physical hardware resource in the same cycle (e.g., single memory port accessed by IF and MEM simultaneously). Solution: Separate L1 Instruction and Data caches (Harvard architecture).",
                "2. **Data Hazard (RAW - Read-After-Write):** An instruction needs an operand produced by an earlier instruction that has not yet completed write-back. Three types exist:",
                "   - **RAW (True Dependency):** $I_2$ reads a register written by $I_1$. Occurs in in-order pipelines.",
                "   - **WAR (Anti-Dependency):** $I_2$ writes a register before $I_1$ reads it. Occurs only in out-of-order execution.",
                "   - **WAW (Output Dependency):** $I_2$ writes a register before $I_1$ writes it. Occurs only in out-of-order execution.",
                "**Remedies for RAW Hazards:**",
                "- **Software/Hardware Stalls:** Inserting bubble cycles.",
                "- **Operand Forwarding (Bypassing):** Routing ALU result from EX/MEM or MEM/WB pipeline registers directly to the ALU input multiplexers, eliminating stalls for ALU-to-ALU dependencies!",
                "- **Load-Use Delay:** A LOAD instruction produces its data at the end of the MEM stage. Even WITH forwarding, a dependent instruction immediately following a LOAD requires ==pink:1 stall bubble cycle==.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Register File Half-Cycle Reading Assumption",
                message:
                  "In GATE problems, assume that the Register File is written during the FIRST half of the clock cycle (WB stage), and read during the SECOND half (ID stage). This allows an instruction to read the newly written value in the same clock cycle without an extra stall!",
              },
            },
            {
              type: "gate-analysis",
              heading: "3. GATE Worked Numerical: Unequal Stage Delays & Effective CPI",
              weightage: "2 Marks",
              trap: "Clock period is set by the slowest stage delay PLUS latch delay! Non-pipelined instruction time is the pure sum of stage delays without latches.",
              solutionSteps: [
                "Problem: A 5-stage pipeline has stage delays: IF = 160 ps, ID = 120 ps, EX = 220 ps, MEM = 180 ps, and WB = 100 ps. Pipeline register latch delay is 20 ps. In a benchmark program, 20% of instructions are conditional branches that cause 2 stall cycles. Find:",
                "1. Clock cycle time.",
                "2. Effective CPI.",
                "3. Speedup over an unpipelined processor.",
                "Step 1: Clock Cycle Time:",
                "  $T_{clock} = \\max(160, 120, 220, 180, 100) + 20 \\text{ ps} = 220 + 20 = 240 \\text{ ps}$.",
                "Step 2: Effective CPI:",
                "  $\\text{CPI} = \\text{Ideal CPI} + \\text{Stall cycles per instruction}$",
                "  $\\text{CPI} = 1 + (0.20 \\times 2) = 1 + 0.40 = 1.40 \\text{ cycles/instruction}$.",
                "Step 3: Average execution time per instruction in pipelining:",
                "  $T_{pipe,avg} = \\text{CPI} \\times T_{clock} = 1.40 \\times 240 \\text{ ps} = 336 \\text{ ps}$.",
                "Step 4: Non-pipelined execution time per instruction:",
                "  $T_{nonpipe} = 160 + 120 + 220 + 180 + 100 = 780 \\text{ ps}$.",
                "Step 5: Speedup:",
                "  $S = \\frac{T_{nonpipe}}{T_{pipe,avg}} = \\frac{780 \\text{ ps}}{336 \\text{ ps}} \\approx 2.32\\times$.",
              ],
            },
            {
              type: "resources",
              heading: "4. References & Authoritative Sources",
              sources: [
                {
                  title: "Computer Organization and Design RISC-V Edition",
                  authors: "David A. Patterson, John L. Hennessy",
                  year: "2017",
                  publisher: "Morgan Kaufmann",
                  relevance:
                    "Chapter 4: The Processor — detailed timing diagrams of 5-stage pipeline data forwarding and hazard detection units.",
                },
              ],
            },
          ],
          cheatsheet: {
            title: "Pipelining & Hazards Quick Revision",
            summaryRule: "Pipeline clock period equals max stage delay plus latch overhead; full operand forwarding eliminates stalls for ALU-to-ALU dependencies.",
            keyFormulasAndRules: [
              "T_clock = max(Stage Delays) + Latch Delay.",
              "Ideal CPI = 1; Actual CPI = 1 + Stalls_data + Stalls_branch.",
              "RAW (Read-After-Write) is the only data hazard in in-order pipelines.",
              "Operand forwarding resolves ALU-to-ALU dependencies with 0 stalls.",
              "Load-Use hazard requires 1 stall bubble even with full forwarding.",
            ],
            examPitfalls: [
              "Do not forget latch delay when computing the pipelined clock period.",
              "Ensure register file write occurs in first half-cycle and read in second half-cycle before adding unnecessary bubbles.",
            ],
          },
        },
        {
          id: "structural-control-hazards-and-branch-prediction",
          title: "Branch Hazards, Dynamic Predictors & Branch Target Buffers",
          slug: "structural-control-hazards-and-branch-prediction",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Branch penalties, 2-bit saturating counters, Branch Target Buffers (BTB), and delayed branch.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          sections: [
            {
              type: "explanation",
              heading: "1. Control Hazards & Branch Penalty Dynamics",
              body: [
                "A **Control Hazard** occurs when the pipeline cannot determine the next instruction to fetch because a conditional branch instruction has not yet been resolved.",
                "**Branch Resolution Points:**",
                "1. If branch outcome and target address are resolved at the **EX stage (Stage 3):** The penalty for a taken branch is ==pink:2 stall cycles== (instructions fetched during ID and EX must be flushed).",
                "2. If branch outcome is resolved early at the **ID stage (Stage 2)** with dedicated hardware: The penalty for a taken branch is reduced to ==yellow:1 stall cycle==.",
                "**Branch Hazard Mitigation Strategies:**",
                "- **Delayed Branching:** The instruction immediately following the branch (in the 'delay slot') is ALWAYS executed regardless of whether the branch is taken. The compiler fills this slot with useful work.",
                "- **Static Branch Prediction:** Assume branch is always taken (or always not taken).",
                "- **Dynamic Branch Prediction (2-Bit Saturating Counter):** Uses a 4-state finite state machine per branch instruction:",
                "  - Strongly Taken (11)",
                "  - Weakly Taken (10)",
                "  - Weakly Not Taken (01)",
                "  - Strongly Not Taken (00)",
                "  Requires TWO consecutive mispredictions to change prediction direction. Highly accurate for loops!",
                "- **Branch Target Buffer (BTB):** A small cache indexed by branch PC that stores predicted target addresses. If hit, the target is fetched in the very next cycle with 0 stalls!",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. GATE Worked Numerical: 2-Bit Dynamic Predictor Accuracy",
              weightage: "2 Marks",
              trap: "Trace loop branches carefully! For a loop executing N times, the branch is TAKEN (N-1) times and NOT TAKEN on the final exit.",
              solutionSteps: [
                "Problem: A loop `for (int i = 0; i < 4; i++)` is executed. The conditional branch at the loop bottom is predicted using a 2-bit saturating predictor initialized to Strongly Not Taken (00). Find the number of mispredictions for the first execution of this loop.",
                "Step 1: Understand branch behavior:",
                "  Iteration 1 (i = 0): Loop repeats $\\implies$ Branch is TAKEN (T).",
                "  Iteration 2 (i = 1): Loop repeats $\\implies$ Branch is TAKEN (T).",
                "  Iteration 3 (i = 2): Loop repeats $\\implies$ Branch is TAKEN (T).",
                "  Iteration 4 (i = 3): Loop terminates $\\implies$ Branch is NOT TAKEN (NT).",
                "  Sequence of outcomes: T, T, T, NT.",
                "Step 2: Trace predictor state transitions:",
                "  Initial State: 00 (Strongly Not Taken) $\\implies$ Predicts NT.",
                "  Branch 1 (Outcome: T): Prediction NT is INCORRECT (Misprediction 1). State moves $00 \\to 01$ (Weakly Not Taken).",
                "  Branch 2 (Outcome: T): Prediction NT is INCORRECT (Misprediction 2). State moves $01 \\to 10$ (Weakly Taken).",
                "  Branch 3 (Outcome: T): Prediction T is CORRECT! State moves $10 \\to 11$ (Strongly Taken).",
                "  Branch 4 (Outcome: NT): Prediction T is INCORRECT (Misprediction 3). State moves $11 \\to 10$ (Weakly Taken).",
                "Step 3: Total mispredictions = 3 mispredictions out of 4 branch executions.",
              ],
            },
            {
              type: "resources",
              heading: "3. References & Authoritative Sources",
              sources: [
                {
                  title: "Computer Architecture: A Quantitative Approach (6th Edition)",
                  authors: "John L. Hennessy, David A. Patterson",
                  year: "2017",
                  publisher: "Morgan Kaufmann",
                  relevance:
                    "Chapter 3: Instruction-Level Parallelism and Its Exploitation — dynamic branch prediction, BTB caches, and speculative execution.",
                },
              ],
            },
          ],
          cheatsheet: {
            title: "Branch Hazards & Dynamic Prediction Quick Revision",
            summaryRule: "Branch penalty cycles equal the stages elapsed before target address and branch condition are resolved; 2-bit counter requires two errors to flip.",
            keyFormulasAndRules: [
              "Branch penalty = Stages elapsed before target address and condition are resolved.",
              "Resolving branch at ID stage gives 1 stall cycle; at EX stage gives 2 stall cycles.",
              "2-bit saturating counter states: 11 (Strongly Taken), 10 (Weakly Taken), 01 (Weakly Not Taken), 00 (Strongly Not Taken).",
              "BTB cache eliminates branch penalty completely on hit.",
            ],
            examPitfalls: [
              "Remember that the 2-bit counter requires two successive mispredictions to flip its prediction between Taken and Not Taken.",
            ],
          },
        },
      ],
    },

    // =========================================================================
    // MODULE 5: CONTROL UNIT DESIGN & INPUT/OUTPUT SYSTEMS
    // =========================================================================
    {
      id: "coa-module-5-control-unit-and-io",
      title: "Module 5: Control Unit Design, DMA & Interrupts",
      slug: "control-unit-and-io",
      description:
        "Hardwired vs microprogrammed control units, horizontal vs vertical microinstructions, control store sizing, programmed I/O, interrupts, and DMA transfer modes.",
      order: 5,
      lessons: [
        {
          id: "microprogrammed-control-and-dma",
          title: "Microprogrammed Control Units & DMA Transfer Modes",
          slug: "microprogrammed-control-and-dma",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Horizontal/Vertical control words, control store sizing, and DMA cycle stealing.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          sections: [
            {
              type: "explanation",
              heading: "1. Control Unit Design: Hardwired vs Microprogrammed",
              body: [
                "The **Control Unit (CU)** orchestrates the processor datapath by generating binary control signals that open multiplexers, enable registers, and command the ALU:",
                "1. **Hardwired Control Unit:**",
                "   - Implemented using fixed combinational logic gates, decoders, and finite state machines.",
                "   - Extremely fast clock frequencies (used in RISC architectures).",
                "   - Inflexible: Adding or modifying instructions requires physically redesigning the silicon chip layout.",
                "2. **Microprogrammed Control Unit:**",
                "   - Control signals are stored as binary words ('microinstructions') inside an internal fast ROM called **Control Memory (CM)**.",
                "   - Highly flexible (used in CISC architectures): instruction set extensions can be implemented by updating ROM firmware.",
                "   - Slower execution due to control memory read latency.",
                "**Horizontal vs Vertical Microinstruction Architectures:**",
                "- **Horizontal Microinstruction:** Every control signal is allocated a dedicated bit (1 bit per signal). No decoder needed. Wide control word, maximum parallelism, large ROM size.",
                "- **Vertical Microinstruction:** Mutually exclusive control signals are partitioned into groups and encoded into binary fields. A field of $n$ mutually exclusive signals requires $\\lceil \\log_2(n + 1) \\rceil$ bits (where $+1$ accounts for the NO-OP / inactive state). Narrow control word, requires external decoders.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. GATE Worked Numerical: Horizontal vs Vertical Control Word Width",
              weightage: "2 Marks",
              trap: "Always include the +1 state for the inactive / NO-OP condition in vertical microinstruction field encoding! A group of 7 signals requires ceil(log2(7 + 1)) = 3 bits.",
              solutionSteps: [
                "Problem: A processor has 32 control signals divided into 4 mutually exclusive groups containing 7, 12, 5, and 8 signals respectively. The control memory stores 512 words. Find:",
                "1. Control word bit-width for horizontal microprogramming.",
                "2. Control word bit-width for vertical microprogramming.",
                "3. Total bits saved in the control store.",
                "Step 1: Horizontal control word width:",
                "  1 bit per signal $\\implies 32 \\text{ bits}$.",
                "Step 2: Vertical control word encoding for each group:",
                "  Group 1 (7 signals): $\\lceil \\log_2(7 + 1) \\rceil = \\lceil \\log_2 8 \\rceil = 3 \\text{ bits}$.",
                "  Group 2 (12 signals): $\\lceil \\log_2(12 + 1) \\rceil = \\lceil \\log_2 13 \\rceil = 4 \\text{ bits}$.",
                "  Group 3 (5 signals): $\\lceil \\log_2(5 + 1) \\rceil = \\lceil \\log_2 6 \\rceil = 3 \\text{ bits}$.",
                "  Group 4 (8 signals): $\\lceil \\log_2(8 + 1) \\rceil = \\lceil \\log_2 9 \\rceil = 4 \\text{ bits}$.",
                "  Total vertical control bits $= 3 + 4 + 3 + 4 = 14 \\text{ bits}$.",
                "Step 3: Total control memory bit comparison:",
                "  $\\text{Size}_{horizontal} = 512 \\text{ words} \\times 32 \\text{ bits} = 16,384 \\text{ bits}$.",
                "  $\\text{Size}_{vertical} = 512 \\text{ words} \\times 14 \\text{ bits} = 7,168 \\text{ bits}$.",
                "  Bits saved $= 16,384 - 7,168 = 9,216 \\text{ bits}$ (56.25% memory reduction).",
              ],
            },
            {
              type: "explanation",
              heading: "3. Direct Memory Access (DMA) & Transfer Modes",
              body: [
                "**Direct Memory Access (DMA)** enables high-speed peripheral devices (disks, network cards) to transfer data directly to/from main memory without continuous CPU intervention.",
                "**The Three DMA Operational Modes:**",
                "1. **Burst Mode (Block Transfer):** The DMA controller acquires the system bus and transfers an entire contiguous block of data. The CPU is completely halted from accessing memory during the transfer.",
                "2. **Cycle Stealing Mode:** The DMA controller 'steals' one bus cycle from the CPU at a time, interleaving memory cycles between CPU execution and DMA transfer. CPU execution is slowed down proportionally, but never blocked.",
                "3. **Transparent (Hidden) Mode:** The DMA controller transfers data only when the CPU is performing internal operations (such as ALU execution) and is not using the system bus. Zero CPU slowdown!",
              ],
              callout: {
                kind: "gate-tip",
                title: "CPU Slowdown in Cycle Stealing Mode",
                message:
                  "If a peripheral produces data at rate R bytes/sec, and the memory bus transfers 1 byte in time T_bus, the fraction of CPU time stolen by DMA is: Fraction = R * T_bus. CPU execution is slowed by this exact percentage!",
              },
            },
            {
              type: "resources",
              heading: "4. References & Authoritative Sources",
              sources: [
                {
                  title: "Computer System Architecture (3rd Edition)",
                  authors: "M. Morris Mano",
                  year: "1993",
                  publisher: "Pearson",
                  relevance:
                    "Chapter 7: Microprogrammed Control and Chapter 11: Input-Output Organization — classical diagrams of DMA bus grant/request arbitration.",
                },
              ],
            },
          ],
          cheatsheet: {
            title: "Control Units & DMA Quick Revision",
            summaryRule: "Vertical microinstructions group mutually exclusive signals with ceil(log2(n+1)) bits per group; DMA cycle stealing slows CPU by Rate * T_bus.",
            keyFormulasAndRules: [
              "Horizontal microinstructions: 1 bit per signal; no decoder; high speed.",
              "Vertical microinstructions: Groups encoded with ceil(log2(n+1)) bits; requires decoders.",
              "Burst mode: CPU halted for the entire block transfer.",
              "Cycle stealing: DMA steals 1 bus cycle per data word; CPU slows by fraction = Rate * T_bus.",
            ],
            examPitfalls: [
              "Remember the +1 idle state when computing vertical field bit widths.",
            ],
          },
        },
        {
          id: "io-interrupts-and-bus-arbitration",
          title: "Interrupts, Daisy Chaining Priority & Bus Arbitration",
          slug: "io-interrupts-and-bus-arbitration",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Vectored vs non-vectored interrupts, daisy chaining propagation delay, and bus arbitration.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          sections: [
            {
              type: "explanation",
              heading: "1. Interrupts & Interrupt Service Routine (ISR) Flow",
              body: [
                "An **Interrupt** is an asynchronous signal from hardware (I/O device, timer) or a synchronous trap from software that demands immediate CPU attention.",
                "**Interrupt Handling Sequence:**",
                "1. CPU checks the interrupt line at the conclusion of the current instruction execution cycle.",
                "2. If an interrupt is asserted and interrupts are enabled: CPU pushes current Program Counter (PC) and processor status register (PSR) onto the hardware stack.",
                "3. CPU issues an Interrupt Acknowledge (INTA) signal.",
                "4. **Vectored vs Non-Vectored Interrupts:**",
                "   - **Vectored Interrupt:** The interrupting device places an interrupt vector address (or vector number) directly onto the data bus. The CPU branches directly to that specific ISR address in the Interrupt Vector Table (IVT).",
                "   - **Non-Vectored Interrupt:** The CPU branches to a fixed single memory address, where a polling software routine queries each I/O device's status register sequentially to determine the interrupt source.",
                "**Priority Interrupt Schemes:**",
                "- **Software Polling:** CPU polls devices in order of descending priority. Slow, latency proportional to the number of devices.",
                "- **Hardware Daisy Chaining:** Serial priority arbitration. The INTA line passes sequentially through Device 1 $\\to$ Device 2 $\\to$ Device 3. Device 1 has highest priority. If it requested an interrupt, it blocks INTA from propagating further down the chain.",
                "- **Parallel Priority Encoder:** All interrupt request lines connect in parallel to a priority encoder hardware chip that outputs the binary code of the highest-priority active device in $O(1)$ gate delays.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. GATE Worked Numerical: DMA Cycle Stealing CPU Overhead",
              weightage: "2 Marks",
              trap: "Data rate must be matched with bus transfer cycle time! Always compute how many bus cycles are stolen per second.",
              solutionSteps: [
                "Problem: A hard disk transfers data at a rate of 4 MB/sec (where 1 MB = 10^6 bytes). The system bus has a cycle time of 200 ns and transfers 1 byte per cycle. The CPU clock frequency is 20 MHz with an average CPI of 2.0.",
                "Find the percentage of CPU execution time stolen by the DMA controller in cycle-stealing mode.",
                "Step 1: Bytes transferred per second:",
                "  $\\text{Rate} = 4 \\times 10^6 \\text{ bytes/second}$.",
                "Step 2: Time required for one byte transfer over the bus:",
                "  $T_{bus} = 200 \\text{ ns} = 200 \\times 10^{-9} \\text{ s}$.",
                "Step 3: Total bus time stolen by DMA in 1 second:",
                "  $\\text{Time Stolen} = 4 \\times 10^6 \\text{ bytes} \\times (200 \\times 10^{-9} \\text{ s/byte}) = 4 \\times 10^6 \\times 2 \\times 10^{-7} = 0.80 \\text{ seconds}$.",
                "Step 4: Percentage of CPU time consumed by DMA:",
                "  $\\text{Percentage} = \\frac{0.80 \\text{ s}}{1.00 \\text{ s}} \\times 100\\% = 80\\%$.",
                "  The CPU is slowed down by 80%, retaining only 20% of its normal execution bandwidth.",
              ],
            },
            {
              type: "resources",
              heading: "3. References & Authoritative Sources",
              sources: [
                {
                  title: "Computer Organization and Embedded Systems (6th Edition)",
                  authors: "Carl Hamacher, Zvonko Vranesic, Safwat Zaky, Naraig Manjikian",
                  year: "2011",
                  publisher: "McGraw-Hill",
                  relevance:
                    "Chapter 3: Input/Output Organization — vectored interrupts, daisy chaining priority logic, and DMA controllers.",
                },
              ],
            },
          ],
          cheatsheet: {
            title: "Interrupts & Bus Arbitration Quick Revision",
            summaryRule: "Vectored interrupts supply vector address directly on the data bus; daisy chaining arbitrates device priority in serial hardware order.",
            keyFormulasAndRules: [
              "Vectored: Device supplies vector address directly over the bus to jump to ISR.",
              "Non-vectored: CPU jumps to fixed location and polls devices sequentially.",
              "Daisy chaining: Priority ordered by physical position closest to CPU.",
              "DMA slowdown % = Data Transfer Rate * Bus Cycle Time.",
            ],
            examPitfalls: [
              "Ensure matching units: If rate is in bytes/sec, multiply by bus cycle time in seconds per byte.",
            ],
          },
        },
      ],
    },
  ],
};
