import { CourseMeta } from "./types";

export const COMPILER_DESIGN_COURSE: CourseMeta = {
  id: "compiler-design",
  title: "Compiler Design",
  slug: "compiler-design",
  subjectSlug: "compiler-design",
  shortTitle: "Compilers",
  icon: "🔧",
  color: "bg-orange-400",
  tagline:
    "Master lexical DFA tokenization, LL(1) grammar conditions, LR parsing tables, syntax-directed translations, and control-flow basic block optimizations.",
  description:
    "A rigorous, mathematically formal study notebook covering all phases of compiler construction: lexical scanning and buffer pair dynamics, regular expressions to minimal DFAs, top-down LL(1) predictive parsing with FIRST and FOLLOW sets, bottom-up LR(0), SLR(1), LALR(1), and CLR(1) canonical item collections, core state merging proofs, S-attributed and L-attributed Syntax-Directed Definitions (SDDs), intermediate Three-Address Code (TAC), Static Single Assignment (SSA), basic block partitioning, Control Flow Graphs (CFG), Directed Acyclic Graphs (DAG), and loop optimizations for undergraduate university excellence and top-rank GATE CS/IT performance.",
  level: "Undergraduate / GATE CS",
  estimatedHours: 42,
  prerequisites: [
    "Theory of Computation (DFA, NFA, Context-Free Grammars, Ambiguity)",
    "C Programming & Data Structures (Trees, Stacks, Hash Tables, Pointer Arithmetic)",
  ],
  learningOutcomes: [
    "Design deterministic finite automata for lexical token scanning, evaluate buffer pair sentinels, and apply maximal munch rules",
    "Compute FIRST and FOLLOW sets for complex context-free grammars and eliminate immediate and general left recursion",
    "Construct LL(1) predictive parsing tables, diagnose Shift-Reduce and non-LL(1) grammar conflicts, and compute table entry bounds",
    "Synthesize canonical item collections for LR(0), SLR(1), LALR(1), and CLR(1) parsers and formulate handle pruning stack traces",
    "Prove the LALR(1) state merging theorem and analyze why merging identical LR(0) cores cannot introduce Shift-Reduce conflicts",
    "Differentiate S-attributed vs L-attributed Syntax-Directed Definitions and trace semantic stack evaluations during parsing",
    "Generate intermediate Three-Address Code, Quadruples, Triples, and Static Single Assignment (SSA) form with phi-functions",
    "Partition intermediate instructions into Basic Blocks using leader identification, build CFGs, and apply DAG loop optimizations",
  ],
  gateScope: "GATE 2027 CS/IT scope",
  gateBranches: ["cs"],
  gateSyllabusTopics: [
    "Lexical analysis: Regular expressions, token recognition, finite automata, input buffering",
    "Syntax analysis: Context-free grammars, LL(1) predictive parsing, bottom-up LR(0), SLR(1), LALR(1), CLR(1) parsers, conflicts",
    "Syntax-directed translation: S-attributed and L-attributed definitions, evaluation orders, translation schemes",
    "Intermediate code generation: Three-address code, quadruples, triples, static single assignment (SSA)",
    "Code optimization: Basic blocks, control flow graphs, DAG representation of basic blocks, loop optimizations, data flow analysis",
    "Runtime environments: Activation records, storage organization, parameter passing mechanisms",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: LEXICAL ANALYSIS, TOKENIZATION & FINITE AUTOMATA
    // =========================================================================
    {
      id: "cd-module-1-lexical-analysis",
      title: "Module 1: Lexical Analysis, Tokenization & Finite Automata",
      slug: "lexical-analysis",
      description:
        "Compiler front-end architecture, role of lexical scanner, tokens, patterns, lexemes, buffer pairs with sentinels, regular expressions, and minimal DFA construction.",
      order: 1,
      lessons: [
        {
          id: "lexical-analysis-tokens-buffers",
          title: "Lexical Tokens, Buffer Pairs & Finite Automata Scanning",
          slug: "lexical-analysis-tokens-buffers",
          order: 1,
          estimatedMinutes: 28,
          tagline: "Tokenization boundaries, buffer pair pointer arithmetic, and scanner error recovery strategies.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A Lexical Analyzer scans character streams and converts them into tokens <token-name, attribute-value>. Whitespace and comments are stripped; buffer pairs eliminate lookahead overhead.",
            keyFormulasAndRules: [
              "Token = Abstract terminal category (e.g., `id`, `number`, `if`). Pattern = Formal description (Regular Expression). Lexeme = Concrete character sequence in source code (e.g., `count`, `3.1415`).",
              "Buffer Pairs Scheme: Two N-character buffers loaded alternatively. Pointers: `lexemeBegin` (start of current token) and `forward` (lookahead scanner).",
              "Sentinel Optimization: Appending EOF at the end of each buffer half reduces boundary checks from 2 tests per character (buffer end check + char test) to 1 test per character.",
              "Lexical Errors: Scanner cannot detect syntax errors (e.g., mismatched parentheses) or semantic errors (e.g., undeclared variables). It only catches illegal characters or malformed tokens.",
              "Error Recovery: Panic mode (discarding characters until valid token), deleting extraneous characters, inserting missing characters, or transposing adjacent characters.",
            ],
            examPitfalls: [
              "Undeclared identifiers or type mismatches are NEVER lexical errors; they are checked during Semantic Analysis.",
              "Comments and whitespace do NOT produce tokens; they are consumed and discarded by the lexical analyzer.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Scanner's Role in Compiler Architecture",
              body: [
                "A compiler operates in phases: Lexical Analysis (Scanner) -> Syntax Analysis (Parser) -> Semantic Analysis (Type Checker) -> Intermediate Code Generation (IR) -> Machine-Independent Optimization -> Code Generation -> Machine-Dependent Optimization.",
                "The **Lexical Analyzer** is the only phase that reads the source code character by character from disk/memory. Its primary job is to isolate sequences of characters called **lexemes** and translate them into typed **tokens** of the form `<token-name, attribute-value>`.",
                "Separating lexical analysis from syntax analysis provides three major advantages: (1) **Simplicity of design**: the parser grammar does not need to handle whitespace and comment syntax; (2) **Efficiency**: specialized buffer techniques allow lexical scanning at hardware speed; (3) **Portability**: platform-specific character encodings are isolated entirely within the scanner.",
                "**Buffer Pairs Architecture:** Reading character by character via operating system `read()` calls incurs intolerable I/O overhead. Modern scanners allocate a single array of size `2N` divided into two halves of size `N` (typically 4096 bytes).",
                "Two pointers traverse the buffer: `lexemeBegin` points to the first character of the lexeme currently being constructed. `forward` advances ahead until a complete pattern match is identified. When `forward` approaches the boundary of one buffer half, the other half is filled with the next chunk of source characters asynchronously.",
              ],
              callout: {
                kind: "mental-model",
                title: "The Sentinel Test Reduction",
                message: "Without a sentinel, advancing `forward` requires: `if (forward at end of buffer) reload(); if (*forward == target) ...`. By appending an `eof` character at the end of each buffer half, the scanner only tests `if (*forward == eof)` to handle both buffer wrapping and genuine file termination.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Token Counting & Buffer Pointer Dynamics",
              weightage: "2 Marks (GATE CS)",
              trap: "String literals count as exactly 1 token regardless of the spaces or words inside them. Preprocessor directives or printf format specifiers are tokenized as single string constant tokens.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "Calculate the exact number of tokens generated by the lexical analyzer for the following C code snippet:",
                "```c",
                "int max = (a >= b) ? a : b; /* ternary comparison */",
                "printf(\"Result = %d\\n\", max);",
                "```",
                "Step 1: Analyze Line 1: `int max = (a >= b) ? a : b; /* ternary comparison */`",
                "  - `int` : keyword token [1]",
                "  - `max` : identifier token [2]",
                "  - `=` : assignment operator token [3]",
                "  - `(` : opening parenthesis delimiter [4]",
                "  - `a` : identifier token [5]",
                "  - `>=` : relational operator token [6]",
                "  - `b` : identifier token [7]",
                "  - `)` : closing parenthesis delimiter [8]",
                "  - `?` : conditional operator token [9]",
                "  - `a` : identifier token [10]",
                "  - `:` : colon operator token [11]",
                "  - `b` : identifier token [12]",
                "  - `;` : semicolon delimiter token [13]",
                "  - `/* ternary comparison */` : comment is stripped (0 tokens).",
                "Step 2: Analyze Line 2: `printf(\"Result = %d\\n\", max);`",
                "  - `printf` : identifier token [14]",
                "  - `(` : opening parenthesis delimiter [15]",
                "  - `\"Result = %d\\n\"` : string literal constant [16]",
                "  - `,` : comma delimiter token [17]",
                "  - `max` : identifier token [18]",
                "  - `)` : closing parenthesis delimiter [19]",
                "  - `;` : semicolon delimiter token [20]",
                "Total Tokens = 13 + 7 = 20 tokens.",
              ],
            },
            {
              type: "quick-revision",
              heading: "3. Rapid Lexical Analysis Diagnostic Summary",
              oneMinutePanicCard: {
                coreRule: "Lexical analyzers strip whitespace and comments, group characters into tokens, and communicate with the symbol table using (token_name, attribute_pointer).",
                mustRememberFormulas: [
                  "Tokens per string literal = 1 (enclosed contents are treated as a single token attribute).",
                  "Operators like '++' or '>=' are single multi-character tokens, not pairs of individual symbols.",
                  "Buffer size 2N with sentinels reduces loop branches by half.",
                ],
                criticalPitfalls: [
                  "Do not count header files `#include <stdio.h>` as compiler tokens if the preprocessor runs before the lexer.",
                  "Lexer cannot detect undeclared variables or syntax errors.",
                ],
              },
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Compilers: Principles, Techniques, and Tools (Dragon Book, 2nd Edition)",
                  authors: "Alfred V. Aho, Monica S. Lam, Ravi Sethi, Jeffrey D. Ullman",
                  year: "2006",
                  publisher: "Pearson Education",
                  relevance: "Chapter 3: Lexical Analysis, Input Buffering, and Token Specification.",
                },
              ],
            },
          ],
        },
        {
          id: "regular-expressions-to-lexical-dfa",
          title: "Token Specification, Regular Expressions to Lexical DFA & Longest Match",
          slug: "regular-expressions-to-lexical-dfa",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Maximal munch rule, Thompson's construction, subset powerset simulation, and minimal state scanning.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Lexical rules use Regular Expressions converted via Thompson's NFA to minimal DFA. Conflicts are resolved by: (1) Longest Match (Maximal Munch) and (2) First Rule Priority for equal-length matches.",
            keyFormulasAndRules: [
              "Maximal Munch (Longest Match): The scanner always matches the longest prefix of remaining input that corresponds to a valid token (e.g., `===` is tokenized as `==` and `=`, not three `=` tokens).",
              "Keyword vs Identifier: A keyword like `while` matches the regular expression for identifiers `[a-zA-Z][a-zA-Z0-9]*`. The lexer disambiguates by testing against a reserved keyword hash table or placing keyword patterns first in rule order.",
              "Thompson's Construction: Creates an NFA with at most $2|r|$ states and at most $4|r|$ transitions for a regular expression of length $|r|$.",
              "DFA Subset Construction: Converts NFA with $n$ states to DFA with at most $2^n$ states (though practical programming language token DFAs have linear state counts).",
              "Hopcroft's DFA Minimization: Partitions state space into equivalence groups, separating accepting states from non-accepting states in $O(k \cdot n \log n)$ time.",
            ],
            examPitfalls: [
              "Floating point regular expressions require care: `[0-9]+(\\.[0-9]+)?` requires digits on both sides of decimal point. If empty decimal is permitted, parentheses and question marks must be structured to avoid matching a lone dot.",
              "Maximal munch can cause lexical errors on valid programs: e.g., in early C++, `vector<vector<int>>` was scanned as `>>` (right-shift operator) instead of two nested template brackets.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Converting Patterns to Deterministic Finite Automata",
              body: [
                "Every token pattern in a programming language (identifiers, integers, floating-point numbers, operators, string literals) is specified formally using a **Regular Expression**.",
                "To implement the scanner, these expressions are compiled into finite state automata. The classic tool pipeline (such as `lex` or `flex`) operates as follows:",
                "1. **Thompson's Construction**: Transforms each regular expression $r_i$ into an NFA $N_i$ with $\\epsilon$-transitions. A single global start state with $\\epsilon$-transitions to each $N_i$ is created.",
                "2. **Subset Construction**: Converts the composite NFA into a single Deterministic Finite Automaton (DFA) where each DFA state represents a set of NFA states.",
                "3. **DFA State Minimization**: Applies Hopcroft's partition-refinement algorithm to merge indistinguishable states, producing the smallest possible transition table.",
                "**Disambiguation Rules:** Because multiple token patterns can match the same prefix of characters, the scanner enforces two strict disambiguation axioms:",
                "- **Rule 1 (Longest Match / Maximal Munch)**: The scanner continues looking ahead as long as the DFA remains in an accepting state or can reach one. It selects the token corresponding to the longest possible character sequence.",
                "- **Rule 2 (Rule Priority)**: If the longest match matches multiple patterns (for example, the lexeme `if` matches both the keyword `IF` and the identifier `ID`), the pattern listed first in the specification takes precedence.",
              ],
              callout: {
                kind: "exam-tip",
                title: "DFA Dead State vs Acceptance",
                message: "When the DFA enters a dead state (no valid outgoing transitions), the scanner rolls back the `forward` pointer to the most recently visited accepting state, emits that token, and resets the DFA start state for the next token.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Minimal DFA States for Token Recognition",
              weightage: "2 Marks (GATE CS)",
              trap: "Do not forget the trap/dead state when counting total states of a complete DFA over an alphabet Sigma.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "A lexical analyzer must recognize floating-point numeric constants over alphabet $\\Sigma = \\{d, .\\}$ where $d \\in \\{0, 1, \\dots, 9\\}$.",
                "A valid constant must contain at least one digit, an optional decimal point '.', and if a decimal point is present, it must be followed by at least one digit.",
                "Formal regular expression: $L = d^+ (\\. d^+)?$.",
                "Determine the minimum number of states in a complete DFA that accepts $L$ over $\\Sigma = \\{d, .\\}$.",
                "Step 1: Construct states based on prefix history:",
                "  - State $q_0$ (Start): Initial state (no characters read yet).",
                "    - On input $d$: Transition to state $q_1$ (integer digits accumulated).",
                "    - On input '.': Transition to dead state $q_{trap}$ (cannot start with a dot according to $d^+$).",
                "  - State $q_1$ (Accepting): Has read one or more digits.",
                "    - On input $d$: Self-loop on $q_1$ (more integer digits).",
                "    - On input '.': Transition to state $q_2$ (decimal point seen, awaiting fraction digits).",
                "  - State $q_2$ (Non-accepting): Decimal point encountered, must see at least one digit.",
                "    - On input $d$: Transition to state $q_3$ (fraction digits read).",
                "    - On input '.': Transition to $q_{trap}$ (two dots are invalid).",
                "  - State $q_3$ (Accepting): Valid complete floating point number.",
                "    - On input $d$: Self-loop on $q_3$ (more fraction digits).",
                "    - On input '.': Transition to $q_{trap}$ (a second dot is invalid).",
                "  - State $q_{trap}$ (Dead State): Invalid input sequence.",
                "    - On input $d, .$: Self-loop on $q_{trap}$.",
                "Step 2: Verify state minimality:",
                "  - Accepting states: $\\{q_1, q_3\\}$. Notice $q_1$ transitions on '.' to non-accepting $q_2$, while $q_3$ transitions on '.' to $q_{trap}$. Since their transitions differ on input '.', $q_1$ and $q_3$ are distinguishable and cannot be merged!",
                "  - Non-accepting states: $\\{q_0, q_2, q_{trap}\\}$.",
                "    - From $q_0$, on input $d$, we reach accepting $q_1$.",
                "    - From $q_2$, on input $d$, we reach accepting $q_3$. But on input '.', $q_0$ goes to $q_{trap}$ and $q_2$ goes to $q_{trap}$. Are $q_0$ and $q_2$ equivalent? No, because $q_0$ is the start state and can transition to $q_1$ which accepts, whereas reaching $q_2$ requires having already consumed a dot.",
                "Total states in minimal complete DFA = 5 states ($q_0, q_1, q_2, q_3, q_{trap}$).",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Engineering a Compiler (2nd Edition)",
                  authors: "Keith D. Cooper, Linda Torczon",
                  year: "2011",
                  publisher: "Morgan Kaufmann",
                  relevance: "Chapter 2: Scanners, Maximal Munch algorithm, and Regular Expression engines.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: TOP-DOWN SYNTAX ANALYSIS & LL(1) PARSING
    // =========================================================================
    {
      id: "cd-module-2-top-down-parsing",
      title: "Module 2: Top-Down Syntax Analysis & LL(1) Parsing",
      slug: "top-down-parsing",
      description:
        "Context-free grammars, leftmost derivations, recursive descent, left recursion elimination, left factoring, FIRST and FOLLOW set algorithms, and LL(1) predictive parsing tables.",
      order: 2,
      lessons: [
        {
          id: "first-follow-and-ll1-parsing",
          title: "FIRST & FOLLOW Computation, Left Recursion & Factoring",
          slug: "first-follow-and-ll1-parsing",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Recursive set rules, eliminating immediate and indirect left recursion, and left factoring transformations.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Top-down parsers construct derivations from the root down. They require grammars without left recursion or common prefixes. FIRST(alpha) is the set of terminals starting alpha; FOLLOW(A) is the set of terminals immediately trailing non-terminal A.",
            keyFormulasAndRules: [
              "Immediate Left Recursion Elimination: Production $A \\to A\\alpha_1 \\mid A\\alpha_2 \\mid \\dots \\mid \\beta_1 \\mid \\beta_2$ (where no $\\beta_i$ starts with $A$) transforms to: $A \\to \\beta_1 A' \\mid \\beta_2 A'$, and $A' \\to \\alpha_1 A' \\mid \\alpha_2 A' \\mid \\epsilon$.",
              "General (Indirect) Left Recursion: Order non-terminals $A_1, A_2, \\dots, A_n$. For $i = 1$ to $n$, for $j = 1$ to $i-1$, replace $A_i \\to A_j \\gamma$ with productions substituting $A_j$'s expansions, then eliminate immediate left recursion on $A_i$.",
              "Left Factoring: $A \\to \\alpha\\beta_1 \\mid \\alpha\\beta_2$ transforms to $A \\to \\alpha A'$ and $A' \\to \\beta_1 \\mid \\beta_2$.",
              "FIRST Set Rules: (1) If $X$ is terminal, $\\text{FIRST}(X) = \\{X\\}$. (2) If $X \\to \\epsilon$, $\\epsilon \\in \\text{FIRST}(X)$. (3) For $X \\to Y_1 Y_2 \\dots Y_k$, add $(\\text{FIRST}(Y_1) - \\{\\epsilon\\})$ to $\\text{FIRST}(X)$. If $Y_1 \\Rightarrow^* \\epsilon$, add $(\\text{FIRST}(Y_2) - \\{\\epsilon\\})$, continuing until some $Y_i$ is not nullable. If all $Y_1 \\dots Y_k \\Rightarrow^* \\epsilon$, add $\\epsilon$ to $\\text{FIRST}(X)$.",
              "FOLLOW Set Rules: (1) Add $\\$$ to $\\text{FOLLOW}(S)$ where $S$ is the start symbol. (2) For $A \\to \\alpha B \\beta$, add $(\\text{FIRST}(\\beta) - \\{\\epsilon\\})$ to $\\text{FOLLOW}(B)$. (3) If $A \\to \\alpha B$ or $A \\to \\alpha B \\beta$ where $\\beta \\Rightarrow^* \\epsilon$, add $\\text{FOLLOW}(A)$ to $\\text{FOLLOW}(B)$.",
            ],
            examPitfalls: [
              "Epsilon ($\\epsilon$) can NEVER belong to any FOLLOW set under any circumstance.",
              "When computing $\\text{FOLLOW}(B)$ from $A \\to \\alpha B \\beta$, do NOT add $\\text{FOLLOW}(A)$ unless $\\beta \\Rightarrow^* \\epsilon$ (or $\\beta$ is completely absent).",
              "Left-recursive grammars can NEVER be LL(1) because the parser enters an infinite loop predicting the same non-terminal.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Grammar Mechanics of Top-Down Parsing",
              body: [
                "Top-down syntax analysis attempts to find a leftmost derivation for an input string $w$ starting from the start symbol $S$.",
                "**The Curse of Left Recursion:** A grammar is left recursive if there exists a non-terminal $A$ such that $A \\Rightarrow^+ A\\alpha$ for some string $\\alpha$. A recursive-descent parser attempting to expand $A$ will repeatedly invoke the subroutine for $A$ before consuming any input token, resulting in infinite call stack overflow.",
                "**Left Factoring:** When two productions for $A$ share a common prefix, e.g., $A \\to \\alpha\\beta_1 \\mid \\alpha\\beta_2$, a predictive parser seeing lookahead terminal in $\\text{FIRST}(\\alpha)$ cannot determine which production to select without backtracking. Left factoring defers the decision until $\\alpha$ has been consumed.",
                "**FIRST and FOLLOW Mathematical Formulations:**",
                "- $\\text{FIRST}(\\alpha) = \\{ a \\in \\Sigma \\mid \\alpha \\Rightarrow^* a\\beta \\} \\cup \\{ \\epsilon \\text{ if } \\alpha \\Rightarrow^* \\epsilon \\}$.",
                "- $\\text{FOLLOW}(A) = \\{ a \\in \\Sigma \\cup \\{\\$\\} \\mid S \\Rightarrow^* \\alpha A a \\beta \\}$.",
              ],
              callout: {
                kind: "trap",
                title: "Common FOLLOW Calculation Trap",
                message: "When non-terminal $A$ appears in multiple productions, $\\text{FOLLOW}(A)$ is the UNION of all sets contributed by each occurrence. Missing an occurrence of $A$ across the grammar is the most common cause of lost marks in GATE.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Comprehensive FIRST & FOLLOW Derivation",
              weightage: "2 Marks (GATE CS)",
              trap: "Notice that E' and T' are nullable non-terminals resulting from left-recursion elimination.",
              solutionSteps: [
                "Consider the standard arithmetic expression grammar with left recursion eliminated:",
                "  E  -> T E'",
                "  E' -> + T E' | epsilon",
                "  T  -> F T'",
                "  T' -> * F T' | epsilon",
                "  F  -> ( E ) | id",
                "Step 1: Compute FIRST Sets (bottom-up from terminals):",
                "  - FIRST(F) = {(, id}",
                "  - FIRST(T') = {*, epsilon}",
                "  - FIRST(T): T -> F T', so FIRST(T) = FIRST(F) = {(, id}",
                "  - FIRST(E') = {+, epsilon}",
                "  - FIRST(E): E -> T E', so FIRST(E) = FIRST(T) = {(, id}",
                "Step 2: Compute FOLLOW Sets:",
                "  - Start Symbol: FOLLOW(E) contains {$}. In F -> ( E ), ')' follows E. Thus, FOLLOW(E) = {$, )}.",
                "  - In E -> T E': E' is at the right end, so FOLLOW(E') = FOLLOW(E) = {$, )}.",
                "  - In E -> T E': symbol following T is E'. Thus, add (FIRST(E') - {epsilon}) = {+} to FOLLOW(T).",
                "    Since E' =>* epsilon, add FOLLOW(E) = {$, )} to FOLLOW(T).",
                "    Therefore: FOLLOW(T) = {+, $, )}.",
                "  - In T -> F T': T' is at the right end, so FOLLOW(T') = FOLLOW(T) = {+, $, )}.",
                "  - In T -> F T': symbol following F is T'. Thus, add (FIRST(T') - {epsilon}) = {*} to FOLLOW(F).",
                "    Since T' =>* epsilon, add FOLLOW(T) = {+, $, )} to FOLLOW(F).",
                "    Therefore: FOLLOW(F) = {*, +, $, )}.",
                "Final Sets:",
                "  FIRST(E) = FIRST(T) = FIRST(F) = {(, id}",
                "  FIRST(E') = {+, epsilon}, FIRST(T') = {*, epsilon}",
                "  FOLLOW(E) = FOLLOW(E') = {$, )}",
                "  FOLLOW(T) = FOLLOW(T') = {+, $, )}",
                "  FOLLOW(F) = {*, +, $, )}.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Compilers: Principles, Techniques, and Tools",
                  authors: "Aho, Lam, Sethi, Ullman",
                  year: "2006",
                  publisher: "Pearson",
                  relevance: "Chapter 4.4: Top-Down Parsing, FIRST and FOLLOW formal inductive proofs.",
                },
              ],
            },
          ],
        },
        {
          id: "ll1-predictive-parsing-tables",
          title: "LL(1) Predictive Parsing Table Construction & Conflict Analysis",
          slug: "ll1-predictive-parsing-tables",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Table construction algorithm M[A, a], LL(1) necessary and sufficient conditions, and multi-entry conflicts.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A grammar is LL(1) iff its predictive parsing table M[A, a] contains NO cell with more than one production. Ambiguous grammars, left-recursive grammars, and improperly factored grammars are NEVER LL(1).",
            keyFormulasAndRules: [
              "LL(1) Theorem: A context-free grammar G is LL(1) if and only if for every pair of distinct productions A -> alpha | beta:",
              "  1. FIRST(alpha) and FIRST(beta) are disjoint: FIRST(alpha) ∩ FIRST(beta) = ∅.",
              "  2. At most one of alpha or beta can derive epsilon.",
              "  3. If beta =>* epsilon, then FIRST(alpha) ∩ FOLLOW(A) = ∅.",
              "Table Construction Algorithm:",
              "  For each production A -> alpha in G:",
              "    1. For each terminal 'a' in FIRST(alpha), add A -> alpha to M[A, a].",
              "    2. If epsilon in FIRST(alpha), for each symbol 'b' in FOLLOW(A) (including $), add A -> alpha to M[A, b].",
              "Error Recovery in LL(1): If cell M[A, a] is blank, it indicates a syntax error. In 'panic mode', the parser skips input tokens until reaching a token in the SYNC set (typically chosen as FOLLOW(A)).",
            ],
            examPitfalls: [
              "If epsilon is in FIRST(alpha), the production A -> alpha is placed in columns corresponding to FOLLOW(A), NOT FIRST(A)!",
              "An ambiguous grammar can NEVER be LL(1) (or LR(k) for any k) because ambiguity means an input string has multiple leftmost derivations, forcing at least one parsing table cell to have multiple entries.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Predictive Non-Recursive LL(1) Parsing Engine",
              body: [
                "An **LL(1)** parser operates using a pushdown stack, an input buffer containing the token string terminated with `$`, and a two-dimensional parsing table $M[A, a]$ where rows are non-terminals and columns are terminals (including `$`).",
                "The name **LL(1)** denotes: **L**eft-to-right scan of the input, **L**eftmost derivation, with **1** token of lookahead.",
                "**Parser Execution Cycle:**",
                "Let $X$ be the symbol on top of the stack and $a$ be the current input token.",
                "1. If $X = a = \\$$: Parsing halts and succeeds with acceptance.",
                "2. If $X = a \\ne \\$$: The parser pops $X$ from the stack and advances the input pointer to the next token (match action).",
                "3. If $X$ is a terminal and $X \\ne a$: Syntax error reported.",
                "4. If $X$ is a non-terminal: The parser consults table entry $M[X, a]$.",
                "   - If $M[X, a] = \\{X \\to Y_1 Y_2 \\dots Y_k\\}$, the parser pops $X$ and pushes $Y_k, Y_{k-1}, \\dots, Y_1$ onto the stack (so $Y_1$ is on top).",
                "   - If $M[X, a]$ is empty, a syntax error is raised.",
                "   - If $M[X, a]$ contains $\\ge 2$ productions, the table construction failed because the grammar is **NOT LL(1)**.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Necessary vs Sufficient Conditions for LL(1)",
                message: "Removing left recursion and left factoring are NECESSARY steps, but they do NOT guarantee that the resulting grammar is LL(1). Disjointness of FIRST and FOLLOW must still be verified algebraically.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Proving a Grammar is NOT LL(1)",
              weightage: "2 Marks (GATE CS)",
              trap: "Even though the grammar has no left recursion and appears factored, check the intersection between FIRST and FOLLOW for nullable non-terminals.",
              solutionSteps: [
                "Consider the grammar:",
                "  S -> A a | b",
                "  A -> a | epsilon",
                "Determine if this grammar is LL(1). If not, identify the exact table cell collision.",
                "Step 1: Compute FIRST sets:",
                "  - FIRST(A) = {a, epsilon}",
                "  - FIRST(S) = (FIRST(A) - {epsilon}) U {a} U {b} = {a, b}",
                "Step 2: Compute FOLLOW sets:",
                "  - FOLLOW(S) = {$}",
                "  - In S -> A a: A is followed by terminal 'a'. Thus, FOLLOW(A) = {a}.",
                "Step 3: Test LL(1) Condition on non-terminal A:",
                "  - Productions for A are: (1) A -> a, and (2) A -> epsilon.",
                "  - Let alpha = a, beta = epsilon.",
                "  - FIRST(alpha) = {a}.",
                "  - Since beta =>* epsilon, we must check if FIRST(alpha) ∩ FOLLOW(A) = ∅.",
                "  - Here, FIRST(alpha) = {a} and FOLLOW(A) = {a}.",
                "  - FIRST(alpha) ∩ FOLLOW(A) = {a} ∩ {a} = {a} ≠ ∅!",
                "Step 4: Examine Table Cell M[A, a]:",
                "  - For production A -> a: since 'a' is in FIRST(a), place A -> a in M[A, a].",
                "  - For production A -> epsilon: since epsilon is in FIRST(epsilon), place A -> epsilon in M[A, b] for all b in FOLLOW(A). Since FOLLOW(A) = {a}, place A -> epsilon in M[A, a].",
                "  - Table entry M[A, a] contains BOTH {A -> a, A -> epsilon}.",
                "Conclusion: The grammar is NOT LL(1) due to a multi-entry conflict in cell M[A, a].",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Compilers: Principles, Techniques, and Tools",
                  authors: "Aho, Lam, Sethi, Ullman",
                  year: "2006",
                  publisher: "Pearson",
                  relevance: "Chapter 4.4.3: Construction of predictive parsing tables.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: BOTTOM-UP SYNTAX ANALYSIS & LR PARSERS
    // =========================================================================
    {
      id: "cd-module-3-bottom-up-parsing",
      title: "Module 3: Bottom-Up Syntax Analysis & LR Parsers",
      slug: "bottom-up-parsing",
      description:
        "Shift-Reduce parsing, handle pruning, augmented grammars, LR(0) canonical items, SLR(1) FOLLOW resolution, CLR(1) exact lookaheads, LALR(1) state merging proofs, and conflict taxonomy.",
      order: 3,
      lessons: [
        {
          id: "shift-reduce-and-lr0-items",
          title: "Shift-Reduce Parsing Mechanics & LR(0) Canonical Items",
          slug: "shift-reduce-and-lr0-items",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Handles, viable prefixes, closure and goto operations, and the canonical LR(0) collection.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Bottom-up parsers construct derivations in REVERSE of a Rightmost derivation. At each step, a 'Handle' on top of the stack is reduced to its LHS non-terminal.",
            keyFormulasAndRules: [
              "Handle: A substring beta in a right-sentential form alpha beta w such that replacing beta with A yields the preceding right-sentential form in the derivation (A -> beta).",
              "Viable Prefix: A prefix of a right-sentential form that does not extend past the right end of the handle.",
              "LR(0) Item: A production with a dot at some position on the RHS (e.g., A -> alpha . beta). The dot represents how much of the production has already been seen on the stack.",
              "Augmented Grammar: G' adds S' -> S so the parser halts and accepts when S' -> S . is reached.",
              "CLOSURE(I): (1) Every item in I is in CLOSURE(I). (2) If A -> alpha . B beta is in CLOSURE(I), add B -> . gamma for every production B -> gamma in G.",
              "GOTO(I, X): CLOSURE of all items A -> alpha X . beta such that A -> alpha . X beta is in I.",
            ],
            examPitfalls: [
              "A handle is NOT simply any substring matching a RHS production; it must be the exact substring whose reduction reconstructs the unique rightmost derivation.",
              "For epsilon production A -> epsilon, the only LR(0) item is A -> . (which is immediately ready for reduction).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Handle Pruning Engine",
              body: [
                "Bottom-up parsers trace the reverse of a rightmost derivation: $S = \gamma_0 \Rightarrow_{rm} \gamma_1 \Rightarrow_{rm} \dots \Rightarrow_{rm} \gamma_n = w$.",
                "Starting with the input string $w = \gamma_n$, the parser searches for the **Handle** $\beta_n$ inside $\gamma_n$, replaces it with $A_n$ (reduction) to obtain $\gamma_{n-1}$, and repeats until reaching the start symbol $S$.",
                "**The Shift-Reduce Model:** The parser maintains a stack and input buffer. It executes four fundamental actions:",
                "1. **Shift**: Read the next input token and push it onto the stack.",
                "2. **Reduce**: Pop the handle $\beta$ from the top of the stack and push the non-terminal $A$ (where $A \to \beta$).",
                "3. **Accept**: Successfully finish parsing when the stack contains only $S'$ and input is exhausted ($\$$).",
                "4. **Error**: Raise syntax error when no valid shift or reduction is possible.",
                "**DFA of Viable Prefixes:** The collection of sets of LR(0) items under the `CLOSURE` and `GOTO` operations forms the states and transitions of a DFA that accepts exactly the viable prefixes of the grammar.",
              ],
              callout: {
                kind: "mental-model",
                title: "The Dot Notation",
                message: "In item `A -> alpha . beta`, `alpha` is already on the parser stack (seen), while `beta` is expected to appear in future input (predicted). When the dot reaches the far right `A -> alpha beta .`, the entire handle is present and ready for reduction.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Computing LR(0) State Item Count",
              weightage: "2 Marks (GATE CS)",
              trap: "Remember to augment the grammar with S' -> S before generating state I0.",
              solutionSteps: [
                "Consider the grammar:",
                "  S -> C C",
                "  C -> c C | d",
                "Determine the number of states in the canonical collection of LR(0) items.",
                "Step 1: Augment the grammar: S' -> S.",
                "Step 2: Compute I0 = CLOSURE({S' -> . S}):",
                "  - Add S' -> . S",
                "  - S has dot before it: add S -> . C C",
                "  - C has dot before it: add C -> . c C and C -> . d",
                "  I0 = {S' -> . S, S -> . C C, C -> . c C, C -> . d}.",
                "Step 3: Compute transitions from I0:",
                "  - GOTO(I0, S) = CLOSURE({S' -> S .}) = I1 = {S' -> S .}",
                "  - GOTO(I0, C) = CLOSURE({S -> C . C}) = I2 = {S -> C . C, C -> . c C, C -> . d}",
                "  - GOTO(I0, c) = CLOSURE({C -> c . C}) = I3 = {C -> c . C, C -> . c C, C -> . d}",
                "  - GOTO(I0, d) = CLOSURE({C -> d .}) = I4 = {C -> d .}",
                "Step 4: Compute transitions from remaining states:",
                "  - From I2 on C: GOTO(I2, C) = CLOSURE({S -> C C .}) = I5 = {S -> C C .}",
                "  - From I2 on c: GOTO(I2, c) = I3.",
                "  - From I2 on d: GOTO(I2, d) = I4.",
                "  - From I3 on C: GOTO(I3, C) = CLOSURE({C -> c C .}) = I6 = {C -> c C .}",
                "  - From I3 on c: GOTO(I3, c) = I3.",
                "  - From I3 on d: GOTO(I3, d) = I4.",
                "  - States I1, I4, I5, I6 have only complete items (no outgoing transitions).",
                "Total States = {I0, I1, I2, I3, I4, I5, I6} = Exactly 7 states.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Compilers: Principles, Techniques, and Tools",
                  authors: "Aho, Lam, Sethi, Ullman",
                  year: "2006",
                  publisher: "Pearson",
                  relevance: "Chapter 4.5: Introduction to LR Parsing: Simple LR.",
                },
              ],
            },
          ],
        },
        {
          id: "lr-parsing-and-conflicts",
          title: "SLR(1) Parsing Tables & Conflict Resolution",
          slug: "lr-parsing-and-conflicts",
          order: 2,
          estimatedMinutes: 32,
          tagline: "FOLLOW-set guided reductions, Shift-Reduce (SR) and Reduce-Reduce (RR) conflict diagnosis.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "SLR(1) uses the exact same states as LR(0), but places REDUCE actions ONLY in columns belonging to FOLLOW(A). If an LR(0) state has conflicts, SLR(1) resolves them if the lookahead sets are disjoint.",
            keyFormulasAndRules: [
              "LR(0) Table Action Rule: If item A -> alpha . is in state I_k, put 'reduce by A -> alpha' in ALL terminal columns of row k (including $).",
              "SLR(1) Table Action Rule: If item A -> alpha . is in state I_k, put 'reduce by A -> alpha' ONLY in columns 'a' where a in FOLLOW(A).",
              "Shift Action Rule (same for LR(0) and SLR(1)): If [A -> alpha . a beta] is in I_k and GOTO(I_k, a) = I_j, put 'shift j' in cell Action[k, a].",
              "Shift-Reduce (SR) Conflict: State contains [A -> alpha . a beta] and [B -> gamma .], and 'a' is an allowed reduce lookahead (for SLR(1), a in FOLLOW(B)).",
              "Reduce-Reduce (RR) Conflict: State contains [A -> alpha .] and [B -> beta .], and FOLLOW(A) ∩ FOLLOW(B) ≠ ∅.",
            ],
            examPitfalls: [
              "LR(0) grammars CANNOT have any epsilon productions unless the non-terminal derives ONLY epsilon and never shifts.",
              "If a state contains a completed item A -> alpha . and a shift item B -> beta . a gamma, it is an LR(0) conflict. But it is ONLY an SLR(1) conflict if 'a' belongs to FOLLOW(A).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Power and Conflict Taxonomy of SLR(1)",
              body: [
                "The **Simple LR (SLR(1))** parser significantly strengthens LR(0) by using 1 token of lookahead from the context-free grammar to guard reduction actions.",
                "In an LR(0) parser, whenever an item is completed ($A \to \alpha \cdot$), the parser unconditionally reduces on *any* lookahead token. This generates false conflicts whenever a shift transition is also available.",
                "**SLR(1) Resolution Principle:** When in state $I_k$ with completed item $A \to \alpha \cdot$, reduction is logically permissible *only* if the incoming lookahead token could legitimately follow $A$ in some valid derivation. Hence, the parser writes $r_i$ into column $a$ if and only if $a \in \\text{FOLLOW}(A)$.",
                "**Conflict Taxonomy:**",
                "1. **Shift-Reduce (SR) Conflict**: The parser cannot decide whether to shift the current input token onto the stack or reduce the current stack contents using a production.",
                "2. **Reduce-Reduce (RR) Conflict**: The parser identifies two different productions whose handles are both complete on top of the stack and cannot decide which production to reduce.",
              ],
              callout: {
                kind: "exam-tip",
                title: "Grammar Class Inclusion Hierarchy",
                message: "LR(0) ⊂ SLR(1) ⊂ LALR(1) ⊂ CLR(1). If a grammar is LR(0), it is GUARANTEED to be SLR(1), LALR(1), and CLR(1).",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Identifying SLR(1) Shift-Reduce Conflict",
              weightage: "2 Marks (GATE CS)",
              trap: "Check if the shift terminal symbol appears in the FOLLOW set of the non-terminal being reduced.",
              solutionSteps: [
                "Consider the classic assignment grammar:",
                "  S -> L = R | R",
                "  L -> * R | id",
                "  R -> L",
                "Show that this grammar is NOT SLR(1) by finding the exact conflict in its canonical LR(0) items.",
                "Step 1: Compute FOLLOW sets:",
                "  - FOLLOW(S) = {$}",
                "  - In S -> L = R: symbol '=' follows L. Also S -> R and R -> L, so FOLLOW(L) contains FOLLOW(R).",
                "  - FOLLOW(R) contains FOLLOW(S) = {$} and from S -> L = R, FOLLOW(R) contains FOLLOW(S) = {$}.",
                "  - Since R -> L, FOLLOW(L) contains FOLLOW(R) = {$, =}.",
                "  - Therefore, FOLLOW(R) = {$, =} and FOLLOW(L) = {$, =}.",
                "Step 2: Generate State I0 and Transitions:",
                "  - I0 = CLOSURE({S' -> . S}) contains:",
                "    S' -> . S",
                "    S -> . L = R",
                "    S -> . R",
                "    L -> . * R",
                "    L -> . id",
                "    R -> . L",
                "Step 3: Compute GOTO(I0, L) = I2:",
                "  - Advance dot past L in items containing '. L':",
                "    S -> L . = R",
                "    R -> L .",
                "Step 4: Check for conflicts in State I2:",
                "  - Item 1: S -> L . = R (wants to SHIFT on symbol '=')",
                "  - Item 2: R -> L . (completed item, wants to REDUCE by R -> L on all symbols in FOLLOW(R))",
                "  - Does symbol '=' belong to FOLLOW(R)?",
                "  - Yes! We determined FOLLOW(R) = {$, =}.",
                "  - Therefore, on input symbol '=', State I2 has BOTH:",
                "    - Action[I2, =] = Shift",
                "    - Action[I2, =] = Reduce by R -> L",
                "Conclusion: State I2 contains a Shift-Reduce conflict on '='. The grammar is NOT SLR(1).",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Compilers: Principles, Techniques, and Tools",
                  authors: "Aho, Lam, Sethi, Ullman",
                  year: "2006",
                  publisher: "Pearson",
                  relevance: "Chapter 4.5.3: SLR Parsing Tables and conflict detection.",
                },
              ],
            },
          ],
        },
        {
          id: "clr1-lalr1-parsing-state-merging",
          title: "CLR(1) vs LALR(1) Parsing Tables & State Merging Theorems",
          slug: "clr1-lalr1-parsing-state-merging",
          order: 3,
          estimatedMinutes: 34,
          tagline: "LR(1) item pairs [A -> alpha . beta, a], canonical state splitting, and the LALR(1) core merging theorem.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "CLR(1) (Canonical LR) splits states by exact 1-token lookaheads. LALR(1) merges CLR(1) states having identical LR(0) cores. Merging NEVER creates new Shift-Reduce conflicts, but MAY create Reduce-Reduce conflicts.",
            keyFormulasAndRules: [
              "LR(1) Item Structure: [A -> alpha . beta, a] where 'a' is a terminal or $. Reduction to A is valid ONLY when the lookahead is exactly 'a'.",
              "State Counts Equality: Number of States: |LR(0)| = |SLR(1)| = |LALR(1)| <= |CLR(1)|.",
              "LALR(1) Core Definition: The core of an LR(1) state is its set of LR(0) items without the lookahead components.",
              "LALR(1) State Merging Theorem (SR Conflicts): Merging two CLR(1) states with identical cores can NEVER introduce a Shift-Reduce conflict. Proof: If a merged state had an SR conflict on 'a', one original state had [A -> alpha ., a] and the other had [B -> beta . a gamma, b]. But since both states have the identical core, the shift item [B -> beta . a gamma, ...] existed in the first state too, meaning the SR conflict already existed in CLR(1)!",
              "LALR(1) State Merging Theorem (RR Conflicts): Merging CAN combine lookaheads of two distinct reduce items [A -> alpha ., a] and [B -> beta ., b] from different states, producing an RR conflict if their combined lookahead sets intersect.",
            ],
            examPitfalls: [
              "If a grammar is LALR(1), it is GUARANTEED to be CLR(1). But if it is CLR(1), it might NOT be LALR(1) due to potential RR conflicts.",
              "LALR(1) parsing tables are vastly smaller than CLR(1) tables (typically 10x smaller for real programming languages like C or Java), which is why real parser generators (Yacc, Bison) use LALR(1).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Exact Lookahead Architecture of CLR(1) and LALR(1)",
              body: [
                "While SLR(1) uses the global $\\text{FOLLOW}(A)$ set to decide when to reduce, this lookahead is often too permissive: $\\text{FOLLOW}(A)$ includes all terminals that can follow $A$ in *any* right-sentential form, even if they cannot follow $A$ in the current parsing context.",
                "**Canonical LR (CLR(1)):** Solves this by embedding the *exact* valid lookahead directly into each item: $[A \\to \\alpha \\cdot \\beta, a]$.",
                "- For item $[A \\to \\alpha \\cdot B \\beta, a]$, the closure operation generates $[B \\to \\cdot \gamma, b]$ where $b \\in \\text{FIRST}(\\beta a)$.",
                "- Reduction is performed *strictly* on lookahead $a$. This eliminates all false conflicts present in SLR(1).",
                "**The State Explosion Problem:** For realistic programming languages, CLR(1) creates thousands of states because identical grammatical cores are duplicated for each distinct lookahead context.",
                "**LALR(1) (Look-Ahead LR):** Groups CLR(1) states that have the exact same LR(0) core items and merges them into a single state, combining their lookahead sets: $\\{ [A \\to \\alpha \\cdot, a_1], [A \\to \\alpha \\cdot, a_2] \\} \\implies [A \\to \\alpha \\cdot, a_1 / a_2]$.",
                "The resulting LALR(1) automaton has the exact same number of states as the simple LR(0) automaton, while retaining almost all of CLR(1)'s parsing power.",
              ],
              callout: {
                kind: "mental-model",
                title: "The Four Parser Hierarchy Summary",
                message: "Every LL(1) grammar is an LR(1) grammar. But not all LR(1) grammars are LL(1). The strict power ordering of bottom-up parsers is: LR(0) ⊂ SLR(1) ⊂ LALR(1) ⊂ CLR(1).",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Grammar that is CLR(1) but NOT LALR(1)",
              weightage: "2 Marks (GATE CS)",
              trap: "Watch for identical cores with distinct reduce lookaheads that collide upon state union.",
              solutionSteps: [
                "Consider the grammar G:",
                "  S -> a A d | b B d | a B e | b A e",
                "  A -> c",
                "  B -> c",
                "Show that G is CLR(1) but NOT LALR(1).",
                "Step 1: Trace CLR(1) items following shift of 'c':",
                "  - After prefix 'a': parser predicts A -> c with lookahead 'd', and B -> c with lookahead 'e'.",
                "    State I_x: {[A -> c ., d], [B -> c ., e]}.",
                "    - On lookahead 'd': reduce by A -> c.",
                "    - On lookahead 'e': reduce by B -> c.",
                "    - Since lookaheads {d} and {e} are disjoint, NO conflict in I_x!",
                "  - After prefix 'b': parser predicts B -> c with lookahead 'd', and A -> c with lookahead 'e'.",
                "    State I_y: {[B -> c ., d], [A -> c ., e]}.",
                "    - On lookahead 'd': reduce by B -> c.",
                "    - On lookahead 'e': reduce by A -> c.",
                "    - Lookaheads {d} and {e} are disjoint, NO conflict in I_y!",
                "  - Therefore, the grammar is completely conflict-free in CLR(1). G is CLR(1).",
                "Step 2: Perform LALR(1) State Merging:",
                "  - Notice States I_x and I_y have identical LR(0) cores: {A -> c ., B -> c .}.",
                "  - Merging I_x and I_y creates State I_{xy}:",
                "    I_{xy} = {[A -> c ., d / e], [B -> c ., d / e]}.",
                "  - Lookahead for reducing by A -> c is {d, e}.",
                "  - Lookahead for reducing by B -> c is {d, e}.",
                "  - On input 'd': parser cannot decide whether to reduce by A -> c or B -> c (RR conflict!).",
                "  - On input 'e': parser cannot decide whether to reduce by A -> c or B -> c (RR conflict!).",
                "Conclusion: G is CLR(1), but NOT LALR(1) due to Reduce-Reduce conflicts in the merged state.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Compilers: Principles, Techniques, and Tools",
                  authors: "Aho, Lam, Sethi, Ullman",
                  year: "2006",
                  publisher: "Pearson",
                  relevance: "Chapter 4.7: Using Ambiguous Grammars, Canonical LR, and LALR Parsing.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: SYNTAX-DIRECTED TRANSLATION & INTERMEDIATE CODE GENERATION
    // =========================================================================
    {
      id: "cd-module-4-sdt-icg",
      title: "Module 4: Syntax-Directed Translation & Intermediate Code Generation",
      slug: "sdt-and-icg",
      description:
        "Syntax-Directed Definitions (SDDs), synthesized vs inherited attributes, S-attributed and L-attributed systems, Three-Address Code, Quadruples, Triples, and Static Single Assignment (SSA).",
      order: 4,
      lessons: [
        {
          id: "sdt-and-code-optimization",
          title: "Syntax-Directed Definitions: S-Attributed vs L-Attributed Systems",
          slug: "sdt-and-code-optimization",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Inherited vs synthesized attributes, dependency graphs, bottom-up semantic stacks, and DFS traversal rules.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "S-attributed definitions use ONLY synthesized attributes and evaluate bottom-up during LR parsing. L-attributed definitions permit synthesized and inherited attributes from parent and left siblings ONLY, evaluating in a single depth-first pass.",
            keyFormulasAndRules: [
              "Synthesized Attribute: Computed from attribute values of children nodes in the parse tree (or lexical values for terminals).",
              "Inherited Attribute: Computed from attribute values of parent node and/or sibling nodes.",
              "S-Attributed SDD: Contains ONLY synthesized attributes. Can be implemented naturally by augmenting the LR parser stack with an extra value field.",
              "L-Attributed SDD: For production A -> X_1 X_2 ... X_n, an inherited attribute of X_j can depend ONLY on: (1) Inherited attributes of parent A, and/or (2) Synthesized or inherited attributes of left siblings X_1, X_2, ..., X_{j-1}.",
              "Crucial Theorem: Every S-attributed definition is automatically an L-attributed definition (since the set of inherited attributes in an S-attributed SDD is empty).",
              "Syntax-Directed Translation Scheme (SDT): A context-free grammar with embedded semantic actions { ... } enclosed in curly braces indicating exact execution order.",
            ],
            examPitfalls: [
              "In an L-attributed SDD, an inherited attribute can NEVER depend on an attribute of a RIGHT sibling or on a synthesized attribute of the parent.",
              "Actions in an S-attributed SDT are placed STRICTLY at the end of productions (e.g., A -> alpha { action }).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Semantic Attribute Evaluation Model",
              body: [
                "A **Syntax-Directed Definition (SDD)** attaches semantic attributes (such as data types, values, or code fragments) to grammar symbols, and associates semantic rules with productions.",
                "**Parse Tree Decoration:** Evaluating the semantic rules on a parse tree annotates each node with its computed attribute values, creating a decorated (or annotated) parse tree.",
                "**Dependency Graphs:** If attribute $b$ at node $N$ is computed using attribute $c$ at node $M$, a directed edge $M.c \to N.b$ is drawn in the dependency graph. Valid evaluation is possible if and only if the dependency graph contains **no directed cycles** (an acyclic graph admitting a topological sort).",
                "**S-Attributed Definitions:**",
                "- All attributes are synthesized.",
                "- Can be evaluated in a strictly bottom-up postorder traversal.",
                "- Can be evaluated *on the fly* during bottom-up shift-reduce parsing by maintaining a semantic value stack alongside the parser state stack.",
                "**L-Attributed Definitions:**",
                "- Allows synthesized attributes plus restricted inherited attributes.",
                "- Dependencies flow strictly from top-to-bottom and left-to-right (the 'L' stands for left-to-right).",
                "- Can be evaluated in a single depth-first traversal (preorder for inherited attributes, postorder for synthesized attributes).",
              ],
              callout: {
                kind: "trap",
                title: "Right Sibling Dependency Trap",
                message: "If a semantic rule computes an inherited attribute of $X_1$ using an attribute of $X_2$ in $A \\to X_1 X_2$, the SDD is NOT L-attributed. Top-down single-pass compilers cannot evaluate it without backtracking or multi-pass traversals.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Classifying SDDs and Attribute Evaluation",
              weightage: "2 Marks (GATE CS)",
              trap: "Distinguish between parent inherited attributes (valid in L-attributed) and parent synthesized attributes (invalid in L-attributed).",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "Consider the following Syntax-Directed Definition with semantic rules:",
                "  (1) S -> A B    { S.val = A.val + B.val; }",
                "  (2) A -> x      { A.val = 2 * x.lexval; }",
                "  (3) B -> y C    { B.val = C.val; C.in = B.in + 5; }",
                "  (4) C -> z      { C.val = C.in * z.lexval; }",
                "Classify whether this SDD is: (A) S-attributed, (B) L-attributed but not S-attributed, or (C) Neither.",
                "Step 1: Check if S-attributed:",
                "  - Look at rule (3): `C.in = B.in + 5`. Here, `C.in` is an attribute of symbol `C` computed from `B.in` (its parent).",
                "  - Since `C.in` is an INHERITED attribute (computed for a child node), this SDD contains inherited attributes.",
                "  - Therefore, it is NOT S-attributed.",
                "Step 2: Check if L-attributed:",
                "  - In rule (3): `B -> y C`, we have `C.in = B.in + 5`.",
                "    - `C` is a child of `B`.",
                "    - `C.in` depends on `B.in`, which is an inherited attribute of the parent `B`.",
                "    - According to L-attributed rules, an inherited attribute of child $X_j$ CAN depend on inherited attributes of parent $A$.",
                "    - Is there any dependency on right siblings? No (C has no right siblings).",
                "  - In rule (1): `S.val` depends on children `A.val` and `B.val` (valid synthesized rule).",
                "  - In rule (4): `C.val = C.in * z.lexval` (valid synthesized rule depending on own inherited attribute and terminal lexval).",
                "Conclusion: The SDD is L-attributed, but NOT S-attributed.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Compilers: Principles, Techniques, and Tools",
                  authors: "Aho, Lam, Sethi, Ullman",
                  year: "2006",
                  publisher: "Pearson",
                  relevance: "Chapter 5: Syntax-Directed Translation, S-attributed and L-attributed systems.",
                },
              ],
            },
          ],
        },
        {
          id: "intermediate-code-generation-tac-ssa",
          title: "Intermediate Representations: Three-Address Code, SSA & Forms",
          slug: "intermediate-code-generation-tac-ssa",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Three-Address Code (TAC), Quadruples vs Triples vs Indirect Triples, and Static Single Assignment (SSA) form.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Intermediate representations decouple machine-independent front-ends from machine-dependent back-ends. Three-Address Code (TAC) allows at most one operator on the RHS of each statement.",
            keyFormulasAndRules: [
              "Three-Address Code (TAC): Linear instruction sequence of form: `x = y op z`, `x = op y`, `x = y`, `goto L`, `if x relop y goto L`.",
              "Quadruples: Record structure with 4 fields: `(op, arg1, arg2, result)`. Explicit temporary variables appear in the result field.",
              "Triples: Record structure with 3 fields: `(op, arg1, arg2)`. Results of operations are referenced implicitly by instruction index `(i)`. Avoids temporary variable names but complicates instruction reordering during optimization.",
              "Indirect Triples: Uses an array of pointers to Triples. Optimization reorders the pointer array without moving the underlying triple records.",
              "Static Single Assignment (SSA) Form: Every variable is defined (assigned) exactly ONCE in the entire program text. Merging execution paths use phi-functions: `x_3 = phi(x_1, x_2)`.",
              "Array Offset Formula in TAC: For 2D row-major array $A[N_1][N_2]$ with element size $w$: $\\text{Offset} = (i \\times N_2 + j) \\times w$. Base address $A[i][j] = \\text{Base}(A) + \\text{Offset}$.",
            ],
            examPitfalls: [
              "In Triples, do NOT invent temporary variable names ($t_1, t_2$); use pointer indices $(0), (1)$ to refer to earlier results.",
              "SSA requires a phi-function at any basic block where two or more reaching definitions of the same source variable converge.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Intermediate Representation Spectrum",
              body: [
                "An **Intermediate Representation (IR)** serves as the universal pivot of a modern retargetable compiler: an $M$-language front-end targeting $N$ architectures requires $M + N$ components rather than $M \\times N$ monolithic compilers.",
                "**Three-Address Code (TAC):** Linear low-level representation where each instruction has at most one operator on the right-hand side. Complex nested expressions like `x = a + b * c` are linearized into: `t1 = b * c; t2 = a + t1; x = t2`.",
                "**Representation Formats:**",
                "1. **Quadruples**: Stores `op, arg1, arg2, result`. Example: `(*, b, c, t1)`. Facilitates easy optimization because instructions can be moved freely without breaking operand linkages.",
                "2. **Triples**: Stores `op, arg1, arg2`. Example: `(0) (*, b, c); (1) (+, a, (0))`. Saves memory but reordering instructions requires rewriting all subsequent reference indices.",
                "3. **Indirect Triples**: Maintains an array of pointers pointing to triple entries. Reordering optimizations simply permute the pointer array.",
                "**Static Single Assignment (SSA):**",
                "In SSA form, each variable is assigned exactly once, and each use refers to a unique definition. When control flow paths merge (e.g., after an `if-else` construct), a special **$\\phi$-function** (phi-node) is placed at the merge point to select the appropriate definition based on the predecessor block.",
              ],
              callout: {
                kind: "mental-model",
                title: "Why SSA Dominates Modern Compilers",
                message: "SSA converts data-flow analysis into a trivial lookup: because every variable name corresponds to exactly one static assignment, reaching definitions, constant propagation, and dead code elimination run in linear time.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Array Address Translation to TAC",
              weightage: "2 Marks (GATE CS)",
              trap: "Remember row-major index multiplier: i * NumberOfColumns + j.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "Translate the assignment statement `X = A[i][j] + B[k]` into minimal Three-Address Code instructions.",
                "Given:",
                "  - Array A has dimensions 10 x 20 (10 rows, 20 columns).",
                "  - Each element of A and B occupies 4 bytes.",
                "  - Arrays are stored in row-major order starting at index 0.",
                "Step 1: Compute offset for A[i][j]:",
                "  - Formula: Offset = (i * cols + j) * size = (i * 20 + j) * 4.",
                "  - TAC:",
                "    (1) t1 = i * 20",
                "    (2) t2 = t1 + j",
                "    (3) t3 = t2 * 4",
                "    (4) t4 = A[t3]",
                "Step 2: Compute offset for B[k]:",
                "  - Formula: Offset = k * size = k * 4.",
                "  - TAC:",
                "    (5) t5 = k * 4",
                "    (6) t6 = B[t5]",
                "Step 3: Perform addition and assignment:",
                "  - TAC:",
                "    (7) t7 = t4 + t6",
                "    (8) X = t7",
                "Result: Exactly 8 Three-Address Code instructions.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Compilers: Principles, Techniques, and Tools",
                  authors: "Aho, Lam, Sethi, Ullman",
                  year: "2006",
                  publisher: "Pearson",
                  relevance: "Chapter 6: Intermediate-Code Generation, TAC, Quadruples, and Triples.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: CODE OPTIMIZATION & RUNTIME ENVIRONMENTS
    // =========================================================================
    {
      id: "cd-module-5-optimization-runtime",
      title: "Module 5: Code Optimization & Runtime Environments",
      slug: "optimization-and-runtime",
      description:
        "Basic block partitioning algorithm, Control Flow Graphs (CFG), DAG representation of basic blocks, local optimizations, loop-invariant code motion, induction variables, and activation records.",
      order: 5,
      lessons: [
        {
          id: "basic-blocks-cfg-dag-optimizations",
          title: "Basic Blocks, Control Flow Graphs, DAGs & Loop Optimizations",
          slug: "basic-blocks-cfg-dag-optimizations",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Leader identification algorithm, CFG construction, DAG value numbering, and loop-invariant hoisting.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Basic Blocks enter at the first instruction and exit at the last without branching in between. Control Flow Graphs model program execution flow. DAGs eliminate local common subexpressions.",
            keyFormulasAndRules: [
              "Leader Selection Algorithm (3 Rules):",
              "  1. Instruction 1 (first statement) is a leader.",
              "  2. Any target instruction of a conditional or unconditional jump is a leader.",
              "  3. Any instruction immediately following a conditional or unconditional jump is a leader.",
              "Basic Block Construction: A basic block starts at a leader and includes all instructions up to (but not including) the next leader or the end of the program.",
              "DAG for Basic Blocks: Leaves represent initial variable values. Interior nodes represent operators. Identical expressions share the same interior node (Common Subexpression Elimination).",
              "Loop-Invariant Code Motion: Hoisting expressions whose operand values do not change inside the loop body outside to a preheader.",
              "Induction Variable Elimination & Strength Reduction: Replaces expensive operations (e.g., multiplication `t = i * 4` in a loop where `i` increments by 1) with inexpensive operations (`t = t + 4`).",
              "Activation Records (Stack Frames): Contains Local variables, Temporary variables, Machine status (saved registers, Program Counter), Dynamic Link (control link to caller's frame), Static Link (access link to lexical enclosing scope), and Return value.",
            ],
            examPitfalls: [
              "Do NOT forget Rule 3: The instruction immediately AFTER a goto is ALWAYS a leader, even if it is not targeted by any jump.",
              "Static link is used for accessing non-local variables in nested lexical scopes; dynamic link points to the caller's activation record for stack unwinding.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Control Flow & Optimization Engine",
              body: [
                "Machine-independent optimization operates on Intermediate Representations before physical hardware instructions are selected.",
                "**Basic Blocks:** A Basic Block is a sequence of consecutive three-address instructions in which flow of control enters exclusively at the first instruction and leaves exclusively at the last instruction without possibility of branching except at the end.",
                "**Control Flow Graphs (CFG):** Directed graph $G = (V, E)$ where vertices $V$ are basic blocks and directed edges $E$ represent potential control transfers. An edge exists from $B_1$ to $B_2$ if $B_2$ can execute immediately after $B_1$.",
                "**DAG Representation of a Basic Block:**",
                "- Nodes are labeled with operators or variable names.",
                "- Constructed by scanning instructions in order: before creating an operator node, the compiler checks if a node with the same operator and children already exists. If so, the existing node is reused (Common Subexpression Elimination).",
                "- Dead code elimination: Nodes with no outgoing edges and no associated active variables at block exit are discarded.",
                "**Loop Optimizations:**",
                "A **Natural Loop** has a single entry point (the header) which dominates all nodes in the loop, and at least one back-edge returning to the header.",
                "- **Loop-Invariant Code Motion**: Computes expressions outside the loop if all operands are defined outside or invariant.",
                "- **Strength Reduction**: Replaces multiplication with repeated addition.",
                "- **Loop Unrolling**: Replicates the loop body to decrease branch penalty cycles and instruction test overhead.",
              ],
              callout: {
                kind: "exam-tip",
                title: "Activation Record Links",
                message: "Dynamic link = Caller frame pointer (always present in standard C call stacks). Static link = Lexical parent frame pointer (used in languages with nested functions like Pascal or Python, absent in standard flat C).",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Leader Identification & CFG Partitioning",
              weightage: "2 Marks (GATE CS)",
              trap: "Every instruction immediately following a conditional or unconditional branch is a leader.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "Consider the following intermediate code snippet:",
                "  (1)  i = 1",
                "  (2)  s = 0",
                "  (3)  t1 = i * 4",
                "  (4)  t2 = A[t1]",
                "  (5)  s = s + t2",
                "  (6)  i = i + 1",
                "  (7)  if i <= 100 goto (3)",
                "  (8)  t3 = s * 2",
                "  (9)  if t3 > 500 goto (12)",
                "  (10) print \"Normal\"",
                "  (11) goto (13)",
                "  (12) print \"High\"",
                "  (13) halt",
                "Identify all leaders, partition the code into basic blocks, and determine the number of basic blocks.",
                "Step 1: Apply Leader Identification Rules:",
                "  - Rule 1 (First instruction): Instruction (1) is a leader.",
                "  - Rule 2 (Targets of jumps):",
                "    - Target of jump at (7) is (3) -> (3) is a leader.",
                "    - Target of jump at (9) is (12) -> (12) is a leader.",
                "    - Target of jump at (11) is (13) -> (13) is a leader.",
                "  - Rule 3 (Instructions immediately following jumps):",
                "    - Follows jump at (7) -> (8) is a leader.",
                "    - Follows jump at (9) -> (10) is a leader.",
                "    - Follows jump at (11) -> (12) is a leader (already identified).",
                "  Set of Leaders = {1, 3, 8, 10, 12, 13}.",
                "Step 2: Partition into Basic Blocks:",
                "  - Block B1: Instructions (1) to (2) [from leader 1 up to next leader 3]",
                "  - Block B2: Instructions (3) to (7) [from leader 3 up to next leader 8]",
                "  - Block B3: Instructions (8) to (9) [from leader 8 up to next leader 10]",
                "  - Block B4: Instructions (10) to (11) [from leader 10 up to next leader 12]",
                "  - Block B5: Instruction (12) [from leader 12 up to next leader 13]",
                "  - Block B6: Instruction (13) [from leader 13 to end]",
                "Conclusion: There are exactly 6 Basic Blocks in this program.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Compilers: Principles, Techniques, and Tools",
                  authors: "Aho, Lam, Sethi, Ullman",
                  year: "2006",
                  publisher: "Pearson",
                  relevance: "Chapter 8.4: Basic Blocks and Flow Graphs; Chapter 9: Machine-Independent Optimizations.",
                },
                {
                  title: "Advanced Compiler Design and Implementation",
                  authors: "Steven S. Muchnick",
                  year: "1997",
                  publisher: "Morgan Kaufmann",
                  relevance: "Chapter 7: Control-Flow Analysis, Natural Loops, and Dominator Trees.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
