import type { LessonMeta } from "./types";

export const DA_DATA_TRANSFORMATIONS_LESSON: LessonMeta = {
  id: "da-data-transformations-normalization-discretization-sampling-compression",
  title: "Data Transformations: Normalization, Discretization, Sampling & Compression",
  slug: "da-data-transformations-normalization-discretization-sampling-compression",
  order: 2,
  estimatedMinutes: 32,
  tagline: "Choose, calculate, and validate the transformation named in a data-preparation problem.",
  hasInteractive: false,
  hasGATE: true,
  hasPractice: true,
  syllabusScope: "GATE 2027 DA core: data transformation",
  cheatsheet: { summaryRule: "Fit transformations using training data only, preserve the target meaning, and state which information the transformation discards.", keyFormulasAndRules: ["Min-max to [a,b]: x' = a + (x - min)(b - a)/(max - min), when max > min.", "Z-score: x' = (x - μ)/σ; specify population or sample estimates and define the zero-variance case.", "Equal-width discretization divides a numeric interval into bins of equal width; equal-frequency discretization targets similar counts per bin.", "Compression ratio = original size / compressed size; lossy methods trade exact reconstruction for size."], examPitfalls: ["For a constant feature, min=max; the formula is undefined and needs an explicit policy.", "Compute scaling parameters on training data, not on the full data before a train/test split.", "Database normalization into 1NF/2NF/3NF is a different meaning from numerical feature scaling.", "Sampling with replacement and without replacement have different probabilities; state the design."], },
  sections: [
    { type: "explanation", heading: "Prerequisites and the transformation pipeline", body: ["**Prerequisites:** relational attributes and basic descriptive statistics. See [Relational Algebra and Calculus](/notes/dbms/relational-algebra-and-calculus) and [Probability and Statistics](/notes/probability-and-statistics/combinatorics-probability-axioms-and-independence).", "A data transformation maps a source representation into one that supports analysis while controlling which information is retained. First identify the task: numerical scale normalization, discretization into categories, sampling rows, or compression of a representation. Record the input domain, output domain, fitted parameters, and any information loss.", "**Normalization here means feature scaling**, such as min-max scaling or z-score standardization. It is not relational database normalization into 1NF/2NF/3NF, and it does not mean statistical normalization to a probability distribution unless the question says so. A constant feature has no min-max range; a zero standard deviation makes z-scores undefined, so the pipeline needs a declared policy.", "For train/test evaluation, estimate minima, maxima, means, standard deviations, and bin boundaries from the training split and apply those frozen values to validation/test records. Fitting on all data leaks information about held-out observations."] },
    { type: "comparison", heading: "Choose the operation by its goal", columns: ["Transformation", "What it does", "Key choice / assumption", "Information retained"], criteria: [{ feature: "Normalization / scaling", values: ["Rescales numeric values", "Target interval or mean/standard deviation; training-only fit", "Usually preserves order; distances change" ] }, { feature: "Discretization", values: ["Maps numeric values to bins/categories", "Equal-width, equal-frequency, or domain thresholds", "Exact within-bin values are lost" ] }, { feature: "Sampling", values: ["Selects rows for estimation or computation", "Replacement, sampling frame, and design", "Unselected records are omitted; bias depends on design" ] }, { feature: "Compression", values: ["Encodes data with fewer bits/bytes", "Lossless vs lossy and codec assumptions", "Lossless reconstructs exactly; lossy does not" ] }] },
    { type: "worked-example", heading: "Worked calculations across the four transformations", problemStatement: "Training values are [10, 20, 30]. Scale 20 to [0,1], discretize x=24 into equal-width bins of width 10 beginning at 0, sample 2 of 10 rows without replacement, and compute the ratio when 800 bytes compress to 200 bytes.", steps: [{ stepNumber: 1, title: "Min-max scale", description: "Using min=10 and max=30, x'=(20-10)/(30-10)=10/20=0.5." }, { stepNumber: 2, title: "Discretize", description: "Bins [0,10), [10,20), [20,30), … place 24 in [20,30). State the endpoint convention because values on a boundary can otherwise be ambiguous." }, { stepNumber: 3, title: "Sampling", description: "A simple random sample of 2 distinct rows from 10 has C(10,2)=45 possible unordered samples; each row has inclusion probability 2/10=0.2." }, { stepNumber: 4, title: "Compression", description: "Compression ratio = 800/200 = 4:1. If compression is lossless, decompression recovers all 800 original bytes." }], finalAnswer: "Scaled value 0.5; bin [20,30); 45 possible samples and 0.2 inclusion probability per row; compression ratio 4:1.", examTakeaway: "Name the method and its assumptions before applying a formula." },
    { type: "misconceptions", heading: "Traps to catch", items: [{ commonMyth: "Database normalization and feature normalization are the same procedure.", reality: "They are separate concepts that share a word.", explanation: "Relational normal forms constrain redundancy and dependencies; feature scaling changes numeric units." }, { commonMyth: "Scaling before splitting data cannot affect evaluation.", reality: "It can leak held-out distribution information.", explanation: "Fit parameters on training data, then reuse them unchanged." }, { commonMyth: "Compression always allows exact recovery.", reality: "Only lossless compression guarantees that.", explanation: "Lossy compression deliberately discards detail to reduce size." }] },
    { type: "practice", heading: "Practice: choose and calculate", questions: [{ id: "da-transform-1", prompt: "Training minimum and maximum are 5 and 25. Under min-max scaling to [0,1], what is the transformed value of 15?", type: "numerical", correctAnswer: 0.5, tolerance: 0.001, explanation: "(15-5)/(25-5)=10/20=0.5.", difficulty: "foundation" }, { id: "da-transform-2", prompt: "A constant feature has min=max=7. What is the ordinary min-max formula's denominator?", type: "single-choice", options: [{ id: "a", text: "Zero; the case needs an explicit policy", isCorrect: true, explanation: "The range is 7-7=0, so direct scaling divides by zero." }, { id: "b", text: "One", isCorrect: false, explanation: "No unit range exists for a constant feature." }], explanation: "Do not apply a formula outside its defined conditions.", difficulty: "gate-level" }, { id: "da-transform-3", prompt: "A lossless codec reduces a 1200-byte file to 300 bytes. What is the compression ratio?", type: "numerical", correctAnswer: 4, explanation: "1200/300=4, so the ratio is 4:1.", difficulty: "gate-level" }] },
    { type: "quick-revision", heading: "One-minute revision", oneMinutePanicCard: { coreRule: "Match the transformation to the goal; preserve assumptions and account for information loss and leakage.", mustRememberFormulas: ["Min-max: a+(x-min)(b-a)/(max-min)", "Z-score: (x-μ)/σ", "Compression ratio: original/compressed size", "Simple random sample inclusion probability: n/N"], criticalPitfalls: ["Zero range or zero variance", "Training/test leakage", "Wrong bin boundary convention", "With versus without replacement", "Lossy versus lossless", "Database normal forms versus feature scaling"] } },
    { type: "resources", heading: "References", sources: [{ title: "GATE 2027 DA syllabus", authorOrInstitution: "IIT Madras", url: "https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/DA_GATE2027_Syllabus.pdf", type: "gate-official", topic: "Database Management and Warehousing: normalization, discretization, sampling, and compression." }, { title: "Data Mining: Concepts and Techniques (3rd Edition)", authors: "Jiawei Han, Micheline Kamber, Jian Pei", year: "2011", publisher: "Morgan Kaufmann", topic: "Data preprocessing, data transformation, discretization, sampling, and data reduction." }] },
  ],
};