import { CourseMeta } from "./types";
import { DA_PYTHON_MODULE } from "./python-data";

export const DATA_STRUCTURES_COURSE: CourseMeta = {
  id: "data-structures",
  title: "Data Structures",
  slug: "data-structures",
  subjectSlug: "data-structures",
  shortTitle: "Data Structures",
  icon: "🌳",
  color: "bg-emerald-400",
  tagline:
    "Master multi-dimensional address translation, stack evaluation, binary tree degree theorems, AVL rotations, B/B+ trees, binary heaps, and double hashing.",
  description:
    "A foundational, mathematically rigorous study notebook covering row/column-major array address mappings, stack expression evaluation, circular queues, linked list cycle detection, binary tree structural theorems, binary search trees, self-balancing AVL trees, B/B+ tree order calculations, priority heaps, hash collision resolution dynamics, and Disjoint Set Union (DSU) for semester examinations and top-percentile GATE CS/IT & DA performance.",
  level: "Undergraduate / GATE CS & DA",
  estimatedHours: 46,
  prerequisites: [
    "C Programming fundamentals (pointers, struct memory alignment, dynamic allocation with malloc/free)",
    "Discrete Mathematics (set theory, recurrence relations, induction, graph/tree definitions)",
    "Elementary Logarithmic and Combinatorial arithmetic",
  ],
  learningOutcomes: [
    "Derive exact row-major and column-major memory addresses for multi-dimensional and triangular matrices with arbitrary bounds",
    "Convert infix expressions to prefix/postfix using the Shunting-yard algorithm and simulate recursion stack frames",
    "Prove the fundamental binary tree leaf theorem n0 = n2 + 1 and reconstruct unique trees from traversal sequences",
    "Perform single (LL, RR) and double (LR, RL) AVL balancing rotations and solve Fibonacci-type minimum node recurrences",
    "Calculate exact B-tree and B+ tree node order and capacity constraints given block, key, and pointer sizes",
    "Prove the linear-time Build-Heap property using arithmetic-geometric series and execute priority queue operations",
    "Analyze open addressing collision sequences (linear, quadratic, double hashing) and compute expected probe lengths",
    "Implement Disjoint Set Union with union by rank and path compression achieving inverse Ackermann complexity O(alpha(n))",
  ],
  gateScope: "GATE 2027 CS/IT + DA scope",
  gateBranches: ["cs", "da"],
  gateSyllabusTopics: [
    "Arrays: 1D, 2D, 3D row-major and column-major address translation, triangular and symmetric matrices",
    "Stacks: ADT, infix to postfix/prefix conversion, evaluation, recursion simulation, parenthesis balancing",
    "Queues: Linear queue, circular queue wrap-around arithmetic, Deque, queue implementation using stacks",
    "Linked Lists: Singly, doubly, circular, pointer reversal, Floyd's cycle detection algorithm",
    "Trees: Binary trees, strict/complete/full definitions, degree theorems (n0 = n2 + 1), Catalan structural counts, traversals and unique reconstruction",
    "Binary Search Trees: Search, insertion, three-case deletion, inorder successor/predecessor, height bounds",
    "Self-Balancing Trees: AVL trees, balance factor, LL/RR/LR/RL rotations, minimum nodes recurrence N(h) = N(h-1) + N(h-2) + 1",
    "Multi-Way Trees: B-Trees and B+ Trees, node order definition, fanout, leaf chaining, disk block numericals",
    "Heaps & Priority Queues: Binary min/max heap array indexing, Max-Heapify, linear-time Build-Heap, Heap Sort",
    "Hashing: Hash functions (division, multiplication), chaining, open addressing (linear, quadratic, double hashing), clustering, probe bounds",
    "Disjoint Sets: Disjoint Set Union (DSU), union by rank, path compression, inverse Ackermann complexity",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: LINEAR DATA STRUCTURES
    // =========================================================================
    {
      id: "ds-module-1-linear",
      title: "Module 1: Arrays, Stacks, Queues & Linked Lists",
      slug: "linear-data-structures",
      description:
        "Address calculation formulas for multi-dimensional arrays, stack infix-to-postfix conversion, circular queue arithmetic, and linked list pointer operations.",
      order: 1,
      lessons: [
        {
          id: "arrays-stacks-and-queues",
          title: "Multi-Dimensional Arrays, Address Translation & Stack Mechanics",
          slug: "arrays-stacks-and-queues",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Row-major vs column-major indexing, 3D tensor addresses, operator precedence stack mechanics, and recursion frames.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "In Row-Major 2D array A[L1..U1, L2..U2] with element size c: Addr(A[i, j]) = Base + c * [ (i - L1) * (U2 - L2 + 1) + (j - L2) ].",
            keyFormulasAndRules: [
              "Row-Major 2D: Addr(A[i, j]) = Base + c * [ (i - L1) * N + (j - L2) ] where N = U2 - L2 + 1.",
              "Column-Major 2D: Addr(A[i, j]) = Base + c * [ (j - L2) * M + (i - L1) ] where M = U1 - L1 + 1.",
              "3D Row-Major: Addr(A[i, j, k]) = Base + c * [ (i - L1)*D2*D3 + (j - L2)*D3 + (k - L3) ].",
              "Lower Triangular Matrix (n x n): Stored row-major, element A[i, j] (1-indexed, i >= j) is preceded by i*(i - 1)/2 + (j - 1) elements.",
              "Infix-to-Postfix: Incoming operator popped while in-stack operator has >= precedence (left-associative) or > precedence (right-associative).",
              "Minimum Stacks to implement Queue = 2 Stacks (Amortized O(1) per operation).",
            ],
            examPitfalls: [
              "Check array indexing lower bounds (0 vs 1 vs negative index bounds like -3..5).",
              "Right-associative operators (like exponentiation `^`) have HIGHER incoming precedence than in-stack precedence; identical operators do NOT pop each other.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Physical Memory Mapping of Multi-Dimensional Arrays",
              body: [
                "Computer RAM is a flat, 1-dimensional sequence of byte addresses. Multi-dimensional matrices must be mapped onto this linear physical space.",
                "**1. Row-Major Ordering (Lexicographical / C / Python):**",
                "Consecutive elements of a row are placed contiguously in memory. Moving from row `i` to row `i + 1` requires skipping an entire row of `N = U2 - L2 + 1` elements.",
                "General 2D formula: `text{Addr}(A[i, j]) = text{Base} + c * [ (i - L1) * N + (j - L2) ]`.",
                "General 3D formula for `A[L1..U1, L2..U2, L3..U3]` with dimensions `D1, D2, D3`:",
                "`text{Addr}(A[i, j, k]) = text{Base} + c * [ (i - L1) * D2 * D3 + (j - L2) * D3 + (k - L3) ]`.",
                "**2. Column-Major Ordering (Fortran / MATLAB / R):**",
                "Consecutive elements of a column are placed contiguously. Moving from column `j` to `j + 1` requires skipping `M = U1 - L1 + 1` elements.",
                "`text{Addr}(A[i, j]) = text{Base} + c * [ (j - L2) * M + (i - L1) ]`.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Stack Mechanics & Infix-to-Postfix Shunting-Yard Algorithm",
              body: [
                "A **Stack** operates on the Last-In First-Out (LIFO) principle.",
                "**Infix to Postfix Conversion (Dijkstra's Shunting-Yard Algorithm):**",
                "1. Operands are immediately appended to the output postfix string.",
                "2. When an operator `op` arrives:",
                "   - While the stack is non-empty and the top operator has greater precedence than `op` (or equal precedence if `op` is left-associative), pop the stack to the output.",
                "   - Push `op` onto the stack.",
                "3. Left parenthesis `(` has the lowest in-stack precedence but highest incoming precedence.",
                "4. When `)` arrives, pop operators to output until `(` is encountered, then discard `(`.",
                "5. At end of input, pop all remaining operators.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: 3D Array Address Calculation with Custom Bounds",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Always compute the dimension spans D1, D2, D3 as U - L + 1 before setting up the multiplication offsets.",
              solutionSteps: [
                "Problem: An array A[1..5, -2..3, 0..4] is stored in Row-Major order starting at Base Address 2000. Each element occupies 2 bytes. Compute the exact byte address of element A[3, 1, 2].",
                "Step 1: Compute dimensions of each axis:",
                "  Axis 1: L1 = 1, U1 = 5 => D1 = 5 - 1 + 1 = 5 planes.",
                "  Axis 2: L2 = -2, U2 = 3 => D2 = 3 - (-2) + 1 = 6 rows per plane.",
                "  Axis 3: L3 = 0, U3 = 4 => D3 = 4 - 0 + 1 = 5 columns per row.",
                "  Element size c = 2 bytes, Base = 2000.",
                "Step 2: Apply 3D Row-Major offset formula:",
                "  Offset in elements = (i - L1) * D2 * D3 + (j - L2) * D3 + (k - L3)",
                "Step 3: Substitute i = 3, j = 1, k = 2:",
                "  Plane offset = (3 - 1) * (6 * 5) = 2 * 30 = 60 elements.",
                "  Row offset within plane = (1 - (-2)) * 5 = 3 * 5 = 15 elements.",
                "  Column offset within row = (2 - 0) = 2 elements.",
                "  Total elements skipped = 60 + 15 + 2 = 77 elements.",
                "Step 4: Compute physical memory address:",
                "  Addr = Base + (Total elements * c)",
                "  Addr = 2000 + (77 * 2) = 2000 + 154 = 2154.",
                "Final Answer: Byte address of A[3, 1, 2] is 2154.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Fundamentals of Data Structures in C (2nd Edition)",
                  authors: "Ellis Horowitz, Sartaj Sahni, Susan Anderson-Freed",
                  year: "2008",
                  publisher: "Silicon Press",
                  relevance: "Chapter 2: Arrays and Structures, multi-dimensional address derivations.",
                },
              ],
            },
          ],
        },
        {
          id: "queues-and-linked-lists",
          title: "Queues, Circular Buffers & Linked List Pointer Mechanics",
          slug: "queues-and-linked-lists",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Circular queue boundary arithmetic, Deques, queue via two stacks, Floyd's cycle detection, and list reversals.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "In Circular Queue of capacity N: rear = (rear + 1) % N. Full condition: (rear + 1) % N == front. Empty condition: front == rear.",
            keyFormulasAndRules: [
              "Circular Queue Size: When one empty slot is reserved, max elements stored = N - 1.",
              "Current Count in Circular Queue: count = (rear - front + N) % N.",
              "Queue using Two Stacks: Enqueue pushes to Stack 1; Dequeue pops from Stack 2 (if empty, pop all from Stack 1 into Stack 2). Amortized O(1).",
              "Floyd's Cycle Detection: Slow pointer moves 1 step, Fast pointer moves 2 steps. If they meet, list has a cycle.",
              "Finding Cycle Start Node: After meeting at distance m, reset Slow to head. Advance both Slow and Fast 1 step at a time; they meet at the cycle start node.",
            ],
            examPitfalls: [
              "Linear queue suffers from false overflow: rear reaches N-1 even if front has advanced leaving empty slots at the beginning.",
              "Reversing a singly linked list in-place requires 3 pointers (prev, curr, next) and O(1) auxiliary space.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Circular Queues & Amortized Two-Stack Queue",
              body: [
                "A **Queue** enforces First-In First-Out (FIFO) access.",
                "**Circular Queue Mechanics:**",
                "To prevent false overflow where unused memory accumulates at the front of an array, the end of the array wraps around to index 0 using modulo arithmetic.",
                "- Enqueue: `rear = (rear + 1) % N; Q[rear] = item;`",
                "- Dequeue: `front = (front + 1) % N; return Q[front];`",
                "- Empty: `front == rear`.",
                "- Full: `(rear + 1) % N == front` (sacrifices 1 physical slot to disambiguate full from empty).",
                "**Queue Implemented with Two Stacks:**",
                "- Push to `S1` for `Enqueue(x)`: `O(1)`.",
                "- `Dequeue()`: If `S2` is non-empty, pop `S2`. If `S2` is empty, transfer all elements from `S1` to `S2` (inverting order) and pop `S2`.",
                "Each element is pushed to `S1` once, popped from `S1` once, pushed to `S2` once, and popped from `S2` once. Total 4 operations over its lifetime: **Amortized `O(1)` time**.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Linked Lists & Floyd's Cycle Detection Theorem",
              body: [
                "A Linked List stores elements in dynamically allocated nodes containing data and pointers.",
                "**Floyd's Tortoise and Hare Cycle Finding Theorem:**",
                "Let a singly linked list have a linear non-cyclic prefix of length `k`, followed by a cycle of length `C`.",
                "- Slow pointer `S` advances 1 node per tick.",
                "- Fast pointer `F` advances 2 nodes per tick.",
                "When `S` enters the cycle at time `k`, `F` is at position `k mod C` inside the cycle. The relative distance between `F` and `S` increases by 1 each step. Thus, `F` catches `S` in at most `C` steps.",
                "**Finding the Cycle Entry:**",
                "When they meet at distance `d` from the start of the cycle: the distance from head to cycle start is `k`. The distance from the meeting point to cycle start is also `k (mod C)`. Moving `S` to head and advancing both 1 step per tick guarantees they meet exactly at the cycle entrance!",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Circular Queue Full/Empty State Sequence",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Remember that front points to the position before the first element, while rear points directly to the last inserted element.",
              solutionSteps: [
                "Problem: A circular queue of array size N = 6 is initially empty with front = 0 and rear = 0. Perform the following sequence of operations: Enqueue(10), Enqueue(20), Enqueue(30), Dequeue(), Enqueue(40), Enqueue(50), Enqueue(60), Dequeue(). What are the final values of front, rear, and the number of stored elements?",
                "Step 1: Initial state: front = 0, rear = 0 (empty).",
                "Step 2: Trace operations:",
                "  - Enqueue(10): rear = (0 + 1) % 6 = 1. Q[1] = 10.",
                "  - Enqueue(20): rear = (1 + 1) % 6 = 2. Q[2] = 20.",
                "  - Enqueue(30): rear = (2 + 1) % 6 = 3. Q[3] = 30.",
                "  - Dequeue(): front = (0 + 1) % 6 = 1. Returns Q[1] = 10.",
                "  - Enqueue(40): rear = (3 + 1) % 6 = 4. Q[4] = 40.",
                "  - Enqueue(50): rear = (4 + 1) % 6 = 5. Q[5] = 50.",
                "  - Enqueue(60): rear = (5 + 1) % 6 = 0. Q[0] = 60.",
                "  - Dequeue(): front = (1 + 1) % 6 = 2. Returns Q[2] = 20.",
                "Step 3: Evaluate final state:",
                "  Final front = 2, final rear = 0.",
                "  Stored elements are at indices: 3 (val 30), 4 (val 40), 5 (val 50), 0 (val 60).",
                "  Count = (rear - front + N) % N = (0 - 2 + 6) % 6 = 4 elements.",
                "Final Answer: front = 2, rear = 0, Stored count = 4.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Data Structures and Algorithm Analysis in C (2nd Edition)",
                  authors: "Mark Allen Weiss",
                  year: "1996",
                  publisher: "Pearson",
                  relevance: "Chapter 3: Lists, Stacks, and Queues.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: TREE FUNDAMENTALS, TRAVERSALS & RECONSTRUCTION
    // =========================================================================
    {
      id: "ds-module-2-trees-traversals",
      title: "Module 2: Tree Fundamentals, Traversals & Binary Search Trees",
      slug: "trees-and-bst",
      description:
        "Mathematical properties of binary trees, degree formulas (n0 = n2 + 1), Catalan number structural counts, traversal reconstruction, and BST insertion/deletion mechanics.",
      order: 2,
      lessons: [
        {
          id: "binary-trees-and-traversals",
          title: "Binary Tree Axioms, Degree Theorems & Traversal Reconstruction",
          slug: "binary-trees-and-traversals",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Handshaking lemma on trees, n0 = n2 + 1 proof, Catalan structural count, and unique tree reconstruction from traversals.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "In ANY binary tree, the number of leaf nodes n0 is strictly equal to the number of degree-2 internal nodes plus one: n0 = n2 + 1.",
            keyFormulasAndRules: [
              "Leaf vs Degree-2 Formula: n0 = n2 + 1 (strictly holds for ALL binary trees regardless of balance).",
              "Total Edges: In any tree with n nodes, total edges E = n - 1.",
              "Max Nodes at Level i (root at level 0): 2^i nodes.",
              "Max Nodes in Binary Tree of height h (root at h=0): 2^{h+1} - 1.",
              "Number of Structurally Distinct Binary Trees with n unlabeled nodes: Catalan number C_n = (1 / (n + 1)) * binom(2n, n).",
              "Unique Tree Reconstruction: Requires INORDER + (PREORDER or POSTORDER). Preorder + Postorder is generally AMBIGUOUS.",
            ],
            examPitfalls: [
              "Preorder + Postorder CANNOT uniquely reconstruct a general binary tree. It uniquely reconstructs ONLY strictly full binary trees (every node has 0 or 2 children).",
              "Inorder traversal alone gives ZERO structural information without Preorder or Postorder.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Fundamental Degree Theorem: n0 = n2 + 1",
              body: [
                "Let `T` be an arbitrary binary tree with `n` nodes and `E` edges. Partition the nodes by their out-degree (number of children):",
                "- `n_0`: Nodes with 0 children (Leaves).",
                "- `n_1`: Nodes with 1 child.",
                "- `n_2`: Nodes with 2 children.",
                "Total nodes: `n = n_0 + n_1 + n_2`.",
                "**Proof of Degree Relation:**",
                "1. Every node in a tree except the root has exactly 1 incoming edge. Therefore: `E = n - 1`.",
                "2. Each degree-1 node contributes 1 outgoing edge, and each degree-2 node contributes 2 outgoing edges. Therefore: `E = n_1 + 2 * n_2`.",
                "3. Equating the two expressions for `E`:",
                "`n - 1 = n_1 + 2 * n_2`",
                "`(n_0 + n_1 + n_2) - 1 = n_1 + 2 * n_2`",
                "`n_0 - 1 = n_2 implies n_0 = n_2 + 1`.",
                "This fundamental law holds unconditionally for every binary tree.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Tree Traversals & Unique Reconstruction Theorems",
              body: [
                "There are four standard systematic traversal strategies:",
                "1. **Pre-Order (N-L-R):** Visit Node, traverse Left subtree, traverse Right subtree.",
                "2. **In-Order (L-N-R):** Traverse Left subtree, visit Node, traverse Right subtree.",
                "3. **Post-Order (L-R-N):** Traverse Left subtree, traverse Right subtree, visit Node.",
                "4. **Level-Order:** Breadth-First traversal using a FIFO queue.",
                "**Reconstruction Theorem:**",
                "- Pre-order's first element is always the root. Locate this root in the In-order traversal. All elements to the left of the root in In-order belong to the left subtree; all elements to the right belong to the right subtree. Recursively reconstruct.",
                "- Why Pre-order + Post-order fails: If a node has a single child, Pre-order `[A, B]` and Post-order `[B, A]` cannot determine whether `B` is a left child or a right child.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Node Count & Traversal Reconstruction",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Do not confuse internal nodes with degree-2 nodes. Degree-1 nodes are internal nodes that do NOT count toward n2.",
              solutionSteps: [
                "Problem: A binary tree has 14 leaf nodes and a total of 35 nodes. How many nodes have exactly 1 child? Also determine the total number of edges.",
                "Step 1: Identify given parameters:",
                "  n_0 = 14 (leaves), Total nodes n = 35.",
                "Step 2: Apply leaf vs degree-2 theorem:",
                "  n_0 = n_2 + 1",
                "  14 = n_2 + 1 => n_2 = 13 nodes.",
                "Step 3: Solve for degree-1 nodes n_1:",
                "  Total nodes n = n_0 + n_1 + n_2",
                "  35 = 14 + n_1 + 13 = 27 + n_1",
                "  n_1 = 35 - 27 = 8 nodes.",
                "Step 4: Compute total edges E:",
                "  E = n - 1 = 35 - 1 = 34 edges.",
                "  Check with outgoing edges: n_1 + 2*n_2 = 8 + 2*13 = 8 + 26 = 34 edges. Verified!",
                "Final Answer: 8 nodes have exactly 1 child, and the tree has 34 edges.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Appendix B: Trees, and Chapter 12: Binary Search Trees.",
                },
              ],
            },
          ],
        },
        {
          id: "binary-search-trees",
          title: "Binary Search Trees: Search, Insertion, Deletion & Successors",
          slug: "binary-search-trees",
          order: 2,
          estimatedMinutes: 32,
          tagline: "In-order monotonic property, three-case deletion mechanics, successor/predecessor finding, and height degeneracies.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Inorder traversal of ANY valid BST yields strictly monotonically increasing sorted order.",
            keyFormulasAndRules: [
              "BST Invariant: For any node x, all keys in left subtree are < key(x), and all keys in right subtree are > key(x).",
              "Inorder Successor of node x: If x has right subtree => minimum key in right subtree. Else => lowest ancestor of x whose left child is also an ancestor of x.",
              "Deletion Case 1 (Leaf): Simply remove node (set parent's pointer to null).",
              "Deletion Case 2 (One Child): Splice out node by connecting parent directly to child.",
              "Deletion Case 3 (Two Children): Replace node's key with its Inorder Successor (or Predecessor), then delete the successor (which has at most 1 child).",
              "Height Complexity: Best/Average case O(log n); Worst case O(n) (skewed tree on sorted input).",
            ],
            examPitfalls: [
              "Predecessor and Successor in a BST with n nodes can be found in O(h) time WITHOUT inspecting all nodes.",
              "Inserting elements in already-sorted order degrades an ordinary BST into a singly linked list with O(n) search time.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Binary Search Tree Property & Traversal Order",
              body: [
                "A Binary Search Tree (BST) organizes keys so that binary search can be performed dynamically:",
                "`forall y in text{LeftSubtree}(x): key(y) < key(x)`",
                "`forall z in text{RightSubtree}(x): key(z) > key(x)`",
                "Because of this ordering, an In-Order traversal `(Left -> Node -> Right)` visits keys in strictly ascending sorted order.",
                "**Successor and Predecessor Algorithms:**",
                "To find `Successor(x)` (the smallest key greater than `key(x)`):",
                "1. If `x.right != null`: return the minimum key in `x.right` (follow left pointers until null).",
                "2. If `x.right == null`: traverse up parent pointers. The successor is the lowest ancestor `p` of `x` such that `x` lies in `p`'s left subtree.",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Three Cases of BST Deletion",
              body: [
                "Deleting node `z` from a BST requires maintaining the search tree property:",
                "- **Case 1 (z is a leaf):** Simply disconnect `z` from its parent. `O(1)`.",
                "- **Case 2 (z has 1 child):** Bypass `z` by linking `z.parent` directly to `z.child`. `O(1)`.",
                "- **Case 3 (z has 2 children):** Find `z`'s inorder successor `y` (which lies in `z`'s right subtree and has no left child). Copy `y.key` into `z.key`, and delete `y` from the right subtree using Case 1 or Case 2.",
                "All basic operations (search, insert, delete, min, max, successor) take `O(h)` time, where `h` is the tree height.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: BST Inorder Successor & Node Deletion Sequence",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "When deleting a node with 2 children, its successor has at most ONE child (a right child), so the successor deletion never recursively triggers Case 3.",
              solutionSteps: [
                "Problem: Keys [50, 30, 70, 20, 40, 60, 80, 35, 45] are inserted into an initially empty BST. Find the Inorder Successor of node 30, and trace the tree structure after deleting node 30.",
                "Step 1: Construct BST from insertion order:",
                "  - Root: 50",
                "  - Left of 50: 30",
                "    - Left of 30: 20",
                "    - Right of 30: 40",
                "      - Left of 40: 35",
                "      - Right of 40: 45",
                "  - Right of 50: 70",
                "    - Left of 70: 60",
                "    - Right of 70: 80",
                "Step 2: Find Inorder Successor of 30:",
                "  Node 30 has a right subtree rooted at 40.",
                "  Successor is the minimum key in the right subtree of 30.",
                "  Following left pointers from 40 leads to 35.",
                "  Inorder Successor of 30 = 35.",
                "Step 3: Delete node 30 (Case 3: two children 20 and 40):",
                "  - Copy successor key 35 into node 30's position.",
                "  - Delete original node 35 from right subtree (node 35 is a leaf, so Case 1).",
                "  - Node 40's left child becomes null.",
                "Final Subtree at 35: Left child 20, Right child 40 (with right child 45). BST invariant fully preserved.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 12: Binary Search Trees.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: SELF-BALANCING TREES & MULTI-WAY INDICES
    // =========================================================================
    {
      id: "ds-module-3-balanced-trees",
      title: "Module 3: Self-Balancing Trees & Multi-Way Indices",
      slug: "balanced-and-multiway-trees",
      description:
        "AVL tree balance factor rotations (LL, RR, LR, RL), Fibonacci recurrence for minimal nodes, B-Tree and B+ Tree order, fanout, and disk block size derivations.",
      order: 3,
      lessons: [
        {
          id: "binary-trees-bst-and-avl",
          title: "AVL Trees: Height Balancing, Rotations & Minimal Node Bounds",
          slug: "binary-trees-bst-and-avl",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Balance factors, single and double rotations (LL, RR, LR, RL), Fibonacci recurrence for minimal nodes, and height bounds.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "AVL Balance Factor: BF(node) = Height(LeftSubtree) - Height(RightSubtree) in {-1, 0, +1}. Rebalance immediately at the lowest critical unbalanced node.",
            keyFormulasAndRules: [
              "LL Imbalance: Critical node BF = +2, left child BF = +1 => Single Right Rotation at critical node.",
              "RR Imbalance: Critical node BF = -2, right child BF = -1 => Single Left Rotation at critical node.",
              "LR Imbalance: Critical node BF = +2, left child BF = -1 => Left Rotation at child, then Right Rotation at critical node.",
              "RL Imbalance: Critical node BF = -2, right child BF = +1 => Right Rotation at child, then Left Rotation at critical node.",
              "Minimum Nodes in AVL Tree of height h (root at h=0): N(h) = N(h-1) + N(h-2) + 1, with N(0)=1, N(1)=2.",
              "Maximum Height of AVL tree with n nodes: h <= 1.44 * log2(n + 2) - 0.328 = O(log n).",
            ],
            examPitfalls: [
              "When an insertion causes multiple ancestors to become unbalanced, ALWAYS rotate at the LOWEST (deepest) unbalanced node. A single rotation restores balance to the entire tree.",
              "Be meticulous whether the problem defines height of a single-node tree as 0 or 1.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The AVL Invariant & The Four Rotation Types",
              body: [
                "An **AVL Tree** (Adelson-Velsky and Landis) is a self-balancing binary search tree.",
                "**Balance Factor (BF):**",
                "`text{BF}(u) = text{Height}(text{LeftSubtree}(u)) - text{Height}(text{RightSubtree}(u))`.",
                "For every node in an AVL tree, `text{BF}(u) in {-1, 0, +1}`.",
                "When an insertion causes `text{BF}` to become `+2` or `-2` at a critical node `A`:",
                "1. **LL Case (Inserted in Left of Left):** Right rotation at `A`.",
                "2. **RR Case (Inserted in Right of Right):** Left rotation at `A`.",
                "3. **LR Case (Inserted in Right of Left):** Left rotation at `A.left`, then Right rotation at `A`.",
                "4. **RL Case (Inserted in Left of Right):** Right rotation at `A.right`, then Left rotation at `A`.",
                "Every rotation takes `O(1)` time, guaranteeing `O(log n)` insertion and deletion.",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Fibonacci Recurrence for Minimum AVL Nodes",
              body: [
                "To maximize height with the minimum number of nodes, one subtree of the root must have height `h - 1` and the other must have height `h - 2`.",
                "**Recurrence for Minimum Nodes `N(h)`:**",
                "`N(h) = N(h - 1) + N(h - 2) + 1`",
                "With base cases (height of single node = 0):",
                "- `h = 0`: `N(0) = 1`",
                "- `h = 1`: `N(1) = 2`",
                "- `h = 2`: `N(2) = 2 + 1 + 1 = 4`",
                "- `h = 3`: `N(3) = 4 + 2 + 1 = 7`",
                "- `h = 4`: `N(4) = 7 + 4 + 1 = 12`",
                "- `h = 5`: `N(5) = 12 + 7 + 1 = 20`",
                "- `h = 6`: `N(6) = 20 + 12 + 1 = 33`",
                "Notice `N(h) = F_{h+3} - 1`, where `F_k` is the `k`-th Fibonacci number. Since Fibonacci numbers grow as `phi^h` (where `phi approx 1.618`), `h approx log_phi n = 1.44 log_2 n = O(log n)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Maximum Height of an AVL Tree Given Node Count",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "If n falls strictly between N(h) and N(h+1), the maximum possible height is h, NOT h+1.",
              solutionSteps: [
                "Problem: What is the maximum possible height of an AVL tree containing n = 30 nodes (where a single-node tree has height 0)?",
                "Step 1: Compute minimum node thresholds N(h):",
                "  N(0) = 1",
                "  N(1) = 2",
                "  N(2) = 4",
                "  N(3) = 7",
                "  N(4) = 12",
                "  N(5) = 20",
                "  N(6) = 33",
                "Step 2: Compare given n = 30 with thresholds:",
                "  N(5) = 20 <= 30 < N(6) = 33.",
                "Step 3: Deduce maximum height:",
                "  To achieve height 6, an AVL tree requires at least 33 nodes.",
                "  Since we only have 30 nodes (< 33), a height of 6 is impossible.",
                "  Height 5 requires at least 20 nodes, which is satisfied (30 >= 20).",
                "Final Answer: The maximum possible height is 5.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 13: Red-Black and Balanced Search Trees.",
                },
              ],
            },
          ],
        },
        {
          id: "b-trees-and-b-plus-trees",
          title: "B-Trees & B+ Trees: Multi-Way Indexing & Block Size Numericals",
          slug: "b-trees-and-b-plus-trees",
          order: 2,
          estimatedMinutes: 34,
          tagline: "B-Tree node constraints, split and merge invariants, B+ tree leaf chaining, and disk block order/fanout derivations.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "In B-Tree of order m: Root has between 2 and m children (1 to m-1 keys). Internal nodes have between ceil(m/2) and m children (ceil(m/2)-1 to m-1 keys).",
            keyFormulasAndRules: [
              "B-Tree Order m Constraints: Max keys per node = m - 1; Min keys for non-root = ceil(m/2) - 1.",
              "B+ Tree Distinctive Property: Internal nodes store keys only as routing guides; all actual record pointers and keys reside in leaf nodes, linked as a doubly linked list.",
              "Internal Node Order Equation (Block B, Key K, Block Pointer P): p * P + (p - 1) * K <= B.",
              "Leaf Node Capacity Equation (Record Pointer Pr): q * (K + Pr) + P <= B.",
            ],
            examPitfalls: [
              "In B-Trees, data record pointers are present in ALL nodes (internal and leaf). In B+ Trees, data record pointers are EXCLUSIVELY in leaf nodes.",
              "Leaf nodes in B+ Trees require 1 block pointer to link to the next sibling leaf for range scanning.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Multi-Way Balanced Trees: B-Tree Axioms",
              body: [
                "A **B-Tree of order `m`** is a balanced multi-way search tree designed for disk storage systems where seek latency dominates CPU operations:",
                "1. Every node has at most `m` children and at most `m - 1` keys.",
                "2. Every internal node (except root) has at least `lceil m/2 rceil` children and at least `lceil m/2 rceil - 1` keys.",
                "3. The root has at least 2 children (unless it is a leaf).",
                "4. All leaves appear at the exact same depth (perfect height balance).",
                "**B+ Tree Architectural Superiority:**",
                "- In a B-Tree, internal nodes hold data pointers, reducing fanout.",
                "- In a B+ Tree, internal nodes store keys and block pointers only. This maximizes fanout, resulting in extremely shallow trees (height 3 to 4 for hundreds of millions of records).",
                "- All leaves are linked sequentially, allowing range queries (`WHERE age BETWEEN 20 AND 30`) to execute via linear scan without tree re-traversals.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Disk Block Size & Order Derivation Math",
              body: [
                "In database systems, each tree node is sized to fit exactly within a single physical disk block of size `B` bytes.",
                "Let:",
                "- `B`: Disk block size (bytes)",
                "- `K`: Search key size (bytes)",
                "- `P`: Disk block pointer size (bytes)",
                "- `P_r`: Record pointer size (bytes)",
                "**1. Internal Node Order `p`:**",
                "An internal node of order `p` stores `p` block pointers and `p - 1` keys:",
                "`p * P + (p - 1) * K <= B`",
                "`p * (P + K) - K <= B implies p <= lfloor frac{B + K}{P + K} rfloor`.",
                "**2. Leaf Node Capacity `q`:**",
                "A leaf node stores `q` pairs of `(Key + Record Pointer)` plus 1 block pointer to the next leaf sibling:",
                "`q * (K + P_r) + P <= B implies q <= lfloor frac{B - P}{K + P_r} rfloor`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: B+ Tree Order & Maximum Key Derivation",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Do not forget the single sibling pointer P in the leaf node equation.",
              solutionSteps: [
                "Problem: A database file system has a disk block size of B = 512 bytes. In a B+ tree index, search keys are K = 8 bytes, block pointers are P = 4 bytes, and record pointers are Pr = 6 bytes. Calculate the maximum order p of an internal node and the maximum capacity q of a leaf node.",
                "Step 1: Formulate internal node equation:",
                "  p * P + (p - 1) * K <= B",
                "  4p + 8(p - 1) <= 512",
                "  4p + 8p - 8 <= 512",
                "  12p <= 520",
                "  p = floor(520 / 12) = 43.",
                "  Maximum order of internal node p = 43 (stores 43 block pointers and 42 keys).",
                "Step 2: Formulate leaf node equation:",
                "  q * (K + Pr) + P <= B",
                "  q * (8 + 6) + 4 <= 512",
                "  14q + 4 <= 512",
                "  14q <= 508",
                "  q = floor(508 / 14) = 36.",
                "  Maximum leaf node capacity q = 36 record entries.",
                "Final Answer: Internal order p = 43, Leaf capacity q = 36 records.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Database System Concepts (7th Edition)",
                  authors: "Abraham Silberschatz, Henry F. Korth, S. Sudarshan",
                  year: "2019",
                  publisher: "McGraw-Hill",
                  relevance: "Chapter 14: Indexing and B+ Tree structures.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: PRIORITY QUEUES & HEAP STRUCTURES
    // =========================================================================
    {
      id: "ds-module-4-heaps",
      title: "Module 4: Priority Queues & Binary Heaps",
      slug: "heaps-and-priority-queues",
      description:
        "Binary heap array invariants, Max-Heapify mechanics, linear-time Build-Heap algebraic-geometric proof, and Heap Sort.",
      order: 4,
      lessons: [
        {
          id: "heaps-and-priority-queues",
          title: "Binary Heaps: Invariants, Linear-Time Build-Heap & Heap Sort",
          slug: "heaps-and-priority-queues",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Array indexing, Max-Heapify mechanics, algebraic-geometric proof of O(n) Build-Heap, and priority queue operations.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Build-Heap from an arbitrary array runs in strictly O(n) linear time, NOT O(n log n), because sum_{h=0}^inf (h / 2^h) = 2.",
            keyFormulasAndRules: [
              "Array Indexing (1-indexed): Parent = floor(i/2), Left = 2i, Right = 2i + 1.",
              "Array Indexing (0-indexed): Parent = floor((i - 1)/2), Left = 2i + 1, Right = 2i + 2.",
              "Non-Leaf Internal Nodes: Span indices 1 to floor(n/2). Leaves span floor(n/2) + 1 to n.",
              "Max-Heap Property: A[parent(i)] >= A[i] for all i > 1.",
              "Heap Sort: Build-Heap O(n) + (n-1) Extract-Max calls O(n log n) => Theta(n log n) in-place, unstable.",
            ],
            examPitfalls: [
              "Inserting elements one-by-one into an initially empty heap takes O(n log n). Bottom-up Build-Heap takes O(n).",
              "In a Min-Heap of n elements, the maximum element must be located among the LEAVES (indices floor(n/2) + 1 to n).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Binary Heap as a Compact Array Structure",
              body: [
                "A **Binary Heap** is a complete binary tree stored as an array without explicit pointer overhead:",
                "- The tree is completely filled on all levels except possibly the lowest, which is filled from left to right.",
                "- For node at index `i` (1-indexed):",
                "  `text{Parent}(i) = lfloor i / 2 rfloor`, `text{Left}(i) = 2i`, `text{Right}(i) = 2i + 1`.",
                "**Heap Property:**",
                "- **Max-Heap:** `A[text{Parent}(i)] >= A[i]`. The maximum key is always at index 1.",
                "- **Min-Heap:** `A[text{Parent}(i)] <= A[i]`. The minimum key is always at index 1.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Proof of Linear-Time Build-Heap Complexity",
              body: [
                "To build a heap from an unordered array of `n` elements:",
                "Call `Max-Heapify` bottom-up from index `lfloor n/2 rfloor` down to 1.",
                "**Mathematical Derivation:**",
                "- An `n`-element heap has height `lfloor log_2 n rfloor`.",
                "- There are at most `lceil n / 2^{h+1} rceil` nodes at height `h`.",
                "- Running `Max-Heapify` on a node of height `h` takes `O(h)` time.",
                "Total time:",
                "`T(n) <= sum_{h=0}^{lfloor log_2 n rfloor} lceil frac{n}{2^{h+1}} rceil * O(h) <= frac{n}{2} sum_{h=0}^infty frac{h}{2^h}`",
                "The infinite arithmetic-geometric series `sum_{h=0}^infty frac{h}{2^h} = 2`.",
                "Therefore: `T(n) <= frac{n}{2} * 2 = O(n)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Maximum Element Location in Min-Heap",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "In a Min-Heap, the maximum element is never at an internal node; it is always at a leaf node.",
              solutionSteps: [
                "Problem: An array of n = 10 distinct elements forms a Min-Heap. What are the possible indices where the maximum element can reside (using 1-based indexing)?",
                "Step 1: Identify internal nodes and leaves for n = 10:",
                "  Last internal node = floor(n / 2) = floor(10 / 2) = 5.",
                "  Internal nodes are indices: {1, 2, 3, 4, 5}.",
                "  Leaf nodes are indices: {6, 7, 8, 9, 10}.",
                "Step 2: Apply Min-Heap property:",
                "  In a Min-Heap, every parent is smaller than both of its children.",
                "  If an element is located at any internal node i in {1, 2, 3, 4, 5}, at least one of its children is strictly larger than it.",
                "  Therefore, the global maximum CANNOT reside at any internal node.",
                "Step 3: Conclusion:",
                "  The maximum element must reside in one of the leaf nodes.",
                "Final Answer: The maximum element can reside at any index in {6, 7, 8, 9, 10}.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 6: Heapsort.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: HASHING, COLLISION RESOLUTION & DISJOINT SETS
    // =========================================================================
    {
      id: "ds-module-5-hashing-dsu",
      title: "Module 5: Hashing, Collision Dynamics & Disjoint Sets",
      slug: "hashing-and-dsu",
      description:
        "Open addressing (linear, quadratic, double hashing), clustering phenomena, separate chaining load factors, and Disjoint Set Union with union by rank and path compression.",
      order: 5,
      lessons: [
        {
          id: "heaps-and-hash-tables",
          title: "Hash Tables, Open Addressing & Collision Probing Dynamics",
          slug: "heaps-and-hash-tables",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Division and multiplication hash functions, linear vs quadratic probing, double hashing, and primary/secondary clustering.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Double Hashing: h(k, i) = (h1(k) + i * h2(k)) % m eliminates both primary and secondary clustering. h2(k) must be relatively prime to m.",
            keyFormulasAndRules: [
              "Linear Probing: h(k, i) = (h'(k) + i) % m. Suffers from Primary Clustering (contiguous blocks of occupied slots).",
              "Quadratic Probing: h(k, i) = (h'(k) + c1*i + c2*i^2) % m. Eliminates primary clustering; suffers from Secondary Clustering (keys with same initial hash share probe path).",
              "Double Hashing: h(k, i) = (h1(k) + i * h2(k)) % m. Independent hash function h2(k) provides distinct step size for each key.",
              "Load Factor: alpha = n / m (where n is keys stored, m is table size). In open addressing, alpha <= 1 strictly.",
            ],
            examPitfalls: [
              "In double hashing, h2(k) must NEVER return 0 (an offset of 0 causes an infinite loop at the initial slot).",
              "When deleting from an open-addressed hash table, you CANNOT set slot to empty; you must use a 'DELETED' marker (tombstone) to avoid breaking probe chains.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Hashing Paradigm & Collision Resolution",
              body: [
                "A **Hash Table** implements the dictionary ADT, mapping a universe of keys `U` into `m` table slots using a hash function `h: U -> {0, 1, ..., m - 1}`.",
                "**Collision Resolution Strategies:**",
                "1. **Chaining (Open Hashing):** Colliding elements are stored in a linked list at slot `T[h(k)]`.",
                "2. **Open Addressing (Closed Hashing):** All elements are stored directly in the table array. If a collision occurs, a sequence of alternative slots is probed until an empty slot is found:",
                "- **Linear Probing:** `h(k, i) = (h'(k) + i) bmod m`.",
                "- **Quadratic Probing:** `h(k, i) = (h'(k) + c_1 i + c_2 i^2) bmod m`.",
                "- **Double Hashing:** `h(k, i) = (h_1(k) + i * h_2(k)) bmod m`.",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Clustering Phenomena (Primary vs Secondary)",
              body: [
                "**Primary Clustering (Linear Probing):**",
                "When keys hash to nearby slots, long contiguous runs of occupied slots develop. Any key hashing to any slot in the run extends the run by one, compounding the probability of future collisions. Search times degrade rapidly as `alpha -> 1`.",
                "**Secondary Clustering (Quadratic Probing):**",
                "Two keys with the same initial hash `h'(k_1) = h'(k_2)` trace the exact same sequence of probes throughout the entire table.",
                "**Double Hashing Solution:**",
                "Because `h_2(k)` varies independently of `h_1(k)`, two keys hashing to the same initial slot will have completely different step sizes, eliminating both primary and secondary clustering.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Double Hashing Probe Sequence Execution",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Ensure h2(k) step size is added modulo m at each probe iteration i.",
              solutionSteps: [
                "Problem: Keys are inserted into a hash table of size m = 11 using Double Hashing with hash functions h1(k) = k % 11 and h2(k) = 1 + (k % 7). If slot h1(k) is occupied, find the sequence of probes for key k = 37.",
                "Step 1: Compute primary hash h1(37):",
                "  h1(37) = 37 % 11 = 4.",
                "Step 2: Compute step size h2(37):",
                "  h2(37) = 1 + (37 % 7) = 1 + 2 = 3.",
                "Step 3: Generate probe indices h(37, i) = (h1(37) + i * h2(37)) % 11 for i = 0, 1, 2, 3:",
                "  - i = 0: h(37, 0) = 4 % 11 = 4 (Initial slot).",
                "  - i = 1: h(37, 1) = (4 + 1 * 3) % 11 = 7.",
                "  - i = 2: h(37, 2) = (4 + 2 * 3) % 11 = 10.",
                "  - i = 3: h(37, 3) = (4 + 3 * 3) % 11 = 13 % 11 = 2.",
                "Final Probe Sequence: Indices 4 -> 7 -> 10 -> 2.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 11: Hash Tables.",
                },
              ],
            },
          ],
        },
        {
          id: "chaining-universal-hashing-and-load-factors",
          title: "Chaining, Universal Hashing & Search Complexity Under Load",
          slug: "chaining-universal-hashing-and-load-factors",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Separate chaining, load factor alpha, expected probe lengths, uniform hashing assumption, and universal hash families.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Under Simple Uniform Hashing: Expected time for successful search in chaining is Theta(1 + alpha/2); unsuccessful search is Theta(1 + alpha).",
            keyFormulasAndRules: [
              "Load Factor: alpha = n / m (average keys per slot). In chaining, alpha can exceed 1.",
              "Open Addressing Unsuccessful Search: Expected probes <= 1 / (1 - alpha).",
              "Open Addressing Successful Search: Expected probes <= (1 / alpha) * ln(1 / (1 - alpha)).",
              "Universal Hashing Definition: A family of hash functions H is universal if for any x != y, Pr_{h in H}[h(x) == h(y)] <= 1 / m.",
            ],
            examPitfalls: [
              "In open addressing, as load factor alpha approaches 1, the expected number of probes for an unsuccessful search approaches infinity: 1 / (1 - alpha).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Separate Chaining Complexity Analysis",
              body: [
                "Under **Simple Uniform Hashing**, any key is equally likely to hash into any of the `m` slots, independently of other keys.",
                "**1. Unsuccessful Search:**",
                "The search traverses the entire linked list at slot `h(k)`. The expected length of this list is the load factor `alpha = n / m`. Including the `O(1)` time to compute the hash function:",
                "`E[text{Cost}] = Theta(1 + alpha)`.",
                "**2. Successful Search:**",
                "The expected number of elements examined is 1 plus the expected number of elements inserted into the list after key `x`. On average, this is `alpha / 2`:",
                "`E[text{Cost}] = Theta(1 + alpha / 2)`.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Open Addressing Expected Probe Bounds",
              body: [
                "In open addressing under the assumption of uniform hashing (each probe is equally likely to be any unoccupied slot):",
                "- **Unsuccessful Search:** The probability that the first probe is occupied is `alpha`. The probability that the first two probes are occupied is `alpha^2`. Total expected probes:",
                "`E[P] = 1 + alpha + alpha^2 + alpha^3 + ... = frac{1}{1 - alpha}`.",
                "- **Successful Search:** Each key was inserted when the load factor was smaller. Integrating over the history yields:",
                "`E[P] = frac{1}{alpha} ln frac{1}{1 - alpha}`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Expected Probes Calculation at High Load Factor",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Use the natural logarithm ln, not base-10 log, in the successful search probe formula.",
              solutionSteps: [
                "Problem: An open-addressed hash table using double hashing operates at a load factor of alpha = 0.75. Calculate the expected number of probes for an unsuccessful search and a successful search.",
                "Step 1: Compute expected probes for Unsuccessful Search:",
                "  Formula: E[Unsuccessful] <= 1 / (1 - alpha)",
                "  Substitute alpha = 0.75 = 3/4:",
                "  E[Unsuccessful] <= 1 / (1 - 0.75) = 1 / 0.25 = 4 probes.",
                "Step 2: Compute expected probes for Successful Search:",
                "  Formula: E[Successful] <= (1 / alpha) * ln(1 / (1 - alpha))",
                "  Substitute alpha = 0.75:",
                "  ln(1 / (1 - 0.75)) = ln(1 / 0.25) = ln(4) approx 1.3863.",
                "  E[Successful] <= (1 / 0.75) * 1.3863 = (4 / 3) * 1.3863 = 1.848 probes.",
                "Final Answer: Unsuccessful search expects 4.0 probes; Successful search expects approximately 1.85 probes.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 11: Hash Tables, analysis of open addressing.",
                },
              ],
            },
          ],
        },
        {
          id: "disjoint-set-union",
          title: "Disjoint Set Union (DSU): Union by Rank & Path Compression",
          slug: "disjoint-set-union",
          order: 3,
          estimatedMinutes: 32,
          tagline: "Partition representation, tree rank heuristics, path compression mechanics, and the inverse Ackermann bound O(alpha(n)).",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "DSU with Union by Rank AND Path Compression achieves nearly linear amortized time O(m * alpha(n)) for m operations on n elements.",
            keyFormulasAndRules: [
              "Make-Set(x): Creates single-node tree with parent[x] = x and rank[x] = 0. Time O(1).",
              "Find-Set(x) with Path Compression: Recursively sets parent[x] = Find-Set(parent[x]), flattening tree directly to root.",
              "Union(x, y) by Rank: Attaches root of smaller rank under root of larger rank. Rank increases by 1 ONLY if both roots share equal rank.",
              "Rank Heuristic Upper Bound: A tree with root of rank r has at least 2^r nodes. Hence maximum rank is <= floor(log2 n).",
              "Inverse Ackermann Function: alpha(n) <= 4 for all universe sizes n <= 2^{65536}.",
            ],
            examPitfalls: [
              "Union by rank ALONE gives O(m log n). Path compression ALONE gives O(m log n). BOTH together achieve O(m * alpha(n)).",
              "Path compression does NOT alter the stored rank value of nodes.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Disjoint Set ADT & Representation",
              body: [
                "A **Disjoint Set Union (DSU)** data structure maintains a collection `S = {S_1, S_2, ..., S_k}` of disjoint dynamic sets.",
                "Each set is identified by a canonical representative (the root of a tree).",
                "**Core Operations:**",
                "1. `Make-Set(x)`: Initializes `{x}`.",
                "2. `Find-Set(x)`: Returns the representative of the set containing `x`.",
                "3. `Union(x, y)`: Merges the sets containing `x` and `y`.",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Two Synergistic Optimizations",
              body: [
                "**1. Union by Rank:**",
                "Each node stores a `rank` (an upper bound on its height).",
                "When unioning two sets, make the root with smaller rank point to the root with larger rank. If both ranks are equal, pick either root and increment its rank by 1.",
                "This guarantees that tree depth never exceeds `O(log n)`.",
                "**2. Path Compression:**",
                "During `Find-Set(x)`, update the parent pointer of every node visited along the path to point directly to the root.",
                "**Combined Complexity:**",
                "Combining Union by Rank with Path Compression yields an amortized time of `O(alpha(n))` per operation, where `alpha(n)` is the extremely slow-growing Inverse Ackermann function.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Rank Invariant & Union Sequence",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Rank increases if and only if both roots being unioned have identical rank.",
              solutionSteps: [
                "Problem: Elements {1, 2, 3, 4, 5, 6, 7, 8} are initialized using Make-Set (rank 0 for all). The following sequence of Union operations is performed using Union by Rank: Union(1, 2), Union(3, 4), Union(5, 6), Union(7, 8), Union(1, 3), Union(5, 7), Union(1, 5). What is the final rank of the root node?",
                "Step 1: Pairwise unions at rank 0:",
                "  - Union(1, 2): rank(1)=0, rank(2)=0. Equal! Root = 1, rank(1) = 0 + 1 = 1.",
                "  - Union(3, 4): rank(3)=0, rank(4)=0. Equal! Root = 3, rank(3) = 1.",
                "  - Union(5, 6): rank(5)=0, rank(6)=0. Equal! Root = 5, rank(5) = 1.",
                "  - Union(7, 8): rank(7)=0, rank(8)=0. Equal! Root = 7, rank(7) = 1.",
                "Step 2: Second-level unions at rank 1:",
                "  - Union(1, 3): rank(1)=1, rank(3)=1. Equal! Root = 1, rank(1) = 1 + 1 = 2.",
                "  - Union(5, 7): rank(5)=1, rank(7)=1. Equal! Root = 5, rank(5) = 1 + 1 = 2.",
                "Step 3: Final union at rank 2:",
                "  - Union(1, 5): rank(1)=2, rank(5)=2. Equal! Root = 1, rank(1) = 2 + 1 = 3.",
                "Final Answer: The final root has a rank of 3.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Algorithms (4th Edition)",
                  authors: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
                  year: "2022",
                  publisher: "MIT Press",
                  relevance: "Chapter 19: Data Structures for Disjoint Sets.",
                },
              ],
            },
          ],
        },
      ],
    },
    DA_PYTHON_MODULE,
  ],
};
