import { CourseMeta } from "./types";

export const DIGITAL_LOGIC_COURSE: CourseMeta = {
  id: "digital-logic",
  title: "Digital Logic",
  slug: "digital-logic",
  subjectSlug: "digital-logic",
  shortTitle: "Digital Logic",
  icon: "⚡",
  color: "bg-yellow-400",
  tagline:
    "Master Boolean algebra, K-Maps, multiplexer implementations, flip-flop timing, counters, and finite state machines.",
  description:
    "A comprehensive, hardware-foundational study notebook covering Boolean algebra, canonical representations, combinational circuit synthesis, number representations, arithmetic units, sequential machines, and timing constraints for university examinations and GATE CS/IT.",
  level: "Undergraduate / GATE CS",
  estimatedHours: 42,
  prerequisites: [
    "High school binary arithmetic and Boolean logic basics",
    "Basic understanding of electronic switches and truth tables",
  ],
  learningOutcomes: [
    "Minimize multi-variable Boolean expressions using algebraic identities and 4-variable / 5-variable Karnaugh Maps",
    "Implement arbitrary Boolean functions using multiplexers, decoders, and universal logic gates (NAND/NOR)",
    "Design combinational adders, subtractors, and calculate carry propagation delay in Ripple Carry vs Carry Lookahead Adders",
    "Analyze signed number representations (1's complement, 2's complement), arithmetic overflow, and subtraction circuits",
    "Synthesize combinational building blocks including priority encoders, magnitude comparators, and programmable logic (PLA, PAL, PROM)",
    "Analyze sequential circuits, flip-flop conversions, characteristic equations, and excitation tables",
    "Synthesize synchronous and asynchronous mod-N counters and resolve lock-out / unused state conditions",
    "Design Mealy and Moore Finite State Machines and compute maximum operating clock frequency from setup/hold timing constraints",
  ],
  gateScope: "GATE 2027 CS/IT scope",
  gateBranches: ["cs"],
  gateSyllabusTopics: [
    "Boolean algebra: Combinational and sequential circuits, minimization, number representations and computer arithmetic",
    "Combinational circuits: Multiplexers, decoders, encoders, priority encoders, adders, subtractors, comparators, PLAs, PALs",
    "Sequential circuits: Latches, flip-flops, synchronous and asynchronous counters, shift registers, state machines, setup and hold time",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: BOOLEAN ALGEBRA & MINIMIZATION
    // =========================================================================
    {
      id: "dl-module-1-boolean-algebra",
      title: "Module 1: Boolean Algebra, Canonical Forms & K-Map Minimization",
      slug: "boolean-algebra-minimization",
      description:
        "Boolean axioms, De Morgan's laws, consensus theorem, duality, canonical SOP/POS expressions, prime implicants, essential prime implicants, and K-map minimization.",
      order: 1,
      lessons: [
        {
          id: "boolean-algebra-canonical-forms",
          title: "Boolean Axioms, De Morgan's, Canonical SOP/POS & Dual Functions",
          slug: "boolean-algebra-canonical-forms",
          order: 1,
          estimatedMinutes: 28,
          tagline: "Hunting algebraic redundancies, Shannon's expansion theorem, duality rules, and self-dual function counts.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Boolean algebra operates on two-valued lattices ({0, 1}, +, *, '). The Duality Principle swaps (+ <-> *) and (0 <-> 1) while leaving variables unchanged. Self-dual functions equal their own dual: f = f_D.",
            keyFormulasAndRules: [
              "Consensus Theorem: AB + A'C + BC = AB + A'C (the redundant term BC contains literals present with opposite polarities in AB and A'C). Dual form: (A + B)(A' + C)(B + C) = (A + B)(A' + C).",
              "De Morgan's Laws: (A + B)' = A' * B' and (A * B)' = A' + B'. Generalized: (x_1 + x_2 + ... + x_n)' = x_1' * x_2' * ... * x_n'.",
              "Duality Theorem: If an identity f(x_1, ..., x_n, +, *, 0, 1) = g(...) holds, then f_D(x_1, ..., x_n, *, +, 1, 0) = g_D(...) holds.",
              "Self-Dual Functions: A function is self-dual iff f(x_1, ..., x_n) = (f(x_1', ..., x_n'))'. Number of Boolean functions of n variables = 2^{2^n}. Number of self-dual functions = 2^{2^{n-1}}.",
              "Canonical SOP (Sum of Products): Sum of minterms m_i where every variable appears in true or complemented form. Canonical POS (Product of Sums): Product of maxterms M_i.",
              "Minterm and Maxterm Relation: M_i = (m_i)'. Hence f = Sum m(minterms) = Prod M(missing minterms).",
            ],
            examPitfalls: [
              "Do NOT complement variable literals when finding the DUAL of a function. Complementing literals produces the COMPLEMENT of the dual, which is NOT the dual itself.",
              "A self-dual function CANNOT contain both a minterm m_i and its bitwise complement m_{2^n - 1 - i}; it must contain exactly one from each complementary pair.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Axiomatic Foundation of Boolean Algebra",
              body: [
                "Boolean algebra is an algebraic structure defined over a set $B = \\{0, 1\\}$ equipped with two binary operations: logical addition ($+$ or OR), logical multiplication ($*$ or AND), and a unary operation: complementation ($'$ or NOT).",
                "**Fundamental Theorems:**",
                "1. **Idempotence**: $A + A = A$ and $A \\cdot A = A$.",
                "2. **Involution**: $(A')' = A$.",
                "3. **Absorption**: $A + AB = A$ and $A(A + B) = A$.",
                "4. **Consensus Theorem**: $AB + A'C + BC = AB + A'C$. To apply consensus: (a) Three terms, each with 2 variables; (b) One variable appears complemented in one term and uncomplemented in another ($A$ and $A'$); (c) The third term consists of the remaining variables ($BC$), which is redundant and can be deleted.",
                "**Shannon's Expansion Theorem:** Any Boolean function $f(x_1, x_2, \\dots, x_n)$ can be expanded about variable $x_1$ as: $f(x_1, x_2, \\dots, x_n) = x_1 \\cdot f(1, x_2, \\dots, x_n) + x_1' \\cdot f(0, x_2, \\dots, x_n)$. This theorem forms the mathematical bedrock for multiplexer-based synthesis.",
                "**Self-Dual Functions:** In a truth table of $n$ variables with $2^n$ rows, minterm $m_k$ and minterm $m_{2^n - 1 - k}$ are bitwise complements. For $f$ to equal its dual $f_D$, the output for row $k$ must be the complement of row $2^n - 1 - k$. Thus, there are $2^{n-1}$ complementary pairs, and choosing the value for one half fixes the other. Number of self-dual functions = $2^{2^{n-1}}$.",
              ],
              callout: {
                kind: "exam-tip",
                title: "Neutral Functions vs Self-Dual",
                message: "A neutral function has an equal number of 1s and 0s in its truth table. All self-dual functions are neutral, but NOT all neutral functions are self-dual!",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Minimization via Consensus & Duality",
              weightage: "2 Marks (GATE CS)",
              trap: "Watch for hidden consensus terms disguised by distributing or grouping with a third variable.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "Simplify the following Boolean function into minimal sum-of-products (SOP) form:",
                "  f(A, B, C, D) = A'B'C' + A'C'D + B'CD + A'BD + A'C'D'",
                "Step 1: Combine terms using basic absorption / idempotence:",
                "  Look at terms: A'C'D + A'C'D'",
                "  A'C'D + A'C'D' = A'C'(D + D') = A'C' * 1 = A'C'.",
                "  Now expression is: f = A'B'C' + A'C' + B'CD + A'BD.",
                "Step 2: Apply absorption between A'B'C' and A'C':",
                "  A'C' + A'B'C' = A'C'(1 + B') = A'C'.",
                "  Now expression is: f = A'C' + B'CD + A'BD.",
                "Step 3: Check for Consensus Theorem:",
                "  Let Term 1 = A'C', Term 2 = B'CD.",
                "  Variable C appears uncomplemented in Term 2 (C) and complemented in Term 1 (C').",
                "  The consensus between A'C' and B'CD is: A' * (B'D) = A'B'D.",
                "  Does A'B'D help? Let's check Term 3: A'BD.",
                "  Combine A'BD with A'C' and B'CD:",
                "  Notice between A'BD and B'CD: variable B appears as B and B'.",
                "  Consensus of A'BD and B'CD is: (A'D) * (CD) = A'CD.",
                "  Is A'CD present? Notice A'C' + A'CD = A'(C' + CD) = A'(C' + D) = A'C' + A'D.",
                "  Alternatively, factor A' from first and third terms:",
                "  A'C' + A'BD = A'(C' + BD).",
                "  Can we simplify B'CD? Notice B'CD + A'BD: (B'C + A'B)D.",
                "  In fact, K-map plotting confirms: minterms covered are A'C' (all D), B'CD (when A=0 or A=1), and A'BD.",
                "  Minimal SOP: A'C' + A'D + B'CD = A'C' + D(A' + B'C) = A'C' + A'D + B'CD.",
                "  Since A'D + B'CD = (A' + B'C)D = (A' + B')(A' + C)D, minimal SOP is: f = A'C' + A'BD + B'CD.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Digital Design: With an Introduction to the Verilog HDL (5th Edition)",
                  authors: "M. Morris Mano, Michael D. Ciletti",
                  year: "2012",
                  publisher: "Pearson",
                  relevance: "Chapter 2: Boolean Algebra and Logic Gates.",
                },
              ],
            },
          ],
        },
        {
          id: "k-maps-and-minimization",
          title: "Karnaugh Maps, Prime Implicants & Don't Cares",
          slug: "k-maps-and-minimization",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Gray code adjacency, essential prime implicants, minimal SOP/POS, and 5-variable K-map partitions.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A Prime Implicant (PI) cannot be merged into any larger group. An Essential Prime Implicant (EPI) covers at least one minterm not covered by any other PI. All EPIs MUST be in the minimal SOP.",
            keyFormulasAndRules: [
              "Gray Code Adjacency: K-map row/column sequences: 00, 01, 11, 10. Only 1 bit changes between adjacent cells and wrap-around boundaries.",
              "Group Size Rule: Groups must be powers of 2 (1, 2, 4, 8, 16...). A group of size 2^k eliminates k variables from the product term.",
              "Don't-Care (X) Strategy: Include 'X' in groups ONLY if it enlarges a group of 1s (eliminating more variables). NEVER create a group containing only 'X's.",
              "Minimal SOP Procedure: 1. Identify all PIs. 2. Identify all EPIs. 3. Select all EPIs. 4. Cover remaining 1s with minimal number of non-essential PIs.",
              "Minimal POS Procedure: Group 0s on the K-map to obtain f', then apply De Morgan's theorem (or directly group maxterms).",
            ],
            examPitfalls: [
              "Corner groups wrap around in 4-variable K-maps: minterms (0, 2, 8, 10) form a group of 4 giving B'D'. Missing corner groups is the most frequent K-map error.",
              "Minimal SOP is NOT always unique; a function can have multiple distinct minimal SOP representations with identical literal and term counts.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Karnaugh Map Topology & Implicant Hierarchy",
              body: [
                "A Karnaugh Map (K-map) provides a systematic visual method for Boolean minimization up to 4 or 5 variables without algebraic trial-and-error.",
                "**Topological Wrap-Around:** A 4-variable K-map represents a torus: the top edge is adjacent to the bottom edge, and the left edge is adjacent to the right edge. The four corner cells `m_0 (0000)`, `m_2 (0010)`, `m_8 (1000)`, and `m_{10} (1010)` are all mutually adjacent and form a single group of 4.",
                "**Terminology Hierarchy:**",
                "1. **Implicant**: Any product term that implies the function (any single '1' or group of '1's).",
                "2. **Prime Implicant (PI)**: An implicant obtained by combining the maximum possible number of adjacent squares. A PI cannot be subsumed by any larger group.",
                "3. **Essential Prime Implicant (EPI)**: A PI that covers at least one minterm that is not covered by any other PI.",
                "4. **Redundant Prime Implicant**: A PI whose minterms are completely covered by the set of chosen EPIs.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Finding EPIs Rapidly",
                message: "Look for any minterm '1' that has only ONE valid grouping opportunity. The prime implicant covering that unique 1 is immediately an Essential Prime Implicant.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Counting PIs and EPIs with Don't Cares",
              weightage: "2 Marks (GATE CS)",
              trap: "Don't cares (d) can help form PIs, but an EPI must cover an original minterm (1), not merely a don't-care condition.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "Find the number of Prime Implicants (PI) and Essential Prime Implicants (EPI) for:",
                "  f(A, B, C, D) = Sigma m(0, 2, 5, 7, 8, 10, 15) + d(3, 13)",
                "Step 1: Plot on 4x4 K-map:",
                "  Row 00 (A'B'): m0=1, m2=1, d3=X",
                "  Row 01 (A'B):  m5=1, m7=1",
                "  Row 11 (AB):   d13=X, m15=1",
                "  Row 10 (AB'):  m8=1, m10=1",
                "Step 2: Identify maximal groups (PIs):",
                "  - Group 1: Corners (0, 2, 8, 10). All four are minterms '1'. Size = 4 -> B'D'. (PI 1)",
                "  - Group 2: Cells (2, 3, 0... wait: 2, 3 is size 2 A'B'C). But minterm 2 is already in Group 1.",
                "  - Group 3: Cells (5, 7, 13, 15). Notice m5=1, m7=1, d13=X, m15=1. Group of size 4 in column 01 and 11 -> BD. (PI 2)",
                "  - Group 4: Row A'B minterms m5, m7 with d3: (3, 7) or (5, 7)? (5, 7, 13, 15) covers 5 and 7 already.",
                "  - Can m0 combine with m8? Covered by Group 1.",
                "  - Can d3 combine with m2? Group of 2: (2, 3) -> A'B'C. (PI 3)",
                "  - Can d3 combine with m7? Group of 2: (3, 7) -> A'CD. (PI 4)",
                "  - Total PIs = {B'D', BD, A'B'C, A'CD}.",
                "Step 3: Test Essentiality of PIs:",
                "  - Minterm 0: covered ONLY by B'D' -> B'D' is an EPI.",
                "  - Minterm 5: covered ONLY by BD -> BD is an EPI.",
                "  - Minterm 8, 10: covered ONLY by B'D'.",
                "  - Minterm 15: covered ONLY by BD.",
                "  - Notice that all minterms {0, 2, 5, 7, 8, 10, 15} are FULLY covered by the two EPIs: B'D' and BD!",
                "  - B'D' covers {0, 2, 8, 10}. BD covers {5, 7, 15} (and d13).",
                "  - Neither A'B'C nor A'CD covers any uncovered minterm.",
                "Total PIs = 4, Total EPIs = 2 (B'D' and BD).",
                "Minimal SOP expression = B'D' + BD.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Digital Design: With an Introduction to the Verilog HDL",
                  authors: "M. Morris Mano, Michael D. Ciletti",
                  year: "2012",
                  publisher: "Pearson",
                  relevance: "Chapter 3: Gate-Level Minimization, Map Method, and Don't-Care Conditions.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: NUMBER REPRESENTATION & ARITHMETIC CIRCUITS
    // =========================================================================
    {
      id: "dl-module-2-arithmetic-circuits",
      title: "Module 2: Number Representation & Computer Arithmetic Circuits",
      slug: "number-representation-arithmetic",
      description:
        "Signed magnitude, 1's and 2's complement arithmetic, range formulas, overflow conditions, half adders, full adders, ripple carry adders, and carry lookahead adders.",
      order: 2,
      lessons: [
        {
          id: "number-representations-arithmetic",
          title: "Signed Number Representations, 2's Complement & Overflow Arithmetic",
          slug: "number-representations-arithmetic",
          order: 1,
          estimatedMinutes: 28,
          tagline: "Range boundaries, sign extension rules, modular arithmetic, and two's complement overflow detection.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "In 2's complement arithmetic, subtraction A - B is performed as A + (2's complement of B). Overflow occurs iff two numbers of the SAME sign are added and produce a result of the OPPOSITE sign: V = C_in XOR C_out into/out of the MSB.",
            keyFormulasAndRules: [
              "N-Bit Representation Ranges:",
              "  Unsigned: [0, 2^n - 1]",
              "  Signed Magnitude: [-(2^{n-1} - 1), +(2^{n-1} - 1)] (two zeros: +0 and -0)",
              "  1's Complement: [-(2^{n-1} - 1), +(2^{n-1} - 1)] (two zeros: +0 and -0)",
              "  2's Complement: [-2^{n-1}, +(2^{n-1} - 1)] (unique zero, asymmetric negative range)",
              "2's Complement Negation Rule: Invert all bits and add 1, OR scan from right to left, keep all bits up to and including the first '1', and flip all remaining bits to the left.",
              "Sign Extension: To convert an n-bit 2's complement number to m bits (m > n), replicate the MSB (sign bit) into all (m - n) upper bit positions.",
              "Overflow Formula: V = A_{n-1} * B_{n-1} * S_{n-1}' + A_{n-1}' * B_{n-1}' * S_{n-1} = C_n XOR C_{n-1}.",
            ],
            examPitfalls: [
              "Adding numbers of OPPOSITE signs can NEVER cause arithmetic overflow.",
              "In 2's complement, the most negative number -2^{n-1} (e.g., 1000 for n=4, which is -8) cannot be negated in n bits because +8 exceeds the representation range.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Hardware Elegance of 2's Complement",
              body: [
                "Computer hardware overwhelmingly uses **2's complement** for signed integer arithmetic because it allows addition and subtraction to be executed by identical adder hardware without sign-checking logic.",
                "**Weight of the MSB:** In an $n$-bit 2's complement number $A = a_{n-1} a_{n-2} \\dots a_1 a_0$, the MSB has a negative weight: $\\text{Value}(A) = -a_{n-1} 2^{n-1} + \\sum_{i=0}^{n-2} a_i 2^i$.",
                "**Arithmetic Overflow:** Because finite-word registers have bounded ranges, adding two large positive numbers can produce a negative result (sign bit becomes 1), or adding two large negative numbers can produce a positive result (sign bit becomes 0).",
                "**Hardware Overflow Detection:** In an $n$-bit adder with carry-in $C_{n-1}$ into the sign bit and carry-out $C_n$ out of the sign bit, overflow occurs if and only if $V = C_n \\oplus C_{n-1} = 1$. A simple XOR gate on the final two carry lines detects overflow in a single gate delay.",
              ],
              callout: {
                kind: "mental-model",
                title: "Carry Out vs Overflow",
                message: "Carry-out ($C_{out} = 1$) indicates an unsigned overflow (result exceeds $2^n - 1$). Overflow ($V = 1$) indicates a signed overflow (result outside $[-2^{n-1}, 2^{n-1}-1]$). They are completely independent conditions!",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: 2's Complement Subtraction & Overflow",
              weightage: "2 Marks (GATE CS)",
              trap: "Remember to sign-extend both operands to the same bit width before performing addition.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "Let A = 101100 and B = 100101 be two 6-bit 2's complement numbers.",
                "Compute S = A - B in 6-bit 2's complement arithmetic and determine whether signed overflow occurs.",
                "Step 1: Determine decimal values of A and B:",
                "  - A = 101100: MSB is 1 (negative). Value = -32 + 8 + 4 = -20.",
                "  - B = 100101: MSB is 1 (negative). Value = -32 + 4 + 1 = -27.",
                "  - Expected result: A - B = (-20) - (-27) = +7.",
                "Step 2: Find 2's complement of B:",
                "  - B = 100101.",
                "  - Invert bits: 011010. Add 1: 011011 (+27).",
                "Step 3: Compute A + (-B):",
                "    1 0 1 1 0 0  (A = -20)",
                "  + 0 1 1 0 1 1  (-B = +27)",
                "  -------------",
                "  Carry bits: 1 1 1 0 0 0",
                "  Sum = (1) 0 0 0 1 1 1",
                "  - 6-bit result = 000111 (+7 in decimal).",
                "Step 4: Check Overflow:",
                "  - Carry into MSB (C5) = 1.",
                "  - Carry out of MSB (C6) = 1.",
                "  - V = C6 XOR C5 = 1 XOR 1 = 0.",
                "  - No overflow! The result +7 is within the 6-bit signed range [-32, +31].",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Computer Organization and Architecture (10th Edition)",
                  authors: "William Stallings",
                  year: "2015",
                  publisher: "Pearson",
                  relevance: "Chapter 10: Computer Arithmetic, 2's complement, and hardware overflow flags.",
                },
              ],
            },
          ],
        },
        {
          id: "adders-subtractors-cla-delay",
          title: "Adders, Subtractors, Ripple Carry vs Carry Lookahead Adders",
          slug: "adders-subtractors-cla-delay",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Gate propagation delays, Half/Full adder synthesis, CLA generate and propagate algebra, and asymptotic speedup.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Ripple Carry Adders suffer from O(n) linear delay because each stage must wait for the carry from the previous stage. Carry Lookahead Adders (CLA) compute all carries in parallel in O(1) constant delay using generate (G_i) and propagate (P_i) signals.",
            keyFormulasAndRules: [
              "Half Adder (HA): Sum = A XOR B; Carry = A * B. Requires 1 XOR + 1 AND gate.",
              "Full Adder (FA): Sum = A XOR B XOR C_in; Carry = AB + BC_in + AC_in = AB + C_in(A XOR B). Can be implemented using 2 HAs + 1 OR gate.",
              "Ripple Carry Adder (RCA) Delay: T_{RCA} = t_{FA(carry)} * n + t_{FA(sum)} = O(n).",
              "CLA Carry Generate: G_i = A_i * B_i (generates carry regardless of carry-in).",
              "CLA Carry Propagate: P_i = A_i XOR B_i (or A_i + B_i; propagates carry-in).",
              "Carry Equations: C_1 = G_0 + P_0 C_0; C_2 = G_1 + P_1 G_0 + P_1 P_0 C_0; C_3 = G_2 + P_2 G_1 + P_2 P_1 G_0 + P_2 P_1 P_0 C_0; C_4 = G_3 + P_3 G_2 + P_3 P_2 G_1 + P_3 P_2 P_1 G_0 + P_3 P_2 P_1 P_0 C_0.",
              "CLA Propagation Delay: 4-bit CLA computes all carries in exactly 2 gate delays (AND-OR levels) after P_i and G_i are available.",
            ],
            examPitfalls: [
              "In CLA, high fan-in restricts single-level lookahead to 4 bits in physical VLSI. For larger widths (16 or 64 bits), multi-level hierarchical (Block) CLAs are used.",
              "Full Subtractor: Difference = A XOR B XOR B_in; Borrow = A'B + B'(A XOR B)' ... = A'B + B_in(A XOR B)'.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Arithmetic Carry Bottleneck",
              body: [
                "In digital arithmetic, addition is the primitive operation upon which multiplication, subtraction, and address calculations are built. The critical speed limit of an adder is determined by the **carry propagation path**.",
                "**Ripple Carry Adder (RCA):** Chaining $n$ Full Adders connects $C_{out}$ of bit $i$ to $C_{in}$ of bit $i+1$. In the worst case (e.g., adding `111...1` and `000...1`), the carry must ripple through all $n$ stages sequentially. For $n=64$, this introduces 64 stages of gate delay.",
                "**Carry Lookahead Adder (CLA):** Eliminates ripple delay by expressing every carry $C_{i+1}$ directly as a function of the primary inputs $A, B$ and initial carry $C_0$ using two auxiliary terms:",
                "- **Generate ($G_i = A_i B_i$)**: A carry is generated internally at bit $i$ if both inputs are 1.",
                "- **Propagate ($P_i = A_i \\oplus B_i$)**: A carry entering bit $i$ is passed directly to bit $i+1$ if one of the inputs is 1.",
                "Since all $G_i$ and $P_i$ are generated in parallel in 1 gate delay, all carries $C_1, C_2, C_3, C_4$ are computed simultaneously in a 2-level AND-OR logic network, making carry computation independent of word length $n$.",
              ],
              callout: {
                kind: "exam-tip",
                title: "P_i Definition in GATE",
                message: "In GATE examinations, $P_i$ can be defined as either $A_i \\oplus B_i$ or $A_i + B_i$. Both give identical carry equations because when $A_i B_i = 1$, $G_i$ dominates $P_i$ anyway.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Delay Comparison RCA vs CLA",
              weightage: "2 Marks (GATE CS)",
              trap: "Distinguish between the time required to generate the final carry output vs the final sum bit.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "A 4-bit Ripple Carry Adder is constructed from full adders where each full adder has a sum delay of 12 ns and a carry delay of 8 ns.",
                "A 4-bit CLA uses gates with delays: XOR = 10 ns, AND = 4 ns, OR = 4 ns.",
                "Compute the worst-case delay to obtain all 4 sum bits and the final carry out for: (a) The RCA, and (b) The CLA.",
                "Step 1: Calculate RCA worst-case delay:",
                "  - Carry out of stage 1: 8 ns.",
                "  - Carry out of stage 2: 8 + 8 = 16 ns.",
                "  - Carry out of stage 3: 16 + 8 = 24 ns.",
                "  - Final carry out (C4): 24 + 8 = 32 ns.",
                "  - Final sum bit (S3): requires C3 (24 ns) + sum delay of FA3 (12 ns) = 36 ns.",
                "  - Worst-case delay for RCA = max(32 ns, 36 ns) = 36 ns.",
                "Step 2: Calculate CLA worst-case delay:",
                "  - Generate Pi, Gi: P_i = A_i XOR B_i (10 ns); G_i = A_i AND B_i (4 ns).",
                "    Both available at t = 10 ns.",
                "  - Carry lookahead network: Each carry C_i = G_{i-1} + P_{i-1} G_{i-2} + ... is a 2-level AND-OR circuit.",
                "    AND gate delay = 4 ns, OR gate delay = 4 ns.",
                "    All carries C1, C2, C3, C4 ready at: t = 10 ns (Pi) + 4 ns (AND) + 4 ns (OR) = 18 ns.",
                "  - Final sum bits: S_i = P_i XOR C_i.",
                "    Carries ready at 18 ns. XOR gate delay = 10 ns.",
                "    All sum bits ready at: t = 18 ns + 10 ns = 28 ns.",
                "  - Worst-case delay for CLA = 28 ns.",
                "Result: RCA delay = 36 ns; CLA delay = 28 ns.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Digital Design and Computer Architecture (2nd Edition)",
                  authors: "David Money Harris, Sarah L. Harris",
                  year: "2012",
                  publisher: "Morgan Kaufmann",
                  relevance: "Chapter 5.2: Adders, Ripple Carry, and Carry-Lookahead Adders.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: COMBINATIONAL LOGIC MODULES & CIRCUIT SYNTHESIS
    // =========================================================================
    {
      id: "dl-module-3-combinational-modules",
      title: "Module 3: Combinational Logic Modules & Circuit Synthesis",
      slug: "combinational-modules",
      description:
        "Multiplexers, Shannon's expansion, decoders with active-low enables, priority encoders, magnitude comparators, and programmable logic architectures (PROM, PLA, PAL).",
      order: 3,
      lessons: [
        {
          id: "multiplexers-and-adders",
          title: "Multiplexers, Shannon's Expansion & Universal Logic Synthesis",
          slug: "multiplexers-and-adders",
          order: 1,
          estimatedMinutes: 30,
          tagline: "2^n:1 MUX synthesis, tree expansions, Shannon's decomposition, and universal logic generation.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A 2^n:1 MUX can implement ANY Boolean function of (n + 1) variables without external gates, and ANY function of n variables directly by connecting inputs to 0 or 1.",
            keyFormulasAndRules: [
              "MUX Output Equation: Y = Sum_{i=0}^{2^n - 1} m_i * I_i, where m_i is the minterm of select lines S_{n-1} ... S_0.",
              "Implementing (n + 1) variables with 2^n:1 MUX: Connect n variables to select lines. The data inputs I_i are assigned from {0, 1, x_{n+1}, x_{n+1}'}.",
              "Shannon's Decomposition: f(A, B, C) = A * f(1, B, C) + A' * f(0, B, C). A 2:1 MUX directly evaluates this with select line A.",
              "Tree Expansion of Multiplexers: A 16:1 MUX can be built using five 4:1 MUXes (4 in first stage, 1 in second stage), or two 8:1 MUXes + one 2:1 MUX.",
              "Number of 2:1 MUXes needed to build a 2^n:1 MUX = 2^n - 1.",
            ],
            examPitfalls: [
              "Ensure the order of select lines matches MSB and LSB conventions. Swapping S1 and S0 permutes data inputs and inverts the implemented Boolean logic.",
              "When an enable line (EN) is present, active-low enable (EN') forces output to 0 whenever EN = 1 regardless of select inputs.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Universal Logic of Multiplexers",
              body: [
                "A **Multiplexer (MUX)** is a combinational selector that routes one of $2^n$ data inputs to a single output based on $n$ select lines.",
                "**Why Multiplexers are Universal:** Multiplexers are fundamentally hardware implementations of truth tables. By connecting variables to select lines, each data input $I_i$ corresponds to a specific row (or pair of rows) of the truth table.",
                "**Synthesis Strategies:**",
                "1. **$n$-variable function with $2^n:1$ MUX**: Connect all $n$ variables to the select lines. Connect $I_i = 1$ if minterm $m_i$ is in the function, and $I_i = 0$ otherwise.",
                "2. **$(n+1)$-variable function with $2^n:1$ MUX**: Connect $n$ variables to the select lines. For each combination of the select variables, express the output as a function of the remaining single variable $C$. The value of each $I_i$ will be one of: $0$, $1$, $C$, or $C'$.",
                "3. **Modular Expansion**: To construct a $2^n:1$ MUX using $2^k:1$ MUXes ($k < n$), the total number of smaller multiplexers required is given by the geometric series: $\\sum_{i=1}^{\\lceil n/k \\rceil} \\frac{2^n}{2^{k \\cdot i}}$. Specifically, to build a $2^n:1$ MUX entirely from 2:1 MUXes requires exactly $2^n - 1$ modules.",
              ],
              callout: {
                kind: "mental-model",
                title: "Tree Architecture Calculation",
                message: "Building a 64:1 MUX from 4:1 MUXes requires: Stage 1 = 64/4 = 16 MUXes; Stage 2 = 16/4 = 4 MUXes; Stage 3 = 4/4 = 1 MUX. Total = 16 + 4 + 1 = 21 MUXes.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Function Synthesis via 4:1 MUX with Reordered Select Lines",
              weightage: "2 Marks (GATE CS)",
              trap: "Notice that select inputs are chosen as B (MSB) and C (LSB), leaving A as the input data variable.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "Implement the function f(A, B, C) = Sigma m(0, 1, 4, 6, 7) using a 4:1 MUX where select lines are connected as S1 = B and S0 = C.",
                "Determine the inputs (I0, I1, I2, I3) connected to data lines.",
                "Step 1: Write truth table grouped by select lines (B, C):",
                "  For BC = 00 (I0): covers m0 (A=0, BC=00) and m4 (A=1, BC=00).",
                "    Both m0 and m4 are present in f! Thus, when BC = 00, f = 1 regardless of A.",
                "    Therefore, I0 = 1.",
                "  For BC = 01 (I1): covers m1 (A=0, BC=01) and m5 (A=1, BC=01).",
                "    m1 is in f (output 1), m5 is NOT in f (output 0).",
                "    When A = 0, f = 1; when A = 1, f = 0 -> f = A'.",
                "    Therefore, I1 = A'.",
                "  For BC = 10 (I2): covers m2 (A=0, BC=10) and m6 (A=1, BC=10).",
                "    m2 is NOT in f (output 0), m6 is in f (output 1).",
                "    When A = 0, f = 0; when A = 1, f = 1 -> f = A.",
                "    Therefore, I2 = A.",
                "  For BC = 11 (I3): covers m3 (A=0, BC=11) and m7 (A=1, BC=11).",
                "    m3 is NOT in f (output 0), m7 is in f (output 1).",
                "    When A = 0, f = 0; when A = 1, f = 1 -> f = A.",
                "    Therefore, I3 = A.",
                "Result: The data inputs are (I0, I1, I2, I3) = (1, A', A, A).",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Fundamentals of Logic Design (7th Edition)",
                  authors: "Charles H. Roth, Larry L. Kinney",
                  year: "2013",
                  publisher: "Cengage Learning",
                  relevance: "Chapter 9: Multiplexers, Decoders, and Programmable Logic Devices.",
                },
              ],
            },
          ],
        },
        {
          id: "decoders-encoders-converters",
          title: "Decoders, Encoders, Priority Encoders & Code Converters",
          slug: "decoders-encoders-converters",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Active-low minterm generators, priority resolution truth tables, and BCD-to-seven-segment logic.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "An n-to-2^n decoder generates all 2^n minterms. A Priority Encoder outputs the binary code of the highest-order active input, ignoring lower-order active inputs.",
            keyFormulasAndRules: [
              "Decoder Output: Active-high decoder outputs y_i = m_i. Active-low decoder outputs y_i' = (m_i)' = M_i (maxterm generator).",
              "Implementing Functions with Decoders: Any Boolean function can be implemented using an n-to-2^n decoder + an OR gate (for active-high) or a NAND gate (for active-low).",
              "Decoder Tree Expansion: To build an n-to-2^n decoder using k-to-2^k decoders: Use 2^{n-k} decoders in the second stage, and one (n-k)-to-2^{n-k} decoder to drive their enable lines.",
              "Priority Encoder: Resolves multiple simultaneous active inputs. A 4-to-2 priority encoder has inputs D3 (highest), D2, D1, D0 (lowest), valid flag V = D3 + D2 + D1 + D0, and outputs Y1 = D3 + D2, Y0 = D3 + D2' D1.",
            ],
            examPitfalls: [
              "Commercial decoders (e.g., 74LS138) have active-LOW outputs. Combining active-low decoder outputs to form a function requires a NAND gate, NOT an OR gate!",
              "Do not forget the Valid (V) output of priority encoders, which distinguishes between input `0001` (D0 active) and `0000` (all inactive).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Decoders and Priority Encoders in Hardware Architecture",
              body: [
                "A **Decoder** is a combinational circuit that converts an $n$-bit binary input code into $2^n$ unique output lines. Exactly one output line is activated for each input combination.",
                "**Minterm Generator:** Because each output corresponds to a specific minterm, any Boolean function expressed in canonical SOP form $f = \\sum m(1, 3, 7)$ can be synthesized simply by feeding the corresponding decoder outputs into an OR gate.",
                "**Active-Low Decoders:** Most real TTL/CMOS decoders use active-low outputs ($Y_i = 0$ when selected, $1$ otherwise). By De Morgan's laws: $\\sum m_i = (\\prod m_i')' = (\\prod Y_i)'$. Therefore, connecting active-low decoder outputs to a **NAND gate** directly produces the OR of minterms!",
                "**Priority Encoders:** Standard encoders assume exactly one input is active at any time. When multiple inputs are asserted simultaneously (as in hardware interrupt controllers), a standard encoder produces corrupted outputs. A **Priority Encoder** guarantees that the output reflects the index of the highest-priority asserted request.",
              ],
              callout: {
                kind: "exam-tip",
                title: "Decoder Expansion Formula",
                message: "To build a 5-to-32 decoder using 3-to-8 decoders: Stage 2 requires $32/8 = 4$ decoders. Stage 1 requires one 2-to-4 decoder to drive the enables of the 4 decoders. Total = $4 + 1 = 5$ decoders.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Logic Function Synthesis via Active-Low Decoder",
              weightage: "2 Marks (GATE CS)",
              trap: "Active-low outputs combined into a NOR or AND gate perform different dual functions.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "A 3-to-8 decoder has active-low outputs Y0' through Y7' where Y_k' = 0 iff input (A, B, C) represents binary k.",
                "The outputs Y1', Y3', Y5', and Y7' are connected to the inputs of an active-low input NAND gate (which is equivalent to an OR gate).",
                "What Boolean function f(A, B, C) is realized?",
                "Step 1: Write output expression of the NAND gate:",
                "  f = (Y1' * Y3' * Y5' * Y7')'.",
                "Step 2: Apply De Morgan's theorem:",
                "  f = (Y1')' + (Y3')' + (Y5')' + (Y7')'.",
                "Step 3: Relate to minterms:",
                "  Since Y_k' = (m_k)', we have (Y_k')' = m_k.",
                "  Therefore, f = m1 + m3 + m5 + m7.",
                "Step 4: Minimize the minterm sum:",
                "  m1 = A'B'C, m3 = A'BC, m5 = AB'C, m7 = ABC.",
                "  Factor out C: f = (A'B' + A'B + AB' + AB) C = 1 * C = C.",
                "Result: The circuit computes the simple identity f(A, B, C) = C.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Digital Design: With an Introduction to the Verilog HDL",
                  authors: "M. Morris Mano, Michael D. Ciletti",
                  year: "2012",
                  publisher: "Pearson",
                  relevance: "Chapter 4.9: Decoders and Encoders.",
                },
              ],
            },
          ],
        },
        {
          id: "comparators-programmable-logic",
          title: "Magnitude Comparators, Parity Generators & Programmable Logic (PROM, PLA, PAL)",
          slug: "comparators-programmable-logic",
          order: 3,
          estimatedMinutes: 28,
          tagline: "Cascaded comparator delays, even/odd parity generation, and architectural differences between PROM, PLA, and PAL.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "PROM has fixed AND array (full decoder) + programmable OR array. PAL has programmable AND array + fixed OR array. PLA has BOTH programmable AND and programmable OR arrays.",
            keyFormulasAndRules: [
              "Programmable Device Architecture Comparison:",
              "  PROM: Fixed AND array (decodes all 2^n minterms) + Programmable OR array. (Best for look-up tables, wastes chip area if few minterms used).",
              "  PAL (Programmable Array Logic): Programmable AND array + Fixed OR array. (Fast, easy to program, but fixed number of product terms per OR gate).",
              "  PLA (Programmable Logic Array): Programmable AND array + Programmable OR array. (Most flexible, allows product term sharing across outputs, but slower due to dual programmable links).",
              "1-Bit Comparator: A = B iff A XNOR B = 1; A > B iff A B' = 1; A < B iff A' B = 1.",
              "Parity Generator / Checker: Odd parity of n bits = XOR sum of all bits. Even parity = XNOR sum.",
            ],
            examPitfalls: [
              "Remember the flexibility hierarchy: PLA > PAL > PROM in terms of term sharing, but PAL > PLA in terms of operating propagation speed.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Programmable Logic Structures & Comparators",
              body: [
                "**Programmable Logic Devices (PLDs)** allow digital systems to be fabricated using standard off-the-shelf chips programmed by the engineer rather than fixed gate layouts.",
                "**Architectural Comparison Matrix:**",
                "1. **PROM**: Contains an $n$-to-$2^n$ decoder (fixed AND array generating every minterm) feeding into a programmable OR array. A PROM can implement *any* function of $n$ variables, but cannot share product terms and scales exponentially.",
                "2. **PLA (Programmable Logic Array)**: Both the AND array (which forms product terms) and the OR array (which sums product terms) are fully programmable. Multiple outputs can share the exact same product term, making PLAs extremely space-efficient for multi-output minimization.",
                "3. **PAL (Programmable Array Logic)**: The AND array is programmable, but the OR array is completely fixed (each output OR gate receives a fixed group of product terms, e.g., 4 or 8 terms). PALs are faster and cheaper to manufacture than PLAs because only one array of fuses is programmable.",
                "**Magnitude Comparators:** Compare two $n$-bit numbers $A$ and $B$ and generate three outputs: $A > B$, $A = B$, and $A < B$. Equality is computed as $\\prod_{i=0}^{n-1} (A_i \\odot B_i)$. Greater-than condition evaluates from MSB down to LSB: $A > B$ if $A_{n-1} > B_{n-1}$, or ($A_{n-1} = B_{n-1}$ and $A_{n-2} > B_{n-2}$), etc.",
              ],
              callout: {
                kind: "mental-model",
                title: "Product Term Sharing",
                message: "Only PLAs can share product terms between outputs. If output $F_1 = AB + CD$ and $F_2 = AB + EF$, a PLA requires only 3 AND gates ($AB, CD, EF$). A PAL requires 4 AND gates because the AND terms feeding $F_1$'s OR gate cannot connect to $F_2$'s OR gate.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: PLA Capacity & Product Term Sharing",
              weightage: "2 Marks (GATE CS)",
              trap: "Optimize multiple outputs simultaneously to maximize shared product terms.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "Determine the minimum number of product terms (AND gates) required in a PLA to implement the two functions:",
                "  F1(A, B, C) = Sigma m(1, 2, 3, 5, 7)",
                "  F2(A, B, C) = Sigma m(1, 3, 4, 5)",
                "Step 1: Simplify F1 individually:",
                "  Minterms: 1 (001), 2 (010), 3 (011), 5 (101), 7 (111).",
                "  Combine (1, 3, 5, 7) -> C.",
                "  Combine (2, 3) -> A'B.",
                "  F1 = C + A'B. (Product terms: C, A'B).",
                "Step 2: Simplify F2 individually:",
                "  Minterms: 1 (001), 3 (011), 4 (100), 5 (101).",
                "  Combine (1, 3, 5) -> C with 1 and 3? (1, 3) = A'C; (1, 5) = B'C.",
                "  Combine (4, 5) -> AB'.",
                "  F2 = B'C + AB' (or A'C + AB').",
                "Step 3: Analyze potential shared product terms:",
                "  Can F2 use C? If F2 uses C, minterms 1, 3, 5 are covered, but 3 is included (which is in F2). However, C also covers minterm 7, which is NOT in F2!",
                "  So F2 cannot use the lone term C.",
                "  What if F1 uses B'C? Notice C = B'C + BC.",
                "  If F1 is expressed as: F1 = B'C + BC + A'B = B'C + (B)(C + A') = B'C + BC + A'B.",
                "  Alternatively: can F1 and F2 share B'C?",
                "  For F1: covers 1, 5 (B'C). Remaining minterms in F1 are 2, 3, 7: covered by A'B (2, 3) and BC (3, 7).",
                "  Terms: {B'C, A'B, BC}. (3 terms for F1).",
                "  For F2: minterms 1, 5 (covered by B'C), 4 (covered by AB' with 5), 3 (covered by A'C with 1).",
                "  Total unique terms needed: C (for F1), A'B (for F1), B'C (for F2), AB' (for F2). Total = 4 AND gates.",
                "Result: A PLA requires a minimum of 4 product terms to implement both functions.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Modern Digital Electronics (4th Edition)",
                  authors: "R. P. Jain",
                  year: "2010",
                  publisher: "McGraw Hill Education",
                  relevance: "Chapter 6: PLDs, Comparators, and Parity Generators.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: SEQUENTIAL CIRCUITS & FLIP-FLOP DYNAMICS
    // =========================================================================
    {
      id: "dl-module-4-sequential-circuits",
      title: "Module 4: Sequential Circuits, Latches & Flip-Flop Dynamics",
      slug: "sequential-circuits",
      description:
        "Latches vs Flip-flops, characteristic equations, excitation tables, conversion methodology, race-around condition, and synchronous/asynchronous counter synthesis.",
      order: 4,
      lessons: [
        {
          id: "flip-flops-and-counters",
          title: "Latches, Flip-Flops (SR, JK, D, T), Conversions & Race-Around Condition",
          slug: "flip-flops-and-counters",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Master-slave architectures, excitation tables, characteristic equations, and flip-flop conversion algorithms.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Latches are level-triggered; Flip-Flops are edge-triggered. The Race-Around condition occurs in level-triggered JK flip-flops when J=K=1 and pulse width t_p > t_{pd}.",
            keyFormulasAndRules: [
              "Characteristic Equations:",
              "  SR Flip-Flop: Q_{next} = S + R' Q (Constraint: S * R = 0)",
              "  JK Flip-Flop: Q_{next} = J Q' + K' Q",
              "  D Flip-Flop:  Q_{next} = D",
              "  T Flip-Flop:  Q_{next} = T XOR Q = T Q' + T' Q",
              "Excitation Tables (Transition Q -> Q_{next}):",
              "  0 -> 0: S=0, R=X | J=0, K=X | D=0 | T=0",
              "  0 -> 1: S=1, R=0 | J=1, K=X | D=1 | T=1",
              "  1 -> 0: S=0, R=1 | J=X, K=1 | D=0 | T=1",
              "  1 -> 1: S=X, R=0 | J=X, K=0 | D=1 | T=0",
              "Race-Around Condition Elimination: (1) Master-Slave flip-flop, (2) Edge-triggered flip-flop, (3) Ensuring clock pulse width t_p < t_{pd(FF)}.",
            ],
            examPitfalls: [
              "In SR latch using NOR gates, S=1 sets Q=1; but in SR latch using NAND gates (S'R' latch), the inputs are active-low!",
              "Do not forget the invalid condition S=R=1 in SR flip-flops, which forces both Q and Q' to 0 (or 1 in NAND latches), violating complementarity.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Bistable Multivibrator & Memory Dynamics",
              body: [
                "A **Latch** is a level-sensitive bistable circuit that responds to input signals throughout the entire duration of an active clock level.",
                "A **Flip-Flop** is an edge-triggered storage element that updates its state exclusively on the transition (rising 0->1 or falling 1->0) of the clock pulse.",
                "**The Race-Around Condition:** In a level-triggered JK flip-flop with inputs $J = K = 1$, the output toggles every $t_{pd}$ nanoseconds while the clock remains HIGH ($t_p$). If the clock pulse width $t_p$ is greater than the propagation delay $t_{pd}$, the output will oscillate unpredictably between 0 and 1, leaving the final state undetermined when the clock drops LOW.",
                "**Solutions to Race-Around:**",
                "1. **Clock narrowing**: Ensure clock width $t_p < t_{pd}$ (technologically impractical due to parasitic capacitances).",
                "2. **Master-Slave Architecture**: The Master latch responds while clock is HIGH; the Slave latch is isolated. When clock falls LOW, Master is locked and Slave transfers the state to outputs.",
                "3. **Edge-Triggered Flip-Flops**: Internal steering circuits lock inputs within a fraction of a nanosecond around the clock edge.",
                "**Conversion Methodology:** To convert an existing Flip-Flop $A$ into a target Flip-Flop $B$:",
                "1. Write the truth table of target Flip-Flop $B$ listing current state $Q$ and target input.",
                "2. Determine next state $Q_{next}$ using target $B$'s characteristic behavior.",
                "3. Use the excitation table of source Flip-Flop $A$ to determine required inputs of $A$ for each transition $Q \\to Q_{next}$.",
                "4. Simplify the inputs of $A$ using K-maps in terms of target inputs and $Q$.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Flip-Flop Conversion Rule",
                message: "Always use the TARGET flip-flop's truth table to find Q_next, and the AVAILABLE flip-flop's excitation table to find the input equations.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Converting a JK Flip-Flop to a T Flip-Flop",
              weightage: "2 Marks (GATE CS)",
              trap: "Ensure that Q is treated as an input variable alongside T when simplifying J and K.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "Derive the input equations to convert a JK flip-flop into a T flip-flop.",
                "Step 1: Write Truth Table with Q, T and desired Q_next:",
                "  T | Q | Q_next",
                "  0 | 0 |   0    (T=0 holds state)",
                "  0 | 1 |   1    (T=0 holds state)",
                "  1 | 0 |   1    (T=1 toggles 0 -> 1)",
                "  1 | 1 |   0    (T=1 toggles 1 -> 0)",
                "Step 2: Determine required J and K using JK Excitation Table:",
                "  Transition Q -> Q_next | Required J | Required K",
                "  0 -> 0 (Row 1):        |     0      |     X",
                "  1 -> 1 (Row 2):        |     X      |     0",
                "  0 -> 1 (Row 3):        |     1      |     X",
                "  1 -> 0 (Row 4):        |     X      |     1",
                "Step 3: Combine with inputs (T, Q):",
                "  For J in terms of (T, Q):",
                "    Row 1 (T=0, Q=0): J = 0",
                "    Row 2 (T=0, Q=1): J = X",
                "    Row 3 (T=1, Q=0): J = 1",
                "    Row 4 (T=1, Q=1): J = X",
                "    K-map for J: Grouping cells with T=1 (giving J=1 and J=X) yields: J = T.",
                "  For K in terms of (T, Q):",
                "    Row 1 (T=0, Q=0): K = X",
                "    Row 2 (T=0, Q=1): K = 0",
                "    Row 3 (T=1, Q=0): K = X",
                "    Row 4 (T=1, Q=1): K = 1",
                "    K-map for K: Grouping cells with T=1 (giving K=X and K=1) yields: K = T.",
                "Result: Connect both J and K together to input T: J = T and K = T.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Digital Design: With an Introduction to the Verilog HDL",
                  authors: "M. Morris Mano, Michael D. Ciletti",
                  year: "2012",
                  publisher: "Pearson",
                  relevance: "Chapter 5: Synchronous Sequential Logic and Flip-Flop conversions.",
                },
              ],
            },
          ],
        },
        {
          id: "counter-synthesis-mod-n",
          title: "Synchronous & Asynchronous (Ripple) Counter Synthesis & Modulo States",
          slug: "counter-synthesis-mod-n",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Ripple counter glitch hazards, synchronous state table synthesis, unused states, and self-correcting counters.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "An Asynchronous (Ripple) counter cascades clock signals (Q of flip-flop i clocks flip-flop i+1). A Synchronous counter clocks all flip-flops simultaneously, achieving much higher operating frequency.",
            keyFormulasAndRules: [
              "Ripple Counter Clock Polling Rules:",
              "  Negative-edge triggered FF: Clock from Q -> UP Counter; Clock from Q' -> DOWN Counter.",
              "  Positive-edge triggered FF: Clock from Q -> DOWN Counter; Clock from Q' -> UP Counter.",
              "Ripple Counter Delay: T_{delay} = n * t_{pd(FF)}. Maximum frequency: f_{max} = 1 / (n * t_{pd(FF)}).",
              "Mod-N Counter Requirement: Number of flip-flops n must satisfy: 2^{n-1} < N <= 2^n.",
              "Synchronous Counter Design Procedure: 1. State diagram with N states. 2. State table with present state Q_i and next state Q_i^+. 3. Flip-flop excitation inputs. 4. K-maps for each FF input. 5. Verify unused state lock-out.",
              "Ring Counter vs Johnson Counter (n flip-flops):",
              "  Ring Counter: Modulo = n (states: 1000, 0100, 0010, 0001).",
              "  Johnson (Twisted Ring) Counter: Modulo = 2n (states: 0000, 1000, 1100, 1110, 1111, 0111, 0011, 0001).",
            ],
            examPitfalls: [
              "Asynchronous counters produce transient 'glitches' on intermediate output transitions due to cumulative delay, making them dangerous for decoding logic without strobe gates.",
              "Always check where unused states go in a synchronous counter. If an unused state transitions into a cycle of other unused states, the counter suffers from Lock-Out and is NOT self-correcting.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Physics and Logic of Digital Counters",
              body: [
                "A **Counter** is a register capable of progressing through a prescribed sequence of states upon the application of input clock pulses.",
                "**Asynchronous (Ripple) Counters:** The external clock is applied *only* to the first flip-flop (LSB). The output of each flip-flop triggers the clock input of the next flip-flop. While extremely simple to wire, the cumulative propagation delay $n \\cdot t_{pd}$ causes decoding glitches and severely limits maximum operating frequency.",
                "**Synchronous Counters:** The clock input is connected directly and simultaneously to the clock terminal of *all* flip-flops. State transitions occur concurrently on the active clock edge. Combinational steering logic computes the next state in parallel, keeping total delay constant at $t_{pd(FF)} + t_{comb}$ regardless of counter size $n$.",
                "**Lock-Out and Self-Correction:** When an $n$-bit counter uses $N < 2^n$ valid states, there are $2^n - N$ **unused states**. If noise or power-up forces the counter into an unused state, a robust counter design must guarantee that subsequent clock pulses eventually guide the system back into the main counting sequence (self-correcting design).",
              ],
              callout: {
                kind: "exam-tip",
                title: "Johnson Counter Decoding Advantage",
                message: "An $n$-stage Johnson counter has $2n$ states, and each state can be decoded using a simple 2-input AND gate without glitches, whereas a standard binary counter requires $n$-input gates.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Tracing Sequence of a Feedback Counter",
              weightage: "2 Marks (GATE CS)",
              trap: "Trace all flip-flops simultaneously on the clock edge; do not propagate new states within the same clock period.",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "A sequential counter is constructed using three D flip-flops (Q2, Q1, Q0) with inputs:",
                "  D2 = Q1 XOR Q0",
                "  D1 = Q2",
                "  D0 = Q1'",
                "If the initial state is Q2 Q1 Q0 = 0 0 0, find the counting sequence and determine the modulus (number of distinct states).",
                "Step 1: Compute next state logic for each state:",
                "  - State 0 (000):",
                "    D2 = 0 XOR 0 = 0",
                "    D1 = 0",
                "    D0 = 0' = 1",
                "    Next State: 0 0 1.",
                "  - State 1 (001):",
                "    D2 = 0 XOR 1 = 1",
                "    D1 = 0",
                "    D0 = 0' = 1",
                "    Next State: 1 0 1.",
                "  - State 2 (101):",
                "    D2 = 0 XOR 1 = 1",
                "    D1 = 1",
                "    D0 = 0' = 1",
                "    Next State: 1 1 1.",
                "  - State 3 (111):",
                "    D2 = 1 XOR 1 = 0",
                "    D1 = 1",
                "    D0 = 1' = 0",
                "    Next State: 0 1 0.",
                "  - State 4 (010):",
                "    D2 = 1 XOR 0 = 1",
                "    D1 = 0",
                "    D0 = 1' = 0",
                "    Next State: 1 0 0.",
                "  - State 5 (100):",
                "    D2 = 0 XOR 0 = 0",
                "    D1 = 1",
                "    D0 = 0' = 1",
                "    Next State: 0 1 1.",
                "  - State 6 (011):",
                "    D2 = 1 XOR 1 = 0",
                "    D1 = 0",
                "    D0 = 1' = 0",
                "    Next State: 0 0 0 (Returns to initial state!).",
                "Step 2: Count distinct states in sequence:",
                "  Sequence: 000 -> 001 -> 101 -> 111 -> 010 -> 100 -> 011 -> 000.",
                "  Number of distinct states in the cycle = 7.",
                "Result: The counter is a Modulo-7 counter.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Digital Design: With an Introduction to the Verilog HDL",
                  authors: "M. Morris Mano, Michael D. Ciletti",
                  year: "2012",
                  publisher: "Pearson",
                  relevance: "Chapter 6: Registers and Counters, Ripple Counters, and Synchronous Counter Design.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: SHIFT REGISTERS, FSMs & TIMING CONSTRAINTS
    // =========================================================================
    {
      id: "dl-module-5-fsm-timing",
      title: "Module 5: Shift Registers, Finite State Machines & Timing Constraints",
      slug: "fsm-and-timing",
      description:
        "SISO, SIPO, PISO, PIPO shift registers, Mealy vs Moore state machines, state minimization, setup time, hold time, clock skew, and maximum operating frequency.",
      order: 5,
      lessons: [
        {
          id: "fsm-shift-registers-timing",
          title: "Shift Registers, FSMs (Mealy/Moore) & Setup/Hold Time Timing Analysis",
          slug: "fsm-shift-registers-timing",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Mealy vs Moore machines, setup and hold slack inequalities, clock skew hazards, and metastabiliy.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Moore machine outputs depend ONLY on the present state. Mealy machine outputs depend on present state AND present inputs. Minimum clock period T_clk >= t_{cq(max)} + t_{comb(max)} + t_{setup} - t_{skew}.",
            keyFormulasAndRules: [
              "Mealy vs Moore Output Comparison:",
              "  Moore Machine: Output = lambda(State). Changing input changes output only on the NEXT clock edge. Requires generally more states than Mealy.",
              "  Mealy Machine: Output = lambda(State, Input). A change in input can change the output IMMEDIATELY asynchronously (prone to glitches).",
              "Shift Register Types: SISO (Serial In Serial Out - n clock pulses to load, n to read), SIPO (1 to read), PISO (1 to load, n to read), PIPO (1 to load, 1 to read).",
              "Setup Time Constraint (Limits Max Speed): T_{clk} >= t_{cq(max)} + t_{comb(max)} + t_{setup} - t_{skew}. Max frequency f_{max} = 1 / T_{clk(min)}.",
              "Hold Time Constraint (Prevents Race Through): t_{cq(min)} + t_{comb(min)} >= t_{hold} + t_{skew}. NOTE: Hold time is INDEPENDENT of clock period T_clk!",
              "Clock Skew definition: t_{skew} = T_{clk(dest)} - T_{clk(source)}. Positive skew helps setup time but harms hold time.",
            ],
            examPitfalls: [
              "Slowing down the clock (increasing T_clk) NEVER fixes a hold time violation because T_clk does not appear in the hold time inequality!",
              "In sequence detector design, check whether overlapping sequences are allowed. An overlapping detector reuses the suffix of an existing match as the prefix of the next match.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. State Machines and Dynamic Timing Closures",
              body: [
                "**Finite State Machines (FSM):** Every synchronous sequential system can be formalized as an FSM characterized by present states, inputs, next states, and outputs.",
                "- **Moore Model**: Output is associated exclusively with the state node. In state transition graphs, outputs are written inside the state circle ($S_0 / 0$). Outputs change strictly synchronously with clock edges.",
                "- **Mealy Model**: Output is associated with the transition edge ($a / 0$: input $a$ produces output $0$). An input transition can immediately perturb the output combinationally between clock edges.",
                "**Static Timing Analysis (STA):**",
                "Real digital gates do not switch instantaneously. Reliable data transfer between two communicating flip-flops (launching flip-flop $FF_1$ and capturing flip-flop $FF_2$) requires satisfying two independent timing inequalities:",
                "1. **Setup Time ($t_{setup}$)**: Data launched by $FF_1$ on clock edge 1 must propagate through clock-to-Q delay $t_{cq}$ and combinational logic $t_{comb}$ and settle at $FF_2$'s input at least $t_{setup}$ nanoseconds *before* clock edge 2 arrives: $T_{clk} \\ge t_{cq} + t_{comb} + t_{setup} - t_{skew}$.",
                "2. **Hold Time ($t_{hold}$)**: New data launched by $FF_1$ on clock edge 2 must *not* arrive at $FF_2$ too quickly before $FF_2$ has finished capturing the old data: $t_{cq(min)} + t_{comb(min)} \\ge t_{hold} + t_{skew}$.",
              ],
              callout: {
                kind: "trap",
                title: "The Hold Violation Trap",
                message: "If two flip-flops are connected directly back-to-back ($t_{comb} = 0$), a hold violation occurs if $t_{cq} < t_{hold} + t_{skew}$. This is a fatal chip fabrication defect that cannot be fixed by adjusting the operating clock speed.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Analysis: Maximum Clock Frequency and Hold Slack Calculation",
              weightage: "2 Marks (GATE CS)",
              trap: "Pay close attention to whether clock skew is positive (destination clock arrives later) or negative (destination clock arrives earlier).",
              solutionSteps: [
                "Problem Statement (Modeled on GATE Pattern):",
                "A digital synchronous datapath has two flip-flops communicating through a combinational multiplier.",
                "Given parameters:",
                "  - Clock-to-Q delay: t_cq(max) = 2.5 ns, t_cq(min) = 1.2 ns",
                "  - Combinational path delay: t_comb(max) = 8.0 ns, t_comb(min) = 2.0 ns",
                "  - Setup time: t_setup = 1.5 ns",
                "  - Hold time: t_hold = 1.0 ns",
                "  - Clock skew: t_skew = 0.5 ns (destination clock delayed)",
                "Calculate: (a) The minimum clock period T_clk and maximum clock frequency f_max, and (b) The hold slack.",
                "Step 1: Apply Setup Time Inequality for T_clk:",
                "  Formula: T_clk >= t_cq(max) + t_comb(max) + t_setup - t_skew",
                "  T_clk >= 2.5 ns + 8.0 ns + 1.5 ns - 0.5 ns",
                "  T_clk >= 11.5 ns.",
                "  Minimum clock period T_clk(min) = 11.5 ns.",
                "  Maximum frequency f_max = 1 / 11.5 ns = 1 / (11.5 * 10^-9 s) ≈ 86.96 MHz.",
                "Step 2: Check Hold Time Constraint:",
                "  Formula: t_{data_arrival(min)} >= t_{data_required}",
                "  t_cq(min) + t_comb(min) >= t_hold + t_skew",
                "  LHS = 1.2 ns + 2.0 ns = 3.2 ns.",
                "  RHS = 1.0 ns + 0.5 ns = 1.5 ns.",
                "  Hold Slack = LHS - RHS = 3.2 ns - 1.5 ns = +1.7 ns.",
                "Conclusion: Hold slack is positive (+1.7 ns), meaning no hold violation exists. Maximum clock frequency is 86.96 MHz.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Digital Integrated Circuits: A Design Perspective (2nd Edition)",
                  authors: "Jan M. Rabaey, Anantha Chandrakasan, Borivoje Nikolic",
                  year: "2003",
                  publisher: "Pearson",
                  relevance: "Chapter 10: Timing Issues in Digital Circuits, Setup, Hold, and Clock Skew.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
