import { CourseMeta } from "./types";

export const DISCRETE_MATHEMATICS_COURSE: CourseMeta = {
  id: "discrete-mathematics",
  title: "Discrete Mathematics",
  slug: "discrete-mathematics",
  subjectSlug: "discrete-mathematics",
  shortTitle: "Discrete Maths",
  icon: "🔢",
  color: "bg-indigo-400",
  tagline:
    "Master mathematical logic, first-order quantifiers, relation closures, POSET lattices, cyclic groups, combinatorics, recurrence relations, planar graphs, and chromatic coloring.",
  description:
    "A rigorous, foundational study notebook covering the mathematical structures that underpin all of computer science and theoretical computation: propositional logic equivalences, first-order predicate quantifiers, relation counting, Hasse diagrams, complemented distributive lattices, group theory and Lagrange's theorem, generating functions, Euler's planar formula, and Hall's matching theorem for B.Tech semester exams and top-rank GATE CS/IT & DA preparation.",
  level: "Undergraduate / GATE CS & DA",
  estimatedHours: 48,
  prerequisites: [
    "High school algebra, modular arithmetic, and set operations",
    "Basic mathematical reasoning and proof by induction",
  ],
  learningOutcomes: [
    "Evaluate propositional arguments and perform resolution refutation proofs in propositional and first-order logic",
    "Translate complex natural language specifications into first-order predicate formulas with nested quantifiers",
    "Count relation types on finite sets and analyze partial orders, Hasse diagrams, and lattice complements",
    "Apply group theory axioms, determine element orders, and utilize Lagrange's subgroup coset theorem",
    "Solve linear homogeneous and non-homogeneous recurrence relations and evaluate derangements and generating functions",
    "Prove graph properties using Euler's Planar Formula V - E + F = 2, Kuratowski's theorem, and Handshaking lemma",
    "Determine vertex chromatic numbers, Eulerian circuits, Hamiltonian cycles, and apply Hall's Marriage Theorem",
  ],
  gateScope: "GATE 2027 CS/IT + DA scope",
  gateBranches: ["cs", "da"],
  gateSyllabusTopics: [
    "Mathematical logic: Propositional logic, connectives, equivalences, normal forms (DNF, CNF), inference rules, first-order predicate logic, quantifiers",
    "Sets, relations, and functions: Operations, equivalence relations, partitions, closures, POSETs, Hasse diagrams, lattices, Boolean algebras",
    "Algebraic structures: Semigroups, monoids, groups, abelian groups, subgroups, Lagrange's theorem, cyclic groups, generators",
    "Combinatorics: Counting principles, permutations and combinations, stars and bars, Pigeonhole Principle, Inclusion-Exclusion, derangements",
    "Recurrence relations: Linear recurrence relations with constant coefficients, characteristic equation roots, generating functions",
    "Graph theory: Paths, cycles, Handshaking lemma, bipartite graphs, Eulerian graphs, Hamiltonian graphs, planar graphs (Euler formula, Kuratowski theorem), graph coloring, chromatic numbers, matching",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: MATHEMATICAL LOGIC & PREDICATE CALCULUS
    // =========================================================================
    {
      id: "dm-module-1-logic",
      title: "Module 1: Mathematical Logic & Predicate Calculus",
      slug: "logic-and-proofs",
      description:
        "Truth tables, conditional implications, logical equivalences, DNF/CNF canonical normal forms, inference rules, resolution, and first-order predicate logic with nested quantifiers.",
      order: 1,
      lessons: [
        {
          id: "propositional-and-predicate-logic",
          title: "Propositional Equivalences, Normal Forms & Inference Rules",
          slug: "propositional-and-predicate-logic",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Tautologies, DNF/CNF canonical expansions, inference rules, and resolution refutation.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Conditional Implication p -> q is logically equivalent to ~p v q, and its Contrapositive ~q -> ~p. It is FALSE only when p is True and q is False.",
            keyFormulasAndRules: [
              "Implication Law: p -> q <=> ~p v q.",
              "Contrapositive Law: p -> q <=> ~q -> ~p (Strictly Equivalent).",
              "Converse: q -> p (NOT logically equivalent to p -> q).",
              "Inverse: ~p -> ~q (NOT logically equivalent to p -> q).",
              "De Morgan's Laws: ~(p ^ q) <=> ~p v ~q; ~(p v q) <=> ~p ^ ~q.",
              "Modus Ponens: From p and p -> q, infer q.",
              "Modus Tollens: From ~q and p -> q, infer ~p.",
              "Resolution Rule: From (p v q) and (~p v r), infer (q v r).",
            ],
            examPitfalls: [
              "The converse (q -> p) and inverse (~p -> ~q) are equivalent to each other, but NEITHER is equivalent to the original implication (p -> q).",
              "p <-> q is true when p and q share the same truth value. p <-> q <=> (p -> q) ^ (q -> p).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Propositional Connectives & The Implication Axiom",
              body: [
                "A **Proposition** is a declarative statement that is either TRUE or FALSE, but not both.",
                "**The Conditional Implication (`p -> q`):**",
                "The statement `p -> q` asserts that if hypothesis `p` holds, conclusion `q` must hold. It is **FALSE in only one case: when `p` is TRUE and `q` is FALSE**.",
                "If `p` is FALSE, `p -> q` is vacuously TRUE regardless of `q`.",
                "**Canonical Equivalence Laws:**",
                "1. `p -> q <=> neg p lor q` (Implication Law)",
                "2. `p -> q <=> neg q -> neg p` (Contrapositive Law)",
                "3. `neg(p -> q) <=> p land neg q`",
                "4. `p <-> q <=> (p -> q) land (q -> p) <=> (p land q) lor (neg p land neg q)`",
                "**Formulas Classification:**",
                "- **Tautology:** TRUE under all truth assignments.",
                "- **Contradiction:** FALSE under all truth assignments.",
                "- **Contingency:** Neither a tautology nor a contradiction.",
                "- **Satisfiable:** TRUE under at least one assignment.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Canonical Normal Forms & Resolution Refutation",
              body: [
                "Every boolean formula can be converted into standard normal forms:",
                "1. **Disjunctive Normal Form (DNF):** OR of ANDs (Sum of Products).",
                "2. **Conjunctive Normal Form (CNF):** AND of ORs (Product of Sums).",
                "**The Resolution Principle (Robinson):**",
                "Resolution is an inference rule that operates on clauses in CNF:",
                "`frac{(A lor B) quad land quad (neg B lor C)}{A lor C}`",
                "Here `B` and `neg B` are complementary literals that cancel out to produce the **resolvent** `A lor C`.",
                "To prove that premise set `Delta` entails conclusion `alpha` (`Delta models alpha`):",
                "Convert `Delta cup {neg alpha}` into CNF clauses and apply resolution. If the empty clause `square` (a contradiction) is derived, `alpha` is valid.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Testing Argument Validity via Resolution",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "To prove validity by refutation, you must negate the conclusion before resolving.",
              solutionSteps: [
                "Problem: Determine the validity of the argument with premises P1: p -> (q v r), P2: ~q, P3: ~r, and conclusion C: ~p.",
                "Step 1: Convert premises and negated conclusion into CNF clauses:",
                "  P1: p -> (q v r) <=> ~p v q v r (Clause 1: {~p, q, r})",
                "  P2: ~q (Clause 2: {~q})",
                "  P3: ~r (Clause 3: {~r})",
                "  Negated Conclusion ~C: ~(~p) <=> p (Clause 4: {p})",
                "Step 2: Apply resolution steps:",
                "  - Resolve Clause 1 {~p, q, r} with Clause 4 {p}:",
                "    Complementary literals p and ~p cancel => Resolvent R1: {q, r}.",
                "  - Resolve R1 {q, r} with Clause 2 {~q}:",
                "    Complementary literals q and ~q cancel => Resolvent R2: {r}.",
                "  - Resolve R2 {r} with Clause 3 {~r}:",
                "    Complementary literals r and ~r cancel => Resolvent R3: {} (Empty Clause / Contradiction).",
                "Step 3: Conclusion:",
                "  Derivation of the empty clause confirms that P1 ^ P2 ^ P3 ^ p is unsatisfiable.",
                "  Therefore, the original argument is VALID.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Discrete Mathematics and Its Applications (8th Edition)",
                  authors: "Kenneth H. Rosen",
                  year: "2019",
                  publisher: "McGraw-Hill",
                  relevance: "Chapter 1: The Foundations: Logic and Proofs.",
                },
              ],
            },
          ],
        },
        {
          id: "first-order-logic-and-quantifiers",
          title: "First-Order Predicate Logic, Nested Quantifiers & Translations",
          slug: "first-order-logic-and-quantifiers",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Universal and existential scope, negation duality, nested quantifier order, and English specification translations.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Negation duality: ~(forall x P(x)) <=> exists x ~P(x), and ~(exists x P(x)) <=> forall x ~P(x). Swapping forall and exists changes truth value.",
            keyFormulasAndRules: [
              "Universal Translation: 'All A are B' => forall x (A(x) -> B(x)). NEVER use ^ here.",
              "Existential Translation: 'Some A are B' => exists x (A(x) ^ B(x)). NEVER use -> here.",
              "Quantifier Order Non-Equivalence: forall x exists y P(x, y) is NOT equivalent to exists y forall x P(x, y).",
              "Duality of Null Quantifiers: If x does not appear free in A, then forall x (A v B(x)) <=> A v forall x B(x).",
            ],
            examPitfalls: [
              "'Every student passed' is forall x (Student(x) -> Passed(x)). If you write forall x (Student(x) ^ Passed(x)), it falsely claims every object in the universe is a student!",
              "exists y forall x P(x, y) strictly implies forall x exists y P(x, y), but the converse is FALSE.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Grammar of Predicates & Quantifiers",
              body: [
                "**Predicates** model relations on domains: `P(x)` evaluates to a truth value when variable `x` is assigned an element from the Domain of Discourse `D`.",
                "**The Two Fundamental Quantifiers:**",
                "1. **Universal Quantifier (`forall x P(x)`):** True iff `P(a)` is true for **every** `a in D`.",
                "2. **Existential Quantifier (`exists x P(x)`):** True iff `P(a)` is true for **at least one** `a in D`.",
                "**De Morgan Laws for Quantifiers:**",
                "`neg(forall x P(x)) <=> exists x neg P(x)`",
                "`neg(exists x P(x)) <=> forall x neg P(x)`",
              ],
            },
            {
              type: "explanation",
              heading: "2. Nested Quantifiers & Ordering Dynamics",
              body: [
                "When quantifiers of the same type are adjacent, their order can be swapped without changing meaning:",
                "`forall x forall y P(x, y) <=> forall y forall x P(x, y)`",
                "`exists x exists y P(x, y) <=> exists y exists x P(x, y)`",
                "**When quantifiers are mixed, ORDER IS CRITICAL:**",
                "- `forall x exists y text{Loves}(x, y)`: 'Everybody loves somebody' (each person `x` can choose a different person `y`).",
                "- `exists y forall x text{Loves}(x, y)`: 'There is a single universal person who is loved by everybody'.",
                "Theorem: `exists y forall x P(x, y) implies forall x exists y P(x, y)`, but the converse does NOT hold.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Formalizing Complex Natural Language Specifications",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Distinguish 'only if' from 'if' when setting up the direction of logical implication.",
              solutionSteps: [
                "Problem: Translate the following English statement into first-order predicate logic using predicates Student(x), Course(y), Enrolled(x, y), and Passed(x, y):",
                "  'Every student who is enrolled in some course has passed at least one course.'",
                "Step 1: Identify components:",
                "  - 'x is a student': Student(x).",
                "  - 'x is enrolled in some course': exists y (Course(y) ^ Enrolled(x, y)).",
                "  - Combined antecedent: Student(x) ^ exists y (Course(y) ^ Enrolled(x, y)).",
                "  - 'x has passed at least one course': exists z (Course(z) ^ Passed(x, z)).",
                "Step 2: Universal quantification over all students x:",
                "  forall x [ (Student(x) ^ exists y (Course(y) ^ Enrolled(x, y))) -> exists z (Course(z) ^ Passed(x, z)) ]",
                "Step 3: Verify boundary conditions:",
                "  If x is not a student, antecedent is False => implication is vacuously True.",
                "  If x is a student not enrolled in any course, antecedent is False => True.",
                "  If x is enrolled in a course, x must satisfy the consequent by passing at least one course.",
                "Final Formalized Formula: forall x [ (Student(x) ^ exists y (Course(y) ^ Enrolled(x, y))) -> exists z (Course(z) ^ Passed(x, z)) ].",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Discrete Mathematics and Its Applications (8th Edition)",
                  authors: "Kenneth H. Rosen",
                  year: "2019",
                  publisher: "McGraw-Hill",
                  relevance: "Chapter 1: Predicate Logic and Nested Quantifiers.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: SETS, RELATIONS, POSETS & LATTICES
    // =========================================================================
    {
      id: "dm-module-2-relations-and-lattices",
      title: "Module 2: Sets, Relations, POSETs & Lattices",
      slug: "relations-and-lattices",
      description:
        "Equivalence relations, relation closures, exact counting of relation types on finite sets, partial orders, Hasse diagrams, and distributive/complemented lattices.",
      order: 2,
      lessons: [
        {
          id: "relations-posets-and-lattices",
          title: "Relations, Closures, Equivalence Partitions & Counting",
          slug: "relations-posets-and-lattices",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Reflexive, symmetric, transitive closures, counting relation types on finite sets, and partition Bell numbers.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "For a set of size n: Reflexive = 2^{n^2 - n}, Symmetric = 2^{n(n+1)/2}, Anti-symmetric = 2^n * 3^{n(n-1)/2}, Reflexive & Symmetric = 2^{n(n-1)/2}.",
            keyFormulasAndRules: [
              "Total Relations on set of size n: 2^{n^2}.",
              "Reflexive Relations: 2^{n^2 - n} (diagonal pairs must be included).",
              "Irreflexive Relations: 2^{n^2 - n} (diagonal pairs must be excluded).",
              "Symmetric Relations: 2^{n(n+1)/2} (diagonal pairs can be in/out, off-diagonal symmetric pairs chosen together).",
              "Anti-Symmetric Relations: 2^n * 3^{n(n-1)/2} (diagonal in/out, off-diagonal can be (a,b), (b,a), or neither).",
              "Asymmetric Relations: 3^{n(n-1)/2} (no diagonal allowed).",
              "Equivalence Relation: Simultaneously Reflexive, Symmetric, and Transitive. Partitions set into disjoint equivalence classes.",
            ],
            examPitfalls: [
              "Anti-symmetric is NOT the opposite of symmetric. A relation can be BOTH symmetric and anti-symmetric (e.g. Identity relation R = {(a, a)}).",
              "A relation can be NEITHER symmetric nor anti-symmetric.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Binary Relation Axioms on Finite Sets",
              body: [
                "A binary relation `R` from set `A` to set `B` is a subset of the Cartesian product `A times B`. When `A = B`, `R` is a relation on `A`.",
                "For a set `A` with `|A| = n` elements, the product `A times A` has `n^2` ordered pairs.",
                "**Core Properties:**",
                "1. **Reflexive:** `forall a in A, (a, a) in R`.",
                "2. **Irreflexive:** `forall a in A, (a, a) notin R`.",
                "3. **Symmetric:** `forall a, b in A, (a, b) in R implies (b, a) in R`.",
                "4. **Anti-Symmetric:** `forall a, b in A, [ (a, b) in R land (b, a) in R ] implies a = b`.",
                "5. **Asymmetric:** `forall a, b in A, (a, b) in R implies (b, a) notin R` (implies irreflexive).",
                "6. **Transitive:** `forall a, b, c in A, [ (a, b) in R land (b, c) in R ] implies (a, c) in R`.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Combinatorial Counting of Relation Types",
              body: [
                "Represent `R` as an `n times n` Boolean adjacency matrix:",
                "- There are `n` main diagonal entries `(a_i, a_i)`.",
                "- There are `n^2 - n = n(n - 1)` off-diagonal entries, forming `n(n - 1) / 2` symmetric pairs `{ (a_i, a_j), (a_j, a_i) }` with `i < j`.",
                "**Derivations:**",
                "- **Reflexive:** Diagonal entries are fixed to 1 (1 choice). The `n(n - 1)` off-diagonal entries can each be 0 or 1 (2 choices). Total = `2^{n(n - 1)} = 2^{n^2 - n}`.",
                "- **Symmetric:** Diagonal entries can each be 0 or 1 (`2^n` choices). For each of the `n(n - 1)/2` off-diagonal pairs, both must be 0 or both must be 1 (2 choices). Total = `2^n * 2^{n(n - 1)/2} = 2^{n(n + 1)/2}`.",
                "- **Anti-Symmetric:** Diagonal entries can be 0 or 1 (`2^n` choices). For each of the `n(n - 1)/2` pairs, we cannot have both equal 1. Possible choices: `(0, 0), (1, 0), (0, 1)` (3 choices). Total = `2^n * 3^{n(n - 1)/2}`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Exact Counting on Finite Set of Size n = 4",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Do not mix up Reflexive & Symmetric with just Symmetric. Adding reflexivity forces all n diagonal entries to 1, eliminating 2^n degrees of freedom.",
              solutionSteps: [
                "Problem: For a set A containing n = 4 elements, calculate:",
                "  1. The number of reflexive relations.",
                "  2. The number of symmetric relations.",
                "  3. The number of relations that are simultaneously reflexive and symmetric.",
                "  4. The number of anti-symmetric relations.",
                "Step 1: Set size parameters: n = 4, n^2 = 16, n(n - 1) / 2 = 4(3) / 2 = 6 pairs.",
                "Step 2: Calculate Reflexive relations:",
                "  Formula: 2^{n^2 - n} = 2^{16 - 4} = 2^{12} = 4,096 relations.",
                "Step 3: Calculate Symmetric relations:",
                "  Formula: 2^{n(n + 1) / 2} = 2^{4(5) / 2} = 2^{10} = 1,024 relations.",
                "Step 4: Calculate Reflexive & Symmetric relations:",
                "  Diagonal has 1 choice (must be 1). Off-diagonal has 6 pairs, each with 2 choices.",
                "  Formula: 2^{n(n - 1) / 2} = 2^6 = 64 relations.",
                "Step 5: Calculate Anti-Symmetric relations:",
                "  Formula: 2^n * 3^{n(n - 1) / 2} = 2^4 * 3^6 = 16 * 729 = 11,664 relations.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Discrete Mathematics and Its Applications (8th Edition)",
                  authors: "Kenneth H. Rosen",
                  year: "2019",
                  publisher: "McGraw-Hill",
                  relevance: "Chapter 9: Relations, counting properties.",
                },
              ],
            },
          ],
        },
        {
          id: "posets-hasse-diagrams-and-lattices",
          title: "POSETs, Hasse Diagrams, Lattices & Boolean Algebras",
          slug: "posets-hasse-diagrams-and-lattices",
          order: 2,
          estimatedMinutes: 34,
          tagline: "Partial orders, topological sorting, LUB/GLB existence, distributive and complemented lattices, and Boolean algebras.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A POSET is a Lattice iff EVERY pair of elements has a UNIQUE LUB (join v) and a UNIQUE GLB (meet ^). A complemented distributive lattice is a Boolean Algebra.",
            keyFormulasAndRules: [
              "POSET Definition: Reflexive + Anti-Symmetric + Transitive.",
              "Hasse Diagram: Visual DAG of a finite POSET with reflexive self-loops and transitive edges removed.",
              "LUB (Least Upper Bound / Supremum): Smallest among all upper bounds. Must be unique.",
              "GLB (Greatest Lower Bound / Infimum): Largest among all lower bounds. Must be unique.",
              "Distributive Lattice: a ^ (b v c) = (a ^ b) v (a ^ c) for all a, b, c.",
              "Complement of a in bounded lattice [0, 1]: An element b such that a v b = 1 and a ^ b = 0.",
              "Boolean Algebra: Bounded + Distributive + Complemented lattice.",
              "Divisibility Lattice D_n: Forms a Boolean Algebra iff n is a SQUARE-FREE integer (e.g. D_30 = {1, 2, 3, 5, 6, 10, 15, 30}).",
            ],
            examPitfalls: [
              "If two elements share multiple upper bounds with no single unique least upper bound, the POSET is NOT a lattice.",
              "A lattice can have elements with NO complements or MULTIPLE complements, unless it is a Boolean algebra where complements are strictly unique.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Partially Ordered Sets & Hasse Diagrams",
              body: [
                "A relation `R` on set `S` is a **Partial Order** if it is Reflexive, Anti-Symmetric, and Transitive. The pair `(S, R)` is called a **POSET**.",
                "**Hasse Diagrams:**",
                "A visual drawing of a finite POSET where:",
                "1. All reflexive loops `(x, x)` are omitted.",
                "2. All transitive edges (if `x <= y` and `y <= z`, omit `(x, z)`) are omitted.",
                "3. Edge arrows are replaced by vertical orientation: if `x < y`, `y` is drawn above `x` and connected by an edge.",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Lattice Hierarchy to Boolean Algebra",
              body: [
                "**1. Lattice:** A POSET `(L, <=)` where every pair of elements `{a, b}` has a unique Least Upper Bound (LUB / Join `a lor b`) and a unique Greatest Lower Bound (GLB / Meet `a land b`).",
                "**2. Bounded Lattice:** Has a global universal lower bound `0` and global universal upper bound `1`.",
                "**3. Distributive Lattice:** Meet distributes over join, and join distributes over meet. (Non-distributive lattices always contain sublattices isomorphic to the pentagon `N_5` or diamond `M_3`).",
                "**4. Complemented Lattice:** In a bounded lattice, every element `a` has a complement `a'` such that `a lor a' = 1` and `a land a' = 0`.",
                "**5. Boolean Algebra:** A lattice that is simultaneously Bounded, Distributive, and Complemented. In a Boolean algebra, the complement of every element is **strictly unique**.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Testing Divisibility Lattices for Complements",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "D_n is a Boolean algebra if and only if n has no repeated prime factors (square-free).",
              solutionSteps: [
                "Problem: Consider the divisibility relation on D_36 = {1, 2, 3, 4, 6, 9, 12, 18, 36}. Determine whether (D_36, |) is a lattice, and whether it forms a Boolean algebra.",
                "Step 1: Determine whether D_36 is a lattice:",
                "  For any a, b in D_36:",
                "  LUB(a, b) = lcm(a, b), and GLB(a, b) = gcd(a, b).",
                "  Since gcd and lcm are unique positive integers and both divide 36 for any divisors of 36, every pair has a unique LUB and GLB.",
                "  Therefore, (D_36, |) is a valid LATTICE. Lower bound 0 = 1, Upper bound 1 = 36.",
                "Step 2: Test for complementation:",
                "  In a complemented lattice, for every element a, there exists b such that:",
                "  gcd(a, b) = 1 (meet is 1), and lcm(a, b) = 36 (join is 36).",
                "Step 3: Test element a = 6:",
                "  We require gcd(6, b) = 1 and lcm(6, b) = 36.",
                "  If gcd(6, b) = 1, then b cannot be divisible by 2 or 3.",
                "  The only divisors of 36 not divisible by 2 or 3 is {1}.",
                "  However, lcm(6, 1) = 6 != 36.",
                "  No element in D_36 satisfies the condition for a = 6. Hence, 6 has NO COMPLEMENT!",
                "Final Conclusion: (D_36, |) is a distributive lattice, but it is NOT a complemented lattice, and therefore NOT a Boolean algebra.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Discrete Mathematical Structures with Applications to Computer Science",
                  authors: "J.P. Tremblay, R. Manohar",
                  year: "1987",
                  publisher: "McGraw-Hill",
                  relevance: "Chapter 4: Lattices and Boolean Algebra.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: ALGEBRAIC STRUCTURES & GROUP THEORY
    // =========================================================================
    {
      id: "dm-module-3-algebra",
      title: "Module 3: Algebraic Structures & Group Theory",
      slug: "algebraic-structures",
      description:
        "Semigroups, monoids, groups, abelian groups, subgroups, Lagrange's subgroup coset theorem, and cyclic group generators.",
      order: 3,
      lessons: [
        {
          id: "algebraic-structures-and-groups",
          title: "Algebraic Structures: Semigroups, Monoids, Groups & Subgroups",
          slug: "algebraic-structures-and-groups",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Group axioms, abelian groups, permutation groups, subgroup criteria, and Lagrange's coset theorem.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Lagrange's Theorem: In any finite group G, the order (cardinality) of every subgroup H strictly divides the order of the group: |H| divides |G|.",
            keyFormulasAndRules: [
              "Groupoid (Closure): a * b in G.",
              "Semigroup: Closure + Associativity: (a * b) * c = a * (b * c).",
              "Monoid: Semigroup + Identity element e (a * e = e * a = a).",
              "Group: Monoid + Inverse element a^{-1} for every element.",
              "Abelian Group: Group + Commutativity (a * b = b * a).",
              "Subgroup Criterion: Non-empty subset H is a subgroup iff for all a, b in H, a * b^{-1} in H.",
              "Inversion Formula: (a * b)^{-1} = b^{-1} * a^{-1}.",
            ],
            examPitfalls: [
              "The converse of Lagrange's Theorem is FALSE: If d divides |G|, there is NOT necessarily a subgroup of order d (classic counterexample: Alternating group A4 of order 12 has no subgroup of order 6).",
              "Identity element and inverses in any group are strictly UNIQUE.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Hierarchy of Algebraic Structures",
              body: [
                "An **Algebraic Structure** consists of a non-empty set `G` paired with one or more binary operations `*`:",
                "1. **Groupoid (Magma):** Closed under `*` (`forall a, b in G, a * b in G`).",
                "2. **Semigroup:** Groupoid that satisfies **Associativity**: `(a * b) * c = a * (b * c)`.",
                "3. **Monoid:** Semigroup that has an **Identity element** `e in G` such that `a * e = e * a = a`.",
                "4. **Group:** Monoid where every element `a in G` has a unique **Inverse** `a^{-1} in G` such that `a * a^{-1} = a^{-1} * a = e`.",
                "5. **Abelian (Commutative) Group:** Group that also satisfies `a * b = b * a` for all `a, b in G`.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Subgroups, Cosets & Lagrange's Theorem",
              body: [
                "A subset `H subseteq G` is a **Subgroup** (`H leq G`) if `H` itself forms a group under the operation of `G`.",
                "**One-Step Subgroup Test:** `H` is a subgroup iff `forall a, b in H, a * b^{-1} in H`.",
                "**Cosets:** For a subgroup `H leq G` and element `g in G`:",
                "- Left Coset: `gH = { g * h : h in H }`.",
                "- Right Coset: `Hg = { h * g : h in H }`.",
                "The left cosets of `H` form an exact partition of `G` into disjoint subsets, each of cardinality `|H|`.",
                "**Lagrange's Theorem:**",
                "If `G` is a finite group and `H` is a subgroup of `G`, then `|H|` divides `|G|`:",
                "`|G| = [G : H] * |H|`",
                "where `[G : H]` is the index of `H` in `G` (the number of distinct cosets).",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Subgroup Order Analysis using Lagrange Theorem",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Possible subgroup orders must be divisors of |G|. Non-divisors can never be subgroup orders.",
              solutionSteps: [
                "Problem: A group G has order |G| = 30. What are all possible orders of non-trivial proper subgroups of G? Can G have a subgroup of order 7?",
                "Step 1: State Lagrange's theorem condition:",
                "  If H is a subgroup of G, then |H| must divide |G| = 30.",
                "Step 2: Find all positive divisors of 30:",
                "  Divisors of 30 = {1, 2, 3, 5, 6, 10, 15, 30}.",
                "Step 3: Identify non-trivial proper subgroups:",
                "  - Trivial subgroup order = 1 ({e}).",
                "  - Improper subgroup order = 30 (G itself).",
                "  - Non-trivial proper subgroup orders are divisors strictly between 1 and 30:",
                "    Possible orders = {2, 3, 5, 6, 10, 15}.",
                "Step 4: Check subgroup of order 7:",
                "  Since 7 does NOT divide 30 (30 % 7 = 2 != 0), by Lagrange's theorem, G CANNOT have any subgroup of order 7.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Abstract Algebra (3rd Edition)",
                  authors: "David S. Dummit, Richard M. Foote",
                  year: "2003",
                  publisher: "Wiley",
                  relevance: "Chapter 1 & 3: Group Theory, Lagrange's Theorem.",
                },
              ],
            },
          ],
        },
        {
          id: "cyclic-groups-and-lagrange-theorem",
          title: "Cyclic Groups, Generators, Element Orders & Coset Partitions",
          slug: "cyclic-groups-and-lagrange-theorem",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Cyclic group structure, generator count with Euler's totient phi(n), element order divisibility, and quotient structures.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A group G of order n is Cyclic iff it has an element a of order n. The number of generators of a finite cyclic group of order n is Euler's totient phi(n).",
            keyFormulasAndRules: [
              "Order of an Element: Smallest positive integer k such that a^k = e. Denoted o(a).",
              "Divisibility of Element Order: In any finite group G, o(a) divides |G| for all a in G.",
              "Euler Totient Function phi(n): Number of integers 1 <= k <= n coprime to n. phi(p) = p - 1 for prime p.",
              "Product Formula: phi(n) = n * prod_{p | n} (1 - 1/p).",
              "Generator Condition in (Z_n, +): k is a generator of Z_n iff gcd(k, n) = 1.",
              "Every Cyclic Group is ABELIAN (converse is false: Klein 4-group is abelian but not cyclic).",
            ],
            examPitfalls: [
              "A group of prime order is ALWAYS cyclic, and every non-identity element is a generator.",
              "In a cyclic group of order n, for every divisor d of n, there is a UNIQUE subgroup of order d.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Order of an Element & Cyclic Group Structure",
              body: [
                "The **Order of an element** `a in G` (`o(a)`) is the smallest positive integer `k` such that `a^k = e` (under multiplication) or `k * a = 0` (under addition).",
                "Corollary of Lagrange's Theorem: In any finite group `G`, `o(a)` divides `|G|`. Furthermore, `a^{|G|} = e` for all `a in G`.",
                "**Definition of a Cyclic Group:**",
                "A group `G` is **cyclic** if there exists an element `g in G` such that `G = langle g rangle = { g^k : k in mathbb{Z} }`. The element `g` is called a **generator**.",
                "**Fundamental Properties:**",
                "1. Every cyclic group is Abelian.",
                "2. Any subgroup of a cyclic group is also cyclic.",
                "3. In a finite cyclic group of order `n`, the element `a^k` has order `n / gcd(k, n)`.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Counting Generators via Euler's Totient Function phi(n)",
              body: [
                "In the additive group `mathbb{Z}_n = {0, 1, ..., n - 1}` under addition modulo `n`:",
                "An element `k` is a generator if and only if `gcd(k, n) = 1`.",
                "Therefore, the total number of generators is `phi(n)` (Euler's Totient Function):",
                "`phi(n) = n * prod_{p | n} (1 - frac{1}{p})`",
                "For example, for `n = 12 = 2^2 * 3`:",
                "`phi(12) = 12 * (1 - 1/2) * (1 - 1/3) = 12 * (1/2) * (2/3) = 4` generators: `{1, 5, 7, 11}`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Generator and Element Order Calculation",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Remember that order of an element under addition is k * a = 0 mod n, not a^k.",
              solutionSteps: [
                "Problem: Consider the cyclic group G = (Z_18, +_18).",
                "  1. How many generators does G have?",
                "  2. List all generator elements.",
                "  3. Find the order of element 8.",
                "Step 1: Calculate generator count phi(18):",
                "  Prime factorization of 18 = 2^1 * 3^2.",
                "  phi(18) = 18 * (1 - 1/2) * (1 - 1/3) = 18 * (1/2) * (2/3) = 6 generators.",
                "Step 2: List integers 1 <= k < 18 coprime to 18 (gcd(k, 18) = 1):",
                "  Coprime set = {1, 5, 7, 11, 13, 17}.",
                "  There are exactly 6 generators.",
                "Step 3: Compute the order of element 8 in Z_18:",
                "  Formula: o(k) = n / gcd(k, n)",
                "  o(8) = 18 / gcd(8, 18) = 18 / 2 = 9.",
                "  Verification: 9 * 8 = 72 = 4 * 18 = 0 (mod 18). Smallest positive multiple is 9.",
                "Final Answer: 6 generators ({1, 5, 7, 11, 13, 17}), and order of 8 is 9.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Contemporary Abstract Algebra (9th Edition)",
                  authors: "Joseph A. Gallian",
                  year: "2016",
                  publisher: "Cengage Learning",
                  relevance: "Chapter 4: Cyclic Groups.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: COMBINATORICS & RECURRENCE RELATIONS
    // =========================================================================
    {
      id: "dm-module-4-combinatorics",
      title: "Module 4: Combinatorics & Recurrence Relations",
      slug: "combinatorics-and-recurrences",
      description:
        "Pigeonhole Principle, stars and bars counting, Inclusion-Exclusion, derangements, and solving linear recurrence relations via characteristic roots and generating functions.",
      order: 4,
      lessons: [
        {
          id: "combinatorics-and-recurrence-solving",
          title: "Combinatorics: Pigeonhole Principle, Stars & Bars & Derangements",
          slug: "combinatorics-and-recurrence-solving",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Generalized pigeonhole bounds, combinations with repetition, inclusion-exclusion, and derangements formula.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Non-negative integer solutions to x1 + ... + xn = r is binom(n + r - 1, r). Derangements of n items: D_n = n! * sum_{k=0}^n [(-1)^k / k!].",
            keyFormulasAndRules: [
              "Pigeonhole Principle (Ceiling): If N objects placed in k boxes => at least one box contains ceil(N / k) objects.",
              "Guaranteed Count: To guarantee at least m objects in same box => N = k*(m - 1) + 1 objects required.",
              "Stars and Bars (x_i >= 0): binom(n + r - 1, r).",
              "Stars and Bars (x_i >= 1): binom(r - 1, n - 1).",
              "Derangements Count: D_0 = 1, D_1 = 0, D_2 = 1, D_3 = 2, D_4 = 9, D_5 = 44.",
              "Recurrence for Derangements: D_n = (n - 1) * (D_{n-1} + D_{n-2}).",
            ],
            examPitfalls: [
              "When lower bounds on variables differ (e.g. x1 >= 2, x2 >= 0), substitute x1' = x1 - 2 to shift all variables to non-negative.",
              "Probability of a random permutation being a derangement approaches 1/e approx 0.3678 as n -> inf.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Generalized Pigeonhole Principle",
              body: [
                "**Basic Principle (Dirichlet):** If `k + 1` or more items are placed into `k` bins, at least one bin must contain at least 2 items.",
                "**Generalized Principle:**",
                "If `N` objects are placed into `k` boxes, then at least one box must contain at least `lceil N / k rceil` objects.",
                "**Inverted Problem (Guaranteeing a Quota):**",
                "How many items `N` must be chosen to **guarantee** that at least `m` items fall into the same category across `k` categories?",
                "By worst-case analysis: place `m - 1` items into each of the `k` categories without achieving the quota. The very next item forces the quota:",
                "`N_{min} = k * (m - 1) + 1`.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Stars and Bars & The Derangements Invariant",
              body: [
                "**Stars and Bars (Combinations with Repetition):**",
                "The number of ways to distribute `r` identical items into `n` distinct labeled bins (or non-negative integer solutions to `x_1 + x_2 + ... + x_n = r` with `x_i >= 0`):",
                "`binom{n + r - 1}{r} = frac{(n + r - 1)!}{r! (n - 1)!}`.",
                "**Derangements (Permutations with No Fixed Points):**",
                "A **derangement** is a permutation of `{1, 2, ..., n}` where no element appears in its original position (`pi(i) != i` for all `i`).",
                "Using the Principle of Inclusion-Exclusion (PIE):",
                "`D_n = n! sum_{k=0}^n frac{(-1)^k}{k!} = n! [ 1 - frac{1}{1!} + frac{1}{2!} - frac{1}{3!} + ... + frac{(-1)^n}{n!} ]`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Constrained Integer Solutions & Derangements",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Shift variables to >= 0 by subtracting non-zero lower bounds from total sum r.",
              solutionSteps: [
                "Problem: Find the number of integer solutions to x1 + x2 + x3 + x4 = 10 subject to constraints x1 >= 1, x2 >= 2, x3 >= 0, x4 >= 0.",
                "Step 1: Define non-negative shifted variables:",
                "  Let x1' = x1 - 1 >= 0  => x1 = x1' + 1",
                "  Let x2' = x2 - 2 >= 0  => x2 = x2' + 2",
                "  x3' = x3 >= 0",
                "  x4' = x4 >= 0",
                "Step 2: Substitute into equation:",
                "  (x1' + 1) + (x2' + 2) + x3' + x4' = 10",
                "  x1' + x2' + x3' + x4' = 10 - 3 = 7.",
                "Step 3: Apply Stars and Bars formula with n = 4, r = 7:",
                "  Number of solutions = binom(n + r - 1, r) = binom(4 + 7 - 1, 7) = binom(10, 7)",
                "  binom(10, 7) = binom(10, 3) = (10 * 9 * 8) / (3 * 2 * 1) = 720 / 6 = 120.",
                "Final Answer: Exactly 120 solutions.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introductory Combinatorics (5th Edition)",
                  authors: "Richard A. Brualdi",
                  year: "2009",
                  publisher: "Pearson",
                  relevance: "Chapters 2 & 6: Permutations and Combinations, The Inclusion-Exclusion Principle.",
                },
              ],
            },
          ],
        },
        {
          id: "recurrence-relations-and-generating-functions",
          title: "Recurrence Relations & Ordinary Generating Functions",
          slug: "recurrence-relations-and-generating-functions",
          order: 2,
          estimatedMinutes: 34,
          tagline: "Linear homogeneous recurrence with distinct/repeated roots, non-homogeneous particular solutions, and OGF power series.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "For a_n + c1*a_{n-1} + c2*a_{n-2} = 0: Distinct roots r1, r2 => a_n = A*r1^n + B*r2^n. Repeated root r => a_n = (A + B*n)*r^n.",
            keyFormulasAndRules: [
              "Characteristic Equation of degree 2: r^2 + c1*r + c2 = 0.",
              "Repeated Roots (multiplicity m): a_n = (A0 + A1*n + ... + A_{m-1}*n^{m-1}) * r^n.",
              "Non-Homogeneous Recurrence: a_n = a_n^{(h)} + a_n^{(p)} (Homogeneous + Particular solution).",
              "Generating Function: G(x) = sum_{n=0}^inf a_n * x^n.",
              "Standard OGF: 1 / (1 - ax) = sum_{n=0}^inf a^n * x^n.",
              "Fibonacci Generating Function: F(x) = x / (1 - x - x^2).",
            ],
            examPitfalls: [
              "If the non-homogeneous term f(n) = c * r^n coincides with a characteristic root of multiplicity m, the trial particular solution MUST be multiplied by n^m: a_n^{(p)} = C * n^m * r^n.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Solving Linear Homogeneous Recurrences",
              body: [
                "A recurrence relation of the form `a_n + c_1 a_{n-1} + c_2 a_{n-2} + ... + c_k a_{n-k} = 0` has constant coefficients.",
                "**Method of Characteristic Roots:**",
                "Substitute trial solution `a_n = r^n` into the recurrence to obtain the characteristic equation:",
                "`r^k + c_1 r^{k-1} + ... + c_k = 0`.",
                "1. **Distinct Real Roots `r_1, r_2, ..., r_k`:**",
                "`a_n = A_1 r_1^n + A_2 r_2^n + ... + A_k r_k^n`.",
                "2. **Repeated Roots (Root `r` with multiplicity `m`):**",
                "`a_n = (A_0 + A_1 n + A_2 n^2 + ... + A_{m-1} n^{m-1}) r^n`.",
                "Constants `A_i` are determined from initial boundary conditions.",
              ],
            },
            {
              type: "explanation",
              heading: "2. The Ordinary Generating Function (OGF) Method",
              body: [
                "An **Ordinary Generating Function** encapsulates an infinite numerical sequence `{a_0, a_1, a_2, ...}` as coefficients of a formal power series:",
                "`G(x) = sum_{n=0}^infty a_n x^n = a_0 + a_1 x + a_2 x^2 + ...`",
                "**Standard Power Series Expansions:**",
                "- `frac{1}{1 - x} = sum_{n=0}^infty x^n = 1 + x + x^2 + ...`",
                "- `frac{1}{1 - a x} = sum_{n=0}^infty a^n x^n`",
                "- `frac{1}{(1 - x)^2} = sum_{n=0}^infty (n + 1) x^n`",
                "- `frac{1}{(1 - x)^k} = sum_{n=0}^infty binom{n + k - 1}{n} x^n`",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Solving Second-Order Recurrence Relation",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Ensure initial conditions a0 and a1 are substituted correctly into the general solution to avoid algebraic sign flips.",
              solutionSteps: [
                "Problem: Solve the recurrence relation a_n = 5*a_{n-1} - 6*a_{n-2} for n >= 2, with initial conditions a_0 = 1, a_1 = 4.",
                "Step 1: Write characteristic equation:",
                "  r^2 - 5r + 6 = 0",
                "  (r - 2)(r - 3) = 0 => Distinct roots r1 = 2, r2 = 3.",
                "Step 2: Set up general homogeneous solution:",
                "  a_n = c1 * (2^n) + c2 * (3^n).",
                "Step 3: Solve for constants using initial conditions:",
                "  For n = 0: a_0 = c1*(2^0) + c2*(3^0) = c1 + c2 = 1.",
                "  For n = 1: a_1 = c1*(2^1) + c2*(3^1) = 2*c1 + 3*c2 = 4.",
                "Step 4: Solve linear 2x2 system:",
                "  From eq 1: c1 = 1 - c2.",
                "  Substitute: 2(1 - c2) + 3*c2 = 4 => 2 + c2 = 4 => c2 = 2.",
                "  c1 = 1 - 2 = -1.",
                "Step 5: Write final explicit closed-form expression:",
                "  a_n = 2 * (3^n) - (2^n).",
                "  Check for n = 2: a_2 = 2*(9) - 4 = 18 - 4 = 14.",
                "  From recurrence: a_2 = 5*(4) - 6*(1) = 20 - 6 = 14. Perfect match!",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Discrete Mathematics and Its Applications (8th Edition)",
                  authors: "Kenneth H. Rosen",
                  year: "2019",
                  publisher: "McGraw-Hill",
                  relevance: "Chapter 8: Advanced Counting Techniques, Recurrence Relations and Generating Functions.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: GRAPH THEORY, PLANARITY & COLORING
    // =========================================================================
    {
      id: "dm-module-5-graph-theory",
      title: "Module 5: Graph Theory, Connectivity, Planarity & Coloring",
      slug: "graph-theory",
      description:
        "Handshaking lemma, bipartite graphs, Eulerian circuits, Hamiltonian cycles, Euler's formula V - E + F = 2, Kuratowski's theorem, vertex coloring, and Hall's Marriage Theorem.",
      order: 5,
      lessons: [
        {
          id: "graph-theory-fundamentals-and-connectivity",
          title: "Graph Theory Foundations, Handshaking Lemma & Connectivity",
          slug: "graph-theory-fundamentals-and-connectivity",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Degree sum theorem, bipartite characterizations, vertex/edge connectivity, and Whitney's inequality.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Handshaking Lemma: sum_{v in V} deg(v) = 2|E|. The number of vertices of ODD degree in ANY graph is ALWAYS EVEN.",
            keyFormulasAndRules: [
              "Handshaking Lemma: sum_{v in V} deg(v) = 2E.",
              "Bipartite Graph Characterization: A graph is bipartite iff it contains NO ODD CYCLES.",
              "Complete Bipartite Graph K_{m, n}: Edges E = m * n, Chromatic number chi = 2.",
              "Complete Graph K_n: Edges E = n(n - 1) / 2, Chromatic number chi = n.",
              "Whitney's Connectivity Inequality: kappa(G) <= kappa'(G) <= delta(G) (Vertex connectivity <= Edge connectivity <= Minimum degree).",
            ],
            examPitfalls: [
              "A self-loop on vertex v contributes 2 to the degree of v in an undirected graph.",
              "A tree with n vertices has EXACTLY n - 1 edges and is ALWAYS bipartite (contains zero cycles).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Handshaking Lemma & Degree Invariants",
              body: [
                "An undirected graph `G = (V, E)` consists of vertices `V` and edges `E`.",
                "**The Handshaking Lemma:**",
                "`sum_{v in V} deg(v) = 2 |E|`",
                "*Proof:* Each edge `e = (u, v)` contributes exactly 1 to `deg(u)` and 1 to `deg(v)`. Summing over all vertices counts every edge exactly twice.",
                "**Fundamental Corollary:**",
                "Partition vertices into even degree `V_{even}` and odd degree `V_{odd}`:",
                "`sum_{v in V_{even}} deg(v) + sum_{v in V_{odd}} deg(v) = 2 |E|`.",
                "Since the total sum and the even sum are both even integers, `sum_{v in V_{odd}} deg(v)` must be an even integer. The sum of odd numbers can only be even if there is an **even count of odd terms**.",
                "Hence, **every graph has an even number of odd-degree vertices**.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Bipartite Graphs & Whitney's Connectivity Inequality",
              body: [
                "A graph `G` is **Bipartite** if its vertex set `V` can be partitioned into two disjoint subsets `V_1, V_2` such that every edge connects a vertex in `V_1` to a vertex in `V_2`.",
                "**Theorem (König):** A graph is bipartite if and only if it contains **no odd-length cycles**.",
                "**Connectivity Metrics:**",
                "- **Vertex Connectivity (`kappa(G)`):** Minimum vertices whose removal disconnects `G`.",
                "- **Edge Connectivity (`kappa'(G)`):** Minimum edges whose removal disconnects `G`.",
                "- **Minimum Degree (`delta(G)`):** Minimum vertex degree in `G`.",
                "**Whitney's Inequality:** For any graph `G`:",
                "`kappa(G) <= kappa'(G) <= delta(G)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Minimum Edges and Handshaking Inequality",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Use the inequality sum deg(v) >= n * delta(G) when minimum degree is specified.",
              solutionSteps: [
                "Problem: An undirected connected graph G has 8 vertices, and every vertex has degree at least 3. What is the minimum possible number of edges in G?",
                "Step 1: Apply Handshaking Lemma:",
                "  2 * |E| = sum_{v in V} deg(v).",
                "Step 2: Apply minimum degree constraint:",
                "  Since deg(v) >= 3 for all 8 vertices:",
                "  sum_{v in V} deg(v) >= 8 * 3 = 24.",
                "Step 3: Solve for |E|:",
                "  2 * |E| >= 24 => |E| >= 12.",
                "Step 4: Check realizability:",
                "  Can an 8-vertex 3-regular connected graph exist? Yes (e.g. 3D Cube graph Q3 has 8 vertices, each of degree 3, and exactly 12 edges).",
                "Final Answer: The minimum possible number of edges is 12.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Graph Theory (2nd Edition)",
                  authors: "Douglas B. West",
                  year: "2000",
                  publisher: "Prentice Hall",
                  relevance: "Chapter 1: Fundamental Concepts and Degree Sequences.",
                },
              ],
            },
          ],
        },
        {
          id: "graph-theory-planarity-and-coloring",
          title: "Eulerian Paths, Hamiltonian Cycles & Kuratowski Planarity",
          slug: "graph-theory-planarity-and-coloring",
          order: 2,
          estimatedMinutes: 34,
          tagline: "Eulerian circuit criteria, Dirac/Ore Hamiltonian theorems, Euler's formula V - E + F = 2, and Kuratowski minors.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Connected Planar Graphs: V - E + F = 2. For simple planar graphs with V >= 3: E <= 3V - 6 (or E <= 2V - 4 if triangle-free).",
            keyFormulasAndRules: [
              "Eulerian Circuit: Exists iff graph is connected and EVERY vertex has EVEN degree.",
              "Eulerian Path: Exists iff graph is connected and has EXACTLY 0 or 2 odd-degree vertices.",
              "Euler's Formula: V - E + F = 2 (where F includes the infinite exterior face).",
              "Planar Edge Bound: E <= 3V - 6 (for V >= 3).",
              "Triangle-Free Planar Edge Bound: E <= 2V - 4 (applies to bipartite planar graphs).",
              "Kuratowski's Theorem: G is planar iff it contains no subgraph homeomorphic to K_5 or K_{3,3}.",
            ],
            examPitfalls: [
              "Euler's formula V - E + F = 2 requires the graph to be CONNECTED. For a disconnected planar graph with k components: V - E + F = 1 + k.",
              "K_5 is non-planar (10 > 3(5) - 6 = 9). K_{3,3} is non-planar (9 > 2(6) - 4 = 8).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Eulerian vs Hamiltonian Traversals",
              body: [
                "**1. Eulerian Graph (Edge Traversal):**",
                "- **Eulerian Path:** A trail visiting every **edge** exactly once.",
                "- **Eulerian Circuit:** A closed trail visiting every **edge** exactly once.",
                "**Theorem:** A connected graph has an Eulerian circuit iff every vertex has **even degree**. It has an Eulerian path iff exactly 0 or 2 vertices have odd degree.",
                "**2. Hamiltonian Graph (Vertex Traversal):**",
                "- **Hamiltonian Cycle:** A closed cycle visiting every **vertex** exactly once.",
                "- Determining whether a general graph is Hamiltonian is **NP-Complete**.",
                "- **Dirac's Theorem:** If `G` is a simple graph with `n >= 3` vertices and `deg(v) >= n / 2` for all `v`, then `G` is Hamiltonian.",
                "- **Ore's Theorem:** If `deg(u) + deg(v) >= n` for every pair of non-adjacent vertices `u, v`, then `G` is Hamiltonian.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Planar Graphs, Euler's Formula & Kuratowski's Theorem",
              body: [
                "A graph is **Planar** if it can be embedded in a 2D plane such that no edges intersect except at vertices.",
                "**Euler's Planar Formula:**",
                "`V - E + F = 2` (where `F` is the number of regions/faces, including the outer unbounded region).",
                "**Boundary Invariant:**",
                "Each face is bounded by at least 3 edges. In planar graph `G`, `2E = sum_{f} text{deg}(f) >= 3F implies F <= frac{2E}{3}`.",
                "Substituting into Euler's formula:",
                "`2 = V - E + F <= V - E + frac{2E}{3} = V - frac{E}{3}`",
                "`frac{E}{3} <= V - 2 implies E <= 3V - 6`.",
                "If `G` contains no triangles (each face has degree `>= 4`, as in bipartite graphs):",
                "`2E >= 4F implies F <= frac{E}{2} implies E <= 2V - 4`.",
                "**Kuratowski's Theorem:** A graph is planar if and only if it does not contain a subgraph homeomorphic to `K_5` (complete graph on 5 vertices) or `K_{3,3}` (utility bipartite graph).",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Planar Graph Face Counting & Invariant Check",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Always verify whether the graph is connected before using V - E + F = 2.",
              solutionSteps: [
                "Problem: A connected simple planar graph has V = 10 vertices and divides the plane into F = 8 faces. Find the number of edges E, and verify whether the planar edge bound holds.",
                "Step 1: Apply Euler's formula for connected planar graphs:",
                "  V - E + F = 2",
                "  10 - E + 8 = 2",
                "  18 - E = 2",
                "  E = 18 - 2 = 16 edges.",
                "Step 2: Check standard planar edge bound E <= 3V - 6:",
                "  Max allowed edges for V = 10:",
                "  E_max = 3(10) - 6 = 30 - 6 = 24.",
                "  Since E = 16 <= 24, the edge bound is satisfied.",
                "Step 3: Verification with face degrees:",
                "  Average face degree = 2E / F = (2 * 16) / 8 = 32 / 8 = 4 edges/face.",
                "  Every face has on average 4 boundary edges. Perfectly valid!",
                "Final Answer: Number of edges E = 16.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Graph Theory (2nd Edition)",
                  authors: "Douglas B. West",
                  year: "2000",
                  publisher: "Prentice Hall",
                  relevance: "Chapter 6: Planar Graphs, Euler's formula and Kuratowski theorem.",
                },
              ],
            },
          ],
        },
        {
          id: "graph-coloring-and-matching",
          title: "Graph Coloring, Chromatic Numbers & Bipartite Matching",
          slug: "graph-coloring-and-matching",
          order: 3,
          estimatedMinutes: 32,
          tagline: "Vertex coloring, Four Color Theorem, chromatic polynomial counting, and Hall's Marriage Theorem.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Chromatic number chi(G) is the minimum colors to color vertices such that no adjacent vertices share a color. Bipartite graphs have chi = 2. Planar graphs have chi <= 4.",
            keyFormulasAndRules: [
              "Complete Graph K_n: chi(K_n) = n.",
              "Cycle Graph C_n: chi(C_n) = 2 if n is even; chi(C_n) = 3 if n is odd.",
              "Wheel Graph W_n (C_{n-1} + center hub): chi(W_n) = 3 if n is odd (even cycle); chi(W_n) = 4 if n is even (odd cycle).",
              "Bipartite Graph: chi(G) <= 2.",
              "Four Color Theorem (Appel & Haken): Every planar graph has chi(G) <= 4.",
              "Hall's Marriage Theorem: Bipartite graph G = (X cup Y, E) has a matching that saturates X iff |N(S)| >= |S| for all subsets S subseteq X.",
            ],
            examPitfalls: [
              "Greedy coloring with maximum degree Delta gives chi(G) <= Delta + 1. Brook's Theorem tightens this to chi(G) <= Delta (unless G is an odd cycle or complete graph).",
              "Hall's condition must hold for EVERY subset S of X, not just individual vertices.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Vertex Coloring & The Chromatic Number",
              body: [
                "A **k-coloring** of graph `G = (V, E)` is an assignment `c: V -> {1, 2, ..., k}` such that `(u, v) in E implies c(u) != c(v)`.",
                "The **Chromatic Number (`chi(G)`)** is the minimum `k` for which `G` is `k`-colorable.",
                "**Chromatic Numbers of Common Graph Families:**",
                "- **Complete Graph `K_n`:** Every vertex is adjacent to all others => `chi(K_n) = n`.",
                "- **Trees:** 2-colorable (bipartite) => `chi(T) = 2` (for `|V| >= 2`).",
                "- **Cycle Graph `C_n`:**",
                "  - `chi(C_n) = 2` if `n` is even.",
                "  - `chi(C_n) = 3` if `n` is odd.",
                "- **Planar Graphs (Four Color Theorem):** Every planar graph has `chi(G) <= 4`.",
              ],
            },
            {
              type: "explanation",
              heading: "2. Matching & Hall's Marriage Theorem",
              body: [
                "A **Matching** `M subseteq E` is a set of edges without common vertices.",
                "**Hall's Marriage Theorem (Bipartite Matching):**",
                "Let `G = (X cup Y, E)` be a bipartite graph. For any subset `S subseteq X`, let `N(S)` denote the neighborhood of `S` in `Y` (`N(S) = { y in Y : exists x in S, (x, y) in E }`).",
                "**Theorem:** There exists a matching that saturates every vertex in `X` if and only if:",
                "`|N(S)| >= |S| quad text{for every subset } S subseteq X`.",
                "If `G` is a `k`-regular bipartite graph (`k >= 1`), Hall's condition is unconditionally satisfied, meaning every regular bipartite graph contains a perfect matching.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "3. Worked Problem: Chromatic Number of Wheel Graph",
              weightage: "Original Practice Problem · Modeled on GATE Pattern (2 Marks)",
              trap: "Notice whether W_n denotes total n vertices or an n-cycle rim.",
              solutionSteps: [
                "Problem: Find the chromatic number chi(G) of the Wheel graph W_7 (which consists of an outer cycle C_6 on 6 vertices connected to a central hub vertex).",
                "Step 1: Identify outer cycle rim C_6:",
                "  The outer rim is an even cycle of length 6.",
                "  For any even cycle C_{2k}, its chromatic number is chi(C_6) = 2.",
                "  Let the two alternating colors on the rim be Red and Blue.",
                "Step 2: Color the central hub vertex:",
                "  The central hub is adjacent to EVERY vertex on the rim.",
                "  Since both Red and Blue appear among its neighbors, the hub cannot use Red or Blue.",
                "  A 3rd color (e.g. Green) is required for the hub.",
                "Step 3: Evaluate total colors:",
                "  Red and Blue for rim + Green for hub = 3 colors.",
                "  Can 2 colors suffice? No, because hub connects to rim vertices of both colors.",
                "Final Answer: The chromatic number of W_7 is 3.",
              ],
            },
            {
              type: "resources",
              heading: "4. Authoritative References",
              sources: [
                {
                  title: "Introduction to Graph Theory (2nd Edition)",
                  authors: "Douglas B. West",
                  year: "2000",
                  publisher: "Prentice Hall",
                  relevance: "Chapter 5: Coloring of Graphs, and Chapter 3: Matchings and Factors.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
