import { CourseMeta } from "./types";

export const ENGINEERING_MATHEMATICS_COURSE: CourseMeta = {
  id: "engineering-mathematics",
  title: "Engineering Mathematics",
  slug: "engineering-mathematics",
  subjectSlug: "engineering-mathematics",
  shortTitle: "Engg. Maths",
  icon: "📐",
  color: "bg-blue-400",
  tagline:
    "Master Linear Algebra, Multivariable Calculus, and Probability Distributions — the formal mathematical backbone of Computer Science and GATE.",
  description:
    "A rigorous, mathematically formal study notebook covering Linear Algebra, Differential and Integral Calculus, and Probability Theory tailored specifically for undergraduate computer science and GATE CS/IT high-scorers.",
  level: "Undergraduate / GATE CS",
  estimatedHours: 35,
  prerequisites: [
    "High school calculus (derivatives, integration, limits)",
    "Basic vector and 2D/3D coordinate geometry",
    "Elementary set theory and combinatorics",
  ],
  learningOutcomes: [
    "Compute matrix rank, nullity, determinants, LU decomposition, and solve homogeneous and non-homogeneous linear systems using Gaussian elimination",
    "Calculate eigenvalues, eigenvectors, algebraic and geometric multiplicities, and apply the Cayley-Hamilton Theorem to compute matrix powers and inverses",
    "Evaluate single and multivariable limits, determine continuity and differentiability, and apply Mean Value Theorems (Rolle's, Lagrange's, Cauchy's)",
    "Find local and absolute extrema for single-variable and two-variable functions using the Hessian discriminant test",
    "Evaluate definite and improper integrals using symmetry, change of variables, Leibniz rule, and Gamma functions",
    "Apply conditional probability, the Law of Total Probability, and Bayes' Theorem to prior-posterior update problems",
    "Compute expectation, variance, covariance, and standard deviations across discrete and continuous random variables",
    "Model discrete and continuous stochastic phenomena using Binomial, Poisson, Uniform, Exponential, and Normal distributions",
  ],
  gateScope: "GATE 2027 CS/IT Engineering Mathematics scope",
  gateBranches: ["cs", "da"],
  gateSyllabusTopics: [
    "Linear Algebra: Matrices, determinants, system of linear equations, eigenvalues and eigenvectors, LU decomposition",
    "Calculus: Limits, continuity and differentiability, max and min, mean value theorem, evaluation of definite and improper integrals",
    "Probability and Statistics: Random variables, uniform, normal, exponential, Poisson and binomial distributions, mean, median, mode and standard deviation, conditional probability and Bayes theorem",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: LINEAR ALGEBRA — MATRICES, SYSTEMS & LU DECOMPOSITION
    // =========================================================================
    {
      id: "math-module-1-linear-algebra",
      title: "Module 1: Matrices, Linear Systems & LU Factorization",
      slug: "linear-algebra",
      description:
        "Matrix algebra, determinants, rank of a matrix, Gaussian elimination, consistency of linear systems AX = B, and LU decomposition.",
      order: 1,
      lessons: [
        {
          id: "matrices-and-eigenvalues",
          title: "Matrix Rank, Systems of Equations & LU Decomposition",
          slug: "matrices-and-eigenvalues",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Echelon forms, Rouché-Capelli theorem, unique vs infinite solutions, and Doolittle LU factorization.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A system AX = B is consistent iff Rank(A) = Rank([A|B]). It has a unique solution if Rank = n, and infinitely many if Rank < n.",
            keyFormulasAndRules: [
              "Rank-Nullity Theorem: Rank(A) + Nullity(A) = n (number of columns / dimension of domain).",
              "Determinant Properties: Det(AB) = Det(A) * Det(B); Det(A^T) = Det(A); Det(k * A_{n x n}) = k^n * Det(A); Det(A^{-1}) = 1 / Det(A).",
              "Rouché-Capelli Theorem for AX = B:",
              "  1. Inconsistent (No Solution): Rank(A) < Rank([A|B]).",
              "  2. Unique Solution: Rank(A) = Rank([A|B]) = n.",
              "  3. Infinitely Many Solutions: Rank(A) = Rank([A|B]) = r < n (with n - r free variables).",
              "Homogeneous System AX = 0:",
              "  - Always consistent (trivial zero solution X = 0 always exists).",
              "  - Non-trivial (non-zero) solution exists iff Rank(A) < n iff Det(A) = 0 (for square A).",
              "LU Decomposition: A = L * U where L is unit lower triangular (l_ii = 1) and U is upper triangular (Doolittle method). Possible without pivoting iff all leading principal minors are non-zero.",
            ],
            examPitfalls: [
              "Do not forget Det(k * A) = k^n * Det(A) for an n x n matrix. For a 3x3 matrix, Det(2A) = 8 * Det(A), NOT 2 * Det(A).",
              "Elementary row operations do NOT alter matrix rank or solutions of AX = B, but multiplying a row by scalar c scales Det by c, and swapping two rows flips the sign of Det.",
              "In parameter consistency problems (e.g., finding k, m for infinite solutions), verify both the coefficient row AND the augmented constant entry simultaneously vanish.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Matrix Rank, Echelon Forms, and Fundamental Subspaces",
              body: [
                "For an m x n matrix A over the real field R:",
                "**Row Echelon Form (REF):** A matrix is in REF if: (1) all zero rows are at the bottom, (2) the leading entry of each non-zero row is strictly to the right of the leading entry of the row above it.",
                "**Rank:** The rank of A, denoted rho(A) or Rank(A), is the maximum number of linearly independent row vectors (or column vectors). Rank(A) <= min(m, n).",
                "**Rank-Nullity Theorem:** For an m x n matrix representing linear transformation T: R^n -> R^m, dim(Col(A)) + dim(Null(A)) = n, i.e., Rank(A) + Nullity(A) = n.",
                "**System of Linear Equations AX = B:**",
                "- Augmented matrix: [A | B] of dimension m x (n + 1).",
                "- Rouché-Capelli Theorem:",
                "  1. Rank(A) < Rank([A | B]): System is INCONSISTENT (0 solutions, hyperplanes never intersect).",
                "  2. Rank(A) = Rank([A | B]) = n: System is CONSISTENT with UNIQUE solution.",
                "  3. Rank(A) = Rank([A | B]) = r < n: System is CONSISTENT with INFINITELY MANY solutions parameterized by (n - r) free variables.",
                "**LU Decomposition:** A matrix A can be factored as A = L * U, where L is a unit lower triangular matrix (diagonal elements = 1) and U is an upper triangular matrix.",
                "To solve AX = B using LU: first solve LY = B via forward substitution (O(n^2)), then solve UX = Y via backward substitution (O(n^2)).",
              ],
              callout: {
                kind: "gate-tip",
                title: "LU Decomposition Feasibility Condition",
                message:
                  "A square matrix A admits an LU decomposition without row permutations (Gaussian elimination without partial pivoting) if and only if all of its leading principal submatrices A_k (for k = 1, 2, ..., n-1) are non-singular (Det(A_k) != 0).",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Parametric Consistency of Linear Systems",
              weightage: "2 Marks (Compulsory GATE Pattern)",
              trap: "Students frequently confuse the condition for no solution with infinite solutions. For infinite solutions, the entire row in the augmented matrix including RHS must reduce to 0 = 0.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "Consider the linear system:",
                "  x + 2y + 3z = 5",
                "  x + 3y + 5z = 8",
                "  2x + 5y + a*z = b",
                "Determine the values of a and b such that the system has (i) a unique solution, (ii) infinitely many solutions, and (iii) no solution.",
                "Step 1: Write Augmented Matrix [A | B]:",
                "  [ 1  2  3 | 5 ]",
                "  [ 1  3  5 | 8 ]",
                "  [ 2  5  a | b ]",
                "Step 2: Eliminate x from Row 2 and Row 3 (R2 -> R2 - R1, R3 -> R3 - 2*R1):",
                "  R2: [ 0  (3-2)  (5-3) | (8-5) ] = [ 0  1  2 | 3 ]",
                "  R3: [ 0  (5-4)  (a-6) | (b-10) ] = [ 0  1  a-6 | b-10 ]",
                "Step 3: Eliminate y from Row 3 (R3 -> R3 - R2):",
                "  R3: [ 0  (1-1)  (a-6-2) | (b-10-3) ] = [ 0  0  a-8 | b-13 ]",
                "Resulting Upper Triangular Augmented Matrix:",
                "  [ 1  2   3  |  5  ]",
                "  [ 0  1   2  |  3  ]",
                "  [ 0  0  a-8 | b-13 ]",
                "Step 4: Analyze cases based on Rouché-Capelli Theorem:",
                "  - Case 1 (Unique Solution): Rank(A) = 3 = n. This requires a - 8 != 0 => a != 8. (b can be any real number).",
                "  - Case 2 (Infinitely Many Solutions): Rank(A) = Rank([A|B]) < 3. Both third row entries must vanish: a - 8 = 0 and b - 13 = 0 => a = 8 and b = 13. (Free variable = 3 - 2 = 1).",
                "  - Case 3 (No Solution / Inconsistent): Rank(A) = 2 while Rank([A|B]) = 3. This requires a - 8 = 0 and b - 13 != 0 => a = 8 and b != 13 (giving 0*z = non-zero, impossible).",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Introduction to Linear Algebra (5th Edition)",
                  authors: "Gilbert Strang",
                  year: "2016",
                  publisher: "Wellesley-Cambridge Press",
                  relevance: "Chapters 1-3 provide the definitive geometric treatment of four fundamental subspaces, row operations, and LU decomposition.",
                },
                {
                  title: "Higher Engineering Mathematics (44th Edition)",
                  authors: "B.S. Grewal",
                  year: "2017",
                  publisher: "Khanna Publishers",
                  relevance: "Chapter 2 covers rank, consistency of linear systems, and canonical forms with extensive solved engineering problems.",
                },
              ],
            },
          ],
        },
        {
          id: "eigenvalues-eigenvectors-and-cayley-hamilton",
          title: "Eigenvalues, Eigenvectors & Cayley-Hamilton Theorem",
          slug: "eigenvalues-eigenvectors-and-cayley-hamilton",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Characteristic polynomials, eigenspaces, algebraic vs geometric multiplicity, and matrix powers.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Sum of eigenvalues equals Trace(A); Product of eigenvalues equals Det(A). Every square matrix satisfies its own characteristic equation: P(A) = 0.",
            keyFormulasAndRules: [
              "Characteristic Equation: Det(A - lambda * I) = 0.",
              "Spectral Invariants: Sum_{i=1}^n lambda_i = Trace(A); Prod_{i=1}^n lambda_i = Det(A).",
              "Eigenvalue Transformation Properties:",
              "  - If A has eigenvalue lambda, then A^k has eigenvalue lambda^k.",
              "  - A + c*I has eigenvalue lambda + c.",
              "  - A^{-1} has eigenvalue 1/lambda (if Det(A) != 0).",
              "  - A^T has identical eigenvalues to A.",
              "Multiplicity: Algebraic Multiplicity (AM) = multiplicity of root lambda in char poly. Geometric Multiplicity (GM) = dimension of Null(A - lambda*I) = n - Rank(A - lambda*I). 1 <= GM <= AM.",
              "Diagonalizability: An n x n matrix is diagonalizable iff GM = AM for all eigenvalues (or iff A has n linearly independent eigenvectors).",
              "Special Matrices:",
              "  - Symmetric matrix (A = A^T): All eigenvalues are strictly REAL; eigenvectors corresponding to distinct eigenvalues are mutually orthogonal.",
              "  - Skew-symmetric (A = -A^T): Eigenvalues are either 0 or purely imaginary.",
              "  - Orthogonal (A^T * A = I): Absolute magnitude of every eigenvalue is 1 (|lambda| = 1).",
              "  - Idempotent (A^2 = A): Eigenvalues can only be 0 or 1.",
              "  - Nilpotent (A^k = 0): All eigenvalues are identically 0.",
            ],
            examPitfalls: [
              "Eigenvectors corresponding to the same eigenvalue are not unique; any non-zero scalar multiple is also an eigenvector.",
              "For Cayley-Hamilton, do not substitute lambda = A and forget the identity matrix on the constant term: lambda^2 - 5*lambda + 6 = 0 becomes A^2 - 5A + 6I = 0 (NOT 6).",
              "If GM < AM for even one eigenvalue, the matrix is defective and CANNOT be diagonalized.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Eigenspaces, Characteristic Polynomials, and Invariants",
              body: [
                "For an n x n real or complex matrix A:",
                "**Definition:** A non-zero vector x in C^n is an eigenvector of A with associated eigenvalue lambda in C if:",
                "  A * x = lambda * x  <=>  (A - lambda * I) * x = 0",
                "Since x != 0, the matrix (A - lambda * I) must be singular, meaning:",
                "  p(lambda) = Det(A - lambda * I) = 0  (Characteristic Equation)",
                "**Cayley-Hamilton Theorem:** Every square matrix satisfies its own characteristic equation. That is, if p(lambda) = lambda^n + c_{n-1}*lambda^{n-1} + ... + c_1*lambda + c_0 = 0, then:",
                "  p(A) = A^n + c_{n-1}*A^{n-1} + ... + c_1*A + c_0*I = 0",
                "**Applications of Cayley-Hamilton:**",
                "1. Expressing high powers of A (e.g., A^100) as a polynomial in A of degree at most n - 1.",
                "2. Computing matrix inverse: If c_0 = (-1)^n * Det(A) != 0, then multiplying p(A) = 0 by A^{-1} gives:",
                "   A^{-1} = (-1 / c_0) * [ A^{n-1} + c_{n-1}*A^{n-2} + ... + c_1*I ]",
              ],
              callout: {
                kind: "gate-tip",
                title: "Trace & Determinant Shortcut for 2x2 and 3x3 Matrices",
                message:
                  "For a 2x2 matrix: lambda^2 - Trace(A)*lambda + Det(A) = 0. Always check the two invariant constraints first: lambda_1 + lambda_2 = a_11 + a_22 and lambda_1 * lambda_2 = a_11*a_22 - a_12*a_21. This often eliminates 3 out of 4 multiple-choice options immediately.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Matrix Inverse and Powers via Cayley-Hamilton",
              weightage: "2 Marks (GATE CS)",
              trap: "When applying Cayley-Hamilton to find A^{-1}, remember that the constant term c_0 becomes c_0 * A^{-1}, not c_0 * I.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "Let A = [ [ 1, 2 ], [ 3, 2 ] ].",
                "(a) Find the eigenvalues of A.",
                "(b) Express A^4 as a linear combination of A and I using the Cayley-Hamilton theorem.",
                "Step 1: Compute Characteristic Equation:",
                "  Trace(A) = 1 + 2 = 3",
                "  Det(A) = (1)(2) - (2)(3) = 2 - 6 = -4",
                "  Char Eq: lambda^2 - Trace(A)*lambda + Det(A) = 0",
                "  lambda^2 - 3*lambda - 4 = 0",
                "  (lambda - 4)(lambda + 1) = 0 => lambda_1 = 4, lambda_2 = -1.",
                "Step 2: Apply Cayley-Hamilton Theorem:",
                "  A^2 - 3A - 4I = 0  =>  A^2 = 3A + 4I",
                "Step 3: Compute higher powers recursively:",
                "  A^3 = A * A^2 = A(3A + 4I) = 3A^2 + 4A",
                "  Substitute A^2 = 3A + 4I:",
                "  A^3 = 3(3A + 4I) + 4A = 9A + 12I + 4A = 13A + 12I",
                "  A^4 = A * A^3 = A(13A + 12I) = 13A^2 + 12A",
                "  Substitute A^2 = 3A + 4I:",
                "  A^4 = 13(3A + 4I) + 12A = 39A + 52I + 12A = 51A + 52I",
                "Verification via Division Algorithm:",
                "  Dividing lambda^4 by lambda^2 - 3*lambda - 4:",
                "  lambda^4 = (lambda^2 - 3*lambda - 4)(lambda^2 + 3*lambda + 13) + (51*lambda + 52).",
                "  Since p(A) = 0, A^4 = 51A + 52I. Verified perfectly.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Linear Algebra and Its Applications (5th Edition)",
                  authors: "David C. Lay, Steven R. Lay, Judi J. McDonald",
                  year: "2015",
                  publisher: "Pearson",
                  relevance: "Chapter 5 covers eigenvalues, eigenvectors, characteristic equations, and diagonal matrix representations.",
                },
                {
                  title: "Matrix Analysis (2nd Edition)",
                  authors: "Roger A. Horn, Charles R. Johnson",
                  year: "2012",
                  publisher: "Cambridge University Press",
                  relevance: "Comprehensive reference on the Cayley-Hamilton theorem, Jordan canonical forms, and spectral theory.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: DIFFERENTIAL CALCULUS — LIMITS & MEAN VALUE THEOREMS
    // =========================================================================
    {
      id: "math-module-2-differential-calculus",
      title: "Module 2: Differential Calculus & Mean Value Theorems",
      slug: "differential-calculus",
      description: "Limits, indeterminate forms, continuity, differentiability, Rolle's, Lagrange's, Cauchy's Mean Value Theorems, and Taylor series.",
      order: 2,
      lessons: [
        {
          id: "limits-calculus-and-optimization",
          title: "Limits, Indeterminate Forms, Continuity & Differentiability",
          slug: "limits-calculus-and-optimization",
          order: 1,
          estimatedMinutes: 28,
          tagline: "L'Hôpital's rule, 1^infinity exponential identities, left/right limits, and smoothness conditions.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "For indeterminate form 1^infinity: lim [f(x)]^{g(x)} = exp( lim [f(x) - 1] * g(x) ). Differentiability at c implies continuity at c, but continuity does NOT imply differentiability.",
            keyFormulasAndRules: [
              "Seven Indeterminate Forms: 0/0, infinity/infinity, 0 * infinity, infinity - infinity, 1^infinity, 0^0, infinity^0.",
              "L'Hôpital's Rule: If lim f(x)/g(x) is 0/0 or +/-inf/inf, then lim f(x)/g(x) = lim f'(x)/g'(x) provided the derivative limit exists.",
              "Standard Limits (as x -> 0):",
              "  - lim (sin x) / x = 1; lim (tan x) / x = 1; lim (1 - cos x) / x^2 = 1/2.",
              "  - lim (e^x - 1) / x = 1; lim (ln(1 + x)) / x = 1; lim ((1 + x)^n - 1) / x = n.",
              "Continuity at x = c: lim_{x -> c^-} f(x) = lim_{x -> c^+} f(x) = f(c).",
              "Differentiability at x = c: Left Hand Derivative (LHD) = Right Hand Derivative (RHD) = finite value.",
              "  LHD = lim_{h -> 0^+} [f(c) - f(c - h)] / h; RHD = lim_{h -> 0^+} [f(c + h) - f(c)] / h.",
              "Sharp Turn / Corner / Cusp: A function with a sharp corner (like |x| at x = 0) is continuous but NOT differentiable.",
            ],
            examPitfalls: [
              "Do not apply L'Hôpital's rule if the quotient is NOT in 0/0 or inf/inf form. For example, lim_{x->0} (cos x) / (1 + x) = 1/1 = 1; applying L'Hôpital gives (-sin 0)/1 = 0, which is incorrect.",
              "Always check both LHD and RHD from first principles at piecewise junction points; do not just differentiate the formulas without verifying continuity first.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Formal Limits, Indeterminate Forms, and Smoothness",
              body: [
                "**Rigorous Definition of Limit:** lim_{x -> c} f(x) = L means for every epsilon > 0, there exists delta > 0 such that 0 < |x - c| < delta implies |f(x) - L| < epsilon.",
                "**Evaluation Strategies for Indeterminate Forms:**",
                "1. Algebraic manipulation / Rationalization: multiply by conjugate.",
                "2. Standard Series Expansions: e^x = 1 + x + x^2/2! + ..., sin x = x - x^3/3! + ..., cos x = 1 - x^2/2! + ...",
                "3. Logarithmic Transformation for Power Forms (1^inf, 0^0, inf^0): Let y = [f(x)]^{g(x)}, then ln y = g(x) * ln f(x). Evaluate lim ln y = L, then lim y = e^L.",
                "**Continuity & Differentiability Hierarchy:**",
                "- Differentiable at c => Continuous at c.",
                "- Counterexample to converse: f(x) = |x| at x = 0. Continuous (lim = 0 = f(0)), but LHD = -1 != RHD = +1, so not differentiable.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Mastering the 1^infinity Shortcut",
                message:
                  "If lim f(x) = 1 and lim g(x) = infinity, then lim [f(x)]^{g(x)} = e^{lim g(x) * [f(x) - 1]}. This single identity solves over 80% of GATE power-limit questions in under 60 seconds.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: 1^infinity Indeterminate Form & Continuity Junction",
              weightage: "2 Marks (GATE CS)",
              trap: "Students often forget to take exp() of the final inner limit when resolving 1^infinity forms.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "Evaluate L = lim_{x -> 0} ( (sin x) / x )^{1 / x^2}.",
                "Step 1: Check indeterminate form:",
                "  As x -> 0, (sin x)/x -> 1, and 1/x^2 -> +infinity. Form is 1^infinity.",
                "Step 2: Apply exponential formula L = exp( lim_{x -> 0} [ (sin x)/x - 1 ] * (1/x^2) ):",
                "  Inner limit K = lim_{x -> 0} (sin x - x) / x^3.",
                "Step 3: Evaluate K using Taylor expansion:",
                "  sin x = x - x^3 / 3! + x^5 / 5! - ... = x - x^3 / 6 + O(x^5)",
                "  sin x - x = -x^3 / 6 + O(x^5)",
                "  K = lim_{x -> 0} [ -x^3 / 6 ] / x^3 = -1/6.",
                "Step 4: Exponentiate to obtain final limit:",
                "  L = e^K = e^{-1/6} = 1 / e^{1/6}.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Thomas' Calculus (14th Edition)",
                  authors: "Joel R. Hass, Christopher E. Heil, Maurice D. Weir",
                  year: "2018",
                  publisher: "Pearson",
                  relevance: "Chapters 2 and 3 provide the gold-standard treatment of limit proofs, continuity theorems, and differential mechanics.",
                },
              ],
            },
          ],
        },
        {
          id: "mean-value-theorems-and-taylor-series",
          title: "Mean Value Theorems & Taylor-Maclaurin Series",
          slug: "mean-value-theorems-and-taylor-series",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Rolle's, Lagrange's, Cauchy's MVT, Taylor polynomial approximations, and remainder formulas.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Lagrange MVT: f'(c) = [f(b) - f(a)] / (b - a) for some c in (a, b). Rolle's theorem is the special case where f(a) = f(b) => f'(c) = 0.",
            keyFormulasAndRules: [
              "Rolle's Theorem: If f is (1) continuous on [a, b], (2) differentiable on (a, b), and (3) f(a) = f(b), then there exists at least one c in (a, b) such that f'(c) = 0.",
              "Lagrange's Mean Value Theorem (LMVT): If f is continuous on [a, b] and differentiable on (a, b), there exists c in (a, b) such that f'(c) = [f(b) - f(a)] / (b - a).",
              "Cauchy's Mean Value Theorem: If f and g are continuous on [a, b] and differentiable on (a, b) with g'(x) != 0 on (a, b), then [f(b) - f(a)] / [g(b) - g(a)] = f'(c) / g'(c) for some c in (a, b).",
              "Taylor's Theorem with Lagrange Remainder: f(x) = Sum_{k=0}^n [f^{(k)}(a) / k!] * (x - a)^k + R_n(x), where R_n(x) = [f^{(n+1)}(c) / (n+1)!] * (x - a)^{n+1} for c between a and x.",
              "Maclaurin Series (Taylor series centered at a = 0):",
              "  - 1 / (1 - x) = 1 + x + x^2 + x^3 + ... for |x| < 1.",
              "  - ln(1 + x) = x - x^2/2 + x^3/3 - x^4/4 + ... for -1 < x <= 1.",
            ],
            examPitfalls: [
              "Verify the open vs closed interval condition: continuity is required on CLOSED [a, b], but differentiability is only required on OPEN (a, b).",
              "The intermediate point c MUST lie strictly strictly inside (a, b); c cannot equal the endpoints a or b.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Mean Value Theorems and Polynomial Approximations",
              body: [
                "Mean Value Theorems connect average rate of change over an interval to instantaneous rate of change at an interior point.",
                "**Geometric Meaning of LMVT:** The secant line connecting (a, f(a)) and (b, f(b)) is parallel to the tangent line to the curve at some interior point (c, f(c)).",
                "**Root Isolation Corollary of Rolle's Theorem:** Between any two real roots of a differentiable function f(x) = 0, there exists at least one real root of f'(x) = 0. Therefore, if f'(x) has at most k real roots, f(x) can have at most k + 1 real roots.",
                "**Taylor Series Expansion:** Represents smooth functions as infinite polynomials:",
                "  f(x) = f(a) + f'(a)(x - a) + [f''(a) / 2!](x - a)^2 + ... + [f^{(n)}(a) / n!](x - a)^n + ...",
              ],
              callout: {
                kind: "gate-tip",
                title: "Checking Boundedness of Derivatives via LMVT",
                message:
                  "If |f'(x)| <= M for all x in [a, b], LMVT guarantees |f(b) - f(a)| <= M * |b - a|. GATE frequently tests this inequality to bound function values without integrating.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Finding the Point 'c' in LMVT",
              weightage: "1 to 2 Marks (GATE Pattern)",
              trap: "If multiple roots for c arise, discard any values outside the open interval (a, b).",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "Verify Lagrange's Mean Value Theorem for f(x) = x^3 - 3x on the interval [0, 2], and find the value of c in (0, 2) that satisfies the theorem.",
                "Step 1: Verify hypotheses:",
                "  f(x) is a polynomial, hence continuous on [0, 2] and differentiable on (0, 2).",
                "Step 2: Compute f(a), f(b), and the average slope:",
                "  f(0) = 0^3 - 3(0) = 0",
                "  f(2) = 2^3 - 3(2) = 8 - 6 = 2",
                "  Average rate of change = [f(2) - f(0)] / (2 - 0) = [2 - 0] / 2 = 1.",
                "Step 3: Differentiate f(x) and equate f'(c) to average slope:",
                "  f'(x) = 3x^2 - 3",
                "  f'(c) = 3c^2 - 3 = 1",
                "  3c^2 = 4  =>  c^2 = 4/3  =>  c = +/- 2 / sqrt(3).",
                "Step 4: Check domain restriction c in (0, 2):",
                "  c = +2 / sqrt(3) ≈ 2 / 1.732 ≈ 1.155 in (0, 2).",
                "  c = -2 / sqrt(3) is rejected since -1.155 is not in (0, 2).",
                "Conclusion: c = 2 / sqrt(3).",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Principles of Mathematical Analysis (3rd Edition)",
                  authors: "Walter Rudin",
                  year: "1976",
                  publisher: "McGraw-Hill",
                  relevance: "Chapter 5 provides rigorous proofs of the Mean Value Theorem, Cauchy's generalization, and Taylor's theorem with remainder.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: OPTIMIZATION & INTEGRAL CALCULUS
    // =========================================================================
    {
      id: "math-module-3-optimization-and-integrals",
      title: "Module 3: Maxima-Minima & Definite/Improper Integrals",
      slug: "optimization-and-integrals",
      description: "Critical points, single and multivariable extrema, Hessian discriminant test, definite integrals, and improper integral convergence.",
      order: 3,
      lessons: [
        {
          id: "single-and-multivariable-maxima-minima",
          title: "Single & Multivariable Maxima-Minima & Saddle Points",
          slug: "single-and-multivariable-maxima-minima",
          order: 1,
          estimatedMinutes: 30,
          tagline: "First/second derivative tests, Hessian matrix determinant test D = f_xx * f_yy - (f_xy)^2.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "For f(x, y) at critical point (a, b) where grad f = 0, let D = f_xx * f_yy - (f_xy)^2. If D > 0 and f_xx < 0 => Local Max; if D > 0 and f_xx > 0 => Local Min; if D < 0 => Saddle Point.",
            keyFormulasAndRules: [
              "Single Variable Extrema: Critical point c has f'(c) = 0 or f'(c) undefined.",
              "  - Second Derivative Test: f''(c) < 0 => Local Max; f''(c) > 0 => Local Min; f''(c) = 0 => Test inconclusive (examine sign change of f').",
              "Multivariable Extrema (Two Variables f(x, y)):",
              "  - Necessary condition for interior local extremum: grad f = (partial f / partial x, partial f / partial y) = (0, 0).",
              "  - Second Partials Discriminant D = f_xx(a, b) * f_yy(a, b) - [f_xy(a, b)]^2.",
              "  - Case 1: D > 0 and f_xx(a, b) > 0 => Local Minimum.",
              "  - Case 2: D > 0 and f_xx(a, b) < 0 => Local Maximum.",
              "  - Case 3: D < 0 => Saddle Point (neither max nor min; minimum in one direction, maximum in another).",
              "  - Case 4: D = 0 => Test is inconclusive.",
              "Global Extrema on Compact Domain: Evaluate all interior critical points PLUS the boundary points using parameterization or Lagrange multipliers.",
            ],
            examPitfalls: [
              "If D < 0, it is ALWAYS a saddle point, regardless of the sign of f_xx or f_yy.",
              "Do not forget to test endpoints when optimizing on a closed interval [a, b]. The global maximum can occur at an endpoint where f'(x) != 0.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Optimization Theory in One and Multiple Dimensions",
              body: [
                "Optimization is fundamental across algorithm design, machine learning cost functions, and computer systems engineering.",
                "**Stationary / Critical Points:** Points where the gradient vector vanishes: nabla f(x_1, ..., x_n) = 0.",
                "**Hessian Matrix:** The matrix of second-order partial derivatives:",
                "  H = [ [ f_xx, f_xy ], [ f_yx, f_yy ] ]",
                "By Clairaut's Theorem (Schwarz's Theorem), mixed partials are equal (f_xy = f_yx) whenever second derivatives are continuous.",
                "- Det(H) = D = f_xx * f_yy - (f_xy)^2.",
                "- If H is positive definite (eigenvalues > 0, D > 0, f_xx > 0) => strict local minimum.",
                "- If H is negative definite (eigenvalues < 0, D > 0, f_xx < 0) => strict local maximum.",
                "- If H is indefinite (eigenvalues of opposite signs, D < 0) => saddle point.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Recognizing Saddle Points Instantly",
                message:
                  "For f(x, y) = x^2 - y^2 at (0, 0): f_xx = 2, f_yy = -2, f_xy = 0 => D = -4 < 0. Along the x-axis, f(x, 0) = x^2 (minimum at 0). Along the y-axis, f(0, y) = -y^2 (maximum at 0). It is a classic saddle point.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Multivariable Critical Point Classification",
              weightage: "2 Marks (GATE CS Pattern)",
              trap: "Ensure you find all pairs of (x, y) that simultaneously satisfy both partial equations f_x = 0 and f_y = 0.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "Find and classify all critical points of the function f(x, y) = x^3 + y^3 - 3xy.",
                "Step 1: Compute first partial derivatives and set to zero:",
                "  f_x = 3x^2 - 3y = 0  =>  y = x^2",
                "  f_y = 3y^2 - 3x = 0  =>  x = y^2",
                "Step 2: Solve the simultaneous system:",
                "  Substitute y = x^2 into x = y^2:",
                "  x = (x^2)^2 = x^4  =>  x^4 - x = 0  =>  x(x^3 - 1) = 0.",
                "  Real solutions for x: x = 0 or x = 1.",
                "  - If x = 0 => y = 0^2 = 0. Point P1 = (0, 0).",
                "  - If x = 1 => y = 1^2 = 1. Point P2 = (1, 1).",
                "Step 3: Compute second partial derivatives:",
                "  f_xx = 6x,   f_yy = 6y,   f_xy = -3.",
                "  Discriminant D(x, y) = f_xx * f_yy - (f_xy)^2 = (6x)(6y) - (-3)^2 = 36xy - 9.",
                "Step 4: Classify each critical point:",
                "  - At P1(0, 0): D = 36(0)(0) - 9 = -9 < 0.",
                "    Since D < 0, (0, 0) is a SADDLE POINT.",
                "  - At P2(1, 1): D = 36(1)(1) - 9 = 27 > 0.",
                "    f_xx(1, 1) = 6(1) = 6 > 0.",
                "    Since D > 0 and f_xx > 0, (1, 1) is a LOCAL MINIMUM.",
                "    Local minimum value: f(1, 1) = 1^3 + 1^3 - 3(1)(1) = 2 - 3 = -1.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Calculus: Early Transcendentals (8th Edition)",
                  authors: "James Stewart",
                  year: "2015",
                  publisher: "Cengage Learning",
                  relevance: "Chapter 14 provides clear geometric illustrations of multivariable extrema, saddle surfaces, and Lagrange multipliers.",
                },
              ],
            },
          ],
        },
        {
          id: "definite-and-improper-integrals",
          title: "Definite & Improper Integrals, Symmetry & Gamma Function",
          slug: "definite-and-improper-integrals",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Properties of definite integrals, Leibniz integral rule, Gamma function Gamma(n), and improper convergence.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "King's Property: integral_a^b f(x) dx = integral_a^b f(a + b - x) dx. Gamma Function: Gamma(n) = (n - 1)! for positive integers, and Gamma(1/2) = sqrt(pi).",
            keyFormulasAndRules: [
              "King's Property (Reflection Formula): integral_a^b f(x) dx = integral_a^b f(a + b - x) dx.",
              "Symmetry on [-a, a]: integral_{-a}^a f(x) dx = 0 if f is odd (f(-x) = -f(x)); 2 * integral_0^a f(x) dx if f is even (f(-x) = f(x)).",
              "Leibniz Integral Rule (Differentiation under the Integral Sign):",
              "  d/dx [ integral_{u(x)}^{v(x)} f(x, t) dt ] = f(x, v(x)) * v'(x) - f(x, u(x)) * u'(x) + integral_{u(x)}^{v(x)} [partial f / partial x] dt.",
              "Gamma Function Definition: Gamma(z) = integral_0^infinity t^{z - 1} * e^{-t} dt for Re(z) > 0.",
              "  - Recurrence: Gamma(z + 1) = z * Gamma(z).",
              "  - For integer n >= 1: Gamma(n) = (n - 1)!.",
              "  - Special Value: Gamma(1/2) = sqrt(pi).",
              "Improper Integral Convergence:",
              "  - integral_1^infinity 1 / x^p dx converges iff p > 1.",
              "  - integral_0^1 1 / x^p dx converges iff p < 1.",
            ],
            examPitfalls: [
              "When using Leibniz rule, remember the chain rule factors v'(x) and u'(x). Forgetting to multiply by the derivative of the integration limits is the most frequent error.",
              "Do not integrate across an infinite discontinuity without splitting the integral into improper limits.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Advanced Integration Techniques in Engineering Mathematics",
              body: [
                "Definite integration in GATE CS frequently tests clever analytical symmetry properties rather than tedious anti-differentiation.",
                "**King's Rule Application:**",
                "To evaluate I = integral_a^b [ f(x) / (f(x) + f(a + b - x)) ] dx:",
                "By King's property, replacing x with a + b - x yields the exact same integral I.",
                "Adding the two equations: 2I = integral_a^b 1 dx = b - a  =>  I = (b - a) / 2.",
                "This instantly evaluates integrals like integral_0^{pi/2} [ sin^n x / (sin^n x + cos^n x) ] dx = (pi/2 - 0) / 2 = pi / 4.",
                "**Leibniz Rule:** Allows differentiating integrals whose limits depend on a variable. Widely used in probability density functions and cumulative distribution computations.",
                "**Gamma and Beta Functions:** Essential tools for evaluating integrals of exponential decay and power laws arising in statistics.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Instant Answer via King's Rule",
                message:
                  "Whenever the integrand has the form numerator / (numerator + complementary_term) over [0, pi/2] (like sin x / (sin x + cos x) or sqrt(tan x) / (1 + sqrt(tan x))), the answer is always half the interval length: (pi/2) / 2 = pi/4.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Leibniz Differentiation Under Integral Sign",
              weightage: "2 Marks (GATE CS)",
              trap: "Remember to evaluate the integrand at the upper limit and multiply by the derivative of that upper limit.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "Let F(x) = integral_0^{x^2} sqrt(1 + t^3) dt. Find F'(1).",
                "Step 1: Identify limits and integrand for Leibniz Rule:",
                "  u(x) = 0 (constant lower limit => u'(x) = 0)",
                "  v(x) = x^2 (upper limit => v'(x) = 2x)",
                "  f(t) = sqrt(1 + t^3)",
                "Step 2: Apply Leibniz Rule:",
                "  F'(x) = f(v(x)) * v'(x) - f(u(x)) * u'(x)",
                "  F'(x) = sqrt(1 + (x^2)^3) * (2x) - sqrt(1 + 0^3) * 0",
                "  F'(x) = 2x * sqrt(1 + x^6)",
                "Step 3: Evaluate at x = 1:",
                "  F'(1) = 2(1) * sqrt(1 + 1^6) = 2 * sqrt(2).",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Advanced Engineering Mathematics (10th Edition)",
                  authors: "Erwin Kreyszig",
                  year: "2011",
                  publisher: "John Wiley & Sons",
                  relevance: "Chapter 10 provides comprehensive coverage of special functions (Gamma, Beta) and definite integral properties.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: PROBABILITY THEORY & RANDOM VARIABLES
    // =========================================================================
    {
      id: "math-module-4-probability-theory",
      title: "Module 4: Probability Foundations & Random Variables",
      slug: "probability-theory",
      description: "Sample spaces, conditional probability, Bayes' Theorem, discrete/continuous random variables, expectation, variance, and covariance.",
      order: 4,
      lessons: [
        {
          id: "bayes-theorem-and-distributions",
          title: "Conditional Probability, Total Probability & Bayes' Theorem",
          slug: "bayes-theorem-and-distributions",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Prior to posterior updates, base-rate fallacy, partition of sample spaces, and conditional independence.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Bayes' Theorem: P(A_k | B) = [ P(B | A_k) * P(A_k) ] / [ Sum_i P(B | A_i) * P(A_i) ]. Always calculate the denominator via Law of Total Probability first.",
            keyFormulasAndRules: [
              "Kolmogorov Probability Axioms: (1) P(E) >= 0; (2) P(S) = 1; (3) P(Union_i E_i) = Sum_i P(E_i) for mutually disjoint events.",
              "Conditional Probability: P(A | B) = P(A intersect B) / P(B), provided P(B) > 0.",
              "Multiplication Rule: P(A intersect B) = P(A | B) * P(B) = P(B | A) * P(A).",
              "Independent Events: A and B are independent iff P(A intersect B) = P(A) * P(B) iff P(A | B) = P(A).",
              "Law of Total Probability: For a partition {A_1, A_2, ..., A_k} of sample space S: P(B) = Sum_{i=1}^k P(B | A_i) * P(A_i).",
              "Bayes' Formula: Inverts causes and effects to compute posterior probability P(Cause | Effect).",
            ],
            examPitfalls: [
              "Mutually exclusive events are NOT independent unless at least one event has probability 0. If P(A) > 0 and P(B) > 0, mutually exclusive implies P(A intersect B) = 0 != P(A)*P(B).",
              "Base Rate Fallacy: In medical testing or spam detection, a test with high accuracy (e.g., 99%) still yields low posterior probability if the condition prevalence is extremely rare.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Formal Probability Framework and Bayesian Inference",
              body: [
                "Probability formalizes quantitative reasoning under uncertainty.",
                "**Sample Space and Events:** A sample space S is the set of all possible outcomes. An event A is a subset of S.",
                "**Partitions:** A family of events {A_1, A_2, ..., A_n} forms a partition of S if:",
                "1. Pairwise disjoint: A_i intersect A_j = empty set for all i != j.",
                "2. Exhaustive: Union_{i=1}^n A_i = S.",
                "**Bayes' Theorem Formulation:**",
                "Let {A_1, ..., A_n} be a partition of S with prior probabilities P(A_i) > 0. For an observed evidence event B with P(B) > 0:",
                "  P(A_k | B) = [ P(B | A_k) * P(A_k) ] / [ Sum_{i=1}^n P(B | A_i) * P(A_i) ]",
                "- P(A_k) is the **prior probability** of hypothesis A_k.",
                "- P(B | A_k) is the **likelihood** of evidence B given A_k.",
                "- The denominator is the **marginal evidence** P(B).",
                "- P(A_k | B) is the **posterior probability** after observing B.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Solving Bayes' Problems via Frequency Trees",
                message:
                  "If algebraic fraction manipulation gets confusing under exam pressure, assume a population of 100,000 individuals and build a two-tier branch tree with exact integer counts. The ratio of (target branch) / (all matching branches) gives the exact posterior probability without decimal errors.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Three-Machine Defect Rate Bayes Analysis",
              weightage: "2 Marks (Compulsory GATE Pattern)",
              trap: "Carefully map which machine produced the defective item vs which machine is being queried in the numerator.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "In a factory, machines M1, M2, and M3 manufacture 30%, 25%, and 45% of total computer memory chips, respectively.",
                "The defective output rates are 2% for M1, 3% for M2, and 1% for M3.",
                "A chip is picked at random and found to be defective. What is the probability that it was manufactured by machine M2?",
                "Step 1: Define events and identify prior probabilities:",
                "  P(M1) = 0.30,   P(M2) = 0.25,   P(M3) = 0.45",
                "  Verify partition: 0.30 + 0.25 + 0.45 = 1.00.",
                "Step 2: Identify conditional defect likelihoods P(D | Mi):",
                "  P(D | M1) = 0.02,   P(D | M2) = 0.03,   P(D | M3) = 0.01.",
                "Step 3: Compute total probability of defect P(D):",
                "  P(D) = P(D|M1)*P(M1) + P(D|M2)*P(M2) + P(D|M3)*P(M3)",
                "  P(D) = (0.02 * 0.30) + (0.03 * 0.25) + (0.01 * 0.45)",
                "  P(D) = 0.0060 + 0.0075 + 0.0045 = 0.0180 (1.8% defect rate overall).",
                "Step 4: Apply Bayes' Formula for P(M2 | D):",
                "  P(M2 | D) = [ P(D | M2) * P(M2) ] / P(D)",
                "  P(M2 | D) = 0.0075 / 0.0180 = 75 / 180 = 5 / 12 ≈ 0.4167 (41.67%).",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "A First Course in Probability (9th Edition)",
                  authors: "Sheldon Ross",
                  year: "2013",
                  publisher: "Pearson",
                  relevance: "Chapter 3 covers conditional probability, independence, Bayes' rule, and odds ratios.",
                },
              ],
            },
          ],
        },
        {
          id: "expectation-variance-and-moments",
          title: "Random Variables, Expectation, Variance & Covariance",
          slug: "expectation-variance-and-moments",
          order: 2,
          estimatedMinutes: 30,
          tagline: "PDF/CDF properties, Linearity of Expectation, Covariance, and Chebyshev's inequality.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Linearity of Expectation E[aX + bY] = a*E[X] + b*E[Y] ALWAYS holds, regardless of dependence. Variance Var(aX + b) = a^2 * Var(X).",
            keyFormulasAndRules: [
              "Cumulative Distribution Function (CDF): F(x) = P(X <= x). F is non-decreasing, F(-inf) = 0, F(+inf) = 1. P(a < X <= b) = F(b) - F(a).",
              "Continuous PDF: f(x) = F'(x) >= 0; integral_{-inf}^{+inf} f(x) dx = 1.",
              "Mathematical Expectation:",
              "  - Discrete: E[X] = Sum x * P(X = x).",
              "  - Continuous: E[X] = integral_{-inf}^{+inf} x * f(x) dx.",
              "Variance Formula: Var(X) = E[X^2] - (E[X])^2.",
              "Variance Scaling: Var(aX + b) = a^2 * Var(X). (Adding a constant b does not change spread!).",
              "Sum Variance: Var(X + Y) = Var(X) + Var(Y) + 2 * Cov(X, Y).",
              "  - If X and Y are independent, Cov(X, Y) = 0 => Var(X + Y) = Var(X) + Var(Y).",
              "Covariance: Cov(X, Y) = E[XY] - E[X]*E[Y].",
              "Correlation Coefficient: rho(X, Y) = Cov(X, Y) / [ sigma_X * sigma_Y ], with -1 <= rho <= +1.",
              "Chebyshev's Inequality: P(|X - mu| >= k * sigma) <= 1 / k^2 for any random variable with finite variance.",
            ],
            examPitfalls: [
              "E[g(X)] != g(E[X]) in general (Jensen's inequality). Specifically, E[X^2] != (E[X])^2 unless Var(X) = 0.",
              "Uncorrelatedness (Cov(X, Y) = 0) does NOT necessarily imply independence. (However, independence DOES imply uncorrelatedness).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Random Variables, Moments, and Joint Distributions",
              body: [
                "A random variable X is a measurable function mapping the sample space S to the real line R.",
                "**Discrete vs Continuous:**",
                "- Discrete: Takes values in a countable set. Characterized by Probability Mass Function (PMF) p(x) = P(X = x).",
                "- Continuous: P(X = c) = 0 for any individual point c. Probability is assigned over intervals via Probability Density Function (PDF) f(x).",
                "**Linearity of Expectation Theorem:**",
                "For any random variables X_1, X_2, ..., X_n and constants c_1, c_2, ..., c_n:",
                "  E[ Sum_{i=1}^n c_i * X_i ] = Sum_{i=1}^n c_i * E[X_i]",
                "This requires NO assumption of independence. This is one of the most powerful problem-solving tools in computer science algorithm analysis and GATE.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Solving Complex Counting via Indicator Random Variables",
                message:
                  "To find the expected number of events that occur, define indicator I_i = 1 if event i occurs, 0 otherwise. Then E[I_i] = P(event i occurs). By Linearity of Expectation, E[Total] = Sum E[I_i] = Sum P(event i occurs). This solves hat-check problems, coupon collectors, and hash collision expectations in 2 lines.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Finding PDF Normalization Constant and Variance",
              weightage: "2 Marks (GATE CS)",
              trap: "Remember to integrate over the valid support interval only, and do not forget to square E[X] when subtracting from E[X^2].",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "A continuous random variable X has probability density function:",
                "  f(x) = c * (2x - x^2) for 0 <= x <= 2, and 0 otherwise.",
                "Find (a) the constant c, (b) E[X], and (c) Var(X).",
                "Step 1: Determine c using the total probability axiom integral f(x) dx = 1:",
                "  integral_0^2 c * (2x - x^2) dx = 1",
                "  c * [ x^2 - x^3 / 3 ]_0^2 = 1",
                "  c * [ 4 - 8/3 ] = c * [ 4/3 ] = 1  =>  c = 3/4.",
                "Step 2: Compute Expectation E[X]:",
                "  E[X] = integral_0^2 x * f(x) dx = (3/4) * integral_0^2 (2x^2 - x^3) dx",
                "  E[X] = (3/4) * [ (2x^3 / 3) - (x^4 / 4) ]_0^2",
                "  E[X] = (3/4) * [ (16/3) - (16/4) ] = (3/4) * [ 16/3 - 4 ] = (3/4) * [ 4/3 ] = 1.",
                "  (Notice f(x) is symmetric around x = 1, so E[X] = 1 by symmetry!).",
                "Step 3: Compute E[X^2]:",
                "  E[X^2] = integral_0^2 x^2 * f(x) dx = (3/4) * integral_0^2 (2x^3 - x^4) dx",
                "  E[X^2] = (3/4) * [ (2x^4 / 4) - (x^5 / 5) ]_0^2",
                "  E[X^2] = (3/4) * [ (32/4) - (32/5) ] = (3/4) * [ 8 - 6.4 ] = (3/4) * (1.6) = 1.2 = 6/5.",
                "Step 4: Compute Variance Var(X):",
                "  Var(X) = E[X^2] - (E[X])^2 = (6/5) - (1)^2 = 1/5 = 0.20.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Introduction to Probability Models (11th Edition)",
                  authors: "Sheldon Ross",
                  year: "2014",
                  publisher: "Academic Press",
                  relevance: "Chapter 2 covers random variables, expectation, variance, conditional distributions, and inequalities.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: STANDARD DISTRIBUTIONS & DESCRIPTIVE STATISTICS
    // =========================================================================
    {
      id: "math-module-5-distributions-and-statistics",
      title: "Module 5: Standard Distributions & Descriptive Statistics",
      slug: "distributions-and-statistics",
      description: "Binomial, Poisson, Uniform, Exponential, Normal distributions, Central Limit Theorem, and descriptive metrics (mean, median, mode, variance).",
      order: 5,
      lessons: [
        {
          id: "discrete-and-continuous-probability-distributions",
          title: "Standard Discrete & Continuous Distributions",
          slug: "discrete-and-continuous-probability-distributions",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Binomial, Poisson approximation, Uniform, Exponential memoryless property, and Normal / Gaussian curve.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Exponential distribution is the unique continuous memoryless distribution: P(X > s + t | X > s) = P(X > t). For Poisson distribution, Mean = Variance = lambda.",
            keyFormulasAndRules: [
              "Binomial Distribution B(n, p): P(X = k) = nCk * p^k * (1 - p)^{n - k}.",
              "  - Mean = n*p,   Variance = n*p*(1 - p).",
              "Poisson Distribution Poi(lambda): P(X = k) = (lambda^k * e^{-lambda}) / k! for k = 0, 1, 2, ...",
              "  - Mean = lambda,   Variance = lambda. (Poisson approximates Binomial when n -> inf, p -> 0, lambda = np).",
              "Continuous Uniform Distribution U(a, b): f(x) = 1 / (b - a) for a <= x <= b.",
              "  - Mean = (a + b) / 2,   Variance = (b - a)^2 / 12.",
              "Exponential Distribution Exp(lambda): f(x) = lambda * e^{-lambda * x} for x >= 0; F(x) = 1 - e^{-lambda * x}.",
              "  - Mean = 1 / lambda,   Variance = 1 / lambda^2.",
              "  - Memoryless Property: P(X > s + t | X > s) = P(X > t).",
              "Normal Distribution N(mu, sigma^2): f(x) = [1 / (sigma * sqrt(2*pi))] * exp( - (x - mu)^2 / (2*sigma^2) ).",
              "  - Standard Normal Variable: Z = (X - mu) / sigma ~ N(0, 1).",
              "  - Empirical Rule: 68.27% within mu +/- 1*sigma, 95.45% within mu +/- 2*sigma, 99.73% within mu +/- 3*sigma.",
            ],
            examPitfalls: [
              "Do not confuse the rate parameter lambda with the mean in the Exponential distribution. If average arrival time is 5 minutes, then mean = 5 => lambda = 1/5 = 0.2 per minute.",
              "For Normal distribution problems, always convert to Z-score before using standard symmetry tables.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Classical Family of Parametric Distributions",
              body: [
                "The GATE CS syllabus tests five standard distribution models thoroughly:",
                "**1. Binomial Distribution:** Models the number of successes in n independent Bernoulli trials with constant success probability p.",
                "**2. Poisson Distribution:** Models the count of rare events occurring independently at a constant average rate lambda in a fixed time/space interval. It is the limiting form of Binomial as n -> infinity, p -> 0, with np = lambda.",
                "**3. Continuous Uniform:** Maximum entropy distribution on a bounded interval [a, b] when no prior information exists.",
                "**4. Exponential Distribution:** Models the waiting time between Poisson arrivals. Unique continuous distribution possessing the memoryless property.",
                "**5. Normal (Gaussian) Distribution:** By the Central Limit Theorem, the sum/mean of many independent random variables approaches a normal distribution regardless of their original distributions.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Poisson Variance Equality Diagnostic",
                message:
                  "If a GATE question states that a discrete count variable has Mean = Variance, immediately recognize it as a Poisson distribution. If Mean > Variance, it is Binomial (np > np(1-p)).",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Exponential Memoryless Property in Server Queueing",
              weightage: "2 Marks (GATE CS)",
              trap: "Using full conditional probability integrals when the memoryless property gives the answer directly.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "The service time of requests at a web server is exponentially distributed with a mean of 4 milliseconds.",
                "A request has already been running for 6 milliseconds without completing.",
                "What is the probability that its total service time exceeds 10 milliseconds?",
                "Step 1: Identify distribution parameters:",
                "  Mean = 1 / lambda = 4 ms  =>  lambda = 1/4 = 0.25 ms^{-1}.",
                "  Let X be the total service time. X ~ Exp(lambda = 0.25).",
                "Step 2: Formulate the conditional probability query:",
                "  We want P(X > 10 | X > 6).",
                "Step 3: Apply the Memoryless Property P(X > s + t | X > s) = P(X > t):",
                "  Here s = 6 and s + t = 10 => t = 4.",
                "  P(X > 10 | X > 6) = P(X > 4).",
                "Step 4: Compute survival function P(X > t) for Exponential distribution:",
                "  P(X > t) = integral_t^infinity lambda * e^{-lambda * x} dx = e^{-lambda * t}.",
                "  P(X > 4) = e^{- (0.25) * 4} = e^{-1} ≈ 0.3679.",
                "Conclusion: The probability that it takes more than 10 ms given it took > 6 ms is exactly 1/e ≈ 36.79%.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Probability and Statistics for Computer Scientists (2nd Edition)",
                  authors: "Michael Baron",
                  year: "2013",
                  publisher: "CRC Press",
                  relevance: "Focused application of Poisson processes, exponential queueing, and Gaussian models in computer systems.",
                },
              ],
            },
          ],
        },
        {
          id: "descriptive-statistics-and-central-limit-theorem",
          title: "Descriptive Statistics, Central Limit Theorem & Dispersion",
          slug: "descriptive-statistics-and-central-limit-theorem",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Mean, median, mode, standard deviation, skewness, sample mean variance, and the Central Limit Theorem.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Central Limit Theorem: For n i.i.d. random variables with mean mu and variance sigma^2, the sample mean X_bar is approximately N(mu, sigma^2 / n) as n -> infinity.",
            keyFormulasAndRules: [
              "Measures of Central Tendency:",
              "  - Sample Mean: x_bar = (1/n) * Sum_{i=1}^n x_i.",
              "  - Median: Middle value of sorted data (50th percentile). Robust against extreme outliers.",
              "  - Mode: Most frequently occurring value in the data set.",
              "Empirical Relationship for Moderately Skewed Distributions: Mean - Mode ≈ 3 * (Mean - Median).",
              "Measures of Dispersion:",
              "  - Sample Variance: s^2 = [1 / (n - 1)] * Sum_{i=1}^n (x_i - x_bar)^2 (Bessel's correction for unbiased estimator).",
              "  - Standard Deviation: s = sqrt(s^2).",
              "  - Coefficient of Variation (CV): CV = (sigma / mu) * 100% (dimensionless relative dispersion).",
              "Central Limit Theorem (CLT):",
              "  - Sample Mean X_bar = (1/n) * Sum_{i=1}^n X_i.",
              "  - E[X_bar] = mu,   Var(X_bar) = sigma^2 / n,   StdDev(X_bar) = sigma / sqrt(n) (Standard Error).",
              "  - Z = [ X_bar - mu ] / [ sigma / sqrt(n) ] ~ N(0, 1) as n -> infinity (typically n >= 30).",
            ],
            examPitfalls: [
              "When applying CLT to the sum S_n = Sum_{i=1}^n X_i, E[S_n] = n*mu, but Var(S_n) = n*sigma^2 (so StdDev is sqrt(n)*sigma, NOT n*sigma).",
              "Do not use n instead of (n - 1) in the denominator when computing unbiased sample variance from sample data.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Descriptive Measures and the Power of the Central Limit Theorem",
              body: [
                "Statistics summarizes empirical observations and quantifies inference precision.",
                "**Comparison of Central Tendency Measures:**",
                "- **Mean:** Mathematically tractable, utilizes all data points, highly sensitive to outliers.",
                "- **Median:** Divides data into equal halves, resilient to outliers (e.g., income, network latency).",
                "- **Mode:** Only measure applicable to categorical/nominal data.",
                "**Skewness:**",
                "- Symmetric (Normal): Mean = Median = Mode.",
                "- Positively Skewed (Right-tailed): Mode < Median < Mean.",
                "- Negatively Skewed (Left-tailed): Mean < Median < Mode.",
                "**The Central Limit Theorem (CLT):**",
                "Regardless of the underlying distribution of the independent and identically distributed (i.i.d.) population (whether uniform, exponential, or skewed):",
                "  The distribution of the standardized sample mean converges to the standard normal distribution as sample size n grows large.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Sum vs Mean in Central Limit Theorem",
                message:
                  "For the sum S_n: S_n ~ N(n*mu, n*sigma^2). For the average X_bar: X_bar ~ N(mu, sigma^2 / n). Always double-check whether the exam question asks for the probability regarding the sum of items or the average of items.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Central Limit Theorem on Packet Transmission",
              weightage: "2 Marks (GATE CS)",
              trap: "Standard error is sigma / sqrt(n), do not divide by n.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "The latency of packets through a router has an unknown distribution with mean mu = 20 microseconds and standard deviation sigma = 8 microseconds.",
                "A sample of 64 packets is observed independently.",
                "Using the Central Limit Theorem, find the probability that the sample mean latency exceeds 21.5 microseconds. (Given: Area under standard normal curve from 0 to Z=1.5 is 0.4332).",
                "Step 1: Identify sample size and parameter values:",
                "  n = 64,   mu = 20,   sigma = 8.",
                "Step 2: Compute mean and standard error of sample mean X_bar:",
                "  E[X_bar] = mu = 20 microseconds.",
                "  sigma_{X_bar} = sigma / sqrt(n) = 8 / sqrt(64) = 8 / 8 = 1.0 microsecond.",
                "Step 3: Calculate the Z-score for X_bar = 21.5:",
                "  Z = (X_bar - mu) / sigma_{X_bar} = (21.5 - 20) / 1.0 = 1.5.",
                "Step 4: Compute probability P(X_bar > 21.5):",
                "  P(X_bar > 21.5) = P(Z > 1.5) = 0.5 - P(0 < Z <= 1.5)",
                "  P(Z > 1.5) = 0.5000 - 0.4332 = 0.0668 (6.68%).",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Mathematical Statistics with Applications (7th Edition)",
                  authors: "Dennis Wackerly, William Mendenhall, Richard L. Scheaffer",
                  year: "2008",
                  publisher: "Cengage Learning",
                  relevance: "Chapter 7 provides the classical mathematical foundation of sampling distributions, unbiased estimators, and the Central Limit Theorem.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
