import { CourseMeta } from "./types";

export const GENERAL_APTITUDE_COURSE: CourseMeta = {
  id: "general-aptitude",
  title: "General Aptitude",
  slug: "general-aptitude",
  subjectSlug: "general-aptitude",
  shortTitle: "Aptitude",
  icon: "🧠",
  color: "bg-amber-400",
  tagline:
    "Master quantitative numerical shortcuts, logical deduction, spatial reasoning, and critical verbal analysis for a mandatory 15 marks in GATE.",
  description:
    "A comprehensive, exam-focused study notebook covering all four pillars of GATE General Aptitude: Quantitative Ability, Analytical Reasoning, Spatial Aptitude, and Verbal Ability. Essential for both GATE CS/IT and GATE Data Science & AI.",
  level: "Undergraduate / GATE CS & DA",
  estimatedHours: 25,
  prerequisites: [
    "High school arithmetic, basic algebra, and elementary geometry",
    "Basic logical reasoning and English comprehension skills",
  ],
  learningOutcomes: [
    "Apply modular arithmetic, remainder theorem, and percentage-ratio shortcuts to solve arithmetic questions in under 90 seconds",
    "Calculate work-rate, pipes and cisterns, and relative speed problems using LCM efficiency units without algebraic overhead",
    "Evaluate permutations, combinations, counting selections, and probability for discrete events",
    "Extract and synthesize data accurately from tables, bar graphs, pie charts, and trend line plots",
    "Analyze formal syllogisms with Venn diagrams and resolve complex seating arrangements and family relationships",
    "Verify 2D/3D spatial rotations, reflections, unfolded cube nets, and paper-folding punch hole patterns",
    "Identify grammatical errors in subject-verb agreement, verb tenses, parallelism, and prepositions",
    "Deconstruct reading comprehension passages, deduce author assumptions, and resolve paragraph jumbles",
  ],
  gateScope: "GATE 2027 common General Aptitude (15 marks)",
  gateBranches: ["cs", "da"],
  gateSyllabusTopics: [
    "Quantitative Aptitude: Data interpretation, numerical computation, percentages, ratios, permutations, combinations, geometry",
    "Analytical Aptitude: Logic, deduction, induction, analogies, sequences and series, seating arrangements",
    "Spatial Aptitude: Transformation of shapes, translation, rotation, mirroring, paper folding, cube nets",
    "Verbal Aptitude: English grammar, vocabulary, sentence completion, reading comprehension, critical reasoning",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: QUANTITATIVE APTITUDE — ARITHMETIC & RATES
    // =========================================================================
    {
      id: "aptitude-module-1-quantitative",
      title: "Module 1: Quantitative Aptitude — Arithmetic & Rates",
      slug: "quantitative-aptitude",
      description:
        "Arithmetic shortcuts, ratios, percentages, profit-loss, mixture alligation, work-rate efficiency, and time-speed-distance.",
      order: 1,
      lessons: [
        {
          id: "numbers-percentages-ratios",
          title: "Number Systems, Percentages & Ratio-Proportions",
          slug: "numbers-percentages-ratios",
          order: 1,
          estimatedMinutes: 28,
          tagline: "Divisibility rules, remainder theorems, successive percentages, profit & loss, and mixture alligation.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Successive percentage change of a% and b% equals (a + b + ab/100)%. Mixture Alligation: (Quantity 1 / Quantity 2) = (Price 2 - Mean) / (Mean - Price 1).",
            keyFormulasAndRules: [
              "Successive % change: Net % = a + b + (a * b) / 100.",
              "Expenditure Invariance: If price increases by r%, consumption must reduce by [r / (100 + r)] * 100% to keep expenditure constant.",
              "Profit & Loss:",
              "  - Profit % = [(SP - CP) / CP] * 100; Loss % = [(CP - SP) / CP] * 100.",
              "  - Marked Price (MP) & Discount (D%): SP = MP * (1 - D / 100).",
              "Mixture Alligation Rule: (Cheaper Quantity / Dearer Quantity) = (Dearer Price - Mean Price) / (Mean Price - Cheaper Price).",
              "Repeated Dilution: If x units are removed from a container of capacity C containing pure liquid and replaced with water n times, remaining pure liquid = C * (1 - x / C)^n.",
              "Remainder Theorems: Remainder of [A * B] / m = ( (A mod m) * (B mod m) ) mod m.",
            ],
            examPitfalls: [
              "Profit percentage is ALWAYS calculated on Cost Price (CP), never on Selling Price (SP), unless explicitly specified.",
              "When combining two ratios A:B = 2:3 and B:C = 4:5, multiply through to match the common term B: A:B:C = (2*4) : (3*4) : (3*5) = 8:12:15.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Core Quantitative Principles for GATE",
              body: [
                "General Aptitude contributes 15 marks out of 100 in every GATE paper (5 questions of 1 mark each and 5 questions of 2 marks each). Scoring 13+ marks is the single highest-ROI strategy for securing a top-500 rank.",
                "**Successive Percentage Changes:** When a quantity is modified by +x% followed by +y%, the net multiplier is (1 + x/100)(1 + y/100) = 1 + (x + y + xy/100)/100. For discounts (-d1% and -d2%), Net Discount = d1 + d2 - (d1 * d2) / 100.",
                "**Rule of Alligation:** When two ingredients of prices C (cheaper) and D (dearer) are mixed to produce a mean price M, the ratio of weights is (Quantity of C) / (Quantity of D) = (D - M) / (M - C).",
                "**Modular Arithmetic & Remainders:** Euler's Totient Theorem: If gcd(a, m) = 1, then a^{phi(m)} = 1 (mod m). For prime p, Fermat's Little Theorem states a^{p-1} = 1 (mod p).",
              ],
              callout: {
                kind: "gate-tip",
                title: "Expenditure Reduction Shortcut",
                message:
                  "If petrol price rises by 25% (+1/4), consumption must fall by (1 / (4 + 1)) = 1/5 = 20% to keep expenditure unchanged. If price rises by 1/n, consumption drops by 1/(n+1). If price falls by 1/n, consumption can rise by 1/(n-1).",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Repeated Dilution & Mixture Ratio",
              weightage: "2 Marks (GATE Standard Pattern)",
              trap: "Do not subtract linear amounts; each removal takes away a mixture containing both wine and water.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "A cask initially contains 80 liters of pure chemical solvent. 16 liters of the solvent are drawn off and replaced with water.",
                "This operation is repeated two more times (total 3 operations).",
                "What is the final quantity of chemical solvent remaining in the cask?",
                "Step 1: Identify container capacity C, withdrawal amount x, and iterations n:",
                "  C = 80 liters,   x = 16 liters,   n = 3.",
                "Step 2: Compute fractional dilution factor per operation:",
                "  Fraction remaining = (1 - x / C) = (1 - 16 / 80) = (1 - 1/5) = 4/5 = 0.8.",
                "Step 3: Apply the repeated dilution formula:",
                "  Solvent remaining = C * (1 - x / C)^n = 80 * (4/5)^3",
                "  Solvent remaining = 80 * (64 / 125) = (80 / 125) * 64 = (16 / 25) * 64",
                "  Solvent remaining = 1024 / 25 = 40.96 liters.",
                "Conclusion: 40.96 liters of chemical solvent remain, and (80 - 40.96) = 39.04 liters of water are present.",
              ],
            },
            {
              type: "resources",
              heading: "3. Standard References & Practice Sets",
              sources: [
                {
                  title: "Quantitative Aptitude for Competitive Examinations",
                  authors: "R.S. Aggarwal",
                  year: "2022",
                  publisher: "S. Chand Publishing",
                  relevance: "Standard compendium of arithmetic problem types and shortcut formulas.",
                },
              ],
            },
          ],
        },
        {
          id: "work-rate-and-speed-time-distance",
          title: "Work-Rate, Pipes & Cisterns, Relative Speed & Motion",
          slug: "work-rate-and-speed-time-distance",
          order: 2,
          estimatedMinutes: 28,
          tagline: "LCM efficiency method, negative work of drainage pipes, relative velocity, trains, and river boats.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Assign total capacity/distance equal to the LCM of the given times to convert rates into integer daily/hourly efficiencies.",
            keyFormulasAndRules: [
              "LCM Efficiency Method for Work:",
              "  - Total Work = LCM(time_1, time_2, ..., time_k).",
              "  - Daily Efficiency = Total Work / Individual Time.",
              "  - Combined Time = Total Work / Sum of Efficiencies.",
              "Negative Work (Drainage / Leaks): Assign negative efficiency to empty pipes: Net Efficiency = Inflow - Outflow.",
              "Speed, Time & Distance: Distance = Speed * Time.",
              "  - Unit Conversion: 1 km/h = 5/18 m/s; 1 m/s = 18/5 km/h.",
              "Harmonic Mean for Average Speed: When distances are equal, V_avg = 2 * v1 * v2 / (v1 + v2).",
              "Relative Speed:",
              "  - Opposite Directions: V_rel = v1 + v2 (closing speed).",
              "  - Same Direction: V_rel = |v1 - v2| (overtaking speed).",
              "Trains: Time to cross a stationary pole of length 0: t = L_train / v. Time to cross a platform of length L_plat: t = (L_train + L_plat) / v.",
              "Boats & Streams: Downstream speed = v_boat + v_stream; Upstream speed = v_boat - v_stream.",
            ],
            examPitfalls: [
              "Do not average speeds directly when distance is fixed. If you travel at 60 km/h and return at 40 km/h, the average speed is 2*60*40 / (60+40) = 48 km/h, NOT 50 km/h.",
              "When two trains cross each other, the distance covered is ALWAYS the sum of both train lengths (L1 + L2), whether moving in the same direction or opposite directions.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Efficiency Method and Kinematic Frames",
              body: [
                "Instead of manipulating fractions like 1/12 + 1/15 - 1/20 under exam time constraints, the **LCM Unit Efficiency Framework** eliminates fractions completely.",
                "**Relative Motion Principle:** To analyze two moving bodies, fix one body at rest by subtracting its velocity vector from the other body. Distance covered is the initial separation between the bodies plus their physical lengths.",
                "**Upstream vs Downstream Mechanics:**",
                "- Downstream: River current assists motion: v_d = u + v.",
                "- Upstream: River current opposes motion: v_u = u - v.",
                "- Boat in still water: u = (v_d + v_u) / 2.",
                "- Stream velocity: v = (v_d - v_u) / 2.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Boats & Streams Instant Decomposition",
                message:
                  "If downstream speed is 16 km/h and upstream speed is 10 km/h, still water speed is simply (16 + 10)/2 = 13 km/h, and water current speed is (16 - 10)/2 = 3 km/h.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Alternating Work with Pipe Leak",
              weightage: "2 Marks (GATE CS/DA Pattern)",
              trap: "When working in alternate hours, do not divide total work by cycle work directly near the end, because the tank might fill during an active filling hour before the leak hour occurs.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "Pipe A can fill a tank in 12 hours. Pipe B empties the full tank in 18 hours.",
                "The pipes are opened on alternate hours starting with Pipe A. How many hours will it take for the tank to be completely filled?",
                "Step 1: Set Total Capacity = LCM(12, 18) = 36 units:",
                "  Efficiency(A) = +36 / 12 = +3 units/hour.",
                "  Efficiency(B) = -36 / 18 = -2 units/hour.",
                "Step 2: Analyze a 2-hour cycle (Hour 1: A, Hour 2: B):",
                "  Work done in 2 hours = 3 - 2 = +1 unit.",
                "Step 3: Guard against overflow near the end:",
                "  Since A can contribute +3 units in a single hour, stop the cycle analysis before reaching (36 - 3) = 33 units.",
                "  To reach 33 units: 33 cycles of 2 hours each = 33 * 2 = 66 hours.",
                "  After 66 hours, work completed = 33 units.",
                "Step 4: Analyze remaining work on Hour 67 (Pipe A's turn):",
                "  Remaining work = 36 - 33 = 3 units.",
                "  Pipe A does exactly +3 units in 1 hour.",
                "  Therefore, on Hour 67, the tank becomes completely full and the process terminates.",
                "Total time taken = 66 + 1 = 67 hours.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "How to Prepare for Quantitative Aptitude for the CAT",
                  authors: "Arun Sharma",
                  year: "2021",
                  publisher: "McGraw-Hill",
                  relevance: "Chapters on Time & Work and Time, Speed & Distance cover all advanced competitive problem variations.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: COUNTING, ALGEBRA & DATA INTERPRETATION
    // =========================================================================
    {
      id: "aptitude-module-2-counting-and-data",
      title: "Module 2: Counting, Algebra & Data Interpretation",
      slug: "counting-and-data-interpretation",
      description: "Permutations, combinations, pigeonhole principle, geometric mensuration, bar charts, pie charts, and data synthesis.",
      order: 2,
      lessons: [
        {
          id: "permutations-combinations-and-probability",
          title: "Combinatorics, Permutations & Elementary Probability",
          slug: "permutations-combinations-and-probability",
          order: 1,
          estimatedMinutes: 28,
          tagline: "Factorial arrangements, circular permutations, derangements, stars and bars, and dice/coin/card probability.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Arrangements of n items where r items are identical: n! / (r1! * r2!). Derangements of n items: D_n = n! * [ 1 - 1/1! + 1/2! - 1/3! + ... + (-1)^n / n! ].",
            keyFormulasAndRules: [
              "Fundamental Counting Principle: Multiplication rule for sequential independent choices; Addition rule for mutually exclusive choices.",
              "Permutations nPr = n! / (n - r)! (order matters); Combinations nCr = n! / [r! * (n - r)!] (order does not matter).",
              "Circular Permutations:",
              "  - Distinguishable circle (e.g. people around a table): (n - 1)!.",
              "  - Non-distinguishable flip (e.g. beads in a necklace): (n - 1)! / 2.",
              "Stars and Bars (Distributing n identical items into r distinct boxes):",
              "  - Non-negative integers (x_i >= 0): (n + r - 1) C (r - 1).",
              "  - Positive integers (x_i >= 1): (n - 1) C (r - 1).",
              "Derangements (no item in its original position): D_1 = 0, D_2 = 1, D_3 = 2, D_4 = 9, D_5 = 44.",
              "Pigeonhole Principle: If n items are put into k pigeonholes, at least one container has >= ceil(n / k) items.",
            ],
            examPitfalls: [
              "Watch for 'at least one' wording. Always evaluate 1 - P(none) to avoid complex summations.",
              "Do not forget to divide by identical letter count when forming words from anagrams with repeated characters.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Systematic Combinatorial Counting Strategies",
              body: [
                "Counting problems in GATE Aptitude reward disciplined partitioning:",
                "**1. The Tie Method (Together):** To arrange items where certain elements must always appear together, bundle them into a single super-element.",
                "**2. The Gap Method (Never Together):** To ensure no two restricted elements are adjacent, first arrange the unrestricted elements, then place the restricted elements into the empty slots (gaps) created between them.",
                "**3. Derangements Formula:** The number of permutations of n elements such that no element appears in its original position is given by:",
                "  D_n = n! * Sum_{k=0}^n [ (-1)^k / k! ]",
                "  For large n, D_n / n! approaches 1/e ≈ 0.3678.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Derangement Values to Memorize",
                message:
                  "Memorize the first 5 derangement values directly for instant GATE answers: D_1 = 0, D_2 = 1, D_3 = 2, D_4 = 9, D_5 = 44.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Gap Method for Non-Adjacent Seating",
              weightage: "2 Marks (GATE CS/DA)",
              trap: "Do not subtract adjacent pairs from total without accounting for triple overlaps.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "In how many ways can 5 computer science professors and 4 data science professors sit in a single row such that no two data science professors sit next to each other?",
                "Step 1: Arrange the unrestricted group (5 CS professors) in a row:",
                "  Number of ways = 5! = 120 ways.",
                "Step 2: Identify the gaps created by 5 professors:",
                "  _ CS1 _ CS2 _ CS3 _ CS4 _ CS5 _",
                "  There are 5 + 1 = 6 available gaps.",
                "Step 3: Select and arrange the 4 Data Science professors into the 6 gaps:",
                "  Number of ways to choose 4 gaps and arrange = 6P4 = 6! / (6 - 4)! = 6 * 5 * 4 * 3 = 360 ways.",
                "Step 4: Apply multiplication principle:",
                "  Total ways = 5! * 6P4 = 120 * 360 = 43,200 ways.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Introductory Combinatorics (5th Edition)",
                  authors: "Richard A. Brualdi",
                  year: "2009",
                  publisher: "Pearson",
                  relevance: "Definitive textbook for permutations, combinations, pigeonhole principle, and derangements.",
                },
              ],
            },
          ],
        },
        {
          id: "geometry-mensuration-and-data-interpretation",
          title: "Geometry, Mensuration & Data Interpretation Graphs",
          slug: "geometry-mensuration-and-data-interpretation",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Area, perimeter, solid volumes, angle properties, bar charts, line graphs, and pie chart angle fractions.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "In pie charts, 100% corresponds to 360 degrees (1% = 3.6 degrees). For similar shapes with scaling factor k, length scales by k, area by k^2, and volume by k^3.",
            keyFormulasAndRules: [
              "2D Mensuration:",
              "  - Circle: Area = pi * r^2,   Circumference = 2 * pi * r.",
              "  - Triangle: Area = (1/2) * base * height = sqrt( s(s-a)(s-b)(s-c) ) (Heron's formula).",
              "  - Equilateral Triangle: Area = (sqrt(3)/4) * a^2,   Height = (sqrt(3)/2) * a.",
              "3D Solid Mensuration:",
              "  - Cylinder: Volume = pi * r^2 * h,   Curved Area = 2 * pi * r * h.",
              "  - Cone: Volume = (1/3) * pi * r^2 * h,   Curved Area = pi * r * l (where l = sqrt(r^2 + h^2)).",
              "  - Sphere: Volume = (4/3) * pi * r^3,   Surface Area = 4 * pi * r^2.",
              "Data Interpretation Formulas:",
              "  - Percentage Growth Rate = [ (Value_final - Value_initial) / Value_initial ] * 100%.",
              "  - Compound Annual Growth Rate (CAGR) = [ (Value_final / Value_initial)^{1/n} - 1 ] * 100%.",
              "  - Pie Chart Angle Conversion: Angle = (Value / Total) * 360 degrees.",
            ],
            examPitfalls: [
              "When reading graphs, inspect the Y-axis baseline! If a bar chart starts at 100 rather than 0, visual bar height ratios are misleading.",
              "Do not confuse percentage change with percentage point difference (e.g., from 20% to 25% is an increase of 5 percentage points, but a 25% relative growth).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Visual Data Synthesis and Geometric Theorems",
              body: [
                "Data Interpretation (DI) in GATE questions tests fast extraction and mental arithmetic from tabular and graphic presentations.",
                "**Pie Chart Mechanics:** A full circle spans 360 degrees, representing 100% of the aggregate quantity. Each slice theta represents a fraction theta / 360. If slice angle is 54 degrees, its percentage share is (54 / 360) * 100 = 15%.",
                "**Polygon Angle Rules:**",
                "- Sum of interior angles of an n-sided polygon = (n - 2) * 180 degrees.",
                "- Sum of exterior angles of ANY convex polygon is ALWAYS 360 degrees.",
                "- Number of diagonals in an n-gon = n*(n - 3) / 2.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Approximation in DI Ratios",
                message:
                  "Never compute full 4-digit long divisions in GATE DI. Round numbers to 2 significant digits (e.g. 4831 / 9712 ≈ 48 / 97 ≈ 50%) to verify multiple-choice options in seconds.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Cylinder Volume to Wire Conversion",
              weightage: "2 Marks (GATE Pattern)",
              trap: "Ensure all units are converted to the same dimension (meters vs millimeters) before equating volumes.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "A solid metallic cylinder of base radius 6 cm and height 12 cm is melted and recast into a uniform cylindrical wire of diameter 2 mm.",
                "What is the total length of the recast wire in meters?",
                "Step 1: Convert all dimensions to centimeters:",
                "  Cylinder: R = 6 cm,   H = 12 cm.",
                "  Wire diameter = 2 mm  =>  radius r = 1 mm = 0.1 cm.",
                "Step 2: Equate conservation of volume (Volume_cylinder = Volume_wire):",
                "  pi * R^2 * H = pi * r^2 * L",
                "  R^2 * H = r^2 * L",
                "Step 3: Solve for wire length L:",
                "  (6)^2 * 12 = (0.1)^2 * L",
                "  36 * 12 = 0.01 * L",
                "  432 = 0.01 * L  =>  L = 432 / 0.01 = 43,200 cm.",
                "Step 4: Convert length to meters:",
                "  L = 43,200 / 100 = 432 meters.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Magical Book on Quicker Maths",
                  authors: "M. Tyra",
                  year: "2018",
                  publisher: "BSC Publishing",
                  relevance: "Standard resource for fast mental calculations in geometry, mensuration, and data interpretation.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: ANALYTICAL REASONING & DEDUCTIVE LOGIC
    // =========================================================================
    {
      id: "aptitude-module-3-analytical-logic",
      title: "Module 3: Analytical Reasoning & Deductive Logic",
      slug: "analytical-reasoning",
      description: "Deductive arguments, formal syllogisms, Euler diagrams, seating arrangements, family blood relations, and truth-teller puzzles.",
      order: 3,
      lessons: [
        {
          id: "syllogisms-and-deductive-logic",
          title: "Syllogisms, Euler Diagrams & Formal Deductive Logic",
          slug: "syllogisms-and-deductive-logic",
          order: 1,
          estimatedMinutes: 25,
          tagline: "Definite truth vs possibilities, Venn representations, categorical propositions, and contradiction pairs.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A conclusion in a syllogism is logically valid ONLY if it holds true in EVERY possible Venn diagram.",
            keyFormulasAndRules: [
              "Categorical Propositions:",
              "  - A (Universal Affirmative): 'All A are B' => Set A is a subset of Set B.",
              "  - E (Universal Negative): 'No A is B' => A intersect B = empty set.",
              "  - I (Particular Affirmative): 'Some A are B' => A intersect B != empty set.",
              "  - O (Particular Negative): 'Some A are not B' => A - B != empty set.",
              "Contradictory Pairs: (A and O), (E and I). Exactly one is true, one is false.",
              "Complementary Either-Or Condition: Requires (1) both conclusions to be individually uncertain, (2) same subject and predicate, and (3) one conclusion affirmative and the other negative (e.g. Some and No).",
            ],
            examPitfalls: [
              "Do not use real-world facts in syllogisms; statements must be accepted as absolute truth (e.g. 'All dogs are cats').",
              "If a conclusion is true in one Venn diagram but false in another valid diagram, it is NOT logically valid.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Formal Logic of Syllogisms",
              body: [
                "Syllogism problems in GATE test formal deductive inference. Every question provides 2 or 3 premise statements and asks which of the given conclusions logically follow beyond all doubt.",
                "**The Gold Standard Rule:** A conclusion definitely follows if and only if it holds across every valid Venn representation of the premises.",
                "**Complementary Pairs (Either-Or Case):** If two conclusions form a contradictory pair (e.g. 'Some A are B' and 'No A is B') and neither is independently certain, the answer is 'Either I or II follows'.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. GATE Worked Example: Multi-Premise Syllogism",
              weightage: "1 Mark (GATE Aptitude Core)",
              trap: "Watch out for 'Some' not implying 'All'.",
              solutionSteps: [
                "Statements: 1. All engineers are problem solvers. 2. Some problem solvers are mathematicians.",
                "Conclusions: I. Some engineers are mathematicians. II. Some problem solvers are engineers.",
                "Step 1: Check Conclusion I: Can we draw a Venn diagram where the set of Engineers (E) and Mathematicians (M) are completely disjoint while both staying inside or overlapping Problem Solvers (P)? Yes. Hence Conclusion I does NOT definitely follow.",
                "Step 2: Check Conclusion II: Since All E are P, the intersection of P and E is non-empty (it contains all of E). Therefore, Some P are E must always be true.",
                "Answer: Only Conclusion II follows.",
              ],
            },
            {
              type: "resources",
              heading: "3. References & Practice Materials",
              sources: [
                {
                  title: "A Modern Approach to Verbal & Non-Verbal Reasoning",
                  authors: "R.S. Aggarwal",
                  year: "2021",
                  publisher: "S. Chand Publishing",
                  relevance: "Comprehensive coverage of syllogism rules and deductive logical puzzles.",
                },
              ],
            },
          ],
        },
        {
          id: "logical-puzzles-seating-and-blood-relations",
          title: "Seating Arrangements, Blood Relations & Knights-Knaves Puzzles",
          slug: "logical-puzzles-seating-and-blood-relations",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Linear and circular seating, inward/outward facing orientations, family tree notations, and truth-teller paradoxes.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "In circular seating facing center: Right is anti-clockwise, Left is clockwise. For blood relations, draw a generation hierarchy tree with +/- for male/female.",
            keyFormulasAndRules: [
              "Circular Seating Conventions:",
              "  - Facing Center (Inward): Immediate Left is Clockwise; Immediate Right is Anti-Clockwise.",
              "  - Facing Away from Center (Outward): Immediate Left is Anti-Clockwise; Immediate Right is Clockwise.",
              "Family Tree Notations:",
              "  - Gender: (+) for Male, (-) for Female.",
              "  - Marriage: Double horizontal line (=).",
              "  - Siblings: Single horizontal line (-).",
              "  - Generation descent: Vertical downward arrow (|).",
              "Binary Logic (Knights and Knaves / Truth-Tellers & Liars):",
              "  - Knight always tells the truth; Knave always lies.",
              "  - If person X says 'I am a knave', this is an impossible contradiction (neither knight nor knave could say it).",
              "  - Case analysis: Assume person A is telling the truth, check for contradictions; if contradiction arises, person A must be lying.",
            ],
            examPitfalls: [
              "Do not assume gender based on names. Gender must be explicitly stated in the problem text or derived from biological roles (father, mother, brother, sister).",
              "In linear seating, 'between A and B' does not necessarily mean immediately between them unless specified as 'exactly midway'.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Systematic Puzzle Modeling Framework",
              body: [
                "Analytical reasoning puzzles evaluate working memory and constraint satisfaction under pressure.",
                "**Seating Arrangement Strategy:**",
                "1. Always start by anchoring the most restrictive constraint (e.g. 'P sits exactly opposite Q', or 'R sits at the extreme left end').",
                "2. Branch into a maximum of two tentative diagrams if ambiguity exists, then eliminate the contradicting diagram with subsequent clues.",
                "**Family Relationship Hierarchy:**",
                "Standard relationships frequently tested in GATE:",
                "- Maternal uncle: Mother's brother.",
                "- Nephew / Niece: Brother's or sister's son / daughter.",
                "- Cousin: Uncle's or aunt's child.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Solving Truth-Teller Liar Puzzles in 1 Minute",
                message:
                  "If two people make contradictory claims about the same fact, exactly one is a truth-teller and the other is a liar. Use this mutually contradictory pair to anchor your truth-count immediately.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Circular Seating with Dual Orientations",
              weightage: "2 Marks (GATE Pattern)",
              trap: "Carefully reverse left/right orientations for members who face outward compared to inward.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "Six engineers (A, B, C, D, E, F) sit around a circular table.",
                "A, B, and C face the center, while D, E, and F face outward.",
                "B sits second to the right of A.",
                "D sits immediately to the left of B.",
                "E sits opposite to B.",
                "Who sits immediately to the right of D?",
                "Step 1: Place A at bottom facing center (Inward):",
                "  Since A faces inward, Right is counter-clockwise.",
                "  B sits second to the right of A => B is 2 positions counter-clockwise.",
                "Step 2: Place D:",
                "  B faces inward, so B's left is clockwise. D sits immediately to B's left.",
                "Step 3: Analyze D's orientation and right hand:",
                "  D faces OUTWARD. For an outward-facing person, Right is CLOCKWISE.",
                "  Moving clockwise from D leads directly to the seat of B.",
                "Conclusion: B sits immediately to the right of D.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Analytical Reasoning",
                  authors: "M.K. Pandey",
                  year: "2019",
                  publisher: "BSC Publishing",
                  relevance: "Classic textbook for analytical puzzles, conditional deductions, and binary logic games.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: SPATIAL APTITUDE & TRANSFORMATIONS
    // =========================================================================
    {
      id: "aptitude-module-4-spatial-reasoning",
      title: "Module 4: Spatial Aptitude & Shape Transformations",
      slug: "spatial-and-verbal",
      description: "2D/3D transformations, translation, rotation, mirror reflection, paper folding, hole punching, cube nets, and isometric views.",
      order: 4,
      lessons: [
        {
          id: "spatial-transformations-and-grammar",
          title: "2D/3D Spatial Transformations, Mirror Symmetry & Chirality",
          slug: "spatial-transformations-and-grammar",
          order: 1,
          estimatedMinutes: 25,
          tagline: "Rigid rotations, coordinate reflection matrices, chirality inversion, and shape congruence.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Rigid rotation preserves chirality (handedness); reflection inverts chirality. No amount of 2D rotation can turn a left glove into a right glove.",
            keyFormulasAndRules: [
              "2D Rotation Matrix by theta degrees counter-clockwise: [ [ cos theta, -sin theta ], [ sin theta, cos theta ] ].",
              "Standard 90-degree rotations in plane:",
              "  - 90 deg Clockwise: (x, y) -> (y, -x).",
              "  - 90 deg Counter-Clockwise: (x, y) -> (-y, x).",
              "  - 180 deg (Inversion): (x, y) -> (-x, -y).",
              "Reflection Operations:",
              "  - Reflection across Y-axis: (x, y) -> (-x, y) (horizontal flip).",
              "  - Reflection across X-axis: (x, y) -> (x, -y) (vertical flip).",
              "  - Reflection across line y = x: (x, y) -> (y, x).",
              "Chirality Rule: Pure rotations NEVER alter chirality (clockwise arrows stay clockwise). Reflections ALWAYS invert chirality (clockwise arrows become counter-clockwise).",
            ],
            examPitfalls: [
              "Do not confuse in-plane 2D rotation with 3D reflection (flipping over). If a figure has no reflective symmetry, a reflection cannot be matched by any 2D rotation.",
              "Track asymmetric interior markers (like a dot in one corner) through successive 90-degree turns.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Geometry of 2D Rigid Transformations",
              body: [
                "Spatial Aptitude was formally introduced into the GATE syllabus in 2021 to test an engineer's spatial intuition.",
                "**Translation:** Shifts every point of a shape by a constant vector (dx, dy). Preserves orientation and size.",
                "**Rotation:** Turns a shape around a fixed pivot point by angle theta. Preserves distances, angles, and chirality.",
                "**Reflection (Mirror Image):** Flips a shape over a mirror axis line. Reverses chirality (inverts left and right relative to the axis).",
                "**Composite Transformations:** A reflection followed by another reflection across a perpendicular axis is identical to a 180-degree rotation.",
              ],
              callout: {
                kind: "gate-tip",
                title: "The Handedness Test for Spatial Matching",
                message:
                  "If asked whether Shape B can be obtained from Shape A via 2D rotation only: pick an asymmetric feature (e.g. an arrow pointing from square to circle). Check whether you turn clockwise or counter-clockwise. If one is clockwise and the other counter-clockwise, it is a REFLECTION and CANNOT be produced by rotation alone.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Identifying Rotational Equivalence",
              weightage: "1 Mark (GATE Spatial Pattern)",
              trap: "Distinguish between mirror reflections and 90/180-degree planar rotations.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "An asymmetric letter 'F' is rotated 90 degrees clockwise, then reflected across the vertical Y-axis.",
                "Which single transformation produces the exact same final image from the original letter 'F'?",
                "Step 1: Track coordinate transformation on a test vector (x, y):",
                "  Original: (x, y).",
                "Step 2: 90 degrees clockwise rotation:",
                "  T1(x, y) = (y, -x).",
                "Step 3: Reflection across vertical Y-axis (negate first coordinate):",
                "  T2(y, -x) = (-y, -x).",
                "Step 4: Identify equivalent single operation:",
                "  Notice (x, y) -> (-y, -x) interchanges coordinates with a sign flip.",
                "  This is the reflection across the line y = -x.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Spatial Reasoning Tests: The Ultimate Guide",
                  authors: "Richard McMunn",
                  year: "2019",
                  publisher: "How2Become Ltd",
                  relevance: "Covers 2D and 3D shape transformations, spatial projections, and pattern matching.",
                },
              ],
            },
          ],
        },
        {
          id: "paper-folding-cube-nets-and-isometric-views",
          title: "Paper Folding, Unfolded Cube Nets & Isometric 3D Views",
          slug: "paper-folding-cube-nets-and-isometric-views",
          order: 2,
          estimatedMinutes: 28,
          tagline: "LIFO unfolding of punch hole cutouts, 6-face cube nets, opposite face rules, and orthographic projections.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "In an unfolded 6-square cube net, squares separated by exactly one square along a straight line are OPPOSITE faces and can NEVER be simultaneously visible.",
            keyFormulasAndRules: [
              "Paper Folding & Hole Punching Mechanics:",
              "  - Every fold line acts as an axis of mirror reflection.",
              "  - Unfold in reverse chronological order (Last-In, First-Out / LIFO).",
              "  - Each unfold step duplicates cutouts across the active fold crease.",
              "  - If paper is folded k times, a single punch produces up to 2^k holes.",
              "Unfolded Cube Net Rules:",
              "  - Rule 1 (Opposite Faces): Faces separated by one face in a straight strip are opposite.",
              "  - Rule 2 (Adjacency Constraint): Opposite faces can NEVER be adjacent in any 3D view.",
              "  - Rule 3 (Vertex Cyclic Order): The cyclic sequence of 3 faces meeting at a corner must match between the net and the 3D cube.",
              "Isometric Projections: Front View, Top View (Plan), Side View (Elevation). Total solid blocks = Top view block count with height tags.",
            ],
            examPitfalls: [
              "Do not forget that a punch hole made on a folded crease will produce a single merged hole on the fold line when opened, not two separate holes.",
              "In cube questions, if a candidate 3D cube shows two faces that are opposite on the net, discard that option immediately.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Mechanics of Cube Folding and Spatial Cuts",
              body: [
                "Paper folding and cube net questions test visualization of 3D objects from 2D planar layouts.",
                "**The 11 Valid Cube Nets:** There are exactly 11 distinct planar nets that can be folded into a closed cube. They fall into 4 classes: 1-4-1 (6 types), 2-3-1 (3 types), 2-2-2 (1 type), and 3-3 (1 type).",
                "**Opposite Face Elimination:** This is the most lethal test-taking tool in GATE. Identify all three opposite pairs: (Pair 1, Pair 2, Pair 3). In any perspective view of a cube, exactly 3 faces are visible. The view is valid if and only if it contains exactly ONE face from each opposite pair.",
              ],
              callout: {
                kind: "gate-tip",
                title: "The Opposite Face Elimination Shortcut",
                message:
                  "Identify the three opposite pairs on the unfolded net: (A-B), (C-D), (E-F). Look at the four multiple-choice options. Any option showing both A and B, both C and D, or both E and F is instantly eliminated.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Validating Folded Cube Perspectives",
              weightage: "2 Marks (Compulsory GATE Spatial Pattern)",
              trap: "Remember that opposite faces can never share a common edge in the folded 3D cube.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "A cube has faces marked 1, 2, 3, 4, 5, 6. The unfolded net consists of a vertical column with faces [1, 2, 3, 4] from top to bottom, with face 5 attached to the left of face 2, and face 6 attached to the right of face 3.",
                "Determine which faces are opposite, and check whether a view showing faces (1, 2, 3) is possible.",
                "Step 1: Identify opposite pairs using the skip-one rule:",
                "  - Face 1 and Face 3 are separated by 2 in the vertical strip => 1 is opposite to 3.",
                "  - Face 2 and Face 4 are separated by 3 in the vertical strip => 2 is opposite to 4.",
                "  - The two side tabs (Face 5 and Face 6) fold up to face each other => 5 is opposite to 6.",
                "Step 2: Evaluate the candidate view (1, 2, 3):",
                "  - The candidate view shows Face 1 and Face 3 simultaneously.",
                "  - But Face 1 and Face 3 are OPPOSITE faces.",
                "  - Opposite faces can never be visible at the same time on a physical cube.",
                "Conclusion: The view (1, 2, 3) is IMPOSSIBLE.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Non-Verbal Reasoning for Competitive Exams",
                  authors: "B.S. Sijwali, Indu Sijwali",
                  year: "2020",
                  publisher: "Arihant Publications",
                  relevance: "Exhaustive coverage of cube nets, paper folding, mirror images, and figures counting.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: VERBAL APTITUDE & READING COMPREHENSION
    // =========================================================================
    {
      id: "aptitude-module-5-verbal-reasoning",
      title: "Module 5: Verbal Aptitude & Reading Comprehension",
      slug: "verbal-aptitude",
      description: "English grammar rules, subject-verb agreement, prepositions, vocabulary in context, reading comprehension, and paragraph jumbles.",
      order: 5,
      lessons: [
        {
          id: "english-grammar-and-vocabulary-in-context",
          title: "English Grammar Rules, Modifiers & Vocabulary in Context",
          slug: "english-grammar-and-vocabulary-in-context",
          order: 1,
          estimatedMinutes: 25,
          tagline: "Subject-verb agreement, dangling modifiers, parallel structures, tenses, and contextual word meanings.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Parenthetical phrases (e.g. 'accompanied by', 'as well as', 'along with') do NOT change the number of the subject. A singular subject remains singular.",
            keyFormulasAndRules: [
              "Subject-Verb Agreement (SVA):",
              "  - Intervening Phrases: 'The professor, as well as her students, WAS [not were] present.'",
              "  - 'Either... or' / 'Neither... nor': Verb agrees with the CLOSER subject ('Neither the teacher nor the students WERE present').",
              "  - Indefinite Pronouns: 'Each', 'Everyone', 'Neither', 'Either', 'Nobody' take strictly SINGULAR verbs.",
              "Parallelism: Elements in a list must share the same grammatical form (e.g., 'She likes swimming, running, and cycling', NOT 'and to cycle').",
              "Dangling Modifiers: An introductory participial phrase must modify the subject immediately following the comma (e.g. 'Walking into the lab, the server crashed' implies the server was walking!).",
              "Tense Consistency: Conditionals:",
              "  - Zero: If + Present, Present (scientific truth).",
              "  - First: If + Present, will + Verb (probable future).",
              "  - Second: If + Past, would + Verb (hypothetical).",
              "  - Third: If + Past Perfect, would have + Past Participle (unreal past).",
            ],
            examPitfalls: [
              "Do not confuse 'its' (possessive pronoun) with 'it's' (contraction for 'it is').",
              "Watch out for words that sound alike (homophones): affect (verb: influence) vs effect (noun: result); principle (rule) vs principal (chief/school head).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Core Grammar Mechanics for GATE Verbal",
              body: [
                "Verbal Aptitude in GATE CS/DA comprises 4-5 questions testing precision rather than literary flair.",
                "**1. Subject-Verb Agreement:** Identify the true grammatical head of the noun phrase. Ignore all prepositional phrases and parenthetical clauses set off by commas.",
                "**2. Dangling and Misplaced Modifiers:** A descriptive modifier must immediately precede or follow the entity it describes.",
                "**3. Contextual Vocabulary:** Rather than rote memorization of dictionary entries, questions test discerning tone and nuance (e.g., 'ingenious' vs 'ingenuous', 'compliment' vs 'complement').",
              ],
              callout: {
                kind: "gate-tip",
                title: "The Neither/Either Proximity Rule",
                message:
                  "In 'Neither X nor Y', the verb agrees with Y. If Y is plural, verb is plural. If Y is singular, verb is singular. Example: 'Neither the captain nor the players were ready.' vs 'Neither the players nor the captain was ready.'",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Subject-Verb Agreement with Intervening Phrase",
              weightage: "1 Mark (GATE Verbal Pattern)",
              trap: "Allowing a plural object of a preposition to distract from a singular subject.",
              solutionSteps: [
                "Problem [Original Practice Problem · Modeled on GATE Pattern]:",
                "Choose the grammatically correct option to fill the blank:",
                "  'The batch of experimental microchips, including the latest quantum sensors, ________ rigorously tested before deployment.'",
                "  (A) were    (B) was    (C) have been    (D) are",
                "Step 1: Identify the true grammatical subject:",
                "  The noun phrase is 'The batch'.",
                "  'of experimental microchips' is a prepositional phrase modifying 'batch'.",
                "  'including the latest quantum sensors' is an intervening non-restrictive phrase.",
                "Step 2: Determine grammatical number of 'batch':",
                "  'Batch' is a singular collective noun.",
                "Step 3: Select the singular auxiliary verb:",
                "  Singular past passive requires 'was'.",
                "Conclusion: (B) was is the only grammatically correct option.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "Word Power Made Easy",
                  authors: "Norman Lewis",
                  year: "2014",
                  publisher: "Anchor",
                  relevance: "The definitive guide for building etymological vocabulary and context mastery.",
                },
                {
                  title: "High School English Grammar and Composition",
                  authors: "Wren & Martin",
                  year: "2017",
                  publisher: "S. Chand Publishing",
                  relevance: "Standard reference for formal rules of syntax, subject-verb agreement, and parallelism.",
                },
              ],
            },
          ],
        },
        {
          id: "reading-comprehension-and-critical-reasoning",
          title: "Reading Comprehension, Critical Inference & Para-Jumbles",
          slug: "reading-comprehension-and-critical-reasoning",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Primary purpose, logical inferences, author assumptions, strengthening/weakening arguments, and narrative ordering.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "An inference MUST be strictly provable from the passage text. Any option requiring unstated real-world assumptions or extreme claims ('always', 'never', 'only') is incorrect.",
            keyFormulasAndRules: [
              "Question Types in Reading Comprehension:",
              "  1. Main Idea / Central Theme: What is the author's primary objective?",
              "  2. Direct Factual / Detail: Information explicitly stated in text.",
              "  3. Logical Inference: Must be necessarily true if the passage statements are true.",
              "  4. Assumption Question: Unstated premise without which the author's argument falls apart.",
              "  5. Strengthen / Weaken: Evidence that increases or decreases the likelihood of author's conclusion.",
              "Para-Jumbles (Sentence Rearrangement):",
              "  - Identify the Opening Sentence: Must introduce the noun/concept without pronouns or forward-referencing conjunctions (e.g. 'However', 'Therefore').",
              "  - Mandatory Pairs: Chronological sequences, noun-to-pronoun transitions, cause-and-effect connectors.",
            ],
            examPitfalls: [
              "Do not select an option simply because it is a true scientific statement in real life; it MUST be supported by the passage itself.",
              "Beware of scope shifts: if the passage discusses 'many modern compilers', an option claiming 'all software programs' is an overgeneralization trap.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Critical Reasoning and Passage Deconstruction",
              body: [
                "GATE reading comprehension passages are concise (100-250 words) but dense in argument structure.",
                "**The Anatomy of an Argument:**",
                "- **Premise:** Fact or evidence provided by the author.",
                "- **Assumption:** Unstated bridge connecting the premise to the conclusion.",
                "- **Conclusion:** The claim the author attempts to establish.",
                "**Assumption Negation Technique:** To verify whether a statement is an assumption of the author's argument, negate it. If negating the statement shatters the argument, the statement is indeed a mandatory assumption.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Eliminating Extreme Language",
                message:
                  "Options containing absolute words such as 'solely', 'exclusively', 'never', 'invariably', or 'universally' are incorrect in over 90% of GATE inference questions unless the author used identical extreme wording.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Problem: Critical Reasoning Assumption Identification",
              weightage: "2 Marks (GATE Verbal Pattern)",
              trap: "Do not confuse an additional consequence with a required underlying assumption.",
              solutionSteps: [
                "Passage [Original Practice Problem · Modeled on GATE Pattern]:",
                "'Autonomous driving systems rely on deep neural networks trained on millions of real-world driving hours. However, simulations can generate edge-case scenarios—such as extreme blizzard conditions with erratic pedestrian behavior—that occur only once every ten million highway miles. Therefore, autonomous vehicles trained with extensive simulation data will exhibit significantly lower accident rates in extreme weather than those trained on real-world driving alone.'",
                "Question: Which of the following is an underlying assumption of the argument?",
                "  (A) Real-world driving data will soon become completely obsolete.",
                "  (B) Driving skills learned in simulated edge cases successfully transfer to physical vehicle control in real extreme weather.",
                "  (C) Blizzard conditions are the single most dangerous weather pattern.",
                "  (D) Neural networks train faster in simulated environments than real road miles.",
                "Step 1: Identify conclusion and premise:",
                "  Premise: Simulations generate rare edge cases much more frequently than real driving.",
                "  Conclusion: Vehicles trained on simulations will have lower accident rates in physical extreme weather.",
                "Step 2: Apply Assumption Negation Technique:",
                "  Negate option (B): 'Driving skills learned in simulated edge cases DO NOT transfer to physical vehicle control in real extreme weather.'",
                "  If simulated skills do not transfer to physical cars, simulation training cannot lower real accident rates.",
                "  The conclusion collapses completely.",
                "Conclusion: (B) is the mandatory underlying assumption.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "The Official Guide to the GRE General Test (3rd Edition)",
                  authors: "Educational Testing Service (ETS)",
                  year: "2017",
                  publisher: "McGraw-Hill",
                  relevance: "Standard benchmark for reading comprehension, argument assumptions, and critical reasoning.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
