import { CourseMeta } from "./types";

export const LINEAR_ALGEBRA_COURSE: CourseMeta = {
  id: "linear-algebra",
  title: "Linear Algebra",
  slug: "linear-algebra",
  subjectSlug: "linear-algebra",
  shortTitle: "Linear Algebra",
  icon: "📐",
  color: "bg-blue-500",
  tagline:
    "Master vector spaces, four fundamental subspaces, Gaussian elimination, eigenvalues, spectral theorem, SVD, and PCA for GATE DA.",
  description:
    "A comprehensive academic study notebook covering vector spaces, subspaces, linear independence, basis and dimension, linear transformations, Rank-Nullity theorem, systems of linear equations, Gaussian elimination, determinants, eigenvalues and eigenvectors, Cayley-Hamilton theorem, diagonalizability, Gram-Schmidt orthogonalization, QR decomposition, symmetric matrices, Spectral Theorem, Positive Definiteness, Singular Value Decomposition (SVD), and Principal Component Analysis (PCA). Modeled on the reference Operating Systems benchmark for the official GATE Data Science & AI (DA) curriculum.",
  level: "Undergraduate / GATE DA",
  estimatedHours: 42,
  prerequisites: [
    "High school matrix arithmetic, determinants, and vector dot products",
    "Basic algebraic geometry and systems of linear equations",
  ],
  learningOutcomes: [
    "Test vector space and subspace axioms, determine bases, compute dimensions, and verify linear independence",
    "Determine the four fundamental subspaces of any matrix and apply the Rank-Nullity theorem",
    "Construct matrix representations of linear transformations and apply change-of-basis similarity transformations",
    "Solve systems of linear equations using Gaussian elimination, REF/RREF, and Rouché-Capelli rank solvability criteria",
    "Evaluate determinants using axiomatic multilinear properties and apply Cramer's rule and matrix inverses",
    "Compute eigenvalues, eigenvectors, and characteristic polynomials, and test diagonalizability via AM vs GM",
    "Apply the Cayley-Hamilton theorem to evaluate high matrix powers and matrix polynomial inverses",
    "Construct orthonormal bases via the Gram-Schmidt process, compute QR decompositions, and find least-squares projections",
    "Apply the Spectral Theorem to orthogonally diagonalize real symmetric matrices and test positive definiteness via Sylvester's criterion",
    "Compute SVD factorizations A = U Sigma V^T, derive Eckart-Young rank-k approximations, and diagonalize covariance matrices for PCA",
  ],
  gateScope: "GATE 2027 DA scope",
  gateBranches: ["da"],
  gateSyllabusTopics: [
    "Vector spaces, subspaces, linear dependence and independence of vectors, basis, dimension",
    "Linear transformations, matrix representation of linear transformations, rank-nullity theorem",
    "Systems of linear equations, Gaussian elimination, row echelon form, consistency and solutions",
    "Determinants, axiomatic properties, Cramer's rule, matrix inverse via adjugate",
    "Eigenvalues, eigenvectors, characteristic polynomial, trace and determinant relations",
    "Cayley-Hamilton theorem, minimal polynomial, matrix powers and inverse calculations",
    "Diagonalizability, algebraic multiplicity (AM) vs geometric multiplicity (GM), defective matrices",
    "Inner product spaces, Cauchy-Schwarz inequality, Gram-Schmidt orthogonalization, QR decomposition",
    "Projections, least-squares normal equations, orthogonal projection matrices",
    "Symmetric matrices, Spectral Theorem, quadratic forms, positive definite and positive semi-definite matrices",
    "Singular Value Decomposition (SVD), low-rank approximation, Principal Component Analysis (PCA)",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: VECTOR SPACES & LINEAR TRANSFORMATIONS
    // =========================================================================
    {
      id: "da-la-module-1-vector-spaces",
      title: "Module 1: Vector Spaces, Subspaces & Linear Transformations",
      slug: "vector-spaces-and-transformations",
      description:
        "Vector space axioms, subspace tests, linear span, bases, dimension, the four fundamental subspaces, the Rank-Nullity theorem, and matrix representations of linear maps.",
      order: 1,
      lessons: [
        {
          id: "vector-spaces-subspaces-and-linear-independence",
          title: "Vector Spaces, Subspaces & Linear Independence",
          slug: "vector-spaces-subspaces-and-linear-independence",
          order: 1,
          estimatedMinutes: 28,
          tagline: "Vector axioms, subspace closure criteria, spanning sets, linear independence, and basis dimensions.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Subspace Test: A non-empty subset W of V is a subspace iff 0 in W, u + v in W, and c * u in W for all scalars c.",
            keyFormulasAndRules: [
              "Linear Independence: c1*v1 + c2*v2 + ... + ck*vk = 0 iff c1 = c2 = ... = ck = 0.",
              "Basis: A set B = {v1, ..., vk} is a basis for V iff B is linearly independent and span(B) = V.",
              "Dimension: The number of vectors in any basis of V is unique and denotes dim(V).",
              "Any set of k > n vectors in R^n is GUARANTEED to be linearly dependent.",
              "If dim(V) = n, any linearly independent set of n vectors is automatically a basis.",
            ],
            examPitfalls: [
              "A set containing the zero vector {0} is ALWAYS linearly dependent because 1 * 0 = 0 provides a non-trivial linear combination.",
              "A subset that does not contain the origin (0 vector) can NEVER be a vector subspace (e.g. affine hyperplanes like x + y = 1).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Vector Spaces, Closure Axioms & Subspace Criteria",
              body: [
                "A **Vector Space** V over field F (typically R) is a set equipped with vector addition and scalar multiplication satisfying 8 core axioms: commutativity, associativity, additive identity 0, additive inverse, multiplicative identity 1, and distributivity.",
                "**The Two-Step Subspace Criterion:**",
                "A subset W of V is a subspace if and only if:",
                "1. Zero vector: `0 in W`.",
                "2. Closure under addition: For all `u, v in W`, `u + v in W`.",
                "3. Closure under scalar multiplication: For all `u in W` and `c in R`, `c * u in W`.",
                "Combined in one step: For all `u, v in W` and `alpha, beta in R`, `alpha * u + beta * v in W`.",
                "**Linear Independence & Spanning Sets:**",
                "Vectors `{v1, ..., vk}` are **linearly independent** if the only solution to `Sum_{i=1}^k c_i v_i = 0` is `c1 = c2 = ... = ck = 0`.",
                "If at least one non-zero scalar exists, the vectors are **linearly dependent**, meaning at least one vector can be written as a linear combination of the others.",
                "**Basis & Dimension:**",
                "A set B is a **basis** for V if it is linearly independent and spans V. The number of vectors in B is the **dimension** `dim(V)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Subspace Verification & Basis Extraction",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Ensure you solve for the number of free variables; dim(W) = n - number of independent linear constraints.",
              solutionSteps: [
                "Problem: Let W be the subset of R^4 defined by: W = { (x, y, z, w) in R^4 : x + 2y - z = 0  and  y - w = 0 }. Verify that W is a subspace of R^4, find its dimension, and construct a basis.",
                "Step 1: Check subspace criteria:",
                "  Homogeneous linear equations always contain the origin: (0, 0, 0, 0) satisfies 0 + 0 - 0 = 0 and 0 - 0 = 0.",
                "  Linear combinations of solutions to homogeneous linear equations are also solutions. Thus, W is a valid subspace.",
                "Step 2: Express dependent variables in terms of free variables:",
                "  Constraint 1: x + 2y - z = 0  =>  x = z - 2y",
                "  Constraint 2: y - w = 0       =>  y = w",
                "  Let the free variables be z = s and w = t (where s, t in R).",
                "  Then: y = t, and x = s - 2t.",
                "Step 3: Parameterize any vector v in W:",
                "  v = [ x, y, z, w ]^T = [ s - 2t, t, s, t ]^T",
                "  v = s * [ 1, 0, 1, 0 ]^T + t * [ -2, 1, 0, 1 ]^T",
                "Step 4: Check linear independence of basis candidates:",
                "  Vector 1: b1 = [ 1, 0, 1, 0 ]^T",
                "  Vector 2: b2 = [ -2, 1, 0, 1 ]^T",
                "  Neither vector is a scalar multiple of the other (component 4 is 0 in b1 but 1 in b2).",
                "Conclusion: Basis for W is { [1, 0, 1, 0]^T, [-2, 1, 0, 1]^T }, and dim(W) = 2.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Linear Algebra and Its Applications (5th Edition)",
                  authors: "David C. Lay, Steven R. Lay, Judi J. McDonald",
                  year: "2015",
                  publisher: "Pearson",
                  relevance: "Chapter 4: Vector spaces, subspaces, null spaces, and bases.",
                },
              ],
            },
          ],
        },
        {
          id: "four-fundamental-subspaces-and-rank-nullity",
          title: "The Four Fundamental Subspaces & Rank-Nullity Theorem",
          slug: "four-fundamental-subspaces-and-rank-nullity",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Column space, null space, row space, left null space, orthogonal complements, and dim(V) = rank + nullity.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Rank-Nullity Theorem: For an m x n matrix A, Rank(A) + Nullity(A) = n (number of columns).",
            keyFormulasAndRules: [
              "Column Space C(A) in R^m: Dimension = r = Rank(A). Spanned by pivot columns of A.",
              "Null Space N(A) in R^n: Dimension = n - r = Nullity(A). Solutions to Ax = 0.",
              "Row Space C(A^T) in R^n: Dimension = r. Spanned by non-zero rows of RREF(A).",
              "Left Null Space N(A^T) in R^m: Dimension = m - r. Solutions to A^T y = 0.",
              "Orthogonality Relations: N(A) = (C(A^T))_perp and N(A^T) = (C(A))_perp.",
              "Sum of Dimensions: dim(C(A^T)) + dim(N(A)) = r + (n - r) = n.",
            ],
            examPitfalls: [
              "To find a basis for the Column Space C(A), pick the PIVOT COLUMNS OF ORIGINAL MATRIX A, NOT the columns of RREF(A).",
              "Row rank ALWAYS equals Column rank for ANY matrix, square or rectangular: dim(C(A)) = dim(C(A^T)) = r.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Four Fundamental Subspaces of Linear Algebra",
              body: [
                "For any real `m x n` matrix A with rank `r`:",
                "1. **Column Space C(A):** Subspace of `R^m` spanned by the columns of A. `dim(C(A)) = r`.",
                "2. **Null Space N(A):** Subspace of `R^n` containing all solutions to `Ax = 0`. `dim(N(A)) = n - r`.",
                "3. **Row Space C(A^T):** Subspace of `R^n` spanned by the rows of A. `dim(C(A^T)) = r`.",
                "4. **Left Null Space N(A^T):** Subspace of `R^m` containing all solutions to `A^T y = 0`. `dim(N(A^T)) = m - r`.",
                "**Fundamental Theorem of Linear Algebra (Gilbert Strang):**",
                "`N(A)` is the orthogonal complement of `C(A^T)` in `R^n`.",
                "`N(A^T)` is the orthogonal complement of `C(A)` in `R^m`.",
                "Every vector `x in R^n` can be uniquely decomposed as `x = x_r + x_n`, where `x_r in C(A^T)` and `x_n in N(A)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Complete Decomposition of Four Subspaces",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Pivot column indices in RREF point back to original matrix columns for C(A).",
              solutionSteps: [
                "Problem: For matrix A = [ [1, 2, 0, 1], [0, 1, 1, 0], [1, 3, 1, 1] ] (size 3 x 4), find the rank, nullity, and bases for all four fundamental subspaces.",
                "Step 1: Reduce A to RREF:",
                "  R3 -> R3 - R1: [ 0, 1, 1, 0 ]",
                "  R3 -> R3 - R2: [ 0, 0, 0, 0 ]",
                "  R1 -> R1 - 2*R2: [ 1, 0, -2, 1 ]",
                "  RREF(A) = [ [1, 0, -2, 1], [0, 1, 1, 0], [0, 0, 0, 0] ]",
                "  Pivot columns: Col 1 and Col 2. Free variables: Col 3 and Col 4.",
                "  Rank r = 2, Nullity = n - r = 4 - 2 = 2.",
                "Step 2: Basis for Column Space C(A) (dim = 2 in R^3):",
                "  Take original columns 1 and 2 of A:",
                "  Basis(C(A)) = { [1, 0, 1]^T, [2, 1, 3]^T }.",
                "Step 3: Basis for Row Space C(A^T) (dim = 2 in R^4):",
                "  Take non-zero rows of RREF(A):",
                "  Basis(C(A^T)) = { [1, 0, -2, 1]^T, [0, 1, 1, 0]^T }.",
                "Step 4: Basis for Null Space N(A) (dim = 2 in R^4):",
                "  x1 = 2*x3 - x4; x2 = -x3; x3 = s; x4 = t.",
                "  Basis(N(A)) = { [2, -1, 1, 0]^T, [-1, 0, 0, 1]^T }.",
                "Step 5: Basis for Left Null Space N(A^T) (dim = m - r = 3 - 2 = 1 in R^3):",
                "  Solve A^T y = 0: y1 + y3 = 0, 2*y1 + y2 + 3*y3 = 0, y2 + y3 = 0.",
                "  y3 = 1 => y1 = -1, y2 = -1.",
                "  Basis(N(A^T)) = { [-1, -1, 1]^T }.",
                "Conclusion: All four dimensions satisfy: dim(C(A))=2, dim(N(A))=2, dim(C(A^T))=2, dim(N(A^T))=1.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Introduction to Linear Algebra (5th Edition)",
                  authors: "Gilbert Strang",
                  year: "2016",
                  publisher: "Wellesley-Cambridge Press",
                  relevance: "Chapter 3: The Four Fundamental Subspaces.",
                },
              ],
            },
          ],
        },
        {
          id: "linear-transformations-matrix-representation-and-change-of-basis",
          title: "Linear Maps, Matrix Representations & Change of Basis",
          slug: "linear-transformations-matrix-representation-and-change-of-basis",
          order: 3,
          estimatedMinutes: 30,
          tagline: "Linearity tests, standard matrix representations [T], kernel, range, and similarity transformations A' = P^{-1} A P.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Similarity Transformation: Two matrices A and B represent the same linear transformation under different bases iff B = P^{-1} * A * P for an invertible transition matrix P.",
            keyFormulasAndRules: [
              "Linearity Criterion: T(alpha * u + beta * v) = alpha * T(u) + beta * T(v).",
              "Standard Matrix: Columns of [T] are the images of standard basis vectors: [T] = [ T(e1) | T(e2) | ... | T(en) ].",
              "Matrix representation in basis B: [T]_B = P^{-1} * [T] * P, where P has basis vectors of B as columns.",
              "Similar matrices share the SAME eigenvalues, trace, determinant, and rank.",
            ],
            examPitfalls: [
              "Similar matrices share eigenvalues, but their EIGENVECTORS ARE NOT GENERALLY THE SAME (they are transformed by P).",
              "Affine transformations T(x) = Ax + b with b != 0 are NOT linear transformations because T(0) != 0.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Linear Transformations & Coordinate Representations",
              body: [
                "A mapping `T: V -> W` is a **Linear Transformation** if it preserves vector addition and scalar multiplication.",
                "**Kernel and Range:**",
                "`Kernel(T) = { v in V : T(v) = 0 }` (corresponds to null space of representation matrix).",
                "`Range(T) = { T(v) : v in V }` (corresponds to column space of representation matrix).",
                "**Change of Basis Matrix:**",
                "Let `B = {b1, ..., bn}` and `B' = {b1', ..., bn'}` be two bases for V. The transition matrix `P = P_{B -> B'}` transforms coordinates: `[x]_{B'} = P^{-1} [x]_B`.",
                "The matrix of transformation in the new basis is given by the **Similarity Transformation**:",
                "`[T]_{B'} = P^{-1} [T]_B P`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Change of Basis Transformation Matrix",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Remember P^{-1} A P ordering: columns of P are the new basis vectors expressed in standard coordinates.",
              solutionSteps: [
                "Problem: Let T: R^2 -> R^2 be defined by T(x, y) = (2x + 3y, x - y). Find the standard matrix A = [T]_E, and compute the representation matrix B = [T]_B in the basis B = { b1 = (1, 1)^T, b2 = (1, -1)^T }.",
                "Step 1: Construct standard matrix A:",
                "  T(e1) = T(1, 0) = (2, 1)^T",
                "  T(e2) = T(0, 1) = (3, -1)^T",
                "  A = [ [2, 3], [1, -1] ].",
                "Step 2: Construct transition matrix P with columns b1 and b2:",
                "  P = [ [1, 1], [1, -1] ]",
                "  det(P) = (1)(-1) - (1)(1) = -2.",
                "  P^{-1} = (1 / -2) * [ [-1, -1], [-1, 1] ] = [ [1/2, 1/2], [1/2, -1/2] ].",
                "Step 3: Compute product A * P:",
                "  A * P = [ [2, 3], [1, -1] ] * [ [1, 1], [1, -1] ]",
                "  Col 1: [ 2*1 + 3*1, 1*1 + (-1)*1 ]^T = [ 5, 0 ]^T",
                "  Col 2: [ 2*1 + 3*(-1), 1*1 + (-1)*(-1) ]^T = [ -1, 2 ]^T",
                "  A * P = [ [5, -1], [0, 2] ].",
                "Step 4: Compute B = P^{-1} * (A * P):",
                "  B = [ [1/2, 1/2], [1/2, -1/2] ] * [ [5, -1], [0, 2] ]",
                "  Row 1: [ (1/2)*5 + (1/2)*0, (1/2)*(-1) + (1/2)*2 ] = [ 5/2, 1/2 ]",
                "  Row 2: [ (1/2)*5 - (1/2)*0, (1/2)*(-1) - (1/2)*2 ] = [ 5/2, -3/2 ]",
                "  B = [ [2.5, 0.5], [2.5, -1.5] ].",
                "Conclusion: Under basis B, the transformation matrix is B = [ [2.5, 0.5], [2.5, -1.5] ].",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Linear Algebra Done Right (3rd Edition)",
                  authors: "Sheldon Axler",
                  year: "2015",
                  publisher: "Springer",
                  relevance: "Chapter 3: Linear Maps and matrices.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: SYSTEMS OF LINEAR EQUATIONS & DETERMINANTS
    // =========================================================================
    {
      id: "da-la-module-2-linear-systems",
      title: "Module 2: Systems of Linear Equations & Determinants",
      slug: "linear-systems-and-determinants",
      description:
        "Gaussian elimination, Row Echelon Forms, Rouché-Capelli consistency theorem, parametric solvability, and axiomatic determinant algebra.",
      order: 2,
      lessons: [
        {
          id: "systems-of-linear-equations-and-gaussian-elimination",
          title: "Gaussian Elimination & Linear System Solvability",
          slug: "systems-of-linear-equations-and-gaussian-elimination",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Augmented matrices, REF/RREF, Rouché-Capelli theorem, unique solutions, infinite solutions, and inconsistency.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Rouché-Capelli Theorem: Ax = b is consistent iff Rank(A) = Rank([A|b]). If rank = n, unique solution; if rank < n, infinitely many solutions.",
            keyFormulasAndRules: [
              "Consistent with Unique Solution: Rank(A) = Rank([A|b]) = n (number of variables).",
              "Consistent with Infinitely Many Solutions: Rank(A) = Rank([A|b]) = r < n (n - r free parameters).",
              "Inconsistent (No Solution): Rank(A) < Rank([A|b]) (a row of the form [0, 0, ..., 0 | c] with c != 0 appears).",
              "Homogeneous Systems Ax = 0: ALWAYS consistent (x = 0 is trivial solution). Non-trivial solution exists iff Rank(A) < n iff det(A) = 0 for square A.",
            ],
            examPitfalls: [
              "Never perform row operations that divide by an unknown algebraic parameter (e.g. dividing by k - 3) before checking the case where that parameter equals zero.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Linear Systems, Row Reduction & Solvability Regimes",
              body: [
                "Consider the linear system of m equations in n unknowns: `Ax = b`.",
                "**Elementary Row Operations:**",
                "1. Swap two rows (`R_i <-> R_j`).",
                "2. Multiply a row by non-zero scalar (`R_i -> c * R_i`).",
                "3. Add a scalar multiple of one row to another (`R_i -> R_i + c * R_j`).",
                "**Row Echelon Form (REF) vs Reduced Row Echelon Form (RREF):**",
                "In RREF, every leading entry (pivot) is 1, and each pivot is the ONLY non-zero entry in its entire column.",
                "**The Three Solvability Regimes:**",
                "Let `r = Rank(A)` and `r_aug = Rank([A | b])`:",
                "- `r < r_aug`: **Inconsistent** (0 = c contradiction; No solution).",
                "- `r = r_aug = n`: **Consistent & Unique** (all columns have pivots).",
                "- `r = r_aug < n`: **Consistent & Infinite** (`n - r` free parameters).",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Parameterized System Consistency Analysis",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Distinguish when the augmented column introduces an extra pivot versus when it falls into existing pivot structure.",
              solutionSteps: [
                "Problem: Consider the system of linear equations in variables x, y, z:",
                "  x + y + z = 6",
                "  x + 2y + 3z = 10",
                "  x + 2y + k*z = mu",
                "Determine the values of parameters k and mu for which the system has: (a) a unique solution, (b) infinitely many solutions, (c) no solution.",
                "Step 1: Set up the augmented matrix [A | b]:",
                "  [ [1, 1, 1 | 6], [1, 2, 3 | 10], [1, 2, k | mu] ]",
                "Step 2: Apply row operations to reach upper triangular form:",
                "  R2 -> R2 - R1: [ 0, 1, 2 | 4 ]",
                "  R3 -> R3 - R1: [ 0, 1, k - 1 | mu - 6 ]",
                "  R3 -> R3 - R2: [ 0, 0, k - 3 | mu - 10 ]",
                "  The reduced augmented matrix is:",
                "  [ [1, 1, 1 | 6], [0, 1, 2 | 4], [0, 0, k - 3 | mu - 10] ]",
                "Step 3: Analyze the three cases:",
                "  Case (a) Unique Solution: Requires Rank(A) = 3 = n.",
                "    This requires k - 3 != 0  =>  k != 3 (mu can be any real value).",
                "  Case (b) Infinitely Many Solutions: Requires Rank(A) = Rank([A|b]) = 2 < 3.",
                "    This requires the entire last row to be zero:",
                "    k - 3 = 0  and  mu - 10 = 0  =>  k = 3 and mu = 10.",
                "  Case (c) No Solution (Inconsistent): Requires Rank(A) = 2 != Rank([A|b]) = 3.",
                "    This requires k - 3 = 0  and  mu - 10 != 0  =>  k = 3 and mu != 10.",
                "Conclusion: Unique if k != 3; Infinite if k = 3, mu = 10; Inconsistent if k = 3, mu != 10.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Elementary Linear Algebra (11th Edition)",
                  authors: "Howard Anton, Chris Rorres",
                  year: "2013",
                  publisher: "Wiley",
                  relevance: "Chapter 1: Systems of Linear Equations and Matrices.",
                },
              ],
            },
          ],
        },
        {
          id: "determinants-properties-and-matrix-inverses",
          title: "Determinant Algebra, Cramer's Rule & Inverses",
          slug: "determinants-properties-and-matrix-inverses",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Axiomatic multilinearity, geometric volume interpretation, determinant identities, and adjugate inverses.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Matrix Invertibility: A square n x n matrix A is invertible iff det(A) != 0 iff Rank(A) = n iff Ax = 0 has only the trivial solution.",
            keyFormulasAndRules: [
              "Scalar Multiplication: det(c * A) = c^n * det(A) for an n x n matrix A.",
              "Product Rule: det(A * B) = det(A) * det(B).",
              "Inverse Determinant: det(A^{-1}) = 1 / det(A).",
              "Transpose Invariance: det(A^T) = det(A).",
              "Adjugate Inverse Formula: A^{-1} = (1 / det(A)) * adj(A).",
              "Adjugate Determinant: det(adj(A)) = (det(A))^{n - 1}.",
              "Orthogonal Matrix: det(Q) = +1 or -1.",
            ],
            examPitfalls: [
              "Remember det(c * A) = c^n * det(A), NOT c * det(A). Forgetting the power n is one of the most common GATE errors.",
              "det(A + B) != det(A) + det(B) in general; determinants do not distribute over matrix addition.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Determinants: Geometric Meaning & Algebraic Properties",
              body: [
                "The **Determinant** is a scalar value associated with any square matrix `n x n` representing the signed scaling factor of n-dimensional volume.",
                "**Key Axiomatic Properties:**",
                "1. `det(I) = 1`.",
                "2. Swapping two rows multiplies determinant by -1.",
                "3. If two rows/columns are identical or linearly dependent, `det(A) = 0`.",
                "4. Adding a scalar multiple of one row to another preserves `det(A)`.",
                "5. For triangular or diagonal matrices, `det(A) = prod_{i=1}^n a_{ii}`.",
                "**The Adjugate & Matrix Inverse:**",
                "The classical adjoint `adj(A) = C^T`, where C is the cofactor matrix.",
                "`A * adj(A) = det(A) * I`.",
                "`A^{-1} = (1 / det(A)) * adj(A)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Compound Determinant Identity",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Carefully factor the scalar 2 out of the 3x3 matrix: factor is 2^3 = 8.",
              solutionSteps: [
                "Problem: Let A be an invertible 3 x 3 real matrix such that det(A) = 5. Find the value of: det( 2 * A^{-1} * A^T * adj(A) ).",
                "Step 1: Identify matrix dimensions and scalar scaling:",
                "  Matrix dimension n = 3.",
                "  For any scalar c and 3 x 3 matrix M, det(c * M) = c^3 * det(M).",
                "  Here c = 2, so the scalar contributes factor 2^3 = 8.",
                "Step 2: Apply product rule det(M1 * M2 * M3) = det(M1) * det(M2) * det(M3):",
                "  det( 2 * A^{-1} * A^T * adj(A) ) = 8 * det(A^{-1}) * det(A^T) * det(adj(A)).",
                "Step 3: Evaluate individual determinants:",
                "  det(A^{-1}) = 1 / det(A) = 1 / 5.",
                "  det(A^T) = det(A) = 5.",
                "  det(adj(A)) = (det(A))^{n - 1} = 5^{3 - 1} = 5^2 = 25.",
                "Step 4: Compute final product:",
                "  Result = 8 * (1 / 5) * 5 * 25",
                "  Result = 8 * 1 * 25 = 200.",
                "Conclusion: det( 2 * A^{-1} * A^T * adj(A) ) = 200.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Linear Algebra (4th Edition)",
                  authors: "Stephen H. Friedberg, Arnold J. Insel, Lawrence E. Spence",
                  year: "2002",
                  publisher: "Pearson",
                  relevance: "Chapter 4: Determinants and multilinear forms.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: EIGENVALUES, DIAGONALIZATION & CAYLEY-HAMILTON
    // =========================================================================
    {
      id: "da-la-module-3-eigen-systems",
      title: "Module 3: Eigenvalues, Diagonalization & Cayley-Hamilton",
      slug: "eigenvalues-and-diagonalization",
      description:
        "Characteristic equations, trace/determinant relations, Algebraic vs Geometric multiplicity, modal diagonalization, and Cayley-Hamilton matrix polynomial algebra.",
      order: 3,
      lessons: [
        {
          id: "eigenvalues-eigenvectors-and-characteristic-polynomial",
          title: "Eigenvalues, Eigenvectors & Trace-Determinant Relations",
          slug: "eigenvalues-eigenvectors-and-characteristic-polynomial",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Av = lambda v, characteristic polynomial det(A - lambda I) = 0, trace sum, and determinant product rules.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Sum of eigenvalues equals Trace(A); Product of eigenvalues equals det(A).",
            keyFormulasAndRules: [
              "Eigenvalue Definition: A * v = lambda * v with non-zero eigenvector v != 0.",
              "Characteristic Equation: det(A - lambda * I) = 0.",
              "Trace Property: Sum_{i=1}^n lambda_i = Trace(A) = Sum_{i=1}^n a_{ii}.",
              "Determinant Property: Prod_{i=1}^n lambda_i = det(A).",
              "Eigenvalues of A^k are lambda_i^k.",
              "Eigenvalues of A^{-1} are 1 / lambda_i (provided det(A) != 0).",
              "Eigenvalues of A + c * I are lambda_i + c.",
              "Eigenvalues of Triangular/Diagonal matrices are simply the diagonal entries.",
            ],
            examPitfalls: [
              "Eigenvectors must be NON-ZERO vectors by definition. A zero vector is NEVER an eigenvector, even though lambda = 0 is a valid eigenvalue.",
              "Eigenvalues of A + B are NOT generally lambda(A) + lambda(B) unless A and B commute (AB = BA).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Eigensystem: Physical Geometry & Characteristic Equations",
              body: [
                "When a matrix A acts on a vector v, it generally rotates and scales v. An **Eigenvector** is a special direction that undergoes ONLY pure scaling, without rotation: `A v = lambda v`.",
                "**Characteristic Equation:**",
                "`(A - lambda I) v = 0` has non-trivial solutions iff `det(A - lambda I) = 0`.",
                "This yields an n-th degree polynomial `p(lambda) = (-1)^n lambda^n + c_{n-1} lambda^{n-1} + ... + det(A)`.",
                "**Essential Trace & Determinant Relations:**",
                "For any n x n matrix:",
                "- `Trace(A) = Sum_{i=1}^n lambda_i` (sum of diagonal entries).",
                "- `det(A) = Prod_{i=1}^n lambda_i`.",
                "These two relations allow fast verification of calculated eigenvalues in GATE examinations.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Eigenvalues & Eigenspaces of 3x3 Matrix",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Notice the block-triangular structure to rapidly factor the characteristic polynomial.",
              solutionSteps: [
                "Problem: Find all eigenvalues and basis vectors for the eigenspaces of matrix A = [ [2, 1, 1], [1, 2, 1], [0, 0, 1] ].",
                "Step 1: Set up characteristic equation det(A - lambda * I) = 0:",
                "  det([ [2 - lambda, 1, 1], [1, 2 - lambda, 1], [0, 0, 1 - lambda] ]) = 0",
                "  Expand along row 3:",
                "  (1 - lambda) * [ (2 - lambda)^2 - (1)(1) ] = 0",
                "  (1 - lambda) * [ (lambda^2 - 4*lambda + 4) - 1 ] = 0",
                "  (1 - lambda) * (lambda^2 - 4*lambda + 3) = 0",
                "  (1 - lambda) * (lambda - 1) * (lambda - 3) = 0",
                "  -(lambda - 1)^2 * (lambda - 3) = 0.",
                "Step 2: Identify eigenvalues and verify with trace and determinant:",
                "  lambda1 = 1 (multiplicity 2), lambda2 = 3 (multiplicity 1).",
                "  Trace check: 1 + 1 + 3 = 5; Diagonal sum: 2 + 2 + 1 = 5. (Matches).",
                "  det check: 1 * 1 * 3 = 3; det(A) = 1 * (4 - 1) = 3. (Matches).",
                "Step 3: Eigenspace for lambda = 3: (A - 3*I) v = 0:",
                "  [ [-1, 1, 1], [1, -1, 1], [0, 0, -2] ] [ v1, v2, v3 ]^T = 0",
                "  Row 3 => -2*v3 = 0 => v3 = 0.",
                "  Row 1 => -v1 + v2 = 0 => v1 = v2.",
                "  Eigenvector for lambda = 3: v = [ 1, 1, 0 ]^T.",
                "Step 4: Eigenspace for lambda = 1: (A - 1*I) v = 0:",
                "  [ [1, 1, 1], [1, 1, 1], [0, 0, 0] ] [ v1, v2, v3 ]^T = 0",
                "  Single independent equation: v1 + v2 + v3 = 0.",
                "  Two free variables (v2 = s, v3 = t) => v1 = -s - t.",
                "  Basis eigenvectors: v_a = [ -1, 1, 0 ]^T, and v_b = [ -1, 0, 1 ]^T.",
                "Conclusion: Eigenvalues are {1, 1, 3} with eigenspace bases { [-1, 1, 0]^T, [-1, 0, 1]^T } for lambda=1 and { [1, 1, 0]^T } for lambda=3.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Linear Algebra and Its Applications (5th Edition)",
                  authors: "David C. Lay, Steven R. Lay, Judi J. McDonald",
                  year: "2015",
                  publisher: "Pearson",
                  relevance: "Chapter 5: Eigenvalues and Eigenvectors.",
                },
              ],
            },
          ],
        },
        {
          id: "diagonalizability-algebraic-geometric-multiplicity",
          title: "Diagonalizability, Multiplicities & Defective Matrices",
          slug: "diagonalizability-algebraic-geometric-multiplicity",
          order: 2,
          estimatedMinutes: 30,
          tagline: "AM vs GM, modal matrix P, similarity diagonalization A = P D P^{-1}, and computing matrix powers A^k.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Diagonalizability Criterion: An n x n matrix A is diagonalizable iff Geometric Multiplicity equals Algebraic Multiplicity for EVERY eigenvalue (GM = AM), yielding n linearly independent eigenvectors.",
            keyFormulasAndRules: [
              "Algebraic Multiplicity AM(lambda): The multiplicity of lambda as a root of the characteristic polynomial.",
              "Geometric Multiplicity GM(lambda): The dimension of the eigenspace Nullity(A - lambda * I) = n - Rank(A - lambda * I).",
              "Multiplicity Inequality: 1 <= GM(lambda) <= AM(lambda).",
              "Sufficient Condition: If A has n DISTINCT eigenvalues, A is AUTOMATICALLY diagonalizable.",
              "Diagonalization: A = P * D * P^{-1}, where columns of P are eigenvectors, and D = diag(lambda1, ..., lambdan).",
              "Matrix Powers: A^k = P * D^k * P^{-1}, where D^k = diag(lambda1^k, ..., lambdan^k).",
            ],
            examPitfalls: [
              "Having repeated eigenvalues does NOT mean a matrix is not diagonalizable. It is defective ONLY IF GM < AM.",
              "A defective matrix CANNOT be diagonalized into a pure diagonal matrix (requires Jordan Canonical Form).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Diagonalization & The Multiplicity Theorem",
              body: [
                "A matrix A is **Diagonalizable** if it is similar to a diagonal matrix: `A = P D P^{-1}`.",
                "**Algebraic vs Geometric Multiplicity:**",
                "- **AM(lambda):** How many times `(lambda - lambda_0)` divides `det(A - lambda I)`.",
                "- **GM(lambda):** Number of linearly independent eigenvectors for `lambda`, equal to `Nullity(A - lambda I) = n - Rank(A - lambda I)`.",
                "**The Defective Matrix Trap:**",
                "If `GM(lambda) < AM(lambda)` for any eigenvalue, the matrix is **defective** and lacks a full basis of eigenvectors. It CANNOT be diagonalized.",
                "**Power Calculation Application:**",
                "Computing `A^{100}` directly requires 99 matrix multiplications. Under diagonalization:",
                "`A^{100} = (P D P^{-1})^{100} = P D^{100} P^{-1}`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Diagonalizability Test & Matrix Power",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Check GM = n - rank(A - lambda*I) to confirm sufficient independent eigenvectors.",
              solutionSteps: [
                "Problem: Let A = [ [1, 2], [0, 3] ]. Verify if A is diagonalizable. Construct the modal matrix P and diagonal matrix D, and compute A^4.",
                "Step 1: Find eigenvalues of triangular matrix A:",
                "  Since A is upper triangular, its eigenvalues are the diagonal entries: lambda1 = 1, lambda2 = 3.",
                "  Since both eigenvalues are distinct (lambda1 != lambda2), A is GUARANTEED to be diagonalizable (AM = GM = 1 for each).",
                "Step 2: Find eigenvector for lambda1 = 1: (A - 1*I) v = 0:",
                "  [ [0, 2], [0, 2] ] [ v1, v2 ]^T = 0  =>  2*v2 = 0  =>  v2 = 0, v1 = 1.",
                "  p1 = [ 1, 0 ]^T.",
                "Step 3: Find eigenvector for lambda2 = 3: (A - 3*I) v = 0:",
                "  [ [-2, 2], [0, 0] ] [ v1, v2 ]^T = 0  =>  -2*v1 + 2*v2 = 0  =>  v1 = v2.",
                "  p2 = [ 1, 1 ]^T.",
                "Step 4: Construct P, P^{-1}, and D:",
                "  P = [ [1, 1], [0, 1] ];  D = [ [1, 0], [0, 3] ].",
                "  det(P) = 1.  P^{-1} = [ [1, -1], [0, 1] ].",
                "Step 5: Compute A^4 = P * D^4 * P^{-1}:",
                "  D^4 = [ [1^4, 0], [0, 3^4] ] = [ [1, 0], [0, 81] ].",
                "  P * D^4 = [ [1, 1], [0, 1] ] * [ [1, 0], [0, 81] ] = [ [1, 81], [0, 81] ].",
                "  A^4 = [ [1, 81], [0, 81] ] * [ [1, -1], [0, 1] ] = [ [1, -1 + 81], [0, 81] ] = [ [1, 80], [0, 81] ].",
                "Conclusion: A is diagonalizable, and A^4 = [ [1, 80], [0, 81] ].",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Linear Algebra and Learning from Data",
                  authors: "Gilbert Strang",
                  year: "2019",
                  publisher: "Wellesley-Cambridge Press",
                  relevance: "Chapter 1: Diagonalization and Powers of Matrices.",
                },
              ],
            },
          ],
        },
        {
          id: "cayley-hamilton-theorem-and-minimal-polynomial",
          title: "Cayley-Hamilton Theorem & Minimal Polynomials",
          slug: "cayley-hamilton-theorem-and-minimal-polynomial",
          order: 3,
          estimatedMinutes: 30,
          tagline: "p(A) = 0, polynomial reduction of high powers, matrix inverse derivation, and the minimal polynomial monic divisor.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Cayley-Hamilton Theorem: Every square matrix satisfies its own characteristic equation: p(A) = 0.",
            keyFormulasAndRules: [
              "Characteristic Polynomial: p(lambda) = det(A - lambda * I) = (-1)^n lambda^n + c_{n-1} lambda^{n-1} + ... + c_0.",
              "Cayley-Hamilton Matrix Identity: (-1)^n A^n + c_{n-1} A^{n-1} + ... + c_0 I = 0.",
              "Matrix Inverse via Cayley-Hamilton: A^{-1} = (-1 / c_0) * [ (-1)^n A^{n-1} + c_{n-1} A^{n-2} + ... + c_1 I ], provided c_0 = det(A) != 0.",
              "Minimal Polynomial m(lambda): The unique monic polynomial of minimum degree such that m(A) = 0. Divides p(lambda).",
              "Diagonalizability via Minimal Polynomial: A matrix A is diagonalizable iff its minimal polynomial m(lambda) factors into DISTINCT linear terms (no repeated roots).",
            ],
            examPitfalls: [
              "Remember that the scalar term c_0 in p(lambda) becomes c_0 * I (identity matrix) when substituting matrix A.",
              "The minimal polynomial m(lambda) has the EXACT same set of distinct roots as p(lambda), but with possibly lower powers.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Cayley-Hamilton Theorem & Polynomial Algebra",
              body: [
                "The **Cayley-Hamilton Theorem** states that if `p(lambda) = det(A - lambda I)` is the characteristic polynomial of square matrix A, then `p(A) = 0` (the zero matrix).",
                "**Application to Matrix Powers:**",
                "Any polynomial `f(A)` of degree `k >= n` can be divided by `p(A)`:",
                "`f(A) = q(A) * p(A) + r(A) = q(A) * 0 + r(A) = r(A)`.",
                "Here `r(A)` has degree at most `n - 1`. Thus, ANY high matrix power can be expressed as a linear combination of `{I, A, A^2, ..., A^{n-1}}`.",
                "**The Minimal Polynomial m(lambda):**",
                "The **minimal polynomial** `m(lambda)` is the monic polynomial of lowest degree satisfying `m(A) = 0`.",
                "Key Theorem: A matrix A is diagonalizable if and only if `m(lambda) = (lambda - lambda_1)(lambda - lambda_2)...(lambda - lambda_k)` has NO repeated roots.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Evaluating Matrix Polynomial via Cayley-Hamilton",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Use the characteristic polynomial identity A^2 = tr(A)*A - det(A)*I to reduce high powers iteratively.",
              solutionSteps: [
                "Problem: Let A = [ [1, 2], [3, 4] ]. (a) Use the Cayley-Hamilton theorem to find A^{-1}. (b) Express A^4 as a linear combination of A and I.",
                "Step 1: Compute characteristic polynomial p(lambda):",
                "  Trace(A) = 1 + 4 = 5.",
                "  det(A) = (1)(4) - (2)(3) = 4 - 6 = -2.",
                "  p(lambda) = lambda^2 - Trace(A)*lambda + det(A) = lambda^2 - 5*lambda - 2.",
                "Step 2: Apply Cayley-Hamilton theorem p(A) = 0:",
                "  A^2 - 5*A - 2*I = 0  =>  A^2 = 5*A + 2*I.",
                "Step 3: Derive A^{-1} by multiplying identity by A^{-1}:",
                "  A - 5*I - 2*A^{-1} = 0",
                "  2*A^{-1} = A - 5*I  =>  A^{-1} = (1 / 2) * (A - 5*I).",
                "  A - 5*I = [ [1 - 5, 2], [3, 4 - 5] ] = [ [-4, 2], [3, -1] ].",
                "  A^{-1} = [ [-2, 1], [1.5, -0.5] ].",
                "  Verification via formula: (1 / -2) * [ [4, -2], [-3, 1] ] = [ [-2, 1], [1.5, -0.5] ]. (Matches exactly).",
                "Step 4: Compute A^4 via iterative reduction:",
                "  A^2 = 5*A + 2*I.",
                "  A^3 = A * A^2 = A * (5*A + 2*I) = 5*A^2 + 2*A = 5*(5*A + 2*I) + 2*A = 27*A + 10*I.",
                "  A^4 = A * A^3 = A * (27*A + 10*I) = 27*A^2 + 10*A = 27*(5*A + 2*I) + 10*A = 135*A + 54*I + 10*A.",
                "  A^4 = 145*A + 54*I.",
                "Conclusion: A^{-1} = 0.5*(A - 5*I) and A^4 = 145*A + 54*I.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Matrix Analysis (2nd Edition)",
                  authors: "Roger A. Horn, Charles R. Johnson",
                  year: "2012",
                  publisher: "Cambridge University Press",
                  relevance: "Chapter 3: Cayley-Hamilton and Minimal Polynomials.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: ORTHOGONALITY, QR & SYMMETRIC MATRICES
    // =========================================================================
    {
      id: "da-la-module-4-orthogonality-spectral",
      title: "Module 4: Orthogonality, QR Factorization & Spectral Theorem",
      slug: "orthogonality-and-spectral-theorem",
      description:
        "Inner product geometry, Cauchy-Schwarz, Gram-Schmidt orthogonalization, QR decomposition, least-squares projections, real symmetric matrices, and positive definiteness.",
      order: 4,
      lessons: [
        {
          id: "inner-product-spaces-gram-schmidt-and-qr-decomposition",
          title: "Inner Products, Gram-Schmidt & QR Factorization",
          slug: "inner-product-spaces-gram-schmidt-and-qr-decomposition",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Orthogonal bases, Gram-Schmidt process, QR decomposition A = QR, and least-squares projection matrices.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Orthogonal Matrix Q: Q^T * Q = I, meaning Q^{-1} = Q^T. Preserves vector lengths ||Q x|| = ||x|| and angles.",
            keyFormulasAndRules: [
              "Cauchy-Schwarz Inequality: |<u, v>| <= ||u|| * ||v|| with equality iff u and v are linearly dependent.",
              "Gram-Schmidt Step: u_k = v_k - Sum_{j=1}^{k-1} [ (v_k . u_j) / (u_j . u_j) ] * u_j; Normalization: e_k = u_k / ||u_k||.",
              "QR Decomposition: Any m x n matrix A with linearly independent columns can be factored as A = Q * R, where Q (m x n) has orthonormal columns and R (n x n) is upper triangular.",
              "Orthogonal Projection Matrix: P = A * (A^T * A)^{-1} * A^T. Properties: P^2 = P (idempotent), P^T = P (symmetric).",
              "Least-Squares Solution: When Ax = b is inconsistent, x_hat = (A^T A)^{-1} A^T b solves ||Ax - b||_2.",
            ],
            examPitfalls: [
              "When normalizing Gram-Schmidt vectors, divide by the Euclidean norm ||u_k|| = sqrt(Sum u_{ki}^2), NOT the sum of components.",
              "If Q is rectangular (m > n with orthonormal columns), Q^T Q = I_n, but Q Q^T is the PROJECTION MATRIX onto C(Q), NOT I_m.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Orthogonal Geometry, Gram-Schmidt & QR Decomposition",
              body: [
                "Two vectors are **orthogonal** if their inner product is zero: `u . v = 0`. An **orthonormal** set consists of mutually orthogonal unit vectors.",
                "**The Gram-Schmidt Process:**",
                "Given a linearly independent basis `{v1, v2, ..., vk}`, construct an orthonormal basis `{e1, e2, ..., ek}`:",
                "`u1 = v1`, `e1 = u1 / ||u1||`.",
                "`u2 = v2 - (v2 . e1) * e1`, `e2 = u2 / ||u2||`.",
                "`u_k = v_k - Sum_{j=1}^{k-1} (v_k . e_j) * e_j`, `e_k = u_k / ||u_k||`.",
                "**QR Factorization:**",
                "`A = Q R` where Q has orthonormal columns and R is upper triangular with `r_{ij} = v_j . e_i`.",
                "In least-squares regression, substituting `A = Q R` into `A^T A x_hat = A^T b` simplifies the normal equations to `R x_hat = Q^T b`, which can be solved instantly via back-substitution without matrix inversion.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: 3D Gram-Schmidt Orthonormalization",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Ensure intermediate vectors u2 and u3 are strictly orthogonal to all previously constructed vectors before normalizing.",
              solutionSteps: [
                "Problem: Orthonormalize the basis { v1 = [1, 1, 0]^T, v2 = [1, 0, 1]^T, v3 = [0, 1, 1]^T } in R^3.",
                "Step 1: First orthonormal vector e1:",
                "  u1 = v1 = [ 1, 1, 0 ]^T.",
                "  ||u1|| = sqrt(1^2 + 1^2 + 0^2) = sqrt(2).",
                "  e1 = [ 1/sqrt(2), 1/sqrt(2), 0 ]^T.",
                "Step 2: Second orthogonal vector u2 and normalized e2:",
                "  u2 = v2 - (v2 . e1) * e1.",
                "  v2 . e1 = (1)(1/sqrt(2)) + (0)(1/sqrt(2)) + (1)(0) = 1/sqrt(2).",
                "  (v2 . e1) * e1 = (1/sqrt(2)) * [ 1/sqrt(2), 1/sqrt(2), 0 ]^T = [ 1/2, 1/2, 0 ]^T.",
                "  u2 = [ 1, 0, 1 ]^T - [ 1/2, 1/2, 0 ]^T = [ 1/2, -1/2, 1 ]^T.",
                "  ||u2|| = sqrt( (1/2)^2 + (-1/2)^2 + 1^2 ) = sqrt( 1/4 + 1/4 + 1 ) = sqrt(6/4) = sqrt(6)/2.",
                "  e2 = u2 / ||u2|| = (2/sqrt(6)) * [ 1/2, -1/2, 1 ]^T = [ 1/sqrt(6), -1/sqrt(6), 2/sqrt(6) ]^T.",
                "Step 3: Third orthogonal vector u3 and normalized e3:",
                "  u3 = v3 - (v3 . e1)*e1 - (v3 . e2)*e2.",
                "  v3 . e1 = 0 + 1/sqrt(2) + 0 = 1/sqrt(2)  =>  (v3 . e1)*e1 = [ 1/2, 1/2, 0 ]^T.",
                "  v3 . e2 = 0 - 1/sqrt(6) + 2/sqrt(6) = 1/sqrt(6)  =>  (v3 . e2)*e2 = (1/sqrt(6)) * [ 1/sqrt(6), -1/sqrt(6), 2/sqrt(6) ]^T = [ 1/6, -1/6, 2/6 ]^T.",
                "  u3 = [ 0, 1, 1 ]^T - [ 1/2, 1/2, 0 ]^T - [ 1/6, -1/6, 1/3 ]^T",
                "  u3 = [ -2/3, 2/3, 2/3 ]^T.",
                "  Verify orthogonality: u3 . u1 = -2/3 + 2/3 + 0 = 0;  u3 . u2 = -1/3 - 1/3 + 2/3 = 0. (Strictly orthogonal!).",
                "  ||u3|| = sqrt( 4/9 + 4/9 + 4/9 ) = sqrt(12)/3 = 2/sqrt(3).",
                "  e3 = u3 / ||u3|| = [ -1/sqrt(3), 1/sqrt(3), 1/sqrt(3) ]^T.",
                "Conclusion: Orthonormal basis is { [1/sqrt(2), 1/sqrt(2), 0]^T, [1/sqrt(6), -1/sqrt(6), 2/sqrt(6)]^T, [-1/sqrt(3), 1/sqrt(3), 1/sqrt(3)]^T }.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Mathematics for Machine Learning",
                  authors: "Marc Peter Deisenroth, A. Aldo Faisal, Cheng Soon Ong",
                  year: "2020",
                  publisher: "Cambridge University Press",
                  relevance: "Chapter 3: Analytic Geometry and Projections.",
                },
              ],
            },
          ],
        },
        {
          id: "symmetric-matrices-spectral-theorem-and-positive-definiteness",
          title: "Symmetric Matrices, Spectral Theorem & Positive Definiteness",
          slug: "symmetric-matrices-spectral-theorem-and-positive-definiteness",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Real eigenvalues, orthogonal diagonalization A = Q Lambda Q^T, quadratic forms x^T A x, and Sylvester's criterion.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Spectral Theorem: Every real symmetric matrix A = A^T can be orthogonally diagonalized as A = Q * Lambda * Q^T, with all eigenvalues real and mutually orthogonal eigenvectors.",
            keyFormulasAndRules: [
              "Real Eigenvalues: All eigenvalues of a real symmetric matrix are guaranteed to be REAL numbers.",
              "Orthogonal Eigenvectors: Eigenvectors corresponding to distinct eigenvalues of a symmetric matrix are MUTUALLY ORTHOGONAL.",
              "Spectral Decomposition: A = Sum_{i=1}^n lambda_i * q_i * q_i^T, expressing A as a weighted sum of rank-1 projection matrices.",
              "Quadratic Form: q(x) = x^T * A * x = Sum_{i, j} a_{ij} x_i x_j.",
              "Positive Definite (PD): x^T A x > 0 for all x != 0 iff all lambda_i > 0 iff all leading principal minors det(A_k) > 0 (Sylvester's Criterion).",
              "Positive Semi-Definite (PSD): x^T A x >= 0 for all x iff all lambda_i >= 0 iff all principal minors >= 0.",
              "Cholesky Factorization: A is Positive Definite iff A = L * L^T for a unique lower triangular matrix L with positive diagonal.",
            ],
            examPitfalls: [
              "Sylvester's criterion for Positive Definiteness requires ONLY the LEADING principal minors to be > 0. But for Positive SEMI-Definiteness, ALL principal minors (not just leading ones) must be >= 0.",
              "If a symmetric matrix has both positive and negative eigenvalues, it is INDEFINITE and its quadratic form has a saddle point at x = 0.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Spectral Theorem & Quadratic Forms in Machine Learning",
              body: [
                "Real symmetric matrices `A = A^T` are the cornerstone of multivariate statistics, Hessian curvature optimization, and kernel methods.",
                "**The Spectral Theorem:**",
                "For any real symmetric matrix A:",
                "1. All eigenvalues `lambda_1, ..., lambda_n` are real.",
                "2. Eigenvectors can be chosen to form an orthonormal basis of `R^n`.",
                "3. `A = Q Lambda Q^T`, where Q is an orthogonal matrix (`Q^T Q = I`).",
                "**Classification of Quadratic Forms `q(x) = x^T A x`:**",
                "- **Positive Definite (PD):** `x^T A x > 0` for all `x != 0`. (Strict local minimum in optimization).",
                "- **Positive Semi-Definite (PSD):** `x^T A x >= 0` for all `x`. (Convex optimization landscape; Covariance matrices are always PSD).",
                "- **Negative Definite (ND):** `x^T A x < 0` for all `x != 0`. (Strict local maximum).",
                "- **Indefinite:** `x^T A x` takes both positive and negative values. (Saddle point).",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Sylvester's Criterion & Spectral Decomposition",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Confirm all leading principal minors are strictly positive for strict positive definiteness.",
              solutionSteps: [
                "Problem: Let A = [ [2, -1, 0], [-1, 2, -1], [0, -1, 2] ]. (a) Test if A is Positive Definite using Sylvester's criterion. (b) Find its eigenvalues to confirm.",
                "Step 1: Compute leading principal minors (Sylvester's Criterion):",
                "  D1 = det([ 2 ]) = 2 > 0.",
                "  D2 = det([ [2, -1], [-1, 2] ]) = (2)(2) - (-1)(-1) = 4 - 1 = 3 > 0.",
                "  D3 = det(A) = expand along row 1:",
                "    D3 = 2 * det([ [2, -1], [-1, 2] ]) - (-1) * det([ [-1, -1], [0, 2] ]) + 0",
                "    D3 = 2 * (3) + 1 * (-2 - 0) = 6 - 2 = 4 > 0.",
                "  All leading principal minors (D1 = 2, D2 = 3, D3 = 4) are strictly positive.",
                "  Therefore, A is strictly POSITIVE DEFINITE (PD).",
                "Step 2: Solve characteristic polynomial det(A - lambda * I) = 0:",
                "  det([ [2 - lambda, -1, 0], [-1, 2 - lambda, -1], [0, -1, 2 - lambda] ]) = 0",
                "  (2 - lambda) * [ (2 - lambda)^2 - 1 ] - (-1) * [ -(2 - lambda) ] = 0",
                "  (2 - lambda) * [ (2 - lambda)^2 - 1 ] - (2 - lambda) = 0",
                "  (2 - lambda) * [ (2 - lambda)^2 - 2 ] = 0.",
                "Step 3: Extract eigenvalues:",
                "  lambda1 = 2",
                "  (2 - lambda)^2 = 2  =>  2 - lambda = +- sqrt(2)",
                "  lambda2 = 2 - sqrt(2) ≈ 0.586",
                "  lambda3 = 2 + sqrt(2) ≈ 3.414.",
                "Step 4: Verify definiteness via eigenvalues:",
                "  All three eigenvalues (0.586, 2, 3.414) are strictly positive real numbers (> 0).",
                "Conclusion: A is positive definite by both Sylvester's criterion and positive eigenvalues.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Convex Optimization",
                  authors: "Stephen Boyd, Lieven Vandenberghe",
                  year: "2004",
                  publisher: "Cambridge University Press",
                  relevance: "Appendix A: Mathematical background on positive definite matrices and quadratic forms.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: SVD & PRINCIPAL COMPONENT ANALYSIS
    // =========================================================================
    {
      id: "da-la-module-5-svd-pca",
      title: "Module 5: Singular Value Decomposition (SVD) & PCA",
      slug: "svd-and-pca",
      description:
        "General matrix factorizations, singular values, left/right singular vectors, Eckart-Young theorem, covariance matrix diagonalization, and Principal Component Analysis.",
      order: 5,
      lessons: [
        {
          id: "singular-value-decomposition-and-pca",
          title: "SVD Factorization, Eckart-Young Theorem & PCA",
          slug: "singular-value-decomposition-and-pca",
          order: 1,
          estimatedMinutes: 34,
          tagline: "A = U Sigma V^T, singular values sigma_i = sqrt(lambda_i), Eckart-Young rank-k truncation, and PCA dimensionality reduction.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "SVD: Any m x n matrix A can be factored as A = U * Sigma * V^T, where U (m x m) and V (n x n) are orthogonal, and Sigma contains non-negative singular values sigma_1 >= sigma_2 >= ... >= sigma_r > 0.",
            keyFormulasAndRules: [
              "Singular Values: sigma_i = sqrt(lambda_i(A^T A)) = sqrt(lambda_i(A A^T)).",
              "Right Singular Vectors (columns of V): Eigenvectors of A^T A (size n x n).",
              "Left Singular Vectors (columns of U): Eigenvectors of A A^T (size m x m). Relation: u_i = (1 / sigma_i) * A * v_i.",
              "Frobenius Norm: ||A||_F^2 = Sum_{i, j} a_{ij}^2 = Sum_{i=1}^r sigma_i^2.",
              "Eckart-Young-Mirsky Theorem: The optimal rank-k approximation minimizing ||A - A_k||_F is A_k = Sum_{i=1}^k sigma_i * u_i * v_i^T.",
              "PCA Connection: If data matrix X is mean-centered, the sample covariance matrix is Sigma_X = (1/n) * X^T X. The principal components are the right singular vectors V of X.",
              "Explained Variance Ratio: EVR_k = (Sum_{i=1}^k sigma_i^2) / (Sum_{j=1}^r sigma_j^2).",
            ],
            examPitfalls: [
              "Singular values are ALWAYS non-negative real numbers, even if matrix entries or eigenvalues of A are negative.",
              "Columns of U and V must be paired consistently using u_i = (1 / sigma_i) * A * v_i to avoid sign contradictions.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Geometry of SVD & Principal Component Analysis",
              body: [
                "**Singular Value Decomposition (SVD)** generalizes eigendecomposition to non-square matrices of arbitrary shape `m x n`.",
                "**Geometric Meaning:**",
                "SVD decomposes any linear mapping into three sequential geometric operations: a rotation in the domain `V^T`, a coordinate stretching along orthogonal axes `Sigma`, and a rotation in the codomain `U`.",
                "**The Eckart-Young Low-Rank Approximation:**",
                "In data science, we frequently compress large datasets by discarding noisy dimensions. The best rank-k approximation in both Frobenius and spectral norm is the truncated SVD:",
                "`A_k = Sum_{i=1}^k sigma_i u_i v_i^T`.",
                "**PCA as SVD:**",
                "Given a mean-centered data matrix X (where column means are 0), computing SVD `X = U Sigma V^T` directly reveals:",
                "1. Principal component loading directions: Columns of `V`.",
                "2. Low-dimensional projections: `Z = X V = U Sigma`.",
                "3. Variances along principal axes: `lambda_i = sigma_i^2 / (N - 1)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Complete SVD & Rank-1 Approximation",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Use u_i = (1 / sigma_i) * A * v_i to ensure the left singular vectors have consistent signs with V.",
              solutionSteps: [
                "Problem: Find the singular values, SVD matrices, and the optimal rank-1 approximation A_1 for matrix A = [ [3, 2, 2], [2, 3, -2] ] (size 2 x 3). What fraction of the total variance is captured by A_1?",
                "Step 1: Compute A * A^T (size 2 x 2):",
                "  A * A^T = [ [3, 2, 2], [2, 3, -2] ] * [ [3, 2], [2, 3], [2, -2] ]",
                "  Entry (1, 1): 3^2 + 2^2 + 2^2 = 9 + 4 + 4 = 17.",
                "  Entry (1, 2): (3)(2) + (2)(3) + (2)(-2) = 6 + 6 - 4 = 8.",
                "  Entry (2, 2): 2^2 + 3^2 + (-2)^2 = 4 + 9 + 4 = 17.",
                "  A * A^T = [ [17, 8], [8, 17] ].",
                "Step 2: Find eigenvalues of A * A^T:",
                "  det([ [17 - lambda, 8], [8, 17 - lambda] ]) = 0",
                "  (17 - lambda)^2 - 64 = 0  =>  17 - lambda = +- 8.",
                "  lambda1 = 25,  lambda2 = 9.",
                "Step 3: Extract singular values:",
                "  sigma1 = sqrt(25) = 5.",
                "  sigma2 = sqrt(9) = 3.",
                "Step 4: Find left singular vectors u1 and u2 (eigenvectors of A A^T):",
                "  For lambda1 = 25: (A A^T - 25*I) u1 = 0  =>  [ [-8, 8], [8, -8] ] u1 = 0  =>  u1 = [ 1/sqrt(2), 1/sqrt(2) ]^T.",
                "  For lambda2 = 9:  (A A^T - 9*I) u2 = 0   =>  [ [8, 8], [8, 8] ] u2 = 0    =>  u2 = [ 1/sqrt(2), -1/sqrt(2) ]^T.",
                "Step 5: Compute right singular vectors v1 and v2 via v_i = (1 / sigma_i) * A^T * u_i:",
                "  v1 = (1 / 5) * [ [3, 2], [2, 3], [2, -2] ] * [ 1/sqrt(2), 1/sqrt(2) ]^T",
                "     = (1 / (5*sqrt(2))) * [ 3 + 2, 2 + 3, 2 - 2 ]^T = (1 / (5*sqrt(2))) * [ 5, 5, 0 ]^T = [ 1/sqrt(2), 1/sqrt(2), 0 ]^T.",
                "  v2 = (1 / 3) * [ [3, 2], [2, 3], [2, -2] ] * [ 1/sqrt(2), -1/sqrt(2) ]^T",
                "     = (1 / (3*sqrt(2))) * [ 3 - 2, 2 - 3, 2 - (-2) ]^T = (1 / (3*sqrt(2))) * [ 1, -1, 4 ]^T.",
                "Step 6: Compute optimal rank-1 approximation A_1 = sigma1 * u1 * v1^T:",
                "  A_1 = 5 * [ 1/sqrt(2), 1/sqrt(2) ]^T * [ 1/sqrt(2), 1/sqrt(2), 0 ]",
                "  A_1 = 5 * (1/2) * [ [1, 1, 0], [1, 1, 0] ] = [ [2.5, 2.5, 0], [2.5, 2.5, 0] ].",
                "Step 7: Compute explained variance fraction:",
                "  Total variance (Frobenius norm squared): sigma1^2 + sigma2^2 = 25 + 9 = 34.",
                "  Variance captured by A_1 = sigma1^2 / (sigma1^2 + sigma2^2) = 25 / 34 ≈ 0.7353 (73.53%).",
                "Conclusion: Singular values are {5, 3}, rank-1 approximation is A_1 = [ [2.5, 2.5, 0], [2.5, 2.5, 0] ], explaining 73.53% of total variance.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Linear Algebra and Learning from Data",
                  authors: "Gilbert Strang",
                  year: "2019",
                  publisher: "Wellesley-Cambridge Press",
                  relevance: "Chapter 1 & 2: Singular Values and Principal Components.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
