import { CourseMeta } from "./types";

export const MACHINE_LEARNING_COURSE: CourseMeta = {
  id: "machine-learning",
  title: "Machine Learning",
  slug: "machine-learning",
  subjectSlug: "machine-learning",
  shortTitle: "Machine Learning",
  icon: "🤖",
  color: "bg-purple-500",
  tagline:
    "Master closed-form regression math, Ridge/Lasso shrinkage, SVM maximum margin geometry, decision tree impurity, neural backpropagation, and unsupervised manifolds for GATE DA.",
  description:
    "A rigorous, first-principles academic study notebook covering supervised regression and classification models, kernel methods, ensemble architectures, multilayer perceptrons, clustering, dimensionality reduction, and model validation metrics. Designed specifically to match the highest-yield requirements of the official GATE Data Science & Artificial Intelligence (DA) curriculum.",
  level: "Undergraduate / GATE DA",
  estimatedHours: 48,
  prerequisites: [
    "Linear Algebra (matrix inversion, positive semi-definite matrices, rank, eigenvalues, SVD)",
    "Probability and Statistics (Bayes' rule, Gaussian distributions, expectation, variance, covariance)",
    "Calculus and Optimization (partial derivatives, gradient vectors, Hessian curvature, convex sets, Lagrange multipliers)",
  ],
  learningOutcomes: [
    "Derive the closed-form Ordinary Least Squares (OLS) normal equation and prove the geometric projection theorem",
    "Analyze the optimization geometries of L1 (Lasso) vs L2 (Ridge) regularizations and their mathematical impact on sparsity",
    "Derive the logistic sigmoid log-odds formulation and binary cross-entropy gradient update rules",
    "Calculate Shannon Entropy, Information Gain, and Gini Impurity for optimal decision tree node splitting",
    "Derive Fisher's linear discriminant criterion maximizing between-class scatter over within-class scatter for LDA classification",
    "Formulate primal and dual Support Vector Machine (SVM) optimization problems and apply Mercer kernel transformations",
    "Derive step-by-step backpropagation gradients across multi-layer perceptron layers using the multivariable chain rule",
    "Execute K-Means, K-Medoids, and Hierarchical agglomerative clustering algorithms with formal linkage metrics",
    "Derive Principal Component Analysis (PCA) through covariance eigendecomposition and evaluate models using ROC-AUC and Bias-Variance tradeoffs",
  ],
  gateScope: "GATE 2027 DA scope",
  gateBranches: ["da"],
  gateSyllabusTopics: [
    "Supervised Learning: Linear regression, simple and multiple, ridge and lasso, logistic regression, k-NN, naive Bayes, linear discriminant analysis (LDA)",
    "Decision Trees & Ensembles: ID3, CART, entropy, Gini impurity, random forests, bagging, boosting (AdaBoost)",
    "Support Vector Machines: Linear and non-linear SVM, maximum margin, slack variables, dual formulation, kernel trick",
    "Neural Networks: Multi-layer perceptrons, activation functions, loss functions, backpropagation algorithm",
    "Unsupervised Learning: K-means, k-medoids, hierarchical clustering, dimensionality reduction (PCA, t-SNE)",
    "Model Evaluation: Confusion matrix, precision, recall, F1-score, ROC-AUC, bias-variance tradeoff, cross-validation",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: LINEAR MODELS & REGULARIZATION
    // =========================================================================
    {
      id: "ml-module-1-linear-models",
      title: "Module 1: Linear Regression & Regularization (OLS, Ridge, Lasso)",
      slug: "linear-models-and-regularization",
      description:
        "Ordinary Least Squares (OLS) normal equations, geometric column-space projection, multicollinearity, Ridge (L2) shrinkage, and Lasso (L1) sparsity.",
      order: 1,
      lessons: [
        {
          id: "ols-linear-regression-normal-equations",
          title: "Ordinary Least Squares (OLS) & Normal Equation Derivations",
          slug: "ols-linear-regression-normal-equations",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Minimizing Residual Sum of Squares (RSS), matrix calculus derivations, and projection onto the column space.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "The OLS weight vector w* = (X^T X)^{-1} X^T y projects target vector y orthogonally onto the Column Space Col(X).",
            keyFormulasAndRules: [
              "Residual Sum of Squares (RSS): RSS(w) = ||y - Xw||_2^2 = (y - Xw)^T (y - Xw) = y^T y - 2 w^T X^T y + w^T X^T X w.",
              "Matrix Gradient: grad_w RSS(w) = -2 X^T y + 2 X^T X w = 0.",
              "Normal Equations: (X^T X) w* = X^T y.",
              "Projection Matrix (Hat Matrix): H = X (X^T X)^{-1} X^T. Hat matrix is symmetric (H^T = H) and idempotent (H^2 = H).",
              "Predicted Values: y_hat = H y. Residual Vector: e = y - y_hat = (I - H) y.",
              "Gauss-Markov Theorem: Under homoscedastic and uncorrelated errors, OLS estimator is BLUE (Best Linear Unbiased Estimator).",
            ],
            examPitfalls: [
              "The matrix X^T X is invertible if and only if design matrix X has FULL COLUMN RANK (columns of X are linearly independent).",
              "If features are collinear (multicollinearity), Det(X^T X) = 0 and OLS fails to yield a unique solution.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Linear Regression Formulation & Matrix Calculus",
              body: [
                "In linear regression, we model the relationship between an n x d feature matrix X and an n x 1 target vector y as: `y = Xw + epsilon`, where epsilon is an unobserved noise vector with mean zero and variance sigma^2 I.",
                "**Derivation of the Normal Equations:**",
                "1. Express the objective function as the quadratic scalar form: `L(w) = (y - Xw)^T (y - Xw) = y^T y - 2 w^T X^T y + w^T X^T X w`.",
                "2. Take the vector derivative with respect to w using standard matrix identities (`d(a^T w)/dw = a` and `d(w^T A w)/dw = 2 A w` for symmetric A):",
                "   `grad_w L(w) = - 2 X^T y + 2 X^T X w`.",
                "3. Set the gradient to zero to find the stationary point: `2 X^T X w = 2 X^T y => (X^T X) w = X^T y`.",
                "4. When X has full column rank, X^T X is positive definite and invertible: `w* = (X^T X)^{-1} X^T y`.",
              ],
              callout: {
                kind: "gate-tip",
                title: "Geometric Orthogonality of Residuals",
                message:
                  "The residual vector e = y - y_hat is strictly orthogonal to every column vector in X. Mathematically: X^T e = X^T (y - Xw*) = X^T y - X^T X (X^T X)^{-1} X^T y = 0. This is a recurring conceptual trap in GATE DA questions.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: 2D Feature Normal Equation Calculation",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Remember to prepend a column of 1s to account for the intercept term w0.",
              solutionSteps: [
                "Problem: Fit a line y = w0 + w1 * x through data points (1, 2), (2, 5), (3, 7) using Ordinary Least Squares.",
                "Step 1: Construct design matrix X and target y:",
                "  X = [ 1  1 ]",
                "      [ 1  2 ]",
                "      [ 1  3 ]",
                "  y = [ 2, 5, 7 ]^T",
                "Step 2: Compute X^T X:",
                "  X^T X = [ 1  1  1 ] [ 1  1 ] = [ 3   6 ]",
                "          [ 1  2  3 ] [ 1  2 ]   [ 6  14 ]",
                "                      [ 1  3 ]",
                "Step 3: Compute X^T y:",
                "  X^T y = [ 1  1  1 ] [ 2 ] = [ 14 ]",
                "          [ 1  2  3 ] [ 5 ]   [ 33 ]",
                "                      [ 7 ]",
                "Step 4: Invert (X^T X):",
                "  Det(X^T X) = (3)(14) - (6)(6) = 42 - 36 = 6.",
                "  (X^T X)^{-1} = (1/6) * [ 14  -6 ] = [ 7/3   -1 ]",
                "                         [ -6   3 ]   [ -1    1/2 ]",
                "Step 5: Multiply (X^T X)^{-1} * X^T y:",
                "  w0 = (7/3)(14) + (-1)(33) = 98/3 - 99/3 = -1/3 ≈ -0.333",
                "  w1 = (-1)(14) + (1/2)(33) = -14 + 16.5 = 2.5 = 5/2",
                "Final Model: y_hat = -0.333 + 2.5 * x.",
              ],
            },
            {
              type: "resources",
              heading: "3. Authoritative References",
              sources: [
                {
                  title: "The Elements of Statistical Learning (2nd Edition)",
                  authors: "Trevor Hastie, Robert Tibshirani, Jerome Friedman",
                  year: "2009",
                  publisher: "Springer",
                  relevance: "Chapter 3.2: Linear Regression Models and Least Squares geometric proofs.",
                },
                {
                  title: "Pattern Recognition and Machine Learning",
                  authors: "Christopher M. Bishop",
                  year: "2006",
                  publisher: "Springer",
                  relevance: "Chapter 3.1: Linear Basis Function Models and Normal Equation derivations.",
                },
              ],
            },
          ],
        },
        {
          id: "ridge-and-lasso-regularization",
          title: "Ridge (L2) vs Lasso (L1) Regularization & Geometric Sparsity",
          slug: "ridge-and-lasso-regularization",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Shrinkage mechanics, solving ill-conditioned matrices, L1 subgradients, and feature selection.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Ridge adds an L2 spherical ball penalty shrinking weights smoothly. Lasso adds an L1 diamond penalty driving weights to exact zeros.",
            keyFormulasAndRules: [
              "Ridge Objective (L2): min_w ||y - Xw||_2^2 + lambda * ||w||_2^2.",
              "Ridge Closed Form: w*_{ridge} = (X^T X + lambda * I)^{-1} X^T y.",
              "Lasso Objective (L1): min_w ||y - Xw||_2^2 + lambda * ||w||_1.",
              "SVD Representation of Ridge: w*_{ridge} = V (D^2 + lambda I)^{-1} D U^T y = Sum_{j=1}^d [ d_j^2 / (d_j^2 + lambda) ] * (u_j^T y / d_j) * v_j.",
              "Lasso Soft-Thresholding: For orthonormal X, w_j* = sign(w_j^{ols}) * max(0, |w_j^{ols}| - lambda/2).",
            ],
            examPitfalls: [
              "Ridge regression NEVER produces sparse weight vectors (weights approach zero asymptotically but rarely equal exact 0).",
              "Lasso has NO closed-form matrix solution because the L1 norm |w| has non-differentiable corners at w = 0.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Mathematical Duality Between L1 and L2 Norm Penalties",
              body: [
                "When features are collinear, the eigenvalues of X^T X approach zero, causing OLS weight variance to explode (`Var(w*) = sigma^2 (X^T X)^{-1}`). Regularization restores numerical stability by penalizing model complexity.",
                "**Ridge Regression (L2):**",
                "By adding `lambda * I` to `X^T X`, every eigenvalue is shifted upwards by lambda (`lambda_i(X^T X + lambda I) = lambda_i(X^T X) + lambda > 0`). Hence, the regularized matrix is strictly invertible even when columns are linearly dependent.",
                "**Why Lasso Produces Exact Sparsity:**",
                "The Lasso constraint region is a rotated hypercube (`Sum |w_i| <= C`), which features sharp corners on the coordinate axes. The elliptical contours of the quadratic RSS loss touch these corners first with high probability, setting entire dimensions to exact zero and performing embedded feature selection.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Ridge Shrinkage Computation",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Ensure lambda is added along the diagonal of X^T X, not added to individual elements.",
              solutionSteps: [
                "Problem: An orthonormal design matrix X satisfies X^T X = I. If the OLS estimate is w_{ols} = [4, -2]^T and Ridge regularization parameter is lambda = 1, find the Ridge weight vector w_{ridge}.",
                "Step 1: Write Ridge closed-form formula for orthonormal features:",
                "  w_{ridge} = (X^T X + lambda * I)^{-1} X^T y",
                "Step 2: Since X^T y = (X^T X) w_{ols} = I * w_{ols} = w_{ols}:",
                "  w_{ridge} = (I + lambda * I)^{-1} w_{ols} = [ (1 + lambda) I ]^{-1} w_{ols} = [ 1 / (1 + lambda) ] * w_{ols}",
                "Step 3: Substitute lambda = 1:",
                "  w_{ridge} = [ 1 / (1 + 1) ] * [ 4, -2 ]^T = (1/2) * [ 4, -2 ]^T = [ 2, -1 ]^T.",
                "Conclusion: Under orthonormal features, Ridge shrinks every parameter uniformly by a factor of 1 / (1 + lambda).",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Statistical Learning with Sparsity: The Lasso and Generalizations",
                  authors: "Trevor Hastie, Robert Tibshirani, Martin Wainwright",
                  year: "2015",
                  publisher: "CRC Press",
                  relevance: "Chapter 2: The Lasso and Soft-Thresholding geometric proofs.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: CLASSIFICATION & PROBABILISTIC MODELS
    // =========================================================================
    {
      id: "ml-module-2-classification",
      title: "Module 2: Logistic Regression, k-NN, Naive Bayes & LDA",
      slug: "classification-models",
      description:
        "Sigmoid activation, log-odds, binary cross-entropy MLE, k-Nearest Neighbors distance metrics, Naive Bayes with Laplace smoothing, and Fisher's Linear Discriminant Analysis (LDA).",
      order: 2,
      lessons: [
        {
          id: "logistic-regression-and-cross-entropy",
          title: "Logistic Regression, Logit Link & Cross-Entropy Optimization",
          slug: "logistic-regression-and-cross-entropy",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Sigmoid mapping, maximum likelihood estimation, odds ratios, and linear decision boundaries.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Logistic Regression is a linear classifier because the log-odds (logit) is a linear combination of features: ln(p / (1 - p)) = w^T x.",
            keyFormulasAndRules: [
              "Sigmoid Function: sigma(z) = 1 / (1 + e^{-z}) = e^z / (1 + e^z).",
              "Sigmoid Derivative: d sigma(z) / dz = sigma(z) * (1 - sigma(z)).",
              "Odds Ratio: Odds = p / (1 - p). Logit: ln(Odds) = w^T x + b.",
              "Binary Cross-Entropy Loss: J(w) = - (1/n) * Sum_{i=1}^n [ y_i * ln(p_i) + (1 - y_i) * ln(1 - p_i) ].",
              "Gradient of Cross-Entropy: grad_w J(w) = (1/n) * X^T (p - y), identical in form to OLS gradient!",
            ],
            examPitfalls: [
              "Logistic regression predicts probabilities, but the decision boundary (where p = 0.5 => w^T x = 0) is strictly HYPERPLANAR (linear).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Probabilistic Derivation of Logistic Regression",
              body: [
                "Unlike linear regression, which predicts an unbounded real value y in R, binary classification requires mapping predictions to the probability interval [0, 1].",
                "**Maximum Likelihood Estimation (MLE):**",
                "Assuming training examples are independently Bernoulli-distributed:",
                "`L(w) = Product_{i=1}^n p_i^{y_i} (1 - p_i)^{1 - y_i}`.",
                "Taking the natural log gives the Log-Likelihood:",
                "`ln L(w) = Sum_{i=1}^n [ y_i ln(p_i) + (1 - y_i) ln(1 - p_i) ]`.",
                "Minimizing the negative log-likelihood per sample yields the Binary Cross-Entropy Loss function.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Odds and Probability Calculation",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Do not confuse Odds = p / (1-p) with Probability p = Odds / (1 + Odds).",
              solutionSteps: [
                "Problem: A logistic regression model outputs w^T x = 1.386 for an input instance. What are the predicted odds and probability p that the instance belongs to the positive class?",
                "Step 1: Compute Odds:",
                "  Odds = e^{w^T x} = e^{1.386} ≈ 4.0",
                "Step 2: Compute Probability p:",
                "  p = Odds / (1 + Odds) = 4 / (1 + 4) = 4 / 5 = 0.80 (80%).",
                "Verification via Sigmoid:",
                "  sigma(1.386) = 1 / (1 + e^{-1.386}) = 1 / (1 + 0.25) = 1 / 1.25 = 0.80.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Machine Learning: A Probabilistic Perspective",
                  authors: "Kevin P. Murphy",
                  year: "2012",
                  publisher: "MIT Press",
                  relevance: "Chapter 8: Logistic Regression and GLMs.",
                },
              ],
            },
          ],
        },
        {
          id: "knn-and-naive-bayes-classifiers",
          title: "k-Nearest Neighbors & Naive Bayes with Laplace Smoothing",
          slug: "knn-and-naive-bayes-classifiers",
          order: 2,
          estimatedMinutes: 28,
          tagline: "Voronoi decision cells, non-parametric boundary complexity, conditional independence, and add-1 smoothing.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "In k-NN, k=1 has maximum variance (overfitting); large k has maximum bias (underfitting). Naive Bayes uses conditional independence P(x|y) = Prod P(xi|y).",
            keyFormulasAndRules: [
              "Euclidean Distance: d(x, z) = sqrt( Sum_{j=1}^d (x_j - z_j)^2 ). Manhattan: d(x, z) = Sum |x_j - z_j|.",
              "Minkowski Metric: d_p(x, z) = ( Sum |x_j - z_j|^p )^{1/p}.",
              "Naive Bayes Posterior: P(y=c | x) proportional to P(y=c) * Product_{j=1}^d P(x_j | y=c).",
              "Laplace (Add-1) Smoothing: P(x_j = v | y=c) = ( Count(x_j=v, y=c) + 1 ) / ( Count(y=c) + |V_j| ), where |V_j| is the number of possible values for feature j.",
            ],
            examPitfalls: [
              "When calculating Laplace smoothing, the denominator must add |V_j| (the number of distinct values feature j can take), NOT the total number of classes.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Instance-Based vs Generative Classifiers",
              body: [
                "**k-Nearest Neighbors (k-NN):** A non-parametric, lazy-learning algorithm that makes predictions based on the majority label among the k closest training points.",
                "**The Bias-Variance Knobs of k-NN:**",
                "- Small k (e.g. k=1): Complex, highly flexible decision boundary. High variance, zero training error, sensitive to outliers.",
                "- Large k (e.g. k=N): Oversmoothed decision boundary predicting the global majority class. High bias.",
                "**Naive Bayes:** A generative probabilistic classifier that assumes all features are conditionally independent given the class label. While the conditional independence assumption is rarely true in reality, Naive Bayes performs surprisingly well for high-dimensional text classification.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Laplace Smoothing Calculation",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Do not forget to smooth both positive and negative conditional frequencies when estimating probabilities from sparse data.",
              solutionSteps: [
                "Problem: In a binary text classification training set of 20 documents (12 Spam, 8 Ham), the word 'prize' appears in 6 Spam documents and 0 Ham documents. If the vocabulary size is |V| = 1000 words, compute the Laplace-smoothed probability P('prize' | Ham).",
                "Step 1: Identify given parameters:",
                "  Count('prize', Ham) = 0",
                "  Total words in Ham documents = N_Ham = 800 words",
                "  Vocabulary size |V| = 1000 words",
                "Step 2: Apply Laplace Add-1 Smoothing formula:",
                "  P('prize' | Ham) = [ Count('prize', Ham) + 1 ] / [ N_Ham + |V| ]",
                "Step 3: Substitute values:",
                "  P('prize' | Ham) = (0 + 1) / (800 + 1000) = 1 / 1800 ≈ 0.000556.",
                "Conclusion: Without Laplace smoothing, P('prize' | Ham) would be 0, zeroing out the entire posterior probability Product.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Pattern Recognition and Machine Learning",
                  authors: "Christopher M. Bishop",
                  year: "2006",
                  publisher: "Springer",
                  relevance: "Chapter 2.5: Non-parametric methods and nearest-neighbour density estimation.",
                },
              ],
            },
          ],
        },
        {
          id: "linear-discriminant-analysis",
          title: "Linear Discriminant Analysis (LDA) & Fisher's Criterion",
          slug: "linear-discriminant-analysis",
          order: 3,
          estimatedMinutes: 32,
          tagline: "Maximizing between-class separation while minimizing within-class variance, Fisher's ratio, and Bayes optimal boundaries.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "LDA projects data onto a direction w that maximizes between-class variance relative to within-class variance: w* = S_W^{-1} (mu_1 - mu_2).",
            keyFormulasAndRules: [
              "Fisher's Criterion Objective: J(w) = (w^T S_B w) / (w^T S_W w), where S_B is between-class scatter and S_W is within-class scatter.",
              "Between-Class Scatter (Binary): S_B = (mu_1 - mu_2) (mu_1 - mu_2)^T (Rank 1 matrix).",
              "Within-Class Scatter: S_W = S_1 + S_2 = Sum_{x in C_1} (x - mu_1)(x - mu_1)^T + Sum_{x in C_2} (x - mu_2)(x - mu_2)^T.",
              "Optimal Projection Vector: w* = S_W^{-1} (mu_1 - mu_2). Derived by setting grad_w J(w) = 0 and solving the generalized eigenvalue problem S_B w = lambda S_W w.",
              "Maximum Projected Dimensions: For C classes, rank(S_B) <= C - 1. Therefore, LDA can project into at most C - 1 dimensions.",
              "Bayes Optimality Assumptions: LDA is equivalent to the Bayes optimal classifier if class-conditional distributions are Gaussian N(mu_c, Sigma) with IDENTICAL (shared) covariance matrices Sigma_1 = Sigma_2 = ... = Sigma_C.",
              "LDA vs QDA: If class covariance matrices are unequal (Sigma_1 != Sigma_2), the quadratic term in the log-posterior does not cancel, yielding Quadratic Discriminant Analysis (QDA).",
            ],
            examPitfalls: [
              "LDA requires S_W to be INVERTIBLE (full rank). If number of features d > number of samples n (high-dimensional regime), S_W is singular. PCA is often applied first (PCA-LDA).",
              "LDA is a SUPERVISED dimensionality reduction and classification method (uses class labels to maximize separation), whereas PCA is UNSUPERVISED (maximizes total data variance without knowing labels).",
              "For C classes, the maximum number of discriminant directions is min(d, C - 1). For binary classification (C = 2), LDA projects to at most 1 dimension!",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Theoretical Derivation of Fisher's Linear Discriminant",
              body: [
                "While PCA finds directions of maximum variance regardless of class labels, Linear Discriminant Analysis (LDA) is a supervised dimensionality reduction technique and linear classifier originally formulated by Ronald Fisher in 1936.",
                "**Fisher's Objective Criterion:**",
                "Consider projecting d-dimensional data vector x onto a 1-dimensional line via scalar projection: `y = w^T x`. Let mu_1 and mu_2 be the class sample means. The projected means are `m_1 = w^T mu_1` and `m_2 = w^T mu_2`.",
                "The difference between projected means squared is: `(m_1 - m_2)^2 = (w^T (mu_1 - mu_2))^2 = w^T (mu_1 - mu_2)(mu_1 - mu_2)^T w = w^T S_B w`, where `S_B = (mu_1 - mu_2)(mu_1 - mu_2)^T` is the Between-Class Scatter Matrix.",
                "The projected within-class scatter is: `s_1^2 + s_2^2 = Sum_{x in C_1} (w^T x - w^T mu_1)^2 + Sum_{x in C_2} (w^T x - w^T mu_2)^2 = w^T S_W w`, where `S_W = S_1 + S_2` is the Within-Class Scatter Matrix.",
                "Fisher's criterion maximizes the ratio of between-class scatter to within-class scatter: `J(w) = (w^T S_B w) / (w^T S_W w)`.",
                "**Solving for the Optimal Projection Vector w\*:**",
                "Differentiating J(w) with respect to w and setting to zero yields the generalized eigenvalue problem: `S_B w = lambda S_W w`.",
                "Notice that `S_B w = (mu_1 - mu_2)(mu_1 - mu_2)^T w`. The term `(mu_1 - mu_2)^T w` is simply a scalar alpha. Thus, `S_B w = alpha (mu_1 - mu_2)` always points in the direction of the mean difference vector!",
                "Substituting this into the eigenvalue equation: `lambda S_W w = alpha (mu_1 - mu_2) => w* = S_W^{-1} (mu_1 - mu_2)` (ignoring unimportant scalar scaling factor alpha / lambda).",
              ],
              callout: {
                kind: "gate-tip",
                title: "LDA vs PCA & The Gaussian Generative View",
                message:
                  "Under the probabilistic generative perspective, if each class c follows a multivariate normal distribution N(mu_c, Sigma) with a shared covariance matrix Sigma, the log-posterior ratio ln(P(C_1|x) / P(C_2|x)) is strictly linear in x with weight vector w = Sigma^{-1} (mu_1 - mu_2). If class covariances differ (Sigma_1 != Sigma_2), the quadratic term x^T Sigma_c^{-1} x does not cancel, yielding Quadratic Discriminant Analysis (QDA).",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: 2D Fisher's Linear Discriminant Derivation",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Do not invert individual class matrices S_1 and S_2. You must sum them first to form S_W = S_1 + S_2 before inverting.",
              solutionSteps: [
                "Problem: A 2D binary classification problem has two classes C1 and C2 with sample means: mu_1 = [1, 2]^T and mu_2 = [3, 4]^T. The class scatter matrices are: S_1 = [ 2  1 ] / [ 1  2 ] and S_2 = [ 1  0 ] / [ 0  1 ]. Compute the optimal Fisher linear projection vector w*.",
                "Step 1: Compute the mean difference vector (mu_1 - mu_2):",
                "  mu_1 - mu_2 = [ 1 - 3, 2 - 4 ]^T = [ -2, -2 ]^T",
                "Step 2: Compute Within-Class Scatter Matrix S_W = S_1 + S_2:",
                "  S_W = [ 2  1 ] + [ 1  0 ] = [ 3  1 ]",
                "        [ 1  2 ]   [ 0  1 ]   [ 1  3 ]",
                "Step 3: Invert S_W:",
                "  Determinant Det(S_W) = (3)(3) - (1)(1) = 9 - 1 = 8.",
                "  S_W^{-1} = (1/8) * [ 3  -1 ]",
                "                     [ -1  3 ]",
                "Step 4: Compute w* = S_W^{-1} (mu_1 - mu_2):",
                "  w* = (1/8) * [ 3  -1 ] [ -2 ] = (1/8) * [ 3(-2) + (-1)(-2) ] = (1/8) * [ -6 + 2 ] = (1/8) * [ -4 ] = [ -1/2 ]",
                "               [ -1  3 ] [ -2 ]           [ (-1)(-2) + 3(-2) ]         [  2 - 6 ]          [ -4 ]   [ -1/2 ]",
                "Step 5: Simplify direction:",
                "  w* is proportional to [ 1, 1 ]^T or [ -1, -1 ]^T.",
                "Conclusion: The optimal 1D line that maximizes class separability is y = x_1 + x_2. Projecting data onto w* collapses 2D coordinates into a 1D scalar where class overlap is minimized.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "The Elements of Statistical Learning (2nd Edition)",
                  authors: "Trevor Hastie, Robert Tibshirani, Jerome Friedman",
                  year: "2009",
                  publisher: "Springer",
                  relevance: "Chapter 4.3: Linear Discriminant Analysis, Fisher's discriminant criterion, and QDA boundaries.",
                },
                {
                  title: "Pattern Recognition and Machine Learning",
                  authors: "Christopher M. Bishop",
                  year: "2006",
                  publisher: "Springer",
                  relevance: "Chapter 4.1.4: Fisher's linear discriminant for two classes and multi-class generalization.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: DECISION TREES & ENSEMBLE METHODS
    // =========================================================================
    {
      id: "ml-module-3-trees-ensembles",
      title: "Module 3: Decision Trees (ID3, CART) & Ensemble Methods",
      slug: "trees-and-ensembles",
      description:
        "Shannon Entropy, Information Gain, Gini Impurity, CART pruning, Bootstrap Aggregation (Bagging), Random Forests, and AdaBoost.",
      order: 3,
      lessons: [
        {
          id: "decision-trees-id3-and-cart",
          title: "Decision Trees: Shannon Entropy, Information Gain & Gini Index",
          slug: "decision-trees-id3-and-cart",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Impurity splitting metrics, ID3 vs CART, continuous feature thresholds, and cost-complexity pruning.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "ID3 splits on Maximum Information Gain using Entropy. CART splits on Minimum Gini Impurity (binary splits).",
            keyFormulasAndRules: [
              "Shannon Entropy: H(S) = - Sum_{c=1}^C p_c log_2(p_c). Max entropy = log_2(C) (uniform distribution); Min entropy = 0 (pure).",
              "Information Gain: Gain(S, A) = H(S) - Sum_{v in Values(A)} [ |S_v| / |S| ] * H(S_v).",
              "Gini Impurity: Gini(S) = 1 - Sum_{c=1}^C p_c^2. For binary classification, Gini_max = 0.5 (at p=0.5).",
              "Variance Reduction (Regression Trees): Variance = (1/N) Sum (y_i - y_bar)^2.",
            ],
            examPitfalls: [
              "Information Gain is biased towards features with numerous distinct values (e.g. ID numbers). Gain Ratio normalizes by Split Information.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Mathematics of Tree Splitting Criteria",
              body: [
                "Decision trees recursively partition input feature space into orthogonal hyper-rectangles using greedy impurity reduction.",
                "**Entropy vs Gini Impurity:**",
                "Both measure the impurity of a node. Gini impurity is computationally faster because it avoids logarithmic evaluations (`log_2`). For a binary classification task:",
                "- `Entropy = - [ p log_2(p) + (1-p) log_2(1-p) ]` (peaks at 1.0 bit when p=0.5).",
                "- `Gini = 1 - [ p^2 + (1-p)^2 ] = 2p(1-p)` (peaks at 0.5 when p=0.5).",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Information Gain on Discrete Features",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Remember to weight each child entropy by its proportion |S_v| / |S|.",
              solutionSteps: [
                "Problem: A dataset of 10 samples has 6 Positive (+) and 4 Negative (-) instances. A feature splits it into Left (4+, 1-) and Right (2+, 3-). Compute the Information Gain.",
                "Step 1: Compute Parent Entropy H(S):",
                "  p+ = 6/10 = 0.6, p- = 4/10 = 0.4",
                "  H(S) = - [ 0.6 * log2(0.6) + 0.4 * log2(0.4) ] = - [ 0.6*(-0.737) + 0.4*(-1.322) ] = 0.442 + 0.529 = 0.971 bits.",
                "Step 2: Compute Left Child Entropy H(S_L) [4+, 1-]:",
                "  p+ = 4/5 = 0.8, p- = 1/5 = 0.2",
                "  H(S_L) = - [ 0.8*log2(0.8) + 0.2*log2(0.2) ] = - [ 0.8*(-0.322) + 0.2*(-2.322) ] = 0.258 + 0.464 = 0.722 bits.",
                "Step 3: Compute Right Child Entropy H(S_R) [2+, 3-]:",
                "  p+ = 2/5 = 0.4, p- = 3/5 = 0.6",
                "  H(S_R) = 0.971 bits (same distribution as parent).",
                "Step 4: Compute Weighted Child Entropy:",
                "  E[H] = (5/10) * H(S_L) + (5/10) * H(S_R) = 0.5 * (0.722 + 0.971) = 0.5 * 1.693 = 0.8465 bits.",
                "Step 5: Compute Information Gain:",
                "  Gain = H(S) - E[H] = 0.971 - 0.8465 = 0.1245 bits.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Classification and Regression Trees",
                  authors: "Leo Breiman, Jerome Friedman, Richard Olshen, Charles Stone",
                  year: "1984",
                  publisher: "Wadsworth",
                  relevance: "The foundational text establishing the CART methodology and Gini impurity.",
                },
              ],
            },
          ],
        },
        {
          id: "ensemble-methods-bagging-and-boosting",
          title: "Ensemble Learning: Random Forests, Bagging & AdaBoost",
          slug: "ensemble-methods-bagging-and-boosting",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Bootstrap aggregation, decorrelating trees, out-of-bag validation, and adaptive sample reweighting.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Bagging (Random Forests) reduces VARIANCE by averaging independent models. Boosting (AdaBoost) reduces BIAS by sequentially correcting weak learners.",
            keyFormulasAndRules: [
              "Bootstrap Sampling Probability: Probability a sample is NOT selected in N draws = (1 - 1/N)^N -> 1/e ≈ 36.8% (Out-of-Bag data).",
              "Random Forest Feature Subsampling: For classification with d features, split across floor(sqrt(d)) randomly chosen features at each node.",
              "AdaBoost Classifier Weight: alpha_m = (1/2) * ln( (1 - eps_m) / eps_m ), where eps_m is weighted error.",
              "AdaBoost Sample Weight Update: w_{i, m+1} = w_{i, m} * exp( - alpha_m * y_i * h_m(x_i) ) / Z_m.",
            ],
            examPitfalls: [
              "Random Forests do NOT overfit as the number of trees increases (generalization error converges to a finite bound by Strong Law of Large Numbers).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Variance-Reduction Mechanics of Ensembles",
              body: [
                "**Bagging (Bootstrap Aggregation):**",
                "Draws B independent bootstrap samples with replacement from training dataset D, fits a deep high-variance tree to each, and aggregates by voting (classification) or averaging (regression).",
                "If individual trees have variance sigma^2 and pairwise correlation rho, the ensemble variance is: `Var(Ensemble) = rho * sigma^2 + [ (1 - rho) / B ] * sigma^2`.",
                "**Random Forest Innovation:** By forcing each tree node to choose from a random subset of sqrt(d) features, trees are decorrelated, significantly lowering rho and crushing variance.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: AdaBoost Classifier Weighting",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "If an error rate eps_m >= 0.5, the weak learner performs no better than random guessing.",
              solutionSteps: [
                "Problem: An AdaBoost weak learner produces a training error rate eps = 0.20 on weighted training data. Compute the stage weight alpha assigned to this learner.",
                "Step 1: Write AdaBoost weight formula:",
                "  alpha = (1/2) * ln[ (1 - eps) / eps ]",
                "Step 2: Substitute eps = 0.20:",
                "  (1 - 0.20) / 0.20 = 0.80 / 0.20 = 4.0",
                "Step 3: Compute natural logarithm:",
                "  ln(4.0) ≈ 1.3863",
                "Step 4: Compute alpha:",
                "  alpha = (1/2) * 1.3863 = 0.69315.",
                "Interpretation: Because the learner error was low (20%), it receives a positive vote weight of ~0.69 in the final majority decision.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "The Elements of Statistical Learning (2nd Edition)",
                  authors: "Hastie, Tibshirani, Friedman",
                  year: "2009",
                  publisher: "Springer",
                  relevance: "Chapter 10 & 15: Boosting and Additive Trees, and Random Forests.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: SUPPORT VECTOR MACHINES & KERNEL METHODS
    // =========================================================================
    {
      id: "ml-module-4-svm-kernels",
      title: "Module 4: Support Vector Machines (SVM) & Kernel Methods",
      slug: "support-vector-machines",
      description:
        "Maximum margin hyperplane geometry, hard/soft margin primal-dual formulations, support vectors, and non-linear Mercer kernels.",
      order: 4,
      lessons: [
        {
          id: "support-vector-machines-hard-and-soft-margin",
          title: "SVM Maximum Margin Hyperplane & Dual Optimization",
          slug: "support-vector-machines-hard-and-soft-margin",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Geometric margin 2/||w||, Lagrangian multipliers, KKT complementary slackness, and slack variables.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Maximizing geometric margin 2/||w|| is equivalent to minimizing (1/2)||w||^2 subject to y_i(w^T x_i + b) >= 1.",
            keyFormulasAndRules: [
              "Primal Hard-Margin Problem: min_{w, b} (1/2) ||w||_2^2 s.t. y_i (w^T x_i + b) >= 1 for all i.",
              "Primal Soft-Margin Problem: min_{w, b, xi} (1/2) ||w||_2^2 + C Sum_{i=1}^n xi_i s.t. y_i (w^T x_i + b) >= 1 - xi_i, xi_i >= 0.",
              "Dual Formulation: max_{alpha} Sum alpha_i - (1/2) Sum_{i, j} alpha_i alpha_j y_i y_j (x_i^T x_j) s.t. 0 <= alpha_i <= C and Sum alpha_i y_i = 0.",
              "Weight Recovery: w* = Sum_{i=1}^n alpha_i y_i x_i. Only Support Vectors have alpha_i > 0!",
              "KKT Complementary Slackness: alpha_i * [ y_i (w^T x_i + b) - 1 + xi_i ] = 0.",
            ],
            examPitfalls: [
              "Non-support vectors have alpha_i = 0 and have ZERO influence on the resulting hyperplane.",
              "Large C penalizes margin violations heavily (approaches hard-margin, risks overfitting). Small C allows wider margin with more violations (higher bias).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Geometry of the Maximum Margin Separator",
              body: [
                "Given linearly separable training data with labels y_i in {-1, +1}, infinite hyperplanes `w^T x + b = 0` can separate the classes.",
                "**The Optimal Margin Criterion:**",
                "The distance from any point x to the hyperplane is `|w^T x + b| / ||w||`. For canonical support vectors on the margin boundary `|w^T x + b| = 1`, the margin width between the two boundary planes `w^T x + b = +1` and `w^T x + b = -1` is exactly: `Margin = 2 / ||w||`.",
                "Maximizing `2 / ||w||` is mathematically equivalent to minimizing the convex quadratic objective `(1/2) ||w||^2`, guaranteeing a unique global minimum without local optima.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Support Vector Hyperplane Calculation",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Use the KKT condition alpha_1 y_1 + alpha_2 y_2 + alpha_3 y_3 = 0 to solve dual multipliers.",
              solutionSteps: [
                "Problem: Find the maximum margin hyperplane for 3 support vectors: Positive (+1) at (2, 0) and (0, 2); Negative (-1) at (0, 0).",
                "Step 1: Inspect the geometric midpoint boundary:",
                "  The positive points form line x1 + x2 = 2.",
                "  The negative point is at (0, 0) where x1 + x2 = 0.",
                "  The separating hyperplane lies exactly halfway: x1 + x2 - 1 = 0.",
                "Step 2: Check support vector canonical equations:",
                "  At (2, 0): w1(2) + w2(0) + b = +1 => 2 w1 + b = 1",
                "  At (0, 2): w1(0) + w2(2) + b = +1 => 2 w2 + b = 1 => w1 = w2",
                "  At (0, 0): w1(0) + w2(0) + b = -1 => b = -1",
                "Step 3: Solve for weights:",
                "  2 w1 - 1 = 1 => 2 w1 = 2 => w1 = 1, w2 = 1.",
                "  Weight vector w = [1, 1]^T, b = -1.",
                "Step 4: Compute Margin width:",
                "  ||w|| = sqrt(1^2 + 1^2) = sqrt(2).",
                "  Margin = 2 / ||w|| = 2 / sqrt(2) = sqrt(2) ≈ 1.414.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "An Introduction to Support Vector Machines",
                  authors: "Nello Cristianini, John Shawe-Taylor",
                  year: "2000",
                  publisher: "Cambridge University Press",
                  relevance: "Chapter 5: Optimization theory, KKT conditions, and dual formulations for SVMs.",
                },
              ],
            },
          ],
        },
        {
          id: "kernel-trick-and-non-linear-svms",
          title: "The Kernel Trick, Mercer's Theorem & RBF Kernels",
          slug: "kernel-trick-and-non-linear-svms",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Inner products in Hilbert spaces, Polynomial kernels, Gaussian RBF, and Mercer positive semi-definiteness.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "The Kernel Trick replaces inner product x_i^T x_j with K(x_i, x_j) = phi(x_i)^T phi(x_j), mapping data to high dimensions without explicit transformation.",
            keyFormulasAndRules: [
              "Mercer's Theorem: A symmetric function K(x, z) is a valid kernel iff its Gram Matrix K_{ij} = K(x_i, x_j) is Positive Semi-Definite for any dataset.",
              "Linear Kernel: K(x, z) = x^T z.",
              "Polynomial Kernel: K(x, z) = (x^T z + c)^d (Dimension of feature space is (d + n)! / (d! n!)).",
              "Gaussian / Radial Basis Function (RBF) Kernel: K(x, z) = exp( - gamma * ||x - z||^2 ) = exp( - ||x - z||^2 / (2 sigma^2) ).",
              "RBF Dimension: Corresponds to an INFINITE-dimensional feature Hilbert space via Taylor series expansion of exp(.)!",
            ],
            examPitfalls: [
              "Large gamma in RBF kernel leads to a narrow Gaussian bell curve (overfitting / memorizing data points). Small gamma leads to oversmoothing (underfitting).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Power of Mercer Kernels in High Dimensions",
              body: [
                "When data is not linearly separable in the original input space R^d (e.g. concentric circles or the XOR problem), we map samples into a higher-dimensional feature space R^D via non-linear mapping `phi(x)`.",
                "**Why Explicit Mapping Fails:** Computing `phi(x)` explicitly in 10,000 dimensions is computationally intractable in time and memory.",
                "**The Kernel Miracle:** Notice that in the SVM dual formulation, features appear ONLY through the dot product `x_i^T x_j`. By substituting `K(x_i, x_j) = phi(x_i)^T phi(x_j)`, we perform optimal maximum margin separation in an infinite-dimensional space while computing only simple scalar distances in original O(d) time!",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Polynomial Kernel Explicit Mapping Verification",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Remember the sqrt(2) scaling factor on cross-terms when deriving the explicit feature vector phi(x).",
              solutionSteps: [
                "Problem: For 2D vectors x = [x1, x2]^T and z = [z1, z2]^T, show that the kernel K(x, z) = (x^T z)^2 corresponds to an explicit 3D feature mapping phi(x).",
                "Step 1: Expand the algebraic dot product:",
                "  x^T z = x1 z1 + x2 z2",
                "Step 2: Square the sum:",
                "  (x^T z)^2 = (x1 z1 + x2 z2)^2 = (x1 z1)^2 + 2 (x1 z1)(x2 z2) + (x2 z2)^2",
                "  = (x1^2) (z1^2) + [ sqrt(2) x1 x2 ] [ sqrt(2) z1 z2 ] + (x2^2) (z2^2)",
                "Step 3: Define explicit mapping phi(x):",
                "  phi(x) = [ x1^2, sqrt(2) x1 x2, x2^2 ]^T",
                "Step 4: Verify dot product:",
                "  phi(x)^T phi(z) = x1^2 z1^2 + 2 x1 x2 z1 z2 + x2^2 z2^2 = (x^T z)^2 = K(x, z).",
                "Conclusion: K(x, z) maps 2D coordinates into a 3D parabolic feature space where quadratic boundaries become linear hyperplanes.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Kernel Methods for Pattern Analysis",
                  authors: "John Shawe-Taylor, Nello Cristianini",
                  year: "2004",
                  publisher: "Cambridge University Press",
                  relevance: "Chapter 2 & 3: Properties of Kernels and Mercer's theorem conditions.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: NEURAL NETWORKS & BACKPROPAGATION
    // =========================================================================
    {
      id: "ml-module-5-neural-networks",
      title: "Module 5: Multilayer Perceptrons & Backpropagation Math",
      slug: "neural-networks-and-backprop",
      description:
        "Perceptrons, activation functions (Sigmoid, Tanh, ReLU), Universal Approximation, multivariable chain rule, and Backpropagation updates.",
      order: 5,
      lessons: [
        {
          id: "multilayer-perceptrons-and-activation-functions",
          title: "Multilayer Perceptrons, Non-Linear Activations & Vanishing Gradients",
          slug: "multilayer-perceptrons-and-activation-functions",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Overcoming linear separability, Universal Approximation Theorem, and ReLU non-saturating gradients.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "A neural network without non-linear activation functions collapses into a single-layer linear model: W2 * (W1 * x) = (W2 * W1) * x = W_eff * x.",
            keyFormulasAndRules: [
              "Universal Approximation Theorem (Cybenko 1989): A feedforward network with a single hidden layer containing finite non-linear neurons can approximate any continuous function on compact subsets of R^n.",
              "Sigmoid: sigma(z) = 1 / (1 + e^{-z}); max derivative is 0.25 (at z=0). Causes vanishing gradients in deep networks!",
              "Tanh: tanh(z) = (e^z - e^{-z}) / (e^z + e^{-z}); zero-centered; max derivative is 1.0 (at z=0).",
              "ReLU: ReLU(z) = max(0, z); Derivative is 1 for z > 0, 0 for z < 0. Avoids vanishing gradient for positive activations.",
              "Leaky ReLU: max(alpha * z, z) with alpha ≈ 0.01 to prevent the 'Dying ReLU' problem.",
            ],
            examPitfalls: [
              "Initializing all weights to zero in a neural network causes SYMMETRIC updates across all hidden neurons, preventing the network from learning diverse features.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Architectural Foundations of Deep Learning",
              body: [
                "In 1969, Minsky and Papert proved that single-layer perceptrons cannot learn simple non-linear logical functions such as XOR.",
                "**Why Multilayer Networks Succeed:**",
                "By composing linear affine transformations `z = Wx + b` with non-linear activation functions `a = g(z)`, neural networks bend and fold feature space, allowing complex non-linear classification boundaries to become linearly separable at the final output layer.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: XOR Architecture Minimum Parameters",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Remember to count both weights and bias parameters in each layer.",
              solutionSteps: [
                "Problem: What is the minimum number of hidden neurons in a 1-hidden layer MLP (with step or ReLU activation) required to solve the 2-input XOR problem?",
                "Step 1: Understand XOR truth table:",
                "  Inputs: (0, 0)->0, (0, 1)->1, (1, 0)->1, (1, 1)->0.",
                "Step 2: Linear boundaries required:",
                "  XOR requires TWO separating hyperplanes (e.g. x1 + x2 >= 0.5 AND x1 + x2 <= 1.5).",
                "Step 3: Minimum Hidden Neurons = 2 hidden units.",
                "Step 4: Count total trainable parameters (weights + biases):",
                "  Layer 1 (2 inputs -> 2 hidden): 2 x 2 weights + 2 biases = 6 parameters.",
                "  Layer 2 (2 hidden -> 1 output): 2 x 1 weights + 1 bias = 3 parameters.",
                "Total Parameters = 6 + 3 = 9 parameters.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Deep Learning",
                  authors: "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
                  year: "2016",
                  publisher: "MIT Press",
                  relevance: "Chapter 6: Deep Feedforward Networks and activation function behavior.",
                },
              ],
            },
          ],
        },
        {
          id: "backpropagation-and-neural-optimization",
          title: "The Backpropagation Algorithm: Multivariable Chain Rule Derivation",
          slug: "backpropagation-and-neural-optimization",
          order: 2,
          estimatedMinutes: 34,
          tagline: "Backward error propagation, intermediate sensitivity deltas, computational graphs, and SGD updates.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Backpropagation propagates the error delta_j backward using the chain rule: dL/dw_{jk} = delta_j * a_k.",
            keyFormulasAndRules: [
              "Forward Pass: z_j^{(l)} = Sum_k w_{jk}^{(l)} a_k^{(l-1)} + b_j^{(l)}; a_j^{(l)} = g(z_j^{(l)}).",
              "Output Error Delta: delta_j^{(L)} = ( dL / da_j^{(L)} ) * g'(z_j^{(L)}). For MSE + Linear: delta_j = (a_j - y_j).",
              "Hidden Error Delta: delta_k^{(l-1)} = ( Sum_j w_{jk}^{(l)} delta_j^{(l)} ) * g'(z_k^{(l-1)}).",
              "Weight Gradient: dL / dw_{jk}^{(l)} = delta_j^{(l)} * a_k^{(l-1)}.",
              "Bias Gradient: dL / db_j^{(l)} = delta_j^{(l)}.",
            ],
            examPitfalls: [
              "Weight update subtraction: w_{new} = w_{old} - eta * (dL/dw). A common exam sign error is adding instead of subtracting the gradient.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Step-by-Step Mathematical Derivation of Backprop",
              body: [
                "Backpropagation is an efficient dynamic programming application of the multivariable calculus chain rule on a directed acyclic computational graph.",
                "**The Four Fundamental Backprop Equations:**",
                "1. `delta^{(L)} = grad_a L * g'(z^{(L)})` (Output layer sensitivity).",
                "2. `delta^{(l)} = ( (W^{(l+1)})^T delta^{(l+1)} ) * g'(z^{(l)})` (Sensitivity backpropagated through layer weights).",
                "3. `dL / db^{(l)} = delta^{(l)}` (Rate of change wrt bias).",
                "4. `dL / dW^{(l)} = delta^{(l)} (a^{(l-1)})^T` (Outer product gradient wrt weight matrix).",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: 1-Step Backpropagation Weight Update",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Evaluate the activation derivative g'(z) at the pre-activation value z.",
              solutionSteps: [
                "Problem: A neuron has single input x = 2.0, weight w = 1.5, bias b = 0. Target output y = 1.0. Activation is linear g(z) = z, loss is squared error L = (1/2)(y_hat - y)^2. Learning rate eta = 0.1. Compute updated weight w_new.",
                "Step 1: Forward Pass:",
                "  z = w * x + b = 1.5 * 2.0 + 0 = 3.0",
                "  y_hat = g(z) = 3.0",
                "Step 2: Compute Loss and Output Error:",
                "  Loss = (1/2) * (3.0 - 1.0)^2 = (1/2) * 4 = 2.0",
                "  dL / dy_hat = y_hat - y = 3.0 - 1.0 = 2.0",
                "Step 3: Compute Gradient wrt Weight w:",
                "  dL / dw = (dL / dy_hat) * (dy_hat / dz) * (dz / dw)",
                "  dy_hat / dz = g'(z) = 1.0; dz / dw = x = 2.0",
                "  dL / dw = 2.0 * 1.0 * 2.0 = 4.0",
                "Step 4: Update Weight via Gradient Descent:",
                "  w_new = w - eta * (dL / dw) = 1.5 - 0.1 * (4.0) = 1.5 - 0.4 = 1.1.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Neural Networks and Deep Learning",
                  authors: "Michael Nielsen",
                  year: "2015",
                  publisher: "Determination Press",
                  relevance: "Chapter 2: How the backpropagation algorithm works (visual proof of 4 equations).",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 6: UNSUPERVISED LEARNING & MODEL EVALUATION
    // =========================================================================
    {
      id: "ml-module-6-unsupervised-eval",
      title: "Module 6: Clustering, PCA & Model Evaluation Metrics",
      slug: "clustering-pca-and-evaluation",
      description:
        "K-Means, K-Medoids, Hierarchical clustering linkages, Principal Component Analysis, ROC-AUC, and the Bias-Variance tradeoff.",
      order: 6,
      lessons: [
        {
          id: "clustering-kmeans-kmedoids-and-hierarchical",
          title: "Clustering Algorithms: K-Means, K-Medoids & Hierarchical Linkages",
          slug: "clustering-kmeans-kmedoids-and-hierarchical",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Lloyd's WCSS convergence, K-means++ initialization, PAM medoids, and single/complete linkage dendrograms.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "K-Means alternates Assignment (nearest centroid) and Update (mean of cluster). Single Linkage uses MIN distance (chaining effect); Complete Linkage uses MAX distance (compact spheres).",
            keyFormulasAndRules: [
              "Within-Cluster Sum of Squares (Inertia): WCSS = Sum_{k=1}^K Sum_{x in C_k} ||x - mu_k||_2^2.",
              "Centroid Update: mu_k = (1 / |C_k|) * Sum_{x in C_k} x.",
              "Single Linkage Distance: D(A, B) = min_{x in A, y in B} d(x, y).",
              "Complete Linkage Distance: D(A, B) = max_{x in A, y in B} d(x, y).",
              "Average Linkage Distance: D(A, B) = [ 1 / (|A| * |B|) ] * Sum_{x in A} Sum_{y in B} d(x, y).",
            ],
            examPitfalls: [
              "K-Means converges to a LOCAL minimum of WCSS, not necessarily the global optimum. Different random initializations produce different final clusters.",
              "K-Means is heavily sensitive to outliers because the squared Euclidean distance penalizes distant points quadratically.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Geometry of Partitional & Hierarchical Clustering",
              body: [
                "Clustering partitions an unlabeled dataset X into K groups such that points within the same cluster have high similarity, while points across different clusters are dissimilar.",
                "**K-Means++ Initialization:**",
                "Standard K-Means picks initial centroids purely at random, which often traps the model in bad local minima. K-means++ chooses the first centroid uniformly at random, and then picks subsequent centroids with probability proportional to their squared distance to the closest existing centroid: `P(x) = D(x)^2 / Sum D(z)^2`, ensuring widely spaced initial seeds.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: 1D K-Means Centroid Iteration",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Recompute cluster membership immediately based on nearest centroid before taking the new mean.",
              solutionSteps: [
                "Problem: Given 1D points [2, 4, 10, 12, 20] and initial centroids mu1 = 3 and mu2 = 15. Perform one iteration of K-Means and find the updated centroids.",
                "Step 1: Assign each point to nearest centroid (tie-breaker to lower index):",
                "  Point 2: |2-3|=1 vs |2-15|=13 => Cluster 1",
                "  Point 4: |4-3|=1 vs |4-15|=11 => Cluster 1",
                "  Point 10: |10-3|=7 vs |10-15|=5 => Cluster 2",
                "  Point 12: |12-3|=9 vs |12-15|=3 => Cluster 2",
                "  Point 20: |20-3|=17 vs |20-15|=5 => Cluster 2",
                "Step 2: Compute new centroid means:",
                "  Cluster 1 = {2, 4} => mu1_new = (2 + 4) / 2 = 6 / 2 = 3.0",
                "  Cluster 2 = {10, 12, 20} => mu2_new = (10 + 12 + 20) / 3 = 42 / 3 = 14.0",
                "Conclusion: After 1 iteration, centroids update to mu1 = 3.0 and mu2 = 14.0.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Data Mining: Concepts and Techniques (3rd Edition)",
                  authors: "Jiawei Han, Micheline Kamber, Jian Pei",
                  year: "2011",
                  publisher: "Morgan Kaufmann",
                  relevance: "Chapter 10: Cluster Analysis basic concepts and methods.",
                },
              ],
            },
          ],
        },
        {
          id: "dimensionality-reduction-pca-and-tsne",
          title: "Dimensionality Reduction: Principal Component Analysis (PCA) & t-SNE",
          slug: "dimensionality-reduction-pca-and-tsne",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Covariance matrix diagonalization, maximizing projection variance, eigenvalues, and t-SNE manifolds.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "PCA finds orthogonal directions that maximize data variance (eigenvectors of covariance matrix Sigma = (1/n) X^T X).",
            keyFormulasAndRules: [
              "Sample Covariance Matrix: Sigma = (1 / n) * X^T X (assuming zero-mean centered X).",
              "Eigenvalue Problem: Sigma v_i = lambda_i v_i. Principal components are sorted by lambda_1 >= lambda_2 >= ... >= lambda_d >= 0.",
              "Total Variance: Sum_{i=1}^d lambda_i = Trace(Sigma).",
              "Explained Variance Ratio of k components: Proportion = (Sum_{i=1}^k lambda_i) / (Sum_{j=1}^d lambda_j).",
              "t-SNE vs PCA: PCA is a global linear projection. t-SNE is a local non-linear manifold visualizer using Student-t distribution in low dimensions to prevent the crowding problem.",
            ],
            examPitfalls: [
              "Data MUST be mean-centered before applying PCA; otherwise the first principal component points toward the data mean rather than the direction of maximum variance.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Two Equivalent Formulations of PCA",
              body: [
                "Principal Component Analysis can be formally derived through two complementary mathematical perspectives:",
                "1. **Maximum Variance Perspective:** Find a unit vector u (`u^T u = 1`) that maximizes the variance of projected points: `max_u u^T Sigma u` subject to `u^T u = 1`. The Lagrangian is `L(u, lambda) = u^T Sigma u - lambda (u^T u - 1)`. Setting derivative to zero yields `Sigma u = lambda u` (Eigenvalue problem!).",
                "2. **Minimum Reconstruction Error Perspective:** Find orthogonal subspace that minimizes the sum of squared distances between original points and their low-dimensional projections.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: PCA Explained Variance Proportion",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Explained variance proportion is the ratio of selected eigenvalues to the trace of the covariance matrix.",
              solutionSteps: [
                "Problem: A 3D dataset has sample covariance matrix with eigenvalues lambda1 = 8.0, lambda2 = 3.0, lambda3 = 1.0. What percentage of total variance is retained by projecting onto the top-2 principal components?",
                "Step 1: Compute total variance (Sum of all eigenvalues):",
                "  Total Variance = lambda1 + lambda2 + lambda3 = 8.0 + 3.0 + 1.0 = 12.0",
                "Step 2: Compute variance explained by top-2 components:",
                "  Top-2 Variance = lambda1 + lambda2 = 8.0 + 3.0 = 11.0",
                "Step 3: Calculate percentage:",
                "  Proportion = (11.0 / 12.0) * 100% = 91.67%.",
                "Conclusion: Reducing dimensions from 3D to 2D retains ~91.7% of information while compressing data by 33%.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Mathematics for Machine Learning",
                  authors: "Marc Peter Deisenroth, A. Aldo Faisal, Cheng Soon Ong",
                  year: "2020",
                  publisher: "Cambridge University Press",
                  relevance: "Chapter 10: Dimensionality Reduction with Principal Component Analysis.",
                },
              ],
            },
          ],
        },
        {
          id: "model-evaluation-roc-auc-and-bias-variance",
          title: "Model Evaluation: Confusion Matrix, ROC-AUC & Bias-Variance Decomposition",
          slug: "model-evaluation-roc-auc-and-bias-variance",
          order: 3,
          estimatedMinutes: 32,
          tagline: "Precision, Recall, Specificity, F1 harmonic mean, ROC curves, and the mathematical bias-variance decomposition.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Precision = TP / (TP + FP). Recall (Sensitivity, TPR) = TP / (TP + FN). Specificity (TNR) = TN / (TN + FP). FPR = 1 - Specificity.",
            keyFormulasAndRules: [
              "F1-Score: 2 * (Precision * Recall) / (Precision + Recall) = 2 * TP / (2*TP + FP + FN).",
              "ROC Curve: Plots True Positive Rate (Recall) on Y-axis vs False Positive Rate (FPR) on X-axis across varying threshold tau.",
              "ROC-AUC: Area under ROC curve; random guess gives AUC = 0.5; perfect model gives AUC = 1.0.",
              "Bias-Variance Decomposition: E[(y - f_hat(x))^2] = [ Bias(f_hat(x)) ]^2 + Var(f_hat(x)) + sigma^2, where sigma^2 is irreducible noise.",
              "k-Fold Cross-Validation: Partitions dataset into k equal folds; trains on (k-1) and tests on 1, repeated k times.",
            ],
            examPitfalls: [
              "Accuracy is a dangerously misleading metric for class-imbalanced datasets (e.g. 99% accuracy on 99% negative class by predicting all negatives). Use F1-score or PR-AUC.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Confusion Matrix Metrics & ROC Mechanics",
              body: [
                "Evaluation metrics determine whether a learned machine learning hypothesis generalizes to unseen test distributions.",
                "**The Four Fundamental Quadrants:**",
                "- True Positive (TP): Ground truth 1, Predicted 1.",
                "- False Positive (FP, Type I Error): Ground truth 0, Predicted 1.",
                "- True Negative (TN): Ground truth 0, Predicted 0.",
                "- False Negative (FN, Type II Error): Ground truth 1, Predicted 0.",
                "**The Bias-Variance Tradeoff:**",
                "- **Bias:** Error introduced by approximating complex real-world phenomena with overly simplistic models (underfitting).",
                "- **Variance:** Model sensitivity to random fluctuations in the training set (overfitting).",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Complete Evaluation Metric Derivation",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Recall has False Negatives (FN) in the denominator; Precision has False Positives (FP) in the denominator.",
              solutionSteps: [
                "Problem: A diagnostic test evaluates 200 patients. Confusion matrix: TP = 70, FP = 10, FN = 30, TN = 90. Compute Precision, Recall, Specificity, and F1-Score.",
                "Step 1: Compute Precision (P):",
                "  P = TP / (TP + FP) = 70 / (70 + 10) = 70 / 80 = 0.875 (87.5%).",
                "Step 2: Compute Recall (R, Sensitivity, TPR):",
                "  R = TP / (TP + FN) = 70 / (70 + 30) = 70 / 100 = 0.700 (70.0%).",
                "Step 3: Compute Specificity (TNR):",
                "  Specificity = TN / (TN + FP) = 90 / (90 + 10) = 90 / 100 = 0.900 (90.0%).",
                "  False Positive Rate (FPR) = 1 - Specificity = 1 - 0.90 = 0.100 (10.0%).",
                "Step 4: Compute F1-Score:",
                "  F1 = 2 * (P * R) / (P + R) = 2 * (0.875 * 0.70) / (0.875 + 0.70) = 2 * (0.6125) / (1.575) = 1.225 / 1.575 = 7 / 9 ≈ 0.7778 (77.78%).",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "An Introduction to Statistical Learning (with Applications in R/Python)",
                  authors: "Gareth James, Daniela Witten, Trevor Hastie, Robert Tibshirani",
                  year: "2021",
                  publisher: "Springer",
                  relevance: "Chapter 2.2: Assessing Model Accuracy and the Bias-Variance Tradeoff.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
