import { LessonCheatSheet } from './types';

export const OS_LESSON_CHEATSHEETS: Record<string, LessonCheatSheet> = {
  'why-operating-systems-exist': {
    title: 'Why Operating Systems Exist · Subtopic Cheat Sheet',
    summaryRule: 'OS = Resource Manager (arbitrator of CPU, RAM, I/O) + Extended Machine (abstractor of hardware into files, sockets, processes).',
    keyFormulasAndRules: [
      'Kernel execution is reactive: Invoked strictly via Interrupts, Traps, or System Calls.',
      'Hardware provides the protection boundary (Mode Bit); the OS defines and enforces policy.',
      'User Space (Ring 3): Restricted instruction set; hardware access strictly forbidden.',
      'Kernel Space (Ring 0): Full hardware authority; direct memory mapping and I/O access.',
    ],
    examPitfalls: [
      'Compilers, linkers, shells, and web browsers are NOT part of the OS kernel; they are user applications.',
      'Device drivers run with kernel privileges, making buggy drivers the leading cause of OS crashes.',
      'The OS is not a continuously running loop; it runs only when an event (interrupt/trap/syscall) triggers it.',
    ],
    highYieldTips: [
      'GATE frequently tests whether shells, GUI managers, or standard C libraries execute in User Mode or Kernel Mode (Answer: User Mode).',
      'Remember the dual role: Resource Allocation (efficiency & isolation) vs Abstraction (ease of use).',
    ],
    visualAnchor: `[ THE DUAL ROLE OF THE KERNEL ]
┌────────────────────────────────────────────────────────┐
│                   APPLICATIONS / USER                  │
└──────────────────────────┬─────────────────────────────┘
                           │ System Calls (Controlled)
┌──────────────────────────▼─────────────────────────────┐
│                      OS KERNEL                         │
│  [Resource Manager]             [Extended Machine]     │
│  Arbitration & Protection       Clean Abstractions     │
└──────────────────────────┬─────────────────────────────┘
                           │ Privileged Hardware Control
┌──────────────────────────▼─────────────────────────────┐
│              CPU · RAM · DISK · I/O HARDWARE           │
└────────────────────────────────────────────────────────┘`,
  },

  'dual-mode-and-system-calls': {
    title: 'Dual-Mode & System Calls · Subtopic Cheat Sheet',
    summaryRule: 'CPU hardware enforces safety via the Mode Bit (0 = Kernel, 1 = User). Privileged instructions fail with a CPU trap if executed when Mode Bit = 1.',
    keyFormulasAndRules: [
      'Mode Bit: 1 = User Mode (unprivileged), 0 = Kernel/Supervisor Mode (privileged).',
      'Trap / Exception: Synchronous event generated by software instruction (syscall, divide by 0, page fault).',
      'Interrupt: Asynchronous event generated by external hardware (timer interrupt, disk controller, keyboard).',
      'Privileged Instructions: HLT, CLI/STI, modifying base/limit registers or page table roots (CR3), direct I/O (IN/OUT).',
      'Non-Privileged Instructions: Reading timer/clock, arithmetic, branch, user stack operations, executing trap/syscall.',
    ],
    examPitfalls: [
      'Mode switch ≠ Context switch! A mode switch stays in the same process context (just switches user stack → kernel stack).',
      'User code NEVER jumps directly to kernel function memory addresses; it vectors through the Interrupt Descriptor Table (IDT).',
      'Resetting timer register is PRIVILEGED; reading the timer/clock is NON-PRIVILEGED.',
    ],
    highYieldTips: [
      'GATE Trap: "Disabling interrupts" is ALWAYS a privileged instruction (otherwise user code could monopolize the CPU).',
      'Switch from User to Kernel occurs via hardware trap/interrupt (clears Mode Bit to 0); Kernel to User occurs via iret/sysret (sets Mode Bit to 1).',
    ],
    visualAnchor: `[ DUAL-MODE HARDWARE TRANSITION ]
[ User Mode (Bit=1) ] ──(syscall / trap instruction)──> [ Hardware flips bit to 0 ]
                                                                  │
                                                                  ▼
[ User Mode (Bit=1) ] <──(iret / sysret instruction)──── [ Kernel Mode (Bit=0) ]`,
  },

  'what-is-a-process': {
    title: 'Process Concept & PCB · Subtopic Cheat Sheet',
    summaryRule: 'Process = Program in execution with isolated virtual address space (Text + Data + BSS + Heap + Stack) + Process Control Block (PCB).',
    keyFormulasAndRules: [
      'Virtual Memory Hierarchy: Text (Low) → Initialized Data → Uninitialized BSS → Heap (Grows Up ↑) → Free Space → Stack (Grows Down ↓, High).',
      'Stack: Stores local variables, function frames, return addresses, parameters.',
      'Heap: Stores dynamically allocated memory via malloc(), calloc(), or new.',
      'BSS: Stores uninitialized global and static variables (zero-initialized by kernel).',
      'Data Segment: Stores initialized global and static variables.',
      'Threads SHARE: Code (Text), Data, BSS, Heap, Open file descriptors, Working directory.',
      'Threads KEEP PRIVATE: Stack, Registers, Program Counter (PC), State.',
    ],
    examPitfalls: [
      'Static variables declared INSIDE functions live in Data/BSS, NOT on the stack!',
      'PCB is allocated and maintained strictly in KERNEL memory; user code cannot inspect or modify its own PCB directly.',
      'Threads within the same process share the same PID and address space, but each thread has its own private Stack and TCB.',
    ],
    highYieldTips: [
      'GATE Classic: Given variable declarations, determine memory segment locations (Stack vs Data vs BSS vs Heap).',
      'Stack grows toward lower addresses (High → Low); Heap grows toward higher addresses (Low → High). Collision triggers Stack Overflow.',
    ],
    visualAnchor: `[ MEMORY LAYOUT OF A PROCESS ]
[ High Memory: 0xFFFF ] ───> STACK (Grows Downward ↓)
                                 │
                             Free Space
                                 │
                             HEAP (Grows Upward ↑)
                             BSS (Uninitialized Globals = 0)
                             DATA (Initialized Globals)
[ Low Memory:  0x0000 ] ───> TEXT / CODE (Read-Only)`,
  },

  'process-states-and-transitions': {
    title: 'Process States & Transitions · Subtopic Cheat Sheet',
    summaryRule: '5 States: New → Ready ⇄ Running → Terminated (with Running → Waiting → Ready). 7-State model adds Ready-Suspend and Blocked-Suspend on secondary disk.',
    keyFormulasAndRules: [
      'Running → Waiting (Blocked): Voluntary block for I/O request or waiting for child/signal.',
      'Waiting → Ready: Event/IO completed. Placed back in Ready Queue (never straight to CPU!).',
      'Running → Ready: Involuntary preemption (Timer quantum expired or higher priority process arrived).',
      'Blocked-Suspend → Ready-Suspend: I/O completes while process is swapped out to secondary disk.',
      'Medium-Term Scheduler: Swaps processes between RAM and Disk to regulate the Degree of Multiprogramming.',
      'Long-Term Scheduler: Job scheduler; controls Degree of Multiprogramming from Disk (Job pool) to RAM.',
      'Short-Term Scheduler: CPU scheduler / Dispatcher; picks process from Ready Queue to run on CPU core.',
    ],
    examPitfalls: [
      'Blocked/Waiting → Running is IMPOSSIBLE in all operating systems. Only Ready processes can transition to Running.',
      'In a non-preemptive OS, there is NO Running → Ready transition.',
      'Blocked-Suspend does NOT become Ready in RAM when I/O completes; it transitions to Ready-Suspend on Disk!',
    ],
    highYieldTips: [
      'GATE Question Rule: Minimum number of processes in Running state on single-core CPU = 0 (when idle), Maximum = 1.',
      'Dispatcher is the module that gives control of CPU to process selected by short-term scheduler (handles context switch & mode switch).',
    ],
    visualAnchor: `[ 5-STATE & 7-STATE TRANSITION FLOW ]
[NEW] ──> [READY] ◄──(Preempt / Timer)──► [RUNNING] ──> [TERMINATED]
             ▲                                │
             │           (I/O Completes)      ▼
             └────────────── [WAITING / BLOCKED]
[DISK SWAP]:
[READY-SUSPEND] ◄────(I/O Completes)──── [BLOCKED-SUSPEND]`,
  },

  'context-switching': {
    title: 'Context Switching & Hardware Overhead · Subtopic Cheat Sheet',
    summaryRule: 'Context switch is pure system overhead where the CPU executes NO user instructions: State(P0) saved to PCB0 → Scheduler runs → State(P1) restored from PCB1.',
    keyFormulasAndRules: [
      'Context Switch Overhead: CPU time spent saving registers, reloading MMU page table pointer (CR3), and TLB invalidation.',
      'Process Switch Steps: Save Registers/PC → Save PCB0 → Pick P1 → Switch Virtual Address Space (CR3) → Flush/tag TLB → Restore PCB1 → iret.',
      'Thread Switch vs Process Switch: Thread switch DOES NOT switch address space (CR3 stays identical, TLB remains valid) → 10x to 100x faster!',
    ],
    examPitfalls: [
      'A Mode Switch is NOT a Context Switch! Mode switch (User ↔ Kernel) keeps the same process address space and PCB.',
      'Context switch time is 100% wasted CPU time (pure overhead); hardware support like multiple register sets reduces this time.',
    ],
    highYieldTips: [
      'GATE Trap: "Does context switch happen during every system call?" No! Only if the system call causes the current process to block or preempt.',
      'Hardware that has multiple register sets (e.g. UltraSPARC) can switch context simply by changing the current register window pointer.',
    ],
    visualAnchor: `[ CONTEXT SWITCH TIMELINE ]
Process P0: [ Executing ] ──(Timer Interrupt / Syscall)
                                 │
                      [ Kernel saves P0 to PCB0 ]  <── Context Switch Overhead
                      [ Scheduler selects P1    ]  <── (No user work done!)
                      [ Kernel restores P1 PCB1 ]  <──
                                 │
Process P1:                      └──> [ Executing ]`,
  },

  'inter-process-communication': {
    title: 'IPC & fork() Tree Counting · Subtopic Cheat Sheet',
    summaryRule: 'IPC: Shared Memory (fastest, zero kernel copy, requires synchronization) vs Message Passing (system calls, kernel buffers). fork() creates an identical clone child.',
    keyFormulasAndRules: [
      'Total Processes created by n consecutive fork() calls = 2^n.',
      'Child Processes created = 2^n - 1.',
      'Unnamed Pipe: Unidirectional byte stream; created via pipe(fd[2]); fd[0] = Read, fd[1] = Write; only between related processes.',
      'Named Pipe (FIFO): Has file system name, bidirectional or unidirectional, works between unrelated processes.',
      'fork() return value: Returns 0 to the Child process, returns Child PID (> 0) to Parent process, returns -1 on error.',
    ],
    examPitfalls: [
      'In fork() loops with printf("..."): remember whether newline "\\n" is present! Without "\\n", stdout is buffered and duplicated across child processes.',
      'In pipes, both ends are inherited across fork(). If the writer does not close its read end or reader does not close write end, EOF will never be received.',
    ],
    highYieldTips: [
      'GATE Tree Counting: Draw binary tree for fork(). For fork() && fork() || fork(), evaluate short-circuit Boolean evaluation step-by-step.',
      'Zombie process: Process terminated, but parent hasn’t called wait() (entry remains in PCB). Orphan process: Parent died without waiting; adopted by init/systemd (PID 1).',
    ],
    visualAnchor: `[ FORK TREE FORMULA ]
n fork() calls  ──> Total Processes = 2^n
Parent alone    ──> 1
Child Processes ──> 2^n - 1

PIPE ENDS:
fd[0] = READ  (0 looks like mouth opening to read)
fd[1] = WRITE (1 looks like pen to write)`,
  },

  'scheduling-basics': {
    title: 'CPU Scheduling Metrics & Criteria · Subtopic Cheat Sheet',
    summaryRule: 'Turnaround Time (TAT) = CT - AT. Waiting Time (WT) = TAT - BT. Response Time (RT) = First CPU Time - AT.',
    keyFormulasAndRules: [
      'Completion Time (CT): Instant at which process completes execution.',
      'Turnaround Time (TAT): CT - AT (total residency time in system).',
      'Waiting Time (WT): TAT - BT (time spent waiting in ready queue).',
      'Response Time (RT): (Time when process first gets CPU) - AT.',
      'CPU Utilization: (Total Busy Time / Total Schedule Time) × 100%.',
      'Throughput: Number of processes completed per unit time.',
    ],
    examPitfalls: [
      'Do not calculate WT from Gantt chart directly by adding blocks; ALWAYS compute WT = TAT - BT to prevent errors on multiple CPU bursts or preemption.',
      'Check for CPU Idle gaps! If highest arrival time has not reached the current clock time, the CPU is idle.',
    ],
    highYieldTips: [
      'Average TAT = (Σ TAT_i) / n; Average WT = (Σ WT_i) / n.',
      'Response Time == Waiting Time strictly for NON-PREEMPTIVE algorithms (if process never blocks for I/O).',
    ],
    visualAnchor: `[ METRICS CHEAT FORMULAS ]
┌────────────────────────────────────────────────────────┐
│  TAT = CT - AT       (Completion - Arrival)            │
│  WT  = TAT - BT      (Turnaround - Burst)              │
│  RT  = FirstCPU - AT (First Scheduled - Arrival)       │
└────────────────────────────────────────────────────────┘`,
  },

  'fcfs-and-round-robin': {
    title: 'FCFS & Round Robin · Subtopic Cheat Sheet',
    summaryRule: 'FCFS: Non-preemptive, suffers Convoy Effect. Round Robin: Preemptive with time quantum q; q → ∞ degrades to FCFS; q → 0 causes thrashing from context switch overhead.',
    keyFormulasAndRules: [
      'FCFS Selection: Process with lowest Arrival Time (AT) gets CPU until completion.',
      'Convoy Effect in FCFS: One CPU-intensive process holds CPU; short I/O-intensive jobs starve in ready queue.',
      'Round Robin Selection: FIFO ready queue with preemption after time slice q.',
      'RR Rule: If process P_i preemption and process P_new arrival happen at the EXACT SAME instant, newly arrived P_new enters ready queue BEFORE preempted P_i.',
      'Number of context switches in RR: If job burst is BT and quantum is q, ceil(BT/q) - 1 context switches (if no other jobs interfere).',
    ],
    examPitfalls: [
      'Tie-breaking in Round Robin: Always verify whether ready queue appends newly arriving process first or preempted process first (standard GATE convention: newly arriving process goes first).',
      'Time quantum q selection: If q is too large, interactive response time suffers; if q is too small, context switch overhead dominates CPU cycles.',
    ],
    highYieldTips: [
      'GATE Rule: 80% of CPU bursts should be shorter than time quantum q for optimal interactive response.',
      'Round Robin is starvation-free because every ready process gets a turn within at most (n - 1) × q time.',
    ],
    visualAnchor: `[ ROUND ROBIN READY QUEUE RULE ]
At Time t:
1. Newly arrived process P_new enters queue tail.
2. Preempted process P_old enters behind P_new.
Queue: [ Front ] ──> P_next ──> P_new ──> P_old ──> [ Back ]`,
  },

  'sjf-srtf-priority-scheduling': {
    title: 'SJF, SRTF & Priority Scheduling · Subtopic Cheat Sheet',
    summaryRule: 'SJF is provably OPTIMAL for minimum average waiting time (non-preemptive). SRTF is preemptive SJF. Priority scheduling uses Aging to prevent starvation.',
    keyFormulasAndRules: [
      'SJF (Non-Preemptive): Chooses process with shortest burst time once current finishes.',
      'SRTF (Preemptive SJF): Preempts running process whenever a newly arrived process has strictly shorter remaining burst time.',
      'Highest Response Ratio Next (HRRN): Response Ratio = (W + S) / S = 1 + W/S (Non-preemptive; prevents starvation while favoring shorter jobs).',
      'Exponential Smoothing for CPU burst prediction: τ_{n+1} = α · t_n + (1 - α) · τ_n (where 0 ≤ α ≤ 1).',
      'Aging Technique: Gradually increase priority of processes waiting in ready queue over time.',
    ],
    examPitfalls: [
      'SJF / SRTF can cause Starvation (indefinite postponement) for long processes if short processes keep arriving.',
      'In SRTF, if remaining burst of running process EQUALS burst of new arrival, DO NOT preempt (preempt only if strictly less, unless specified).',
      'Priority convention check: In GATE questions, ALWAYS check whether lower number = higher priority or higher number = higher priority!',
    ],
    highYieldTips: [
      'SRTF produces the absolute theoretical minimum average waiting time among all scheduling algorithms.',
      'HRRN: As waiting time W increases, response ratio increases, guaranteeing even giant burst processes eventually run.',
    ],
    visualAnchor: `[ SJF vs SRTF vs HRRN ]
• SJF:  Evaluate Burst at process completion boundaries.
• SRTF: Evaluate Remaining Burst at EVERY arrival boundary.
• HRRN: Ratio = (Waiting Time + Burst Time) / Burst Time = 1 + W / S`,
  },

  'critical-section-and-semaphores': {
    title: 'Critical Section & Semaphores · Subtopic Cheat Sheet',
    summaryRule: '3 CS Criteria: Mutual Exclusion (Mandatory), Progress (Mandatory), Bounded Waiting (Secondary). Semaphores: wait(S) decrements, signal(S) increments.',
    keyFormulasAndRules: [
      'Mutual Exclusion: If process P_i is executing in CS, no other process can execute in CS.',
      'Progress: Only processes NOT in Remainder Section can participate in deciding who enters CS next; decision cannot be postponed indefinitely.',
      'Bounded Waiting: Limit on number of times other processes enter CS after a process requests entry.',
      'Counting Semaphore value S: Initial value = N resources.',
      'If S ≥ 0: S represents number of available resources.',
      'If S < 0: |S| represents number of processes blocked on semaphore queue.',
      'After m wait() and n signal() operations on initial value S_0: Current Value = S_0 - m + n.',
    ],
    examPitfalls: [
      'A process running in its Remainder Section must NEVER block other processes from entering the Critical Section (violates Progress).',
      'Strict alternation (turn variable) satisfies Mutual Exclusion and Bounded Waiting, but VIOLATES Progress.',
      'Binary semaphore values are strictly 0 and 1; counting semaphores can be negative in blocked queue implementations.',
    ],
    highYieldTips: [
      'Peterson’s Algorithm solves Critical Section for exactly 2 processes and satisfies all 3 conditions.',
      'GATE Formula: To allow at most k processes in CS simultaneously, initialize Counting Semaphore to k.',
    ],
    visualAnchor: `[ SEMAPHORE INVARIANTS ]
Initial Value: S_0
After m wait() and n signal():
  Current S = S_0 - m + n
If S < 0:
  Number of blocked processes = |S|`,
  },

  'deadlock-principles-and-bankers': {
    title: 'Deadlocks & Banker\'s Algorithm · Subtopic Cheat Sheet',
    summaryRule: '4 Coffman Conditions must hold simultaneously: Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait. Banker\'s algorithm ensures system never leaves a Safe State.',
    keyFormulasAndRules: [
      'Deadlock Prevention: Invalidate at least ONE of the 4 Coffman conditions before runtime.',
      'Deadlock Avoidance (Banker\'s): Check if granting request leaves at least ONE Safe Sequence.',
      'Need Matrix: Need[i][j] = Max[i][j] - Allocation[i][j].',
      'Banker\'s Safety Test: Find P_i where Need[i] ≤ Available. If found: Available = Available + Allocation[i]; mark P_i finished.',
      'Minimum Resources for Deadlock-Free Execution: M ≥ Σ(MaxDemand_i - 1) + 1 = N × (K - 1) + 1 (for N processes, max demand K each).',
    ],
    examPitfalls: [
      'A cycle in a Resource Allocation Graph (RAG) is a NECESSARY and SUFFICIENT condition for deadlock ONLY if every resource has exactly 1 instance!',
      'If resources have multiple instances, a cycle is necessary but NOT sufficient for deadlock.',
      'Unsafe State ≠ Deadlocked State! An unsafe state is merely a state from which the OS cannot guarantee deadlock will not occur.',
    ],
    highYieldTips: [
      'Deadlock-Free Bound: If each of N processes needs at most K instances, min resources M = N × (K - 1) + 1 guarantees deadlock freedom.',
      'Resource ordering (hierarchical allocation) prevents Circular Wait.',
    ],
    visualAnchor: `[ DEADLOCK CONDITIONS & SAFETY BOUND ]
4 COFFMAN CONDITIONS (All 4 needed for deadlock):
1. Mutual Exclusion  2. Hold & Wait  3. No Preemption  4. Circular Wait

DEADLOCK-FREE FORMULA:
  M >= N * (K - 1) + 1
Where: N = number of processes, K = max demand of each, M = total resources.`,
  },

  'paging-and-tlb': {
    title: 'Paging & TLB EMAT · Subtopic Cheat Sheet',
    summaryRule: 'Logical Address = Page Number (p) + Offset (d). Page Size = Frame Size = 2^d bytes. TLB Hit: EMAT = h·(t_tlb + t_m) + (1-h)·(t_tlb + (k+1)·t_m).',
    keyFormulasAndRules: [
      'Page Offset bits: d = log2(Page Size in Bytes).',
      'Number of Pages = Logical Address Space / Page Size = 2^(p).',
      'Number of Frames = Physical Address Space / Frame Size = 2^(f).',
      'Page Table Size = (Number of Pages) × (Page Table Entry Size).',
      'EMAT (Single-level paging with TLB): EMAT = h · (t_tlb + t_m) + (1 - h) · (t_tlb + 2 · t_m).',
      'EMAT (k-level paging with TLB): EMAT = h · (t_tlb + t_m) + (1 - h) · (t_tlb + (k + 1) · t_m).',
      'Inverted Page Table: Size proportional to Physical Memory (RAM), independent of number of processes.',
    ],
    examPitfalls: [
      'Don’t forget the final memory access to fetch the actual operand/byte! (That is why miss takes (k + 1) memory accesses).',
      'Parallel vs Sequential TLB lookup: If TLB and Cache/RAM are looked up in parallel on hit: EMAT = h · (t_m) + (1 - h) · (t_tlb + 2·t_m). Read question carefully!',
      'Internal Fragmentation happens on the last page of a process (average = Page Size / 2). Paging eliminates External Fragmentation.',
    ],
    highYieldTips: [
      'Multi-level paging condition: Outer page table must fit completely into EXACTLY ONE memory page frame!',
      'TLB reach = (TLB Entries) × (Page Size).',
    ],
    visualAnchor: `[ ADDRESS TRANSLATION & EMAT ]
Logical Address:  [ Page Number (p) | Offset (d) ]
                         │               │
                     TLB / PT            │
                         ▼               │
Physical Address: [ Frame Number (f)| Offset (d) ]

EMAT = h * (t_tlb + t_m) + (1 - h) * (t_tlb + (k + 1) * t_m)`,
  },

  'page-replacement-algorithms': {
    title: 'Page Replacement & Belady\'s Anomaly · Subtopic Cheat Sheet',
    summaryRule: 'FIFO suffers Belady\'s Anomaly. Stack algorithms (LRU, Optimal) never suffer Belady\'s Anomaly. Optimal is theoretical benchmark.',
    keyFormulasAndRules: [
      'Belady\'s Anomaly: Increasing physical page frames causes an INCREASE in page faults (observed in FIFO).',
      'Stack Algorithm Property: Set of pages in n frames is always a subset of pages in (n + 1) frames at all times → Immune to Belady\'s Anomaly.',
      'Optimal Page Replacement (OPT / MIN): Replaces page that will NOT be used for the longest time in future.',
      'Least Recently Used (LRU): Replaces page that has not been used for longest time in past (approximated by Clock / Second Chance).',
      'Effective Memory Access Time (Demand Paging): EAT = (1 - p) · t_m + p · (Page Fault Service Time).',
      'Thrashing: Occurs when Sum of Locality Sizes > Total Physical Memory Size. CPU utilization drops toward zero.',
    ],
    examPitfalls: [
      'FIFO does NOT guarantee fewer page faults when frames increase! Classic example: reference string `1, 2, 3, 4, 1, 2, 5, 1, 2, 3, 4, 5` (3 frames = 9 faults; 4 frames = 10 faults).',
      'Optimal algorithm cannot be implemented in general-purpose OS because the OS cannot predict future page references.',
    ],
    highYieldTips: [
      'Working Set Model (Denning) monitors working set window Δ to prevent thrashing.',
      'Page Fault Service Time is measured in milliseconds (ms), while RAM access is in nanoseconds (ns) — page fault penalty is ~100,000x slower!',
    ],
    visualAnchor: `[ PAGE REPLACEMENT COMPARISON ]
• FIFO:    First In First Out (Queue). Suffers Belady's Anomaly!
• LRU:     Least Recently Used (Stack/Counter). Subset property holds.
• OPTIMAL: Replace page with longest forward distance. Benchmark.
• CLOCK:   Second-chance approximation with Reference Bit (0/1).`,
  },

  'file-allocation-and-inodes': {
    title: 'Unix Inodes & File Allocation · Subtopic Cheat Sheet',
    summaryRule: 'Unix Inode: Direct blocks + Single Indirect + Double Indirect + Triple Indirect pointers. Max file size = BlockSize × [Direct + Single*(DB) + Double*(DB^2) + Triple*(DB^3)].',
    keyFormulasAndRules: [
      'Number of block addresses per indirect block: DB = Block Size / Block Address Size (in bytes).',
      'Direct Block capacity: (Number of Direct Pointers) × Block Size.',
      'Single Indirect capacity: DB × Block Size.',
      'Double Indirect capacity: DB^2 × Block Size.',
      'Triple Indirect capacity: DB^3 × Block Size.',
      'Max File Size = Block Size × [N_direct + DB + DB^2 + DB^3].',
      'Contiguous Allocation: Fast sequential & direct access, but suffers external fragmentation.',
      'Linked Allocation: No external fragmentation, but slow direct access and pointer overhead.',
      'Indexed Allocation: Fast direct access, no external fragmentation, but index block overhead for small files.',
    ],
    examPitfalls: [
      'Do NOT confuse Block Address Size with Disk Address Size or Inode Size. Read the given values carefully.',
      'Disk block size is given in KB or bytes; ensure all exponents match before calculating max file size.',
      'Directory entries in Unix only store: File Name and Inode Number! File size, owner, permissions, and timestamps are in the Inode.',
    ],
    highYieldTips: [
      'GATE Numerical: If Block Size = 4 KB and Address Size = 4 Bytes, DB = 4 KB / 4 B = 1024 addresses per indirect block.',
      'Double indirect holds 1024 × 1024 = 1,048,576 blocks = 4 GB of data.',
    ],
    visualAnchor: `[ UNIX INODE POINTER SCHEME ]
Inode:
├── Direct Pointers [0..11]  ──> Data Blocks (Immediate access)
├── Single Indirect Pointer  ──> Block of 1024 block addresses
├── Double Indirect Pointer  ──> Block of 1024 single-indirect pointers
└── Triple Indirect Pointer  ──> Block of 1024 double-indirect pointers`,
  },

  'disk-scheduling-algorithms': {
    title: 'Disk Scheduling Algorithms · Subtopic Cheat Sheet',
    summaryRule: 'Seek time dominates disk I/O. SCAN touches extreme cylinder (0 or Max). LOOK reverses at highest request. C-SCAN/C-LOOK service requests in ONE direction only.',
    keyFormulasAndRules: [
      'Total Head Movement: Sum of absolute cylinder differences across serviced trajectory.',
      'FCFS: Services requests in arrival order (simple, fair, highest head movement).',
      'SSTF: Greedy selection of request closest to current head (suffers starvation for distant tracks).',
      'SCAN (Elevator): Moves toward one edge servicing requests; reverses at extreme disk boundary (0 or Max).',
      'LOOK: Like SCAN, but reverses at the farthest pending request without traveling to disk edge.',
      'C-SCAN (Circular SCAN): Moves in one direction servicing requests to edge; resets to opposite edge without servicing requests on return.',
      'C-LOOK: Moves in one direction servicing requests up to highest pending; jumps to lowest pending without servicing return.',
    ],
    examPitfalls: [
      'SCAN ALWAYS goes to cylinder 0 or Max (e.g. 199), even if no request exists at 0 or 199!',
      'LOOK reverses at the last pending request (e.g. 183), saving unnecessary travel to cylinder 199.',
      'In C-SCAN and C-LOOK, check whether the return jump counts toward total head movement (standard GATE rule: count the return distance unless explicitly asked otherwise).',
    ],
    highYieldTips: [
      'If disk requests are uniformly distributed, C-SCAN provides more uniform waiting time than SCAN.',
      'Rotational latency average = 1 / (2 × RPM) × 60 seconds.',
    ],
    visualAnchor: `[ SCAN vs LOOK vs C-SCAN vs C-LOOK ]
Platter Cylinders: [ 0 ──────────────── 53 (Head) ──────────────── 199 ]

• SCAN:   [ 53 ──> 199 (Edge) ] ──reverses──> [ 37 ──> 14 ]
• LOOK:   [ 53 ──> 183 (Last) ] ──reverses──> [ 37 ──> 14 ] (Saves 16 tracks!)
• C-SCAN: [ 53 ──> 199 ] ──jump to 0 (no service)──> [ 14 ──> 37 ]
• C-LOOK: [ 53 ──> 183 ] ──jump to 14 (no service)──> [ 37 ]`,
  },
};
