import { CourseMeta } from "./types";

export const PROB_STATS_COURSE: CourseMeta = {
  id: "probability-and-statistics",
  title: "Probability and Statistics",
  slug: "probability-and-statistics",
  subjectSlug: "probability-and-statistics",
  shortTitle: "Prob & Stats",
  icon: "🎲",
  color: "bg-cyan-500",
  tagline:
    "Master counting combinatorics, discrete/continuous distributions, bivariate joint PDFs, Central Limit Theorem, MLE parameter estimation, and hypothesis testing for GATE DA.",
  description:
    "A comprehensive academic study notebook covering counting principles, probability axioms, Bayes' Theorem, classical discrete and continuous distributions, joint and conditional distributions, covariance matrices, sampling distributions (Chi-square, t, F), Central Limit Theorem, point estimation (MLE), and statistical hypothesis testing (z, t, Chi-square). Modeled on the reference Operating Systems benchmark for the official GATE Data Science & AI (DA) curriculum.",
  level: "Undergraduate / GATE DA",
  estimatedHours: 42,
  prerequisites: [
    "Calculus (single and double integrals, limits, Taylor series)",
    "Linear Algebra (vectors, matrices, positive semi-definite covariance matrices)",
    "Basic set theory and discrete mathematics",
  ],
  learningOutcomes: [
    "Apply fundamental counting principles, permutations, and combinations to discrete sample spaces",
    "Compute marginal, conditional, and posterior probabilities using the Law of Total Probability and Bayes' Theorem",
    "Model stochastic processes using discrete distributions (Bernoulli, Binomial, Poisson) and continuous distributions (Uniform, Exponential, Gaussian)",
    "Calculate joint expectations, marginal distributions, conditional expectations, and covariance matrices for multivariate random vectors",
    "Apply Markov's inequality, Chebyshev's inequality, the Law of Large Numbers, and the Central Limit Theorem to sampling regimes",
    "Derive Maximum Likelihood Estimators (MLE) for standard parametric probability models",
    "Construct confidence intervals and perform formal statistical hypothesis tests (z-test, t-test, Chi-square test) interpreting p-values and Type I/II errors",
  ],
  gateScope: "GATE 2027 DA scope",
  gateBranches: ["da"],
  gateSyllabusTopics: [
    "Counting, permutations, combinations, probability axioms, sample space, independent events, mutually exclusive events",
    "Marginal, conditional and joint probability, Bayes Theorem, conditional expectation and variance",
    "Mean, median, mode, standard deviation, correlation, covariance, random variables, PMF, PDF, CDF",
    "Distributions: Bernoulli, Binomial, Poisson, Uniform, Exponential, Gaussian/Normal, Student's t, Chi-square",
    "Two-dimensional random variables, marginal and conditional distributions, covariance matrix",
    "Central Limit Theorem (CLT), Law of Large Numbers, Chebyshev's inequality",
    "Estimation & Inference: Maximum Likelihood Estimation (MLE), confidence intervals, z-test, t-test, Chi-square test",
  ],
  modules: [
    // =========================================================================
    // MODULE 1: PROBABILITY FOUNDATIONS & BAYES' THEOREM
    // =========================================================================
    {
      id: "da-stat-module-1-foundations",
      title: "Module 1: Probability Axioms, Counting & Bayes' Theorem",
      slug: "probability-foundations-and-bayes",
      description:
        "Combinatorics, Kolmogorov's probability axioms, independent and mutually exclusive events, conditional probability, Law of Total Probability, and Bayesian posterior updating.",
      order: 1,
      lessons: [
        {
          id: "combinatorics-probability-axioms-and-independence",
          title: "Combinatorics, Probability Axioms & Conditional Independence",
          slug: "combinatorics-probability-axioms-and-independence",
          order: 1,
          estimatedMinutes: 28,
          tagline: "Permutations, combinations, Kolmogorov axioms, and independent vs mutually exclusive events.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Events A and B are independent iff P(A ∩ B) = P(A) * P(B). Two non-empty events cannot be simultaneously independent AND mutually exclusive.",
            keyFormulasAndRules: [
              "Permutations (ordered): P(n, r) = n! / (n - r)!. Combinations (unordered): C(n, r) = n! / [ r! (n - r)! ].",
              "Kolmogorov Axioms: 1) P(E) >= 0; 2) P(S) = 1; 3) For mutually disjoint events, P(Union E_i) = Sum P(E_i).",
              "Inclusion-Exclusion (2 events): P(A ∪ B) = P(A) + P(B) - P(A ∩ B).",
              "Inclusion-Exclusion (3 events): P(A ∪ B ∪ C) = P(A) + P(B) + P(C) - P(A ∩ B) - P(B ∩ C) - P(A ∩ C) + P(A ∩ B ∩ C).",
              "Conditional Probability: P(A | B) = P(A ∩ B) / P(B), provided P(B) > 0.",
              "Pairwise vs Mutual Independence: Pairwise independence P(A_i ∩ A_j) = P(A_i) P(A_j) does NOT imply mutual independence P(A_1 ∩ ... ∩ A_k) = Prod P(A_i).",
            ],
            examPitfalls: [
              "Mutually exclusive events satisfy P(A ∩ B) = 0. If P(A) > 0 and P(B) > 0, then P(A ∩ B) = 0 != P(A)P(B). Hence mutually exclusive events are DEPENDENT!",
              "When sampling without replacement, events are dependent; with replacement, successive draws are independent.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Sample Spaces, Set Theory & Kolmogorov's Axioms",
              body: [
                "Probability theory mathematically formalizes uncertainty over a sample space Omega of all possible outcomes of a random experiment.",
                "**Kolmogorov's Three Axioms:**",
                "1. **Non-negativity:** For every event A in the event space F, `P(A) >= 0`.",
                "2. **Unit Measure:** The probability of the entire sample space is unity: `P(Omega) = 1`.",
                "3. **Countable Additivity:** For any countable sequence of pairwise disjoint events A_1, A_2, ... where `A_i ∩ A_j = empty` for i != j:",
                "   `P( Union_{i=1}^infinity A_i ) = Sum_{i=1}^infinity P(A_i)`.",
                "**Independent vs Mutually Exclusive Events:**",
                "Two events A and B are **independent** if knowledge that B occurred does not alter the likelihood of A: `P(A | B) = P(A) <=> P(A ∩ B) = P(A) P(B)`. By contrast, A and B are **mutually exclusive** (disjoint) if they cannot occur simultaneously: `A ∩ B = empty => P(A ∩ B) = 0`.",
              ],
              callout: {
                kind: "gate-tip",
                title: "The Mutual Exclusivity vs Independence Trap",
                message:
                  "If two events A and B each have non-zero probabilities, they CANNOT be both mutually exclusive and independent. If they are mutually exclusive, P(A ∩ B) = 0, but independence requires P(A ∩ B) = P(A)P(B) > 0. This conceptual contradiction is tested frequently in GATE DA.",
              },
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Combinatorial Feature Selection Probability",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Use the complement rule: P(At least one collinear) = 1 - P(Zero collinear selected).",
              solutionSteps: [
                "Problem: An automated machine learning feature selector randomly picks a subset of 3 features from an available set of 8 candidate features. Unknown to the system, exactly 2 of the 8 features are highly collinear. Find the probability that the selected subset contains at least one of the collinear features.",
                "Step 1: Compute the total number of equally likely ways to select 3 features from 8:",
                "  Total outcomes |S| = C(8, 3) = 8! / [ 3! * (8 - 3)! ] = (8 * 7 * 6) / (3 * 2 * 1) = 56.",
                "Step 2: Compute the number of ways to pick 3 features containing NO collinear features:",
                "  There are 8 - 2 = 6 non-collinear features.",
                "  Number of ways to choose 3 from these 6: C(6, 3) = (6 * 5 * 4) / (3 * 2 * 1) = 20.",
                "Step 3: Calculate the probability of selecting zero collinear features:",
                "  P(Zero collinear) = C(6, 3) / C(8, 3) = 20 / 56 = 5 / 14 ≈ 0.3571.",
                "Step 4: Apply the complement rule for 'at least one':",
                "  P(At least one collinear) = 1 - P(Zero collinear) = 1 - (5 / 14) = 9 / 14 ≈ 0.6429 (64.29%).",
                "Conclusion: The probability that the subset contains at least one collinear feature is exactly 9/14.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Introduction to Probability Models (12th Edition)",
                  authors: "Sheldon Ross",
                  year: "2019",
                  publisher: "Academic Press",
                  relevance: "Chapter 1: Elements of Probability and combinatorial sample spaces.",
                },
                {
                  title: "All of Statistics: A Concise Course in Statistical Inference",
                  authors: "Larry Wasserman",
                  year: "2004",
                  publisher: "Springer",
                  relevance: "Chapter 1: Probability spaces, axioms, and conditional independence.",
                },
              ],
            },
          ],
        },
        {
          id: "law-of-total-probability-and-bayes-theorem",
          title: "The Law of Total Probability & Bayes' Theorem",
          slug: "law-of-total-probability-and-bayes-theorem",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Partitions of sample space, marginalization, prior and posterior probabilities, and likelihood ratios.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Bayes' Theorem inverts conditional probabilities: P(A_k | B) = [ P(B | A_k) * P(A_k) ] / [ Sum_i P(B | A_i) * P(A_i) ].",
            keyFormulasAndRules: [
              "Law of Total Probability: For a partition {A_1, ..., A_k} of sample space S, P(B) = Sum_{i=1}^k P(B | A_i) P(A_i).",
              "Bayes' Rule: P(A | B) = [ P(B | A) * P(A) ] / P(B).",
              "Posterior proportional to Likelihood * Prior: P(theta | D) ∝ P(D | theta) * P(theta).",
              "Odds Form of Bayes' Rule: Odds(A | B) = Odds(A) * [ P(B | A) / P(B | A^c) ], where P(B|A)/P(B|A^c) is the Bayes Factor.",
            ],
            examPitfalls: [
              "Base Rate Fallacy: In rare disease testing (low prior P(D)), even a test with 99% accuracy produces a posterior P(D|+) far lower than expected due to false positives from the large healthy population.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Inverse Probability & The Bayesian Mechanism",
              body: [
                "In machine learning, we often observe evidence (data D) and wish to infer the unobserved generative hypothesis or class label C.",
                "**The Law of Total Probability:**",
                "Let events A_1, A_2, ..., A_k form a partition of the sample space Omega (meaning they are mutually disjoint `A_i ∩ A_j = empty` and collectively exhaustive `Union A_i = Omega`). Then for any event B:",
                "`P(B) = Sum_{i=1}^k P(B ∩ A_i) = Sum_{i=1}^k P(B | A_i) P(A_i)`.",
                "**Bayes' Theorem Formulation:**",
                "Substituting the total probability of B into the denominator of the conditional definition `P(A_k | B) = P(A_k ∩ B) / P(B)` yields:",
                "`P(A_k | B) = [ P(B | A_k) P(A_k) ] / [ Sum_{i=1}^k P(B | A_i) P(A_i) ]`.",
                "Here, P(A_k) is the **Prior**, P(B | A_k) is the **Likelihood**, P(B) is the **Evidence / Marginal Likelihood**, and P(A_k | B) is the **Posterior**.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Rare Disease Diagnostic & Base Rate Fallacy",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Do not confuse P(Positive | Disease) = 0.98 with the desired posterior P(Disease | Positive).",
              solutionSteps: [
                "Problem: A rare medical disease D affects 0.5% of a population (prior P(D) = 0.005). A diagnostic test has 98% sensitivity (P(+ | D) = 0.98) and 95% specificity (P(- | D^c) = 0.95). If a randomly chosen patient tests positive, what is the posterior probability that they actually have the disease?",
                "Step 1: Define given probabilities and complements:",
                "  P(D) = 0.005  =>  P(D^c) = 1 - 0.005 = 0.995",
                "  P(+ | D) = 0.98 (True Positive Rate / Sensitivity)",
                "  P(- | D^c) = 0.95 (Specificity)  =>  P(+ | D^c) = 1 - 0.95 = 0.05 (False Positive Rate)",
                "Step 2: Compute total probability of a positive test P(+):",
                "  P(+) = P(+ | D) * P(D) + P(+ | D^c) * P(D^c)",
                "  P(+) = (0.98 * 0.005) + (0.05 * 0.995)",
                "  P(+) = 0.0049 + 0.04975 = 0.05465",
                "Step 3: Apply Bayes' Theorem:",
                "  P(D | +) = [ P(+ | D) * P(D) ] / P(+)",
                "  P(D | +) = 0.0049 / 0.05465 = 490 / 5465 ≈ 0.08966 (8.97%).",
                "Conclusion: Despite a 98% sensitive and 95% specific test, a positive test result yields only an ~8.97% chance of having the disease because the prior base rate (0.5%) is so small.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "A First Course in Probability (10th Edition)",
                  authors: "Sheldon Ross",
                  year: "2018",
                  publisher: "Pearson",
                  relevance: "Chapter 3: Conditional Probability, Total Probability, and Bayes' Formula.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 2: RANDOM VARIABLES & STANDARD DISTRIBUTIONS
    // =========================================================================
    {
      id: "da-stat-module-2-distributions",
      title: "Module 2: Discrete & Continuous Distributions",
      slug: "random-variables-and-distributions",
      description:
        "Random variables, Probability Mass Functions (PMF), Probability Density Functions (PDF), Cumulative Distribution Functions (CDF), Binomial, Poisson, Uniform, Exponential, and Gaussian distributions.",
      order: 2,
      lessons: [
        {
          id: "discrete-random-variables-pmf-binomial-poisson",
          title: "Discrete Random Variables: PMF, CDF, Binomial & Poisson",
          slug: "discrete-random-variables-pmf-binomial-poisson",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Expectation E[X], Variance Var(X), Bernoulli trials, Binomial PMF, and Poisson limit theorem.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Binomial: n independent trials with success probability p (Mean = np, Var = np(1-p)). Poisson: rare events with rate lambda (Mean = lambda, Var = lambda).",
            keyFormulasAndRules: [
              "Expectation: E[X] = Sum x * p(x). Linearity: E[aX + bY + c] = a E[X] + b E[Y] + c (always holds!).",
              "Variance: Var(X) = E[X^2] - (E[X])^2. Scaling: Var(aX + b) = a^2 Var(X).",
              "Bernoulli: P(X=1) = p, P(X=0) = 1-p. Mean = p, Var = p(1-p).",
              "Binomial PMF: P(X = k) = C(n, k) * p^k * (1 - p)^{n - k} for k = 0, 1, ..., n.",
              "Poisson PMF: P(X = k) = ( e^{-lambda} * lambda^k ) / k! for k = 0, 1, 2, ...",
              "Poisson Approximation to Binomial: When n -> infinity and p -> 0 such that np = lambda (constant), Binomial(n, p) -> Poisson(lambda).",
            ],
            examPitfalls: [
              "Linearity of Expectation holds for ALL random variables whether independent or dependent. Linearity of Variance Var(X + Y) = Var(X) + Var(Y) holds ONLY when Cov(X, Y) = 0.",
              "For Poisson distribution, Mean = Variance = lambda. If Mean != Variance in empirical data, the distribution is not Poisson.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Discrete Random Variables, Moments & Distributions",
              body: [
                "A discrete random variable X maps outcomes from sample space Omega to countable values in R, characterized by a Probability Mass Function (PMF) `p(x) = P(X = x)` satisfying `p(x) >= 0` and `Sum p(x) = 1`.",
                "**Binomial Distribution:**",
                "Models the number of successes k in n independent Bernoulli trials with constant success probability p.",
                "`P(X = k) = (n choose k) p^k (1 - p)^{n - k}`.",
                "Expectation: `E[X] = np`. Variance: `Var(X) = np(1 - p)`.",
                "**Poisson Distribution:**",
                "Models the count of rare events occurring in a fixed interval of time or space with constant average arrival rate lambda.",
                "`P(X = k) = (e^{-lambda} lambda^k) / k!`.",
                "Crucial Property: `E[X] = Var(X) = lambda`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Poisson Queueing Arrivals",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Remember that P(X >= 2) = 1 - P(X = 0) - P(X = 1).",
              solutionSteps: [
                "Problem: Network requests arrive at an API server following a Poisson process with an average rate of lambda = 3 requests per minute. Find the exact probability that at least 2 requests arrive in a given 1-minute interval.",
                "Step 1: State the Poisson PMF with parameter lambda = 3:",
                "  P(X = k) = (e^{-3} * 3^k) / k!",
                "Step 2: Express 'at least 2' via the complement:",
                "  P(X >= 2) = 1 - P(X = 0) - P(X = 1)",
                "Step 3: Evaluate P(X = 0):",
                "  P(X = 0) = (e^{-3} * 3^0) / 0! = e^{-3} / 1 ≈ 0.04979",
                "Step 4: Evaluate P(X = 1):",
                "  P(X = 1) = (e^{-3} * 3^1) / 1! = 3 * e^{-3} ≈ 0.14936",
                "Step 5: Compute P(X >= 2):",
                "  P(X >= 2) = 1 - (e^{-3} + 3 * e^{-3}) = 1 - 4 * e^{-3}",
                "  P(X >= 2) = 1 - 4 * 0.04979 = 1 - 0.19915 = 0.80085 (approx 80.09%).",
                "Conclusion: The probability that at least 2 requests arrive in one minute is 1 - 4e^{-3} ≈ 0.8009.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Mathematical Statistics with Applications (7th Edition)",
                  authors: "Dennis Wackerly, William Mendenhall, Richard L. Scheaffer",
                  year: "2008",
                  publisher: "Cengage Learning",
                  relevance: "Chapter 3: Discrete Random Variables and their Probability Distributions.",
                },
              ],
            },
          ],
        },
        {
          id: "continuous-random-variables-pdf-uniform-exponential",
          title: "Continuous Random Variables: PDF, Uniform & Exponential",
          slug: "continuous-random-variables-pdf-uniform-exponential",
          order: 2,
          estimatedMinutes: 30,
          tagline: "PDF integration, CDF properties, Continuous Uniform, Exponential distribution, and the memoryless property.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Continuous random variables have P(X = c) = 0 for any single point c. Probability is the area under PDF: P(a <= X <= b) = integral_a^b f(x) dx = F(b) - F(a).",
            keyFormulasAndRules: [
              "PDF normalization: integral_{-inf}^{inf} f(x) dx = 1.",
              "CDF Definition: F(x) = P(X <= x) = integral_{-inf}^x f(t) dt. Derivative: f(x) = dF(x) / dx.",
              "Continuous Uniform U(a, b): f(x) = 1 / (b - a) on [a, b]. Mean = (a + b) / 2, Var = (b - a)^2 / 12.",
              "Exponential Exp(lambda): f(x) = lambda * e^{-lambda * x} for x >= 0. CDF: F(x) = 1 - e^{-lambda * x}.",
              "Exponential Moments: Mean E[X] = 1 / lambda, Variance Var(X) = 1 / lambda^2.",
              "Memoryless Property: P(X > s + t | X > s) = P(X > t). The ONLY continuous distribution with this property!",
            ],
            examPitfalls: [
              "Do not confuse rate parameter lambda with scale parameter beta = 1/lambda. In GATE DA, verify whether the problem defines f(x) = lambda e^{-lambda x} or (1/beta) e^{-x/beta}.",
              "P(a <= X <= b) = P(a < X < b) for continuous random variables because single points have zero measure.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Continuous Probability Density & The Memoryless Exponential",
              body: [
                "For continuous random variables, probabilities correspond to intervals. The Probability Density Function (PDF) f(x) represents density, not point probability: `P(X in [x, x + dx]) ≈ f(x) dx`.",
                "**Continuous Uniform Distribution U(a, b):**",
                "Every subinterval of equal length within [a, b] has identical probability. `f(x) = 1 / (b - a)`.",
                "- `E[X] = (a + b) / 2`",
                "- `Var(X) = (b - a)^2 / 12`",
                "**Exponential Distribution Exp(lambda):**",
                "Models the continuous waiting time until the first occurrence of a Poisson event.",
                "`f(x) = lambda e^{-lambda x}` for `x >= 0`.",
                "`F(x) = 1 - e^{-lambda x}`.",
                "**Proof of the Memoryless Property:**",
                "`P(X > s + t | X > s) = P(X > s + t ∩ X > s) / P(X > s) = P(X > s + t) / P(X > s)`",
                "`= e^{-lambda (s + t)} / e^{-lambda s} = e^{-lambda t} = P(X > t)`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Memoryless Exponential Survival",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Do not compute complex conditional integration; apply the memoryless property directly.",
              solutionSteps: [
                "Problem: The lifetime of a server GPU (in thousands of hours) follows an Exponential distribution with rate parameter lambda = 0.5. Given that a GPU has already operated without failure for 2,000 hours (X > 2), compute the probability that it will survive for at least 5,000 hours in total (X > 5).",
                "Step 1: Identify the conditional probability required:",
                "  P(X > 5 | X > 2)",
                "Step 2: Express in the memoryless form P(X > s + t | X > s):",
                "  Here s = 2 and s + t = 5  =>  t = 5 - 2 = 3.",
                "Step 3: Apply the memoryless property:",
                "  P(X > 2 + 3 | X > 2) = P(X > 3)",
                "Step 4: Compute survival probability for Exponential distribution:",
                "  P(X > t) = 1 - F(t) = e^{-lambda * t}",
                "  Substitute lambda = 0.5 and t = 3:",
                "  P(X > 3) = e^{-(0.5 * 3)} = e^{-1.5}",
                "Step 5: Calculate numerical value:",
                "  e^{-1.5} ≈ 0.22313 (approx 22.31%).",
                "Conclusion: The probability of surviving an additional 3,000 hours given it survived 2,000 hours is e^{-1.5} ≈ 0.2231.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Introduction to Probability and Statistics for Engineers and Scientists (5th Edition)",
                  authors: "Sheldon Ross",
                  year: "2014",
                  publisher: "Academic Press",
                  relevance: "Chapter 5: Continuous Random Variables, Uniform, and Exponential distributions.",
                },
              ],
            },
          ],
        },
        {
          id: "normal-gaussian-distribution-and-standard-scores",
          title: "The Normal (Gaussian) Distribution & Standard Score Math",
          slug: "normal-gaussian-distribution-and-standard-scores",
          order: 3,
          estimatedMinutes: 30,
          tagline: "Symmetric bell curve, inflection points at mu ± sigma, Z-score transformation, and table integration.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Standard Normal Z = (X - mu) / sigma ~ N(0, 1). Normal distribution is symmetric about mu: Phi(-z) = 1 - Phi(z).",
            keyFormulasAndRules: [
              "Gaussian PDF: f(x) = [ 1 / (sigma * sqrt(2*pi)) ] * exp( - (x - mu)^2 / (2 * sigma^2) ).",
              "Standard Normal PDF: phi(z) = [ 1 / sqrt(2*pi) ] * exp( - z^2 / 2 ).",
              "Symmetry Property: P(Z <= -z) = Phi(-z) = 1 - Phi(z).",
              "Empirical Rule: P(mu - sigma <= X <= mu + sigma) ≈ 68.27%; P(mu - 2*sigma <= X <= mu + 2*sigma) ≈ 95.45%; P(mu - 3*sigma <= X <= mu + 3*sigma) ≈ 99.73%.",
              "Linear Combination of Normals: If X_1 ~ N(mu_1, sigma_1^2) and X_2 ~ N(mu_2, sigma_2^2) are independent, then a X_1 + b X_2 ~ N(a mu_1 + b mu_2, a^2 sigma_1^2 + b^2 sigma_2^2).",
            ],
            examPitfalls: [
              "Normal distribution variance scaling: Var(aX) = a^2 Var(X). When taking standard deviation, sigma_{aX} = |a| * sigma_X.",
              "Inflection points of the Gaussian bell curve occur precisely at x = mu - sigma and x = mu + sigma.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Gaussian Distribution & Its Symmetries",
              body: [
                "The Gaussian distribution N(mu, sigma^2) is the paramount distribution in statistical machine learning, arising naturally as the limiting distribution of sums under the Central Limit Theorem and as the maximum entropy distribution for a specified mean and variance.",
                "**Standardization (Z-Transform):**",
                "Any general normal variable `X ~ N(mu, sigma^2)` is converted to the standard normal `Z ~ N(0, 1)` via the affine transformation:",
                "`Z = (X - mu) / sigma`.",
                "The cumulative distribution function of Z is denoted `Phi(z) = P(Z <= z)`.",
                "**Key Symmetry Identities:**",
                "1. `Phi(0) = 0.5`",
                "2. `Phi(-z) = 1 - Phi(z)`",
                "3. `P(a <= X <= b) = Phi((b - mu)/sigma) - Phi((a - mu)/sigma)`",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Standard Normal Interval Probability",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Use the symmetry identity Phi(-z) = 1 - Phi(z) to evaluate negative Z-scores.",
              solutionSteps: [
                "Problem: Model accuracy scores across 1000 cross-validation splits follow a normal distribution with mean mu = 75% and standard deviation sigma = 8%. Given Phi(1.0) = 0.8413 and Phi(2.0) = 0.9772, find the proportion of models scoring between 67% and 91%.",
                "Step 1: Convert boundary values to Standard Normal Z-scores:",
                "  For lower bound x1 = 67:",
                "    z1 = (67 - 75) / 8 = -8 / 8 = -1.0",
                "  For upper bound x2 = 91:",
                "    z2 = (91 - 75) / 8 = 16 / 8 = +2.0",
                "Step 2: Express interval probability in terms of CDF Phi(z):",
                "  P(67 <= X <= 91) = P(-1.0 <= Z <= 2.0) = Phi(2.0) - Phi(-1.0)",
                "Step 3: Apply the symmetry identity for Phi(-1.0):",
                "  Phi(-1.0) = 1 - Phi(1.0) = 1 - 0.8413 = 0.1587",
                "Step 4: Compute final probability:",
                "  P = Phi(2.0) - Phi(-1.0) = 0.9772 - 0.1587 = 0.8185 (81.85%).",
                "Conclusion: Approximately 81.85% of the models achieve accuracy scores between 67% and 91%.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "All of Statistics: A Concise Course in Statistical Inference",
                  authors: "Larry Wasserman",
                  year: "2004",
                  publisher: "Springer",
                  relevance: "Chapter 2.3: The Normal Distribution and probability calculations.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 3: JOINT DISTRIBUTIONS, COVARIANCE & LIMIT THEOREMS
    // =========================================================================
    {
      id: "da-stat-module-3-joint-clt",
      title: "Module 3: Joint Distributions, Covariance & Limit Theorems",
      slug: "joint-distributions-and-limit-theorems",
      description:
        "Bivariate random variables, marginalization, conditional expectation and variance, covariance matrices, Chebyshev's inequality, Law of Large Numbers, and the Central Limit Theorem.",
      order: 3,
      lessons: [
        {
          id: "joint-distributions-marginal-and-conditional-expectation",
          title: "Joint Distributions, Marginalization & Conditional Expectation",
          slug: "joint-distributions-marginal-and-conditional-expectation",
          order: 1,
          estimatedMinutes: 32,
          tagline: "Double integrals over coupled domains, marginal PDFs, conditional density, and iterated expectation.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Marginal PDF f_X(x) = integral_{-inf}^{inf} f(x, y) dy. Conditional expectation E[Y|X=x] = integral y * f_{Y|X}(y|x) dy is a FUNCTION of x.",
            keyFormulasAndRules: [
              "Joint PDF Normalization: integral integral f(x, y) dx dy = 1.",
              "Marginal PDFs: f_X(x) = integral f(x, y) dy; f_Y(y) = integral f(x, y) dx.",
              "Conditional PDF: f_{Y|X}(y | x) = f(x, y) / f_X(x), provided f_X(x) > 0.",
              "Independence Criterion: X and Y are independent iff f(x, y) = f_X(x) * f_Y(y) for ALL (x, y).",
              "Law of Total Expectation: E[Y] = E_X[ E_{Y|X}[Y | X] ].",
              "Law of Total Variance (Eve's Law): Var(Y) = E[Var(Y|X)] + Var(E[Y|X]).",
            ],
            examPitfalls: [
              "When integrating joint PDFs over coupled domains (e.g. 0 <= x <= y <= 1), the inner and outer integration limits must strictly respect boundary inequalities.",
              "E[Y|X] is a RANDOM VARIABLE (a function of X); E[E[Y|X]] is a SCALAR equal to E[Y].",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Multivariate Random Variables & Marginalization",
              body: [
                "Real-world data science problems inherently involve vectors of multiple dependent variables (X_1, X_2, ..., X_d).",
                "**Bivariate Probability Density:**",
                "For continuous random variables (X, Y), the joint probability density function f(x, y) satisfies:",
                "`P((X, Y) in R) = iint_R f(x, y) dx dy`.",
                "**Marginalization:**",
                "To extract the behavior of individual variable X, we integrate out all other dimensions (nuisance variables):",
                "`f_X(x) = int_{-infinity}^{+infinity} f(x, y) dy`.",
                "**Conditional Density & Expectation:**",
                "`f_{Y|X}(y | x) = f(x, y) / f_X(x)`.",
                "`E[Y | X = x] = int_{-infinity}^{+infinity} y f_{Y|X}(y | x) dy`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Coupled Triangle Domain Joint PDF",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "When finding f_X(x), integrate y from x to 1; do NOT integrate from 0 to 1.",
              solutionSteps: [
                "Problem: Let (X, Y) have joint PDF f(x, y) = c * x for 0 <= x <= y <= 1, and 0 elsewhere. Find the normalization constant c and the marginal expectation E[Y].",
                "Step 1: Set double integral over the triangular region to 1:",
                "  Region: 0 <= x <= y and 0 <= y <= 1.",
                "  int_0^1 dy int_0^y c * x dx = 1",
                "Step 2: Evaluate inner integral with respect to x:",
                "  int_0^y c * x dx = c * [x^2 / 2]_0^y = c * (y^2 / 2)",
                "Step 3: Evaluate outer integral with respect to y:",
                "  int_0^1 (c / 2) * y^2 dy = (c / 2) * [y^3 / 3]_0^1 = c / 6 = 1  =>  c = 6.",
                "  Joint PDF: f(x, y) = 6x for 0 <= x <= y <= 1.",
                "Step 4: Find marginal PDF f_Y(y):",
                "  f_Y(y) = int_0^y 6x dx = 6 * [x^2 / 2]_0^y = 3 y^2 for 0 <= y <= 1.",
                "Step 5: Compute E[Y]:",
                "  E[Y] = int_0^1 y * f_Y(y) dy = int_0^1 y * (3 y^2) dy = 3 * int_0^1 y^3 dy",
                "  E[Y] = 3 * [y^4 / 4]_0^1 = 3 / 4 = 0.75.",
                "Conclusion: The normalization constant is c = 6 and the marginal expectation is E[Y] = 3/4.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Introduction to Probability Models (12th Edition)",
                  authors: "Sheldon Ross",
                  year: "2019",
                  publisher: "Academic Press",
                  relevance: "Chapter 2: Jointly distributed random variables and conditional expectations.",
                },
              ],
            },
          ],
        },
        {
          id: "covariance-correlation-and-bivariate-normals",
          title: "Covariance, Correlation & Bivariate Gaussian Properties",
          slug: "covariance-correlation-and-bivariate-normals",
          order: 2,
          estimatedMinutes: 30,
          tagline: "Covariance Cov(X, Y), Pearson correlation rho, Positive Semi-Definite covariance matrices, and bivariate Gaussian independence.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Cov(X, Y) = E[XY] - E[X]E[Y]. If X, Y are independent, Cov(X, Y) = 0. The converse holds ONLY for jointly Gaussian variables!",
            keyFormulasAndRules: [
              "Covariance: Cov(X, Y) = E[(X - mu_X)(Y - mu_Y)] = E[XY] - E[X]E[Y].",
              "Symmetry & Variance: Cov(X, X) = Var(X). Cov(X, Y) = Cov(Y, X).",
              "Bilinear Property: Cov(aX + bY, cZ + dW) = ac Cov(X, Z) + ad Cov(X, W) + bc Cov(Y, Z) + bd Cov(Y, W).",
              "Variance of Sum: Var(aX + bY) = a^2 Var(X) + b^2 Var(Y) + 2ab Cov(X, Y).",
              "Pearson Correlation: rho_{X,Y} = Cov(X, Y) / (sigma_X * sigma_Y) in [-1, +1]. |rho| = 1 iff Y = aX + b almost surely.",
              "Bivariate Normal Property: If (X, Y) is bivariate normal, then Cov(X, Y) = 0 <=> X and Y are INDEPENDENT.",
            ],
            examPitfalls: [
              "Var(X - Y) = Var(X) + Var(Y) - 2 Cov(X, Y). A frequent sign error is writing Var(X) - Var(Y).",
              "Zero correlation does NOT imply independence in general (e.g. Y = X^2 with symmetric X around 0 has Cov(X, Y) = 0, yet Y is completely determined by X).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Linear Dependence: Covariance & Correlation",
              body: [
                "Covariance measures the joint linear variability of two random variables.",
                "**Properties of Covariance:**",
                "1. `Cov(X, Y) = E[XY] - E[X] E[Y]`.",
                "2. If X and Y are independent: `E[XY] = E[X] E[Y] => Cov(X, Y) = 0`.",
                "**Pearson Correlation Coefficient rho:**",
                "Normalized scale-invariant measure of linear association:",
                "`rho = Cov(X, Y) / (sigma_X sigma_Y)`.",
                "By Cauchy-Schwarz inequality: `-1 <= rho <= +1`.",
                "- `rho = +1`: Perfect positive linear relationship (`Y = aX + b, a > 0`).",
                "- `rho = -1`: Perfect negative linear relationship (`Y = aX + b, a < 0`).",
                "- `rho = 0`: Uncorrelated (no linear relationship).",
                "**The Bivariate Gaussian Special Case:**",
                "For jointly Gaussian random variables, uncorrelatedness strictly implies independence, because cross-terms in the exponent of the bivariate normal PDF vanish when rho = 0.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Variance of Linear Combination",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Notice the negative coefficient on Y: (-3)^2 = +9, and the cross-term has 2 * (2) * (-3) * Cov(X, Y).",
              solutionSteps: [
                "Problem: Random variables X and Y have Var(X) = 16, Var(Y) = 25, and Pearson correlation coefficient rho = 0.6. Find the variance of the linear combination W = 2X - 3Y + 7.",
                "Step 1: Compute standard deviations of X and Y:",
                "  sigma_X = sqrt(16) = 4",
                "  sigma_Y = sqrt(25) = 5",
                "Step 2: Compute Cov(X, Y):",
                "  Cov(X, Y) = rho * sigma_X * sigma_Y = 0.6 * 4 * 5 = 0.6 * 20 = 12.",
                "Step 3: State the variance expansion for Var(aX + bY + c):",
                "  Constants do not affect variance: Var(W) = Var(2X - 3Y)",
                "  Var(aX + bY) = a^2 * Var(X) + b^2 * Var(Y) + 2 * a * b * Cov(X, Y)",
                "Step 4: Substitute coefficients a = 2, b = -3:",
                "  Var(W) = (2)^2 * Var(X) + (-3)^2 * Var(Y) + 2 * (2) * (-3) * Cov(X, Y)",
                "  Var(W) = 4 * (16) + 9 * (25) - 12 * Cov(X, Y)",
                "  Var(W) = 64 + 225 - 12 * (12) = 289 - 144 = 145.",
                "Conclusion: The variance of 2X - 3Y + 7 is exactly 145.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "All of Statistics: A Concise Course in Statistical Inference",
                  authors: "Larry Wasserman",
                  year: "2004",
                  publisher: "Springer",
                  relevance: "Chapter 3: Expectation, Variance, Covariance, and Correlation.",
                },
              ],
            },
          ],
        },
        {
          id: "chebyshev-inequality-lln-and-central-limit-theorem",
          title: "Chebyshev's Inequality, Law of Large Numbers & Central Limit Theorem",
          slug: "chebyshev-inequality-lln-and-central-limit-theorem",
          order: 3,
          estimatedMinutes: 32,
          tagline: "Markov bound, Chebyshev tail bound, Weak Law of Large Numbers, and Gaussian convergence of sample sums.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Central Limit Theorem: For ANY population with mean mu and finite variance sigma^2, the sample mean X_bar of n i.i.d. draws converges in distribution to N(mu, sigma^2 / n) as n -> infinity.",
            keyFormulasAndRules: [
              "Markov's Inequality: For non-negative random variable X >= 0 and a > 0, P(X >= a) <= E[X] / a.",
              "Chebyshev's Inequality: P(|X - mu| >= k * sigma) <= 1 / k^2. Equivalent form: P(|X - mu| < k * sigma) >= 1 - 1 / k^2.",
              "Weak Law of Large Numbers (WLLN): As n -> infinity, sample mean X_bar converges in probability to population mean mu: P(|X_bar - mu| >= epsilon) -> 0.",
              "Central Limit Theorem (CLT): Sample sum S_n = Sum_{i=1}^n X_i ~ N(n mu, n sigma^2).",
              "Sample Mean Standard Error: SE(X_bar) = sigma / sqrt(n).",
              "Standardized CLT Variable: Z_n = (X_bar - mu) / (sigma / sqrt(n)) = (S_n - n mu) / (sigma sqrt(n)) -> N(0, 1).",
            ],
            examPitfalls: [
              "Chebyshev's inequality provides a WORST-CASE upper bound valid for ANY distribution; it is conservative compared to exact Gaussian probabilities.",
              "The standard error of the sample mean is sigma / sqrt(n), NOT sigma / n.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. Concentration Inequalities & Asymptotic Convergence",
              body: [
                "Concentration inequalities allow us to bound probabilities of extreme deviations without knowing the complete underlying distribution.",
                "**Markov's Inequality:** For non-negative random variable X >= 0 and any constant a > 0: `P(X >= a) <= E[X] / a`.",
                "**Chebyshev's Inequality:** Applying Markov's inequality to `(X - mu)^2` yields: `P(|X - mu| >= epsilon) <= Var(X) / epsilon^2`.",
                "Setting `epsilon = k * sigma` gives: `P(|X - mu| >= k * sigma) <= 1 / k^2`.",
                "**The Central Limit Theorem (Lindeberg-Levy):**",
                "Let X_1, X_2, ..., X_n be independent and identically distributed (i.i.d.) random variables with mean mu and finite variance sigma^2 > 0.",
                "Then regardless of the underlying distribution of X_i (whether Uniform, Exponential, Poisson, or custom), the normalized sample mean converges in distribution to the standard normal distribution:",
                "`Z_n = (X_bar - mu) / (sigma / sqrt(n)) ---> N(0, 1)` as `n -> infinity`.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Chebyshev Conservative Bound",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Identify the number of standard deviations k: deviation 15 divided by sigma = 5 gives k = 3.",
              solutionSteps: [
                "Problem: A random variable X has mean mu = 50 and variance Var(X) = 25. Its probability distribution is completely unknown. Using Chebyshev's inequality, determine the guaranteed minimum probability that X falls strictly between 35 and 65.",
                "Step 1: Compute standard deviation sigma:",
                "  sigma = sqrt(Var(X)) = sqrt(25) = 5.",
                "Step 2: Express the interval (35, 65) in terms of deviation from mean mu = 50:",
                "  35 < X < 65  <=>  -15 < X - 50 < 15  <=>  |X - 50| < 15.",
                "Step 3: Relate deviation to standard deviation units k * sigma:",
                "  15 = k * sigma = k * 5  =>  k = 15 / 5 = 3.",
                "Step 4: Apply Chebyshev's two-sided bounded formula:",
                "  P(|X - mu| < k * sigma) >= 1 - (1 / k^2)",
                "Step 5: Substitute k = 3:",
                "  P(|X - 50| < 15) >= 1 - (1 / 3^2) = 1 - 1/9 = 8/9 ≈ 0.8889 (88.89%).",
                "Conclusion: Regardless of the shape of the distribution, at least 88.89% (8/9) of the distribution mass is guaranteed to lie between 35 and 65.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "All of Statistics: A Concise Course in Statistical Inference",
                  authors: "Larry Wasserman",
                  year: "2004",
                  publisher: "Springer",
                  relevance: "Chapter 4: Inequalities (Markov, Chebyshev, Hoeffding) and Chapter 5: Convergence of Random Variables.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 4: SAMPLING DISTRIBUTIONS & PARAMETER ESTIMATION
    // =========================================================================
    {
      id: "da-stat-module-4-estimation",
      title: "Module 4: Sampling Distributions & Maximum Likelihood Estimation",
      slug: "sampling-distributions-and-mle",
      description:
        "Sampling distributions (Chi-square, Student's t, Snedecor's F), point estimation properties (bias, consistency, efficiency), and Maximum Likelihood Estimation (MLE).",
      order: 4,
      lessons: [
        {
          id: "sampling-distributions-chisquare-t-and-f",
          title: "Sampling Distributions: Chi-Square, Student's t & F-Distributions",
          slug: "sampling-distributions-chisquare-t-and-f",
          order: 1,
          estimatedMinutes: 30,
          tagline: "Degrees of freedom, ratios of Chi-squares, heavy tails, and small-sample statistics.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Chi-square is a sum of squared standard normals. Student's t is a normal divided by sqrt(ChiSq / df). F is a ratio of two independent Chi-squares divided by their respective degrees of freedom.",
            keyFormulasAndRules: [
              "Chi-Square Definition: If Z_1, ..., Z_k ~ i.i.d N(0, 1), then Q = Sum_{i=1}^k Z_i^2 ~ ChiSq(k). Mean = k, Var = 2k.",
              "Sample Variance Distribution: (n - 1) S^2 / sigma^2 ~ ChiSq(n - 1) for normal samples.",
              "Student's t Definition: T = Z / sqrt(V / k), where Z ~ N(0, 1) and V ~ ChiSq(k) are independent. Mean = 0 (k > 1), Var = k / (k - 2) (k > 2).",
              "Snedecor's F Definition: F = ( U / d_1 ) / ( V / d_2 ), where U ~ ChiSq(d_1) and V ~ ChiSq(d_2) are independent.",
              "t and F Relationship: If T ~ t(k), then T^2 ~ F(1, k).",
            ],
            examPitfalls: [
              "Student's t-distribution has HEAVIER tails than the standard normal distribution due to uncertainty in estimating the unknown variance s.",
              "As degrees of freedom k -> infinity, the t-distribution converges to the Standard Normal distribution N(0, 1).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Geometry of Sampling Distributions",
              body: [
                "Statistical inference relies on probability distributions derived from functions of sample statistics.",
                "**1. Chi-Square Distribution ChiSq(k):**",
                "Arises when summing the squares of k independent standard normal random variables. It is right-skewed and defined strictly on [0, infinity).",
                "`Mean = k`, `Variance = 2k`.",
                "**2. Student's t-Distribution t(k):**",
                "Formulated by William Gosset ('Student') in 1908 to account for additional uncertainty when sample size is small and the true population variance sigma^2 is unknown and replaced by sample variance s^2.",
                "`T = [ (X_bar - mu) / (s / sqrt(n)) ] ~ t(n - 1)`.",
                "**3. Snedecor's F-Distribution F(d_1, d_2):**",
                "Used to compare variances between two independent populations (ANOVA tests).",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Identifying Sampling Distribution Constructs",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Ensure the denominator chi-square variable is divided by its own degrees of freedom before taking the square root.",
              solutionSteps: [
                "Problem: Let Z1, Z2, Z3, Z4, Z5 be independent standard normal random variables ~ N(0, 1). Identify the exact distribution (including parameter values) of: W = Z1 / sqrt[ (Z2^2 + Z3^2 + Z4^2 + Z5^2) / 4 ].",
                "Step 1: Inspect the numerator:",
                "  Z1 ~ N(0, 1) is a single standard normal variable.",
                "Step 2: Inspect the sum in the denominator:",
                "  V = Z2^2 + Z3^2 + Z4^2 + Z5^2",
                "  Since Z2, Z3, Z4, Z5 are 4 independent standard normals, the sum of their squares follows a Chi-square distribution with 4 degrees of freedom: V ~ ChiSq(4).",
                "Step 3: Check independence between numerator and denominator:",
                "  Z1 is independent of Z2, Z3, Z4, Z5, so Z1 and V are independent.",
                "Step 4: Apply Student's t-distribution definition:",
                "  T = Z / sqrt(V / k), where Z ~ N(0, 1), V ~ ChiSq(k), and Z, V are independent.",
                "  Here k = 4.",
                "Conclusion: W follows a Student's t-distribution with 4 degrees of freedom: W ~ t(4).",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "Mathematical Statistics with Applications (7th Edition)",
                  authors: "Wackerly, Mendenhall, Scheaffer",
                  year: "2008",
                  publisher: "Cengage Learning",
                  relevance: "Chapter 7: Sampling Distributions and the Central Limit Theorem.",
                },
              ],
            },
          ],
        },
        {
          id: "point-estimation-mle-and-method-of-moments",
          title: "Point Estimation: Maximum Likelihood Estimation (MLE)",
          slug: "point-estimation-mle-and-method-of-moments",
          order: 2,
          estimatedMinutes: 32,
          tagline: "Likelihood functions, log-likelihood optimization, score function, Hessian concavity, and estimator properties.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Maximum Likelihood Estimator theta_hat maximizes the likelihood of observing the training sample: d(ln L(theta)) / d(theta) = 0.",
            keyFormulasAndRules: [
              "Likelihood Function: L(theta) = Product_{i=1}^n f(x_i; theta) for i.i.d. samples.",
              "Log-Likelihood Function: l(theta) = ln L(theta) = Sum_{i=1}^n ln f(x_i; theta).",
              "Score Function: S(theta) = d l(theta) / d theta.",
              "Unbiasedness: Estimator theta_hat is unbiased if E[theta_hat] = theta. Bias = E[theta_hat] - theta.",
              "Consistency: theta_hat converges in probability to theta as n -> infinity.",
              "Invariance Property of MLE: If theta_hat is the MLE of theta, then g(theta_hat) is the MLE of g(theta).",
            ],
            examPitfalls: [
              "Sample variance S^2 = (1/n) Sum (X_i - X_bar)^2 is a BIASED estimator of sigma^2 (E[S^2] = (n-1)/n sigma^2). The unbiased estimator divides by n - 1 (Bessel's correction).",
              "For Uniform U(0, theta), the likelihood is discontinuous; setting derivative to zero fails! The MLE is the maximum sample order statistic: theta_hat = max(X_1, ..., X_n).",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Principle of Maximum Likelihood",
              body: [
                "Given observed data x_1, x_2, ..., x_n drawn i.i.d. from a parametric distribution with parameter vector theta, point estimation seeks the single optimal numerical estimate theta_hat.",
                "**Likelihood vs Probability:**",
                "While probability `f(x | theta)` views theta as fixed and evaluates the probability of outcomes x, the likelihood function `L(theta | x)` views observed data x as fixed and evaluates the plausibility of parameter values theta.",
                "**Log-Likelihood Simplification:**",
                "Because the natural logarithm is a strictly monotonically increasing function, maximizing `L(theta)` is mathematically identical to maximizing the log-likelihood `l(theta) = ln L(theta)`:",
                "`l(theta) = Sum_{i=1}^n ln f(x_i; theta)`.",
                "Converting products into sums drastically simplifies differential calculus.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: Gaussian MLE Derivation",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Notice that the MLE estimator for variance sigma^2 divides by n, not n-1.",
              solutionSteps: [
                "Problem: For an i.i.d. sample x1, x2, ..., xn drawn from N(mu, sigma^2), derive the Maximum Likelihood Estimator for the mean parameter mu.",
                "Step 1: Write the Gaussian likelihood function:",
                "  L(mu) = Product_{i=1}^n [ 1 / (sigma * sqrt(2*pi)) ] * exp[ - (x_i - mu)^2 / (2 * sigma^2) ]",
                "  L(mu) = (2 * pi * sigma^2)^{-n/2} * exp[ - (1 / (2 * sigma^2)) * Sum_{i=1}^n (x_i - mu)^2 ]",
                "Step 2: Take the natural logarithm to form the log-likelihood l(mu):",
                "  l(mu) = - (n / 2) * ln(2 * pi * sigma^2) - [ 1 / (2 * sigma^2) ] * Sum_{i=1}^n (x_i - mu)^2",
                "Step 3: Differentiate with respect to mu and set to zero:",
                "  d l(mu) / d mu = - [ 1 / (2 * sigma^2) ] * Sum_{i=1}^n [ 2 * (x_i - mu) * (-1) ] = 0",
                "  = [ 1 / sigma^2 ] * Sum_{i=1}^n (x_i - mu) = 0",
                "Step 4: Solve for mu:",
                "  Sum_{i=1}^n x_i - n * mu = 0  =>  n * mu = Sum_{i=1}^n x_i",
                "  mu_hat_{MLE} = (1 / n) * Sum_{i=1}^n x_i = X_bar",
                "Conclusion: The Maximum Likelihood Estimator for the Gaussian mean is the sample mean X_bar.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "All of Statistics: A Concise Course in Statistical Inference",
                  authors: "Larry Wasserman",
                  year: "2004",
                  publisher: "Springer",
                  relevance: "Chapter 9: Maximum Likelihood Estimators and properties.",
                },
              ],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // MODULE 5: STATISTICAL HYPOTHESIS TESTING & CONFIDENCE INTERVALS
    // =========================================================================
    {
      id: "da-stat-module-5-inference",
      title: "Module 5: Confidence Intervals & Hypothesis Testing",
      slug: "hypothesis-testing-and-intervals",
      description:
        "Confidence intervals, Null and Alternative hypotheses, Type I and Type II errors, p-values, z-test, Student's t-test, and Chi-square goodness-of-fit / contingency tests.",
      order: 5,
      lessons: [
        {
          id: "confidence-intervals-z-t-and-chisquare-tests",
          title: "Confidence Intervals, z-Test, Student's t-Test & Chi-Square Tests",
          slug: "confidence-intervals-z-t-and-chisquare-tests",
          order: 1,
          estimatedMinutes: 34,
          tagline: "Constructing intervals, rejection regions, p-value decision rules, and two-sample statistical tests.",
          hasInteractive: false,
          hasGATE: true,
          hasPractice: true,
          cheatsheet: {
            summaryRule: "Reject Null Hypothesis H0 if test statistic falls in the critical rejection region, or equivalently if p-value <= significance level alpha.",
            keyFormulasAndRules: [
              "Confidence Interval for Mean (known sigma): X_bar ± z_{alpha/2} * (sigma / sqrt(n)). (95% uses z = 1.96; 99% uses z = 2.576).",
              "Confidence Interval for Mean (unknown sigma): X_bar ± t_{alpha/2, n-1} * (s / sqrt(n)).",
              "Type I Error alpha: P(Reject H0 | H0 is True) = Significance Level.",
              "Type II Error beta: P(Fail to Reject H0 | H0 is False). Power of Test = 1 - beta.",
              "One-Sample z-test Statistic: z = (X_bar - mu_0) / (sigma / sqrt(n)).",
              "One-Sample t-test Statistic: t = (X_bar - mu_0) / (s / sqrt(n)) with df = n - 1.",
              "Chi-Square Goodness-of-Fit: ChiSq = Sum_{i=1}^k [ (O_i - E_i)^2 / E_i ] with df = k - 1 - p.",
            ],
            examPitfalls: [
              "Failing to reject H0 does NOT prove H0 is true; it merely states that the observed sample evidence is insufficient to rule out H0 at the chosen significance level.",
              "p-value is NOT the probability that H0 is true; it is the probability of observing a test statistic at least as extreme as the one calculated, assuming H0 is true.",
            ],
          },
          sections: [
            {
              type: "explanation",
              heading: "1. The Formal Classical Testing Framework",
              body: [
                "Statistical inference bridges empirical sample data to broader population truths through rigorous confidence intervals and hypothesis tests.",
                "**The Four Outcomes of Hypothesis Testing:**",
                "1. **True Negative (Correct):** H0 is True and we Fail to Reject H0 (Confidence level `1 - alpha`).",
                "2. **Type I Error (False Alarm, alpha):** H0 is True but we Reject H0 (Significance level alpha).",
                "3. **Type II Error (Missed Detection, beta):** H0 is False but we Fail to Reject H0.",
                "4. **True Positive (Correct, Power):** H0 is False and we Reject H0 (Power of test `1 - beta`).",
                "**Selecting the Appropriate Test Statistic:**",
                "- Population variance sigma known, large sample: Use **z-test**.",
                "- Population variance sigma unknown, normal population: Use **Student's t-test**.",
                "- Comparing categorical frequency counts against expected ratios: Use **Chi-Square test**.",
              ],
            },
            {
              type: "gate-analysis",
              heading: "2. Worked Practice Problem: One-Sample z-Test & Confidence Interval",
              weightage: "2 Marks (Original Practice Problem · Modeled on GATE DA Pattern)",
              trap: "Two-tailed tests place alpha/2 probability mass in EACH tail (e.g. 0.025 in each tail for alpha = 0.05).",
              solutionSteps: [
                "Problem: A benchmark latency test on n = 36 query evaluations yields a sample mean latency of X_bar = 42.0 ms. The population standard deviation is known to be sigma = 6.0 ms. Construct a 95% confidence interval for the true mean latency mu, and test H0: mu = 40.0 ms vs H1: mu != 40.0 ms at alpha = 0.05.",
                "Step 1: Compute the Standard Error (SE) of the sample mean:",
                "  SE = sigma / sqrt(n) = 6.0 / sqrt(36) = 6.0 / 6 = 1.0 ms.",
                "Step 2: Find the 95% critical value z_{alpha/2}:",
                "  For alpha = 0.05, alpha/2 = 0.025  =>  z_{0.025} = 1.96.",
                "Step 3: Construct the 95% Confidence Interval:",
                "  CI = X_bar ± z_{alpha/2} * SE = 42.0 ± 1.96 * 1.0 = 42.0 ± 1.96",
                "  95% CI = [ 40.04 ms, 43.96 ms ].",
                "Step 4: Compute the test statistic for H0: mu = 40.0 ms:",
                "  z_stat = (X_bar - mu_0) / SE = (42.0 - 40.0) / 1.0 = 2.0 / 1.0 = +2.0.",
                "Step 5: Apply decision rule:",
                "  For a two-tailed test at alpha = 0.05, the critical rejection region is |z| >= 1.96.",
                "  Since |z_stat| = 2.0 >= 1.96, we REJECT H0.",
                "Step 6: Compute p-value:",
                "  p-value = 2 * P(Z >= 2.0) = 2 * (1 - Phi(2.0)) = 2 * (1 - 0.9772) = 2 * 0.0228 = 0.0456.",
                "  Since p-value = 0.0456 < 0.05, the result is statistically significant at alpha = 0.05.",
                "Conclusion: True mean latency is significantly different from 40.0 ms; 95% CI is [40.04, 43.96] ms.",
              ],
            },
            {
              type: "resources",
              heading: "3. References",
              sources: [
                {
                  title: "All of Statistics: A Concise Course in Statistical Inference",
                  authors: "Larry Wasserman",
                  year: "2004",
                  publisher: "Springer",
                  relevance: "Chapter 6: Confidence Intervals and Chapter 10: Hypothesis Testing and p-values.",
                },
                {
                  title: "Mathematical Statistics with Applications (7th Edition)",
                  authors: "Wackerly, Mendenhall, Scheaffer",
                  year: "2008",
                  publisher: "Cengage Learning",
                  relevance: "Chapter 10: Hypothesis Testing, Power, and Neyman-Pearson Lemma.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
